### ISSUE TITLE
Support generic user-defined classes

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.serialization#1]
It should be possible to define:

```
@Serializable class Box<T>(val value: T)
```

and the enjoy type-safe serialization of `Box(42)` and `Box("foo")` alike. This is a meta-issue to discuss design problems surrounding type-safe access to instances of serializers for generic classes.

**Comment by elizarov** [comment]
The way it should work is this in Kotlin <1.3 (w/o any language changes):

```
@Serializable data class MyData(val x: Int)
@Serializable data class Box<T>(val v: T)

val b = Bot(MyData(42))
JSON.stringify(b, Box.serializer(MyData)) // produces "{v: {x: 42}}" -- types are fully static
val c = JSON.parse("...", Box.serializer(MyData))
```

In short, the idea that generic classes shall define an `serialier(...)` function in their companion object that has as many parameters as there are generic type parameters in the class, each parameter to the `serializer` function being the corresponding serializer.

In Koltin 1.3 we can rollout a language support for serialization and redefine `JSON.parse` function like this:

```
fun <serializable T> parse(): T
```

The `serializable` modifier is going to work similarly to `reified`, but without the need for `inline`. It will plug the corresponding type-specific serializer as an additional parameter to the `parse` function behind the scenes. Inside the `parse` it could be accessed like `T::serializer`.

**Comment by sandwwraith** [comment]
Generic user classes supported (modulo bugs) in 0.3 with syntax described [here](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/runtime_usage.md#obtaining-serializers)
