### ISSUE TITLE
polymorphic serialization no longer works in JS target

### ISSUE THREAD

**Issue by DetachHead** [Kotlin/kotlinx.serialization#1000]
in 0.20.0, polymporphic serialisation worked in both JVM and JS. in 1.0.0-RC, it fails on JS targets with the following error:
```
SerializationException: Serializer for class 'Project' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
```

**To Reproduce**
run the following examples in a JS target:
https://github.com/Kotlin/kotlinx.serialization/blob/master/guide/example/example-poly-08.kt (only seems to fail when using js IR)
https://github.com/Kotlin/kotlinx.serialization/blob/master/guide/example/example-poly-09.kt

**Expected behavior**
`data` is serialized into the following string, like it does in the JVM: `{"type":"owned","name":"kotlinx.coroutines","owner":"kotlin"}`

**Environment**
 - Kotlin version: 1.4.0
 - Library version: 1.0.0-RC
 - Kotlin platforms: JVM, JS
 - Gradle version: 6.5.1

**Comment by qwwdfsad** [comment]
This is a missing piece in both KType machinery and our documentation.

Polymorphic serialization works properly, but serializer for interfaces and abstract classes cannot be found by `serializer()` function. As a workaround, you can use `format.encodeToString(Project.serializer(), data)` for serializable abstract classes and `format.encodeToString(PolymorphicSerializer(Project::class), data)` for interfaces
