### ISSUE TITLE
@SerialInfo annotations are not stored when applied to value parameters

### ISSUE THREAD

**Issue by L-Briand** [Kotlin/kotlinx.serialization#1001]
**Describe the bug**
I'm currently working on a [CBOR codec](https://github.com/L-Briand/orandja-cbor/tree/master) and i'm facing a bug with properties annotated with custom annotations. During encoding, classes have correct annotations but parameters do not have any.

In the example below `Test.parameter` should have the annotation `MyTag` while encoding.

**To Reproduce**
```kotlin
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.AbstractEncoder
import kotlinx.serialization.encoding.CompositeEncoder
import kotlinx.serialization.modules.EmptySerializersModule
import kotlinx.serialization.modules.SerializersModule

@SerialInfo
@ExperimentalSerializationApi
@Target(AnnotationTarget.CLASS, AnnotationTarget.PROPERTY, AnnotationTarget.VALUE_PARAMETER)
annotation class MyTag

@ExperimentalSerializationApi
@MyTag
@Serializable
data class Test(
    @MyTag val parameter: String
)

@ExperimentalSerializationApi
fun SerialDescriptor.print() {
    println("Descriptor : $this")
    println("Annotations : $annotations")
    (0 until elementsCount).forEach {
        println("Element $it :")
        println("- Descriptor: ${getElementDescriptor(it)}")
        println("- Annotations: ${getElementAnnotations(it)}")
    }
}

@ExperimentalSerializationApi
@InternalSerializationApi
class Codec(override val serializersModule: SerializersModule = EmptySerializersModule) : BinaryFormat {
    companion object Default : BinaryFormat by Codec()

    override fun <T> decodeFromByteArray(deserializer: DeserializationStrategy<T>, bytes: ByteArray): T =
        throw NotImplementedError()

    override fun <T> encodeToByteArray(serializer: SerializationStrategy<T>, value: T): ByteArray {
        serializer.serialize(Encoder(), value)
        return byteArrayOf()
    }
}

@ExperimentalSerializationApi
@InternalSerializationApi
class Encoder : AbstractEncoder() {
    override fun encodeValue(value: Any) = Unit
    override fun beginStructure(descriptor: SerialDescriptor): CompositeEncoder {
        descriptor.print()
        return super.beginStructure(descriptor)
    }
}

@InternalSerializationApi
@ExperimentalSerializationApi
fun main() {
    Codec.encodeToByteArray(Test.serializer(), Test("TEST"))
}
```

This snippet prints : 
```
Descriptor : Test(parameter: kotlin.String)
Annotations : [MyTag$Impl@5d5eef3d]
Element 0 :
- Descriptor: PrimitiveDescriptor(kotlin.String)
- Annotations: []
```

**Expected behavior**

Element 0 should have MyTag annotation.

**Environment**
 - Kotlin version: 1.4.0
 - Library version: 1.0.0-RC
 - Kotlin platforms: JVM
 - Gradle version: 6.1.1
 - IDE version IntelliJ IDEA 2020.1.4 (CE)
 - JVM OpenJDK 64-Bit Server VM; 11.0.8+10 amd64
 - OS Linux 5.8.0-2-manjaro

build.gradle.kts
```kotlin
plugins {
    kotlin("jvm") version "1.4.0"
    kotlin("plugin.serialization") version "1.4.0"
}

repositories {
    jcenter()
}

dependencies {
    implementation(kotlin("stdlib"))
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-core:1.0.0-RC")
}
```

**Comment by qwwdfsad** [comment]
Thanks for the self-contained repro! This indeed is a plugin bug

**Comment by sandwwraith** [comment]
The actual problem in this code that @SerialInfo annotations can be applied only for properties, not value parameters (they do not have backing fields!). And for some reason, parameters have priority over properties, so annotation is applied to incorrect target.

You should remove `AnnotationTarget.VALUE_PARAMETER` from targets list and everything should be fine.
Whether plugin should recognize annotation on value parameters, it's an open design question.

**Comment by L-Briand** [comment]
Thanks you @sandwwraith ! I didn't know :smile: 
Intellij proposed me automatically to add `AnnotationTarget.VALUE_PARAMETER` at my custom annotation from a data class. In my case it's not a big deal to remove it but it can lead to some bugs if an annotation is required to be `VALUE_PARAMETER` and `PROPERTY` at the same time. I do not have such usecase though.

**Comment by Vehmloewff** [comment]
Just to help out anyone who might arrive here in the future via googling, it is also important that the annotated classes (and their parents) be annotated with `@ExperimentalSerializationApi` instead of the IDE recommended `@OptIn(ExperimentalSerializationApi::class)`

So, in the given example, do as the OP did...

```kotlin
@ExperimentalSerializationApi
@MyTag
@Serializable
data class Test(
    @MyTag val parameter: String
)
```

...instead of this:

```kotlin
@OptIn(ExperimentalSerializationApi::class)
@MyTag
@Serializable
data class Test(
    @MyTag val parameter: String
)
```
