### ISSUE TITLE
Wrong deprecation message for JsonTransformingSerializer.writeTransform

### ISSUE THREAD

**Issue by pmiklos** [Kotlin/kotlinx.serialization#1003]
**Describe the bug**

It's rather minor but the deprecation message of JsonTransformingSerializer.writeTransform is incorrect.

**To Reproduce**

```kotlin
    @Deprecated(
        "This method was renamed to writeTransform during serialization 1.0 API stabilization, please override it instead",
        level = DeprecationLevel.ERROR
    )
    protected fun writeTransform(element: JsonElement): JsonElement = transformSerialize(element)
```

**Expected behavior**

"This method was renamed to writeTransform" should be "This method was renamed to transformSerialize"

**Comment by qwwdfsad** [comment]
Thanks for the report
