### ISSUE TITLE
Add a way to restrict generic parameter to a Serializable type

### ISSUE THREAD

**Issue by SeekDaSky** [Kotlin/kotlinx.serialization#1005]
Hi everyone

**What is your use-case and why do you need this feature?**

I am writing backend code, and I have a bunch of utility functions that needs to have a parameter that is serializable. There is currently no way (as far as I know) to do this with compile time safety without adding manually an interface to every object that is serializable, which is a bit tedious.

**Describe the solution you'd like**

I don't have a precise idea of what the technical solution might look like, but the easiest (for me) would be the use of an interface which could allow me to write functions like:
```kotlin
fun <T : Serializable> respond(serializable : T){ ... }
```
I know adding an interface to any serialized object is quite a big change and that it would "pollute" the generated objects, any other ideas that would allow me to have compile time safety are fine with me.

My current workaround is to call `serializerOrNull` on the `KClass` of the object to check if it's serializable and get it's serializer instance, which is not safe and is not the most performant solution as I have to do reflection.

Thank you for your time, have a great day!

*Edit:* after looking at some issues I saw that the best way to get a serializer dynamically was `serializer(KType)`, I removed `serializerOrNull` from my codebase.

**Comment by elizarov** [comment]
I highly recommend defining your own domain-specific interface that is implemented by appropriate classes in your domain, e.g for `fun respond` you can define a `Response` interface and declare it as `fun respond(response: Response)`. 

Does this solution work for you?

**Comment by qwwdfsad** [comment]
Also, please see my response to a similar issue and general limitations: https://github.com/Kotlin/kotlinx.serialization/issues/329#issuecomment-657675846

**Comment by SeekDaSky** [comment]
@qwwdfsad shoot! I looked for this kind of feature request but could not find it, sorry for the duplicate. As mentioned by @elizarov I'll simply implement something myself, i was just looking for something more "automatic". I get now why this was never implemented.

Thank you both for your time.
