### ISSUE TITLE
Easier data access in JsonElement

### ISSUE THREAD

**Issue by tom5079** [Kotlin/kotlinx.serialization#1006]
**What is your use-case and why do you need this feature?**
Currently, accessing data in JsonElement is quite wordy.
For example, The code that accesses `GlossSeeAlso` from
```json
{
    "glossary": {
        "title": "example glossary",
		"GlossDiv": {
            "title": "S",
			"GlossList": {
                "GlossEntry": {
                    "ID": "SGML",
					"SortAs": "SGML",
					"GlossTerm": "Standard Generalized Markup Language",
					"Acronym": "SGML",
					"Abbrev": "ISO 8879:1986",
					"GlossDef": {
                        "para": "A meta-markup language, used to create markup languages such as DocBook.",
						"GlossSeeAlso": ["GML", "XML"]
                    },
					"GlossSee": "markup"
                }
            }
        }
    }
}
```
[source](https://json.org/example.html)

is this monstrosity
```kotlin
jsonElement
  .jsonObject["glossary"]
  ?.jsonObject?.get("GlossDiv")
  ?.jsonObject?.get("GlossList")
  ?.jsonObject?.get("GlossDef")
  ?.jsonObject?.get("GlossSeeAlso")
  ?.jsonArray?.map { 
      it.jsonPrimitive.content
  }
```
<img src="https://user-images.githubusercontent.com/7948651/91075484-1e2e3f00-e679-11ea-922f-382fe43f91cb.png" width="30%"/>

**Describe the solution you'd like**

Adding CSS/jquery-like selector syntax would be great. Benchmarking [`Jsoup`'s selector-syntax](https://jsoup.org/cookbook/extracting-data/selector-syntax) might be helpful.

Example use:
```kotlin
jsonElement.select("GlossSeeAlso") // Returns all entry that has GlossSeeAlso as a key
jsonElement.select("GlossDiv GlossSeeAlso") // Returns all entry under GlossDiv that has GlossSeeAlso as a key
jsonElement.select("GlossDef > GlossSeeAlso") // Returns all entry directly under GlossDef that has GlossSeeAlso as a key
```

**Comment by elizarov** [comment]
Adding stringly-typed query sublanguage goes into stark conflict with Kotlin type-safe philosophy, but we can consider adding concise extensions. You also have an option defining them yourself. Try writing this one-liner:

```
operator fun JsonElement?.get(key: String) = this?.jsonObject?.get(key)
```

then you can write:

```
jsonElement["glossary"]["GlossDiv"]["GlossList"]["GlossDef"]["GlossSeeAlso"] // and etc
```

Does it help?

**Comment by tom5079** [comment]
That is better, but still too verbose in my opinion.
It doesn't have to be query sublanguage though,
Something like `JsonElement.findAll("GlossSeeAlso")` will also do the job.

Normally, programmers generally have a good idea what their json input looks like, so adding extra failsafe measures feels unnecessary for me.

Also, I'm not quite sure at the moment why this violates the Kotlin's type-safe philosophy as both our solutions are basically doing the same thing.

**Comment by sandwwraith** [comment]
I think we just can't write all possible extensions to concisely interact with `JsonElement` for all possible use-cases, because different cases may require different api. However, I imagine that eventually one may write an extension library, following the most popular approach, say  'Jsoup for kotlinx.serialization' or 'XPath for kotlinx.serialization'

**Comment by tom5079** [comment]
I agree.
