### ISSUE TITLE
Support of generic collections in serializer(type: Type)

### ISSUE THREAD

**Issue by aahlenst** [Kotlin/kotlinx.serialization#1008]
I'm in the process of upgrading to kotlinx-serialization 1.0.0-RC from 0.20.0. I'm using `serializer(type: Type)` **from Java** to (de)serialize JSON. While deserializing arrays, objects and primitive types works flawlessly, deserializing generic collections fails:

```kotlin
@Test
fun readListOfStrings() {
	val body = """
		["abc", "def"]
	"""
	println(Json.decodeFromString(serializer(List::class.java), body))
}
```

The exception is:

```
Expected class kotlinx.serialization.json.JsonObject as the serialized body of kotlinx.serialization.Polymorphic<List>, but had class kotlinx.serialization.json.JsonArray
kotlinx.serialization.json.internal.JsonDecodingException: Expected class kotlinx.serialization.json.JsonObject as the serialized body of kotlinx.serialization.Polymorphic<List>, but had class kotlinx.serialization.json.JsonArray
	at kotlinx.serialization.json.internal.PolymorphicKt.decodeSerializableValuePolymorphic(Polymorphic.kt:82)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:40)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:85)
```

This didn't work with 0.20.0 and earlier either. But 1.0.0-RC does now return a serializer for generic collections which it did not in previous versions, so something has changed.

Questions:

Is it expected that kotlinx.serialization can (de)serialize generic collections from Java? If yes, what am I doing wrong? Are there tests that show how to do it correctly? If it's not supposed to work, wouldn't it be appropriate to fail earlier with a more meaningful exception?

**Comment by elizarov** [comment]
It is supposed to work this (recommended) way:

```
Json.decodeFromString<List<String>>(body)
```

Alternatively, if you need to pass serialized explicitly you can do 

```
Json.decodeFromString(ListSerializer(String.serializer()), body)
```

See this section of the guide: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#constructing-collection-serializers

Does it help?

**Comment by aahlenst** [comment]
This does not really help because the API I'm implementing provides the type information only as `Class<?>`. That's why I'm using `serializer(type: Type)` and according to its javadoc that's how to do it. The sample I gave above is the shortest code to reproduce it and resembles what I'm doing in Java.

**Comment by elizarov** [comment]
If you have only `List::class` the you don't know what its type argument, without it you cannot property deserialize a list. You need either capture Java `Type` or Kotlin `KType` (with `typeOf`) to get the information about the list's generic type parameter.

**Comment by aahlenst** [comment]
Yeah, sorry for the noise. I forgot how to write Java during my vacation. Because the API wanted `Class<?>` I stuck to it instead of using `Type` (which `Class` implements) and then obtaining the `Type` with `typeOf<List<SomeObject>>().javaType` or `new ArrayList<SomeObject>() {}.getClass().getGenericSuperclass()` in plain Java. Works flawlessly now.
