### ISSUE TITLE
How to correctly implement support for polymorphic deserialization in custom format?

### ISSUE THREAD

**Issue by charleskorn** [Kotlin/kotlinx.serialization#1009]
I'm the maintainer of [kaml](https://github.com/charleskorn/kaml), a library that adds support for YAML to kotlinx.serialization.

Recently, I've had an issue raised around how kaml handles polymorphic serialization: https://github.com/charleskorn/kaml/issues/30. Currently, kaml behaves differently to the built-in JSON support when custom serializers are used with a sealed type, which is causing confusion. 

* The behaviour of kaml is: if the type's descriptor says the type is sealed, it always expects to find a discriminator (either a `type` property or a YAML tag), and then returns the type and then the remaining properties to the serializer.

* The behaviour of the built-in JSON decoder appears to be (based on [this code](https://github.com/Kotlin/kotlinx.serialization/blob/master/runtime/commonMain/src/kotlinx/serialization/json/internal/Polymorphic.kt#L61)): if the type's descriptor says the type is sealed and the serializer is a `AbstractPolymorphicSerializer`, follow the same pattern as kaml, otherwise just return the object as-is.

Should this logic (checking the serializer type) be implemented in other libraries like kaml? It seems a little odd to me that the format changes its behaviour in response to the type of serializer being used.

**Comment by sandwwraith** [comment]
Hi,

Indeed, your observation is correct — we usually recommend to check descriptor kind, not the particular instance of serializer. I think current behavior is just a leaky implementation detail — in any case, the only serializers with `PolymorphicKind.OPEN` and `PolymorphicKind.SEALED` are inheritors of `AbstractPolymorphicSerializer`, so you may think that both approaches are equivalent. It also features `findPolymorphicSerializerOrNull` method, but it is simply delegating to `serializersModule.getPolymorphic`.

However, things may get nasty if we allow custom serializers with these kinds. There's no design for them yet and they're not explicitly supported, but there are several use-cases (such as `Either` class). So it is safe to assume that you want your polymorphism logic working if it was a standard polymorphic serializer, and let the custom one perform its own logic. (cc @qwwdfsad).

**Comment by charleskorn** [comment]
Thanks for your response. 

Just to confirm, are you suggesting that I use similar logic in kaml to what the JSON decoder uses? (ie. it should also check the serializer type and change its behaviour based on that)

**Comment by sandwwraith** [comment]
Yes, it should be sufficient
