### ISSUE TITLE
SerialName for enum with Float value -> JsonDecodingException: Expected string literal with quotes

### ISSUE THREAD

**Issue by frist008** [Kotlin/kotlinx.serialization#1012]
I am trying to migrate from Gson to Kotlinx serialization. But I got not expected behavior for enum.

**To Reproduce**
```Json
[
  {
    "number": 1,
    "nameId": 1.0
  },
  {
    "number": 2,
    "nameId": 2.0
  },
  {
    "number": 3,
    "nameId": 3.0
  },
  {
    "number": 3,
    "nameId": 3.001
  }
```

Application
```Kotlin
Json {
    ignoreUnknownKeys = true
}
```

```Kotlin
@Serializable
enum class Image(
    @Transient val number: Int,
) {

    @SerialName("1.0") _001(1),
    @SerialName("2.0") _002(2),
    @SerialName("3.0") _003(3),
    @SerialName("3.001") _003m(3),
}
```

```Kotlin
data class NetworkEntity(
    @SerialName("number") override val number: Int? = null,
    @SerialName("nameId") override val imageEnum: Image? = null
)
```

**Expected behavior**
I shouldn't be getting this Exception:
> kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 40: Expected string literal with quotes.
> Use 'isLenient = true' in 'Json {}` builder to accept non-compliant JSON.
> JSON input: .....  "number": 1,
> "nameId": 1.0

I have not used isLenient for Gson.
```Kotlin
GsonBuilder() .create()
```

**Environment**
 - Kotlin version: [e.g. 1.4.0]
 - Library version: [e.g. 1.0.0-RC]
 - Kotlin platforms: [Android]
 - Gradle version: [e.g. 6.2]
 - IDE version [e.g. Android Studio 4.0.1]

**Comment by tom5079** [comment]
`Enum` values are represented as `String` in kotlinx.serialization.
Attaching double-quotes around the value of the nameId will fix the problem

```kotlin
[
  {
    "number": 1,
    "nameId": "1.0"
  },
  {
    "number": 2,
    "nameId": "2.0"
  },
  {
    "number": 3,
    "nameId": "3.0"
  },
  {
    "number": 3,
    "nameId": "3.001"
  }
]
```

You can also force the weak typing which will make it work without modifying the json.
```kotlin
Json {
  ...
  isLenient = true
  ...
}
```

**Comment by frist008** [comment]
It would be nice to configure the key type somehow. Perhaps you will add this feature in the future?

Now I can't solve this with KSerializer?

**Comment by elizarov** [comment]
You can solve it by writing a custom serializer that serializes your enums as a number. This section of the guide explains the basic principles and provides an example: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#primitive-serializer

**Comment by frist008** [comment]
Hmm... And it will probably work with a generic type. Then I think you can close the issue. Thanks to all.
