### ISSUE TITLE
A standard way to distinguish text and binary fomats

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.serialization#1015]
When serializing some complex domain objects like date and time one can use one of two representations: text representation or compact binary representation. While it is certainly possible to pick one or the other using contextual serializers, it would be convenient if a single serializer can be written in such a way that it can automatically determine what kind of format the class is being serialized to (binary or text) and pick the appropriate encoding. Note, that the solution must also integrate properly with descriptors, so it must somehow extend the context-based serialization infrastructure from this standpoint.

**Comment by sandwwraith** [comment]
Closing as not planned for now due to lack of use cases
