### ISSUE TITLE
CompilationException on extending a class with serialized generics

### ISSUE THREAD

**Issue by Sylvyrfysh** [Kotlin/kotlinx.serialization#1018]
**Describe the bug**
When overriding a value with a generic type in a subclass, the compiler cannot find the serializer for the generic type, even though it should not need the serializer.

```
e: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Serializer for element of type UUID has not been found.
To use context serializer as fallback, explicitly annotate element with @Contextual
File is unknown
```

**To Reproduce**
```
@Serializable
abstract class Base<T> {
    @Contextual abstract val test: T
}

@Serializable
class Sub(@Contextual override val test: UUID): Base<UUID>()

fun main() {
    println(Sub(UUID.randomUUID()))
}
```

Adding the Serializable annotation with any proper serializer continues to cause the issue.
Removing Contextual from the Base class and replacing it with nothing or the Transient annotation also causes the issue.

**Expected behavior**
I would expect the code to behave the same as this code:
```
@Serializable
abstract class BaseConcrete {
    @Contextual abstract val test: UUID
}

@Serializable
class SubConcrete(@Contextual override val test: UUID): BaseConcrete()

fun main() {
    println(SubConcrete(UUID.randomUUID()))
}
```

**Environment**
 - Kotlin version: 1.4.0
 - Library version: 1.0.0-RC
 - Kotlin platforms: JVM
 - Gradle version: 6.1
 - IDE version: IntelliJIDEA 2020.2.1
 - Other relevant context: JDK 1.8.0_252, 11.0.1

**Comment by Sylvyrfysh** [comment]
I found this can be fixed by replacing the Sub class extension with `class Sub(@Contextual override val test: UUID) : Base<@Contextual UUID>()`

**Comment by sandwwraith** [comment]
It's rather a design limitation than a bug: you have to specify what serializer to use on every occurrence of the type. Imagine you have `class Sub(override val test: List<@Contextual UUID>) : Base<UUID>()` or `class Sub(@Contextual override val test: List<UUID>)` or something else that is perfectly valid from the standpoint of type system. In all these cases, this is much less clear that `UUID` should also be contextual. Also see #607.

If you're too bothered and have `UUID`s all over the place, I can suggest you to use `@file:UseContextualSerialization(UUID::class)`.
