### ISSUE TITLE
Kotlin 1.4.0 with LEGACY backend and named companion objects failing JS tests

### ISSUE THREAD

**Issue by Whathecode** [Kotlin/kotlinx.serialization#1032]
**Describe the bug**
I had a serializable class in my code base with a named companion object (`companion object Factory`). When upgrading to Kotlin 1.4.0 and configuring the `IR` JavaScript backend, my compilation and unit tests succeed. However, when using the `LEGACY` backend, running _any_ `jsBrowserTest` unit test fails.

> 2020-08-31T17:47:58.819+0200 [DEBUG] [org.jetbrains.kotlin.gradle.tasks.testing] [KOTLIN] TCSM: ##teamcity[message text='31 08 2020 17:47:58.817:WARN |[reporter|]: SourceMap position not found for trace: Uncaught SerializationException: Serializer for class |'PhoneSensorMeasure|' is not found.

Given my involvement in the following old PR, I thought of removing the custom companion object name: https://github.com/Kotlin/kotlinx.serialization/pull/130

Removing the custom companion object name works as a workaround. Maybe this is related?

**To Reproduce**
Will work on small repro if time permits.

**Expected behavior**
I would have thought the `LEGACY` backend was more likely to work than the new `IR` backend. :) Due to some `@JsExport` limitations we do not yet want to upgrade to the IR backend.

**Environment**
 - Kotlin version: 1.4.0
 - Library version: 1.0.0-RC
 - Kotlin platforms: MP, JS target fails
 - Gradle version: 6.6

**Comment by sandwwraith** [comment]
Is this a complaint about new feature? :) Or I misunderstood you and named companion worked with JS legacy backend in 1.3.x, so this is a regression? I thought it didn't...

IR backend performs code generation and metadata handling in a different way, so some operations (especially 'reflective'-like) are possible only when using it and unavailable in legacy backend.

**Comment by Whathecode** [comment]
This is a regression: named companion objects worked with JS LEGACY backend.

**Comment by sandwwraith** [comment]
Got it, will investigate

**Comment by sandwwraith** [comment]
@Whathecode Can you please provide an example where named companion objects worked with 1.3 (except explicit `X.serializer()`) ?

I've wrote the following test:

```kotlin
@Serializable
class Bar {
    var x = "foo"
    companion object Factory
}

@OptIn(ImplicitReflectionSerializer::class)
@Test
fun testNamedCompanion() {
    val b = Bar()
    println(b::class.serializer())
    println(Json.stringify(b))
}
```

Both `println`s are failing with `SerializationException: Can't locate argument-less serializer for class Bar.` on 1.3.72 + 0.20.0 runtime

**Comment by sandwwraith** [comment]
There's even #226 for that. Although it's 'fixed', `0.20.0-1.4.0-rc-95` gives the same result for me...

**Comment by Whathecode** [comment]
I only use explicit serializers.

This version of the library uses a named companion object and works for JS on 1.3.72.

**Comment by jimmykane** [comment]
We might have a similar issue. If this comment does not belong here please feel free to ask for a new issue. 

Our config 

```
js(LEGACY) {
        binaries.executable()
        browser {
            commonWebpackConfig {
                cssSupport.enabled = true
            }
            webpackTask {
                output.libraryTarget = "umd"
            }
            testTask {
                useKarma {
                    useChromeHeadless()
                }
            }
        }
    }
    ```
    
When we first run the following 
- Clean 
- Build 

the build task fails on the JSBrowserTest with some assertation failures. For example

```
> Task :jsBrowserTest


com.soy.algorithms.something FAILED
    AssertionError at xxxt.kt:68

There were failing tests
```

However, if we run the build task again it succeeds.

**Comment by qwwdfsad** [comment]
We no longer support legacy backend
