### ISSUE TITLE
Docs: Serialization Guide markdown has wrong links to docs generated from source

### ISSUE THREAD

**Issue by elincoln** [Kotlin/kotlinx.serialization#1033]
**Describe the bug**
The docs generated from source aren't being linked to correctly from (some? all?) Serialization Guide markdown files.  Example: 
https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#json-elements 

The link provided in the markdown file for JsonElement is:
https://kotlin.github.io/kotlinx.serialization/kotlinx-serialization/kotlinx.serialization.json/-json-element.html

But the correct link is:
https://kotlin.github.io/kotlinx.serialization/kotlinx-serialization-core/kotlinx-serialization-core/kotlinx.serialization.json/-json-element/index.html

Related:
Overall it'd be nice if the generated docs: https://kotlin.github.io/kotlinx.serialization/kotlinx-serialization-core/kotlinx-serialization-core/index.html were more discoverable.

**Comment by sandwwraith** [comment]
cc @elizarov @qwwdfsad

**Comment by qwwdfsad** [comment]
Hi @elincoln 

Generated docs are kinda hidden for now, because the site is not yet ready. Tho linking to the not-yet-finished site is still better than broken links, I'll take care of that
