### ISSUE TITLE
Deserialize JSON with variable key

### ISSUE THREAD

**Issue by daweedm** [Kotlin/kotlinx.serialization#1037]
I'm trying to write a generic serializable class that would match the following response :

The "pluginDescriptors" key is variable. The name of the key changes relating to the name of the route I am calling.
In this case, I called the route `http://localhost:8080/api/pluginDescriptors`, therefore the key in the `_embedded` object is named `pluginDescriptors` :
```js
{
    "_embedded": {
        "pluginDescriptors": [
            {
              // ...
            }
        ]
    },
    "_links": {
        // ...
    },
    "page": {
        // ...
    }
}
```

If I call the route `http://localhost:8080/api/someEntity`, the key in the `_embedded` object would be named `someEntity` :
```js
{
    "_embedded": {
        "someEntity": [
            {
              // ...
            }
        ]
    },
    "_links": {
        // ...
    },
    "page": {
        // ...
    }
}
```

Regardless the route, the global response stays the same (except the content of `_embedded`, which depends of a generic type, see below)

For now, I have the following Serializable classes :

```kotlin

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable


@Serializable
class PagingAndSortingResponse<T> {
    @SerialName("_embedded")
    val embedded: Embedded<T>? = null

    @SerialName("_links")
    val links: Links? = null

    val page: Page? = null
```

```kotlin

import kotlinx.serialization.Serializable
import kotlinx.serialization.Serializer

@Serializable
class Embedded<T> {
    val pluginDescriptors: List<T>? = null
    //  ^-------- here
}
```
Everything works well if I keep the attribute hardcoded in the `Embedded` class. But it makes it specific to a concrete response (to the response of `http://localhost:8080/api/pluginDescriptors` in this case) . How could I write the `Embedded` definition in order to handle the deserialization in a generic way ?

Since I am using `ktor` as an HTTP client, I could write an transformer in order to change the name of the first sub property on-the-fly, but it seems to be a hackish way and I'm wondering if there is no other elegant approach to solve this.

**Comment by sandwwraith** [comment]
I think the transformer approach is actually fine. In any way, you'll need a custom serializer for it: alternative approach is to write [custom serializer](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#custom-serializers-for-a-generic-type) for `Embedded` and make a `when` over the `tSerializer: KSerializer<T>` in it trying to determine what json property to read.

You can also try to make `Embedded` abstract and use different subclasses with different properties' names, and then expose them back via some abstract method. I think we do not have currently any mechanisms for variable serial names anyway.

**Comment by daweedm** [comment]
Thanks for your response, I solved this this way : 

```kotlin
@Serializable
class PagingAndSortingResponse<T> {
    @SerialName("_embedded")
    private val embedded: Map<String, List<T>>? = null

    @SerialName("_links")
    val links: Map<String, Link>? = null

    val page: Page? = null

    val entities: List<T>?
        get() = embedded?.let {
            it[it.keys.first()]
        }
}
```
