### ISSUE TITLE
What is the best way to deserialize a list/collection of data class?

### ISSUE THREAD

**Issue by neurothew** [Kotlin/kotlinx.serialization#1048]
Hi all, I am completely new in kotlin and currenly encounter the deserialization problem, looking on the internet for few hours but i still havent found a solution.

Suppose I got the following serializable class
`data class Project(
    @SerialName("Name")
    val name: String
)
`

And then I create an external .json file like the following:
`{{"name": "alpha"}, {"name": "beta"}, {"name": "theta"}}`

and want to deserialize from it to get back a list of class Project
[Project(), Project(), Project()], how could I do so?

I dont know if my external .json file was created in right format as well, should it be
`{[{"name": "alpha"}, {"name": "beta"}, {"name": "theta"}]}` ?

could anyone point me to something that i should look at? thank you very much

**Comment by elizarov** [comment]
I think you are looking for something like `[{"name": "alpha"}, {"name": "beta"}, {"name": "theta"}]`. You can check out how lists are represented in JSON in this section of the documentation: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/builtin-classes.md#lists

Please, report here if anything does not work for you.

**Comment by neurothew** [comment]
> I think you are looking for something like `[{"name": "alpha"}, {"name": "beta"}, {"name": "theta"}]`. You can check out how lists are represented in JSON in this section of the documentation: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/builtin-classes.md#lists
> 
> Please, report here if anything does not work for you.

Thanks so much, the section helped. I had a workaround after reading it but I could not directly deserialize the json except explicitly adding a dummy key for the list. e.g. I have to add a "dummy" key such that the .json looks like:

`"""{"dummy": [{"name": "alpha"}, {"name": "beta"}, {"name": "theta"}]}"""`

Then create a parent class as following
```Kotlin
@Serializable
data class parentProject(
    @SerialName("dummy")
    val dummy: List<Project>
)

@Serializable 
data class Project(@SerialName("Name") val name: String)

// The multiple Projects can be assessed as follows:
val demoProject = Json.decodeFromString(parentProject.serializer(), string)
for (currentProject in demoProject.dummy){
    println(currentProject.name)
}
```

That worked, but I want to know if it is possible to throw away the `dummy` key? Thank you for your prompt response.

**Comment by elizarov** [comment]
Please try `Json.decodeFromString<List<Project>>(string)`

**Comment by neurothew** [comment]
> Please try `Json.decodeFromString<List<Project>>(string)`

That worked like a charm! Thank you very much!
