### ISSUE TITLE
Links in doc that point to API reference land on 404 Not found pages

### ISSUE THREAD

**Issue by LouisCAD** [Kotlin/kotlinx.serialization#1050]
Doc page: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#plugin-generated-serializer

All links pointing to the API reference land on 404 Not found pages.

Example 404 link: https://kotlin.github.io/kotlinx.serialization/kotlinx-serialization/kotlinx.serialization/-k-serializer/index.html

**Comment by sandwwraith** [comment]
Duplicate of #1033 ?

**Comment by LouisCAD** [comment]
Looks like it yes.
