### ISSUE TITLE
Compile to commonjs fails on require kotlinx-serialization-runtime-js

### ISSUE THREAD

**Issue by blazer82** [Kotlin/kotlinx.serialization#106]
I have a node application written in Kotlin and would like to include _kotlinx-serialization-runtime-js_.

It compiles just fine but fails on `require('kotlinx-serialization-runtime-js')` during runtime:

```
Error: Cannot find module 'kotlinx-serialization-runtime-js'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (…/index.js:1517:57)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
```

My **gradle** file looks like this:

```
buildscript {
    ext.kotlin_version = '1.2.31'
    ext.serialization_version = '0.4.2'

    repositories {
        mavenCentral()
        maven { url "https://kotlin.bintray.com/kotlinx" }
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlinx:kotlinx-gradle-serialization-plugin:$serialization_version"
    }
}

group 'com.example'
version '1.0-SNAPSHOT'

apply plugin: 'kotlin-platform-js'
apply plugin: 'kotlinx-serialization'

repositories {
    mavenCentral()
    maven { url "https://kotlin.bintray.com/kotlinx" }
}

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-js:$kotlin_version"
    compile "org.jetbrains.kotlinx:kotlinx-serialization-runtime-js:$serialization_version"
}

compileKotlin2Js.kotlinOptions.metaInfo = true
compileKotlin2Js.kotlinOptions.sourceMap = true
compileKotlin2Js.kotlinOptions.moduleKind = "commonjs"
compileKotlin2Js.kotlinOptions.outputFile = "node/index.js"
```

How would I go about including the module in a node project? Are there any examples yet?
Maybe just provide a node module?

Thanks!

**Comment by sandwwraith** [comment]
Doesn't [example-js](https://github.com/Kotlin/kotlinx.serialization/blob/master/example-js/build.gradle) work for you? It has `moduleKind = umd`. As far as I can see from its build output, you need to explicitly require only your `output.js` file which is built from your sources, and `kotlinx-serialziation-runtime-js.js` is automatically loaded from it if it's located in same folder.

**Comment by blazer82** [comment]
Thanks for your response. I'll check it out soon and edit this comment when done.

**Comment by blazer82** [comment]
Thanks, I got it! The example did indeed work for me and apparently I was missing this crucial part in my gradle file:

```
build.doLast {
    configurations.compile.each { File file ->
        copy {
            includeEmptyDirs = false

            from zipTree(file.absolutePath)
            into "${projectDir}/$web_path"
            include { fileTreeElement ->
                def path = fileTreeElement.path
                path.endsWith(".js") && (path.startsWith("META-INF/resources/") || !path.startsWith("META-INF/"))
            }
        }
    }
}
```

**Comment by KirkBushman** [comment]
I have the same problem: 
Error: Cannot find module 'kotlinx-serialization-runtime-js', 

but adding the last part doesn't make it work.

this is my gradle.build:

     buildscript {
         ext.kotlin_version = '1.2.51'
         ext.serialization_version = '0.6.0'

         repositories {
             jcenter()
             mavenCentral()
             maven { url "https://kotlin.bintray.com/kotlinx" }
         }
         dependencies {
            classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
            classpath "org.jetbrains.kotlinx:kotlinx-gradle-serialization-plugin:$serialization_version"
         }
      }
      
    apply plugin: 'kotlin2js'
    apply plugin: 'kotlin-dce-js'
    apply plugin: 'kotlinx-serialization'

    repositories {
        jcenter()
       mavenCentral()
       maven { url "https://kotlin.bintray.com/kotlinx" }
     }
     
     dependencies {
         compile "org.jetbrains.kotlin:kotlin-stdlib-js:$kotlin_version"
         compile "org.jetbrains.kotlinx:kotlinx-serialization-runtime-js:$serialization_version"
     }
     
     compileKotlin2Js.kotlinOptions {
          moduleKind = "commonjs"
          outputFile = "${projectDir}/node/index.js"
          sourceMap = true
         metaInfo = true
      }
     
     build.doLast {
          configurations.compile.each { File file ->
              copy {
                 includeEmptyDirs = false

                 from zipTree(file.absolutePath)
                 into "${projectDir}/node"
                 include { fileTreeElement ->
                      def path = fileTreeElement.path
                      path.endsWith(".js") && (path.startsWith("META-INF/resources/") || !path.startsWith("META-INF/"))
                  }
             }
         }
     
         copy {
             from sourceSets.main.resources.srcDirs
             into "${projectDir}/node"
         }
     }


how did you solve your problem @blazer82? did you switch commonjs?

**Comment by blazer82** [comment]
@KirkBushman I use commonjs, yes.

Check your path parameters. I see your main output goes to `${projectDir}/node`:

    outputFile = "${projectDir}/node/index.js"

and so does your module output:

    into "${projectDir}/node"

The last one should probably go into your `node_modules` path.

So, in the end you might have something like this:

```
build.doLast {
      configurations.compile.each { File file ->
          copy {
             includeEmptyDirs = false

             from zipTree(file.absolutePath)
             into "${projectDir}/node_modules"
             include { fileTreeElement ->
                  def path = fileTreeElement.path
                  path.endsWith(".js") && (path.startsWith("META-INF/resources/") || !path.startsWith("META-INF/"))
              }
         }
     }

    …
}
```

**Comment by KirkBushman** [comment]
You are right, now it works!
Thanks
