### ISSUE TITLE
Can’t add Kotlinx.Serialization to an Android Compose project successfully

### ISSUE THREAD

**Issue by Brett-Best** [Kotlin/kotlinx.serialization#1061]
**Describe the bug**
I’m unable to successfully add the Kotlinx.Serialization to my Android compose project successfully.
I’ve read the README.md of this project and tried a bunch of things but it seems likely that the problem is how I’ve configured my Gradle.

I’ve created a repo example: https://github.com/Brett-Best/KotlinSerializationExample
To view the build output that I get (note the build never fails, just seems to keep repeating the last lines of this output): https://raw.githubusercontent.com/Brett-Best/KotlinSerializationExample/master/README.md

Would appreciate some guidance on this, thanks in advance.

**To Reproduce**
Open the linked project in Android Studio and attempt to build. It will never build.

**Expected behavior**
Expected the project to build.

**Environment**
 - Kotlin version: 1.4.0
 - Library version: 1.0.0-RC (I think)
 - Kotlin platforms: JVM
 - Gradle version: 6.6.1
 - IDE version: Android Studio 4.2 Canary 10
 - Tried on macOS Big Sur 11.0 Beta (20A5364e) and Windows 10

**Comment by hfhbd** [comment]
Possible the same problem? 
See #968

**Comment by Brett-Best** [comment]
@hfhbd yes looks like it.
