### ISSUE TITLE
Java JS(IR)/Native polymorphism not working with Kotlin 1.4.10

### ISSUE THREAD

**Issue by Monkey-Maestro** [Kotlin/kotlinx.serialization#1069]
**Describe the bug**

selead, abstract, interfaces not working with native and IR JS, the same examples are working fine with Legacy JS and JVM
also declaring a custom Serializer (@Serializable with xxx) is ignored for selead, abstract, interfaces

Error: (xyz = selead, abstract, interfaces)
SerializationException: Serializer for class 'xyz' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
SerializationException: Serializer for class 'xyz' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
	at <global>.serializerNotRegistered(C)
	at <global>.serializer(C)
	at SerialisationTests.Test3(C)
	at _no_name_provided__115.invoke(C)
	at Context.<anonymous>(C)

**To Reproduce**
can be reproduced with the examples in the Guide (https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md) eg:

import kotlinx.serialization.*
import kotlinx.serialization.json.*

import kotlinx.serialization.modules.*

val module = SerializersModule {
    polymorphic(Project::class) {
        subclass(OwnedProject::class)
    }
}

val format = Json { serializersModule = module }

@Serializable
abstract class Project {
    abstract val name: String
}
            
@Serializable
@SerialName("owned")
class OwnedProject(override val name: String, val owner: String) : Project()

fun main() {
    val data: Project = OwnedProject("kotlinx.coroutines", "kotlin")
    println(format.encodeToString(data))
}    

**Expected behavior**

**Environment**
 - Kotlin version: [e.g. 1.410]
 - Library version: [e.g. 1.0.0-RC]
 - Kotlin platforms: [e.g. JS(IR), Native]
 - Other relevant context [e.g. W10, openjdk-14.0.2, ... ]

**Comment by sandwwraith** [comment]
It is a current limitation that should be properly documented (cc @qwwdfsad ). Please try `format.encodeToString(PolymorphicSerializer(Project::class), data)`. In case of sealed classes, it should work. If it doesnt, simply use `format.encodeToString(Project.serializer(), data)`

**Comment by FJerabek** [comment]
>Please try `format.encodeToString(PolymorphicSerializer(Project::class), data)`. In case of sealed classes, it should work. If it doesnt, simply use `format.encodeToString(Project.serializer(), data)`

Is there any workaround on class properties with polymorphic types ? I tried annotating the property with polymorphic, but without any result.
