### ISSUE TITLE
How to properly serializer/unserialize a non homogeneous List of objects

### ISSUE THREAD

**Issue by antanas-arvasevicius** [Kotlin/kotlinx.serialization#108]
Hi, I'm trying to serialize and unserialize a list with various objects which are objects of generic class, like `data class EventLog<T>(val guid:String, val event: Event<T>)` and Event of T can be any other @Serializable data class object.
Is there a way to somehow create a serializer which knows how to serialize/unserialize these structures?

Example which works with only one item and only to serialize? Question, how to unserialize? And how to work with arrays/lists?

```kotlin
       @Suppress("UNCHECKED_CAST")
        val serializer = EventLog.serializer(log.event.data::class.serializer()) as KSerializer<EventLog<T>>
        val json = JSON.stringify(serializer, log)
 ```

**Comment by sandwwraith** [comment]
You can use same `serializer` in `JSON.parse(serializer, someInput)`.

Worth mentioning: what you get here is not actually a generic ` KSerializer<EventLog<T>>`, it's T has concrete type of `log.event.data` type. So if in another place you have your data of different type, you need to create new `serializer`.

**Comment by antanas-arvasevicius** [comment]
How could I use the same `serializer` if in deserialization functions I do not have any variables from which I could determine serializer (eg. I had `log` object in serialization and it was possible to retrieve serializer with`log.event.data::class.serializer()`)?
