### ISSUE TITLE
Using a custom KSerializer from a commons library freezes KotlinJS in Multiplatform Projects

### ISSUE THREAD

**Issue by FelixEngl** [Kotlin/kotlinx.serialization#1086]
**Describe the bug**
When using a custom `KSerializer`, from the commons library of a MPP, to deserialize JSON-files in KotlinJS the code freezes without any feedback (e.g. exception/error-message).

**To Reproduce**
Sample code in a minimal project:      
https://github.com/FelixEngl/MPPSerialisationJSFail     

**Expected behavior**
The custom `KSerializer` deserializes the object in KotlinJS like in KotlinJVM without freezing. (see repository)

**Notes**
- This implementation worked with Kotlin 1.3.72 with kotlinx.Serialize 0.20.0 and the respective react libraries.
- It has not been tested if the bug also occurs with CBOR or PROTOBUF 
- It has not been tested if the bug also occurs in a pure KotlinJS project without MPP and a common library
- The code in the repository works with the KotlinJVM part

**Environment**
 - Kotlin version: 1.4.10
 - Library version: Plugin: 1.4.10, Framework: 1.0.0-RC
 - Kotlin platforms: Multiplatform (JS, JVM, Commons)
 - Gradle version: 6.5 and 6.6.1 (both tested)
 - IDE version (if bug is related to the IDE) Intellij IDEA 2020.2.2
 - Other relevant context: Java 11, Chrome [last version], Chrome Edge [last version]

**Comment by FelixEngl** [comment]
**Addendum**
- Cbor fails too.

**Comment by FelixEngl** [comment]
Seems like the KotlinJS-Compiler has a problem with handling the break in the when statement. After adding a label to the while and the break the code works.

**Comment by theromis** [comment]
@FelixEngl stepped on the same problem, my Kotlin js MPP just hangs on KSerializer, could you explain how you fixed this?

**Comment by theromis** [comment]
@FelixEngl does this https://github.com/FelixEngl/MPPSerialisationJSFail works for you without freezing?

**Comment by FelixEngl** [comment]
> @FelixEngl does this https://github.com/FelixEngl/MPPSerialisationJSFail works for you without freezing?

The code in https://github.com/FelixEngl/MPPSerialisationJSFail fails due to an error in the KotlinJS compiler, here is the issue: https://youtrack.jetbrains.com/issue/KT-42262
I fixed it by adding a label, i think your problem is a separate one. 

How did you override the `serialize` and `deserialize` functions?

**Comment by theromis** [comment]
@FelixEngl exactly, just running `sh gradlew jsBrowserDevelopmentRun` triggers `firefox` after 5-10 seconds with message `webpage is slowing down your browser.... stop/wait` and nothing in console.
could you check it on your side?
I'm on Lubuntu 20.10, same results on MacOS

**Comment by FelixEngl** [comment]
> @FelixEngl exactly, just running `sh gradlew jsBrowserDevelopmentRun` triggers `firefox` after 5-10 seconds with message `webpage is slowing down your browser.... stop/wait` and nothing in console.
> could you check it on your side?
> I'm on Lubuntu 20.10, same results on MacOS

The code in the repository is not working, you have to add the labels to the code like described in the ReadMe and the TODOs.

**Comment by theromis** [comment]
@FelixEngl thank you labels fixed an issuу
```diff
--- a/src/commonMain/kotlin/Id.kt
+++ b/src/commonMain/kotlin/Id.kt
@@ -47,12 +47,12 @@ object DefaultIdSerializer : KSerializer<Id<*>> {
             decoder.decodeStructure(descriptor){
                 var id: String? = null
                 //TODO: add label to fix code
-                while (true){
+                loop@ while (true){
                     when(val index = decodeElementIndex(descriptor)){
                         CompositeDecoder.DECODE_DONE -> {
                             println("break")
                             //TODO: add label to fix code
-                            break
+                            break@loop
                         }
                         0 -> id = decodeStringElement(descriptor, index)
                         else -> throw SerializationException("Unkown index $index")
```
