### ISSUE TITLE
Debugging generated code

### ISSUE THREAD

**Issue by StokeMasterJack** [Kotlin/kotlinx.serialization#109]
Where does the serialization-plugin put the generated code? I am not able to access (or step thru) the generated code, making debugging difficult.

**Comment by sandwwraith** [comment]
Unfortunately, there's no "place for generated code" at all. Serializer plugin emits bytecode instructions directly in the compiler output. So what you can do is either decompile `.class` files or use "Show Kotlin bytecode" action in IDEA (assuming you have plugin installed)
