### ISSUE TITLE
Toml support

### ISSUE THREAD

**Issue by smallshen** [Kotlin/kotlinx.serialization#1092]
**What is your use-case and why do you need this feature?**
there are a lot of places uses toml, just like json or yaml(already have)

**Describe the solution you'd like**

I haven't look in to the kotlin.serialization APIs to make custom serializer. but it would great to have official support

**Comment by akuleshov7** [comment]
Working on it's **native** implementation for Kotlin: https://github.com/akuleshov7/ktoml

**Comment by Peanuuutz** [comment]
Almost done: [tomlkt](https://github.com/Peanuuutz/tomlkt).

I haven't publish to maven yet, and there's much to document, so DON'T `implementation` until everything is ready. 😺

**Comment by MihaelBercic** [comment]
> Working on it's **native** implementation for Kotlin: https://github.com/akuleshov7/ktoml First release is done to Maven central already. It partially supports parsing and fully supports deserialization.
> 
> UPD: current version is quite stable and already used by the community - welcome to use it

Awesome work!
Any idea whether this will ever be merged / would you let this repo adapt it?

**Comment by akuleshov7** [comment]
> Any idea whether this will ever be merged
I cannot even imagine how these guys from kotlinx are busy. So I wouldn't expect the adoption in the nearest future.

Only in one single [ktoml](https://github.com/akuleshov7/ktoml) we have got a feedback from a **dozen** of developers, got 5 contributors/reviewers, spent mostly a half of a year on testing and development. And still polishing work is in progress...

**Comment by MihaelBercic** [comment]
> > Any idea whether this will ever be merged
> > I cannot even imagine how these guys from kotlinx are busy. So I wouldn't expect the adoption in the nearest future.
> 
> Only in one single [ktoml](https://github.com/akuleshov7/ktoml) we have got a feedback from a **dozen** of developers, got 5 contributors/reviewers, spent mostly a half of a year on testing and development. And still polishing work is in progress...

Understood, thank you for the reply. Awesome work!

**Comment by sandwwraith** [comment]
We don't have plans to merge more formats in this repository; I think the way it works now — with the list of community-supported formats — is the most optimal.

**Comment by sschuberth** [comment]
For the record, there's also https://github.com/Peanuuutz/tomlkt.
