### ISSUE TITLE
ProtobufDecodingException: Unsupported start group or end group wire type

### ISSUE THREAD

**Issue by meavydev** [Kotlin/kotlinx.serialization#1097]
**Describe the bug**
We are serialising using ProtoBuf so we can send it via Kinesis.
Serialising our GeoLocation produces a bad byte stream which crashes in Python and once we added a test to try decoding the byte stream in Kotlin, it also crashes.

Crash:
```
Process: com.navenio.clevelandapp, PID: 8741
kotlinx.serialization.protobuf.internal.ProtobufDecodingException: Unsupported start group or end group wire type: 3
	at kotlinx.serialization.protobuf.internal.ProtobufReader.skipElement(ProtobufReader.kt:47)
	at kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeElementIndex(ProtobufDecoding.kt:207)
	at com.navenio.clevelandapp.ui.main.model.KinesisData$$serializer.deserialize(Unknown Source:62)
	at com.navenio.clevelandapp.ui.main.model.KinesisData$$serializer.deserialize(KinesisData.kt:8)
	at kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:174)
	at kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:164)
	at kotlinx.serialization.protobuf.ProtoBuf.decodeFromByteArray(ProtoBuf.kt:138)
	at com.navenio.clevelandapp.ui.main.model.Location.toBytes(Location.kt:121)
	at com.navenio.clevelandapp.ui.main.LocatingActivity$sendKinesisLocationStream$1.invokeSuspend(LocatingActivity.kt:180)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

```
Code snippets / gradle file sections:
```
classpath 'com.android.tools.build:gradle:4.0.1'
classpath "org.jetbrains.kotlin:kotlin-serialization:1.4.10"
...

implementation "org.jetbrains.kotlinx:kotlinx-serialization-core:1.0.0-RC2" // JVM dependency
implementation "org.jetbrains.kotlinx:kotlinx-serialization-protobuf:1.0.0-RC2"

...
```

```
private var geoLocationData: KinesisData<GeoLocationData>? = null

fun toBytes(): ByteArray {
	val bytes = ProtoBuf.encodeToByteArray(geoLocationData)
	val test = ProtoBuf.decodeFromByteArray<KinesisData<GeoLocationData>>(bytes)
	return bytes
}

@Serializable
data class GeoLocationData(
	@ProtoNumber(1)
	val latitude: Double,

	@ProtoNumber(2)
	val longitude: Double,

	@ProtoNumber(3)
	val accuracyMtrs: Double,

	@ProtoNumber(4)
	val direction: Double,

	@ProtoNumber(5)
	val provider: String,

	@ProtoNumber(6)
	val timestamp: Long,

	@ProtoNumber(7)
	val speed: Float,

	@ProtoNumber(8)
	val altitude: Double,

	@ProtoNumber(9)
	val bearing: Float
)

...   

@Serializable
data class KinesisData<T>(
    @ProtoNumber(1)
    val type: String,

    @ProtoNumber(4)
    val payload: T,

    @ProtoNumber(2)
    val identityId: String = Utils.getAwsIdentityId(),

    @ProtoNumber(3)
    val timeStamp: Long = System.currentTimeMillis()
)
```
**To Reproduce**
Sample byte stream:
590a0b47656f4c6f636174696f6e224309c85b53c5f93c494011aa5db818a82910c0190000008093982b402100000000000000002a0347505330cf9de9fbcb2e3d00000000410000006066f671404d0000000018c1a5e9fbcb2e

**Expected behavior**
Actually produce a valid byte stream

**Environment**
 - Kotlin version: 1.4.10
 - Library version: 1.0.0-RC2
 - Kotlin platforms: Android
 - Gradle version: 6.1.1

**Comment by meavydev** [comment]
Just for more info, the Json version works OK, but ProtoBuf to hex fails the same was as the bytes.
        val jsonString = Json.encodeToString(geoLocationData)
        val testJson = Json.decodeFromString<KinesisData<GeoLocationData>>(jsonString)
        val hexString = ProtoBuf.encodeToHexString(geoLocationData)
        val testHex = ProtoBuf.decodeFromHexString<KinesisData<GeoLocationData>>(hexString)
        val bytes = ProtoBuf.encodeToByteArray(geoLocationData)
        val test = ProtoBuf.decodeFromByteArray<KinesisData<GeoLocationData>>(bytes)
So testJson decodes Ok, but testHex fails.

**Comment by sandwwraith** [comment]
Can you provide an actual data that produces such a byte stream?

**Comment by sandwwraith** [comment]
Actually, if I change your data to `0a0b47656f4c6f636174696f6e224309c85b53c5f93c494011aa5db818a82910c0190000008093982b402100000000000000002a0347505330cf9de9fbcb2e3d00000000410000006066f671404d0000000018c1a5e9fbcb2e` (removing first '59' byte), it is decoded successfully. 

Since protobuf encoding is deterministic, it should always starts with '0a' — `@ProtoNumber(1) val type: String` property. Tests on my side confirm this. So I assume you have error somewhere else.

**Comment by meavydev** [comment]
We have given up on KotlinX ProtoBuf and gone to Google ProtoBuf which
works.
Having said that, I have supplied the complete definitions for the code
which can't de-serialise something generated by KotlinX, then I feel it's
something we are generating, when I have shown how the byte stream is being
generated, is not likely to be our side.

**Comment by JakeWharton** [comment]
59 is hex for 89. The remaining hex is 178 characters long (89 bytes). Root message encodings are not length-prefixed so the 59 must be removed. If you are dealing with length-prefixed data (usually as a result of streaming) you need to read off the length to determine when the data ends and pass _solely_ the data part to the decoder.

**Comment by meavydev** [comment]
We aren't serialising a stream.
It's just encoding the data class to a ProtoBuf byte stream, that I gave in
this issue, so calling :
val bytes = ProtoBuf.encodeToByteArray(geoLocationData)
Where geoLocationData is:
       private var geoLocationData: KinesisData<GeoLocationData>? = null
As shown above.

**Comment by meavydev** [comment]
Perhaps I should say we were encoding Wifi data and BLE data using the same ProtoBuf.encodeToByteArray() calls, but only the GeoLocationData was failing.

**Comment by digitalheir** [comment]
Something is wrong with Protobuf parser. I have encoded an object with `org.jetbrains.kotlinx:kotlinx-serialization-protobuf:1.3.2`, but can't decode it with the same lib:

```
Exception in thread "main" kotlinx.serialization.protobuf.internal.ProtobufDecodingException: Unsupported start group or end group wire type: 4
	at kotlinx.serialization.protobuf.internal.ProtobufReader.skipElement(ProtobufReader.kt:47)
	at kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeElementIndex(ProtobufDecoding.kt:225)
```

However, command-line tool parses the object correctly.

```
echo 0a08d183d0b7d183d18112046e6f756e1a075275737369616e22027275320b0a095bcb88757aca8a735d32f2011a0f52752dd183d0b7d183d1812e6f67672a5368747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f642f64662f52752d2544312538332544302542372544312538332544312538312e6f676732820168747470733a2f2f75706c6f61642e77696b696d656469612e6f72672f77696b6970656469612f636f6d6d6f6e732f7472616e73636f6465642f642f64662f52752d2544312538332544302542372544312538332544312538312e6f67672f52752d2544312538332544302542372544312538332544312538312e6f67672e6d70335a05417564696f | xxd -r -p | protoc --decode_raw
```
``` 
1: "\321\203\320\267\321\203\321\201"
2: "noun"
3: "Russian"
4: "ru"
6 {
  1: "[\313\210uz\312\212s]"
}
6 {
  3: "Ru-\321\203\320\267\321\203\321\201.ogg"
  5: "https://upload.wikimedia.org/wikipedia/commons/d/df/Ru-%D1%83%D0%B7%D1%83%D1%81.ogg"
  6: "https://upload.wikimedia.org/wikipedia/commons/transcoded/d/df/Ru-%D1%83%D0%B7%D1%83%D1%81.ogg/Ru-%D1%83%D0%B7%D1%83%D1%81.ogg.mp3"
  11: "Audio"
}
```
