### ISSUE TITLE
SerializationException in  iOS Only

### ISSUE THREAD

**Issue by vb-hp** [Kotlin/kotlinx.serialization#1103]
**Unable to serialise the classes with 1.0.0-RC2 only in IOS**.. 
 

**Expected behavior**
- When it works in Android, Expected that it should work in iOS

**Environment**
 - Kotlin version: 1.4.10-release-IJ2020.2-1
 - Library version: 
                           serialization = "1.0.0-RC2"
 - Kotlin platforms: Android/IOS multiplatform
 - Gradle version: 4.0.1
 - IDE version 
                     IntelliJ IDEA 2020.2.2 (Community Edition)
                     Build #IC-202.7319.50, built on September 15, 2020
 
 - iOS 13.3  Simulator

Here is the detailed info:
IDEA Version:
            IntelliJ IDEA 2020.2.2 (Community Edition)
            Build #IC-202.7319.50, built on September 15, 2020
 sample code:

            interface IElement{
}

            @Serializable
            @SerialName("Item")
            data class ElementImpl:IElement

            class JsonExporter {
                suspend fun export(): String {
                    val module = SerializersModule {
                        polymorphic(IElement::class, ElementImpl::class, ElementImpl.serializer())
                    }

                    val elementsList<ElementImpl> = ...
                    val jsonString = Json { serializersModule = module }.encodeToString(elementsList)
                    return jsonString
                }
            }

Multiplatform setup:
            dependencies {
        //others
        classpath "org.jetbrains.kotlin:kotlin-serialization:1.4.10"
    }

    plugins {
    id 'org.jetbrains.kotlin.multiplatform' version '1.4.10'
    id 'org.jetbrains.kotlin.plugin.serialization' version '1.4.10'
    }

    sourceSets {
        commonMain {
            dependencies {
                //serialization
                implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:1.0.0-RC2"
            }
        }
    }

Error:
Exception doesn't match @Throws-specified class list and thus isn't propagated from Kotlin to Objective-C/Swift as NSError.
It is considered unexpected and unhandled instead. Program will be terminated.
Uncaught Kotlin exception: kotlinx.serialization.SerializationException: Serializer for class 'IElement' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
On Kotlin/Native explicitly declared serializer should be used for interfaces and enums without @Serializable annotation
 

External Libraries that got added transitively after i added "kotlinx-serialization-json:1.0.0-RC2" 
Gradle: org.jetbrains.kotlinx:kotlinx-serialization-core-iosx64:klib:1.0.0-RC2
Gradle: org.jetbrains.kotlinx:kotlinx-serialization-core-jvm:1.0.0-RC2@jar
Gradle: org.jetbrains.kotlinx:kotlinx-serialization-core-metadata:1.0.0-RC2
Gradle: org.jetbrains.kotlinx:kotlinx-serialization-json-iosx64:klib:1.0.0-RC2
Gradle: org.jetbrains.kotlinx:kotlinx-serialization-json-jvm:1.0.0-RC2@jar
Gradle: org.jetbrains.kotlinx:kotlinx-serialization-json-metadata:1.0.0-RC2

**Comment by sandwwraith** [comment]
Hi, 
do you have stacktrace available?

Also, are you sure that your `elementsList` is `List<ElementImpl>`, not `List<IElement>`? If it is the latter, please try `encodeToString(ListSerializer(PolymorphicSerializer(IElement::class)), elementsList`. This is a current limitation of Native platform – polymorphic serializer should be stated explicitly. (See also #1069)

**Comment by vb-hp** [comment]
@sandwwraith  thanks for pointing out correctly.  closing it
