### ISSUE TITLE
Serializer for class is not found even marked the class as @Serializable 

### ISSUE THREAD

**Issue by seventhmoon** [Kotlin/kotlinx.serialization#1105]
**Describe the bug**

**To Reproduce**
Attach a code snippet or test data if possible.

Having a data class JwtResult
```
@Keep
@Serializable
data class JwtResult(
        val nonce: String,
        val ctsProfileMatch: Boolean,
        val basicIntegrity: Boolean
)
```

and trying to parse the Json to JwtResult.class by
`val returnedPayload = Json { ignoreUnknownKeys = true }.decodeFromString<JwtResult>(decodedPayload)
`

Exception was thrown in release build (minifyEnabled), but not debug build.
Seem the class was gone during the build process.

> Serializer for class 'JwtResult' is not found. Mark the class as @Serializable or provide the serializer explicitly.
> kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered

**Expected behavior**
successfully parsing the JSON

**Environment**
 - Kotlin version: 1.4.10
 - Library version: 1.4.10
 - Kotlin platforms: Android
 - Gradle version: 6.6.1
 - IDE version (if bug is related to the IDE) Android Studio 4.2 Canary 12
 - Other relevant context [e.g. OS version, JRE version, ... ]

**Comment by Arutyun2312** [comment]
Try this:
`val returnedPayload = Json { ignoreUnknownKeys = true }.decodeFromString(JwtResult.serializer(), decodedPayload)`

**Comment by pdvrieze** [comment]
This seems to be a proguard configuration problem. The suggested solution should fix it as it certainly makes a static reference to the serializer. However decodeFromString should be inline reified and do this too.

**Comment by seventhmoon** [comment]
Yes. I believe it is an issue from AAPT.

**Comment by webfrea-k** [comment]
Stumbled upon this one as well. Downgraded the version to 1.0.0-RC (was RC2) and the issue disappeared.

**Comment by qwwdfsad** [comment]
It seems to be an Android issue. Could you please provide a reproducing project with your R8 configuration?

**Comment by seventhmoon** [comment]
https://github.com/seventhmoon/hello-kotlin-serialization

**Comment by seventhmoon** [comment]
🤦‍♂️ It is fixed by adding the following the instruction about proguard from readme.md
I was expecting the `@Keep` annotation will handle this well.

> -keepattributes *Annotation*, InnerClasses
> -dontnote kotlinx.serialization.SerializationKt
> -keep,includedescriptorclasses class com.yourcompany.yourpackage.**$$serializer { *; } # <-- change package name to your app's
> -keepclassmembers class com.yourcompany.yourpackage.** { # <-- change package name to your app's
>     *** Companion;
> }
> -keepclasseswithmembers class com.yourcompany.yourpackage.** { # <-- change package name to your app's
>     kotlinx.serialization.KSerializer serializer(...);
> }

**Comment by AndresTorrico09** [comment]
I had same issue that yours! Serializables data clases seemed dissapear only during build release and I got the same error.
In my case, I just added @Keep anotation and works perfectly!!! 
Thank you very much for open this issue!! :)

**Comment by gandrewstone** [comment]
Note, you will get this error if you have not added serializations to your gradle plugins section:

plugins {
    kotlin("plugin.serialization") version "1.4.31"
}

**Comment by sandwwraith** [comment]
I assume this can be closed now

**Comment by p4ulor** [comment]
For anyone having issues using this in android studio, check [gradle website](https://plugins.gradle.org/plugin/org.jetbrains.kotlin.plugin.serialization)
Get the latest version and use " instead of '
Like:
`id "org.jetbrains.kotlin.plugin.serialization" version "1.6.0-RC"`
And remove comments (specially if they have links) near the build statements. That can interfere according to my tests.

Finally, try using other grade JDK's by going to gradle settings. It's probably best to use Android's. I've been trying on this issue for 5 hours. Yes.

**Comment by jmarks213** [comment]
I ran into this issue recently after I had refactored my android apps' package in a kotlin multiplatform project.  I needed to add rules to keep the serializers from _both_ the androidApp package _and_ the core library.  My proguard looks something like:

`-keepattributes Annotation, InnerClasses
-dontnote kotlinx.serialization.SerializationKt
-keep,includedescriptorclasses class com.androidApp.package.$$serializer { ; } # <-- change package name to your app's
-keepclassmembers class com.androidApp.package. { # <-- change package name to your app's
*** Companion;
}
-keepclasseswithmembers class com.androidApp.package.* { # <-- change package name to your app's
kotlinx.serialization.KSerializer serializer(...);
}
-keep,includedescriptorclasses class com.kmp.core.$$serializer { ; } # <-- change package name to your app's
-keepclassmembers class com.kmp.core. { # <-- change package name to your app's
*** Companion;
}
-keepclasseswithmembers class com.kmp.core.* { # <-- change package name to your app's
kotlinx.serialization.KSerializer serializer(...);
}`

**Comment by cyb3rko** [comment]
For those where the solutions above were not working.
Here's what I used (taken from this issue here and [StreetComplete](https://github.com/streetcomplete/StreetComplete/blob/1cc0d3338ce94e2ee6c0f66c99a58babf5826df1/app/proguard-rules.pro#L36-L58)):

```pro
-keepattributes Annotation, InnerClasses
-dontnote kotlinx.serialization.AnnotationsKt
-dontnote kotlinx.serialization.SerializationKt

# Keep Serializers

-keep,includedescriptorclasses class com.company.package.**$$serializer { *; }
-keepclassmembers class com.company.package.** {
    *** Companion;
}
-keepclasseswithmembers class com.company.package.** {
    kotlinx.serialization.KSerializer serializer(...);
}

# When kotlinx.serialization.json.JsonObjectSerializer occurs

-keepclassmembers class kotlinx.serialization.json.** {
    *** Companion;
}
-keepclasseswithmembers class kotlinx.serialization.json.** {
    kotlinx.serialization.KSerializer serializer(...);
}
```
