### ISSUE TITLE
Serialization with kotlinx.collections.immutable/persistent classes

### ISSUE THREAD

**Issue by Alddar** [Kotlin/kotlinx.serialization#1114]
Hi, I tried using kotlinx.collections.immutable/persistent as mentioned in issue #635 and created a custom serializer for persistent list:

```
@Serializer(forClass = PersistentList::class)
@Polymorphic
class PersistentListSerializer<T>(private val dataSerializer: KSerializer<T>) : KSerializer<PersistentList<T>> {
    private class PersistentListDescriptor<T> : SerialDescriptor by serialDescriptor<List<T>>() {
        @ExperimentalSerializationApi
        override val serialName: String = "kotlinx.serialization.immutable.persistentList"
    }
    override val descriptor: SerialDescriptor = PersistentListDescriptor<T>()
    override fun serialize(encoder: Encoder, value: PersistentList<T>) {
        return ListSerializer(dataSerializer).serialize(encoder, value.toList())
    }
    override fun deserialize(decoder: Decoder): PersistentList<T> {
        return ListSerializer(dataSerializer).deserialize(decoder).toPersistentList()
    }
}
```

But when I run it, I get the error `Class 'SmallPersistentVector' is not registered for polymorphic serialization in the scope of 'PersistentList'.
Mark the base class as 'sealed' or register the serializer explicitly.`

I read the [Documentation](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md), but I see no way to get this to work, because SmallPersistentVector is marked internal, so I cannot declare it explicitly.

Is there any workaround, that would fix this?

Thanks.

**Comment by sandwwraith** [comment]
You don't need `@Polymorphic`, likely. You serializer should work with any interface implementation. 
You also should apply it in proper way: using `@Serializable(PersistentListSerializer::class)` on a property. Have you done this?
