### ISSUE TITLE
Allowing length constraints for arrays and lists when deserializing

### ISSUE THREAD

**Issue by TorRanfelt** [Kotlin/kotlinx.serialization#1119]
**What is your use-case and why do you need this feature?**
When deserializing it would be great to be able to limit the lengths of arrays with a minimum and maximum length.
I have a use case where users and 3rd-party-systems can create a file that we then import, Certain array needs to be of a certain length. To ensure this we have to go through them all (there are many hundreds).

**Describe the solution you'd like**
```
    // Only 2.
    @Length(2)
    val foo: DoubleArray = DoubleArray(2)

    // 2 to 4.
    @Length(2, 4)
    val bar: DoubleArray = DoubleArray(2)
```

Even better if setting the length made a default value unnecessary:

```
    @Length(2)
    val foo: DoubleArray = DoubleArray(2)

   // or

  const val foobar = 2

   @Length(foobar)
    val foo: DoubleArray = DoubleArray(foobar)
```

could become

```
    @Length(2)
    val foo: DoubleArray // = DoubleArray(2) will be implicit.
```

**Comment by sandwwraith** [comment]
Any validation-like annotations are currently a non-goal of the library. You can write any assertions you like in the `init {}` block of the class (it is called after deserialization) or implement your format which will handle such annotations.
