### ISSUE TITLE
Provide consumer Proguard rules for Android

### ISSUE THREAD

**Issue by ntsik** [Kotlin/kotlinx.serialization#1121]
Android provides a way for libraries to package their own Proguard rules such that users of the library don't need to add rules explicitly. Having consumer rules available simplifies the upgrade process (devs currently need to remember to upgrade the Proguard rules alongside the library version).

**Comment by sandwwraith** [comment]
This can't be done fully on library's side, unfortunately — some proguard rules have to be rewritten using an actual package name of the application

**Comment by ntsik** [comment]
I had a feeling that might be an impetus, though I wasn't sure whether there was some way to work around that. Maybe adding an annotation to the generated code that Proguard can target? (I'm not very familiar with the inner workings of the library or Proguard, so not sure how feasible it would actually be.)

**Comment by ArcticLampyrid** [comment]
#### One possible solution
Mark the gen code with specific annotations and add rules to keep all the classes with annotations

**Comment by ArcticLampyrid** [comment]
In fact, android defines [`Keep` annotation](https://developer.android.com/reference/kotlin/androidx/annotation/Keep)
Of course, the pre-defined annotation is android-only, we need to define it by ourselves

**Comment by ArcticLampyrid** [comment]
My rules:
```proguard
-keepattributes *Annotation*, InnerClasses
-dontnote kotlinx.serialization.AnnotationsKt
-keepclassmembers @kotlinx.serialization.Serializable class ** {
    *** Companion;
}
-if @kotlinx.serialization.Serializable class **
-keepclassmembers class <1>$Companion {
    kotlinx.serialization.KSerializer serializer(...);
}
-keepclasseswithmembers class **$$serializer {
    *** INSTANCE;
}
```
See Also #1129

**Comment by Whathecode** [comment]
Note that [the reason they _weren't_ bundled yet is](https://github.com/Kotlin/kotlinx.serialization#android):

> The following configuration keeps serializers for all serializable classes that are retained after shrinking.
> ...
> In case you want to exclude serializable classes that are used, but never serialized at runtime, you will need to write custom rules with narrower [class specifications](https://www.guardsquare.com/manual/configuration/usage).

But arguably that's enough of an edge case to simply apply the generic rules by default. You should consider the tradeoff with how difficult it potentially is to remove the default bundled rules (I don't know), and possibly document that as well.

**Comment by sandwwraith** [comment]
I've looked at current suggested proguard rules, and it seems that most of them don't include an application package indeed. So yes, embedding rules is possible. And of course, I would be happy to see your PR!

**Comment by sandwwraith** [comment]
Also pls take a look at this comment: https://github.com/Kotlin/kotlinx.serialization/issues/2050#issuecomment-1274445927
It seems that full mode needs additional rules

**Comment by LouisCAD** [comment]
Is this issue fully resolved now since #2092 has been merged?

**Comment by LouisCAD** [comment]
Wait, I think we only need for it to be released. Anything preventing it?

**Comment by sandwwraith** [comment]
@LouisCAD Yes, it should be available in the next release. We plan it shortly after Kotlin 1.8.0 (there's #2111 to be reviewed, and there's Christmas and New Year, so....)
