### ISSUE TITLE
Kotlinx Serialization with GraalVM Native Images

### ISSUE THREAD

**Issue by kdabir** [Kotlin/kotlinx.serialization#1125]
This may not necessarily be bug, any reference in documentation would be helpful. When compiling the example as per the [blog announcement](https://blog.jetbrains.com/kotlin/2020/10/kotlinx-serialization-1-0-released/)

```kotlin
@Serializable
data class Project(
   val name: String,
   val owner: Account,
   val group: String = "R&D"
)

@Serializable
data class Account(val userName: String)

val moonshot = Project("Moonshot", Account("Jane"))
val cleanup = Project("Cleanup", Account("Mike"), "Maintenance")

fun main() {
   val string = Json.encodeToString(listOf(moonshot, cleanup))
   println(string)
 
   val projectCollection = Json.decodeFromString<List<Project>>(string)
   println(projectCollection)
}
 ```

it works with Gradle `run` task (`application` plugin applied). However When I convert application to a graalvm native image, the compilation succeeds (and binary native image is generated) but when I run the native image, I get the following error:

```
Exception in thread "main" kotlinx.serialization.SerializationException: Serializer for class 'Project' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
        at kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered(Platform.common.kt:91)
        at kotlinx.serialization.internal.PlatformKt.platformSpecificSerializerNotRegistered(Platform.kt:29)
        at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt:59)
        at kotlinx.serialization.SerializersKt.serializer(Unknown Source)
        at kotlinx.serialization.SerializersKt__SerializersKt.builtinSerializerOrNull$SerializersKt__SerializersKt(Serializers.kt:79)
        at kotlinx.serialization.SerializersKt__SerializersKt.serializerByKTypeImpl$SerializersKt__SerializersKt(Serializers.kt:69)
        at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt:54)
        at kotlinx.serialization.SerializersKt.serializer(Unknown Source)
```

**To Reproduce**
Just run compile the example using graalvm native image.

**Expected behavior**
Since I assume, `kotlinx.serialization` does not use reflection at runtime, the native image should have worked properly.

If there is something needed in reflection config, please update the docs.

**Environment**
 - Kotlin version: e.g. 1.4.10
 - Library version: e.g. 1.0.0
 - Kotlin platforms: JVM
 - Gradle version: 6.6.1
 - GraalVM: 20.2.0

**Comment by qwwdfsad** [comment]
Thanks!

>Since I assume, kotlinx.serialization does not use reflection at runtime,

`kotlinx.serialization` uses reflection is exactly one place -- `serializer()` function to lookup a serializer. 
This function is used in `reified` methods that do not accept serializer as a parameter.
We are going to change that soon (around Kotlin 1.4.30), but now as a temporary workaround I'd suggest to use `Json.encodeToString(ListSerializer(Project.serializer()), listOf(moonshot, cleanup))` and `Json.decodeFromString(ListSerializer(Project.serializer(), string)` respectively.

**Comment by kdabir** [comment]
Thanks @qwwdfsad for quick response. I can confirm that the workaround works with GraalVM Native Image 👍 

Looking forward for kotlin 1.4.30 though :)

**Comment by nanodeath** [comment]
Just ran into this, and the workaround is mildly annoying -- can we keep this open until 

> We are going to change that soon

this happens? Thanks!

**Comment by rescribet** [comment]
Just bumped into this while using ktor client, tried to add the serializer manually, but that still fails with 'serializer not found'

```kotlin
val serializer = Json {
    serializersModule = SerializersModule {
        contextual(MySerializableClass::class, MySerializableClass.serializer())
    }
}

val client = HttpClient(CIO) {
    install(JsonFeature) {
        serializer = KotlinxSerializer(serializer)
    }
}

val data = client.get<HttpResponse>("...").receive<MySerializableClass>()
```

**Comment by qwwdfsad** [comment]
It will be fixed with #1348, hopefully in 1.8.0

**Comment by Scui1** [comment]
> `kotlinx.serialization` uses reflection is exactly one place -- `serializer()` function to lookup a serializer. This function is used in `reified` methods that do not accept serializer as a parameter. We are going to change that soon (around Kotlin 1.4.30), but now as a temporary workaround I'd suggest to use `Json.encodeToString(ListSerializer(Project.serializer()), listOf(moonshot, cleanup))` and `Json.decodeFromString(ListSerializer(Project.serializer(), string)` respectively.
I just used graalvms [tracing agent](https://www.graalvm.org/22.0/reference-manual/native-image/Agent/) which generated a config for me that works without this ugly workaround. I suspect this is the part that's making it work:
`{
    "name":"package.name.YourClassName",
    "fields":[{"name":"Companion"}]
  },
  {
    "name":"package.name.YourClassName$Companion",
    "methods":[{"name":"serializer","parameterTypes":[] }]
  },`

**Comment by thombergs** [comment]
I can confirm that @Scui1's suggestion above works. When you add the above JSON snippet (wrapped in an array) to, e.g. `META-INF/native-image/groupid/artifactid/reflect-config.json` (see [GraalVM docs](https://www.graalvm.org/22.3/reference-manual/native-image/metadata/#specifying-reflection-metadata-in-json)), you don't need to specify the serializer manually anymore.

Or, if you're using Spring, you can register your `@Serializable` classes like this:

```kotlin
class RuntimeHints : RuntimeHintsRegistrar {
    override fun registerHints(hints: RuntimeHints, classLoader: ClassLoader?) {
        hints.reflection()
            .registerField(YourSerializable::class.java.getField("Companion"))
        hints.reflection()
            .registerMethod(YourSerializable.Companion::class.java.getMethod("serializer"), ExecutableMode.INVOKE)
       }
}
```
