### ISSUE TITLE
Meta-annotation for specifying a serializer

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.serialization#1127]
It would be nice to have the ability to declare user-specific meta-annotations similar to how `@Polymorphic` is an alias for `@Serializable(with = PolymorphicSerializer::class)` and `@Contextual` is an alias for `@Serializable(with = ContextualSerializer::class)`.

What's more important, we can then pass additional parameters there to provide even more customizable serializers, for example:
```
@DateSerializer(format = "dd/MM/yyy")
val date: Date
```

An example is reported in our Slack: https://kotlinlang.slack.com/archives/C7A1U5PTM/p1602180883071300

**Comment by e5l** [comment]
We would like to have this feature for the new locations implementation https://youtrack.jetbrains.com/issue/KTOR-1165

**Comment by sandwwraith** [comment]
Closing as fixed with `@MetaSerializable` (although it has slightly different design)
