### ISSUE TITLE
Provide a way to call encodeToString and decodeFromString with explicit class parameter

### ISSUE THREAD

**Issue by Freezystem** [Kotlin/kotlinx.serialization#1134]
**What is your use-case and why do you need this feature?**

I'm a beginner in kotlin so I may not understand every aspects of that request and may struggle to give accurate answers to it.

I'm trying to use kotlinx.serialization as a replacement for Jackson serializer in the Javalin Framework.
The Javalin documentation provide [a way to replace the default serializer](https://javalin.io/documentation#using-gson) by overriding it's own JsonMapper.

So I took my chance and write something like this:

```kotlin
JavalinJson.toJsonMapper = object : ToJsonMapper {
    override fun map(obj: Any): String = Json.encodeToString(obj)
}
    
JavalinJson.fromJsonMapper = object : FromJsonMapper {
    override fun <T> map(json: String, targetClass: Class<T>): T = Json.decodeFromString(json)
}
```
To me, `encodeToString` part should have worked as is with this implementation. 
But the fact the function is using `<reified T>` seems not to play well with the `toJsonMapper` interface:
```kotlin
@FunctionalInterface
interface ToJsonMapper {
    fun map(obj: Any): String
}
```
Then there is `decodeFromString` that didn't work with the Javalin interface either because of the `<reified T>` part:
```kotlin
@FunctionalInterface
interface FromJsonMapper {
    fun <T> map(json: String, targetClass: Class<T>): T
}
```

A temporary "hacky" solution was provided by another coder [in SO](https://stackoverflow.com/questions/64284767/replace-jackson-with-kotlinx-serialization-in-javalin-framework/64285478#64285478) that look like this:
```kotlin
JavalinJson.toJsonMapper = object : ToJsonMapper {
    override fun map(obj: Any): String {
        val serializer = serializer(obj.javaClass)
        return Json.encodeToString(serializer, obj)
    }
}

JavalinJson.fromJsonMapper = object : FromJsonMapper {
    override fun <T> map(json: String, targetClass: Class<T>): T {
        @Suppress("UNCHECKED_CAST")
        val deserializer = serializer(targetClass) as KSerializer<T>
        return Json.decodeFromString(deserializer, json)
    }
}
```
The solution was far from trivial and I don't think I'd have been able to figure it out by myself with my current Kotlin knowledge.
Plus I had to add a lot of `@ExperimentalSerializationApi` annotation in my code that feel cumbersome.

**Describe the solution you'd like**

Maybe it could be a good thing to provide another `encodeToString` and `decodeFromString` function signature that match these interfaces as it seems to be a standard in json serialization libraries.

I have no clue if it's doable or not or even if it's by design but I'd be glad to understand what going on here as a part of my learning :blush:

**Comment by sandwwraith** [comment]
The interfaces in question, to be honest, are far from ideal. While it's still possible to serialize `obj: Any` using `serializer(obj::class.java)` (btw you can use `@OptIn(ExperimentalSerializationApi::class)` for non-propagating use), the `targetClass: KClass` for deserializer is not enough. Due to Java generics erasure, this method may experience problems on attempt to deserialize e.g. List — the KClass does not have information on its type arguments. Usually this problem is avoided by type tokens, so ideally both these methods should also have `java.lang.reflect.Type` parameter or Kotlin's `KType`.

**Comment by Freezystem** [comment]
@sandwwraith thanks for your explanation. 
I understand a bit more why the _type token_ usage is interesting here after documenting myself on the _Java generics erasure_  concept I was not aware of.
Thanks also for the `@OptIn` annotation tips.
