### ISSUE TITLE
"Unexpected JSON token at offset..." message could be better

### ISSUE THREAD

**Issue by pwgraham91** [Kotlin/kotlinx.serialization#1137]
**Describe the bug**
If you define your data class attribute as a non-nullable list and the JSON returns null in that spot you get an error message that looks like:
```
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 8: Expected '[, kind: LIST'
JSON input: {"one": null, "two": 2}
```

This error message can be confusing if you have a large data class with many attributes because the error message does not say which attribute caused the problem, only that it was supposed to be a list.

**To Reproduce**
```
@Serializable
data class ExampleClass(
    val one: List<String>,
    val two: Int,
)

val exampleJson = "{\"one\": null, \"two\": 2}"

val instance = Json.decodeFromString<ExampleClass>(exampleJson)

Assert.assertEquals(instance.two, 2)
```
**Expected behavior**
It would be easier for developers to diagnose the error if it said which key the reader was trying to decode at the time, the expected type and what was received.
example:
```
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 8: For key "one", Expected: List<String>. Received: null.
JSON input: {"one": null, "two": 2}
```

**Environment**
 - Kotlin version: [e.g. 1.4.10]
 - Library version: [e.g. 1.0.0]
 - Kotlin platforms: [JVM]
 - Gradle version: [e.g. 4.0.2]

**Comment by pwgraham91** [comment]
Another user had this issue in https://github.com/Kotlin/kotlinx.serialization/issues/886 but figured it out for themselves after further investigation.

**Comment by KevinBassaDevelopment** [comment]
Yes this would really help!
It is doable now, but it would speed up the error finding process a lot.

**Comment by antonkovalyov351** [comment]
Any news on it?

**Comment by MoustafaElsaghier** [comment]
any update on this it's not stopping

**Comment by sandwwraith** [comment]
I think #1638 would allow better error messages

**Comment by MoustafaElsaghier** [comment]
@sandwwraith so you found the solution or what?

**Comment by mojtabasheikhy** [comment]
in my case 
   fun saveUserInfo(User_info: UserInfo?) {
            Database.executeTransaction{
                val args = ContentValues()
                args.put(User_Table.userInfo.toString(), -----------> User_info.toString())
                com.dbflow5.query.update<User>().set().conditionValues(args).where().cursor(it)

            }
    }
change to 
  fun saveUserInfo(User_info: UserInfo?) {
           Database.executeTransaction{
                val args = ContentValues()
                args.put(User_Table.userInfo.toString(), ------------> Json.encodeToString(User_info))
                com.dbflow5.query.update<User>().set().conditionValues(args).where().cursor(it)

            }
        }
and fixed
