### ISSUE TITLE
Can't serialize object declarations on JS target platform

### ISSUE THREAD

**Issue by Whathecode** [Kotlin/kotlinx.serialization#1138]
**Describe the bug**
Making an object declaration `@Serializable` compiles correctly for both JVM and JS target platforms using the LEGACY backend. However, at runtime a `SerializationException` occurs when trying to serialize the object on JS.

> SerializationException: Serializer for class 'SomeObject' is not found.

**To Reproduce**
```
@Test
fun fails_on_js() = runBlockingTest {
    val json = Json { }
    val serialized = json.encodeToString( SomeObject )
}

@Serializable
object SomeObject
```

**Expected behavior**
For serialization of object declarations to work on both the JVM and JS platform. I haven't verified whether this works on the new IR backend since we haven't upgraded yet due to a different issue: https://github.com/Kotlin/kotlinx.serialization/issues/980

**Environment**
 - Kotlin version: 1.4.10
 - Library version: 1.1.0-RC2
 - Kotlin platforms: JS
 - Gradle version: 6.6

**Comment by sandwwraith** [comment]
Due to limitations of legacy JS backend, it is only possible to serialize an object when serializer is passed explicitly: `json.encodeToString(SomeObject.serializer(), SomeObject)`

**Comment by Whathecode** [comment]
Unfortunately, that is not possible for my actual use case (this was a reduced repro) in which I need to do polymorphic serialization and the polymorphic serializer of the base class is passed. The following still fails:

```
@Test
fun fails_on_js() = runBlockingTest {
    val module = SerializersModule {
        polymorphic( Base::class )
        {
            subclass( SomeObject::class )
            subclass( SomeClass::class )
        }
    }

    val json = Json { serializersModule = module }
    val serialized = json.encodeToString( PolymorphicSerializer( Base::class ), SomeObject )
}

interface Base

@Serializable
object SomeObject : Base

@Serializable
class SomeClass : Base
```

**Comment by sandwwraith** [comment]
You can use `subclass(SomeObject::class, SomeObject.serializer())`

If I'm not mistaken, this should work on IR, yes

**Comment by Whathecode** [comment]
@sandwwraith Thank you! That wasn't clear to me.

That is a _much_ cleaner temporary workaround than what I was doing before. :)
