### ISSUE TITLE
[Question] What is KSerialClassDesc?

### ISSUE THREAD

**Issue by SeanOThomas-zz** [Kotlin/kotlinx.serialization#114]
I've been hard-pressed to find documentation.  For Android, I'm trying to write a custom serializer for `MyData` by implementing `KSerializer<MyData>`.  I must override `val serialClassDesc: KSerialClassDesc get()`, but I don't know what to provide.

Thanks!

**Comment by sandwwraith** [comment]
`KSerialClassDesc` is a _"serializable class descriptor"_ which usually provides class name and maps properties names to indices and vice versa. Useful implementation for classes is `kotlinx.serialization.internal.SerialClassDescImpl`. You can call its constructor to provide descriptor with class name, which can be sufficient if you don't use `write/readXXXElementValue`. If you do, you should also provide mappings for indices. They're built automatically if you use `SerialClassDescImpl.addElement`.
