### ISSUE TITLE
IDE Encode and Decode Methods Expect Two Parameters

### ISSUE THREAD

**Issue by piacenti** [Kotlin/kotlinx.serialization#1142]
When trying to encode or decode an object the IDE highlights errors saying that you need to pass two parameters. I tried the code snippet from the readme file and this is what I got:
![image](https://user-images.githubusercontent.com/7397483/95927614-1b47f480-0d74-11eb-8cca-3e76c8754b92.png)
![image](https://user-images.githubusercontent.com/7397483/95927879-d8d2e780-0d74-11eb-8ec8-5e6f7ef0597e.png)

**Expected behavior**
It should work as advertised and not require a full serialization method call `Json.encodeToString(Project.serializer(), data)`
**Environment**
 - Kotlin version: 1.4.10
 - Library version: 1.0.0
 - Kotlin platforms: JVM, JS
 - Gradle version: 6.6.1
 - IDE version (if bug is related to the IDE) IntellijIDEA 2020.2.3
 - Other relevant context: MacOs, Java 11.0.5

**Comment by sandwwraith** [comment]
Try to add `import kotlinx.serialization.*`. One-argument function is an extension that should be imported.

**Comment by piacenti** [comment]
Thanks, that was it. I have my IDE expanding * imports and it removed imports it didn't think I need.
