### ISSUE TITLE
Spring support?

### ISSUE THREAD

**Issue by dibog** [Kotlin/kotlinx.serialization#1144]
**What is your use-case and why do you need this feature?**
Is it possible to use kotlinx.serialization for marshaling and unmarshaling methods in
a Spring RestController?

**Describe the solution you'd like**
Currently I'm using Jackson for sending or receiving objects in Spring RestController (using Kotlin ofc.).
Will it in Future be possible to use kotinx.serialization?

**Comment by sandwwraith** [comment]
Judging by this ticket: https://github.com/spring-projects/spring-framework/issues/21188 , the support of kotlinx.serialization in Spring is available since 5.3 RC1

**Comment by rudyscat** [comment]
No

**Comment by sandwwraith** [comment]
@rudyscat sorry, what did you mean by that?
