### ISSUE TITLE
Will Kotlin Serialization provide a built-in serializer for the Result<T> class?

### ISSUE THREAD

**Issue by vngantk** [Kotlin/kotlinx.serialization#1145]

**Comment by sandwwraith** [comment]
I know this looks like a great idea when `Result` contains successful case, but what about failure? Exception classes are rarely `@Serializable`.

**Comment by qwwdfsad** [comment]
We are not going to provide a serializer for `Result` class for this very reason: `Throwable` is not serializable.
The best we can do is to provide helpful diagnostic if this request will be frequent
