### ISSUE TITLE
Json.encodeToString() on a class with a member of type data class returns an incomplete JSON string

### ISSUE THREAD

**Issue by nicolaisingh** [Kotlin/kotlinx.serialization#1165]
**Describe the bug**
Creating a class with a data class member produces an incomplete JSON string when encoding.
When doing a `Json.encodeToString(obj)`, the resulting JSON string does not include the data class.
Tested changing the data class to an ordinary class, and the issue did not occur.

**To Reproduce**
Sample code:
``` kotlin
@Serializable
data class DC(val hash: String, val state: String)

@Serializable
class StateGroup(val someString: String, val anotherString: String, val dcList: List<DC>)

val stateGroup = StateGroup("First", "Second", listOf(DC("abc", "abc"), DC("bcd", "bcd"))))

// Running Json.encodeToString(stateGroup) produces this string.
// The dcList is missing
{"someString":"First","anotherString":"Second"}
```

**Expected behavior**
dcList should be part of the output

**Environment**
 - Kotlin version: 1.4.10
 - Library version: kotlinx-serialization-json:1.0.0, kotlinx-serialization: 1.4.10
 - Kotlin platforms: Native
 - Gradle version: 6.1.1

**Comment by sandwwraith** [comment]
Hi, 
what exact Native platform do you use? I've tested your snippet on macOS and didn't face such an issue. 
In general, data modifier does not affect serialization framework in any way, so problem should be somewhere else. Maybe you have some default value for that class and it was [elided](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/basic-serialization.md#defaults-are-not-encoded)? Try to check with `Json { encodeDefaults = true }`.

**Comment by nicolaisingh** [comment]
@sandwwraith platform is Android.

The value is indeed a default one, although it's weird that if I change the data class into a normal class, it will always gets included in the resulting JSON string.

Here's another sample code where I was able to replicate the behavior:
``` Kotlin
@Serializable
data class Shirt(val color: String, val size: String)

fun defaultShirts() = listOf(Shirt("red", "M"), Shirt("green", "M"), Shirt("blue", "M"))

@Serializable
class Person(val firstName: String, val lastName: String, val shirts: List<Shirt> = defaultShirts()) {

    fun toJsonString(): String {
        return Json.encodeToString(this)
    }

    companion object {
        fun makeBobby(): Person {
            return Person("Bobby", "Man")
        }
    }
}

```

Using the above code, when logging the result of `makeBobby()`:
```
{"firstName":"Bobby","lastName":"Man"}
```

... then, if I change `data class Shirt` to `class Shirt`:
```
{"firstName":"Bobby","lastName":"Man","shirts":[{"color":"red","size":"M"},{"color":"green","size":"M"},{"color":"blue","size":"M"}]}
```

The default value is now included.  Not sure if this is expected or not, but I think the behavior should be the same whether it's a data class or a normal class.

**Comment by sandwwraith** [comment]
Ah, I see now. The problem is that non-`data` classes do not have equals method overriden. Therefore, their comparison to default values always gives `false` and it is considered eligible for encoding.

You can use Json's encodeDefaults flag to change this behavior.
