### ISSUE TITLE
Build error after upgrading from 0.4.2 to 0.5.0 in Android project

### ISSUE THREAD

**Issue by toXel** [Kotlin/kotlinx.serialization#117]
I'm using `kotlinx.serialization` in an Android project with Android Studio. After I upgraded the plugin to 0.5.0 today I now get the following build error:
```
More than one file was found with OS independent path 'META-INF/main.kotlin_module'
```
I already tried a clean build but that doesn't help. When I go back to 0.4.2 it works again.
Kotlin compiler version is 1.2.41 and I use the `kotlin-android-extensions` plugin. Proguard is not active.

**Comment by sandwwraith** [comment]
The easiest workaround is to exclude this file in packaging, since you likely don't need it in your apk:

```gradle
android {
  packagingOptions {
    exclude 'META-INF/main.kotlin_module'
  }
}
```
([original answer](https://stackoverflow.com/a/47509465))

I don't know why plugin version upgrade caused this error, since it is known bug of the compiler: https://youtrack.jetbrains.com/issue/KT-23695

**Comment by toXel** [comment]
As far as I can see it in the YouTrack issue this will be fixed in Kotlin 1.2.50, right? So I will just wait for that release. I'll close the issue.

**Comment by pdvrieze** [comment]
As an alternative you want to specify a unique `archivesBaseName` (A toplevel property in groovy, part of base in kts). The file is actually used for resolving toplevel functions so having it working correctly is useful.

**Comment by toXel** [comment]
Little follow up: After updating to Kotlin 1.2.50 and kotlinx.serialization 0.5.1 it works now.
