### ISSUE TITLE
Untagged union type support (no discriminator)

### ISSUE THREAD

**Issue by demurgos** [Kotlin/kotlinx.serialization#1175]
**What is your use-case and why do you need this feature?**

I want to parse the result of an OAuth access token grant. The server may respond with either an error or an access token. Here are the two possible responses:

```json
{
  "error": "code_expired"
}
```

```json
{
  "access_token": "AMHILF5gGddDnfqVj9K8yIeP3VMIgaxG",
  "refresh_token": "HfznfQUg1C2p87ESIp6WRq945ppG6swD",
  "expires_in": 7200,
  "token_type": "Bearer"
}
```

I do not control the schema of the server response but still want to parse it. There is no common key that may act as a discriminator. I know all the possible types (it is not unbounded polymorphism) and need to parse the server response into a typed value.

**Describe the solution you'd like**

I would like to represent the server response as following (this is a minimal example, the real code would use domain types). **EDIT: I updated the code to better fit with with serialization (these classes can serve as surrogates for the original classes).** 

```kotlin
@Serializable(untagged = true)
sealed class AccessTokenResponse {
  @Serializable
  data class Ok(
    @SerialName("access_token") val accessToken: String,
    @SerialName("refresh_token") val refreshToken: String,
    @SerialName("expires_in") val expiresIn: Int,
    @SerialName("token_type") val tokenType: String,
  ): AccessTokenResponse()

  @Serializable
  data class Error(val error: String): AccessTokenResponse()
}
```

<details>
<summary>Code before the edit</summary>

```kotlin
@Serializable
data class AccessToken (
  @SerialName("access_token") val accessToken: String,
  @SerialName("refresh_token") val refreshToken: String,
  @SerialName("expires_in") val expiresIn: Int,
  @SerialName("token_type") val tokenType: String,
)

@Serializable
data class AccessTokenError (
  val error: String,
)

@Serializable(untagged = true)
sealed class AccessTokenResponse {
  data class Ok(val ok: AccessToken): AccessTokenResponse()
  data class Error(val error: AccessTokenError): AccessTokenResponse()
}
```

</details>

To support untagged unions, there should be an annotation on the `AccessTokenResponse` to change the parser behavior. Instead of reading a discriminator field, it should sequentially try all the possible cases (in definition order) and return the first successfully parsed value. With the examples above, using `Json.decodeFromString<AccessTokenResponse>` would produce:

```kotlin
AccessTokenResponse.Error("code_expired")
```

```kotlin
AccessTokenResponse.Ok("AMHILF5gGddDnfqVj9K8yIeP3VMIgaxG", "HfznfQUg1C2p87ESIp6WRq945ppG6swD", 7200, "Bearer")
```

<details>
<summary>Result before the edit</summary>

```kotlin
AccessTokenResponse.Error(AccessTokenError("code_expired"))
```

```kotlin
AccessTokenResponse.Ok(AccessToken("AMHILF5gGddDnfqVj9K8yIeP3VMIgaxG", "HfznfQUg1C2p87ESIp6WRq945ppG6swD", 7200, "Bearer"))
```

</details>

**Comment by demurgos** [comment]
A few other examples:

# Package.json author

This example is interesting because it presents a union between a primitive and an object.

The following npm `package.json` are both valid and represent the same value:

```json
{
  "name": "foo",
  "version": "1.0.0",
  "author": "John Doe <jdoe@jdoe.com> (https://jdoe.com)"
}
```

```json
{
  "name": "foo",
  "version": "1.0.0",
  "author": {
    "name": "John Doe",
    "email": "jdoe@jdoe.com",
    "url": "https://jdoe.com"
  }
}
```

I expect to use the following Kotlin representation:

```kotlin
@Serializable
data class Package (
  val name: String,
  val version: String,
  val author: Author,
)

@Serializable
sealed class Author {
  data class Str(val author: String): Author()
  data class Obj(val author: AuthorObj): Author()
}

@Serializable
data class AuthorObj (
  val name: String?,
  val email: String?,
  val url: String?,
)
```

And parse the inputs above using `Json.decodeFromString<Package>` as:

```kotlin
Package(
  name = "foo",
  version = "1.0.0",
  author = Author.Str("John Doe <jdoe@jdoe.com> (https://jdoe.com)")
)
```

and

```kotlin
Package(
  name = "foo",
  version = "1.0.0",
  author = Author.Obj(AuthorObj(
    name = "John Doe",
    email = "jdoe@jdoe.com"
    url = "https://jdoe.com"
  ))
)
```

# Multiple user views

This example is interesting because it presents two objects where one is a structural subtype of the other.

This example comes from an API I am consuming, when reading user data from a REST API there are two views: one with public data, and one exposing more private data. Depending on the authorization level, you receive either the public data or all the data. For example:

```json
{
  "id": "1b7985b2-99da-4c9b-a31f-14aeb35bb99a",
  "username": "foo"
}
```

```json
{
  "id": "1b7985b2-99da-4c9b-a31f-14aeb35bb99a",
  "username": "foo",
  "email": "foo@example.com",
  "phone": "0123456789",
}
```

In this situation, `email` and `phone` are not independent: they are either both missing or both present.

The naive user representation `data class User(val id: String, val username: String, val email: String?, val phone: String?)` does not capture this property. If I was free to change the schema, a good solution would be define a data class `PrivateData` with the email and phone, and then use `val privateData: PrivateData?` in the `User` class. Using this model without changing the serialized view would require some logic to flatten objects which is out of scope of this issue. Instead, I want to use the following user representation:

```kotlin
@Serializable
sealed class User {
  data class Full(val user: FullUser): User()
  data class Simple(val user: SimpleUser): User()
}

@Serializable
data class FullUser (
  val id: String,
  val username: String,
  val email: String,
  val phone: String,
)

@Serializable
data class SimpleUser (
  val id: String,
  val username: String,
)
```

and expect to parse the values as:

```kotlin
User.Simple(SimpleUser("1b7985b2-99da-4c9b-a31f-14aeb35bb99a", "foo"))
```

```kotlin
User.Full(FullUser("1b7985b2-99da-4c9b-a31f-14aeb35bb99a", "foo", "foo@example.com", "0123456789"))
```

This case works because the definition order is such that the parser first tries to parse a full user, and only then falls back to a simple user. You may also note that it correctly rejects this malformed value (email but no phone):

```json
{
  "id": "1b7985b2-99da-4c9b-a31f-14aeb35bb99a",
  "username": "foo",
  "email": "foo@example.com",
}
```

It rejects this value because parsing it as a full user fails, and when parsing it as a simple user there is an unexpected extra field. This is the default behavior. Enabling `ignoreUnknownKeys` in the JSON format would allow this input to be parsed as a simple user.

**Comment by 1354092549** [comment]
Serde(rust) provides this feature.
It implements this by trying to match the data against each variant in order.
https://serde.rs/enum-representations.html#untagged

**Comment by demurgos** [comment]
I updated my examples to use a representation that is closer to how Kotlin's serialization works currently. The previous code was trying to avoid inheritance between the sealed class representing the union and the data classes representing each variant. This implied extra complexity that was not relevant for this issue. The new code reduces the number of classes and can still be converted to the previous code using surrogate serialization. The code before the edit is still available in the messages but is hidden by default to avoid confusion.

**Comment by 1354092549** [comment]
BTW, you can use [Content-based polymorphic deserialization](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#content-based-polymorphic-deserialization) to handle this cases.

**Comment by sandwwraith** [comment]
The content-based polymorphic deserialization is an official recommended way to use in such scenarios, and it was designed specifically for that purpose. It is also possible to implement Rust analogue: do `try ... catch(SerializationException)` for every  subtype, but such a solution looks very inefficient to me

**Comment by demurgos** [comment]
Thank you for recommending content-based deserialization. Using the method I was able to implement serializers for all of the cases described above.
I feel that cases like this are common enough that it would be good to derive the serializers automatically. Regarding efficiency, I think that untagged unions are mostly used to switch between a few "families" of types so even a naive solution should work fine. Longer term, the generated serializers could be smart enough to use a different strategy instead of `try/catch` (such as looking for missing fields).

**Comment by luca992** [comment]
I agree with @demurgos. It would be nice if content-based serializers were able to be generated automatically. I've run into this issue many times

**Comment by Seggan** [comment]
I would also like this feature
