### ISSUE TITLE
How to allow empty list on a null field?

### ISSUE THREAD

**Issue by ronjunevaldoz** [Kotlin/kotlinx.serialization#1178]
**What is your use-case and why do you need this feature?**
Given that I have a json object below:

```json
"items": [
{
    "id": 123, "name": "test" 
} 
] 

"items": null
```
**Describe the solution you'd like**

I want it to be modeled like below, the null items should be converted to `emptyList()`

```kotlin
data class Item (val id: Int, val name: String)

data class ItemResponse(val items : List<item> = emptyList())
```

**Comment by sandwwraith** [comment]
Does `coerceInputValues` flag works for you in that case? https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#coercing-input-values

**Comment by sandwwraith** [comment]
Also #1113
