### ISSUE TITLE
Exceptions documentation

### ISSUE THREAD

**Issue by NiematojakTomasz** [Kotlin/kotlinx.serialization#1180]
I think exception types thrown by serialization / deserialization should be documented, so users could properly handle format errors.

Docs missing in:
- kotlinx.serialization.StringFormat
- kotlinx.serialization.BinaryFormat
- serialization-core-jvm-1.0.0-sources.jar!/commonMain/kotlinx/serialization/SerialFormat.kt:91
- kotlinx-serialization-core-jvm-1.0.0-sources.jar!/commonMain/kotlinx/serialization/SerialFormat.kt:99
- ...

**Comment by qwwdfsad** [comment]
The only allowed type of exception is `SerializationException`: https://kotlin.github.io/kotlinx.serialization/kotlinx-serialization-core/kotlinx-serialization-core/kotlinx.serialization/-serialization-exception/index.html

But indeed, we can also mention it in format documentation

**Comment by NiematojakTomasz** [comment]
I am bit paranoid about proper error handling when it comes to user input and always check API docs ; )

**Comment by malachid** [comment]
That isn't the only type actually thrown though.
`The root cause java.lang.RuntimeException was thrown at: org.jetbrains.kotlin.backend.jvm.codegen.FunctionCodegen.generate(FunctionCodegen.kt:50)`

**Comment by sandwwraith** [comment]
@malachid That's an internal compiler error, not a runtime exception from library

**Comment by qwwdfsad** [comment]
Fixed in 1.4.0-RC
