### ISSUE TITLE
buildJsonObject improvements

### ISSUE THREAD

**Issue by Lewik** [Kotlin/kotlinx.serialization#1181]
```
val iCanDoThis = JsonObject(emptyMap())
val butCantDoThis = buildJsonObject { emptyMap() }

val alsoICanDoThis = JsonArray(listOf(JsonObject(emptyMap())))
val butThisWillNotCompileToo = buildJsonArray { addJsonObject { emptyMap() } }
```

![image](https://user-images.githubusercontent.com/1853182/98110507-3fe54700-1eb0-11eb-9f7f-d92787ccb294.png)

**Comment by sandwwraith** [comment]
That's because `emptyMap()` in `buildJsonObject` is actually a no-op and statement not related to builder. In `buildJsonObject`, one should use `put("key", smth)`

**Comment by Lewik** [comment]
```
val fix1 = buildJsonObject { }
val fix2 = buildJsonArray { addJsonObject { } }
```
This should work, thank you.

**Comment by Lewik** [comment]
`val test = buildJsonArray { listOf("A", "B").map { buildJsonObject { put("id", it) } } }`
The intention is to create JsonArray from a list of JsonElements
There is to addList()

**Comment by tonisives** [comment]
I have the same problem

```
return buildJsonArray {
    retainedPoints.forEach {
        mqttUpdate(it.value, it.areaId, it.timestamp.toLong())
    }
}

fun <T> mqttUpdate(value: T, areaId: Int, timestamp: Long) = buildJsonObject {
    "value" to value
    "areaId" to areaId
    "timestamp" to timestamp
}
```

This buildJsonObject returns empty Json. The array has an empty {} inside it. I would expect the jsonObject to have values.
