### ISSUE TITLE
Provide default value information in SerialDescriptor

### ISSUE THREAD

**Issue by thake** [Kotlin/kotlinx.serialization#1182]
**What is your use-case and why do you need this feature?**

It would be useful to retrieve the kotlin default value from the SerialDescriptor. Schema-based serialization formats that have the ability to specify a default value for a serialized field could use this information to enrich the generated schemas with informations about the default value.

**Describe the solution you'd like**

The SerialDescriptor should have an additional function that returns the "defaultValue" for an element.

Example:
```kotlin
@Serializable
data class Person(val name : String = "anonymous")
...
serialDescriptor.getElementDefaultValue(0) == "anonymous"

```

**Comment by sandwwraith** [comment]
This can be a much more complicated task than it seems on the first look: 
default values can be non-constant, meaning that they're re-evaluated each time class is created. How should retrieving the value outside the instance of class should work then? Moreover, default values can depend on other class' constructor parameters.

**Comment by thake** [comment]
@sandwwraith I agree with you. This can be a very daunting task. How about allowing only default values which are using constructors that would also be used on deserializing?

Having this feature would add type safety to schema generation.

**Comment by qwwdfsad** [comment]
It still is not really possible.
We were thinking about it back in the day and weren't able to come up with an elegant, complete and sound solution that works consistently over various serialization use-cases.

E.g. consider the following class: `@Serializable class Foo(val a: String, val b: String = a + " , but 'b'")`. What should `getElementDefaultValue(1)` return?

And, as a library, we cannot provide an API in our very core that "works 50% of the time if the code is written in one way, but not in the other", so, unfortunately, we cannot fix it.

**Comment by thake** [comment]
I agree with you. Providing this for all properties would lead to problems. 

But would it be possible to provide this functionally per opt-in? I.e. if someone annotates the property with a specific annotation, lets say "@Default", would it be possible for the compiler plugin to check if the default value is deterministic?

**Comment by qwwdfsad** [comment]
It will be possible, but we are not going to do it for the same reasons: this is a half-baked solution that works 50% of the time. I realize that it solves your particular problem, but what the rest of the users should do?

What `getElementDefaultValue` should return? What type is it? How to distinguish default `null`  from "this property actually doesn't have a default value"? What should it return for complex default initializations? How to enforce this contract for authors of user-defined serializers and descriptors?
