### ISSUE TITLE
Make SerialDesciptor high level level subclasses public

### ISSUE THREAD

**Issue by rnett** [Kotlin/kotlinx.serialization#1186]
**What is your use-case and why do you need this feature?**

I am attempting to work with the generated serial descriptors.  I'm working on a typed argument parser (i.e. [typed-argument-parser](https://github.com/swansonk14/typed-argument-parser)) and want to use serialization's introspection where possible, instead of writing my own compiler plugin.  Currently, to get the key descriptor from a map descriptor, you have to go through `getElementDescriptor` with hard coded index (to be fair, it's 1 and 2), since `MapLikeDescriptor` is internal.  For the most part, all these classes do is provide type checking and accessors for data that is already available via `SerialDescriptor`, as far as I can tell there is nothing that requires them to be private other than api surface concerns (except `PluginGeneratedSerialDescriptor`, but I'm not advocating for making that one public).

**Describe the solution you'd like**

Making descriptor kind classes (`MapLikeDescriptor`, `ListLikeDescriptor`, `PrimitiveSerialDescriptor`, `SerialDescriptorForNullable`, maybe `EnumDescriptor`) public, and probably mark them with `@ExperimentalSerializationApi` or `InternalSerializationApi`.

**Comment by pdvrieze** [comment]
The hierarchy that is represented by `SerialDescriptor` is actually part of the API. So, for any valid `SerialDescriptor` that wants to describe a `MAP` it needs the right `SerialKind`, but also the right element types. As such you can rely on these. More significantly, making these subtypes public doesn't address your issue as that would disable custom implementations of the descriptor (you would be having to check on the type). `SerialDescriptor` is designed mainly from the format perspective, but it does provide access to all the needed information, and formats can represent structures like lists and maps differently.

In terms of what you are trying to do, it may be most convenient to create a wrapper or mapping from the `SerialDescriptor` to some more useful descriptor you have.

**Comment by rnett** [comment]
Ah, true, I didn't realize custom descriptor implementations were something intended.  I'm using wrappers now and it's working well enough.

**Comment by sandwwraith** [comment]
The main idea, as @pdvrieze correctly noticed, is to provide correct SerialKind and implementations of other methods that match kind's contract. Particular implementation class can be from library or implemented by user, it doesn't matter.
