### ISSUE TITLE
Interface polymorphic deserialization with nested subclasses

### ISSUE THREAD

**Issue by mpierucci** [Kotlin/kotlinx.serialization#1188]
**Describe the bug**
Can´t deserialize a JSON using polymorphic deserialization and interfaces, if the structure coin nested implementation of the interface.

**To Reproduce**
Given the following class hierarchies: 
```
    interface Deliverable
 
    @Serializable
    @SerialName("box")
    data class Box(val address: String) : Deliverable

    @Serializable 
    @SerialName("parcel")
    data class Parcel(val senderNumber: Int, val box: Box) : Deliverable
```
And the corresponding `SerializersModule` to register the implementations:
```
     private val module = SerializersModule {
        polymorphic(Deliverable::class) {
            subclass(Box::class)
            subclass(Parcel::class)
        }
    }
```

Whenever I try to deserialize a matching JSON string. i.e : 
```
  @Test
    fun `deserialize parcel`() {

        val deliverable = """
        {
            "type":"parcel",
            "senderNumber": "5",
            "box": {
                "type": "box",
                "address": "new york"
            }
        }
        """.trimIndent()

        val box = Box("new york")
        val parcel = Parcel(5, box)

        val result = Json { serializersModule = module}.decodeFromString<Deliverable>(deliverable)

        Truth.assertThat(result).isEqualTo(parcel)
    }
```
I get the following error: 

`kotlinx.serialization.json.internal.JsonDecodingException: Encountered unknown key 'type'.
Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys`

My assumption is that since `Parcel` has an explicit implementation declared rather than a `Deliverable` then the polymorphic strategy for interfaces its not applied and cant account for the type field?.

But if that's the case how's the correct way of handling these situations?

Disclaimer:
Adding `'ignoreUnknownKeys = true'` like the error suggest fixes the issues but it doesn't feel right to enable this for this use case, or maybe I´m missing a key part here

**Environment**
 - Kotlin version: [1.4.10]
 - Library version: [1.0.1]
 - Kotlin platforms: [JVM]
 - Gradle version: [6.5]
 - IDE version [Android Studio 4.1]

**Comment by sandwwraith** [comment]
Hi, 
I've copy-pasted your example into jvmTest sourceset of kotlinx.serialization 1.0.1 and it passes successfully.

Note that `.decodeFromString<Deliverable>` is important here — if you write `.decodeFromString<Parcel>` serialization will indeed throw exception about unknown key 'type', because it tries to deserialize concrete type without polymorphism enabled.

**Comment by mpierucci** [comment]
Hello sorry for the confusion, the deserializer module should not have the ` ignoreUnknownKeys = true` bit, I've updated the description.

As stated in the disclaimer the code does work with ` ignoreUnknownKeys = true` so I guess my question is is this the intended way to handle this scenario? 

If I change `Parcel` to 
```
  @Serializable 
  @SerialName("parcel")
  data class Parcel(val senderNumber: Int, val box: Box) : Deliverable
```
It does works without the ignore param, which I reckon now it makes sense since there is no implementation involved?

**Comment by sandwwraith** [comment]
`ignoreUnknownKeys` should not affect polymorphism at all. 

Well, then it seems that you have incorrect serial name in the input data — it should be fq name (with package). With `@SerialName` annotation, this can be changed.

**Comment by mpierucci** [comment]
I'm not sure I follow, as you can see in the example provided, I´m already using the `@SerialName ` annotations in my implementation classes. Is there anything else I´m missing?

**Comment by sandwwraith** [comment]
Yes, it works with `@SerialName`, as it is supposed to

**Comment by mpierucci** [comment]
Care explaining where else should I been using the `@SerialName` annotation besides in the places I´ve already shown in the example. Because it's definitively not working for me

**Comment by testower** [comment]
Can confirm I'm having the same problem.

kotlin_version=1.4.10
kotlinx_serialization_version=1.0.1

**Comment by sandwwraith** [comment]
@mpierucci  I finally got it. The problem is in the nested `Box`. See, your Parcel has `val box: Box`, not `val box: Deliverable`. Therefore framework does not enable polymorphic serialization for this property and does not expect `"type":"box"` in the input. You can simply ignore with `ignoreUnknownKeys` or change the type to `Deliverable` to enable polymorphism.

**Comment by mpierucci** [comment]
@sandwwraith  great! So for this use-case, using `ignoreUnknownKeys ` is the way to go. Thanks for your time and patience.

**Comment by Dominaezzz** [comment]
Can this be closed now?
