### ISSUE TITLE
Recursive call failure in IDEA when mutually declaring both Serializable(with) and Serializer(for)

### ISSUE THREAD

**Issue by altavir** [Kotlin/kotlinx.serialization#1192]
**Describe the bug**
Code analysis in IDEA takes infinite times or never completes. `Recursive call in a lazy value under LockBasedStorageManager` error in IDEA report.

It is possible that dependent applications/libraries are also affected.

**To Reproduce**
```
@Serializable(ASerializer::class)
class A

@Serializer(A::class)
class ASerializer{...}
```

**Expected behavior**
Should not go into an infinite loop.

**Environment**
 - Kotlin version: 1.4.10, 1.4.20
 - Library version: 1.0.0
 - IDE version: 2020.2.3, 2020.3

**Comment by msfjarvis** [comment]
For me this also causes compilation to hang, the `compileDebugKotlin`/`compileReleaseKotlin` task never completes.

**Comment by unused-variable** [comment]
Ran into similar issue with version 1.0.1 as well.

**Comment by shanshin** [comment]
Not reproduced in the latest versions

**Comment by sandwwraith** [comment]
Please reopen if still actual
