### ISSUE TITLE
Polymorphic serialization skips fields

### ISSUE THREAD

**Issue by simpajj** [Kotlin/kotlinx.serialization#1202]
**Describe the bug**

I have some code consisting of a sealed class hierarchy (see snippet below). Prior to version 1.0.0 this serialized without any issues (I did use an explicit serializer module, but not sure if it was strictly necessary). After bumping to 1.0.0 some fields are not present in the serialized string when doing `Json.encodeToString`. For type `NUMERIC_RATING_SCALE` the `min` property is always missing and for type `TEST` `c` & `d` are missing. 

**To Reproduce**

```kotlin
@Serializable
data class Form(
    val id: Int,
    val name: String,
    val questions: List<Question>
)

@Serializable
data class Question(
    val id: Int,
    val name: String,
    val options: Options?
)

@Serializable
sealed class Options

@Serializable
@SerialName("NUMERIC_RATING_SCALE")
data class NumericRatingScale(
    val min: Int = 1,
    val max: Int = 7,
    val minDesc: String = "",
    val maxDesc: String = ""
) : Options()

@Serializable
@SerialName("TEST")
data class Test(
    val a: Int = 1,
    val b: Int = 2,
    val c: Int = 3,
    val d: Int = 4
) : Options()

val json = """
    {
        "id": "1",
        "name": "Form",
        "questions": [
            {
                "id": "1",
                "name": "Question 1",
                "options": {
                    "max": 10,
                    "min": 1,
                    "type": "NUMERIC_RATING_SCALE",
                    "maxDesc": "",
                    "minDesc": ""
                },
            },
            {
                "id": "2",
                "name": "Question 2",
                "options": {
                    "a": 10,
                    "b": 1,
                    "c": 3,
                    "d": 4,
                    "type": "TEST"
                },
            }
        ]
    }
""".trimIndent()

val parsed: Form = Json.decodeFromString(json)
println(parsed)
println(Json.encodeToString(parsed))
```

Example output (shortened for brevity): 

```json
Example output: 

```json
{
    "id": 1,
    "name": "Form",
    "questions": [
        {
            "id": 1,
            "name": "Question 1",
            "options": {
                "type": "NUMERIC_RATING_SCALE",
                "max": 10,
                "minDesc": "",
                "maxDesc": ""
            }
        }
    ]
}
```

**Expected behavior**

All fields should be serialized. 

**Environment**
 - Kotlin version: 1.4.10
 - Library version: 1.0.1 (ktor-serialization 1.4.2)
 - Kotlin platforms: JVM
 - Gradle version: 6.6.1
 - Other relevant context [e.g. OS version, JRE version, ... ]

**Comment by Dominaezzz** [comment]
I think this is what you're looking for. https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/basic-serialization.md#defaults-are-not-encoded .
This was originally on by default but it's now off.

**Comment by simpajj** [comment]
> I think this is what you're looking for. https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/basic-serialization.md#defaults-are-not-encoded .
> This was originally on by default but it's now off.

There's something else at play here, as `encodeDefaults` doesn't seem to do the trick either. All of the fields have default values, but only some of them end up being encoded for some reason.

**Comment by simpajj** [comment]
Yeah, that seems to have done the trick. Thank you!
