### ISSUE TITLE
It is safe to use KClass<T>.serializer() even if is internal?

### ISSUE THREAD

**Issue by prof18** [Kotlin/kotlinx.serialization#1210]
I'm working on a Multiplatform project and I'm building a custom serializer for Alamofire to deserialize a json to a Kotlin Class. That's because I have all the DTOs on KMP side.

The way I found to achieve this is by using the `KClass<T>.serializer()` method that is marked as InternalSerializationApi. So I was wondering if it is safe to use or there is another way that I don't know.

```kotlin
object JsonDecoder {
    @InternalSerializationApi
    fun decodeFromString(jsonString: String, objCClass: ObjCClass): Any {
        val kClazz = getOriginalKotlinClass(objCClass)!!
        val serializer = kClazz.serializer()
        return Json.decodeFromString(serializer, jsonString)
    }
}
```
Swift Code:
```swift
struct Serializer<T>: ResponseSerializer {
    func serialize(request: URLRequest?, response: HTTPURLResponse?, data: Data?, error: Error?) throws -> T {
        do {
            let x = try JsonDecoder().decodeFromString(jsonString: "{ }", objCClass: T.self as! AnyClass) as! T
            return x
        } catch {
            throw AFError.responseSerializationFailed(reason: .decodingFailed(error: error))
        }
    }
}
```

Thanks

**Comment by sandwwraith** [comment]
You can use `KClass.serializer()` if you've carefully read its documentation and understood limitations: it doesn't work with generic classes, lists, custom serializers, etc.

There is a more correct way to retrieve serializer: a `serializer(KType)` function or inline reified `serializer<T>()` that work with generics. However, given that you want Swift interop that doesn't have inline functions, I'm not sure if they fit — unless you make your Kotlin API fully statically typed (e.g. do not use `Any` in functions exposed to Swift)

**Comment by prof18** [comment]
Thanks for the response! I've tried to play with the inline reified serializer, but, as you said, it does not fit well. In the end, I've decided to ditch the internal api and go with another (more boilerplate and safe) way. I share it here if someone is interested to replicate it. 

I have defined an abstract class with an abstract deserialize method that every DTOs has to implement.

```kotlin

abstract class BaseResponseDTO {

    @Throws(Exception::class)
    abstract fun deserialize(jsonString: String): BaseResponseDTO
  
}

@Serializable
data class RandomDTO(
    val field: String
) : BaseResponseDTO() {

    @Throws(Exception::class)
    override fun deserialize(jsonString: String): RandomDTO {
        return Json.decodeFromString(jsonString)
    }
}

```

And on Swift side, I can do this and deserialize only classes that inherit from `BaseResponseDTO`

```swift

struct CustomResponseSerializer<T: BaseResponseDTO>: ResponseSerializer {
    func serialize(request: URLRequest?, response: HTTPURLResponse?, data: Data?, error: Error?) throws -> T {

        guard error == nil else {
            throw error!
        }

        do {

            let jsonString = try StringResponseSerializer(encoding: String.Encoding.utf8).serialize(request: request,
                    response: response,
                    data: data,
                    error: error)

            let deserializedObject = try T().deserialize(jsonString: jsonString) as! T
            deserializedObject.makeFrozen()
            return deserializedObject
        } catch {
            Log.error(error)
            throw AFError.responseSerializationFailed(reason: .decodingFailed(error: error))
        }
    }
}


```

**Comment by Baileypollard** [comment]
@prof18 How does your gradle file look? This solution isn't working for me

**Comment by prof18** [comment]
I have built a sample project that shows this implementation, you can give a look to that:

https://github.com/prof18/shared-deserialization

**Comment by Baileypollard** [comment]
@prof18 HAve you ever encountered `KClass for Objective-C classes is not supported yet` while trying to deserialize?

**Comment by mltbnz** [comment]
@prof18  I am running into `Terminating app due to uncaught exception 'NSGenericException', reason: 'Class BaseResponseDTO is abstract and can't be instantiated'` on the Swift side when using your solution.

**Comment by prof18** [comment]
Hi @mltbnz and @Baileypollard,
I've updated the project with the new memory model and new dependencies and everything is working for me!
