### ISSUE TITLE
Back end Internal Error when serializing object

### ISSUE THREAD

**Issue by Ersikan** [Kotlin/kotlinx.serialization#1217]
**Describe the bug**

When serializing an anonymous object, the code fails to compile.

See attached compilation log:
[build-failure.log](https://github.com/Kotlin/kotlinx.serialization/files/5584864/build-failure.log)

**To Reproduce**

```kotlin
import kotlinx.serialization.Serializable

fun fail() {
    val x = @Serializable object {
        val y = 0
    }
}
```

**Expected behavior**

The code compiles and `x` can be serialized.

If serializing anonymous object is not supported. I expected to see it clearly in the documentation, and to have a better error message than an internal error during the build.

**Environment**
 - Kotlin version: 1.4.10
 - Library version: 1.0.1
 - Kotlin platforms: Native
 - Gradle version: 6.7

**Comment by shanshin** [comment]
Since `1.5.30` compiler error is `Anonymous objects or contained in it classes can not be serializable.`
