### ISSUE TITLE
Provide a BOM for allow easier dependency management

### ISSUE THREAD

**Issue by sdeleuze** [Kotlin/kotlinx.serialization#1220]
Like done on Coroutines side, please provide a BOM to make it easier to have dependency management, Spring Boot would need that as part of https://github.com/spring-projects/spring-boot/issues/24238 for first class kotlinx.serialization support.

**Comment by sdeleuze** [comment]
Do you think you could provide it in upcoming 1.1?

**Comment by qwwdfsad** [comment]
We'll provide it in 1.1.1

**Comment by qwwdfsad** [comment]
Unfortunately, we slightly changed our schedule and decided to release 1.2.0 with BOM instead around the middle of April (along with Kotlin 1.5)
