### ISSUE TITLE
[Help] How to deserialize/parse lists after 1.0?

### ISSUE THREAD

**Issue by hykilpikonna** [Kotlin/kotlinx.serialization#1224]
I used to use `A.serializer().list` to get a list serializer, but this extension is removed after 1.0. And `ArrayListSerializer` is removed too. Is there a replacement?

Answers in this issue are deprecated: https://github.com/Kotlin/kotlinx.serialization/issues/179

### Code:

```kotlin
@Serializable
data class W(val w: String)

val jsonString = """[{"w": 1}, {"w": 2}]"""

// Old method:
val obj = json.parse(W.serializer().list, jsonString)
```

**Comment by ahimberg** [comment]
Have you tried this:
`val obj = json.decodeFromString(ListSerializer(W.serializer()), jsonString)`

**Comment by sandwwraith** [comment]
Yes, `ListSerializer()` is a correct replacement for `list` extension.
