### ISSUE TITLE
Could properties format allow missing array values by filling them with null?

### ISSUE THREAD

**Issue by TorRanfelt** [Kotlin/kotlinx.serialization#1225]
For the properties format would it be okay to allow arrays where not all positions have a value by filling them with nulls if allowed by the type? - This could be a configuration option.

Example:
```
    @Serializable
    data class Foo(
        val first: Array<String?>
    )
```

Should be able to parse

1=Test

first would then contain [null, "Test"]

Right now the array first is undefined instead of just the first index being undefined like [undefined, "Test"] which would also be okay.

**Comment by sandwwraith** [comment]
`Properties` format generally doesn't support nullable values, see #1623 / #1780
