### ISSUE TITLE
(De)Serialization of generic types

### ISSUE THREAD

**Issue by ln-12** [Kotlin/kotlinx.serialization#1231]
In my use case I have to work with an API that sends me JSON like:
```
{
    "ID": 42,
    "Kind": "query",
    "Call": "getLocation",
    "Result": "OK",
    "Data": {
        "Location": "someLocationValue"
    }
}
```
The fields `ID`, `Kind`, `Call` and `Result` are always given. `Data` could be `null` or one of many (known) objects. My approach currently looks the following:
```
@Serializable
data class Response<T>(
    val ID: Int,
    val Kind: String,
    val Call: String,
    val Result: String,
    val Data: T? = null
)
```
And for getting the object: `val obj = Json.decodeFromString<Response>(json)`.
Of course, it does not compile as I have to provide an argument for `T` ([generics in the docs](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/basic-serialization.md#generic-classes)). Is there some generic way of parsing it? I know the type of `Data` by reading the field `Kind` so I would like to only parse the fields `ID`, `Kind`, `Call` and `Result` to evaluate the type and then parse `Data` in a second step. Is that possible? The other option I see is to try/catch all possible configuration to find out the right one, but that is not really efficient.

**Comment by shanshin** [comment]
You can use [Content-Based Polymorphic serializer for JSON](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#content-based-polymorphic-deserialization).


In your case, if all subtypes of T are known you may use a sealed class 
```
    @Serializable
    sealed class Response<T>() {
        abstract val ID: Int
        abstract val Kind: String
        abstract val Call: String
        abstract val Result: String
        abstract val Data: T?

        @Serializable
        data class StringResponse(
            override val ID: Int,
            override val Kind: String,
            override val Call: String,
            override val Result: String,
            override val Data: String? = null
        ) : Response<String>()

        @Serializable
        data class IntResponse(
            override val ID: Int,
            override val Kind: String,
            override val Call: String,
            override val Result: String,
            override val Data: Int? = null
        ) : Response<Int>()
    //e.g. 
    }
```
and then define own serializer
```
    object ResultSerializer : JsonContentPolymorphicSerializer<Response<*>>(Response::class) {
        override fun selectDeserializer(element: JsonElement): KSerializer<out Response<*>> {
            val kind = element.jsonObject["Kind"]?.jsonPrimitive?.content
            return when(kind) {
                "int" -> Response.IntResponse.serializer()
                "string" -> Response.StringResponse.serializer()
                else -> throw SerializationException("Unknown choice $kind")
            }
        }
    }
```

decoding in this solution looks like this
```
Json.decodeFromString(ResultSerializer, """{"ID": 1, "Kind": "int", "Call": "hello!", "Result":"OK!", "Data": 100}""")
```

**Comment by ln-12** [comment]
Awesome, thanks a lot!
