### ISSUE TITLE
Parse to abstract type Number

### ISSUE THREAD

**Issue by triplem** [Kotlin/kotlinx.serialization#1235]
I would like to parse json into an data class which contains a Number property like eg.

@Serializable
data class Measure(val unit: String, @Contextual val value: Number)

I do get a SerializationException "Serializer for class 'Number' is not found.".

A workaround for me would be to use JsonPrimitive instead of "Number", which seems to be quite awkward.

**Comment by sandwwraith** [comment]
What's your use-case for `Number`? If you're expecting integer number, use `Int`, if number with decimal point — use `Double`.

**Comment by triplem** [comment]
I do have a measurement which could be a Double or an Int (depending on the Unit).

**Comment by triplem** [comment]
Lets say, I do have a Quantity Type in my project:

```
@Serializable
class Quantity<T : Number>(
    val unit: String,
    val amount: T
)
```

This serializes just fine, but for deserializing I do need to know, what concrete type the amount is. Any Input on this one? I already tried to annotate the amout with @polymorphic and provide a Module for this one, but to no avail.

**Comment by triplem** [comment]
Lets say, I do have the following type in my project:

```
@serializable
class Quantity<T : Number>(
    val unit: String,
    val amount: T
)
```
Serializing works (as expected) quite easily and no additional config is required. In De-Serialization I do need to define <T> (rather obvious), but this is not known to me in any case.
As a workaround, I tried to use @polymorphic, which tells me, that ```Serializer for Double of kind DOUBLE cannot be serialized polymorphically with class discriminator.```. 

Any possiblity to get this to work?

**Comment by sandwwraith** [comment]
> I do have to provide T for all "upper classes", which is IMHO rather annoying

Yes, because you still need to provide actual type of T. Either you do that in `Element`, or in some other class. If you do not want generic parameter, you can use `Number` right away, but we do not support it (particularly, for reasons described here: https://github.com/Kotlin/kotlinx.serialization/issues/1298#issuecomment-764746213). 

What you can try to do is to write a `KSerializer<Number>` that will return either Int or Double, depending on the input
