### ISSUE TITLE
Allow @SerialInfo annotations to work on types

### ISSUE THREAD

**Issue by pdvrieze** [Kotlin/kotlinx.serialization#124]
When attempting to support uniform serialization to XML it is useful (especially for polymorphic lists) to support the case where the name to for serialization is specified on the serializable type rather than it's container. While it is possible to do runtime reflection on the JVM this doesn't work on javascript.
Instead it would be possible to process the annotations on types and add them to the list in serialClassDesc.

**Comment by Elvis10ten** [comment]
@sandwwraith while this works for custom classes with generated serializers, it doesn't work for primitives.

Eg: I can't add this annotation to an integer, float, boolean.

It would be great if the presence of this annotation triggers the generation of new primitive serializers with this info.
