### ISSUE TITLE
Misleading documentation on serialization of enums

### ISSUE THREAD

**Issue by dkhalanskyjb** [Kotlin/kotlinx.serialization#1248]
**Describe the bug**

https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/builtin-classes.md#enum-classes states that enum classes are serializable out of the box. However, trying to actually serialize an instance of a enum fails on both JS and Native with something like this:
```
SerializationException: Serializer for class 'X' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
On Kotlin/JS explicitly declared serializer should be used for interfaces and enums without @Serializable annotation
```

Either the documentation should state that this holds only for enums that are serialized as fields of a class or this case should be supported.

**To Reproduce**

```kotlin
enum class X { Y, Z; }
Json.encodeToString(X.Y)
```

Passing or not passing `serializer<X>()` explicitly doesn't seem to make a difference.

**Environment**

* Kotlin version: 1.4.10
* Library version: 1.0.1
* Kotlin platforms: JS and Native

**Comment by sandwwraith** [comment]
Sorry for confusion. 'Explicitly declared serializer' in message actually means that on JS and Native, enums have to have a `@Serializable` annotation on them for `serializer<X>()` to work.

**Comment by dkhalanskyjb** [comment]
Sure. The point was, the linked documentation implies that `@Serializable` is not necessary and everything will work without it, but this is not true.
