### ISSUE TITLE
Add SerialName on 3rd-Party Libs 

### ISSUE THREAD

**Issue by triplem** [Kotlin/kotlinx.serialization#1250]
I do have a Domain-Model, which I do not like to dirty with framework and library specific Annotations (in this case @Serializable and @SerialName).

So, currently I do use the solution described in the documentation (https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#serializing-3rd-party-classes). This kinda works for the @Serializable-Annotation, but unfortunately seems to be not implemented for the @SerialName. 

```
val domainSerializerModule = SerializersModule {
    polymorphic(Measurement::class) {
        subclass(MeasurementChild1Serializer)
        subclass(MeasurementChild2Serializer)
    }
}

@Serializer(forClass = MeasrurementChild1::class)
object MeasurementChild1Serializer

@Serializer(forClass = MeasurementChild2::class)
object MeasurementChild2Serializer
```

On using the Serialization, the above returns:

```
{"type":"application.domain.MeasurementChild1","measure":100}
``` 
This is then de-serialized fine, but I would like to avoid the CanonicalName of the class but instead use a defined name. This would make it easier for later refactorings of this class.

**Comment by sandwwraith** [comment]
The solution to this is to override `val descriptor: SerialDescriptor` with a descriptor with serial name you desire
