### ISSUE TITLE
Option to show small Double values not in exponential format in JSON

### ISSUE THREAD

**Issue by mevogt** [Kotlin/kotlinx.serialization#1262]
I'm looking for a way, that small Double values are not represented in exponential format within the JSON?

e.g. instead {"value": 1.0E-4}  it should show {"value": 0.0001}

I've created a custom serializer using encodeString, but unfortunately there is no way to tell the encoder, that it should not print the quotes.

Is there a workaround?

(I'm using Version 1.0.1)

**Comment by sandwwraith** [comment]
There's not such setting yet. Doubles are formatted in the same way as `double.toString()`. Do you have any particular use-case for that setting? Because JSON format does not give precedence to exponential format among the others

**Comment by shanshin** [comment]
Implemented in https://github.com/Kotlin/kotlinx.serialization/pull/2041
