### ISSUE TITLE
PolymorphicSerializer does not support nested classes

### ISSUE THREAD

**Issue by adecker89** [Kotlin/kotlinx.serialization#127]
```
sealed class Foo {
   @Serializable
   class A : Foo()

   @Serializable
   class B : Foo()
}

@Serializable
data class FooWrapper(
  @Serializable(with = PolymorphicSerializer::class) val foo: Foo
)
```

I've found that the above structure does not work for me and throws a `ClassNotFoundException` on deserialization. Whereas moving A and B outside of Foo does work. 

I believe that this because the serialization writes the class name as Foo.A rather than Foo$A, but I haven't looked any further than that yet.

**Comment by sandwwraith** [comment]
Indeed, it's impossible to load a nested class without `$` in name. However, since this is implementation detail of JVM platform, it is really unwanted that dollar symbols would be included in serial class name. Probably this part requires more accurate design.

**Comment by adam-arold** [comment]
#145 is related, with some more details with what causes the problem. It seems that replacing this line:

> at kotlinx.serialization.internal.SerialCache.lookupSerializer$kotlinx_serialization_runtime(Polymorphic.kt:76)

    val klass = preloadedClass ?: Class.forName(className).kotlin

with something like

    val klass = preloadedClass ?: Class.forName(className.replace(".", "$").kotlin

should do the trick.

**Comment by vokilam** [comment]
Another weird way is to use `@SerialName` on a class.

```
sealed class Foo {
   @Serializable
   @SerialName("Foo\$A")
   class A : Foo()

   @Serializable
   @SerialName("Foo\$B")
   class B : Foo()
}
```

**Comment by sandwwraith** [comment]
This should not be an issue with 1.3.30/0.11.0 since polymorphic serialization has been reworked and does not use JVM names/reflection anymore.
