### ISSUE TITLE
Serialization of generic classes in Kotlin/Native causes memory leaks

### ISSUE THREAD

**Issue by darvld** [Kotlin/kotlinx.serialization#1274]
Any generic class instance, even one with a primitive type parameter, causes a memory leak when it is serialized.
Edit: the same thing occurs both with Json and ProtoBuf formats, I don't know if it's related to the formatters or the serialization phase itself.

**To Reproduce**
```

@Serializable
public data class Data<T>(
    val a: T,
    val b: Boolean
)

public fun main(){
    val a = Json.encodeToString(Data(4))
}
```

**Expected behavior**
Running the above produces the following message:
```
Memory leaks detected, 1 objects leaked!
Use `Platform.isMemoryLeakCheckerActive = false` to avoid this check.
```

**Environment**
 - Kotlin version: [1.4.20]
 - Library version: [1.4.20]
 - Kotlin platforms: [Native]
 - Gradle version: [e.g. 6.5.1]
 - IDE version: IntellijIDEA 2020.3
 - Platform: Windows 10 x64

**Comment by vpadmnabh** [comment]
I am facing similar issue while running on iOS platform inside `decodeFromString()` function.

**Comment by darvld** [comment]
Any updates on this yet?

**Comment by RickorDD** [comment]
the same problem with my data class.

![bildschirmfoto_2021-04-18_um_11 58 40](https://user-images.githubusercontent.com/6922544/115183871-f2b30580-a0dc-11eb-9836-15e75ec4c2e1.png)
![bildschirmfoto_2021-04-18_um_11 59 32](https://user-images.githubusercontent.com/6922544/115183914-078f9900-a0dd-11eb-892d-b4bfde13995e.png)

**Comment by sandwwraith** [comment]
Not yet. Is it a blocker?

**Comment by KevinBassaDevelopment** [comment]
Currently its rated as blocker for the future release of the application, as it must not contain memory leaks.

**Comment by checoalejandro** [comment]
I am facing a huge memory leak in iOS also when doing `Json.encodeToString(Data(4))`. I have an object class with a method that does manipulate JsonObjects. As soon as it gets called, simply goes up to 500MB and never frees up.

How can I force this to be freed? Should I use WeakReference?

kotlinx.serialization: 1.5.0

**Comment by checoalejandro** [comment]
Thanks for the update, if anything helps, I was sending a big String to be serialized to a JsonElement (JsonObject). Many items were sent as such, making memory to go high. These were used through utils inside an `object`. Is there any recommendation to help the memory model to free up some of this?
Any workaround to avoid as much as possible this retention?

Thanks.

**Comment by app-z** [comment]
reified ? in inline function

**Comment by sandwwraith** [comment]
I wasn't able to reproduce this leak. Does anyone has an iOS project that demonstrates the issue?

**Comment by darvld** [comment]
The original issue was found long before the new memory manager for Kotlin/Native was available. I haven't been able to reproduce it with modern versions, so I'll close this. Feel free to reopen if any new reproducers are found.
