### ISSUE TITLE
Json.encodeToString() strips out default values if arguments are not provided explicitly to the constructor.

### ISSUE THREAD

**Issue by zr-faisal** [Kotlin/kotlinx.serialization#1278]

**Comment by shanshin** [comment]
Default values of properties are not encoded by default. To encode it you need to change Json format property
```val format = Json { encodeDefaults = true }```

See https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#encoding-defaults

**Comment by pdvrieze** [comment]
This is intended behaviour, not a bug.
