### ISSUE TITLE
Concurrent access to Json raises a SIGSEV invalid memory reference

### ISSUE THREAD

**Issue by zeapo** [Kotlin/kotlinx.serialization#1279]
Calling a function that would decode a json using a shared Json object, the caller crashes with a SIGSEV. 

**To Reproduce**
Given the following code:
```kotlin
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject

@SharedImmutable
val parser = Json.Default

fun decode() {
    parser.decodeFromString(JsonObject.serializer(), """ { } """)
}
```
If we call this function from Rust on multiple threads it fails, however doing it sequentially it works fine. 

In the changelog for 0.11.1 there was a reference to issues #441 and #446 that look pretty similar to my issue above.
(edit: removed irrelevant reference)

**Expected behavior**
Should not crash

**Environment**
 - Kotlin version: [1.4.21]
 - Library version: [1.0.1]
 - Kotlin platforms: [native]
 - Gradle version: [6]

**Comment by qwwdfsad** [comment]
Was fixed with your PR :) Thanks!
