### ISSUE TITLE
How can I replace built in serialize such like primitives

### ISSUE THREAD

**Issue by NamekMaster** [Kotlin/kotlinx.serialization#1281]
My json looks like this:
`{"x": 10.0, "y": 0.0}`

The x and y are Int actually, but when I try to deserialize it with the Int type, I got NumberFormatException.
How can I replace the built in IntSerializer to my custom serializer to decode int as float, Is it possible ?

I tried this but not working, it never invoked :
```
@Serializer(forClass = Int::class)
object IntAsFloatSerializer : KSerializer<Int> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("com.sumavision.www.launcher.parser.IntAsFloatSerializer",
            PrimitiveKind.INT)

    override fun serialize(encoder: Encoder, value: Int): Unit = encoder.encodeInt(value)
    override fun deserialize(decoder: Decoder): Int = decoder.decodeFloat().toInt()
}
```

**Comment by shanshin** [comment]
To override builtin int serializer you may use `UseSerializers` annotation
https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#specifying-serializers-for-a-file
this takes effect for int holders defined in files marked by the annotation.

Or if there are few int holders you may specify serializer on a property
```
@Serializable
data class IntHolder(@Serializable(with = IntAsFloatSerializer::class) val i: Int)
```
https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#specifying-serializer-on-a-property

**Comment by NamekMaster** [comment]
I don't want to change property type to IntHolder, but I found it works with specify serializers for a file or contextual way for `Int`, so it's solved, thanks very much
