### ISSUE TITLE
Type not set in json for a second serialization of same var

### ISSUE THREAD

**Issue by Atatorus** [Kotlin/kotlinx.serialization#1283]
**Describe the bug**
I have a hierachy with an abstract class  `Project`, and two concrete class, `OwnedProject` and `ProjectWithVersion`. If I serialize a variable of type `Project` equals to `OwnedProject`, I get the type discriminator in JSON. But when I reassign my variable to `ProjectWithVersion` and serialize it, I have no type discriminator in JSON.

**To Reproduce**
    
    val module = SerializersModule {
        polymorphic(Project::class) {
            subclass(ProjectWithVersion::class)
            subclass(OwnedProject::class)
        }
    }

    val format = Json { serializersModule = module }

    @Serializable
    abstract class Project {
        abstract val name: String
    }

    @Serializable
    @SerialName("owned")
    data class OwnedProject(override val name: String, val owner: String) : Project()

    @Serializable
    @SerialName("versioned")
    data class ProjectWithVersion(override val name: String, val version: Int): Project()

    fun main() {
        var data: Project = OwnedProject("kotlinx.coroutines", "kotlin")
        var json = format.encodeToString(data)
        println(json)
        data = format.decodeFromString(json)
        println(data)

        data = ProjectWithVersion("kotlinx.coroutines", 42)
        json = format.encodeToString(data)
        println(json)
        data = format.decodeFromString(json)
        println(data)
    }

Output : 

    {"type":"owned","name":"kotlinx.coroutines","owner":"kotlin"}
    OwnedProject(name=kotlinx.coroutines, owner=kotlin)
    {"name":"kotlinx.coroutines","version":42}
    Exception in thread "main" kotlinx.serialization.json.internal.JsonDecodingException: Polymorphic serializer was not found for missing class discriminator ('null')

But if I cast my variable as its own type, ie `Project`, it works :

    fun main() {
        var data: Project = OwnedProject("kotlinx.coroutines", "kotlin")
        var json = format.encodeToString(data)
        println(json)
        data = format.decodeFromString(json)
        println(data)

        data = ProjectWithVersion("kotlinx.coroutines", 42) as Project
        json = format.encodeToString(data)
        println(json)
        data = format.decodeFromString(json)
        println(data)
    }

Output : 

    {"type":"owned","name":"kotlinx.coroutines","owner":"kotlin"}
    OwnedProject(name=kotlinx.coroutines, owner=kotlin)
    {"type":"versioned","name":"kotlinx.coroutines","version":42}
    ProjectWithVersion(name=kotlinx.coroutines, version=42)

**Expected behavior**
I expect I don't have to cast my variable `data` in its own type.

**Environment**
 - Kotlin version: 1.4.21
 - Library version: 1.0.1
 - Kotlin platforms: JVM
 - OS version : Ubuntu 20.04.1 LTS

**Comment by shanshin** [comment]
In your example when you reassign a variable smart cast happens so the compiler accepts that `data` have `ProjectWithVersion` type. So the compiler gives to the library `ProjectWithVersion` as a reified type and the library uses its serializer.

As the serialization library can't change this compiler behavior and you want always use polymorphic serialization you may use an explicit serializer definition
```
        var data: Project = OwnedProject("kotlinx.coroutines", "kotlin")
        var json = format.encodeToString(Project.serializer(), data)
        println(json)
        data = format.decodeFromString(Project.serializer(), json)
        println(data)

        data = ProjectWithVersion("kotlinx.coroutines", 42)
        json = format.encodeToString(Project.serializer(), data)
        println(json)
        data = format.decodeFromString(Project.serializer(), json)
        println(data)
```

**Comment by Atatorus** [comment]
That works, thanks. I hadn't thought to smart cast
