### ISSUE TITLE
Class <classname> is not externally serializable for class with custom serializer

### ISSUE THREAD

**Issue by pdvrieze** [Kotlin/kotlinx.serialization#129]
I fully understand that there are requirements on serializability of classes, but I'm writing a custom serializer for this purpose. I want to be able to do so without this causing a compilation error. The error can also provide a bit more explanation as to what makes the "not externally serializable" bit true.

**Comment by sandwwraith** [comment]
It is stated somewhere in the [docs](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/examples.md): 

> External deserialization (annotation @Serializer(forClass=...)) has more limitations: it supports only primary constructor's vals/vars and class body var properties with visibility higher than protected. Body val properties and all private properties are unseen for external serializer/deserializer.

It's likely that your class has primary constructor parameters which are not properties; in that case, it's unclear how to store them so that constructor can be called later

**Comment by pdvrieze** [comment]
If I'm providing a custom serializer there is no problem that the system doesn't know, I do, and I'm writing the custom serializer. No "default" serializer should be generated in this case.

**Comment by pdvrieze** [comment]
Actually the "fix" seems to be not to have a primary constructor

**Comment by sandwwraith** [comment]
If I understand you right, you've wrote custom serializer with overriden `save` and `load` methods and left `@Serializer(forClass..)` on it to generate other boilerplate?

**Comment by pdvrieze** [comment]
Yes, that is correct. I also left `@Serializable` on the class itself (the companion is the serializer so that it will be the default/only serializer.

**Comment by sandwwraith** [comment]
Then indeed, this check is performed even class have not-generated save and load methods. I should investigate if it is possible to relax this restriction. Probably not, because auto-generated implementation of `serialClassDesc` also tries to iterate all properties, which triggers this exception.

**Comment by pdvrieze** [comment]
Would it be possible to omit the annotation but have the serializer still picked up (I can live with writing the desc by hand although the autogenerated description works correctly).

**Comment by sandwwraith** [comment]
If you have this class in some other serializable classes, you can just use `@Serializable(with=...)` annotation on properties of this type. Or use context mechanism

**Comment by pdvrieze** [comment]
I know I can use that, but I want to define the default picked up serializer. I have full control so the caller shouldn't be burdened with finding out a correct serializer. Perhaps the semantics of `@Serializable(with=...)` on a type (rather than a field) should be to make that class the default serializer for the annotated class.

**Comment by sandwwraith** [comment]
As far as I understand the issue, this commit in 1.3.20 fixes it: https://github.com/JetBrains/kotlin/commit/5f2cea917f7ec74b2bdab2818ebc700a80b6e43f
