### ISSUE TITLE
Polymorphic Serialization throwing ClassCastException in nodeJs app

### ISSUE THREAD

**Issue by minaEweida** [Kotlin/kotlinx.serialization#1290]
I am using Kotlin Serialization in my KMP library and supporting JS as one of the platforms.

I am publishing my lib to our internal npm registry and using it for our NodeJs apps. This lib is registering polymorphic serializers to our data classes and everything used to work fine on our apps when we were using `Kotlin 1.3.71` and `Kotlinx Serialization 0.20.0`.

Recently we upgraded to `Kotlin 1.4.20` and `Kotlinx Serialization 1.0.1` and everything worked as expected for all supported platforms for the lib
- Android
- JVM
- IOS
- JS (Kotlin JS tests passes)
However when trying to use the published version with our npm, it fails to register polymorphic serializers and throwing `ClassCastException`

```
/mylibpath/build/js/node_modules/kotlin/kotlin.js:43108
      throw new ClassCastException('Illegal cast');
      ^
ClassCastException: Illegal cast
    at Object.captureStack (/mylibpath/build/js/node_modules/kotlin/kotlin.js:39116:15)
    at ClassCastException.Exception [as constructor] (/mylibpath/build/js/node_modules/kotlin/kotlin.js:39443:14)
    at ClassCastException.RuntimeException [as constructor] (/mylibpath/build/js/node_modules/kotlin/kotlin.js:39469:17)
    at RuntimeException_init_0 (/mylibpath/build/js/node_modules/kotlin/kotlin.js:39480:24)
    at new ClassCastException (/mylibpath/build/js/node_modules/kotlin/kotlin.js:39599:7)
    at throwCCE_0 (/mylibpath/build/js/node_modules/kotlin/kotlin.js:43108:13)
    at PolymorphicModuleBuilder.buildTo_gz4556$ (/mylibpath/build/js/packages_imported/kotlinx-serialization-kotlinx-serialization-core-jsLegacy/1.0.1/kotlinx-serialization-kotlinx-serialization-core-jsLegacy.js:4905:121)
    at serializers$lambda (/mylibpath/nodesampleapp/node_modules/some_module/kotlin/some_module:38:15)
    at UnsafeLazyImpl.get (/mylibpath/build/js/packages_imported/kotlin/1.4.21/kotlin.js:57266:58)
    at get_serializers (/mylibpath/nodesampleapp/node_modules/some_module/kotlin/some_module.js:43:24) {
  'message_8yp7un$_0': 'Illegal cast',
  'cause_th0jdv$_0': null,
  name: 'ClassCastException'
```
This is thrown when trying to add `subclasses`
You can find the javascript code that fails below

```
  PolymorphicModuleBuilder.prototype.buildTo_gz4556$ = function (builder) {
    if (this.baseSerializer_0 != null)
      builder.registerPolymorphicSerializer_yca12w$(this.baseClass_0, this.baseClass_0, this.baseSerializer_0);
    var tmp$;
    tmp$ = this.subclasses_0.iterator();
    while (tmp$.hasNext()) {
      var element = tmp$.next();
      var kclass = element.component1()
      , serializer = element.component2();
      var tmp$_0;
      var tmp$_1;
      builder.registerPolymorphicSerializer_yca12w$(this.baseClass_0, Kotlin.isType(tmp$_0 = kclass, KClass) ? tmp$_0 : throwCCE(), Kotlin.isType(tmp$_1 = serializer, KSerializer) ? tmp$_1 : throwCCE());
    }
```
And the reason is `tmp$_0 = kclass` which is the data class I am registering (which used to work perfectly fine) is no longer of type `KClass` where `KClass` is 

```
var KClass = Kotlin.kotlin.reflect.KClass;
```
Which is similar to the one in V0.20.0

I changed registration of classes as per the documentation 

```    
SerializersModule {
        fun PolymorphicModuleBuilder<SystemConfiguration>.registerSystemConfigurationSubclasses() {
            subclass(SomeConfiguration1::class, SomeConfiguration1.serializer())
            subclass(SomeConfiguration2::class, SomeConfiguration2.serializer())
            subclass(SomeConfiguration3::class, SomeConfiguration3.serializer())
            default { SomeConfiguration1.serializer() }
        }
        polymorphic(SystemConfiguration::class) { registerSystemConfigurationSubclasses() }
    }
```

This is how I create my json object
```
    Json {
        isLenient = true
        ignoreUnknownKeys = true
        allowSpecialFloatingPointValues = true
        useArrayPolymorphism = true
        encodeDefaults = true
        serializersModule = serializers
    }
```

This code is passing serialization tests for JS but when using in nodeJs it does not work and I cannot understand why.
I have attached screenshots that shows that same object used to return `true` when checking against `KClass` and same object returning `false` when using the newer version using `1.0.1`

<img width="393" alt="Screen Shot 2021-01-12 at 4 19 22 PM" src="https://user-images.githubusercontent.com/20396931/104324309-b3cf4b80-5500-11eb-8979-a43f6d7d64bc.png">
<img width="490" alt="Screen Shot 2021-01-12 at 4 40 43 PM" src="https://user-images.githubusercontent.com/20396931/104324317-b5990f00-5500-11eb-9fa5-c41a9b8b479a.png">

I can understand why this type check is done `Kotlin.isType(tmp$_0 = kclass, KClass)`
It's because function signature is expecting a `KClass`
```
    internal fun <Base : Any, Sub : Base> registerPolymorphicSerializer(
        baseClass: KClass<Base>,
        concreteClass: KClass<Sub>,
        concreteSerializer: KSerializer<Sub>,
        allowOverwrite: Boolean = false
    )
```    
So previously it used to be a KClass, what changed that caused it to fail?
Is there something wrong in my code? Or is there something wrong in Kotlinx serialization latest version?
Or is this related to Kotlin 1.4 release and not related to Kotlinx serialization?

**Environment**
 - Kotlin version: 1.4.20
 - Library version: 1.0.1
 - Kotlin platforms: JS
 - Gradle version: 6.6.1

**Comment by minaEweida** [comment]
@sandwwraith also wanted to ask if is this a valid bug that you were able to reproduce or it's something wrong from my side?

**Comment by sandwwraith** [comment]
@minaEweida Sorry, I haven't been able to look into this thoroughly. I'll return to you when I have more info

**Comment by minaEweida** [comment]
Hello @sandwwraith, do you have updates regarding this one?

**Comment by sandwwraith** [comment]
@minaEweida No, no updates 😞 . Meanwhile, is this a legacy JS compiler or IR one? If it's a legacy, and it is a backend bug, I suggest to migrate to IR

**Comment by sandwwraith** [comment]
Closing as a bug in legacy JS backend.
