### ISSUE TITLE
SerializersModule doesn't prefer either contextual or subclass over plugin-generated serializers

### ISSUE THREAD

**Issue by benkuly** [Kotlin/kotlinx.serialization#1306]
**Describe the bug**
I have many serializers, which are build at runtime and customize the plugin-generated serializers. SerializersModule does not select them. It instead always uses the plugin-generated serializers.

**To Reproduce**
```kotlin
package com.issue

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.*
import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.contextual
import kotlinx.serialization.modules.polymorphic
import kotlinx.serialization.modules.subclass
import kotlin.test.Test
import kotlin.test.assertEquals

class IssueTest {

    @Serializable
    abstract class Project {
        abstract val name: String
    }

    @Serializable
    @SerialName("owned")
    class OwnedProject(override val name: String, val owner: String) : Project()

    class CustomOwnedProjectSerializer(private val customField: String) :
        JsonTransformingSerializer<OwnedProject>(OwnedProject.serializer()) {
        override fun transformSerialize(element: JsonElement): JsonElement {
            require(element is JsonObject)
            return JsonObject(
                mapOf(
                    "customType" to JsonPrimitive("project.owned"),
                    "customField" to JsonPrimitive(customField),
                    *element.entries.map { Pair(it.key, it.value) }.toTypedArray()
                )
            )
        }
    }

    val module = SerializersModule {
        contextual(CustomOwnedProjectSerializer("unicorn"))
        polymorphic(Project::class) {
            subclass(CustomOwnedProjectSerializer("unicorn"))
        }
    }

    val format = Json { serializersModule = module }


    @Test
    fun test() {
        val data = OwnedProject("kotlinx.coroutines", "kotlin")
        val expectedJson =
            """{"customType":"project.owned","customField":"unicorn","name":"kotlinx.coroutines","owner":"kotlin"}"""
        assertEquals(expectedJson, format.encodeToString(CustomOwnedProjectSerializer("unicorn"), data)) // works
        assertEquals(expectedJson, format.encodeToString<Project>(data)) // does not work
        assertEquals(expectedJson, format.encodeToString(data)) // does not work
    }
}
```

**Expected behavior**
I expect, that SerializersModule prefers registered serializers over plugin-generated serializers.

**Environment**
 - Kotlin version: 1.4.21
 - Library version: 1.0.1
 - Kotlin platforms: multiplatform (JVM/JS/Native)]
 - Gradle version: 6.8

**Comment by sandwwraith** [comment]
In your case, because the class is `@Serializable`, it's default serializer is a generated one (and you need this annotation because of #1169 not resolved yet).

What I can recommend here: use ` format.encodeToString(CustomOwnedProjectSerializer("unicorn"), data))` as in your example. Also, you registered your custom serializer for polymorphism correctly, but it doesn't kick in because the static type is not polymorphic (see here: #1280). You can use explicit parent type to work this around: `val data: Project = OwnedProject("kotlinx.coroutines", "kotlin")` or `format.encodeToString<Project>(data)`

**Comment by benkuly** [comment]
Hm okay thank you :)
Because I use Ktor using `format.encodeToString` isn't really an option and using explicit parent type does not work if I expect OwnedProject from ktor as return type...

I still think it's an bug or at least badly documented or an unusual behaviour. `SerializersModule` feels like an option to use  runtime generated serializers, but as I understand you correctly it isn't?

**Comment by sandwwraith** [comment]
`SerializersModule` is intended to be used with `@Contextual` or `@Polymorphic` annotations

**Comment by benkuly** [comment]
Okay thanks! Are there plans that it will change to support also top level types like `Project` or `OwnedProject`?

**Comment by benkuly** [comment]
`format.encodeToString<Project>(data)` does not work:
```
Expected :{"customType":"project.owned","customField":"unicorn","name":"kotlinx.coroutines","owner":"kotlin"}
Actual   :{"type":"kotlin.collections.LinkedHashMap","customType":"project.owned","customField":"unicorn","name":"kotlinx.coroutines","owner":"kotlin"}
```

**Comment by benkuly** [comment]
@sandwwraith any idea?

**Comment by shanshin** [comment]
This is a bug in polymorphism using `JsonTransformingSerializer` child serializer: #1329.
As a temporary workaround, you may try to create a surrogate class (see https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#composite-serializer-via-surrogate).
