### ISSUE TITLE
Constant fields ignored when initialized on declaration

### ISSUE THREAD

**Issue by carlosjrtee** [Kotlin/kotlinx.serialization#1309]
I use field "kind" as a class discriminator which I originally declared as for all serialized types:

data class ClassA(
    val otherFieldA: String? = null,
    val otherFieldB: String
) {
    val kind = ClassA::class.simpleName!!
}

The field is serialized normally in 0.20 but after upgrading to 1.0 and Kotlin 1.4, it's been missing from the generated JSON. Through trial and error, setting the value in the init clause seems to fix the issue:

    override val kind: String

    init {
        kind = ClassA::class.simpleName!!
    }

Also, the issue isn't limited to just the class discriminator. It seems that any field that's been declared and initialized immediately are being ignored.

**Environment**
 - Kotlin version: 1.4.21
 - Library version: 1.0.1
 - Kotlin platforms: Android
 - Gradle version: 6.7.1
 - IDE version: Android Studio 4.2 Beta 3

**Comment by shanshin** [comment]
Currently, initial property values are not encoded by default.
If you want to encode the default value you need to create Json format like this:
```
        val format = Json { encodeDefaults = true }
        println(format.encodeToString(ClassA("A", "B")))
```
will print `{"otherFieldA":"A","otherFieldB":"B","kind":"ClassA"}`
See https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#encoding-defaults

**Comment by carlosjrtee** [comment]
Thanks @shanshin! Setting the encodeDefaults flag worked.
