### ISSUE TITLE
Is Json.decodeFromString<*>("") still experimental?

### ISSUE THREAD

**Issue by dbearded** [Kotlin/kotlinx.serialization#1314]
**What is your use-case and why do you need this feature?**
After reading https://blog.jetbrains.com/kotlin/2020/10/kotlinx-serialization-1-0-released/ I'm unable to call `Json.decodeFromString<*>("")` without enabling Experimental Features. Here is my build.gradle:

```
plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'org.jetbrains.kotlin.plugin.serialization' version "1.4.21"
}

android {
    ...
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    ....
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.4.21"
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:1.0.1"
}
```

**Describe the solution you'd like**
Per the examples shown in the blog, I assume this is possible without enabling Experimental Featuers. Am I misconfigured?

**Comment by dbearded** [comment]
Issue was a gradle misconfiguration

**Comment by treenoder** [comment]
Same issue. How was it solved for you?
