### ISSUE TITLE
@file:UseSerializers is ignored in polymorphism

### ISSUE THREAD

**Issue by krottv** [Kotlin/kotlinx.serialization#1318]
**Describe the bug**

`@file:UseSerializers` is ignored in polymorphism

**To Reproduce**
```
@file:UserSerializers(MediaImageSerializer::class)

@Serializable
sealed class Media()

@SerialName("image")
@Serializable
data class MediaImage(...): Media()

object MediaImageSerializer : JsonTransformingSerializer<MediaImage>(MediaImage.serializer()) 

//somewhere else
fun deserialize(testJson: String) {
   val obj: MediaImage = json.decodeFromString(testJson)
   //wrong serializer is used
}
```

And still the default serializer is used. I tried to put the annotation at any file, from where we call, etc. Doesn't have any effect

**Expected behavior**

MediaImageSerializer is used

**Environment**
 - Kotlin version: 1.4.21
 - Library version: 1.0.1
 - I was testing it in android/src/test with junit 4

**Comment by shanshin** [comment]
`UseSerializers(MediaImageSerializer::class)` annotation acts on the property of class declared in the same file where present  `@file:UseSerializers`.
e.g. 
```
@file:UseSerializers(MediaImageSerializer::class)

package my.package

import kotlinx.serialization.*
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.json.JsonTransformingSerializer

@Serializable
sealed class Media

@SerialName("image")
@Serializable
data class MediaImage(val a: Int): Media()

@Serializable
data class MediaHolder(val media: MediaImage) // property media will be decoded by MediaImageSerializer

object MediaImageSerializer : JsonTransformingSerializer<MediaImage>(MediaImage.serializer()) {
    override fun transformDeserialize(element: JsonElement): JsonElement {
        // do smth
        return super.transformDeserialize(element)
    }
}
```

If you want to change the serializer for top-level class when calling `decodeFromString` you may define it explicitly
```
val obj: MediaImage = Json.decodeFromString(MediaImageSerializer, testJson)
```

**Comment by krottv** [comment]
@shashin Yes. But it just doesn't work for polymorphism. 

I declared the annotation where I had the propery `media: Media` and it didn't use the serializer I have specified

**Comment by pdvrieze** [comment]
Looking at the code, polymorphism shouldn't be relevant here. 
In this code you are using the shortcut method to get the serializer automatically from the context. What seems to be the case is that the code that does that does not follow `@file:UseSerializers`. That annotation is mainly to help with specifying serializers for properties (in generated serializers).

In this case the correct way to deserialize is:
```
val obj: MediaImage = json.decodeFromString(MediaImageSerializer, testJson)
```

**Comment by krottv** [comment]
@pdvrieze 
Okay let me clarify the example

What if we use Media base class and we don't know which type it will be?

`
val obj: Media = json.decodeFromString(testJson)
}`

**Comment by shanshin** [comment]
@krottv You are using only `JsonTransformingSerializer` as a child serializer or can use another?

**Comment by pdvrieze** [comment]
> @pdvrieze 
> Okay let me clarify the example
> 
> What if we use Media base class and we don't know which type it will be?
> 
> `val obj: Media = json.decodeFromString(testJson)`

In this case you need to have a serializersModule with the mappings declared. Btw. If I am not mistaken you can use a contextual declaration to allow the non-polymorphic case to work without specifying the serializer explicitly.

**Comment by krottv** [comment]
@pdvrieze 
Contextual doesn't fit the case, because It's polymorphic.
I do have mappings declared. The problem is with retaining original serializer, because my custom serializer references it. #1310
This is why I was suggested to use file:UseSerializers which doesn't work with polymorphism.

**Comment by krottv** [comment]
@pdvrieze Okay. I got it. We can specify our serializer in 
```
polymorphic(Media::class) {
            subclass(MediaTextSerializer) }
```
      This solved the problem.

**Comment by shanshin** [comment]
@krottv Is `JsonContentPolymorphicSerializer` applicable to your case?
As `JsonTransformingSerializer` now doesn't work correctly with  polymorphism you can try warkouround with custom deserialization.
See https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#content-based-polymorphic-deserialization

**Comment by krottv** [comment]
@shanshin Thanks. I will try this workaround. Seems it can solve the problem for now, but it's not the most elegant solution

**Comment by sandwwraith** [comment]
To sum up, the problem is in the fact that when we create `Media` serializer, we collect all serializers for subclasses (including `MediaImage`), and default serializer is used there, instead of one specified in the `@file:UseSerializers`. I would say that this behavior is 'As Designed', because Sealed serializer uses __default__ serializers for subclasses. Default serializer can be only generated one or one specified in the `@Serializable(with = ...)` annotation __on the class__.

I would also note that with `@KeepGeneratedSerializer` added in 2.0.20, you can make `MediaImageSerializer` a default serializer for `MediaImage`. Simply delegate to the generated serializer: `object MediaImageSerializer : JsonTransformingSerializer<MediaImage>(MediaImage.generatedSerializer())`.
