### ISSUE TITLE
Sealed Generic with Concrete Subtypes fails

### ISSUE THREAD

**Issue by set321go** [Kotlin/kotlinx.serialization#1320]
```
@Serializable
sealed class Property<T> {
  abstract val name: String
  abstract fun valueAsType(value: String): T
}

@Serializable
@SerialName("stringProperty")
data class StringProperty(override val name: String): Property<String> {
  override fun valueAsType(value: String) = value
}
 ```

When I try to deserialize json into this structure i get `JsonDecodingException: Polymorphic serializer was not found for class discriminator 'stringProperty'` when using this json `{"type":"stringProperty","name":"bar"}`

I also tried to define the following `SerializersModule` but I still got the same error
```
    val propertySerializerModule = Json {
        SerializersModule {
            polymorphic(Property::class) {
                subclass(StringProperty::class, StringProperty.serializer())
            }
        }
    }
```
When i attempted to add an argument to the subclass serializer as in the docs [Polymorphism and generic classes](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md#polymorphism-and-generic-classes), I get a to many arguments error from the compiler

**Comment by shanshin** [comment]
May you show the full example of deserialization and clarify versions of the plugin and serialization runtime?

This is an example of working code 
```
@Serializable
sealed class Property<T> {
    abstract val name: String
    abstract fun valueAsType(value: String): T
}

@Serializable
@SerialName("stringProperty")
data class StringProperty(override val name: String): Property<String>() {
    override fun valueAsType(value: String) = value
}

...

  val property = Json.decodeFromString(Property.serializer(PolymorphicSerializer(Any::class)),"""{"type":"stringProperty","name":"bar"}""")
  println(property)
```
it will print `StringProperty(name=bar)`
