### ISSUE TITLE
Optional property unexpectedly not serialized for JSON serialization

### ISSUE THREAD

**Issue by Whathecode** [Kotlin/kotlinx.serialization#1321]
**Describe the bug**
I'm not 100% certain this is a bug, but it might warrant updating the documentation on [optional property initializers](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/basic-serialization.md#optional-property-initializer-call) or limiting the possible initializers for serializable classes.

[_"Default values of properties are not encoded by default, because they will be reconstructed during decoding anyway."_](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#encoding-defaults) However, in case the initializer returns a runtime value which changes over time, i.e., which is not a compile-time constant, some unexpected behavior occurs. Whether or not the value is serialized seems to depend on hidden/undocumented logic.

**To Reproduce**
```
@Serializable
data class Version( val name: String, val date: DateTime = DateTime.now() )
```

Serializing this, sometimes `data` is added as a JSON key, and other times it is not. A race condition seems to occur. I presume the serializer evaluates `DataTime.now()` and does an equality check with the passed value, dropping the JSON key in the serialized output in case they equal. I still need to verify this in the `kotlinx.serialization` sources, but this is intuitively how I would expect this to be implemented which may explain the observed behavior.

**Expected behavior**
Writing code as listed above, I would expect `date` to always be serialized since it is not a compile-time constant. Of course, the solution here is adding `@Required` to the constructor parameter. But, that annotation seems to carry slightly different semantics: it assumes that the value written will be redundant.

Instead, to prevent people from shooting themselves in the foot (as I have), I would by default serialize non compile-time constants. Or, make optional opt-in for non-compile time constants. Primarily food for thought, no real final expected behavior. :)

**Environment**
 - Kotlin version: 1.4.21
 - Library version: 1.0.1
 - Kotlin platforms: JVM
 - Gradle version: 6.6

**Comment by sandwwraith** [comment]
>  presume the serializer evaluates DataTime.now() and does an equality check with the passed value, dropping the JSON key in the serialized output in case they equal. 

You're absolutely right, that's what happens. Although this can't be verified in kotlinx.serialization sources, you need to decompile `@Serializable` class, since it is a check in generated KSerializer.

Looks like it is just another case for #1091 annotation

**Comment by Whathecode** [comment]
@sandwwraith Seems like it. Interesting that the [`@Required` attribute](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/basic-serialization.md#required-properties) hasn't been mentioned in that thread.

It looks like the proposal in that thread might be a more generic solution in that it is an annotation which can be applied to classes as a whole? To double-check, am I correct in presuming that applying `@Required` in the example I present here will solve my issue?

**Comment by sandwwraith** [comment]
> applying @Required in the example I present here will solve my issue

With race condition, yes. On the other hand, now your `decodeFromString` would fail if `date` is missing from the JSON, because it is a required property now (despite having default value)

**Comment by sandwwraith** [comment]
https://youtrack.jetbrains.com/issue/KT-73994
