### ISSUE TITLE
Serializer to serialize maps as arrays of objects to comply with BSON specifications.

### ISSUE THREAD

**Issue by Whathecode** [Kotlin/kotlinx.serialization#1326]
**What is your use-case and why do you need this feature?**

By default, `Map` gets serialized as a JSON object with each key in the map added as a key to the object. I agree this is the cleanest mapping for this data structure to JSON.

However, I received a bug report from someone using MongoDB, which [disallows periods and dollar signs in keys ('.' and '$')](https://stackoverflow.com/a/9760058/590790). I believe these are BSON requirements.

I don't want infrastructure concerns to seep into my domain model. In my case, it is perfectly fine for the keys I model in this specific map to contain any symbol. Therefore, I prefer to solve this by changing the serializer rather than changing my object (DTO in this case).

**Describe the solution you'd like**

I wrote a custom [`MapAsArraySerializer`](https://github.com/cph-cachet/carp.core-kotlin/blob/develop/carp.common/src/commonMain/kotlin/dk/cachet/carp/common/serialization/MapAsArraySerializer.kt) which serializes `Map`s as arrays of `KeyValue` pairs.

```
/**
 * Serializes a [Map] as an array of JSON objects which each have a "key" and "value"
 * instead of a single JSON object containing values for all keys in the map, which is the default.
 *
 * This is useful when using JSON serialization and the serialized keys in a map violate JSON recommendations.
 * E.g., the key may include discouraged symbols such as '.', or '$' for BSON.
 */
@OptIn( ExperimentalSerializationApi::class )
class MapAsArraySerializer<K, V>(
    private val keySerializer: KSerializer<K>,
    private val valueSerializer: KSerializer<V>
) : KSerializer<Map<K, V>>
{
    @Serializable
    data class KeyValue<K, V>( val key: K, val value: V )

    private val arraySerializer = ArraySerializer( KeyValue.serializer( keySerializer, valueSerializer ) )
    override val descriptor: SerialDescriptor = arraySerializer.descriptor

    override fun deserialize( decoder: Decoder ): Map<K, V> = decoder
        .decodeSerializableValue( arraySerializer )
        .map { it.key to it.value }
        .toMap()

    override fun serialize( encoder: Encoder, value: Map<K, V> ) = encoder
        .encodeSerializableValue(
            arraySerializer,
            value.map { KeyValue( it.key, it.value ) }.toTypedArray()
        )
}
```

This is easy enough, and shows how extensible `kotlinx.serialization` is. 🙏 I simply thought I would share since others might have the same need or run into the same issue. I can create a PR in case there is an interest for it.

**Comment by sandwwraith** [comment]
Great job! By the way, it's also possible to achieve this with `JsonTransformingSerializer`, but you solution is more universal.

**Comment by AvlWx2014** [comment]
This is really cool! I seem to be having trouble with deserialization, though. Deserialize is being called once for each element in the array, rather than for the whole array. So for an array of N items I'm getting N calls with an array of 1 item instead of 1 call for the array of all N items. Any insight as to why that might be happening? For further context I'm doing XML deserialization with https://github.com/pdvrieze/xmlutil.

**Comment by sandwwraith** [comment]
Thanks again for the wonderful example! We don't plan to include it in collection of standard serializers though, so I'll close this for now. Maybe it can become a part of #1931
