### ISSUE TITLE
1.0.x releases are uncomsumable by maven

### ISSUE THREAD

**Issue by brunojcm** [Kotlin/kotlinx.serialization#1328]
**Describe the bug**

**To Reproduce**
We put the following dependency on our project:
```
        <dependency>
            <groupId>org.jetbrains.kotlinx</groupId>
            <artifactId>kotlinx-serialization-json</artifactId>
            <version>1.0.1</version>
        </dependency>
```

The following error shows up:

```
[ERROR] Failed to execute goal on project web-api: Could not resolve dependencies for project co.c.prod.jp:web-api:jar:kotlinSerialization-000100: Could not transfer artifact org.jetbrains.kotlinx:kotlinx-serialization-json:jar:1.0.1 from/to central-maven (http://repo1.maven.org/maven2): Transfer failed for http://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-serialization-json/1.0.1/kotlinx-serialization-json-1.0.1.jar 501 HTTPS Required -> [Help 1]
```

Error message is misleading here, problem is not https at all, the fact is that the folder https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-serialization-json/1.0.1/ does not have any jars at all, just a `module` artifact, which maven is unaware of. Gradle probably handles that well, but maven tries to download a JAR (as it should, since `kotlinx-serialization-json` is not marked as a pom-only artifact) and fails in doing so. It seems that MPP support is breaking maven here.

I tried to upgrade to 1.4.30/1.1.0-RC, but I bumped into this other issue: https://github.com/Kotlin/kotlinx.serialization/issues/1327

It seems that 1.1.x stream is now publishing a jar file, but it forces users to upgrade to Kotlin 1.4.30, which could be hard to do, so I'd like to see a 1.0.2 version of kotlinx.serialization also publishing a jar.

**Expected behavior**
Maven project should build with no issues.

**Environment**
 - Kotlin version: 1.4.21
 - Library version: 1.0.1
 - Kotlin platforms: JVM
 - Maven version: 3.6.3

**Comment by qwwdfsad** [comment]
It's indeed the bug of `kotlinx-serialization` and Kotlin plugin publication mechanism: https://github.com/Kotlin/kotlinx.serialization/issues/1143

It is fixed in 1.1.0-RC, but if you want to stick with a stable version, you can temporarily use `kotlinx-serialization-json-jvm` dependency instead
