### ISSUE TITLE
How to serialize a property of the form "val prop: List<SomeInterface>"

### ISSUE THREAD

**Issue by pajatopmr** [Kotlin/kotlinx.serialization#1333]
I believe this issue reflects, at least, a documentation bug in that it is not clear how to serialize a list property where the list item type is expressed as an interface. When the list item is a class, both documentation and KXS behavior are consistent and correct.

The following code is my best effort to comply with the KXS documentation. The Foo property list serializer is not a compile time constant so the code does not compile. It is not clear to me from the docs how to proceed.

    interface Stuff {
        val prop: String
    }

    @Serializable class StuffImpl(
        override val prop: String) : Stuff

    object StuffSerializer : JsonContentPolymorphicSerializer<Stuff>(Stuff::class) {
        override fun selectDeserializer(element: JsonElement) = StuffImpl.serializer()
    }

    @Test
    fun `When serializing a list of interface implementations, verify the result`() {
        @Serializable class Foo(
            @Serializable(with = ListSerializer(StuffSerializer))
            val list: List<Stuff>
        )

        val json = """{"list":[{"prop":"3"},{"prop":"4"},{"prop":"5"}]}"""
        val data = Foo(listOf(StuffImpl("3"), StuffImpl("4"), StuffImpl("5")))

        assertEquals(json, Json.encodeToString(data))
    }

My expectation is that either the KXS plugin should suggest an approach to resolve the problem that one can find in the docs.

**Environment**
 - Kotlin version: 1.4.30
 - Library version: 1.0.1
 - Kotlin platforms: JVM
 - Gradle version: 6.6.2
 - IDE version (if bug is related to the IDE) [e.g. IntellijIDEA 2019.1, Android Studio 3.4]
 - Other relevant context [e.g. OS version, JRE version, ... ]

**Comment by shanshin** [comment]
In this case, using the interface is similar to using a regular class, only the behavior of the list item serializer is different.
According https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#array-wrapping for your example you may create a custom serializer class and use its class literal like this
```
    interface Stuff {
        val prop: String
    }

    @Serializable
    class StuffImpl(override val prop: String) : Stuff

    object StuffSerializer : JsonContentPolymorphicSerializer<Stuff>(Stuff::class) {
        override fun selectDeserializer(element: JsonElement) = StuffImpl.serializer()
    }

    object StuffListSerializer : KSerializer<List<Stuff>> {
        private val builtIn: KSerializer<List<Stuff>> = ListSerializer(StuffSerializer)

        override fun deserialize(decoder: Decoder): List<Stuff> {
            return builtIn.deserialize(decoder)
        }

        override val descriptor: SerialDescriptor = builtIn.descriptor

        override fun serialize(encoder: Encoder, value: List<Stuff>) {
            builtIn.serialize(encoder, value)
        }

    }

    @Serializable
    class Foo(
        @Serializable(with = StuffListSerializer::class)
        val list: List<Stuff>
    )

    @Test
    fun `When serializing a list of interface implementations, verify the result`() {
        val json = """{"list":[{"prop":"3"},{"prop":"4"},{"prop":"5"}]}"""
        val data = Foo(listOf(StuffImpl("3"), StuffImpl("4"), StuffImpl("5")))

        assertEquals(json, Json.encodeToString(data))
    }
```

Be careful, in this solution `JsonContentPolymorphicSerializer` does not allow to control serialization to string, will be used default serializer or serializer from specified in format `serializersModule` (module in priority) https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#content-based-polymorphic-deserialization.

**Comment by pajatopmr** [comment]
Thank you so much for showing the missing piece (StuffListSerializer). Given the very difficult time I (and others) had understanding how to get to your solution, I will write it up as a PR if desired. Just let me know and feel free to suggest other changes to make the documentation better.

**Comment by soguazu** [comment]
Hi guys, am new to kotlin and kotlinx serializations and i have just been onboarded on a codebase with kotlin and vertx to add validations. 

@Serializable
class RegisterUserRequest(val email: String = "", val password: String = "") {
    var type: String? = null
    var phoneNumber: String? = null
    var firstName: String? = null
    var lastName: String? = null
    var countryCode: String? = null
    var country: String? = null
    var profilePictureUrl: String? = null
    var roles: List<EntityRole> = listOf()
}


data class EntityRole(open var entityId: String, open val role: Role)

I keep getting this error 

Serializer has not been found for type 'EntityRole'. To use context serializer as fallback, explicitly annotate type or property with @Contextual

Please i'll really appreciate it.

**Comment by sandwwraith** [comment]
@soguazu Mark `EntityRole` with `@Serializable`.

**Comment by soguazu** [comment]
@sandwwraith thank you so much
