### ISSUE TITLE
KSerialClassDesc should include the KClass being serialized

### ISSUE THREAD

**Issue by ansman** [Kotlin/kotlinx.serialization#134]
Currently the `KSerialClassDesc` only includes the `name` of the class which makes it hard to load custom serializers for some libraries.

**Comment by pdvrieze** [comment]
@ansman This is because in javascript there is no class object. If you look at the implementation then you see that it uses a multiplatform function that uses `Class.forName` under water.

**Comment by ansman** [comment]
Ah, I thought `KClass` existed in kotlin-js but obviously not `Class`.

But this means that `Class.forName(desc.name)` should pretty much always be safe?

**Comment by sandwwraith** [comment]
While `KClass` exists on JS (but can't provide almost nothing except class name), `Class.forName` totally unavailable on JS, thats why #101 request exists

On JVM, `Class.forName(desc.name)` should work for every `@Serializable` white-listed class except nested (#126 )

**Comment by ansman** [comment]
So what would be the downside of including `KClass` rather than the name? Seems like a more flexible solution?

**Comment by pdvrieze** [comment]
@ansman Except that there currently is no way on javascript to get a serializer for a named type.

**Comment by ansman** [comment]
I don't really understand. If you simply replace `.name` with `.klass` on the descriptor then you could simply name `.name` be `.klass.qualifiedName`?

**Comment by pdvrieze** [comment]
@ansman The code at some point needs to have an actual class object that it can retrieve a serializer for. Javascript has no way to store annotations yet (shouldn't be hard to emulate though)

**Comment by sandwwraith** [comment]
KClass won't be included in descriptor because reflection API is very limited in multiplatform setup and there will be almost no benefit in it.

Instead, suggested approach is to use extended features of `SerialDescriptor` (https://github.com/Kotlin/KEEP/blob/master/proposals/extensions/serialization.md#saving-schemas-with-a-descriptor) to introspect class and obtain information about its properties, their types, and annotations.
