### ISSUE TITLE
Inline class deserialization with decodeFromJsonElement does not work

### ISSUE THREAD

**Issue by jbmolle** [Kotlin/kotlinx.serialization#1342]
Hi,

I'm using the inline class experimental feature and I get an error when I try to deserialize from a JsonElement value.
IDEA gives me the following error:
class kotlinx.serialization.json.internal.JsonDecoderForUnsignedTypes can't retrieve untyped values
 
I have the following:
`@Serializable inline class ResourceId(val id: String)`
`@Serializable inline class ResourceType(val type: String)`
`@Serializable data class ResourceIdentifier(val id: ResourceId, val type: ResourceType)`

The serialization / deserialization of those classes work correctly.
But I can receive either a Json string with a JsonObject or a JsonArray and I need to do content based deserialization to return either a ResourceIdentifier or a list of ResourceIdentifiers.

In the deserialize function if I receive a JsonObject and I do the following, it works:
`val elem = decoder.decodeSerializableElement(descriptor, 0, ResourceIdentifier.serializer())`

If I do the following it also works:
`decoder as? JsonDecoder ?: throw SerializationException("This class can be loaded only by Json")
val jsonElement = input.decodeJsonElement()
if (jsonElement is JsonObject) {
    val elem = decoder.json.decodeFromString(ResourceIdentifier.serializer(), jsonElement.toString())
}`

But with the following I get the error:
`decoder as? JsonDecoder ?: throw SerializationException("This class can be loaded only by Json")
val jsonElement = input.decodeJsonElement()
if (jsonElement is JsonObject) {
    val elem = decoder.json.decodeFromJsonElement(ResourceIdentifier.serializer(), jsonElement)
}`
with error JsonDecoderForUnsignedTypes can't retrieve untyped values

Expected behavior
The last code should work.

Environment
 - Kotlin version: 1.4.30
 - Library version: 1.1.0-RC
 - Kotlin platforms: JVM with IR backend compiler
 - OS: Ubuntu 20.04

**Comment by tadfisher** [comment]
This appears to also break in `JsonContentPolymorphicSerializer`, which uses `decodeFromJsonElement`.
