### ISSUE TITLE
Inconsistent Enum Ordinal

### ISSUE THREAD

**Issue by marvinbuff** [Kotlin/kotlinx.serialization#1347]
**Describe the bug**
The ordinal of enum constants is different when using a constructor or a body.

**To Reproduce**
```
enum class TestA {
  VARIANT_X {
    override val label: String = "hello"
  },
  ;

 abstract val label: String
}

enum class TestB(val label: String) {
  VARIANT_Y("bye 2"),
  ;
}

data class TestData(
    val testA: TestA,
    val testB: TestB
)

val testData = TestData(TestA.VARIANT_X, TestB.VARIANT_Y)
console.log(testData)
```

![image](https://user-images.githubusercontent.com/9862282/108506010-78226100-72b8-11eb-9319-debad2826921.png)

**Expected behavior**
I would expect that both variables have the same ordinal and the `testA` should be of type `TestA`.

**Environment**
 - Kotlin version: [1.4.30]
 - Library version: [1.0.1]
 - Kotlin platforms: [JS Browser]
 - Gradle version: [6.8.2]
 - Other relevant context [React Frontend Project]

**Comment by marvinbuff** [comment]
I just noticed that this has nothing to do with serialization. Sorry about that. I will close this issue. But maybe this is still interesting for you. Because you know, there was a reason I thought the issue was caused by the serialization.

Having the correct ordinal lets me annotate and serialize the `TestB` enum without issue.
```
enum class TestA {
  VARIANT_X {
    override val label: String = "hello"
  },
  ;

 abstract val label: String
}

@Serializable
enum class TestB(val label: String) {
  VARIANT_Y("bye 2"),
  ;
}

@Serializable
data class TestData(
    val testA: TestA,
    val testB: TestB
)

val testData = TestData(TestA.VARIANT_X, TestB.VARIANT_Y)
console.log(testData)
```

However, trying the same with the enum with the -1 ordinal leads to an error when serializing `TestData`:
```
@Serializable
enum class TestA {
  VARIANT_X {
    override val label: String = "hello"
  },
  ;

 abstract val label: String
}

enum class TestB(val label: String) {
  VARIANT_Y("bye 2"),
  ;
}

@Serializable
data class TestData(
    val testA: TestA,
    val testB: TestB
)

val testData = TestData(TestA.VARIANT_X, TestB.VARIANT_Y)
console.log(testData)
```

![image](https://user-images.githubusercontent.com/9862282/108510579-fe41a600-72be-11eb-9c42-21158063baf2.png)

**Comment by sandwwraith** [comment]
Maybe you need to report this to kotl.in/issue . It's rather strange that enums have negative ordinals

**Comment by marvinbuff** [comment]
[Tracked issue](https://youtrack.jetbrains.com/issue/KT-45056)
