### ISSUE TITLE
kotlinx.serialization.SerializationException: Serializer for class 'Any' is not found.

### ISSUE THREAD

**Issue by ohyooo** [Kotlin/kotlinx.serialization#1351]
These codes works on 1.0.1, but on 1.1.0 it throws kotlinx.serialization.SerializationException: Serializer for class 'Any' is not found.

```kt
fun main() {
    val result = json.encodeToString(Encode(ClassA()))
    println(result)
}

val json = Json {
    serializersModule = SerializersModule {
        contextual(ClassA::class, ClassASerializer)
    }
}

@Serializable
data class Encode(val data: @Contextual Any)

abstract class NotSerializableClass

@Serializable(with = ClassASerializer::class)
class ClassA : NotSerializableClass() {
    fun convertTo() = ClassB()
}

@Serializable
class ClassB {
    fun convertTo() = ClassA()
}

@Serializer(forClass = ClassA::class)
object ClassASerializer : KSerializer<ClassA> {
    override val descriptor = PrimitiveSerialDescriptor("WithCustomDefault", PrimitiveKind.STRING)

    override fun serialize(encoder: Encoder, value: ClassA) {
        encoder.encodeSerializableValue(ClassB.serializer(), value.convertTo())
    }

    override fun deserialize(decoder: Decoder): ClassA {
        return decoder.decodeSerializableValue(ClassB.serializer()).convertTo()
    }
}
```

**Environment**
 - Kotlin version: [ 1.4.30 ]
 - Library version: [ 1.1.0 ]
 - Kotlin platforms: [ Android / JVM]

**Comment by KarenkovID** [comment]
Same for me

**Comment by ohyooo** [comment]
> Hi, thanks for the report!
> 
> Unfortunately, contextual serialization was never meant to work this way. It worked due to a mistake in implementation, that was fixed in 1.1.0 (see #1277 for details). As documentation for `ContextualSerializer` says, 'Serializers are being looked for in a [SerializersModule] from the target [Encoder] or [Decoder], using statically known [KClass]". Here statically known KClass is `Any`, so it is being looked up in module instead of `ClassA`.
> 
> If you need to determine serializer dynamically for subtypes of `Any`, I suggest you to use polymorphic serialization.
> 
> If you want only serialization (because deserialization never worked in your example even in 1.0.0), I can suggest a workaround serializer for Any:
> 
> ```kotlin
> @ExperimentalSerializationApi
> class DynamicLookupSerializer: KSerializer<Any> {
>     override val descriptor: SerialDescriptor = ContextualSerializer(Any::class, null, emptyArray()).descriptor
> 
>     override fun serialize(encoder: Encoder, value: Any) {
>         val actualSerializer = encoder.serializersModule.getContextual(value::class) ?: value::class.serializer()
>         encoder.encodeSerializableValue(actualSerializer as KSerializer<Any>, value)
>     }
> 
>     override fun deserialize(decoder: Decoder): Any {
>         error("Unsupported")
>     }
> }
> ```

it works ~

**Comment by apelt** [comment]
If you want any json object use type JsonObject:

```
@Serializable
data class Data(
    val json: JsonObject? //can be any JSON object, e.g.: {"test_key":"test value","test_key_object":{"test_key":"test value"}}
)
```

This works well for both serialization & deserialization:

```
  val s = "{\"json\":{\"test_key\":\"test value\",\"test_key_object\":{\"test_key\":\"test value\"}}}"
  val data = Json.decodeFromString(Data.serializer(), s)
  println("test: \n" + Json.encodeToString(data))
```

**Comment by OnwukaDaniel** [comment]
> > Hi, thanks for the report!
> > Unfortunately, contextual serialization was never meant to work this way. It worked due to a mistake in implementation, that was fixed in 1.1.0 (see #1277 for details). As documentation for `ContextualSerializer` says, 'Serializers are being looked for in a [SerializersModule] from the target [Encoder] or [Decoder], using statically known [KClass]". Here statically known KClass is `Any`, so it is being looked up in module instead of `ClassA`.
> > If you need to determine serializer dynamically for subtypes of `Any`, I suggest you to use polymorphic serialization.
> > If you want only serialization (because deserialization never worked in your example even in 1.0.0), I can suggest a workaround serializer for Any:
> > ```kotlin
> > @ExperimentalSerializationApi
> > class DynamicLookupSerializer: KSerializer<Any> {
> >     override val descriptor: SerialDescriptor = ContextualSerializer(Any::class, null, emptyArray()).descriptor
> > 
> >     override fun serialize(encoder: Encoder, value: Any) {
> >         val actualSerializer = encoder.serializersModule.getContextual(value::class) ?: value::class.serializer()
> >         encoder.encodeSerializableValue(actualSerializer as KSerializer<Any>, value)
> >     }
> > 
> >     override fun deserialize(decoder: Decoder): Any {
> >         error("Unsupported")
> >     }
> > }
> > ```
> 
> it works ~

Everyone is accepting the solution. Please tell how to use it.

**Comment by edgarkhimich** [comment]
`Everyone is accepting the solution. Please tell how to use it.`

Define a serializable class above your param:

@Serializable(with = DynamicLookupSerializer::class)
        val data: Any

**Comment by KittenBall** [comment]
> Hi, thanks for the report!
> 
> Unfortunately, contextual serialization was never meant to work this way. It worked due to a mistake in implementation, that was fixed in 1.1.0 (see #1277 for details). As documentation for `ContextualSerializer` says, 'Serializers are being looked for in a [SerializersModule] from the target [Encoder] or [Decoder], using statically known [KClass]". Here statically known KClass is `Any`, so it is being looked up in module instead of `ClassA`.
> 
> If you need to determine serializer dynamically for subtypes of `Any`, I suggest you to use polymorphic serialization.
> 
> If you want only serialization (because deserialization never worked in your example even in 1.0.0), I can suggest a workaround serializer for Any:
> 
> ```kotlin
> @ExperimentalSerializationApi
> class DynamicLookupSerializer: KSerializer<Any> {
>     override val descriptor: SerialDescriptor = ContextualSerializer(Any::class, null, emptyArray()).descriptor
> 
>     override fun serialize(encoder: Encoder, value: Any) {
>         val actualSerializer = encoder.serializersModule.getContextual(value::class) ?: value::class.serializer()
>         encoder.encodeSerializableValue(actualSerializer as KSerializer<Any>, value)
>     }
> 
>     override fun deserialize(decoder: Decoder): Any {
>         error("Unsupported")
>     }
> }
> ```

I have encountered some problems when Any is String
eg: 
```kotlin
val a:Any = "test string"
```
of course, print(a) is `test string` which without quote

but after encoded by DynamicLookupSerializer, the output is `"test string"`, added quote.

This seems to have a solution after 1.5.0.
```kotlin
 @OptIn(ExperimentalSerializationApi::class)
    object DynamicLookupSerializer : KSerializer<Any> {
        override val descriptor: SerialDescriptor =
            ContextualSerializer(Any::class, null, emptyArray()).descriptor

        @Suppress("UNCHECKED_CAST")
        @OptIn(InternalSerializationApi::class)
        override fun serialize(encoder: Encoder, value: Any) {
            val actualSerializer = encoder.serializersModule.getContextual(value::class)
                ?: value::class.serializer()
            if (value is String) {
                val jsonUnquotedLiteral = JsonUnquotedLiteral(value.takeIf { it != "null" })
                encoder.encodeSerializableValue(JsonPrimitive.serializer(), jsonUnquotedLiteral)
            } else {
                encoder.encodeSerializableValue(actualSerializer as KSerializer<Any>, value)
            }
        }

        override fun deserialize(decoder: Decoder): Any {
            error("Unsupported")
        }
    }
```

If anyone has a better solution, please let me know, thanks.

**Comment by sandwwraith** [comment]
@KittenBall Adding a json unquoted literal with a space character will result in invalid JSON, btw

**Comment by KittenBall** [comment]
> @KittenBall Adding a json unquoted literal with a space character will result in invalid JSON, btw

Thank you very much. I changed it.

```kotlin
@OptIn(ExperimentalSerializationApi::class)
internal object DynamicLookupSerializer : KSerializer<Any> {
    override val descriptor: SerialDescriptor =
        ContextualSerializer(Any::class, null, emptyArray()).descriptor

    @Suppress("UNCHECKED_CAST")
    @OptIn(InternalSerializationApi::class)
    override fun serialize(encoder: Encoder, value: Any) {
        val actualSerializer = encoder.serializersModule.getContextual(value::class)
            ?: value::class.serializer()
        if (value is String) {
            val jsonUnquotedLiteral =
                JsonUnquotedLiteral(value.takeIf { it != "null" && it.isNotBlank() })
            encoder.encodeSerializableValue(JsonPrimitive.serializer(), jsonUnquotedLiteral)
        } else {
            encoder.encodeSerializableValue(actualSerializer as KSerializer<Any>, value)
        }
    }

    override fun deserialize(decoder: Decoder): Any {
        error("Unsupported")
    }
}
```

**Comment by Topper865** [comment]
I have modified it to work with ArrayList types

`
@ExperimentalSerializationApi
class DynamicLookupSerializer: KSerializer<Any> {
    override val descriptor: SerialDescriptor = ContextualSerializer(Any::class, null, emptyArray()).descriptor

    @OptIn(InternalSerializationApi::class)
    override fun serialize(encoder: Encoder, value: Any) {
        if(value is ArrayList<*>){
            encoder.encodeSerializableValue(ListSerializer(DynamicLookupSerializer()), value)
            return
        }
        val actualSerializer = encoder.serializersModule.getContextual(value::class) ?: value::class.serializer()
        encoder.encodeSerializableValue(actualSerializer as KSerializer<Any>, value)
    }

    override fun deserialize(decoder: Decoder): Any {
        error("Unsupported")
    }
}
`
