### ISSUE TITLE
Watchos x64 missing

### ISSUE THREAD

**Issue by PaulWoitaschek** [Kotlin/kotlinx.serialization#1357]
When using Kotlin 1.4.31 and serialization 1.1.0 and declaring the watch as a target using the `watchos()` shortcut, the target `watchosX64` gets created.
That target isn't present in kotlinx-serialization so a `.gradlew check` won't compile due to the missing target.

It would be great if you added the missing watch target.

**Comment by sandwwraith** [comment]
PR: #1285
