### ISSUE TITLE
How to generate .kt from .proto?

### ISSUE THREAD

**Issue by lz1998** [Kotlin/kotlinx.serialization#1358]
**What is your use-case and why do you need this feature?**

I want to migrate a golang program to kotlin, but I can't find any solution to generate .kt from .proto.

Should I only use Java's official protobuf generator? I think it's not a good idea.

**Describe the solution you'd like**

A protoc plugin to generate .kt from .proto.

**Comment by sandwwraith** [comment]
See https://github.com/Kotlin/kotlinx.serialization/issues/477#issuecomment-498019273

**Comment by Dogacel** [comment]
Hi @lz1998 , I am actually working on this project and would like to hear from you what you think.

https://github.com/Dogacel/kotlinx-protobuf-gen
