### ISSUE TITLE
Consider supporting leading plus sign in integer literals

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.serialization#1359]
While [JSON specification](https://www.json.org/json-en.html) does not allow leading `+` in integer literals, there is still plenty of parsers based or evolved from `Integer.parseInt` that allows it.

It means that our parser is kind of out-of-line with the rest of JVM JSON parsers, so we may want to support such literals as well.

**Comment by sandwwraith** [comment]
Closing for now because of lack of demand (no votes, comments, etc)
