### ISSUE TITLE
Serialize default, but ignore null value. 

### ISSUE THREAD

**Issue by elkasvirElka** [Kotlin/kotlinx.serialization#1360]
I have 
@Serializable
data class A (var taskStatus: String? = null,
                       var locale: String = "en-US")

I want to deserialize all defaults except null value: 
 {"locale": "en-US"}

**Comment by sandwwraith** [comment]
See also #195

**Comment by ArcticLampyrid** [comment]
Providing EncodeDefault annotation per field can be helpful to this situation.
#1091

**Comment by ArcticLampyrid** [comment]
> I want to deserialize all defaults except null value

Same feature is required in Protobuf to help handle null values by omitting

**Comment by qwwdfsad** [comment]
Fixed along with #195
