### ISSUE TITLE
Make `kotlinx.serialization.json.Json.configuration` public

### ISSUE THREAD

**Issue by comahe-de** [Kotlin/kotlinx.serialization#1361]
Hi,

I want to write a custom serializer, where I also need to access the configuration of the `Json` class . But it is marked a `internal` 

```kotlin
public sealed class Json(internal val configuration: JsonConf) : StringFormat {
```

So I have to use this hack to access the configuration

```kotlin
        val decoder: JsonDecoder = ...
        var classDiscriminatorConfig: String? = null
        Json(decoder.json) {
            classDiscriminatorConfig = classDiscriminator // the value I want to know
        }
```

So I would like to change the visibility of `kotlinx.serialization.json.Json.configuration` to `public`:

```kotlin
    public sealed class Json(val configuration: JsonConf) : StringFormat {
```

and also ` kotlinx.serialization.json.internal.JsonConf`  to be to `public` (and moving to package `kotlinx.serialization.json`)
```kotlin
package kotlinx.serialization.json
...
data class JsonConf
```

**Comment by qwwdfsad** [comment]
Thanks for the use-case! We'll reconsider our decision for the next major version

**Comment by sandwwraith** [comment]
Same problem: #1323
