### ISSUE TITLE
Gradle plugin breaks multi-project builds

### ISSUE THREAD

**Issue by scottbot95** [Kotlin/kotlinx.serialization#1362]
**Describe the bug**
Loading the `kotlin("plugin.serialization")` plugin causes multi-project builds to throw out the `The Kotlin Gradle plugin was loaded multiple times in different subprojects` warning. Additionally, any multiplatform project will completely fail to load if the serialization plugin is loaded in a multi-project setup.

**To Reproduce**
Run any gradle command from https://github.com/scottbot95/kotlin-graldle-multiproject-test/tree/serialization

**Expected behavior**
Gradle build works properly with no errors.

**Environment**
 - Kotlin version: 1.4.21
 - Library version: 1.4.21
 - Kotlin platforms: All
 - Gradle version: 6.7

**Comment by sandwwraith** [comment]
Try to add serialization plugin to the root project of your structure (with `apply: false` if necessary)

**Comment by scottbot95** [comment]
Interesting. I just tested that and moving the plugins to the `build.gradle.kts` and adding them with `apply: false` works and does not cause the error to be emitted.

This seems strange to me since it is my understanding that adding the plugin in the `settings.gradle.kts` file under `pluginManagement` is effectively the same thing as declaring them in your `build.gradle.kts` with `apply: false` , so moving the declaration from once location to another shouldn't affect anything. Moreover, the `settings.gradle.kts` solution is preferred since it does not have the constrained syntax of the `plugins {}` section in the `build.gradle.kts`.

Do you know why setting the version does not work in `settings.gradle.kts`? Adding the plugins there is preferrable since it does not have the constrained syntax of the `plugins {}` section in the `build.gradle.kts` enabling you to pull versions from `gradle.properties` file

**Comment by scottbot95** [comment]
Oh actually I can leave the version specification in the `settings.gradle.kts` and just also add them to the `build.gradle.kts`. Still confused about the inner workings but there doesn't seem to be any issue here other than in my head so I'll close this out.
