### ISSUE TITLE
Transient for enum fields

### ISSUE THREAD

**Issue by zepurplez** [Kotlin/kotlinx.serialization#1368]
**Describe the bug**
@Transient annotation doesn't work for enum fields

**To Reproduce**
```
    @Serializable
    enum class SomeEnum {
        @SerialName("a")
        A,
        @SerialName("a")
        B,
        @kotlinx.serialization.Transient
        C
    }

    @Serializable
    class SomeClass(val someList: List<SomeEnum>)

    @Test
    fun someTest() {
        val value = SomeClass(listOf(SomeEnum.C))
        val encoded = Json.encodeToString(value)
        println(encoded)
    }
```

**Expected behavior**
collection without annotated(@Transient) elements

**Environment**
 - Kotlin version: 1.4.21
 - Library version: 1.0.0
 - Kotlin platforms: JVM
 - Gradle version: 6.7

**Comment by sandwwraith** [comment]
That's because enum instance is actually an object, not a property. Classes and objects can't be transient. What do you expect from serializing `SomeClass(SomeEnum.C)` (with val e: SomeEnum, not the list). Exception?
