### ISSUE TITLE
Do not call Enum.values() on each call to decodeEnumValue for explicitly-serializable enums

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.serialization#1372]
Steps to reproduce:

```
@Serializable
enum class AnnotatedEnum {
    E1,
    E2
}
```

Its `serializer.deserialize` code contains the following sequence: `AnnotatedEnum.values()[decoder.decodeEnum($$serialDesc)];` It triggers an allocation of values array on each call.

The desired behaviour is to pre-cache this array in serializer's state

**Comment by shanshin** [comment]
Fixed via #1851
