### ISSUE TITLE
 Custom serializers for a generic type ignored

### ISSUE THREAD

**Issue by KevinBassaDevelopment** [Kotlin/kotlinx.serialization#1374]
**Describe the bug**
When using a custom serializers for a generic type, the serialization never gets called.
The serialization of the base object happens, but the property with the custom serializer is null.

**To Reproduce**
1. In main method, call deserialzation of base object:
```
json.decodeFromString<Bundle>(jsonData)
```

2. The base entity
```
@Serializable
data class Bundle(
    @SerialName("id")
    val id: String? = null,
    @SerialName("myData")
    val myData: MyDataClass? = null,
)
```
3. The 2nd entity containing the generic type property
```
@Serializable
data class MyDataClass(
    @SerialName("status")
     val status: Enumeration<MyStatus>? = null
)
```
4. The generic type
```
@Serializable(with = EnumerationSerializer::class)
data class Enumeration<T : Enum<*>>(
    val value: T?
)
```
4. The generic type serializer
```
class EnumerationSerializer<T : Enum<*>>(private val dataSerializer: KSerializer<T?>) : KSerializer<Enumeration<T>> {
    override val descriptor: SerialDescriptor = dataSerializer.descriptor

    override fun serialize(encoder: Encoder, enumeration: Enumeration<T>) =
        dataSerializer.serialize(encoder, enumeration.value)

    override fun deserialize(decoder: Decoder): Enumeration<T> =
        decoder.decodeStructure(descriptor) {
            val stringValue = decodeStringElement(descriptor, 0)
            //var enumValue: T? = MultiLanguageEnumParser.parse<T>(stringValue) as T?
            var enumValue = null

            return Enumeration(enumValue)
        }
}
```

**Expected behavior**
Custom serializer should be called, as shown in example [kotlinx.serialization - Custom serializers for a generic type](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#custom-serializers-for-a-generic-type)

**Environment**
 - Kotlin version: 1.4.30
 - Library version: 1.1.0
 - Kotlin platforms: JVM
 - Gradle version: 6.5
 - IDE version Android Studio 3.4

All other object based kserializers work.
So when using a normal object base singleton serializer instead of @Serializable(with = EnumerationSerializer::class) in step 4, the deserialize gets called (but then fails of course because its one specific case and not generic)

**Comment by shanshin** [comment]
May you clarify the source JSON string and the result of the deserialization?

With your code for enum 
```
enum class MyStatus {
    OK,
    ERROR
}
```
and JSON string `Json.decodeFromString<Bundle>("""{"id": "1", "myData": {"status": {"OK"}}}""")` I got result 
```
Bundle(id=1, myData=MyDataClass(status=Enumeration(value=null)))
```
EnumerationSerializer#deserialize is called but `Enumeration(value=null)` because in your example `var enumValue = null`.

Also `EnumerationSerializer` serialization is not symmetry because the `serialize` function write the value as a simple string but `deserialize` expected structure (value enclosed in curly braces like `{"OK"}`).

**Comment by KevinBassaDevelopment** [comment]
The source JSON string is:

```
  {
    "id": "1",
    "myData": 
     {
        "status": "OK"
     }
  }
```

This simple  "status": "OK" should be deserialized to class Enumeration, status.value.

The reason for this is that status contains more complex logic that is excluded for this example.
So a simple ENUM is wrapped in Enumeration, and the custom serializer should be triggered for all instances of Enumeration<T>

Serialize can be ignored for this example, I'm just wondering why in this case the custom serializer does not get called when deserializing a json string.

**Comment by shanshin** [comment]
For JSON string 
```
  {
    "id": "1",
    "myData": 
     {
        "status": "OK"
     }
  }
```
KSerializer can directly use given `dataSerializer`
```
class EnumerationSerializer<T : Enum<*>>(private val dataSerializer: KSerializer<T?>) : KSerializer<Enumeration<T>> {
    override val descriptor: SerialDescriptor = dataSerializer.descriptor

    override fun serialize(encoder: Encoder, enumeration: Enumeration<T>) =
        dataSerializer.serialize(encoder, enumeration.value)

    override fun deserialize(decoder: Decoder): Enumeration<T> {
        return Enumeration(dataSerializer.deserialize(decoder))
    }
}
```
it deserialized as `Bundle(id=1, myData=MyDataClass(status=Enumeration(value=OK)))`

**Comment by KevinBassaDevelopment** [comment]
Ok this was some caching issue, after setting it up newly it gets called correctly. Thought I was going crazy, as I was not able to find any issues in the code. It feels like this currently occurs more often with kmm. Thanks for the support!
