### ISSUE TITLE
What should be leveraged for serializer and descriptor for map-datastucture not in standard library?

### ISSUE THREAD

**Issue by TorRanfelt** [Kotlin/kotlinx.serialization#1379]
**What is your use-case and why do you need this feature?**
I needed a TreeMap in Kotlin-js, and hence had to make my own (not that it matters here, but I had to fold on large "random" intervals efficiently).
Now I need to Serialize TreeMap (into JSON to be specific). Making TreeMap and its Node @Serializable fix that, but I want to make a TreeMapSerializer on par with LinkedHashMapSerializer and HashMapSerializer. I.e. generating a list of [key1, value1, key2, value2, ..., keyN, valueN]. (Has the added benefit of making it easier to change implementation details and map-type later.)

I don't want to do this by using an intermediate HashMap.

First I looked at what was available, and LinkedHashMapSerializer/HashMapSerializer build upon MapLikeSerializer and AbstractCollectionSerializer, but they are both marked as @InternalSerializationApi. So I thought it was best not to use them.

So it's probably necessary to make a serializer from scratch. No problem. However, I will need to implement SerialDescriptor, and it has the comment "SerialDescriptor interface is not stable for inheritance in 3rd party libraries", so I kept looking for a way to build a descriptor I can use without implementing SerialDescriptor directly. I found mapSerialDescriptor which is only marked with @ExperimentalSerializationApi - Even though it builds upon HashMapClassDesc it has nothing to do with a HashMap except for it's serial-name being "kotlin.collections.HashMap".

**Describe the solution you'd like**
I'm not sure what approach is correct with regards to how Kotlinx.serialization is designed and not cornering myself in future library releases:
Make a KSerializer and SerialDescriptor from scratch. (I'm tilting toward this.)
Make a KSerializer from scratch but use mapSerialDescriptor.
Build upon AbstractCollectionSerializer and use mapSerialDescriptor.

What is the library-correct approach?

**Comment by sandwwraith** [comment]
I'd say that safest option for now is the second one: 'Make a KSerializer from scratch but use mapSerialDescriptor', since mapSerialDescriptor is an Experimental, not Internal, API. If you're not OK with name, you can make your own serial descriptor that delegates everything to mapSerialDescriptor except serialName.

**Comment by TorRanfelt** [comment]
@sandwwraith 
Thanks. I'll go ahead with option 2.
