### ISSUE TITLE
Serializable interfaces will have generated constructors

### ISSUE THREAD

**Issue by pdvrieze** [Kotlin/kotlinx.serialization#138]
If I annotate an interface with `@Serializable` it generates a constructor in the interface. This isn't really valid and Android's d8 chokes on it.

**Comment by sandwwraith** [comment]
Currently, `@Serializable` on interfaces is not officially supported. We are looking forward to ways how to implement it (likely with generated on-the-fly synthetic implementations), but for now it is undefined behaviour.

**Comment by pdvrieze** [comment]
The way I would like to implement it is with the serializer parameter that will then have the job to sort it out (polymorphism and all). Perhaps the compiler plugin should just produce a *nice* and helpful error (please indicate what code creates the error).
