### ISSUE TITLE
Serialization should be allowed for a class if any blank constructor exists

### ISSUE THREAD

**Issue by ejektaflex** [Kotlin/kotlinx.serialization#1381]
**What is your use-case and why do you need this feature?**

It would be nice to allow for serialization of classes that have blank secondary constructors, even if another constructor has a property.

The following does not work:

```kotlin
@Serializable
data class MyData(val myInt: Int)

@Serializable // => syntax error
class MyClass(inData: MyData?) {
    constructor() : this(null)
}
```

However, this does work:

```kotlin
@Serializable
data class MyData(val myInt: Int)

@Serializable
class MyClass() {
    constructor(inData: MyData?) : this()
}
```

**Describe the solution you'd like**
Allowing the class to be serialized, since a blank constructor does exist.

**Comment by shanshin** [comment]
Also relates #575
