### ISSUE TITLE
"Serializer for class is not found." when fetching serializer for an enum when using the "Serializable with" annotation

### ISSUE THREAD

**Issue by DavyHubrecht** [Kotlin/kotlinx.serialization#1386]
**Describe the bug**
When you add a custom serializer, and link it to an enum using the "Serializable with" annotation, you get an exception when trying to get the serializer through the "serializer()" method.

```
kotlinx.serialization.SerializationException: Serializer for class 'TestEnum' is not found.
```

**To Reproduce**
```Kotlin
@Serializable(with = TestSerializer::class)
enum class TestEnum {
    test1,
    test2
}

class TestSerializer : KSerializer<TestEnum> {
    ...
}

fun test() {
    val serializer = TestEnum::class.serializer() // Throws exception
}
```

**Potential cause & temp fix**
I've debugged why this fails on enums, but not on classes, and noticed that it's related to the companion object.
At a certain point in the flow this will be called:
```Kotlin
private fun <T : Any> invokeSerializerOnCompanion(jClass: Class<*>, vararg args: KSerializer<Any?>): KSerializer<T>? {
    val companion = jClass.companionOrNull() ?: return null
    return try {
        val types = if (args.isEmpty()) emptyArray() else Array(args.size) { KSerializer::class.java }
        companion.javaClass.getDeclaredMethod("serializer", *types)
            .invoke(companion, *args) as? KSerializer<T>
    } catch (e: NoSuchMethodException) {
        null
    } catch (e: InvocationTargetException) {
        val cause = e.cause ?: throw e
        throw InvocationTargetException(cause, cause.message ?: e.message)
    }
}
```

On an enum this will return on the first line, since no companion is found.

I have then added the companion object + serializer method manually to see if that would work, and it seems it does:

```Kotlin
@Serializable(with = TestSerializer::class)
enum class TestEnum {
    test1,
    test2;

    companion object {
        fun serializer() : KSerializer<TestEnum> {
            return TestSerializer()
        }
    }
}
```

So I assume that there's an issue with the plugin generating the required code?

**Environment**
 - Kotlin version: 1.4.30
 - Library version: 1.1.0
 - Kotlin platforms: Only tested on JVM
 - Gradle version: 6.1.1

**Comment by shanshin** [comment]
Currently, the compiler plugin does not generate a companion object for enum if the serializer is explicitly specified using the `with`.
As a workaround, you may define companion object yourself but this will fail when a bug in a plugin will be fixed.

**Comment by shanshin** [comment]
The `KClass<T>.serializer` function is part of the internal API, so you should avoid using it whenever possible. After manually declaring a companion, you can write `TestEnum.serializer()`.

**Comment by DavyHubrecht** [comment]
@shanshin Yes I'm aware, but the bug also happens when try to encode or decode the enum:

```Kotlin
val json = json.encodeToString(TestEnum.test1) // Throws exception
val enumValue = json.decodeFromString<TestEnum>("test1") // Throws exception
```

The bug does not happen if the enum is used as a property in another class though, and you (de)serialize that class, eg:

```Kotlin
@Serializable
data class TestEnumWrapper (
    val testEnum: TestEnum
)

val json = json.encodeToString(TestEnumWrapper(TestEnum.test1)) // Works OK
val enumWrapper = json.decodeFromString<TestEnumWrapper>("""{testEnum: "test1"}""") // Works OK
```

**Comment by shanshin** [comment]
Try to call `json.encodeToString(TestEnum.test1)` and `json.decodeFromString<TestEnum>("test1")` when you manually define companion object as you wrote above 
```
@Serializable(with = TestSerializer::class)
enum class TestEnum {
    test1,
    test2;

    companion object {
        fun serializer() : KSerializer<TestEnum> {
            return TestSerializer()
        }
    }
}
```

**Comment by DavyHubrecht** [comment]
Yes in that case it works, whenever you add the companion object is added manually it works fine. I just reported this bug, because it shouldn't be necessary to add it manually. 😃

**Comment by KotlinIsland** [comment]
Here's a full example
```kt
import kotlinx.serialization.*
import kotlinx.serialization.descriptors.*
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.Json

@Serializable(with=Test.Companion::class)
enum class Test(val value: Int) {
    It(5);

    companion object : KSerializer<Test> {
        fun fromValue(value: Int) = values().find { it.value == value }!!
        override val descriptor = PrimitiveSerialDescriptor("Test", PrimitiveKind.INT)
        override fun deserialize(decoder: Decoder) = fromValue(decoder.decodeInt())
        override fun serialize(encoder: Encoder, value: Test) = encoder.encodeInt(value.value)
    }
}

fun main() {
    val s = Json.encodeToString(Test, Test.It)
    println(s) // 5

    val outS = Json.decodeFromString(Test, s)
    println(outS) // It

    val s2 = Json.encodeToString(Test.It) // Exception in thread "main" kotlinx.serialization.SerializationException: Serializer for class 'Test' is not found.
    println(s2)
    val outS2: Test = Json.decodeFromString(s2)
    println(outS2)
}
```

**Comment by KotlinIsland** [comment]
@shanshin I think a builtin "serialize by value" option would be good, so one could write:
```kt
@SerializableEnumByValue(Test::value)
enum class Test(val value: Int) {
    It(5);
}
```
