### ISSUE TITLE
Issue with generic classes 

### ISSUE THREAD

**Issue by vfsfitvnm** [Kotlin/kotlinx.serialization#1387]
**Describe the bug**
Error on building: `Caused by: java.lang.AssertionError: Couldn't load KotlinClass from /home/user/AndroidStudioProjects/Example/app/build/tmp/kotlin-classes/debug/com/user/example/Box.class; it may happen because class doesn't have valid Kotlin annotations`

`build/tmp/kotlin-classes/debug/com/user/example/Box.class` decompiled content:
```kotlin
package com.user.example;

public final class Box<T> {
}
```

Error on execution (e.g. when attempting to `Json.encodeToString(...)`): `java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/Object;)V in class Lcom/user/example/Box; or its super classes (declaration of 'user.user.example.Box' appears in /data/app/com.user.example-5ffc_2UFmJKGIyPS5_Ts_A==/base.apk!classes4.dex)`

**To Reproduce**
[Snippet](https://github.com/Kotlin/kotlinx.serialization/blob/master/guide/example/example-classes-14.kt) - following [this](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/basic-serialization.md#generic-classes) example

**Expected behavior**
/

**Environment**
 - Kotlin version: 1.4.30
 - Library version: 1.1.0 (`kotlinx-serialization-json`)
 - Kotlin platforms: JVM
 - Gradle version: 6.8.2
 - IDE version: Android Studio Arctic Fox | 2020.3.1 Canary 9
 - Other relevant context: Linux 5.10.2-2-manjaro

**Comment by shanshin** [comment]
Hi,
Do you have a link to the minimal reproducer / your project? I was unable to reproduce this issue with a small Android project.

**Comment by vfsfitvnm** [comment]
@shanshin

I created a couple of new projects (one of them with jetpack compose), only the one that uses jetpack compose has the issue.

As stated [here](https://github.com/Kotlin/kotlinx.serialization/issues/1324#issuecomment-778359544), there are compatibility issues unless using the `1.4.21` compiler.
