### ISSUE TITLE
error when compile in js @Serializable with @JsExport

### ISSUE THREAD

**Issue by sarahBuisson** [Kotlin/kotlinx.serialization#1389]
I had serialization to a working project in multiplatform,

I get this error during the build, in the (generated by the build ) file
`at /Users/sarahbuisson/dev/workspace-perso/labyrinth-game/build/js/packages/labyrinth-game-game/kotlin/labyrinth-game-game.js (4945, 19): missing name after . operator`

the line of generated code:

`  package$model.<init> = ObjectZone_init;`
  
  The issue seems to appear when you use @JsExport with @Serializable
  
  
  the code : 
  `     @JsExport() 
     @Serializable
     @JsName("ObjectZone")
     open class ObjectZone(open var name: String = "", open var type: String? = null) {

      override fun toString(): String {
          return "" + type + " " + name
      }
  }`

**Comment by sandwwraith** [comment]
What version of compiler do you use? This issue was fixed in JS IR compiler: https://youtrack.jetbrains.com/issue/KT-42111
