### ISSUE TITLE
serializer<T>() does not work on Kotlin/JS when T is an interface

### ISSUE THREAD

**Issue by mtorials** [Kotlin/kotlinx.serialization#1394]
**Describe the issue**

I have a basic polymorphic structure with a base interface `Event` and a subclass `MessageEvent`.
When I try to deserialize a json object (type `MessageEvent`) with a type discriminator as the base class (here `Event`), I get an error `Serializer for class 'Event' is not found.`. This is however expected, because I am targeting Kotlin/JS and `Event` is an interface (#1000).

But serializing and deserializing another class (`Wrapper`) with an attribute of type `Event` works fine. The json object gets a type discriminator and can be deserialized. Why is it possible to get the serializer for `Event` in this case?

To get a type discriminator and successfully serialize/deserialize a `MessageEvent` directly it is possible to specify the `PolymorphicSerializer` explicitly when calling `encodeToString`/`decodeFromString` like suggested in issue #1000. But this does not work with Lists and Arrays.

When serializing Lists and Arrays you can not explicitly specify the `PolymorphicSerializer` for the generic type, so there is no type discriminator in the json. Trying to deserialize fails with `Serializer for class 'Event' is not found.`. Is there a workaround for this problem?

**To Reproduce**

```kotlin
interface Event {
    val id: String
}

@Serializable
data class MessageEvent(
    override val id: String,
    val message: String,
) : Event

@Serializable
data class Wrapper(
    val event: Event
)

val format = Json {
    classDiscriminator = "type"
    prettyPrint = true
    ignoreUnknownKeys = true
    serializersModule = SerializersModule {
        polymorphic(Event::class) {
            subclass(MessageEvent::class)
        }
    }
}

// This works fine, but why?
val wrapperIn = Wrapper(MessageEvent("id3", "A wrapped message"))
val wrapperString = format.encodeToString(wrapperIn)
val wrapper: Wrapper = format.decodeFromString(wrapperString)
println(wrapper) // Wrapper(event=MessageEvent(id=id3, message=A wrapped message))

// Also works fine
val messageEventIn: Event = MessageEvent("id1", "This is a message")
val messageEventString = format.encodeToString(PolymorphicSerializer(Event::class), messageEventIn)
val event: Event = format.decodeFromString(PolymorphicSerializer(Event::class), messageEventString)
println(event) // MessageEvent(id=id1, message=This is a message)

// This does not work
val messageEventListIn = listOf(MessageEvent("id4", "hi"), MessageEvent("id4", "Hui"))
val messageEventListString = format.encodeToString(messageEventListIn)
// Json looks like this (no type discriminator)
//[
//    {
//        "id": "id4",
//        "message": "hi"
//    },
//    {
//        "id": "id4",
//        "message": "Hui"
//    }
//]
val messageEventList : List<Event> = format.decodeFromString(messageEventListString) // errors with Serializer for class 'Event' is not found
println(messageEventList)
```

**Environment**
 - Kotlin version: 1.4.31
 - Library version: 1.1.0
 - Kotlin platforms: JS
 - Gradle version: 6.6.1

**Comment by sandwwraith** [comment]
As a workaround, you can use `encodeToString(ListSerializer(PolymorphicSerializer(Event::class)), ...)`

Regarding the issue: inline `serializer<T>()` (which is used in decodeToString) does not return correct polymorphic serializer on JS now, it's an issue. See also #1116 and #1078

**Comment by sandwwraith** [comment]
Related: https://youtrack.jetbrains.com/issue/KT-41339
