### ISSUE TITLE
Serialize enum by value

### ISSUE THREAD

**Issue by KotlinIsland** [Kotlin/kotlinx.serialization#1398]
A common use case for enums is to have each instance have a unique value, I think it would be really useful to be able to write:
```kt
@SerializableEnumByValue(Test::value)
enum class Test(val value: Int) {
    It(5);
}
```

such that 
```kt
Json.encodeToString(Test.It) == "5"
Json.decodeFromString("5") == Test.It
```

**Comment by Displee** [comment]
What about `.ordinal`?

**Comment by turansky** [comment]
`.ordinal` value is fixed by specification

**Comment by Displee** [comment]
What does that mean?

**Comment by Dominaezzz** [comment]
Easy to write custom serializer for this case.

Can use a solution similar to this one.
https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/builtin-classes.md#long-numbers-as-strings
