### ISSUE TITLE
What is the library size?

### ISSUE THREAD

**Issue by IslamSalah** [Kotlin/kotlinx.serialization#1399]
On checking the library size for [v1.1.0 ](https://github.com/Kotlin/kotlinx.serialization/releases/tag/v1.1.0) in the AS APK analyzer, it was **~220 KB** 
Can you please let us know it if there are more accurate numbers than the shared ones?
<img width="572" alt="kotlinx serialization lib size" src="https://user-images.githubusercontent.com/8607770/113521381-73c8b380-9599-11eb-9f6a-c530f385575b.png">

**Comment by sandwwraith** [comment]
We haven't measured it specifically, so I'm not aware of any size studies beside yours. I don't see reasons not to believe APK analyzer

**Comment by IslamSalah** [comment]
> I don't see reasons not to believe APK analyzer

I'd say any discrepancy for e.g. defected APK generated due to non-clean build. But if you see it reasonable so it's fine
Thanks for the quick reply
