### ISSUE TITLE
kotlinx-serialization-properties - option for unflattened map?

### ISSUE THREAD

**Issue by carterhudson** [Kotlin/kotlinx.serialization#1400]
**What is your use-case and why do you need this feature?**
When I used Moshi, I could easily diff my app's state structure from one state change to the another, and log it for visibility and ease of debugging
```kotlin
  // with Moshi
  private fun getDiffMap(
    old: ApplicationState,
    new: ApplicationState
  ): Map<String, Pair<Any, Any>>? {
    return Moshi
        .Builder()
        .build()
        .adapter(ApplicationState::class.java)
        .let { adapter ->
          val oldMapSequence =
            adapter.toJsonValue(old)?.safeCast<Map<String, Any>>()?.asSequence()
          val newMapSequence =
            adapter.toJsonValue(new)?.safeCast<Map<String, Any>>()?.asSequence() ?: return null

          oldMapSequence
              ?.zip(newMapSequence) { oldEntry, newEntry ->
                oldEntry.key to (oldEntry.value to newEntry.value)
              }
              ?.toMap()
              ?.filter { combinedEntry ->
                combinedEntry.value.first != combinedEntry.value.second
              }
        }
  }

  // print it with logging middleware
  private val loggingMiddleware = middleware<ApplicationState> { store, dispatch, action ->
    val oldState = store.state
    dispatch(action).also {
      val newState = store.state
      Timber.d("[$action] -> ")
      getDiffMap(oldState, newState).forEach { diff ->
        Timber.d("\t${diff.key}: ${diff.value.first} -> ${diff.value.second}")
      }
    }
  }
```

With this, it was easy to see when, for instance, my navigation back stack changed (simple list of tokens). However, Moshi didn't meet my needs with regard to serialization and sealed classes, so I switched to `kotlinx-serialization-json`. I had to search quite a bit to find an equivalent that would let me get a simple map of properties, and I thought `kotlinx-serialization-properties` would be the answer, but the fact that it _flattens_ collections is a problem in my specific use-case. If I'm diffing two states, and my backstack collection changes from 2 items to 1, it throws off the entire diff :(

```kotlin
  // with kotlinx-properties
  private fun getDiffMap(
    old: ApplicationState,
    new: ApplicationState
  ): Map<String, Pair<Any, Any>> {

    val oldMap = Properties.encodeToMap(old)
    val newMap = Properties.encodeToMap(new)

    return oldMap.asSequence()
        .zip(newMap.asSequence()) { oldEntry, newEntry ->
          oldEntry.key to (oldEntry.value to newEntry.value)
        }
        .toMap()
        .filter { combinedEntry ->
          combinedEntry.value.first != combinedEntry.value.second
        }
  }
```

Is there another way to do this, aside from just using reflection?

**Describe the solution you'd like**
Perhaps a flag that keeps collections from being flattened? I understand that this may not be feasible, based on the underlying implementation.

**Comment by sandwwraith** [comment]
Since Properties are based on Java Properties, they're meant to be flattened. What you're asking for is another format, e.g. 'kotlin object to map converter'.

In the meantime, you can convert your data with `encodeToJsonElement` to a JsonObject, which implements `Map<String, JsonElement` interface. You can calculate diff on them right away or convert recursively to `Map<String, Any>`

**Comment by carterhudson** [comment]
> Since Properties are based on Java Properties, they're meant to be flattened. What you're asking for is another format, e.g. 'kotlin object to map converter'.
> 
> In the meantime, you can convert your data with `encodeToJsonElement` to a JsonObject, which implements `Map<String, JsonElement` interface. You can calculate diff on them right away or convert recursively to `Map<String, Any>`

Ah, awesome, that should work perfectly for me. Thanks for showing me the light :D

**Comment by carterhudson** [comment]
@sandwwraith Do you know what would cause json objects of the same type to differ in number of keys? My intuition is that they would always have the same number of keys, as they always have the same number of fields. Yet here, for example, two instances of my `ApplicationState`, which have the same fields, differ in size...
![Screen Shot 2021-04-05 at 6 51 40 PM](https://user-images.githubusercontent.com/2574098/113643694-1c315300-9640-11eb-80c6-99dd16200172.png)
