### ISSUE TITLE
'Mark the class as @Serializable or provide the serializer explicitly' for the serialized class

### ISSUE THREAD

**Issue by akuleshov7** [Kotlin/kotlinx.serialization#1404]
**Describe the bug**
Incorrect exception is thrown about the `Serializable` annotation. The class is marked with an annotation, but on the runtime it requires this annotation.

```
Serializer for class 'A' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
kotlinx.serialization.SerializationException: Serializer for class 'A' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
	at kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered(Platform.common.kt:91)
	at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt:130)
	at kotlinx.serialization.SerializersKt.serializer(Unknown Source)
	at com.akuleshov7.ktoml.test.MainTest.main(MainTest.kt:119)
```

**Small reproducer**
```kotlin
@OptIn(InternalSerializationApi::class)
inline fun <reified T: Any> deserializeData(request: String): T {
    return Json.decodeFromString(T::class.serializer(), request)
}

@Serializable
data class A<T: Any> (
    val a: T
)

fun main() {
    println(deserializeData<A<HI>>("{ \"a\": \"1\" }"))
}
typealias HI = Int
```

**Environment**
 - Kotlin version: 1.4.30
 - Library version: 1.1.0
 - Kotlin platforms: all

**Comment by sandwwraith** [comment]
[Documentation](https://kotlin.github.io/kotlinx.serialization/kotlinx-serialization-core/kotlinx-serialization-core/kotlinx.serialization/index.html) for `KClass.serializer()` says that it does not work with generic classes, that's why it is internal. You should use intrinsified `serializer<T>()` or `serializer(KType)` instead.
