### ISSUE TITLE
Provide way to encode unquoted String in JSON format

### ISSUE THREAD

**Issue by sandwwraith** [Kotlin/kotlinx.serialization#1405]
Mainly to write big numbers. See reasoning here: https://github.com/Kotlin/kotlinx.serialization/issues/1051#issuecomment-812130020

**Comment by JakeWharton** [comment]
Another use case is embedding known JSON documents into others without having to go through an intermediate parsing step. As long as it's named sufficiently scary this can be a powerful escape hatch.

**Comment by nikolaykasyanov** [comment]
Should this issue also include decoding JSON primitives as raw strings (to be able to convert them to smth mentioned `BigDecimal`)?

**Comment by Kantis** [comment]
Do you see any downsides to this approach? I suppose it might be prone to breaking, but it seems to work at least.

```
object BigDecimalSerializer : KSerializer<BigDecimal> {

    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("BigDecimal", PrimitiveKind.STRING)

    override fun deserialize(decoder: Decoder): BigDecimal =
        (decoder as JsonDecoder).decodeJsonElement().jsonPrimitive.content.toBigDecimal()


    override fun serialize(encoder: Encoder, value: BigDecimal) {
        (encoder as JsonEncoder).encodeJsonElement(JsonPrimitive(JsonBigDecimal(value)))
    }
}

internal class JsonBigDecimal(value: BigDecimal) : Number() {

    private val serialized: String = value.toString()

    override fun toString() = serialized

    override fun toByte() = notSupported()
    override fun toChar() = notSupported()
    override fun toDouble() = notSupported()
    override fun toFloat() = notSupported()
    override fun toInt() = notSupported()
    override fun toLong() = notSupported()
    override fun toShort() = notSupported()

    private fun notSupported(): Nothing = throw IllegalStateException("This method should not be invoked, ever.")
}
```

**Comment by DrMetallius** [comment]
This solution unfortunately only works only for decoding. When encoding, the value will get converted to `double` by `JsonLiteralSerializer`.

**Comment by Kantis** [comment]
> 
> 
> This solution unfortunately only works only for decoding. When encoding, the value will get converted to `double` by `JsonLiteralSerializer`.

Darn. I accidentally asserted my expected _too precise for double_ number through a JSON parsing lib which ended up doing the same doble-conversion. 🙄 

Added a warning to my original comment and code snippet.

**Comment by nikolaykasyanov** [comment]
Thanks for sharing @DrMetallius, good to know the limitations.

@sandwwraith looks like there's no viable workaround for serialization, would it be possible to proiritize the issue?

**Comment by sandwwraith** [comment]
I think we'll include this in plans for the next release

**Comment by nikolaykasyanov** [comment]
@sandwwraith that's great to hear, thank you 🙏

**Comment by vivekmalhotragithub** [comment]
any updates on this issue?

**Comment by nikolaykasyanov** [comment]
@sandwwraith 👋 hello, I wonder if this is currently planned.

**Comment by aSemy** [comment]
@nikolaykasyanov encoding raw strings to JSON was completed in #2041, and [it will be available for a month or two](https://github.com/Kotlin/kotlinx.serialization/pull/2041#issuecomment-1287049243).
