### ISSUE TITLE
Support customization of polymorphic discriminator field for individual types

### ISSUE THREAD

**Issue by diesieben07** [Kotlin/kotlinx.serialization#1410]
**What is your use-case and why do you need this feature?**
I am using `kotlinx.serialization` to consume a JSON document from a third party (in particular I am parsing an [OpenAPI Document](https://swagger.io/specification/)). As such I cannot change the format of the JSON.
At various places in the specification, a polymorphic discriminator is used (such as `in` for [parameters](https://swagger.io/specification/#parameter-object) or `type` for [security schemes](https://swagger.io/specification/#security-scheme-object)). Even though the polymorphic serializer is perfectly capable of deserializing these types _on their own_, it is impossible to deserialize a document containing them both, because the discriminator property name is configured globally.
As such a completely custom deserializer must be used. `PolymorphicSerializer` cannot be subclassed and even subclassing the internal `AbstractPolymorphicSerializer` will not work because `StreamingJsonDecoder` will just ignore you and completely bypass the `AbstractPolymorphicSerializer` (see [`Polymorphic.kt`](https://github.com/Kotlin/kotlinx.serialization/blob/fc865ed423cd789c0a0148e5660f2b8b5ca80b8f/formats/json/commonMain/src/kotlinx/serialization/json/internal/Polymorphic.kt#L61-L74)). 

To be honest, I find it perplexing that it is possible to override the discriminator property name on a global level at all - the Json serializer has no business in deciding what this property should be called, it depends on the actual type being serialized.

**Describe the solution you'd like**
I would like an annotation similar to `@SerialName` which can be used on a class to set the discriminator property name used for its children.
```kotlin
@Serializable
@PolymorphicDiscriminator("discriminator")
sealed class BaseClass

@SerialName("foo")
@Serializable
class Foo : BaseClass()

@SerialName("bar")
@Serializable
class Bar : BaseClass()
```

Should produce JSON as follows:
```json
{
  "discriminator": "foo"
}
```

**Comment by Dominaezzz** [comment]
https://github.com/Kotlin/kotlinx.serialization/issues/546

**Comment by diesieben07** [comment]
Thank you, I did search but didn't find that one.
