### ISSUE TITLE
Support for java.io.Serializable

### ISSUE THREAD

**Issue by 1gravity** [Kotlin/kotlinx.serialization#1412]
**What is your use-case and why do you need this feature?**
If kotlinx.serialization would support classes that implement the java.io.Serializable interface instead of just @Serializable annotated classes, I could use the same class for kotlinx.serialization and for Ktorm. Ktorm's preferred method is to use interfaces 
extending org.ktorm.entity.Entity which implements Serializable. As it stands now I cannot serialize the Ktorm entities directly but need to convert them manually to @Serializable classes.

**Describe the solution you'd like**
Use a reflection based approach for interfaces for which it cannot generate a serializer at compile time.

**Comment by sandwwraith** [comment]
We do not aim to provide reflection-based approach (mainly because it wouldn't be multiplatform) for now. What's wrong with annotating the same classes as `@Serializable`? Implementing java.io.Serializable should not be an obstacle for plugin

**Comment by 1gravity** [comment]
Thanks for the feedback.
Ktorm is using interfaces and you can't annotate it with @Serializable:

> @Serializable annotation is ignored because it is impossible to serialize automatically interfaces or enums. Provide serializer manually via e.g. companion object

**Comment by 1gravity** [comment]
I was thinking about a generic KSerializer for java.io.Serializable classes that just converts the entity to a String and back, something like this:
```
class CustomerSerializer<ENTITY: java.io.Serializable> : KSerializer<ENTITY> {
    override fun deserialize(decoder: Decoder): ENTITY {
        return fromString((decoder.decodeString()))
    }

    override fun serialize(encoder: Encoder, value: ENTITY) {
        encoder.encodeString(toString(value))
    }

    @Suppress("UNCHECKED_CAST")
    @Throws(IOException::class, ClassNotFoundException::class, ClassCastException::class)
    private fun fromString(s: String): ENTITY {
        val data: ByteArray = Base64.getDecoder().decode(s)
        ObjectInputStream(ByteArrayInputStream(data)).use {
            return it.readObject() as ENTITY
        }
    }

    /** Write the object to a Base64 string.  */
    @Throws(IOException::class)
    private fun toString(o: ENTITY): String {
        val baos = ByteArrayOutputStream()
        ObjectOutputStream(baos).use {
            it.writeObject(o)
            it.close()
            return Base64.getEncoder().encodeToString(baos.toByteArray())
        }
    }

    override val descriptor = PrimitiveSerialDescriptor("Serializable", PrimitiveKind.STRING)
}
```
Right now it's impossible to use this because neither @Serializable nor @UseSerializers can be applied to interfaces. I don't think it would be hard to make that change to allow any java.io.Serializable entity to be serialized by kotlinx.serialization. It seems weird when the original Java Serializable definition is excluded from being serialized by a dedicsated serializing/deserializing library.

**Comment by sandwwraith** [comment]
You can annotate interface with `@Serializable(with = SomeSerializer::class)` and specify that serializer in `@UseSerializers` too, so I don't see any problems with custom serializers

Java Serializable is very different from Kotlinx serialization: it uses specific internal mechanisms and stores data in a proprietary format. This framework, in contrary, is aimed to support format-agnostic encoding. Your solution with storing binary data in base64 may be sufficient for your use-case, but inappropriate for other users (also keep in mind all versioning problems with Java serialization and security problems).  In general, I do not see any reasons to add first-class support for binary data from Java serializable classes.

**Comment by pdvrieze** [comment]
If you want it to work in both formats I would go for writing a generic implementation (implementation functions - called from each class) that would allow kotlin serialization to drive java serialization. The other way around cannot really work nicely due to the way that Java serialization "works". (Of course write to a random string/bytearray can always be implemented, but then you are embedding a serialization).

**Comment by nedtwigg** [comment]
You could use [Serialysis](https://github.com/ealasu/serialysis) to do `java.io.Serializable` -> byte stream -> [TraceObjectInputStream](https://github.com/ealasu/serialysis). It's licensed under GPL, but I know the author is open to relicensing under Apache if you email him.
