### ISSUE TITLE
MissingFieldException during sequential decoding of large classes

### ISSUE THREAD

**Issue by WinX64** [Kotlin/kotlinx.serialization#1413]
**Describe the bug**
The decoding process will fail with a `MissingFieldException` if the decoded class has more than 31 fields, and the decoder is set to sequentially decode the data. The same process works without issue if the decoding is performed non-sequentially, or if the class has 31 fields or less.
A similar case of this limitation was somewhat explored in #164, but no mention of sequential decoding was made.

**To Reproduce**
Below is a test class and test decoder to replicate the issue. The serializer for `VeryLongClass` is generated by the compiler plugin.
```kotlin
fun main() {
    //Automatically calculate the number of fields
    val elements = MutableList(VeryLongClass::class.primaryConstructor!!.parameters.size) { it }
    val decoder = TestDecoder(elements)

    println(VeryLongClass.serializer().deserialize(decoder))
}

@Serializable
data class VeryLongClass(
    val field0: Int,
    val field1: Int,
    val field2: Int,
    val field3: Int,
    val field4: Int,
    val field5: Int,
    val field6: Int,
    val field7: Int,
    val field8: Int,
    val field9: Int,
    val field10: Int,
    val field11: Int,
    val field12: Int,
    val field13: Int,
    val field14: Int,
    val field15: Int,
    val field16: Int,
    val field17: Int,
    val field18: Int,
    val field19: Int,
    val field20: Int,
    val field21: Int,
    val field22: Int,
    val field23: Int,
    val field24: Int,
    val field25: Int,
    val field26: Int,
    val field27: Int,
    val field28: Int,
    val field29: Int,
    val field30: Int,
    val field31: Int,
)

class TestDecoder(private val elements: MutableList<Int>) : AbstractDecoder() {

    override val serializersModule = EmptySerializersModule
    private var currentIndex = 0

    override fun decodeSequentially() = false /* Decoding fails when equals to true */

    override fun decodeElementIndex(descriptor: SerialDescriptor) = if (currentIndex >= descriptor.elementsCount) {
        CompositeDecoder.DECODE_DONE
    } else {
        currentIndex++
    }.also {
        println("[decodeElementIndex] Index: $it")
    }

    override fun decodeInt() = elements.removeFirst().also {
        println("[decodeInt] Value: $it")
    }
}
```

**Expected behavior**
It would be expected for the same operation (but sequential) to work, but instead, it fails with:

`MissingFieldException: Field 'field31' is required for type with serial name 'VeryLongClass', but it was missing`

Furthermore, if `VeryLongClass` is expanded with more fields, the process fails to find the field at every `32n-1` index (eg.: `field31`, `field63`, `field95`, `field127` and so on).

**Environment**
 - Kotlin version: 1.4.31
 - Library version: 1.1.0
 - Kotlin platforms: JVM
 - Gradle version: 6.5

**Comment by shanshin** [comment]
Reproduced in 1.4.31 JVM, for JVM/IR works fine.
You can build your project with `-Xuse-ir` parameter?

**Comment by WinX64** [comment]
Working with no problems when using JVM/IR. Thanks for the clarification.
