### ISSUE TITLE
Assertion Error thrown when trying to compile.

### ISSUE THREAD

**Issue by CmdrNorthpaw** [Kotlin/kotlinx.serialization#1418]
**Describe the bug**
I've written a library for Minecraft mods that provides tools to serialize in-game inventories using kotlinx.serialization. The library itself compiles fine, but when I try to compile a project that utilises it I get hit with a `java.lang.AssertionError: Class with incorrect id found: expected uk/cmdrnorthpaw/kinventory/inventory/SerializablePlayerInventory.SerializableClientPlayerInventory.$serializer, actual uk/cmdrnorthpaw/kinventory/inventory/SerializablePlayerInventory.SerializableClientPlayerInventory.serializer`

**To Reproduce**
Here is the class that was being compiled when the error is thrown:
```kotlin
@Serializable
class InventoryLog(
    val time: Long,
    val reason: LogReason,
    val inventory: SerializablePlayerInventory,
) {
    init { writeBackup() }

    enum class LogReason {
        DEATH, JOIN, LEAVE, MANUAL
    }
    val logId = UUID.randomUUID().toString()

    fun writeBackup() {
        val logFile = File(logDir, "log_$logId.json")
        logFile.writeText(json.encodeToString(serializer(), this))
    }

    companion object {
        val logDir: File
            get() = File(AcaciaConfig.backupPath.value)

        private val json = Json { prettyPrint = true }

        fun PlayerEntity.getLogs(count: Int = 5): List<InventoryLog> {
            val logs = logDir.listFiles()?.map { json.decodeFromString(serializer(), it.readText()) } ?: listOf()
            return logs.filter { it.inventory.player?.uuidAsString == uuidAsString }.take(count)
        }
    }
}
```
Due to Minecraft's client-server model, the `SerializablePlayerInventory` I'm referencing here is a sealed class with two subclasses, one for the client and one for the server. The problem seems to be occurring with the client class, though.

**Expected behavior**
I'd rather hope that the code would compile without any impossible-to-diagnose compiler errors.

**Environment**
 - Kotlin version: 1.14.32
 - Library version: 1.1.0
 - Kotlin platforms: JVM
 - Gradle version: 6.8.3
  - IDE version (if bug is related to the IDE) Unrelated to IDE, although the IDE's error checker doesn't pick this bug up.

**Comment by sandwwraith** [comment]
Can you please post the whole stacktrace to find out what validates classes names? `$serializer` is indeed a generated nested class name, and it's a valid name from the JVM's point of View. Is there some kind of validation/sanitizing happens during the process of building/packaging Minecraft mod?

**Comment by CmdrNorthpaw** [comment]
Full stacktrace: https://paste.ubuntu.com/p/JRsSfvYSPW/

There is a remapping process during compile where the code is compiled to match up with Minecraft's obfuscation mapping system. I don't think that could be the problem though because I've never had this error before using kotlinx.serialization. In fact the authors of the mod loader specifically recommend that you use kotlinx.serialization if you're planning on serializing anything.

**Comment by sandwwraith** [comment]
What I can say for now that it seems that `.class` file on the disk was changed by some kind of obfuscator, making `serializer` from `$serializer`.

The fact that it only happens during consumption of the library may be explained by the fact that reading of .class files happens only when another jar file is loaded by dependency. I.e. when you compile your own library, you are producing class files, not reading them

**Comment by CmdrNorthpaw** [comment]
I've had another chat with the authors of the modloader and there does actually seem to be a remapping issue, but it only occurs with JARs from an external source (i.e. Maven). I think this issue should probably be closed unless you can think of a fix on your end. There is an open issue on their tracker.

**Comment by sandwwraith** [comment]
I'm not sure I can do anything here. You can post the link to issue here so it would be easier to cross-reference the problem and track progress

**Comment by CmdrNorthpaw** [comment]
[Link to issue on Loom's bugtracker](https://github.com/FabricMC/fabric-loom/issues/365)
