### ISSUE TITLE
MPP (JS/JVM) JsonDecodingException Expected '[, kind: SEALED'

### ISSUE THREAD

**Issue by th-jtullgren** [Kotlin/kotlinx.serialization#1419]
**Describe the bug**
```
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 26: Expected '[, kind: SEALED'
```
is thrown during a POST to a ktor route when consuming the json body using `Application.receive<T>` extension.  The json body is generated by the ktor client. Both projects are using kotlin serialization and no other serializer. The project was actually based off the MPP full stack example.

The class in question has a field for a SEALED type.  The entire SEALED type hierarchy is annotated with `@Serializable`.   The sub types are not scoped to the root (though this doesn't appear to make a difference).

IE
```
@Serializable
sealed class Context: Node

@Serializable
sealed class ContextRule: Rule<Context>, Node

@Serializable
class Content(): ContextRule()
```

The serialized string is the same when invoked from the browser and from a console app and I cannot discern any reason for failure.

```json
{
    "name": "foo",
   // this is a SEALED type field
    "contextRule": {
        "type": "com.company.orchestration.All",
        "rules": [
            {
                "type": "com.company.orchestration.Content",
                "operator": {
                    "type": "com.company.orchestration.ContainsText"
                },
                "operand": {
                    "value": [
                        {
                            "value": {
                                "type": "com.company.orchestration.ContentText",
                                "text": "f"
                            }
                        }
                    ]
                }
            }
        ]
    }
}
```
**To Reproduce**
Classes attached.  Just serialize in JS and send to ktor route for deserialization, error should occur.

**Expected behavior**
No Error

**Environment**
 - Kotlin version: 1.4.32
 - Library version: 1.1.0
 - Kotlin platforms: JVM/JS
 - Gradle version: 6.8.2
 - using org.jetbrains.kotlinx:kotlinx-serialization-json
[com.zip](https://github.com/Kotlin/kotlinx.serialization/files/6326297/com.zip)

**Comment by th-jtullgren** [comment]
By explicitly declaring the serializers module, i was able to work around this.  This seems really unscaleable though.  Is this the expected behavior?

Workaround:
```
val Serializer = Json {
    serializersModule = SerializersModule {
        this.polymorphic(ContextRule::class) {
            subclass(Content::class, Content.serializer())
            subclass(All::class, All.serializer())
        }
        this.polymorphic(Operator::class) {
            subclass(ContainsText::class, ContainsText.serializer())
        }
        this.polymorphic(ContentAttribute::class) {
            subclass(ContentText::class, ContentText.serializer())
        }
    }
}
```

**Comment by sandwwraith** [comment]
I've tried to reproduce the issue but failed. I've completed missing parts in your reproducer this way:


```kotlin

interface Rule<T>
interface Node

@Serializable
sealed class Context

@Serializable
sealed class ContextRule: Rule<Context>, Node

@Serializable
@SerialName("com.company.orchestration.All")
data class All(val rules: List<ContextRule>): ContextRule()

@Serializable
@SerialName("com.company.orchestration.Content")
class Content(): ContextRule()

@Serializable
data class TestRules(val name: String, val contextRule: ContextRule)

    @Test
    fun test() {
        val data = """
            {
                "name": "foo",
                "contextRule": {
                    "type": "com.company.orchestration.All",
                    "rules": [
                        {
                            "type": "com.company.orchestration.Content",
                            "operator": {
                                "type": "com.company.orchestration.ContainsText"
                            },
                            "operand": {
                                "value": [
                                    {
                                        "value": {
                                            "type": "com.company.orchestration.ContentText",
                                            "text": "f"
                                        }
                                    }
                                ]
                            }
                        }
                    ]
                }
            }
        """.trimIndent()
        val parsed = Json { ignoreUnknownKeys = true }.decodeFromString<TestRules>(data)
        println(parsed)
    }
```

Am I missing something? Can you provide self-contained project with reproducer?

Also, maybe its just misconfigured JSON with useArrayPolymorphism or something

**Comment by th-jtullgren** [comment]
@sandwwraith Working on just the JVM this is fine. Its between a server and client.  I have attached an example project.

There is an MPP module, `Serializable`, with all of the types.  There is JS only module that creates a react app that has a button to POST a new `Example` object to the server. There is a JVM server module that uses ktor and has a route for posting to "/examples" which is where we can see the error.

STR.
1. Open attached project as gradle project in intellij
2. Run the :server:run task from intellij to get the server running (listens on port 9090)
3. Open browser to localhost:9090
4. Click post new
5. Check the running log from the :server:run task and see the error.

If the webapp doesn't show up on the first try, perform step 2 again. The copy of the webpack output sometimes fails in gradle. not sure why.

[SerializationBug.zip](https://github.com/Kotlin/kotlinx.serialization/files/6337618/SerializationBug.zip)

**Comment by sandwwraith** [comment]
Maybe it's a problem on Ktor side then
