### ISSUE TITLE
Is it possible to deserialise object from different camelCase naming strategies?

### ISSUE THREAD

**Issue by ChameleonTartu** [Kotlin/kotlinx.serialization#1423]
**What is your use case, and why do you need this feature?**

I am testing, passing objects from the SunHttp backend from Http4K all the way through Spring Controller.
For example, my object:

```
@Serializable
data class Order(val OrderName: String)
``` 

It appears in the test as  {"orderName": "example"}.

After it appears in the test as Entity, I want to stringify it and deserialize it back to the `Order` object.
```
Json { ignorUknownKeys = true }.deserializeFromString(EntityUtils.toString(response.entity))
```

I would expect it to work, or pass there a parameter that will make it work, as it is the same definition of [CamelCase](https://en.wikipedia.org/wiki/Camel_case)

**Describe the solution you'd like**

I would expect:

1. Have documentation on how to do it, in case it is possible to do it now.
2. If it is not, to have a flag saying this is polymorphic to deserialize object:
```
Json { ignorUknownKeys = true; polymorphicToCamelCase = true }.deserializeFromString(EntityUtils.toString(response.entity))
```

**Comment by sandwwraith** [comment]
Sorry, I don't get the idea. For changing property name, we have [serial name annotation](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/basic-serialization.md#serial-field-names). For global policies, there's separate ticket: #33
