### ISSUE TITLE
Support serialization of function-local classes

### ISSUE THREAD

**Issue by dzirbel** [Kotlin/kotlinx.serialization#1427]
**What is your use-case and why do you need this feature?**
Function-local classes can be used to describe data that is relevant only within that single function without polluting the rest of the namespace. This can be particularly useful for wrapping web APIs which either (a) return responses in one-off object types that are specific to a certain call and not used elsewhere or (b) expect input of a certain type which is specific to that endpoint.

My specific use case is for the JSON API that Spotify exposes, which has cases of both (a) and (b):
(a) [this endpoint](https://developer.spotify.com/documentation/web-api/reference/#endpoint-get-multiple-albums) returns an object with a single field `albums` containing a list of album objects. I would like to have a function which calls this endpoint, parses the response and returns a `List<Album>`. A simple class wrapping the single-field object is only used in this function, so keeping it function-local is convenient.
(b) [this endpoint](https://developer.spotify.com/documentation/web-api/reference/#endpoint-transfer-a-users-playback) expects a JSON-encoded body of an object containing two fields. This type of object is only used by this endpoint; again I would like to have a function which calls the endpoint, and using a function-local class to wrap the body is convenient (it would look like [this](https://github.com/dzirbel/kotify/blob/577500cb4106be8533fa1b179ad0988daad15f7f/src/main/kotlin/com/dzirbel/kotify/network/Spotify.kt#L1028)).

**Describe the solution you'd like**
kotlinx.serialization should allow serialization of function-local classes, just like any other classes. Serialization supported this feature (perhaps incidentally) in 1.0.1 but support was removed in 1.1.0 (see #1422).

**Comment by sola1tmy** [comment]
Will it be supported again?

It's nice to describe response data in a web method I think.

**Comment by sandwwraith** [comment]
Given that there are many suggested use cases for this, we may reconsider our decision about prohibiting local and anonymous serializable classes
