### ISSUE TITLE
Open up base serializers for extension

### ISSUE THREAD

**Issue by Whathecode** [Kotlin/kotlinx.serialization#143]
Would it make sense to open base serializers, such as `ReferenceArraySerializer`, for extension? Currently, they are final, so it is not possible to extend from them. However, I find myself in a situation where I would like to write the following:
`object CustomSomeObjectArraySerializer : ReferenceArraySerializer<SomeObject, SomeObject>( SomeObject::class, CustomSomeObjectSerializer )`

The reason is, I want to specify a custom serializer for (polymorph) elements in an array using the `@Serializable` attribute:
```
@Serializable
data class ToSerialize(
    @Serializable( with = CustomSomeObjectArraySerializer::class )
    val someObjectArray: Array<SomeObject> )
```

Of course, I can write a wrapper for `ReferenceArraySerializer` instead:
```
object CustomSomeObjectArraySerializer : KSerializer<Array<SomeObject>>
{
    override val serialClassDesc: KSerialClassDesc
        get() = ArrayClassDesc

    override fun save( output: KOutput, obj: Array<SomeObject> )
    {
        val saver = ReferenceArraySerializer( SomeObject::class, CustomSomeObjectSerializer )
        saver.save( output, obj )
    }

    override fun load( input: KInput ): Array<SomeObject>
    {
        val loader = ReferenceArraySerializer( SomeObject::class, CustomSomeObjectSerializer )
        return loader.load( input )
    }
}
```

This is what I do now, and I can likely also make it generic so that I don't need to implement this for each scenario where I want to specify a custom serializer for arrays. But, I would then have to do something similar for `ArrayListSerializer` and any other existing collection serializers. Instead, would this not be a common enough use case (specifying a custom serializer for items in collections) to warrant opening up these existing serializers for extension?

Maybe I am overlooking a different way of going about what I want to do here. Some further notes for clarification:
- I noticed Kotlin does not allow specifying generics in `SomeObject::class` notations (I believe a JVM limitation), thus it is my understanding extending somewhere using concrete type parameters is needed as I have done above.
- My `CustomSomeObjectSerializer` will become an 'exotic' `PolymorphSerializer` if you will: it will deserialize types known at runtime as it is done in the current `PolymorphSerializer`, but will also support deserializing types unknown at runtime (yet extending from `SomeObject`) by wrapping them in an `UnknownSomeObject` wrapper, exposing some base properties/fields from the base type (`SomeObject`).

**Comment by Whathecode** [comment]
I just spent some time on making the `CustomSomeObjectArraySerializer` generic instead. This is my current solution (which would be unnecessary if I could extend from `ReferenceArraySerializer`):
```
open class CustomReferenceArraySerializer<T: Any>(
        private val kClass: KClass<T>,
        private val serializer: KSerializer<T>)
    : KSerializer<Array<T>>
{
    override val serialClassDesc: KSerialClassDesc
        get() = ArrayClassDesc

    override fun save(output: KOutput, obj: Array<T> )
    {
        val saver = ReferenceArraySerializer( kClass, serializer )
        saver.save( output, obj )
    }

    override fun load( input: KInput): Array<T>
    {
        val loader = ReferenceArraySerializer( kClass, serializer )
        return loader.load( input )
    }
}
```

**Comment by sandwwraith** [comment]
Base collection serializers contain a lot of internal machinery, which I believe, should not be open in order not to break invariants. Instead, delegating and composing should work well. 

I didn't test it well, but does solution using Kotlin delegation mechanisms work for you? I mean this:

```kotlin
object MyCustomArraySerializer: KSerializer<Array<SomeObject>>
        by ReferenceArraySerializer(A::class, MySerializerForSomeObject)
```

**Comment by Whathecode** [comment]
Of course! How could I forget about one of my favorite Kotlin features. :) The following works and is a bit conciser:

```
open class CustomReferenceArraySerializer<T: Any>(
    private val _klass: KClass<T>,
    private val _serializer: KSerializer<T>
): KSerializer<Array<T>> by ReferenceArraySerializer( _klass, _serializer )
```

`KClass<T>` cannot be derived from `T` due to Java's compile-time only generics. The exact error is _"Cannot us `T` as reified type parameter. Use a class instead."_

Even though I am okay with this simple wrapper, and I fully understand/appreciate the 'not breaking invariants' argument, I wonder whether an alternative would then be to simply make all members in these serializers `final`, yet make the class `open`. This way I believe the invariants would be ensured, yet the use case I describe is supported.

As to the actual use case which made me ask this question, I have now implemented a working 'exotic' Polymorphic serializer:

```
/**
 * A serializer for polymorph objects of type [P] which wraps extending types unknown at runtime as instances of type [W].
 */
abstract class UnknownPolymorphicSerializer<P: Any, W: P>( wrapperClass: KClass<W> ) : KSerializer<P>
```

Currently this implementation relies on reflection and such to dig into the depths of kotlinx.serialization to make this work. Is there any interest in such a feature in this library? I understand that is is possibly too specific of a use case, but I am quite pleased with the result.

**Comment by Whathecode** [comment]
Given that I now also needed the same for `ArrayListSerializer` (in order to specify the serializer for a `List` explicitly [to work around a bug introduced in 0.5.1](https://github.com/Kotlin/kotlinx.serialization/issues/153#issuecomment-398337785)) I looked into this again.

Similar to the `ReferenceArraySerializer`, a wrapper can easily be created by using delegation:

```
/**
 * A base [KSerializer] class to serialize instances of [List] which allows specifying a custom [serializer] to be used to serialize the containing elements.
 */
open class CustomArrayListSerializer<T: Any>(
    /**
     * The serializer to use to serialize the elements in the list.
     */
    private val _serializer: KSerializer<T>
): KSerializer<List<T>> by ArrayListSerializer( _serializer )
```

I shortly looked into how feasible it was to make all members of these base serializers final while keeping their class definitions open (to support the use cases described here). This is not as straightforward as it seemed at first since many overridable properties are derived from `ListLikeSerializer`. For each extending type, all these base properties would then need to be redefined as final (and redirected) to this super class.

Therefore, the simple delegation wrapper for now seems to be the most straightforward approach. Would it make sense to make these part of the library?

**Comment by qwwdfsad** [comment]
Sorry for the really delayed answer!
We are currently stabilizing API for 1.0 release, so it's really not the best time to add anything new right now.

I'm closing the issue as outdated, but please feel free to create a new one (based on the current API of the library) if you still think it is a worthwhile addition that a lot of users can benefit
