### ISSUE TITLE
JsonDecodingException: Polymorphic serializer was not found when moving directories

### ISSUE THREAD

**Issue by chronvas** [Kotlin/kotlinx.serialization#1435]
**Description**
When using `SerializersModule` to define `polymorphic` for my interface, 
and when I move the classes and interfaces used in polymorphism in a directory, 
I get the error:
``` 
Exception in thread "main" kotlinx.serialization.json.internal.JsonDecodingException: Polymorphic 
serializer was not found for class discriminator 'First' 
```

**To Reproduce**
Run main function from the initial commit https://github.com/chronvas/kotlinx.serialization-Dir-bug/commit/0a7dda04efcef507e0a2cfad1fde4b1ec3613fff 
-This works when `MyBucket`, `MyInterface` and `First` exist in the same file as the deserialize functions.

Run main function from the next commit https://github.com/chronvas/kotlinx.serialization-Dir-bug/commit/502c05c90fcdb63a90ea6941b0921398422f8663
-This throws `JsonDecodingException` 

(The diff is just moving the files to the `models` directory)

**Expected behavior**
To work as it did in the example in the initial commit

**Environment**
 - Kotlin version: 1.4.32
 - plugin.serialization: 1.4.30 and 1.4.32 same behavior
 - Kotlin platforms: JVM and Android same behavior
 - Gradle version: 6.8
 - OS: Windows x64
 - JVM target: 1.8
 - JDK: adopt-openj9-1.8.0_292

**Comment by chronvas** [comment]
Just tried with adding @SerialName("First") [for this data class ](https://github.com/chronvas/kotlinx.serialization-Dir-bug/commit/502c05c90fcdb63a90ea6941b0921398422f8663#diff-f7c5aad31b32efc4634b43f75f22120ffaa66c413585c2efbad0d3c8613bef65R13)and it works. Is the SerialName mandatory? Why is it working on the first commit?

**Comment by sandwwraith** [comment]
Serial name (and thus class discriminator for polymorphism) by default is the fully-qualified class name. By moving the file, you've changed this name from `First` to `models.First`. Therefore, you either need to change your input or to specify serial name explicitly with `@SerialName` annotation

**Comment by chronvas** [comment]
Thanks for your response. 
`Serial name (and thus class discriminator for polymorphism) by default is the fully-qualified class name.` That sound a bit weird to me, why is it not just the name of the class?
Also the error message is not very useful, personally spent lots of time wondering what am I doing wrong.

My original issue is resolved though, should I close this?

**Comment by sandwwraith** [comment]
Usage of a fully qualified name is standard practice, Jackson and other frameworks do this as well. Generally, it allows you to have classes with the same name in different packages (and this happens a lot in enterprise applications)
