### ISSUE TITLE
HOCON: impossible to override NUMERIC value from ENV or properties

### ISSUE THREAD

**Issue by Dkhusainov** [Kotlin/kotlinx.serialization#1439]
**Describe the bug**
Library does not correctly resolve `NUMBER`(probably `BOOLEAN` too) types when they're set via ENV or properties(since it's all strings)

**To Reproduce**

config.conf
```
my.config.value: ${?MY_CONFIG_VALUE}
```
MyConfig.kt
```kotlin
@Serializable
class MyConfig(
  val value: Long
)
```

env:
`MY_CONFIG_VALUE=1`

parsing exception:
`SerializationException: env variables required to be a NUMBER`

**Expected behavior**
Config is correctly parsed

**Environment**
 - Library version: [e.g. 1.1.0]

**Comment by ahmadshabib** [comment]
@sandwwraith Hey, is this still up for grabs? if yes any head up I need to know before starting?

**Comment by sandwwraith** [comment]
@ahmadshabib Yeah. Just follow guide https://github.com/Kotlin/kotlinx.serialization/blob/master/CONTRIBUTING.md#submitting-prs , everything should be self-explanatory. I think this feature does not require a configuration flag or public API change, so no design space here.

**Comment by peterfigure** [comment]
any workarounds for this?

**Comment by tobiaslieber** [comment]
Hi,
I took the freedom to implement a possible solution in https://github.com/Kotlin/kotlinx.serialization/pull/1795 .
