### ISSUE TITLE
EnumMap support?

### ISSUE THREAD

**Issue by camdenorrb** [Kotlin/kotlinx.serialization#1445]
**What is your use-case and why do you need this feature?**
Would like to serialize EnumMaps with KotlinX serialization

**Describe the solution you'd like**
Add a new collection serializer for EnumMaps

**Comment by sandwwraith** [comment]
By EnumMaps you mean `java.util.EnumMap`, right? We do not have special support for Java-specific collections for now, but we may add it later as a separate module. Meanwhile, it should be relatively easy to write a custom serializer for that.
