### ISSUE TITLE
Value class serialization - invalid constructor call in `deserialize`

### ISSUE THREAD

**Issue by turansky** [Kotlin/kotlinx.serialization#1449]
**Describe the bug**
Value class serializer call "missed" constructor
[Test project](https://github.com/turansky/kfc-plugins/tree/988436dc3a7044ccf4876b3b7007e2b9af923516/examples/value-class)

**To Reproduce**
1. Add following code
```Kotlin
@JvmInline
@Serializable
value class UserId(
    val id: String
)
```
2. Check generated `js` file

**Expected behavior**
2. Valid constructor call
```
// UserId$$serializer.deserialize
return new UserId(local0)
```

**Actual behavior**
2. Invalid constructor call
```
// UserId$$serializer.deserialize
return UserId_init(bitMask0, local0, null);
```

**Environment**
 - Kotlin version: `1.5.0`
 - Library version: `1.2.0`
 - Kotlin platforms: JS (Legacy)
 - Gradle version: `6.8.3`

**Comment by sandwwraith** [comment]
Value classes serialization is available only on IR backends

**Comment by turansky** [comment]
It works in legacy with [small fix](https://github.com/turansky/kfc-plugins/blob/ddd168e951478fcf44e49199eeb1409b2ce56ce4/gradle-plugin/src/main/kotlin/com/github/turansky/kfc/gradle/plugin/ValueClassSerializationPlugin.kt#L19)
