### ISSUE TITLE
No class discriminator rendered for polymorphic type

### ISSUE THREAD

**Issue by pueffl** [Kotlin/kotlinx.serialization#1451]
I have a polymorphic type (at the moment one Interface with an one class that implements it). I expected to get the type rendered for that constellation, but it is not. 

Just try this:

```
val module = SerializersModule {

    polymorphic(Identifiable::class) {
        subclass(PreferenceJson::class)
    }

}

interface Identifiable {
    var id: String
}

import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
@SerialName("preference")
class PreferenceJson: Identifiable {

    override lateinit var id: String
    lateinit var attributes: Attributes

    @Serializable
    class Attributes (
            var ownerId: String? = null,
            var category: String,
            var key: String,
            var value: String,
            var version: Int? = 1
    )

}

class JsonSerializationTest {

    val format = Json { serializersModule = module  }

    @InternalSerializationApi
    @Test
    fun test() {
        val pref1 = PreferenceJson().apply {
            id =  "1213"
            attributes = PreferenceJson.Attributes(category = "category1", key = "key1", value = "value1")
        }
 
        println(format.encodeToString(pref1))
    }
}

```
The result of the println is: {"id":"1213","attributes":{"category":"category1","key":"key1","value":"value1"}} -> no discriminator

**Environment**
 - Kotlin version: 1.4.32

**Comment by pdvrieze** [comment]
The way it works is that the discriminator is written by a PolymorphicSerializer. In your test code, you are using a property `pref1` of type PreferenceJson, which is a final type. As such the actual runtime type is known and a discriminator is not needed. If you explicitly make `pref1` of type `Identifiable` it will work. Alternatively you can explicitly pass the serializer to `encodeToString`

**Comment by pueffl** [comment]
This will work in simple situations like my example but this ist not a sound solution (I am not sure, if it works in all cases).

- Having a discriminator sometimes rendered and somtimes not is a rather erractic behavior. I don't think, you can expect another deserializer (in another language) to be able to deserialize this properly in all cases.
- I would have all my classes to implement a certain interface and cast them to it before deserialization and cast to this interface before serialization.
- This will not work for attributes of a certain type within a serializable class nor will it work for a list of an attribute of a certain type within a serializable class. (or at least only in a rather cumbersome and unintuitive way). 

What I would expect is, that the type is rendered when I give it a name like @SerialName("preference") in all cases. Why else would I specify it? At least a property to specify this behaviour would be very helpful.

**Comment by sandwwraith** [comment]
> I would have all my classes to implement a certain interface and cast them to it before deserialization and cast to this interface before serialization.

That's why you need polymorphic serialization, don't you?

> This will not work for attributes of a certain type within a serializable class nor will it work for a list of an attribute of a certain type within a serializable class.

If attribute type is `Identifiable`, then you'll have the discriminator — rules are simple. If the static type is `PreferenceJson`, kotlinx.serialization is able to serialize and deserialize the data without any additional information, hence type discriminator is omitted.

As far as I understood, this problem only arises if you want some 3rd party non-Kotlin application to receive this type discriminator. This is your use-case, right?

**Comment by pueffl** [comment]
Well, what I am just trying to adhere to a well definied format (https://jsonapi.org/). In that format, an attribute 'type' is required. JSON itself is more a low level thing, to create a consistent API you need a bit more :-)  

> If attribute type is Identifiable, then you'll have the discriminator — rules are simple. If the static type is PreferenceJson, kotlinx.serialization is able to serialize and deserialize the data without any additional information, hence type discriminator is omitted.

I understand that.

Yes, I want to receive the json in Flutter/Dart (but also have general REST interface).  In Dart, the result of a decode would be just 'dynamic' which can be anything. 

For me, I understand how this works and it is also consistent in it's way. I just think you should add an option to always include the type information. This would add just another 'flavor' of consistency to the produced json a developer can choose. It would also enable more sophisticated structuring of JSON requests. It may also improve readability in some situations.

**Comment by sandwwraith** [comment]
I see, this indeed can be useful for interoperability with other APIs and languages, when type may be required or carry additional information

**Comment by sandwwraith** [comment]
There's actually already a plenty of feature requests for that: #1247, #1128, so I'll close this as a duplicate
