### ISSUE TITLE
Is there a possibility for partly decoding/deserialization?

### ISSUE THREAD

**Issue by henry1986** [Kotlin/kotlinx.serialization#1453]
**Short explanation of my issue:**

I have a data class:
```
@Serializable
data class MyData(val primaryKey1:Int, val primaryKey2: Double, val y:Int)
```

and want to decode it from a list:

```
val list = listOf<Any>(5, 6.2)
```
As you see, there are only two instead of three values. "y" is missing. Nonetheless there are usecases, where it is necessary, to decode an object only partly and stopping decoding after all available values are decoded. 

Currently I decode by implementing a custom CompositeDecoder and this Decoder would return DECODE_DONE after the last decoding happened. 

```
override fun decodeElementIndex(descriptor: SerialDescriptor): Int {
    // after getting primaryKey1 and primaryKey2
    return DECODE_DONE
}
```

Currently in doing so, a 

`kotlinx.serialization.MissingFieldException: Field 'y' is required, but it was missing`

is thrown. And I don't want an exception thrown, but rather I would like to stop decoding "MyData" with either returning value from cache or just stop decoding and return nothing (null). 

**Long explanation why this is necessary to me:** 

I'm currently implementing an object relational mapping with the serialization library. Goal is to annotate any object with `@Serializable` and to put instances of this class into a database. Serialization works well so far, but I have an issue with deserialization.

If a table has reference to another table (foreign key), I need to deserialize the foreign key out of my table. 

```
@Serializable
data class MyData(val primaryKey1:Int, val primaryKey2: Double, val y:Int)

@Serializable
data class DataRef(val pX:Int, val myData:MyData)

// MyDataTable
primaryKey1   | primaryKey2 | y
5                     | 6.2                   | 9
5                     | 6.4                   | 8
7                     | 6.2                   | 11
// DataRefTable
pX                  | primaryKey1 | primaryKey2 
9                    | 5                    | 6.2
10                  | 5                    | 6.4
11                   | 7                    | 6.2
```

The client starts to a request to DataRefTable:

```
fun doReading(){
     val dataRef = DataRef.serializer().read("select * from DataRefTable where pX=9;")
}

fun DeserializationStrategy<*>.read(request:String){
// get the data, assuming result of db request: val list = listOf<Any>(9, 5, 6.2)
}
```
Now, the read method uses the CompositeEncoder and runs through DataRef at first. But when trying to get MyData, it only has the primaryKeys of MyData, so decoding of MyData by 
```
// MyData.serializer().decode(list)
// asuming, list is listOf<Any>(5, 6.2)
fun DeserializationStrategy<*>.decode(l:List<Any> ){
    deserialize(object:Decoder{
         override fun beginStructure(descriptor: SerialDescriptor) = object: CompositeDecoder{
               override fun decodeElementIndex(descriptor: SerialDescriptor): Int{
                     // returns DECODE_DONE after two calls
               }
         }
    }
}

```

 can only be done with the first two fields of MyData. MyData.y is not there, so it cannot be decoded and an exception is thrown. 

**My Request**

So I would like any possibility to decode an Data Class with `@Serializable` annotation, but where decoding can be stopped without an exception.

**Comment by sandwwraith** [comment]
Decoding implies that we call class' constructor in the end, and we can't do this without all values. I can suggest either do try-catch on MissingFieldException, or decode to intermediate map-like structure

**Comment by sandwwraith** [comment]
No, there's no available mechanism for that

**Comment by sandwwraith** [comment]
Not planned. It is not clear how 'stopping without exception' can be implemented, if we still need to create a class instance. One of the options is to try to insert a default value for primitives (e.g. 0 for `Int`). Decoder can do this automatically, based on the descriptor — by tracking already decoded indices before returning DECODE_DONE (see how Protobuf and Json implement coercing mechanisms and `ElementMarker` class).
