### ISSUE TITLE
Feature request: annotation which helps with schema evolution besides `@Optional`

### ISSUE THREAD

**Issue by adam-arold** [Kotlin/kotlinx.serialization#146]
Currently if I have a class:

    @Serializable
    data class SomeClass(val value: String)

and I want to add a field to it and still keep the old version working I can add it with the `@Optional` annotation and a default value like this:

    @Serializable
    data class SomeClass(val value: String,
                         @Optional val newValue: String)

This will work for json strings which were serialized before adding `newValue`. If I remove the `@Optional` it will throw an exception about a required field (`newValue`) missing for old jsons.

The problem is that currently I can't add a field which is **required** but has a default value. I can use `@Optional` to have the *functionality* but it doesn't communicate my *intent* that the field is in fact required but was added later and is part of a schema evolution.

**Comment by adam-arold** [comment]
What I mean by schema is just that if I add some fields to my class which I'd like to serialize it should work with older versions. Just like the same way [Liquibase](https://www.liquibase.org/) or [Protobuf](https://developers.google.com/protocol-buffers/docs/proto3#default) works.

If you ever want to create a robust serialization tool you need to support the things Protobuf supports or otherwise it won't be useful for real world projects.

**Comment by sandwwraith** [comment]
@pdvrieze Your comment is fair, and there is a feature request for 'not writing default values': #58 

@adam-arold Maybe I understand your case wrong, but adding a field with default value without `@Optional` makes it required for schema. If you want somehow express optionality only for old schemas, imagine you received JSON/Protobuf without such field, how do you know if its from old version or from new schema, but was serialized incorrectly? Regarding transfer new->old, both json and protobuf can skip unknown values or after implementing #58 they can be skipped during serialization.

**Comment by pdvrieze** [comment]
@sandwwraith I have been thinking a bit about these issues. From my perspective it is an issue to resolve mainly at serializer level. There is some additional information needed to do  this (in my code I've created an annotation that contains the string serialization of the default value). The best way, and one that would solve other cases as well would be to have the concept of schema aware serializers. The serializer would need some sort of schema factory that is fed by the serialization code to create whatever schema it wants. Like the current save/load code for a custom serializer. The schema would be available on the parsing in some way. (Technically the requesting and making available of a schema can be done by the serializer, but some help in the library would be good once the design is somewhat stable).

The codegen for schema generation would be very similar to saveSelf except that it would not provide values (just the delegate serializer or value method invocation instead) and that various properties (such as optionality) are exposed. Of course annotations on the type itself being exposed would be a bonus but somewhat an orthogonal issue.

@adam-arold Perhaps what you want is some sort of validation. Transformation could also be part of that. Standardized serialization by delegating to another object (and two transformation functions) could be helpful, and if it is the "same" type would even allow for validation along the way - without having to implement a custom serializer.

**Comment by sandwwraith** [comment]
@pdvrieze it's #34 FR, and I was thinking of implementing it in a similar way. Anyway, to save schema, it's required to pass somehow information about optionality to saver.

**Comment by pdvrieze** [comment]
@sandwwraith I concur with you on the approach (and indeed it is #34).

**Comment by adam-arold** [comment]
Thanks for the heads up! I'm fine with `@Optional` now this is just an improvement suggestion.

**Comment by NikkyAI** [comment]
is this the place to discuss using @Optional as `serialize whe non-default` or should this be in a new PR ?
this seemed to already touch on the topic though

my current solution looks like this: https://i.imgur.com/rJvbshw.png and i am not happy about it
