### ISSUE TITLE
`serializer` not found when using `@SerialInfo` annotated annotation with more than 1 property

### ISSUE THREAD

**Issue by BartvHelvert** [Kotlin/kotlinx.serialization#1462]
**Describe the bug**
When a `@SerialInfo` annotated annotation has more than 1 property the serializer can't be found. This works fine in the old backend but throws a runtime exception when using the new compiler backend. The first compile seems to work fine but every subsequent compile fails.

**To Reproduce**
Create an annotation like:
```kotlin
@SerialInfo
@Target(AnnotationTarget.PROPERTY)
@ExperimentalSerializationApi
public annotation class JShort(val order: SByteOrder = SByteOrder.BE, val mod: SByteMod = SByteMod.Add)

public enum class SByteOrder {
    BE, LE
}

public enum class SByteMod {
    None, Add
}
```
Create a serializable like:
```kotlin
@ExperimentalSerializationApi
@Serializable
public class Foo(
    @JShort(SByteOrder.LE, SByteMod.None) public val bar: Short,
)
```
Get the `serializer`:
```kotlin
public fun main() {
    Foo.serializer()
}
```
Run the main method (everything should work fine)
Change one of the arguments on `JShort`:
```kotlin
@ExperimentalSerializationApi
@Serializable
public class Foo(
    @JShort(SByteOrder.LE, SByteMod.Add) public val bar: Short,
)
```
Run the main method again and it should throw this exception:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at package.Foo$Companion.serializer(Main.kt:21)
	at package.Main.main(Main.kt:29)
	at package.Main.main(Main.kt)
```
**Environment**
 - Kotlin version: 1.5.0
 - Library version: 1.2.0
 - Kotlin platforms: JVM
 - Gradle version: 7.0
 - Other relevant context: OpenJDK 11.0.11, Windows

**Comment by sandwwraith** [comment]
I wasn't able to reproduce. Maybe this was an incremental compilation glitch? Do you have a stable reproducer?

**Comment by Bartvhelvert** [comment]
Seems like, after moving some code around. I am not able to reproduce it anymorel. Even though I was able to reproduce it consistently at first. I am not really sure what excatly changed but the issue was probably related to incremental compilation indeed, given that the first compilation always worked fine.
