### ISSUE TITLE
EncodeDefault = false does not work on inherited properties in JS-IR

### ISSUE THREAD

**Issue by altavir** [Kotlin/kotlinx.serialization#1467]
**Describe the bug**

Properties with default values are still encoded with `encodeDefault = false` if properties are inherited.

**To Reproduce**
See attached project.
[serial-test.zip](https://github.com/Kotlin/kotlinx.serialization/files/6454605/serial-test.zip)

```kotlin
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

@Serializable
open class AClass {
    var aVariable: String? = null
}

@Serializable
class BClass: AClass(){
    var bVariable: String? = null
}

fun main() {
    console.log("Hello")

    val json = Json {
        encodeDefaults = false
    }
    console.log("AClass: \n ${json.encodeToString(AClass.serializer(), AClass())}" )
    console.log("BClass: \n ${json.encodeToString(BClass.serializer(), BClass())}" )
}

```

**Expected behavior**

Should not serialize any field.

**Environment**
 - Kotlin version: 1.5.0
 - Library version: 1.2.0
 - Kotlin platforms: JS-IR

**Comment by sandwwraith** [comment]
It will likely be fixed in 1.5.20, but I'll recheck this
