### ISSUE TITLE
"java.lang.IllegalStateException: not identifier: <init>" error when compiling with 1.2.0

### ISSUE THREAD

**Issue by charleskorn** [Kotlin/kotlinx.serialization#1468]
**Describe the bug**
My project that previously compiled without issue with v1.1.0 and Kotlin 1.4.32 is now failing to compile with a `java.lang.IllegalStateException: not identifier: <init>` error.

Sample GitHub Actions build showing full error and stack trace: https://github.com/charleskorn/kaml/pull/123/checks?check_run_id=2531990585#step:6:49

**To Reproduce**
* Clone https://github.com/charleskorn/kaml
* Run `./gradlew check`
* Build fails on `compileTestKotlinJvm` task with error

Removing both [`YamlReadingTest.kt`](https://github.com/charleskorn/kaml/blob/7ab5b716003f876c9d7727193f11c8f641e75c0b/src/commonTest/kotlin/com/charleskorn/kaml/YamlReadingTest.kt) and [`YamlWritingTest.kt`](https://github.com/charleskorn/kaml/blob/7ab5b716003f876c9d7727193f11c8f641e75c0b/src/commonTest/kotlin/com/charleskorn/kaml/YamlWritingTest.kt) fixes the issue. Adding either file back causes the issue to return.

**Expected behavior**
Project compiles without error, or gives a clearer error message telling me what is wrong and where the issue is.

**Environment**
 - Kotlin version: 1.5.0
 - Library version: 1.2.0
 - Kotlin platforms: JVM
 - Gradle version: 6.9

**Comment by shanshin** [comment]
A clearer error message will be added in version 1.5.20 of the serialization plugin.

**Comment by shanshin** [comment]
duplicate #1427
