### ISSUE TITLE
Plugin is not applied when using Gradle Kotlin DSL with plugins block

### ISSUE THREAD

**Issue by inuwan** [Kotlin/kotlinx.serialization#147]
Running the example:
```
import kotlinx.serialization.*
import kotlinx.serialization.json.JSON

@Serializable
data class Data(val a: Int, @Optional val b: String = "42")

fun main(args: Array<String>) {
    println(JSON.stringify(Data(42))) // {"a": 42, "b": "42"}
    val obj = JSON.parse<Data>("""{"a":42}""") // Data(a=42, b="42")
}
```
Results in an exception:
`kotlinx.serialization.SerializationException: Can't locate default serializer for class class com.intuit.connect_to_pro.lambda_common_core.handler.Data`

Kotlin 1.2.41
Kotlinx 0.5.0

**Comment by sandwwraith** [comment]
Looks like you forgot to apply plugin in buildscript?

**Comment by inuwan** [comment]
I have these plugin in my build.gradle.kts file:

**Comment by sandwwraith** [comment]
I'm afraid new `plugins` gradle block is not working with this plugin, since `kotlinx-serialization` for gradle is not uploaded to Gradle Plugin Portal yet. You can look for workaround here: #91 or use more traditional `apply` block.

**Comment by jexp** [comment]
It also didn't work for me in the apply block.
It still said plugin not found.

here is the build.gradle.kts:


```
buildscript {
    var kotlin_version: String by extra
    kotlin_version = "1.2.41"

    repositories {
        mavenCentral()
        maven (url="https://kotlin.bintray.com/kotlinx" )
    }
    dependencies {
        classpath(kotlin("gradle-plugin", kotlin_version))
        classpath("org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.5.0")
    }
}

plugins {
    application
    java
    kotlin("jvm") version "1.2.41"
}
apply {
    plugin("kotlinx-serialization")
}

val kotlin_version: String by extra

repositories {
    mavenCentral()
    jcenter()
    maven (url="https://kotlin.bintray.com/kotlinx" )
}

dependencies {
    compile(kotlin("stdlib-jdk8", kotlin_version))
    compile("org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.5.0")
}

```

**Comment by sandwwraith** [comment]
@jexp `buildscript.dependencies` class path should have `classpath "org.jetbrains.kotlinx:kotlinx-gradle-serialization-plugin:$serialization_version"`, not runtime library
