### ISSUE TITLE
JSON decodeFromString never terminates with some invalid inputs (JsonLexer.skipElement loops infinitely) => huge battery drain.

### ISSUE THREAD

**Issue by valeriyo** [Kotlin/kotlinx.serialization#1474]
Duplicating from https://youtrack.jetbrains.com/issue/KT-46611

Using Kotlin 1.5.0 with org.jetbrains.kotlinx:kotlinx-serialization-json:1.2.0 (latest)

Given:
```
@Serializable
class Something

val json = Json { ignoreUnknownKeys = true }
```

.. this expression never terminates (with an exception) as it should, because the input is not valid JSON:
```
json.decodeFromString(Something.serializer(), """{"a":[{"b":[{"c":{}d",""e"":"}]}""")
```

Looks like the JsonLexer hits the end of input string, thus consumeNextToken() returns TC_EOF. After that, the while loop inside skipElement() keeps spinning forever.

**Comment by sandwwraith** [comment]
Have it worked with 1.1.0? Seems that is a general bug, not a regression....

**Comment by valeriyo** [comment]
I wouldn't know, but since 1.2.0 generates garbage (https://github.com/Kotlin/kotlinx.serialization/issues/1455) -- I hit this issue.
