### ISSUE TITLE
Unable to use UInt in custom serializer

### ISSUE THREAD

**Issue by msrd0** [Kotlin/kotlinx.serialization#1480]
**Describe the bug**

I tried to use `UInt` in a custom serializer. Unfortunately, it throws an exception at runtime.

**To Reproduce**

```kotlin
@Serializable(with = Foo.Serializer::class)
class Foo(val bar: UInt) {
	internal class Serializer : KSerializer<Foo> {
		override val descriptor: SerialDescriptor =
			buildClassSerialDescriptor("org.example.Foo") {
				element<UInt>("bar")
			}
		// ...
	}
}
```

This produces the following exception at runtime:

```
kotlinx.serialization.SerializationException: Serializer for class 'UInt' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
	at kotlinx.serialization.internal.Platform_commonKt.serializerNotRegistered(Platform.common.kt:91)
```

The first line in the stacktrace pointing at my code is at the `element<UInt>("bar")` line.

**Environment**
 - Kotlin version: 1.5.0
 - Library version: both 1.1.0 and 1.2.1 produce this exception
 - Kotlin platforms: JVM
 - Gradle version: 7.0
 - Java version: 11.0.11 (OpenJDK)

**Comment by sandwwraith** [comment]
As a workaround, you can use `element("bar", UInt.serializer().descriptor)`

**Comment by msrd0** [comment]
@sandwwraith Using `Class.serializer()` only seems to work for types defined in the same module with `@Serializable` annotation, using `UInt.serializer()` (or `String.serializer()`) produces the following compile error:

```
Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public fun <T : Any> KClass<TypeVariable(T)>.serializer(): KSerializer<TypeVariable(T)> defined in kotlinx.serialization
public inline fun <reified T> SerializersModule.serializer(): KSerializer<TypeVariable(T)> defined in kotlinx.serialization
public fun SerializersModule.serializer(type: Type): KSerializer<Any> defined in kotlinx.serialization
public fun SerializersModule.serializer(type: KType): KSerializer<Any?> defined in kotlinx.serialization
```

**Comment by sandwwraith** [comment]
Try to import this function: https://github.com/Kotlin/kotlinx.serialization/blob/ac5450475f5e6e86f7de0db821bfc6014befb126/core/commonMain/src/kotlinx/serialization/builtins/BuiltinSerializers.kt#L198
