### ISSUE TITLE
polymorphic deserialization produces different results depending on the phase of the moon (fixed by gradle clean)

### ISSUE THREAD

**Issue by AcidApeStudios** [Kotlin/kotlinx.serialization#1481]
In compilation unit A we have this:

```
abstract class BaseContainer {
    @Serializable
    protected abstract class Base {
        var b: Int? = null
    }
}
```

In compilation unit B we have this:

```
class DerivedContainer : BaseContainer() {
    @Serializable
    @SerialName("derived")
    private class Derived : Base() {
        var d = 0
    }

    val json = Json {
        ignoreUnknownKeys = true

        classDiscriminator = "t"

        serializersModule = SerializersModule {
            polymorphic(Base::class) {
                subclass(Derived::class)
            }
        }
    }
}
```

Sometimes, deserializing a `Base` as follows:

```
json.decodeFromString<Base>("""{"t":"derived","d":3}""")
```

Fails because `Base.b` is not considered optional.

Deserialization always succeeds after a clean build. Deserialization may succeed if we move `Base` to the compilation unit where `Derived` is declared.

This is related to #378 and #817, which were supposedly fixed. Quoting @sandwwraith in #378: "I can confirm that most of the bugs related to multi-module/project setups are fixed in Kotlin 1.4 (starting from 1.4-M3, to be precise). So this long and painful story is finally over.".

Well, this painful story is not over yet.

**Environment**
 - Kotlin version: 1.5.0
 - Library version: 1.2.0
 - Kotlin platforms: JVM on Android
 - Gradle version: 7.0.1
 - IDE version: Android Studio 4.2.1, AGP 4.2.1

**Comment by elkasvirElka** [comment]
@AcidApeStudios hello, did you get any reply or luck to fix this bug,
I am having the same issue.

**Comment by elkasvirElka** [comment]
@AcidApeStudios I put the serializable abstract class to a different file(with the same name) in library A
in library B I'm trying to extend this class and I see the same issue:
Fields that I made optional in abstract class are missing values.

Do you have multi library project also?

**Comment by AcidApeStudios** [comment]
@elkasvirElka No, all our serializable classes are in the same subproject.
