### ISSUE TITLE
Get SerialName value?

### ISSUE THREAD

**Issue by P1NG2WIN** [Kotlin/kotlinx.serialization#1482]
How can I get the SerialName annotation value in code?

With gson i use that extensions but after change `SerializedName` to `SerialName `they return null

```
fun KProperty<*>.serializedName(): String? {
    return javaField
        ?.getAnnotation(SerializedName::class.java)
        ?.value
}

fun KProperty<*>.serializedName(defaultValue: String): String {
    return javaField
        ?.getAnnotation(SerializedName::class.java)
        ?.value ?: defaultValue
}
```

**Comment by P1NG2WIN** [comment]
fixed functions. Now all works

```
fun KProperty<*>.serializedName() =
    (annotations.find { it is SerialName } as? SerialName)
        ?.value

fun KProperty<*>.serializedName(defaultValue: String) =
    (annotations.find { it is SerialName } as? SerialName)
        ?.value ?: defaultValue
```


Is there a way to get value without reflection?

**Comment by sandwwraith** [comment]
Property serial name is stored in corresponding class' `SerialDescriptor`. Try this example: `Int.serializer().descriptor.elementNames.toList()`. Also check out `getElementName/getElementIndex`
