### ISSUE TITLE
Boolean is not serialising 

### ISSUE THREAD

**Issue by kksingla** [Kotlin/kotlinx.serialization#1485]
if I'm serializing this class then output is: "{}" 

**To Reproduce**
```
data class Test(val isActive:Boolean)

Json().encodeToString(Test(false))
```

**Expected behavior**
"{"isActive":false}" 

**Environment**
 - Kotlin version: [1.5.0]
 - Library version: [1.2.0]
 - Kotlin platforms: [Native]
 - Gradle version: [4.2]
 - IDE version [Android Studio 3.4]

    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:1.2.0"

**Comment by ArcticLampyrid** [comment]
```diff
+ @Serializable
data class Test(val isActive:Boolean)
```

**Comment by qwwdfsad** [comment]
Could you please provide a self-contained reproducer? Code in your example does not compile, but the corrected version:
```
@Serializable
data class Test(val isActive:Boolean)

fun main() {    
    println(Json.encodeToString(Test(false)))
}

```

works as expected and prints `{"isActive":false}`.
Also, please ensure that your property does not have default value (e.g. `data class Foo(val a: Boolean = false)`. Default values are not serialized by default, unless `encodeDefaults` flag is specified: `Json { encodeDefaults = true }`

**Comment by kksingla** [comment]
If I add, Json { encodeDefaults = true }, even without adding default value, then only boolean are serialising
