### ISSUE TITLE
Exclude class discriminator

### ISSUE THREAD

**Issue by P1NG2WIN** [Kotlin/kotlinx.serialization#1487]
Right now in `Json { }` we cannot disable write `classDiscriminator`. In source code i found that class discriminator can be ignored if we change `writePolymorphic boolean` inside `encodePolymorphically` in `StreamingJsonEncoder`. Can i somehow change it without fully fork your library and change all layers? Maybe somehow with extension

**Comment by Dominaezzz** [comment]
You can skip the writing of the `classDiscriminator` by using the serializer of the child class instead of the base class.

**Comment by P1NG2WIN** [comment]
> You can skip the writing of the `classDiscriminator` by using the serializer of the child class instead of the base class.

Can you provide example?

**Comment by sandwwraith** [comment]
```kotlin
val data = ChildClass("...")
Json.encodeToString<ParentClass>(data) // discriminator written
Json.encodeToString<ChildClass>(data) // discriminator omitted
```

**Comment by P1NG2WIN** [comment]
In my case, this will not suit

**Comment by sandwwraith** [comment]
What's your use case for excluding the discriminator? You won't be able to decode polymorphic data without it.

**Comment by Whathecode** [comment]
Probably the other posted issue: https://github.com/Kotlin/kotlinx.serialization/issues/1486#issue-892136945

**Comment by P1NG2WIN** [comment]
@sandwwraith I don't need to decode this json. He goes to the server. The server does not accept unknown fields. Now I forked the library and added a new field to the builder, so now I have two Json instances, one for the application that writes the class discriminator and the other for the api, which skips it when serializing.

**Comment by sandwwraith** [comment]
I'll close this because #1247 already mentions this use-case — feel free to continue the discussion there
