### ISSUE TITLE
How can I store inherited types in json field?

### ISSUE THREAD

**Issue by alexandr2levin** [Kotlin/kotlinx.serialization#149]
What I want to declare:

```
@Serializable
interface Base {
    val base: Boolean
}

@SerializableTypeName("a")
@Serializable
data class A(
    ...
) : Base

@SerializableTypeName("b")
@Serializable
data class B(
    ...
) : Base

@Serializable
data Foo(
    val objects: List<Base>
)
```

What I want to see in result:

```
{
    "objects": [
        {
            "$type": "a",
            ...
        },
        {
            "$type": "b",
            ...
        }
    ]
}
```

**Comment by pdvrieze** [comment]
This is only possible with a custom serializer. Additionally annotations on types are not available to the serialization code so you would need reflection for serialization. There is unfortunately no way for the deserialization code to know to look for class A or class B so again you would need to hardcode those options into your custom (de)serializer. Sealed classes should allow this last problem to be solved but they don't work correctly at the moment.

**Comment by sandwwraith** [comment]
It seems the same as #50.

**Comment by luca992** [comment]
Is there an example of how to use the the new polymorphic serializer as described here? I do not see much documentation on it. @sandwwraith

**Comment by sandwwraith** [comment]
@luca992 Most of the documentation is in the KDoc for `PolymorphicSerializer`: https://github.com/kotlin/kotlinx.serialization/blob/74b480237ca3a244cf41d3c7f1e83c8259bf8d6f/runtime/common/src/main/kotlin/kotlinx/serialization/Polymorphic.kt#L30

**Comment by luca992** [comment]
Doesn't really explain how to use if for @alexandr2levin 's example...
But i've figured it out:

```
abstract class Base {
}

@SerialName("a")
@Serializable
data class A(
    ...
) : Base()

@SerialName("b")
@Serializable
data class B(
    ...
) : Base

@Serializable
data Foo(
    val objects: List<@Polymorphic Base>
)



    Json(
        context = SerializersModule {
            polymorphic(Base::class) {
                A::class with A.serializer()
                B::class with B.serializer()
            }
        }
    )
    
```
