### ISSUE TITLE
How big is this library? - for use in android

### ISSUE THREAD

**Issue by jrcacd** [Kotlin/kotlinx.serialization#150]

**Comment by sandwwraith** [comment]
I haven't measured exact size in megabytes or methods count, but it should not be big. Library doesn't contains any dependencies except stdlib. Try it on and feel free to share your measurements here.

**Comment by IslamSalah** [comment]
On checking the library size for [v1.1.0 ](https://github.com/Kotlin/kotlinx.serialization/releases/tag/v1.1.0) in the AS APK analyzer, it was **~220 KB** 
@sandwwraith can you please let us know it if there are more accurate numbers than the shared ones?
<img width="572" alt="kotlinx serialization lib size" src="https://user-images.githubusercontent.com/8607770/113521381-73c8b380-9599-11eb-9f6a-c530f385575b.png">
