### ISSUE TITLE
ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by ikovalyov** [Kotlin/kotlinx.serialization#1504]
**Describe the bug**
I have a multiplatofrm project with data classes in the common project and jvm web service using them. Serializing this data class in jvm throws an exception 

**To Reproduce**
```
// In the common 
@Serializable
data class Template(
    val id: String,
    val template: String,
    val lastModified: Instant = Clock.System.now()
) {
    companion object {
        fun create(id: String, template: String) = Template(id, template, Clock.System.now())
    }
}

//In the jvm
        val template = Template(
            id = "123", template = """
            <#--

                Copyright 2017-2019 original authors

                Licensed under the Apache License, Version 2.0 (the "License"
        """.trimIndent()
        )
        val string = try {
            Json.encodeToString(Template.serializer(), template)
        } catch (t: Throwable) {
            logger.error("cant encode", t)
            ""
        }
```

throws an exception
java.lang.ArrayIndexOutOfBoundsException: Index 138 out of bounds for length 138

If I remove first line of the template ("Copyright 2017-2019 original authors") `encodeToString` works fine

**Expected behavior**
No exception thrown

**Environment**
 - Kotlin version: [e.g. 1.3.30]
 - Library version: [e.g. 0.11.0]
 - Kotlin platforms: [e.g. JVM, JS, Native or their combinations]
 - Gradle version: [e.g. 4.10]
 - IDE version (if bug is related to the IDE) [e.g. IntellijIDEA 2019.1, Android Studio 3.4]
 - Other relevant context [e.g. OS version, JRE version, ... ]

**Comment by qwwdfsad** [comment]
This is a bug present in 1.2.0 and fixed in 1.2.1. Please update your library version and see if that helps
