### ISSUE TITLE
CBOR List of Type 2 ByteStrings

### ISSUE THREAD

**Issue by MatthijsZooma** [Kotlin/kotlinx.serialization#1508]
**What is your use-case and why do you need this feature?**
Using the CBOR @ByteString annotation, I'm trying to encode every single ByteArray in a list as a cbor type 2 string.
![image](https://user-images.githubusercontent.com/84580007/119149684-063fec00-ba4e-11eb-89bf-6f517c064450.png)

Seeing as a list of ByteString is a valid cbor message, it cannot be parsed right as far as I know.

**Describe the solution you'd like**
I'd love a solution, be it a new annotation or increased functionality of the current @ByteString annotation to make sure every ByteArray entry in a list can be decoded or encoded as a type 2 CBor data value.

![image](https://user-images.githubusercontent.com/84580007/119150476-c7f6fc80-ba4e-11eb-9929-0677f10162ed.png)

**Comment by sandwwraith** [comment]
Implemented

**Comment by Andy-Bigler** [comment]
![image](https://github.com/Kotlin/kotlinx.serialization/assets/17875084/99208dc8-b38d-4102-adc9-971269e294e5)
