### ISSUE TITLE
Polymorphic serialization with custom logic instead of discriminator

### ISSUE THREAD

**Issue by brettwillis** [Kotlin/kotlinx.serialization#1513]
Currently, polymorphic serialization relies on the use of a discriminator field. Is there any way to implement a custom discrimination logic instead of a discriminator field?

### Consider the following simplistic example:

Data from the server indicates the approval state of an item, 

```JavaScript
{
  "approved": true, // Approved globally
  ...
}
```

or 

```JavaScript
{
  "approved": ["uid123", "uid456"], // Approved for a list of users
  ...
}
```

In Kotlin this can be represented as a sealed class:

```Kotlin
sealed class Approval {
    class Global(val approved: Boolean): Approval()

    class Restricted(val userIds: List<String>)
}
```

I had hoped that I could write a custom serializer for `Approval`, with it's own logic to distindguish between the two different data shapes: `true`/`false` and `["uid123", ...]`, instead of `{"type": "Global", "approved": true}` and `{"type": "Restricted", "userIds": [...]}`. But it seems to be that the `SerialDescriptor` enforces a fixed data shape, and the `Decoder` interface doesn't seem to allow me to "test" the shape of the field (primitive boolean vs list).

Of course this is a basic example, and we could talk about changing the data shape to begin with, but people have to work with existing data/APIs, and there can also be more complex examples...

Is there a way to workaround to implement custom discrimination logic and dynamic data shapes?

**Comment by brettwillis** [comment]
Here is where I started with the custom serializer, but you can see I quickly felt suspicious that this isn't possible?

```Kotlin
@Serializer(forClass = Approval::class)
class ApprovalSerializer: KSerializer<Approval> {

    override val descriptor: SerialDescriptor
        get() = TODO("The descriptor is not fixed, it could be a primitive or a sub-structure...?")

    override fun deserialize(decoder: Decoder): Approval {
        TODO("What decoder API can I use to test if we are encountering a Boolean or a List?")
    }

    override fun serialize(encoder: Encoder, value: Approval) {
        
    }
}
```

**Comment by sandwwraith** [comment]
It's possible with a custom serializer, but we have a feature that makes this task much easier. Check out docs for `JsonContentPolymorphicSerializer `: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#content-based-polymorphic-deserialization

**Comment by brettwillis** [comment]
@sandwwraith Thank you! I read the docs but somehow I missed this.
