### ISSUE TITLE
Uncaught ReferenceError: this$ is not defined

### ISSUE THREAD

**Issue by Grouen** [Kotlin/kotlinx.serialization#1514]
**To Reproduce**

```
@Serializable
class A(val b: B) {
    init {
        b.apply {
            callMe()
        }
    }
}

@Serializable
class B {
    fun A.callMe() {
    }
}
```

**Expected behavior**

When I remove @Serializable it works fine

**Environment**
 - Kotlin version: [1.5.10]
 - Library version: [1.2.1]
 - Kotlin platforms: [JS]
 - Gradle version: [6.7.1]
 - IDE version (if bug is related to the IDE) [e.g. IntellijIDEA 2019.1, Android Studio 3.4]
 - Other relevant context [e.g. OS version, JRE version, ... ]

**Comment by sandwwraith** [comment]
Have you tried JS IR? This is a known problem in JS legacy compiler (https://github.com/Kotlin/kotlinx.serialization/issues/247)

**Comment by Grouen** [comment]
Oh, yes your right. Just new project has old compiler by default. I didn't notice it.
