### ISSUE TITLE
EncodeDefaults = false has unexpected behavior

### ISSUE THREAD

**Issue by patrickwilmes** [Kotlin/kotlinx.serialization#1518]
Using the kotlinx serialization version 1.0.1 I encountered the following 'strange' behavior:

Given an interface like:
```kotlin
interface Event {
     val occurredOn: Long
}
```
and and a parent implementation class like:
```kotlin
@Serializeable
sealed class ADomainEvent(
    val someField: String
): Event {
    override val occurredOn = LocalDateTime.now().atZone(defaultTimezone).toInstant().toEpochMilli()
}
```
and last a specialized form of the parent:
```kotlin
@Serializeable
data class ASpecialDomainEvent (
    val ident: Long,
): ADomainEvent("someFieldValue")
```
Having the json configuration value `encodeDefaults` not set (stays on default false) `Json.encodeToString` behaves
randomly regarding the occurredOn field: Sometimes it's correctly serialized, sometimes it's missing what would be expected 
as it has a default value.

Setting the `encodeDefault` configuration to true solves the issue.

**To Reproduce**
Create an interface with a field like in the example above.
Create another class overriding the field and assigning a default value to it.
Go ahead and create multiple instances of the class and serialize them using the standard Json configuration like:

```kotlin
repeat(1000) {
    val instance = ASpecialDomainEvent(indent = it)
    val encodedString = Json.encodeToString(ASpecialDomainEvent.serializer(), instance)
}
```
Now the occorredOn field will only be sometimes serialized in encodedString and sometimes missing.

**Expected behavior**
If the `encodedDefaults` flag is not set explicitly: all default values are ignored
If the `encodedDefaults` flag is set to true, default values are encoded

**Environment**
 - Kotlin version: 1.4.21
 - Library version: 1.0.1
 - Kotlin platforms: JVM
 - Gradle version: 6.7.1
 - JDK: OpenJDK 11

**Comment by sandwwraith** [comment]
The default value is re-evaluated each time. So, if `occurredOn` is equal to the current millisecond, it would be dropped, if not, it will be encoded.

**Comment by patrickwilmes** [comment]
hmm ok, but shouldn't it be consistent? So what I experienced was rather inconsistent behavior (in my point of view) as I did encode let's say 1000 entities each with a **different** `occurredOn` value and sometimes the value was there and sometimes not.
Or did I get something wrong?

**Comment by patrickwilmes** [comment]
yes that's totally true and we use it right now as this seems to be the solution. What I am talking about is that if I generate a bunch of objects of the same type and different date values (timestamps) it does not have consistent behavior in my opinion. I would expect the library to not encode the value at all as in the documentation is stated that default values are ignored.
