### ISSUE TITLE
Deserialize json that can be jsonObject or jsonArray

### ISSUE THREAD

**Issue by GautierLouis** [Kotlin/kotlinx.serialization#1519]
Hello,
I'm looking for a way to deserialize strings into object. Some time, the propery 'icon' can be an array (insead of object) and I can't figured out who to return an empty Icon in this particular case.

```
@Serializable
data class Menu(
    val index: Int,
    val icon: Icon?
)

@Serializable
data class Icon(
        val type: String,
        val value: String
)

```

```
val a = """{"index": 0,"icon": {"type": "myType","value": "myValue"}}"""
val b = """{"index": 0,"icon": []}"""
println(Json.decodeFromString<Menu>(a))
println(Json.decodeFromString<Menu>(b)) //failed
```

**Comment by sandwwraith** [comment]
I think [this documentation section](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#json-transformations) should help you

**Comment by GautierLouis** [comment]
Oh Tanks you. I didn't saw that. Really helpful

**Comment by GautierLouis** [comment]
object IconSerializer : JsonTransformingSerializer<Icon>(Icon.serializer()) {
    // If response is an array, then return a empty Icon
    override fun transformDeserialize(element: JsonElement): JsonElement =
            if (element is JsonArray) {
                val a: Map<String, JsonElement> = mapOf("type" to JsonPrimitive(""), "value" to JsonPrimitive(""))
                JsonObject(a)
            } else element
}

**Comment by sou1maker** [comment]
I follow the documentation to set it up but it doesn't work, I get an error like this: 

> Expected class kotlinx.serialization.json.JsonArray (Kotlin reflection is not available) as the serialized body of kotlin.collections.ArrayList, but had class kotlinx.serialization.json.JsonObject (Kotlin reflection is not available)

this is my json：

> "description": [] 

or 

> "description": {"en": "Dog Ningen"}

**Comment by sou1maker** [comment]
I think it is possible that the serializer can only match once, that is to say, the first occurrence of `[]`, then the subsequent will not be able to process `{}`

**Comment by GautierLouis** [comment]
In this case, I think your serializer should be on `MangaAttributes` and check if property `description` is an array or object.
It's a bit verbose because you have to do the serialization yourself
