### ISSUE TITLE
UByteArray should be serializable

### ISSUE THREAD

**Issue by NorbertSandor** [Kotlin/kotlinx.serialization#1529]
I wanted to change the type of a property from `ByteArray` to `UByteArray`.
It turned out that only the former is serializable.
I think `UByteArray` should be serializable by default as well.

**Comment by tobias-wahlstrom-hqv** [comment]
Agree on this. When working with cbor you typically interface with a embedded/tiny system that is using unsigned bytes. In the case of bytes, working with signed ones is the odd/strange case. Unsigned is the way to go!

**Comment by sandwwraith** [comment]
Duplicate of #1989 — will be fixed in Kotlin 1.7.20 (see #1992)
