### ISSUE TITLE
Can't decode String to ByteArray

### ISSUE THREAD

**Issue by ccc-sseylani** [Kotlin/kotlinx.serialization#1533]
**Describe the bug**
Hi there, 
I am facing a really weird issue.
I am fetching a JSON file from Api (with ktor). But I am getting this issue
I am expecting to receive a list of Asset class but it keeps complaining that
 """
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 15: Expected start of the array '[', but had ':' instead
JSON input: {"asset":[{"id":"AzWSKY5\/Eeu06AJCwKhABQ==",".....
"""
Json format is in right format, and I can easily get the desired  result with GSON and Retrofit.
Is this a bug with kotlin serialization?

**To Reproduce**
Attach a code snippet or test data if possible.

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/75082292/120816712-01d00480-c51f-11eb-82c6-a200a9d4741c.png">

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/75082292/120816823-1e6c3c80-c51f-11eb-8464-b1f55f50d012.png">

<img width="890" alt="image" src="https://user-images.githubusercontent.com/75082292/120816909-35129380-c51f-11eb-9a18-56ee4659fc41.png">

**Expected behavior**

Accept the Json file and convert it to AppData object.

**Environment**
 - Kotlin version: [1.5.0] 
 - Library version: [1.5.0]
 - Kotlin platforms: [e.g. JVM, JS, Native or their combinations]
 - Gradle version: [e.g. 4.10]
 - IDE version (if bug is related to the IDE) [e.g. IntellijIDEA 2019.1, Android Studio 3.4]
 - Other relevant context [e.g. OS version, JRE version, ... ]

**Comment by sandwwraith** [comment]
What version do you use? There's no `1.6.0` version

**Comment by ccc-sseylani** [comment]
> What version do you use? There's no `1.6.0` version

sorry, KTOR is 1.6.0. Library version is 1.5.0

**Comment by sandwwraith** [comment]
There's no 1.5.0 either

**Comment by ccc-sseylani** [comment]
> There's no 1.5.0 either
It was 1.0.0
just updated to 1.2.1
Still same error
<img width="1179" alt="image" src="https://user-images.githubusercontent.com/75082292/120826986-faadf400-c528-11eb-9087-b7b3e73d4e6e.png">
<img width="829" alt="image" src="https://user-images.githubusercontent.com/75082292/120827111-19ac8600-c529-11eb-84d9-332bbac05778.png">

**Comment by sandwwraith** [comment]
Error says that `Asset.id` type is declared in your code as a List, while input is a string

**Comment by ccc-sseylani** [comment]
> Error says that `Asset.id` type is declared in your code as a List, while input is a string

Interesting!, All of the IDs in our project used to be saved as ByteArray and there was not an error with GSON and retrofit, but apparently KOTLIN  does not accept it. 
I just changed the type of Id to String, and there is no error for that offset anymore. But all of the primary keys and foreign keys are saved as ByteArray in our application, and we have a pretty big database. Is there any way that I can keep the type of Id as a ByteArray? 
What is the best solution here?
Thanks

**Comment by sandwwraith** [comment]
It seems it was a Base-64 encoded byte array then. kotlinx.serialization, unlike GSON, does not support Bsae64 encoding out of the box — you need to write a [custom serializer](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#custom-serializers) for byte array

**Comment by sandwwraith** [comment]
Probably we need to provide `ByteArrayAsBase64StringSerializer` in the JSON jar, but not use it as a default serializer (as with `LongAsStringSerializer`) cc @qwwdfsad

**Comment by ccc-sseylani** [comment]
> It seems it was a Base-64 encoded byte array then. kotlinx.serialization, unlike GSON, does not support Bsae64 encoding out of the box — you need to write a [custom serializer](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#custom-serializers) for byte array

We have more than 60 classes, and 80% of them include a lot of ID as foreign keys. Do I need to write a custom serializer for all of the classes that we have?  or is It possible to create a parent class for a custom serializer and use that one for all of the classes?  Thanks

**Comment by Dominaezzz** [comment]
You just need one custom serializer like `LongAsStringSerializer`.
Then you can annotate the particular fields with the custom serializer.
