### ISSUE TITLE
CBOR tagged data can't be deserialized

### ISSUE THREAD

**Issue by wkornewald** [Kotlin/kotlinx.serialization#1560]
**Describe the bug**

When you have CBOR data that is tagged, deserialization fails with an exception. With tags I'm referring to section 3.4 of the RFC:

https://datatracker.ietf.org/doc/html/rfc8949#section-3.4

In our case for the CovPass / covid vaccination certificate app some countries use tag 0 to annotate strings as being in date/time format.

The other issue is that we can't decode the COSE data format because the array is tagged with 18:

https://cose-wg.github.io/cose-spec/#rfc.appendix.C.2.1

1. By default, tags should just be ignored during deserialization.
2. We could need an annotation that a certain tag should be used for serialization and optionally also be required during deserialization.
3. For more dynamic tagging something like a special `CborTagged(tag, data)` object would be nice which allows extracting arbitrary tags (or null) during deserialization and setting arbitrary tags during serialization.

**Environment**
 - Kotlin version: 1.5.10
 - Library version: 1.2.1

**Comment by Gyurme-Mattr** [comment]
It looks like the changes in https://github.com/Kotlin/kotlinx.serialization/pull/1614 allows parsing of tagged date strings which is great!

I was wondering if anything was in the works for supporting tags in the other issue mentioned, similar to tag 18 there is also tag 24 (https://www.rfc-editor.org/rfc/rfc8949.html#section-3.4.5.1) that is used to indicated embedded CBOR items that causes a similar exception

I'm currently looking at getting tag 24 ignored in my test fork but wondering if some other approach was better 🤔

**Comment by wkornewald** [comment]
Not really. We need to be able to work with the tags, i.e. match them or extract them and set them.

**Comment by sandwwraith** [comment]
I'll leave this open then

**Comment by JesusMcCloud** [comment]
see #2412
