### ISSUE TITLE
It's impossible to parse non-string keys (e.g. see CBOR Web Tokens)

### ISSUE THREAD

**Issue by wkornewald** [Kotlin/kotlinx.serialization#1561]
**Describe the bug**

According to the RFC, CBOR Web Tokens use a map with integer keys:

https://datatracker.ietf.org/doc/html/rfc8392

Currently, there is no way to parse such data. Ideally, `@SerialName` would support arbitrary keys (integer, string, etc.), but even parsing into a `Map` didn't seem to work because the implementation assumes that keys can only be strings.

**Environment**
 - Kotlin version: 1.5.10
 - Library version: 1.2.1

**Comment by JesusMcCloud** [comment]
see  #2412

**Comment by sandwwraith** [comment]
I suppose it is supported by now via `@CborLabel`
