### ISSUE TITLE
Compiler plugin is incorrect in its recognition of primitive type descriptors

### ISSUE THREAD

**Issue by pdvrieze** [Kotlin/kotlinx.serialization#1567]
**Describe the bug**
(See https://github.com/pdvrieze/xmlutil/issues/68). What is happening is that the FQN of the type is the same as the single letter primitive descriptor, the type will be recognized as the primitive, not the actual type (and the child serializer used is for that type)

**To Reproduce**
Attach a code snippet or test data if possible.

In the **anonymous package**, create a serializable class `A` that contains an attribute of type of another class `B` (that isn't nested). Look at the generated serializer for `A`, it will have a child serializer of type `ByteSerializer` for the child, not the generated serializer for B.

**Expected behavior**
Correctly reference the child type.

**Environment**
 - Kotlin version: 1.5.10
 - Library version: 1.2.1
 - Kotlin platforms: JVM
 - Gradle version: 7

**Comment by sandwwraith** [comment]
#1353 

Happens only when classes are in the default package
