### ISSUE TITLE
Sealed interface @Serializable support

### ISSUE THREAD

**Issue by y9san9** [Kotlin/kotlinx.serialization#1576]
I don't know if it is a bug but just wanted to ask, why can I do `abstract val` stuff with sealed classes but can't do the same thing with interfaces.
![image](https://user-images.githubusercontent.com/46930374/123763849-e1505b80-d8cc-11eb-8171-7405fca97e9d.png)
![image](https://user-images.githubusercontent.com/46930374/123763868-e6150f80-d8cc-11eb-83e5-dea4af6c5ee0.png)

**Comment by pdvrieze** [comment]
In general, interfaces can not be marked serializable. However sealed interfaces are sort of an exception. However sealed interfaces are a new feature, so I suspect it is not implemented yet in the compiler plugin.

**Comment by y9san9** [comment]
Then the issue is actual, waiting for implementing 🙃

**Comment by sandwwraith** [comment]
sealed interfaces are currently treated as regular interfaces (can't have serializable annotation and require serializers module). In the future, yes, `@Serializable` annotation on sealed interfaces would be supported

**Comment by PaulWoitaschek** [comment]
And this feature is tracked here? Is there a roadmap for it?
Currently when I only need sealed to get compile time safety I go with sealed interfaces over classes, but whenever I need sth to be serializable I now need to go back to sealed classes.

**Comment by LouisCAD** [comment]
Is this supported for protobuf too?
