### ISSUE TITLE
New error with 1.2.1: Uncaught TypeError: Cannot read property 'dumpTo_ukvgvw$' of undefined

### ISSUE THREAD

**Issue by TorRanfelt** [Kotlin/kotlinx.serialization#1577]
I wanted to bump kotlinx-serialization-json from 1.1.0 to 1.2.1 and suddenly I get this error in the Chrome-console:

```
Uncaught TypeError: Cannot read property 'dumpTo_ukvgvw$' of undefined
    at JsonImpl.validateConfiguration_0 (main.js:133769)
    at new JsonImpl (main.js:133763)
    at Json_0 (main.js:133687)
    at new BoksDataBundler$Companion (main.js:341485)
    at BoksDataBundler$Companion_getInstance (main.js:341702)
    at new BoksDataBundler (main.js:341481)
    at main.js:520985
    at Object.<anonymous> (main.js:521442)
    at Object../build/kotlin-js/main/main.js (main.js:521445)
    at __webpack_require__ (main.js:20)
```

The datastructure being deserialized is huge both in size and in dimensionality (many variables).

**Environment**
 - Kotlin version: 1.5.20
 - Library version: 1.2.1
 - Kotlin platforms: JS
 - Gradle version: 6.8.3

**Comment by sandwwraith** [comment]
`dumpTo` is a special internal method of `SerializersModule` that doesn't play part in the actual deserialization, so this error is kinda strange. Are you sure that you have only one version of serialization in your classpath? If you could provide a reproducer project, this also may help

**Comment by TorRanfelt** [comment]
@sandwwraith Just checked with 1.2.2 and the problem persists.

So for each main project we have there is a dependency to kotlinx-serialization-json used for serializing/deserializing data-blobs (the data-structure is huge in size and dimensionality).

All main projects use a common dependency that handles communication. This has its own dependency on kotlinx-serialization-json. The reason it that communication might not be in the same format that our data-blobs are in (although right now all of it is json), and our data-blobs might not be the same across all main projects.

I have checked and it there is no problem if the dependency that handles communication use kotlinx-serialization-json:1.2.2 while kotlinx-serialization-json:1.1.0 is by the main project for serializing/deserializing the data-blob. The Problem only happens if the main project use a version of kotlinx-serialization-json later than 1.1.0.
Again this data-structure is huge (thousands of variables, lists, arrays, maps and in many cases nested).

**Comment by pdvrieze** [comment]
This looks very much like a conflict between different versions of the serialization library. Try to inspect which versions are pulled in. It certainly should not be related to the actual data being serialized.

**Comment by sandwwraith** [comment]
So you're saying that if you set both dependencies to 1.2.2, this error occurs? Maybe your main project has another third-party dep that uses an old serialization-json version?

**Comment by TorRanfelt** [comment]
> So you're saying that if you set both dependencies to 1.2.2, this error occurs?

That is exactly what I'm saying. - Don't know if it matters, but we also use kotlinx-serialization-properties in the same version as kotlinx-serialization-json in the main project.

> Maybe your main project has another third-party dep that uses an old serialization-json version?

Maybe. It's worth looking into although I'll be surprised if any of them needs to serialize/deserialize json.
I don't have access to the projects for the next few weeks due to vacation, but I'll look into it when I get the opportunity.

**Comment by TorRanfelt** [comment]
@sandwwraith 
These are the 3rd party kotlin-libraries we use:
org.jetbrains.kotlinx:kotlinx-coroutines-core-js:1.5.0
org.jetbrains.kotlin-wrappers:kotlin-extensions:1.0.1-pre.213-kotlin-1.5.20
org.jetbrains:kotlin-react:16.13.1-pre.123-kotlin-1.4.10
org.jetbrains:kotlin-react-dom:16.13.1-pre.123-kotlin-1.4.10
org.jetbrains:kotlin-react-router-dom:5.1.2-pre.123-kotlin-1.4.10

**Comment by TorRanfelt** [comment]
@sandwwraith 
I have gone through the javascript stack and looked through the kotlin code it reflects, and dumpto is being called in 1.3.1 already at initialization of Json:

```
class BoksDataBundler : IBoksDataBundler {
    companion object {
        val jsonMapper = Json {
            encodeDefaults = true
            useArrayPolymorphism = true
            ignoreUnknownKeys = true
            allowStructuredMapKeys = true
            serializersModule = boksDataSerializersModule
        }

// From file Json.kt in kotlinx-serialization 1.3.1:
public fun Json(from: Json = Json.Default, builderAction: JsonBuilder.() -> Unit): Json {
    val builder = JsonBuilder(from)
    builder.builderAction()
    val conf = builder.build()
    return JsonImpl(conf, builder.serializersModule)
}

// ...

private class JsonImpl(configuration: JsonConfiguration, module: SerializersModule) : Json(configuration, module) {

    init {
        validateConfiguration()
    }

    private fun validateConfiguration() {
        if (serializersModule == EmptySerializersModule) return // Fast-path for in-place JSON allocations
        val collector = PolymorphismValidator(configuration.useArrayPolymorphism, configuration.classDiscriminator)
        serializersModule.dumpTo(collector)
    }
}
```

Testing with kotlin 1.6.10 and kotlinx serialization 1.3.1 the issue persists. I'm still stuck at 1.1.0.

**Comment by sandwwraith** [comment]
Indeed, `dumpTo` is called in the beginning. For some reason, `serializersModule` is undefined there, while it should be `bookDataSerializersModule`. 

Maybe it is some kind of cycle initialization problem? Try to move `boksDataSerializersModule` around or in the same companion object, or try to use JSON without module and see if the problem persists.

**Comment by TorRanfelt** [comment]
Moving boksDataSerializersModule to companion object didn't help, but not using a serializersModule helped. - Lucky for us this particular serializersModule has become empty so that solves the problem.

However, now we have a new issue that we also don't have with 1.1.0:
https://github.com/Kotlin/kotlinx.serialization/issues/1803
