### ISSUE TITLE
Incompatible types: Class cannot be converted to Class<? extends KSerializer<?>>

### ISSUE THREAD

**Issue by wakaztahir** [Kotlin/kotlinx.serialization#1579]
### Describe the bug
Error occurs during compilation , I am using a custom serializer on property inside a serializable class like this 

```
@Serializable(with = MutableStateSerializer::class)
var items = mutableStateOf(listOf<ListItem>())
```

**Error :** 
```
error: incompatible types: Class<MutableStateSerializer> cannot be converted to Class<? extends KSerializer<?>>
@kotlinx.serialization.Serializable(with = com.wakaztahir.timeline.utils.serializers.MutableStateSerializer.class)
```

This is written inside my class which is serializable

**Serializer :**

```
class MutableStateSerializer<T>(private val dataSerializer: KSerializer<T>) : KSerializer<MutableState<T>> {
    override val descriptor: SerialDescriptor = dataSerializer.descriptor

    override fun serialize(encoder: Encoder, value: MutableState<T>) =
        dataSerializer.serialize(encoder, value.value)

    override fun deserialize(decoder: Decoder): MutableState<T> =
        mutableStateOf(dataSerializer.deserialize(decoder))

}
```

I am getting this error everywhere I have a property with a custom serializer specified over it , MutableState is an interface (third party) in compose but even if I use a simple third party class like Color , still getting this error !

### To Reproduce

I am not sure if this is only because of my environment but here's what I do

 - Create a class with serializable annotation 
 - Create a property with a class holder which has no serializer available  (use Color)
 - Specify a custom serializer with serializer annotation
 - Code won't compile

### Expected behavior
Compilation should occur without the bug !

### Environment
 - Kotlin version: [e.g. 1.5.10]
 - Library version: [e.g. 1.2.1]
 - Kotlin platforms: [e.g. Android]
 - Gradle version: [e.g. 7.1-rc-1]
 - IDE version (if bug is related to the IDE) [e.g. Android Studio 2021.1.1 Canary 2]
 - Other relevant context [e.g. OS Windows]

**Comment by wakaztahir** [comment]
The Java Code it points to 

````
@kotlinx.serialization.Serializable(with = com.wakaztahir.timeline.utils.serializers.MutableStateSerializer.class) @java.lang.Deprecated() public static void getText$annotations() { }
````

Stackoverflow Question : https://stackoverflow.com/questions/68218624/error-incompatible-types-class-cannot-be-converted-to-class-extends-kseriali

**Comment by sandwwraith** [comment]
#685

**Comment by wakaztahir** [comment]
Yes I am using generics and also kapt plugin !
But I am pretty sure I was getting this error on non generics as well !
Otherwise when will it be fixed ?

Here's something else (question)
Let's say I have a generic class serializer and I am defining a property with that generic class which has a type of another class who's Serializer I would like to define in the property annotation 
Now I need to define two serializers , one for generic class and one for the type of generic 

Like this I have

`val items : MutableState<Color> = mutableStateOf(Color.Red)`

How can I define the serializer for both in the annotation for color and mutable state ? Where color and mutable state both are third party classes 

Thanks for the help in advance

**Comment by InterruptException** [comment]
Just using the default value KSerializer::class, the bug can be reproduced also.
@Serializable(with = KSerializer::class)
If using @Serializable without any argument, the error will disappear.

**Comment by shanshin** [comment]
Closed as a duplicate
