### ISSUE TITLE
Conflict Generic Type Class with Android Jetpack Compose

### ISSUE THREAD

**Issue by graycatdeveloper** [Kotlin/kotlinx.serialization#1583]
**Environment**
 - Kotlin version: 1.5.10
 - Library version: 1.2.1
 - Kotlin platforms: JVM
 - Gradle version: 7.0-bin
 - IDE version: Android Studio 2021.1.1 canary 2
 - Other relevant context: Gradle JRE 11
 
 Test App
[compose-kotlin-serialization-test.zip](https://github.com/Kotlin/kotlinx.serialization/files/6771033/compose-kotlin-serialization-test.zip)

`
buildFeatures {
    compose true
}
Caused by: java.lang.AssertionError: Couldn't load KotlinClass from ...\compose-kotlin-serialization-test\app\build\tmp\kotlin-classes\debug\com\example\myapplication\GGG.class; it may happen because class doesn't have valid Kotlin annotations
`

If you disable compose, then `GGG.class` will compile successfully

**Comment by Sanlorng** [comment]
I also encountered the same problem, when I enabled Jetpack Compose feature

**Comment by graycatdeveloper** [comment]
I found a temporary solution!
I created a separate module with a serialization plugin.
Module `my-kotlin-serialization-module` build.gradle.kts:
```
plugins {
    id 'kotlin'
    id 'org.jetbrains.kotlin.plugin.serialization'
}
dependencies {
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-json:1.2.2"
}
```
Module  `my-kotlin-serialization-module`  Source Code:
```
@Serializable
data class GGG<T>(
    val data: T? = null
)
inline fun <reified T> GGG<T>.string() = Json.encodeToString(this)
```
App build.gradle.kts
```
implementation(project(":my-kotlin-serialization-module"))
```
Test App:
```
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.material.MaterialTheme
import androidx.compose.material.Surface
import androidx.compose.material.Text
import com.agatgroup.api.GGG
import com.agatgroup.api.string
import com.agatgroup.myapplication.ui.theme.MyApplicationTheme

class MainActivity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            MyApplicationTheme {
                // A surface container using the 'background' color from the theme
                Surface(color = MaterialTheme.colors.background) {
                    Text(text = "GGG: ${GGG("test").string()}!")
                }
            }
        }
    }
}
```

**Comment by sandwwraith** [comment]
It should not be a problem on the recent Compose versions. If still reproducible, please re-open the issue.
