### ISSUE TITLE
Add support for MessagePack

### ISSUE THREAD

**Issue by doc987** [Kotlin/kotlinx.serialization#159]
https://msgpack.org/

**Comment by pdvrieze** [comment]
I don't think that various serialization formats should all be added to the core library. It could perhaps be added as extension libraries (either official or not), and many will probably live outside the project at all (in independent projects). Of course problems when writing such a library can be valid bugs / missing features.

**Comment by qwwdfsad** [comment]
Unfortunately, we don't have resources to maintain one more full-blown format of a production-level quality.

**Comment by sandwwraith** [comment]
To clarify more on that: preferable way to contribute a big, complex implementation of serialization format is to maintain your separate library with a dependency on kotlinx.serialization mechanisms. See [this comment](https://github.com/Kotlin/kotlinx.serialization/issues/160#issuecomment-401008239) and [list of community-maintained](https://github.com/Kotlin/kotlinx.serialization/blob/master/formats/README.md#other-community-supported-formats) formats.

**Comment by dlazerka** [comment]
Just some more details, as far as I know, CBOR (included in core library) is a fork of MessagePack made by IETF (more details here https://diziet.dreamwidth.org/6568.html). Correct me, if I'm wrong, but they serve the same niche, so for those who are choosing between formats, may consider `kotlinx-serialization-cbor` as well.
