### ISSUE TITLE
StackOverflowError when parsing deep JSON

### ISSUE THREAD

**Issue by tchernykh** [Kotlin/kotlinx.serialization#1594]
**Describe the bug**
JsonTreeReader class of kotlinx-serialization-json library uses recursion to parse JSON which causes StackOverflowError when JSON is deep enough. 

**To Reproduce**
```Kotlin
var json = """{ "a": %}"""
for (i in 0..12) {
    json = json.replace("%", json)
}
json = json.replace("%", "0")
Json.parseToJsonElement(json)
```

**Expected behavior**
Json parsed without crashing the app.

**Environment**
 - Kotlin version: 1.5.10
 - Library version: 1.2.1
 - Kotlin platforms: JVM
 - Gradle version: 7.0.2

**Comment by pdvrieze** [comment]
How deep a tree are you looking at? Only 12 deep should not cause a problem (the stack should be large enough to accommodate it). Consider though that the system is designed recursively on the serializer (especially the deserializer) end. Deserialization works (or has to work) by deserializing the elements in order, storing the results and when done constructing the object and returning it.

**Comment by tchernykh** [comment]
The error is thrown when tree is very deep. In the sample I've attached it duplicates depth on each iteration which generates about 65kbytes of Json. I have this error when it is 3100 nodes deep. The biggest issue is that I have it in a production application (however very rare) and there is no way around that.
I understand how json serialiser and deserialiser works and I see that it could be changed to utilise stack data structure instead of relying on recursion.

**Comment by qwwdfsad** [comment]
Thanks for the report with a reproducer! 

The serializers structure has nothing to do with that behaviour because the code _only_ uses `parseToJsonElement` on the top-level, so the question is purely implementation-specific. We'll see what we can do here

**Comment by qwwdfsad** [comment]
I have a draft PR that addresses this problem https://github.com/Kotlin/kotlinx.serialization/pull/1596
