### ISSUE TITLE
Add support for Amazon Ion

### ISSUE THREAD

**Issue by doc987** [Kotlin/kotlinx.serialization#160]
https://amzn.github.io/ion-docs/index.html

**Comment by pdvrieze** [comment]
I don't think that various serialization formats should all be added to the core library. It could perhaps be added as extension libraries (either official or not), and many will probably live outside the project at all (in independent projects). Of course problems when writing such a library can be valid bugs / missing features.

**Comment by sandwwraith** [comment]
Adding a lot of formats directly to the core is indeed *non-goal*. However, issues like this can be used to track community reaction on specific format (by voting up/down) and eventually someone who is willing to contribute can start from here.

Formats can be contributed to this repository (into [formats](../tree/master/formats) folder), but only if they're small and highly appreciated. For big integration with complex formats, consider creating separate library which you can maintain. I don't mind to create special "list of 3rd party format providers" so people could discover them from main page.
