### ISSUE TITLE
@Transient shows initializer error in data classes

### ISSUE THREAD

**Issue by Burtan** [Kotlin/kotlinx.serialization#1605]
**Describe the bug**
`error: This property is marked as @Transient and therefore must have an initializing expression`

Analog to github.com/Kotlin/kotlinx.serialization/issues/553

**To Reproduce**
@Serializable
data class Foo(@Transient val number: Int)

the variable would be initialized after construction

**Expected behavior**
No error

**Environment**
 - Kotlin version: 1.5.20
 - Kotlin platforms: JVM
 - Gradle version: 7.1

**Comment by sandwwraith** [comment]
This error is correct. Property marked as transient is excluded from deserialization too, so if it does not have an initializer, then it would be impossible to reconstruct it after e.g. decoding Foo class from Json

**Comment by Burtan** [comment]
Ah, yeah. I get it, sorry for the inconveniences!
