### ISSUE TITLE
JsonDecodingException with ignoreUnknownKeys

### ISSUE THREAD

**Issue by Angads25** [Kotlin/kotlinx.serialization#1606]
**Describe the bug**
I am using `KotlinxSerializer` with `Ktor` in `KMM Project`. While doing so, I am getting `JsonDecodingException` ([Stacktrace](https://singhangad.in/archives/Stacktrace.jpg)) for a key in JSON response I haven't added in the POJO. As mentioned in the docs I have set both `isLenient` and `ignoreUnknownKeys` flags, to resolve the issue but It doesn't seem to make any difference. You can check the snippet below to get an idea of how I am using the feature in my HttpClient

```kotlin
import kotlinx.serialization.json.Json as KotlinJson


install(JsonFeature) {
    serializer = KotlinxSerializer(
        KotlinJson {
            isLenient = true
            ignoreUnknownKeys = true
        }
    )
}
```

**To Reproduce**
You can check the implementation in this repo: https://github.com/Angads25/KMM-Ktor-Features
Although the code is not updated, the overall implementation hasn't changed.

**Environment**
 - Ktor Version: 1.6.1
 - Kotlin version: 1.5.10
 - Library version: 1.2.2
 - Kotlin platforms: KMM
 - Gradle version: 6.7.1
 - IDE version: Android Studio 4.2.2
 - OS Version: Big Sur, Version: 11.4
 - JDK Version: 11.0.6

Please feel free to ask for any other information not mentioned in the issue description.

**Comment by sandwwraith** [comment]
You're using a default instance instead of one you configured here: https://github.com/Angads25/KMM-Ktor-Features/blob/master/shared/src/commonMain/kotlin/com/github/angads25/kmmsampleapp/repository/NetworkUseCase.kt#L27
