### ISSUE TITLE
appendStringSlowPath JVM performance issue

### ISSUE THREAD

**Issue by mvanassche** [Kotlin/kotlinx.serialization#1610]
**Describe the bug**

When serializing an object containing a reasonably large string containing double quotes, the appendStringSlowPath will copy the char array as many times as the size of the large string.
I know that appendStringSlowPath says slow in its name, but that is beyond reasonable.
I believe the problem is that the ensureTotalCapacity is not taking into account the string.length. We know the result will be at least as large as string.length! There is no need to increase by one byte for every byte of the string.

**To Reproduce**

For example, try to serialize an object of:
```
@Serializable
class ContentAnswer(val id: String, val content: String)
```
with content being a string of a few Mb, containing a double quote at the beginning.

**Environment**
 - Kotlin version: 1.5.20
 - Library version: 1.2.1
 - Kotlin platforms: JVM

**Comment by sandwwraith** [comment]
#1491 . It's fixed in 1.2.2
