### ISSUE TITLE
[Question] Serialize Polymorphic & (Recursive) Class

### ISSUE THREAD

**Issue by wakaztahir** [Kotlin/kotlinx.serialization#1615]
I want to write a custom serializer for a class named `MapNode` which contains two lists of itself  and some other properties

````
   abstract class MapNode {
       var colorIndex : Int = 0
   
       var left = listOf<MapNode>()
       var right = listOf<MapNode>()
   }
````

There's TextNode which is extends MapNode
````
    class TextNode : MapNode{
        var text : String = ""
    }
````

**These properties are all delegated which is why I need to write a custom serializer for them as a workaround since delegated properties aren't being serialized default**

Should I write a serializer for TextNode and serialize and deserialize all the properties of MapNode in this serializer but if I do that then every time I write a class which extends MapNode , I would have to again serialize and deserialize MapNode properties 

I don't know how to get the MapNode serializer inside the serializer and serialize the list of itself

I came up with this code but its not complete and does not solve the problem , I would love some insights

````
object MapNodeSerializer : KSerializer<MapNode> {

    private val serializer = ListSerializer(this)

    @OptIn(
        ExperimentalSerializationApi::class,
        kotlinx.serialization.InternalSerializationApi::class
    )
    override val descriptor: SerialDescriptor = buildClassSerialDescriptor("MapNode") {
        element<Boolean>("is_group")
        element<Int>("color_index")
        element<List<MapNode>>("left")
        element<List<MapNode>>("right")
    }

    override fun deserialize(decoder: Decoder): MapNode {
        val node = TextNode() //how to get the subclass here
        decoder.decodeBoolean()
        decoder.decodeInt()
        
        //how to decode the left list and right list
        return node
    }

    override fun serialize(encoder: Encoder, value: MapNode) {
        encoder.encodeStructure(descriptor = descriptor) {
            encodeBooleanElement(descriptor = descriptor, 0, value.isGroup)
            encodeIntElement(descriptor = descriptor, 1, value.colorIndex)

            //How to encode the left list & right list
        }

    }

}
````

**Comment by Dominaezzz** [comment]
What do you want the JSON to look like? (Does it have to be specific or does it just need to work)

Are there any other subclasses of `MapNode`?

**Comment by wakaztahir** [comment]
It just needs to work , normal Json

MapNodeis an abstract class

TextNode and Central Node are it's subclasses , I can register them in serializers module
