### ISSUE TITLE
kotlinx.serialization performance vs gson

### ISSUE THREAD

**Issue by alizarei95** [Kotlin/kotlinx.serialization#1618]
Hello there

I'm using Gson for years but today I decided to switch to kotlinx.serialization. But in my tests kotlinx.serialization works more slower than gson. Here is my tests code and result, is there any problem in my codes?

data link : https://jsonplaceholder.typicode.com/posts

my code :
```
val gson: Gson = GsonBuilder().serializeNulls().create()

    val json = Json {
        encodeDefaults = true
        ignoreUnknownKeys = true
    }

    val t1 = measureTimeMillis {
        json.decodeFromString<List<Post>>(data)
    }

    val t2 = measureTimeMillis {
        gson.fromJson(data, object : TypeToken<List<Post>>() {}.type)
    }

    println("KTX finished in $t1 ms")
    println("GSON finished in $t2 ms")
```

result :
```
KTX finished in 190 ms
GSON finished in 72 ms
```

I have tested several times but every time result is near this one.
Any idea?

**Comment by qwwdfsad** [comment]
I cannot run it myself because `Post` class is not present in your data, but it seems like your benchmark encounters typical JVM measurement pitfalls: it measures class loading, garbage collection, not JIT-compiled code and so on. I suggest using a proven tool like JMH for such measurements.

Also, please ensure that you are not measuring serializer resolving (#1348), try to replace `son.decodeFromString<List<Post>>(data)` with `json.decodeFromString(ListSerializer(Post.serializer()), data)`

**Comment by alizarei95** [comment]
> I cannot run it myself because `Post` class is not present in your data, but it seems like your benchmark encounters typical JVM measurement pitfalls: it measures class loading, garbage collection, not JIT-compiled code and so on. I suggest using a proven tool like JMH for such measurements.
> 
> Also, please ensure that you are not measuring serializer resolving (#1348), try to replace `json.decodeFromString<List<Post>>(data)` with `json.decodeFromString(ListSerializer(Post.serializer()), data)`

Here is Post.kt
```
@Serializable
data class Post(
    val body: String,
    val id: Int,
    val title: String,
    val userId: Int
)
```

I changed my code to `json.decodeFromString(ListSerializer(Post.serializer()), data)` and now ktx speed is near to gson. But what is this method and why is quicker than first one? And when to use ?

**Comment by qwwdfsad** [comment]
If you do not have any particular performance acceptance criteria, I suggest using the one you find more preferable for you.

The former is the slower because it has to resolve the serializer by itself in the runtime (unless #1348 is implemented)
