### ISSUE TITLE
Registering custom Serializer for 3rd party class fails w/ Serializer for class is not found

### ISSUE THREAD

**Issue by efenderbosch** [Kotlin/kotlinx.serialization#1620]
**Describe the bug**
I'm trying to register a `Serializer` for `Instant` and basing it on the [docs](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#serializing-3rd-party-classes) for `DateAsLongSerializer`

**To Reproduce**
```kotlin
val rfc3339Formatter: DateTimeFormatter =
    DateTimeFormatterBuilder()
        .appendPattern("yyyy-MM-dd'T'HH:mm:ss")
        .optionalStart()
        .appendFraction(ChronoField.NANO_OF_SECOND, 0, 6, true)
        .optionalEnd()
        .appendPattern("xxx")
        .toFormatter()
        .withZone(ZoneOffset.UTC)

object InstantSerializer : KSerializer<Instant> {
    override fun deserialize(decoder: Decoder): Instant =
        decoder.decodeString().let { rfc3339Formatter.parse(it, Instant::from) }

    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("Instant", PrimitiveKind.STRING)

    override fun serialize(encoder: Encoder, value: Instant) {
        encoder.encodeString(rfc3339Formatter.format(value))
    }
}

@Serializable
data class Foo(val bar: UInt, @Contextual val timestamp: Instant)

val serializersModule = SerializersModule {
    contextual(Instant::class, InstantSerializer)
}

val customJson = Json {
    serializersModule = serializersModule
}

val foo = Foo(UInt.MAX_VALUE, Instant.now())
val json = customJson.encodeToString(foo)
println(json)
val deserialized = customJson.decodeFromString<Foo>(json)
println(deserialized == foo)
```
This throws `kotlinx.serialization.SerializationException: Serializer for class 'Instant' is not found.`

**Expected behavior**
`Instant` is serialized to a `String` using the custom `InstantSerializer`
If I add `@Serializable(with = InstantSerializer::class)` to the attribute, then it works, but I'd prefer to not have to sprinkle that all over the code.

**Environment**
 - Kotlin version: 1.5.20
 - Library version: 1.2.2
 - Kotlin platforms: JVM
 - Gradle version: 7.1

**Comment by efenderbosch** [comment]
If I create my custom `Json` like this:
```kotlin
val Json = Json {
    serializersModule = SerializersModule {
        contextual(Instant::class, InstantSerializer)
    }
}
```
It works.

Not sure if this should be left open because it seems like the original above should still work.

**Comment by efenderbosch** [comment]
Also, are there any plans to allow registration of custom serializers for 3rd-party classes via `@Serializer(forClass = Instant::class)`? If the compiler plugin can find the classes annotated w/ `@Serializable` why can't it from `@Serializer`?

**Comment by sandwwraith** [comment]
It seems that

```
val customJson = Json {
    serializersModule = serializersModule
}
```

assigns _property_ `serializersModule` to itself. Try renaming your `val serializersModule = SerializersModule { contextual(Instant::class, InstantSerializer)}` into something else

> Also, are there any plans to allow registration of custom serializers for 3rd-party classes via @Serializer(forClass = Instant::class)?

No, this mechanism should not affect global registration because there may be a lot of different serializers for one class
