### ISSUE TITLE
serializing issue with inner polymorphic class

### ISSUE THREAD

**Issue by liskov** [Kotlin/kotlinx.serialization#1628]
i didn't find an explanation why it happening, i saw similar issues: [145](https://github.com/Kotlin/kotlinx.serialization/issues/145), [127](https://github.com/Kotlin/kotlinx.serialization/issues/127)

Describe the bug
can't serialize container class when it have property that is polymorphic class. the exception:
Exception in thread "main" kotlinx.serialization.SerializationException: Class 'Man' is not registered for polymorphic serialization in the scope of 'Human'.
Mark the base class as 'sealed' or register the serializer explicitly.

it works if i register serializer explicitly, but why its not working automatically? Human class is already sealed class.
i also explicitly cast man instance into Human, but without luck.

To Reproduce:
```
@Serializable
data class Creator(
    val kind: Human,
)

@Polymorphic
@Serializable
sealed class Human {
    abstract val name: String
}

@SerialName("Man")
@Serializable
data class Man(
    override val name: String,
): Human()

@SerialName("Woman")
@Serializable
data class Woman(
    override val name: String,
): Human()

fun main() {
    val man = Man("richard")
    val creator = Creator(
        man,
    )
    val jsonElement = Json.encodeToJsonElement(creator) // I receive this exception
    // Exception in thread "main" kotlinx.serialization.SerializationException: Class 'Man' is not registered for polymorphic serialization in the scope of 'Human'.
    // Mark the base class as 'sealed' or register the serializer explicitly.
}
```

Expected behavior
It works

Environment

Kotlin version: 1.5.20
Library version: 1.2.2
Kotlin platforms: JVM IR
Gradle version: 7.1

**Comment by shanshin** [comment]
Hi!
To use auto-registered classes for a sealed class, remove the `@Polymorphic` annotation.
Currently, in this situation, the serialization plugin mistakenly uses the `PolymorphicSerializer` serializer instead of `SealedClassSerializer` for `Creator.kind` property.

**Comment by liskov** [comment]
Thank you, it worked

**Comment by sandwwraith** [comment]
I think it's not a bug – `@Polymorphic` has a higher priority than a default serializer. But we may need inspection that says '@Polymorphic on sealed class is a bad idea'

**Comment by shanshin** [comment]
> @Polymorphic has a higher priority than a default serializer.

In this case, the documentation must be changed, because it says `Does not affect sealed classes, because they are gonna be serialized with subclasses automatically`.

**Comment by mihai1voicescu** [comment]
I agree with @shanshin, the documentation is very misleading and you waste a lot of time because you can't easily debug 😢. 

Maybe it would also be a good idea to add a warning in the `@Polymorphic` documentation until this issue is sorted.
