### ISSUE TITLE
How to serialize type is not fixed json value?

### ISSUE THREAD

**Issue by xiao-cao-x** [Kotlin/kotlinx.serialization#1632]
**What is your use-case and why do you need this feature?**

Serialization The type returned from the PHP side is not a fixed json value.

**Describe the solution you'd like**
```kotlin
@Serializable
data class CoverImage(
    @SerialName("profile_cover_ext")
    val profileCoverExt: String,

    @SerialName("profile_cover_image")
    val profileCoverImage: Map<String, String>,
)
```

```kotlin
@SerialName("cover_image")
val coverImage: CoverImage? = null,
```

There is a field which may be `CoverImage ` type or `Boolean ` type (only `false`),
I need to parse it when the type is `CoverImage` , otherwise it is set to `null`.
Does kotlinx.serialization support this function, and if so, how to write the code?

---

From Google Translate

**Comment by sandwwraith** [comment]
There's no built-in mechanism for this, but you can write a custom `KSerializer<CoverImage?>` that will return `null` on unacceptable values. It can be done, for example, using json transforming serializers: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#json-transformations

**Comment by xiao-cao-x** [comment]
> There's no built-in mechanism for this, but you can write a custom `KSerializer<CoverImage?>` that will return `null` on unacceptable values. It can be done, for example, using json transforming serializers: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#json-transformations

Hello, after I wrote a`KSerializer<CoverImage?>`, the following error occurred.
```
Exception in thread "main" kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 1236: Expected start of the object '{', but had ' ' instead
JSON input: ....."follows": 65,
      "social": [],
      "user_comment_html".....
```
---
This is the json data of CoverImage.
```json
{
  "cover_image": {
    "profile_cover_ext": "jpg",
    "profile_cover_image": {
      "720x360": "url"
    }
  }
}
```
```json
{
  "cover_image": false
}
```
---
This is my code, can you help me see it? 
```kotlin
object CoverImageCustomSerializer : KSerializer<CoverImage?> {
    override fun deserialize(decoder: Decoder): CoverImage? {
        require(decoder is JsonDecoder)

        return try {
            val json = decoder.decodeJsonElement().jsonObject

            CoverImage(
                profileCoverExt = json.getValue("profile_cover_ext").jsonPrimitive.content,
                profileCoverImage = json.getValue("profile_cover_image")
                    .jsonObject.toMap().map {
                        Pair(it.key, it.value.jsonPrimitive.content)
                    }.toMap()
            )
        } catch (e: Exception) {
            null
        }

    }

    override val descriptor: SerialDescriptor = buildClassSerialDescriptor("cover_image") {
        element<String>("profile_cover_ext")
        element<Map<String, String>>("profile_cover_image")
    }

    override fun serialize(encoder: Encoder, value: CoverImage?) {

        require(encoder is JsonEncoder)
        val element = encoder.json.encodeToJsonElement(value)
        encoder.encodeJsonElement(element)
    }

}

@Serializable(with = CoverImageCustomSerializer::class)
data class CoverImage(
    val profileCoverExt: String,
    val profileCoverImage: Map<String, String>,
)
```
thank.

**Comment by sandwwraith** [comment]
Your serializer looks fine, so I'm not sure where this error came from. The only thing I would change is replace `try/catch` with a simpler `is JsonObject` check to make sure that exception from `decodeJsonElement` (from a malformed json) wouldn't be swallowed.

Is 'JSON token at offset 1236' a start point for CoverImage object? Does this exception stacktrace starts from custom serializer or somewhere else?

**Comment by xiao-cao-x** [comment]
> 您的序列化程序看起来不错，所以我不确定这个错误来自哪里。我唯一要改变的是`try/catch`用更简单的`is JsonObject`检查替换，以确保`decodeJsonElement`不会吞下（来自格式错误的 json）的异常。
> 
> “偏移 1236 处的 JSON 令牌”是 CoverImage 对象的起点吗？此异常堆栈跟踪是从自定义序列化程序还是其他地方开始？

custom serializer

**Comment by xiao-cao-x** [comment]
> 您的序列化程序看起来不错，所以我不确定这个错误来自哪里。我唯一要改变的的英文`try/catch`用更简单的`is JsonObject`检查替换，以确保`decodeJsonElement`不会吞下（来自格式错误的JSON）的异常。
> 
> “偏移1236处的JSON令牌”是CoverImage的起点吗？此化序列对象追踪是从自定义其他地方开始？

Can you test it by running the code?

**Comment by xiao-cao-x** [comment]
> Your serializer looks fine, so I'm not sure where this error came from. The only thing I would change is replace `try/catch` with a simpler `is JsonObject` check to make sure that exception from `decodeJsonElement` (from a malformed json) wouldn't be swallowed.
> 
> Is 'JSON token at offset 1236' a start point for CoverImage object? Does this exception stacktrace starts from custom serializer or somewhere else?

When I try to "encode" or "decode", "override fun serialize" and "override fun deserialize" have not been executed before an exception occurs
