### ISSUE TITLE
Provide ByteArrayAsBase64StringSerializer

### ISSUE THREAD

**Issue by sandwwraith** [Kotlin/kotlinx.serialization#1633]
See the https://github.com/Kotlin/kotlinx.serialization/issues/1533 for context

**Comment by cy6erGn0m** [comment]
@sandwwraith Where do you recommend to mention it in the docs?

**Comment by sandwwraith** [comment]
`LongAsStringSerializer` is mentioned in builtin classes (https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/builtin-classes.md#long-numbers-as-strings), although I think better place for base64 serializer is somewhere at the end of JSON settings

**Comment by GeorgePap-719** [comment]
Hey @sandwwraith, is this still up for grabs?

**Comment by sandwwraith** [comment]
@GeorgePap-719 I believe so, as the previous attempt (#1676) wasn't finished.
