### ISSUE TITLE
Add iosSimulatorArm64 target

### ISSUE THREAD

**Issue by hfhbd** [Kotlin/kotlinx.serialization#1647]
**What is your use-case and why do you need this feature?**
I want to use the new `iosSimulatorArm64` target from Kotlin 1.5.30.

**Describe the solution you'd like**
Add the target to `build.gradle.kts`and publish it.
https://kotlinlang.org/docs/mpp-share-on-platforms.html#target-shortcuts-and-arm64-apple-silicon-simulators

**Comment by leocabral** [comment]
@sandwwraith any update on this? 🙏

**Comment by sandwwraith** [comment]
@leocabral We're planning next release with these targets

**Comment by AshStefanOltmann** [comment]
Also supports `macosArm64`, `watchosSimulatorArm64` and `tvosSimulatorArm64`
