### ISSUE TITLE
Disable class discriminator with polymorphism

### ISSUE THREAD

**Issue by ribafish** [Kotlin/kotlinx.serialization#1652]
**What is your use-case and why do you need this feature?**

We are generating signatures/hashes from an interface, which is implemented by a few classes. The signature is sent to the BE, which rejects it, as it doesn't match what is saved, because of the additional `type` fields. This happens in a bunch of places, with nested polymorphic classes, so it would be nice to be able to use the default polymorphic serializer to encode it to string, but not add the `type` field.

**Describe the solution you'd like**

A solution would be to either add it as a json config 
```
Json {
    generateClassDiscriminator = true
}
```
which is set to `true` by default, or add an annotation to disable it, eg. `@DisableClassDiscriminator`.

**Comment by shanshin** [comment]
Duplicates #1247

**Comment by ribafish** [comment]
Duplicates #1247 🤦
