### ISSUE TITLE
From Json Number 1.0 to Kotlin Int

### ISSUE THREAD

**Issue by SilenLoc** [Kotlin/kotlinx.serialization#1653]
**Describe the bug**
I assume the prerequesite of the json number format 

> JSON can represent four primitive types (strings, numbers, booleans,
   and null) and two structured types (objects and arrays).

Now Java / Kotlin has Integers, 
when deserializing from {"x": 1.0} to x: Int 
The expected behavior for me would be that kotlinx would accept 1.0 in json for an integer but:

Unexpected JSON token at offset 6: Unexpected symbol '.' in numeric literal
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 6: Unexpected symbol '.' in numeric literal
JSON input: {"x": 1.0}

**To Reproduce**
run:
`
@Serializable
data class Data (val x: Int )

val json = """{"x": 1.0}"""
val jsonDeserializer = Json {}
val data: Data = jsonDeserializer.decodeFromString(json)    
  `

**Expected behavior**
kotlinx (json) would accept 1.0 for Integers (obv. not for 1.2 / 1.7 etc.)

**Environment**
 - Kotlin version: [1.5.30]
 - Library version: [1.2.2]
 - Kotlin platforms: [JVM]
 - Gradle version: [e.g. 4.10]

Is this a bug, wrongly configurated from me or intentional and I have to cast after deserialization? (I found nothing in the doc about this)

**Comment by sandwwraith** [comment]
Since JSON specification in this place is vague and JSON per se does not differentiate integer/fractional types, I'd say this behavior is implementation-defined and coincidental. We should take a look at other libraries and decide whether we want to support it

**Comment by SilenLoc** [comment]
> Since JSON specification in this place is vague and JSON per se does not differentiate integer/fractional types, I'd say this behavior is implementation-defined and coincidental. We should take a look at other libraries and decide whether we want to support it

What about a configurable

Mainly because: 

Libraries like Gson allow it without specifying anything, which also is not what I would expect. So when we would build an application that uses out and in going Json with Gson we could have both in the Json, 1.0 and 1 and not notice. 

Then when we would use the Json in another application with Kotlinx the serialization would fail even though it would hold the type contract from a language point of view. 

I think Kotlinx should not consider to just accept it but to make it possible in a easy way, especially because of cross platform functionality (JavaScript - Kotlin). Writing a custom serializer works but you have to encounter this behavior and then work around it, instead of making a "simple" configuration that is more consistent.

I hope this helps, thank you

**Comment by xiaobailong24** [comment]
Same problem with me

**Comment by FrancisDx** [comment]
> Do we also have to change the Kotlin language? Because `val count: Int = 1.0` does not compile.
> 
> If your desire is to accept all numbers representable in the JSON format then you should be using `Double` because that is the type that mirrors the semantics. Accepting clearly floating-point numbers as integers is fraught with all kinds of gotchas. For example, is 1.000000000000000000001 a double or an int?
> 
> ```kotlin
> fun main() {
>   val one1 = "1.000000000000000000001".toDouble()
>   val one2 = "1.0".toDouble()
>   println(one1 == one2)
> }
> ```
> 
> Strong +1 to keeping the current behavior.

It's about JSON decoding. Kotlin semantics cannot be applied to the JSON format. 1 and 1.0 are the same in JSON (unlike Kotlin).

**Comment by optimuspaul** [comment]
Strong -10000000 to keeping the current behavior. This is absurd. I can't control how others format their JSON. I certainly can't control how a database decides to encode the JSON. I think you made the wrong decision here.

**Comment by pdvrieze** [comment]
> Strong -10000000 to keeping the current behavior. This is absurd. I can't control how others format their JSON. I certainly can't control how a database decides to encode the JSON. I think you made the wrong decision here.

This is where custom serializers come in. Nothing stops you from creating a `LenientIntSerializer` that uses raw value access. Using a type alias, you just create one for your lenient ints and everything works.
