### ISSUE TITLE
Double with default value zero will be serialized if value is minus zero even though encodeDefaults is disabled

### ISSUE THREAD

**Issue by TorRanfelt** [Kotlin/kotlinx.serialization#1655]
**Describe the bug**
When encodeDefaults is disabled (which is the default) a default variable can still be serialized if the variable is a Double and the default value is zero. It happens if the variable is set to minus zero.

Kotlin consider 0.0 and -0.0 equal, so I would expect it to be the case here too.

**Environment**
 - Kotlin version: 1.5.21
 - Library version: 1.1.0 // Can't upgrade to 1.2.2 (https://github.com/Kotlin/kotlinx.serialization/issues/1577) but an issue search didn't turn up anything relevant.
 - Kotlin platforms: JS
 - Gradle version: 7.1

**Comment by sandwwraith** [comment]
Is it JS or JS IR?

**Comment by TorRanfelt** [comment]
IR has not been enabled.

**Comment by sandwwraith** [comment]
Then I assume it just calls incorrect equals function in generated code (`==` or `===` directly)
