### ISSUE TITLE
Serializer for class 'AtomicLong' is not found.

### ISSUE THREAD

**Issue by nkbai** [Kotlin/kotlinx.serialization#1659]
**What is your use-case and why do you need this feature?**
support Atomic*
**Describe the solution you'd like**
Support  all the type of in java standard library

**Comment by sandwwraith** [comment]
Currently, we do not have plans to support any Java-specific classes out of the box, like Dates or BigIntegers, as serializers for them can relatively easily be written by hand. In future, we can provide a separate module for Java classes, but whether to do this is an open question.
