### ISSUE TITLE
Different behaviour of decodeFromString on iOS simulator and physical iOS device

### ISSUE THREAD

**Issue by belousovgm** [Kotlin/kotlinx.serialization#1666]
Bug description:
This code:
`val responseJson = json.decodeFromString<JsonObject>(response)`
works on physical device, but on simulator it raises following seralization exception:
`Field 'name' is required, but it was missing`.

But this variant works on both simulator and physical device:
`val responseJson = json.decodeFromString(JsonObject.serializer(), response)`

**To Reproduce**
Run this code on iOS simulator:
`val responseJson = json.decodeFromString<JsonObject>(response)`

**Expected behavior**
running without exception

**Environment**
 - Kotlin version: 1.4.31
 - Library version: 1.1.0
 - Kotlin platforms: Native
 - Gradle version: 6.9
 - Other relevant context: iOS 14.6

**Comment by sandwwraith** [comment]
Are you using `kotlinx.serialization.json.JsonObject` or your own class?

**Comment by belousovgm** [comment]
I use `kotlinx.serialization.json.JsonObject`

**Comment by sandwwraith** [comment]
I was unable to reproduce the issue using Kotlin 2.x and serialization 1.7.3. If you still have it, please re-open the issue
