### ISSUE TITLE
Kotlin 1.5.30: Leaking @ExperimentalSerializationApi in stable APIs

### ISSUE THREAD

**Issue by BenWoodworth** [Kotlin/kotlinx.serialization#1668]
**Describe the bug**
Some stable APIs are being reported as experimental.

**To Reproduce**
```kotlin
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json

Json.encodeToString(Int.serializer(), 0) // No warnings

Json.encodeToString(0)
//   ^^^^^^^^^^^^^^ 
//   This declaration is experimental and its usage should be marked with
//   '@kotlinx.serialization.ExperimentalSerializationApi' or
//   '@OptIn(kotlinx.serialization.ExperimentalSerializationApi::class)'
```

**Expected behavior**
No opt-in warnings on stable APIs

**Environment**
 - Kotlin version: 1.5.30
 - Library version: 1.2.2, 1.3.0-RC
 - Kotlin platforms: JVM (probably others)
 - Gradle version: 6.8

**Comment by sandwwraith** [comment]
It looks like this is happens after changes to `OptIn` in 1.5.30 :

> In Kotlin 1.5.30, the compiler treats any declaration that has an experimental type in the signature as experimental. Namely, it requires opt-in even for implicit usages of an experimental API. For example, if the function’s return type is marked as an experimental API element, a usage of the function requires you to opt-in even if the declaration is not marked as requiring an opt-in explicitly.

https://kotlinlang.org/docs/whatsnew1530.html#requiring-opt-in-on-implicit-usages-of-experimental-apis
https://github.com/Kotlin/KEEP/blob/d7287626dd4c40c6c89877e266044b83fca38bcd/proposals/opt-in.md#optin-marker-contagiousness

cc @qwwdfsad looks like we need to remove `@ExpreimentalSerializationApi` from SerialFormat

**Comment by fcurts** [comment]
I'm also getting this with kotlinx-serialization 1.2.2 (after updating to Kotlin 1.5.30).
