### ISSUE TITLE
Convert Int to Boolean with custom serializer

### ISSUE THREAD

**Issue by xdma** [Kotlin/kotlinx.serialization#167]
Hi, I've already spent a lot of time trying to write custom serializer, to replace Int (TINYINT from mysql) to Boolean.

Using **Gson** I do it without problems, something like this (java):
` public class BooleanSerializer implements JsonSerializer<Boolean>, JsonDeserializer<Boolean> {

        @Override
        public JsonElement serialize(Boolean arg0, Type arg1, JsonSerializationContext arg2) {
            return new JsonPrimitive(arg0 ? 1 : 0);
        }

        @Override
        public Boolean deserialize(JsonElement arg0, Type arg1, JsonDeserializationContext arg2) throws JsonParseException {
            return arg0.getAsInt() == 1;
        }
    }

GsonBuilder().registerTypeAdapter(Boolean.class, serializer)
`

Is it possible to achieve the same result here and how?
Thank you.

**Comment by Skeptick** [comment]
As I understand it, this is not possible at the moment. I use for this:
```kotlin
@Serializable
data class BooleanInt internal constructor(val value: Boolean) {

    @Serializer(forClass = BooleanInt::class)
    companion object : KSerializer<BooleanInt> {
        override fun save(output: KOutput, obj: BooleanInt) =
            output.writeIntValue(if (obj.value) 1 else 0)

        override fun load(input: KInput): BooleanInt =
            BooleanInt(input.readNullable(IntSerializer) == 1)
    }
}
```
And:
```kotlin
@Serializable
data class Example(
    @SerialName("my_bool") val myBool: BooleanInt
)
```

**Comment by xdma** [comment]
Yes, I did the same, but it's not very convenient

**Comment by sandwwraith** [comment]
Or you can use `@Serializable(with=...)` on boolean properties which you need to convert with custom serializer.

Currently, indeed, there is no option to override default serializers globally.

**Comment by pdvrieze** [comment]
Given the way the serialization code is generated by the plugin overriding the only straightforward way is to have a delegating writer and reader where the boolean option is redirected.

**Comment by qwwdfsad** [comment]
@xdma 
Even though globally one can't override `Boolean` serializer, it's possible to achieve locally.
For your custom serialization format, it's possible to write custom `KSerializer`, which can hook into `writeBooleanElementValue` and `readBooleanElementValue`.

If you need such feature in JSON (do you?), we can provide different implementation/builder which allows to hookup into specific serialization points by `::class` or `KSerialClassDesc`

**Comment by xdma** [comment]
@qwwdfsad 

Thanks, I already solved the problem, as @Skeptick advised, it's less convenient, but it works and I don't want to go back to that part of project now  :)

**Comment by sandwwraith** [comment]
You can now also use `@file:UseSerializers` to override default serializers on a per-file basis.
