### ISSUE TITLE
Copyright didn't get updated after 2019.

### ISSUE THREAD

**Issue by Pradumnasaraf** [Kotlin/kotlinx.serialization#1674]
**Problem**
Copyright didn't get updated after 2019.

Should I update this to 2021?

![Screenshot 2021-09-14 193843](https://user-images.githubusercontent.com/51878265/133273182-6ebc4632-dd8b-4e4d-9528-01f90f75f096.png)

**Comment by sandwwraith** [comment]
What file it is? Looks like it should be reported to kotlinx.coroutines. cc @qwwdfsad

**Comment by Pradumnasaraf** [comment]
kotlinx.serialization/license/NOTICE.txt

**Comment by sandwwraith** [comment]
Indeed, we may need to update it (and license/LICENSE.txt too)

**Comment by Pradumnasaraf** [comment]
Anyway I can contribute to it?

**Comment by Pradumnasaraf** [comment]
> Indeed, we may need to update it (and license/LICENSE.txt too)

Anyway I can contribute to it? @sandwwraith

**Comment by sandwwraith** [comment]
yeah why not

**Comment by Pradumnasaraf** [comment]
how? by changing the year to 2021?
