### ISSUE TITLE
SerializersModule.polymorphic doesn't work for Kotlin Native (ios)

### ISSUE THREAD

**Issue by krottv** [Kotlin/kotlinx.serialization#1679]
**Describe the bug**

SerializersModule.polymorphic doesn't work for Kotlin Native (ios)

```
 serializersModule = SerializersModule {
            polymorphic(AnimApplier::class) {
                subclass(ScaleOuterAnimApplier::class)
                subclass(FadeAnimApplier::class)
}
```

After I get
```
Uncaught Kotlin exception: kotlinx.serialization.json.internal.JsonDecodingException: Polymorphic serializer was not found for class discriminator 'fade'
JSON input: {"type":"fade","from":1,"to":0}
```

**To Reproduce**
```
abstract class AnimApplier

@Serializable
@SerialName("fade")
class FadeAnimApplier(var from: Float = 0f, var to: Float = 1f) : AnimApplier()

@Serializable
@SerialName("scale")
class ScaleOuterAnimApplier(var fromX: Float = 1f, var toX: Float = 1f, var fromY: Float = 1f, var toY: Float = 1f)

class SomeContainer(val animApplier: AnimApplier)
// this crashes the app
val someContainer: SomeContainer = json.decodeFromString("""
{
    "animApplier": {"type":"fade","from":1,"to":0}
}
""")

```

**Environment**
 - Kotlin version: 1.5.30
 - Library version: 1.3.0-RC
 - Kotlin platforms: Native - ios

**Comment by sandwwraith** [comment]
I don't get the example. Have you specified `@SerialName("fade")` on one of the subclasses?

**Comment by krottv** [comment]
@sandwwraith I have updated the code.

**Comment by sandwwraith** [comment]
You created json with `Json { serializersModule = myModule }`, right? (Pay attention to it, because if your module named `serializersModule` too, it will be ignored unfortunately... `Json { serializersModule = serializersModule }` will reassign builder var to itself.)

And this code works on JVM correctly, error happens only on Native?

**Comment by krottv** [comment]
@sandwwraith It was my issue. I accidentally used different instance of json for ios target.
