### ISSUE TITLE
The suggested name 'from' for property fromY is already one of the names for property fromX in scale(fromX: kotlin.Float, toX: kotlin.Float, fromY: kotlin.Float, toY: kotlin.Float)

### ISSUE THREAD

**Issue by krottv** [Kotlin/kotlinx.serialization#1681]
**What is your use-case and why do you need this feature?**

I have the following class:

```
@SerialName("scale")
@Serializable
class ScaleOuterAnimApplier @OptIn(ExperimentalSerializationApi::class) constructor(
    @JsonNames("from", "fromX") var fromX: Float = 1f,
    @JsonNames("to", "toX") var toX: Float = 1f,
    @JsonNames("from", "fromY") var fromY: Float = 1f,
    @JsonNames("to", "toY") var toY: Float = 1f
)
```
The idea behind is to deserialize this json:
```
{
   "type": "scale",
   "from": 1,
    "to": 1.25
}
```

**Comment by sandwwraith** [comment]
So you want `"from": 1` to be deserialized to both `fromX` and `fromY`?

**Comment by krottv** [comment]
@sandwwraith Yes, exactly. It is more compact to write from: 0, to: 1, then to specify each property.

**Comment by sandwwraith** [comment]
You can use JSON transformations (https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#json-transformations) to copy `from` property to a pair of `fromX`, `fromY`. I don't think it is a good idea in general to allow one-to-many mapping during JSON parsing.
