### ISSUE TITLE
Custom serializer for a generic class doesn't turn off missing serializer compiler error for the generic type

### ISSUE THREAD

**Issue by gohlinka2** [Kotlin/kotlinx.serialization#1682]
**Describe the bug**

When a custom serializer for a `List<A>` (or any other generic class, not just `List`) is provided using `@Serializable` annotation on a property, the compiler shows an error for `A`: `Serializer has not been found for type 'Child'. To use context serializer as fallback, explicitly annotate type or property with @Contextual`. However, this error shouldn't be shown, as the whole property is serialized using the given serializer.

Note: this does work correctly for non-generic classes.

**To Reproduce**
```kotlin
@Serializable
data class Parent(
    @Serializable(with = ChildListSerializer::class)
    val children: List<Child> // Serializer has not been found for type 'Child'
)

data class Child(val name: String)

object ChildListSerializer: KSerializer<List<Child>> {...}
```
**Expected behavior**

The error should not be there.

**Environment**
 - Kotlin version: 1.5.30
 - Library version: 1.2.2
 - Kotlin platforms: JVM, Native
 - Gradle version: 7.2
 - IDE version: Android Studio Arctic Fox | 2020.3.1 Patch 1

**Comment by sandwwraith** [comment]
Seems to be fixed in 2.0.20
