### ISSUE TITLE
Unexpected 'null' value instead of string literal

### ISSUE THREAD

**Issue by graycatdeveloper** [Kotlin/kotlinx.serialization#1683]
If there is such a field in json
```
{
  "name": "null"
}
```
for such a model
```
data class Model(
  val name: String
)
```
then an error occurs
```
Unexpected JSON token at offset ...: Unexpected 'null' value instead of string literal "name": "null"
```

 - Kotlin version: 1.5.30
 - Library version: 1.2.2
 - Kotlin platforms: JVM
 - Gradle version: 7.2
 - IDE version: IntellijIDEA latest

**Comment by sandwwraith** [comment]
Try 1.3.0-RC, error should be fixed there (#1637)
