### ISSUE TITLE
Support for @Transient properties initialized in subtype call to super constructor

### ISSUE THREAD

**Issue by Whathecode** [Kotlin/kotlinx.serialization#1689]
**What is your use-case and why do you need this feature?**

The following is an example of the use case I am interested in:

```
@Serializable
abstract class Base( @Transient val needsValidation: String )
{
    init { require( needsValidation != "Invalid" ) }
}

@Serializable
class Valid : Base( "This is okay" )

@Serializable
class Invalid : Base( "Invalid" )
```

The `Base` class needs to validate constructor arguments passed from extending classes. This constraint checking logic is common to all extending classes, and ideally can thus be defined in `Base` and run at initialization.

However, these are constant compile-time values and I am therefore not interested in serializing these. Thus, I try to apply the `@Transient` attribute. But, as expected, this leads to the error:

> This property is marked as `@Transient` and therefore must have an initializing expression.

Neither of the current "solutions" fulfill my real requirement:

- Removing `@Transient` still serializes `needsValidation`.
- Adding a default initializer (e.g. `needsValidation: String = ""`) causes deserialized concrete types to have `needsValidation` set to the default value, not the one specified in the constructor of the deriving type.

**Describe the solution you'd like**

Something similar to the original code provided, but I expect due to the way serialization is implemented this may likely not be possible. Just thought I would ask what the recommendation is here.

The only option I see now is having a separate `validate` call in the abstract base class which is called after initialization, and make `needsValidation` an abstract property which is overridden in extending classes.

**Comment by sandwwraith** [comment]
The deserialization process does not invoke usual primary constructors of the serializable classes, it uses special generated ones. Therefore, the plugin needs to know what value to initialize `val needsValidation` with. Extracting values from primary constructor super call theoretically possible, but can be problematic due to a lot of nuances. 

I can suggest you the following trick: 

```kotlin
@Serializable
abstract class Base private constructor( @Transient val needsValidation: String = "" )
{
    constructor(needsValidation): this(needsValidation)
    init { require( needsValidation != "Invalid" ) }
}
```

I think it may work in your case, but I haven't tested it.

**Comment by Whathecode** [comment]
@sandwwraith That doesn't work due to conflicting overloads; the private and public constructor take the same parameters.

**Comment by sandwwraith** [comment]
Just add some `Unit` or `Nothing?` parameter

**Comment by Whathecode** [comment]
@sandwwraith Tried it, but it has the same result as what I tried before:

> Adding a default initializer (e.g. needsValidation: String = "") causes deserialized concrete types to have needsValidation set to the default value, not the one specified in the constructor of the deriving type.
