### ISSUE TITLE
Problems are reported as Compiler Internal Errors at compile time

### ISSUE THREAD

**Issue by shafirov** [Kotlin/kotlinx.serialization#17]
e: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Optional field failure in primary constructor of serializable class Packet must have default value
File being compiled and position: (13,71) in /Users/max/Projects/circlet/client-api/src/main/kotlin/circlet/client/api/transport/Packet.kt
PsiElement: @Optional val failure: FailureInfo?

**Comment by elizarov** [comment]
Yes. We should do frontend diagnostics.

**Comment by sandwwraith** [comment]
Collected use-cases and similar issues in #37
