### ISSUE TITLE
Unable to serialize generic class

### ISSUE THREAD

**Issue by ebhsgit** [Kotlin/kotlinx.serialization#1700]
**Describe the bug**

I have a class that holds generic content. Both the holder class and content class have been marked as serializable.

When serializing to Json, get the following exception:

```
java.lang.IllegalStateException: Only KClass supported as classifier, got T
        at kotlinx.serialization.internal.Platform_commonKt.kclass(Platform.common.kt:102)
        at kotlinx.serialization.SerializersKt__SerializersKt.serializerByKTypeImpl$SerializersKt__SerializersKt(Serializers.kt:78)
        at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt:59)
        at kotlinx.serialization.SerializersKt.serializer(Unknown Source:1)
        at kotlinx.serialization.SerializersKt__SerializersKt.builtinSerializer$SerializersKt__SerializersKt(Serializers.kt:96)
        at kotlinx.serialization.SerializersKt__SerializersKt.serializerByKTypeImpl$SerializersKt__SerializersKt(Serializers.kt:84)
        at kotlinx.serialization.SerializersKt__SerializersKt.serializer(Serializers.kt:59)
        at kotlinx.serialization.SerializersKt.serializer(Unknown Source:1)
```

**To Reproduce**

```
@Serializable
class ContentHolder<T>(
    val description: String,
    val timestamp: Long,
    val contents: T,
) {
    fun toJsonString() = Json.encodeToString(this)
}

@Serializable
class Content1(
    val long: Long,
    val str: String,
)

@Serializable
class Content2(
    val str1: String,
    val str2: String,
)
```

```
val contentHolder = ContentHolder(
                "abc",
                System.currentTimeMillis(),
                Content1(
                    123,
                    "some stuff",
                )
            )
val json = contentHolder.toJsonString()
```
**Expected behavior**
Get the json string

**Environment**
 - Kotlin version: 1.5.30
 - Library version: 1.2.2
 - Kotlin platforms: JVM (Android)
 - Gradle version: 7.0.2
 - IDE version: Android Studio 2020.3.1 Patch 2

**Comment by slavonnet** [comment]
System known T as Serializable and Serializable after compile time. Serializes created before compile. In theory replace it with

```
@Serializable
class ContentHolder<T>(
    val description: String,
    val timestamp: Long,
    val contents: T,
) {
    fun toJsonString() = Json.encodeToString(this)
}


@Serializable
sealed MyS()

@Serializable
class Content1: MyS(
    val long: Long,
    val str: String,
)

@Serializable
class Content2 : MyS(
    val str1: String,
    val str2: String,
)
```

Define T as Content1 or Content2  and compiler can;t do cast

**Comment by ebhsgit** [comment]
@slavonnet 

Thanks for the suggestion. But it still has same exception.

```
@Serializable
class ContentHolder<T: MyS>(
    val description: String,
    val timestamp: Long,
    val contents: T,
) {
    fun toJsonString() = Json.encodeToString(this)
}

@Serializable
sealed class MyS {}

@Serializable
class Content1(
    val long: Long,
    val str: String,
): MyS()

@Serializable
class Content2(
    val str1: String,
    val str2: String,
): MyS()
```

**Comment by sandwwraith** [comment]
Problem arises from the fact that `Json.encodeToString(this)` is equals to `Json.encodeToString<Content<T>>(this)`, where T is unknown (and equals to Any on runtime, which you do not really want). To overcome this problem, you need specify type parameters explicitly. 

For example, your last comment's code can be rewritten as 

 ```kotlin
 @Serializable
class ContentHolder<T: MyS>(
    val description: String,
    val timestamp: Long,
    val contents: T,
) {
    fun toJsonString() = Json.encodeToString<Content<MyS>>(this)
}
```

or even 

```kotlin
@Serializable
class ContentHolder(
    val description: String,
    val timestamp: Long,
    val contents: MyS,
) {
    fun toJsonString() = Json.encodeToString(this) // no T, no need to specify type param
}
```

**Comment by ebhsgit** [comment]
@sandwwraith 

Thanks for the reply.

I can confirm, the below works.

```
@Serializable
class ContentHolder(
    val description: String,
    val timestamp: Long,
    val contents: MyS,
) {
    fun toJsonString() = Json.encodeToString(this) // no T, no need to specify type param
}
```

The other version with `class ContentHolder<T: MyS>` does not compile.
This line `fun toJsonString() = Json.encodeToString<ContentHolder<MyS>>(this)` has the following error
>Type mismatch: inferred type is ContentHolder<T> but ContentHolder<MyS> was expected

----

For my project, it using `sealed class` is not ideal, as it would require all "content" types to be defined in the same package

Currently, the "content" types/classes are defined in different parts of the projects under different package/namespaces. Each package represents a grouping of domain function.

The `toJsonString()` is part of an interface, so changing that signature to pass in a `KSerializer` is also not an option.

Is there any other solutions?

**Comment by ebhsgit** [comment]
Thanks to @sandwwraith and @slavonnet 
I can answer my own question.

The problem is due to type erasure

The general solution would be to use `inline reified`. So below extension function would work

```
inline fun <reified T> ContentHolder<T>.toJsonString(): String = Json.encodeToString(this)
```

However, for my case, I can not use `reified` keyword, due to other project constraints.

The solution is to use serialization polymorphism. 
https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md

`sealed class` is the simplest, but due to other project constraint, I can't use it.

I ended up using open polymorphism
Below is a gist of the solution

```
@Serializable
class ContentHolder(
    val description: String,
    val timestamp: Long,
    val contents: MyS,
) {
    companion object {
        private val module = SerializersModule {
            polymorphic(MyS::class) {
                subclass(Content1::class)
                subclass(Content2::class)
            }
        }

        private val json = Json { serializersModule = module }
    }

    fun toJsonString(): String {
        return json.encodeToString(this)
    }
}

interface MyS

@Serializable
@SerialName("content1")
class Content1(
    val long: Long,
    val str: String,
) : MyS

@Serializable
@SerialName("content2")
class Content2(
    val str1: String,
    val str2: String,
) : MyS
```

----

Note:
The solution is not ideal, because if a developer forgets to register the child class to the SerializersModule, then a runtime exception is thrown.

> Assume there is a class Content3
> Class 'Content3' is not registered for polymorphic serialization in the scope of 'MyS'
