### ISSUE TITLE
Gradle install fails

### ISSUE THREAD

**Issue by Earthcomputer** [Kotlin/kotlinx.serialization#1704]
**Describe the bug**
I am trying to publish a local version of kotlinx.serialization using `./gradlew build install`, but it is failing with the following error:
```
* What went wrong:
Execution failed for task ':kotlinx-serialization-core:install'.
> Could not publish configuration 'archives'
   > A POM cannot have multiple artifacts with the same type and classifier. Already have MavenArtifact kotlinx-serialization-core:klib:klib:null, trying to add MavenArtifact kotlinx-serialization-core:klib:klib:null.
```
Nothing I have tried could get it to build. Is there something I'm doing wrong, or is it something with the buildscript?

**To Reproduce**
Clone a fresh copy of this repo and run `./gradlew build install`.

**Expected behavior**
Build successful.

**Environment**
 - Kotlin version: 1.5.31
 - Library version: Latest dev branch
 - Kotlin platforms: Building all of them
 - Gradle version: 6.9.1
 - IDE version (if bug is related to the IDE) [e.g. IntellijIDEA 2019.1, Android Studio 3.4]
 - Other relevant context: Ubuntu 20.04, OpenJDK 15.0.2

**Comment by sandwwraith** [comment]
Try `./gradlew publishToMavenLocal`.

**Comment by Earthcomputer** [comment]
Hmm, that seems to miss the platform-specific artifacts such as `kotlinx-serialization-cbor-jvm`
