### ISSUE TITLE
Optional properties are not working on Kotlin 1.5.31

### ISSUE THREAD

**Issue by MikolajKakol** [Kotlin/kotlinx.serialization#1705]
I'm dealing with demanding API, that has 3 states: value, null value, no value. It's a case described in blog post here: https://medium.com/livefront/kotlinx-serialization-de-serializing-jsons-nullable-optional-properties-442c7f0c2614

**To Reproduce**
I have serialiser as in blog post:

```
open class OptionalPropertySerializer<T>(
    private val valueSerializer: KSerializer<T>
) : KSerializer<OptionalProperty<T>> {
    final override val descriptor: SerialDescriptor = valueSerializer.descriptor

    final override fun deserialize(decoder: Decoder): OptionalProperty<T> =
        OptionalProperty.Present(valueSerializer.deserialize(decoder))

    final override fun serialize(encoder: Encoder, value: OptionalProperty<T>) {
        when (value) {
            OptionalProperty.NotPresent -> throw SerializationException(
                "Tried to serialize an optional property that had no value present." +
                        " Is encodeDefaults false?"
            )
            is OptionalProperty.Present ->
                valueSerializer.serialize(encoder, value.value)
        }
    }
}
```
on Kotlin 1.5.30 this `valueSerializer` was injected correctly. However on 1.5.31 I'm always getting there instance of: `kotlinx.serialization.internal.UnitSerializer`

**Expected behavior**
It should work as in Kotlin 1.5.30. I'm not sure what created that regression (https://github.com/JetBrains/kotlin/releases/tag/v1.5.31) or is it serialisation issue or Kotlin's. 

**Environment**
 - Kotlin version: 1.5.31
 - Library version: 1.3.0, also tested with the same result on 1.2.2
 - Kotlin platforms: JVM, native
 - Gradle version: 7.2

**Comment by sandwwraith** [comment]
Can you please show how you apply this serializer?

**Comment by MikolajKakol** [comment]
```
class OptionalPropertySerializer<T>(
    private val valueSerializer: KSerializer<T>
) : KSerializer<Optional<T>> {
    final override val descriptor: SerialDescriptor = valueSerializer.descriptor

    final override fun deserialize(decoder: Decoder): Optional<T> {
        return try {
            Optional.Value(valueSerializer.deserialize(decoder))
        } catch (exception: Exception) {
            L.e(exception)
            Optional.NotPresent
        }
    }

    final override fun serialize(encoder: Encoder, value: Optional<T>) {
        val msg = "Tried to serialize an optional property that had no value present. Is encodeDefaults false?"
        when (value) {
            Optional.NotPresent -> throw SerializationException(msg)
            is Optional.Value ->
                when (val optional = value.value) {
                    null -> encoder.encodeNull()
                    else -> valueSerializer.serialize(encoder, optional)
                }
        }
    }
}
```

```@Serializable(OptionalPropertySerializer::class)
sealed class Optional<out T : Any?> {

    object NotPresent : Optional<Nothing>()

    data class Value<T : Any?>(val value: T?) : Optional<T>()

    fun get(): T? {
        return when (this) {
            NotPresent -> null
            is Value -> this.value
        }
    }
}
```

And then in data classes:
```
    @SerialName("credit_limit")
    val creditLimit: Optional<Money?> = Optional.NotPresent,
    @SerialName("insurance")
    val insurance: Optional<String?> = Optional.NotPresent,
```

I believe it's identical as in linked blog post.

**Comment by shanshin** [comment]
As a workaround, you need to remove the `@Serializable(OptionalPropertySerializer::class)` annotation from the `Optional` class and add it to each property of your data class (like in blog post).

**Comment by DRSchlaubi** [comment]
Still happens in 1.6.10 and 1.6.0 and is preventing us from upgrading

**Comment by DRSchlaubi** [comment]
> As a workaround, you need to remove the `@Serializable(OptionalPropertySerializer::class)` annotation from the `Optional` class and add it to each property of your data class (like in blog post).

That's not a fie sable workaround, that class is used a couple of thousand times in our project

**Comment by DRSchlaubi** [comment]
I just checked the generated byte code from the compiler plugin, and it's completely identical

**Comment by C2H6O** [comment]
Related YouTrack ticket: https://youtrack.jetbrains.com/issue/KT-50764
