### ISSUE TITLE
When Default is present, null should be ignored when decoding

### ISSUE THREAD

**Issue by Shabinder** [Kotlin/kotlinx.serialization#1710]
**Describe the bug**
How to configure Json so that if a data class field has DEFAULT value and when decoding if json has 
`"fieldName": null`
to ignore null and just use Default Value provided in Model.
So that this behaviour is enabled when decoding manually and using 3rd party libs like Ktor etc
**To Reproduce**
```
data class Greet(name: String = "anonymous")

json:
 {"name":null} OR {"name":"null"}

Error:
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset : Unexpected 'null' value instead of string literal

```

**Expected behavior**
when encountered any, it should **serialize with default value: `Greet(name="anonymous")`** and ignore null and deserialize back into `{"name":"anonymous"}`

**Environment**
 - Kotlin version: 1.5.31
 - Library version: 1.2.2
 - Kotlin platforms: KMP
 - Gradle version: 4.2.2

**Comment by shanshin** [comment]
Hi!
To decode `null` as default value you can use `coerceInputValues` flag for Json format
```
@Serializable
data class Greet(val name: String = "anonymous")

val json = Json {
    coerceInputValues = true
}
...
println(json.decodeFromString<Greet>("""{"name": null}"""))
```
it prints `Greet(name=anonymous)`

**Comment by Shabinder** [comment]
Thanks :+1:
