### ISSUE TITLE
Automatically find the `StringFormat` through `ServiceLoader`

### ISSUE THREAD

**Issue by RinOrz** [Kotlin/kotlinx.serialization#1711]
**What is your use-case and why do you need this feature?**
Conveniently decoded a given file in a multi-format visualization decoder

**Describe the solution you'd like**
Referring to [Tika](https://github.com/apache/tika/blob/main/tika-parsers/tika-parsers-standard/tika-parsers-standard-modules/tika-parser-text-module/src/main/resources/META-INF/services/org.apache.tika.detect.EncodingDetector), I can detect different files or contents by defining corresponding parsers and detectors in the `/META-INF/services`. In some cases, this will get rid of the inconvenience of specifying format classes (`Json`, `Yaml`, `Properties`)

**Comment by sandwwraith** [comment]
Sorry, I didn't quite get the idea. Do you want `kotlinx.serialization` to implement Tika's service or to provide format auto-detect by itself?

In either way, I think service loaders are a non-goal for this library. There are several reasons for it:

1. There's no reliable multiplatform ServiceLoader implementation
2. Detecting input format is a hard task to write from scratch, while its benefits are unclear — most users do know what format they parse. 
3. It's relatively easy to write your own adapter with service loading mechanism
