### ISSUE TITLE
JsonConfiguration#ignoreUnknownKeys is not working.

### ISSUE THREAD

**Issue by DSeeLP** [Kotlin/kotlinx.serialization#1713]
**Describe the bug**
`Decoder#decodeSerializableValue` ignores `JsonConfiguration#ignoreUnknownKeys` and an `JsonDecodingException` is thrown.

**To Reproduce**
https://gist.github.com/DSeeLP/c5055f616ad0b7e4337cdadd24d1c4e5

**Expected behavior**
It should deserialize it to `FineRestResponse(value=kotlin.Unit)` and discard the unknown keys. 

**Environment**
 - Kotlin version: 1.5.31
 - Library version: 1.3.0
 - Kotlin platforms: JVM
 - Gradle version: 7.1.1
 - JRE Version: OpenJDK 11.0.11
 - OS: Fedora 34

**Comment by josepanguera** [comment]
In your example you're using `Unit` which is not serializable.

If you add this class

```
@Serializable
class Discard  // this could be named however you want
```

and then change the line

```
println(json.decodeFromString<RestResult<Unit>>(inputText))
```

for 

```
println(json.decodeFromString<RestResult<Discard>>(inputText))
```

you'll see that it works as intended and and is in fact respecting the `ignoreUnknownKeys` setting.
