### ISSUE TITLE
Document applying the plugin when using Gradle's Kotlin DSL

### ISSUE THREAD

**Issue by d-noll** [Kotlin/kotlinx.serialization#1716]
**What is your use-case and why do you need this feature?**

I was trying to use `kotlinx.serialization` from a Gradle build script which is not the main build script.

So far, I have verified that this is legal:

```kotlin
buildscript {
    dependencies {
        val kotlinVersion = "1.5.31"
        classpath(kotlin("gradle-plugin", version = kotlinVersion))
        classpath(kotlin("serialization", version = kotlinVersion))
    }
}
```

[The documentation for applying it for Groovy](https://github.com/Kotlin/kotlinx.serialization/blame/master/README.md#L142) in Kotlin syntax ends up as this:

```kotlin
apply(plugin = "gradle-plugin")
apply(plugin = "kotlinx-serialization")
```

But this fails the build with:

```lang-none
* What went wrong:
Plugin with id 'gradle-plugin' not found.
```

The documentation describes this as "the old way", but the new way documented doesn't work unless you're in the main build file, which I am not.

**Describe the solution you'd like**

* Documentation gives a working example of how to apply the plugin for Gradle Kotlin DSL.
* Documentation does not use the wording "the old way" unless it also describes a newer alternative which works in files which are not the main build script.

**Comment by sandwwraith** [comment]
I believe README.md contains correct example now (for old way, it should be `apply plugin: 'kotlin'`)
