### ISSUE TITLE
Question about line breaks

### ISSUE THREAD

**Issue by september669** [Kotlin/kotlinx.serialization#1718]
Code like this

```kotlin
@Serializable
data class Foo(
        val string: String
)

    fun lineBreak(){

        val jsonString = """
            {
              "string": "Line ->\\n<- break"
            }
        """.trimIndent()

        val json = Json {
            ignoreUnknownKeys = true
            isLenient = true
            prettyPrint = true
        }

        val foo = json.decodeFromString<Foo>(jsonString)
        logError { "Foo: $foo" }
    }
```

print out:
```
Foo: Foo(string=Line ->\n<- break)
```

Is there are any possibility to parse "line breaks" like above to real line breaks?

**Comment by pdvrieze** [comment]
You would need to use a custom serializer (`EscapeStringSerializer`) that would do the encoding/decoding of strings that takes into account breaks. Then use the regular way to specify which serializer to use (not the default). Another way is to use a value class (maybe with `@JvmInline`) which would allow the serializer to be specified for the type and automatically picked up.

**Comment by september669** [comment]
Thanks a lot!
