### ISSUE TITLE
Inconsistent Serialization for properties with default values

### ISSUE THREAD

**Issue by BreimerR** [Kotlin/kotlinx.serialization#1719]
**Describe the bug**
Properties in data class constructor not serialized correctly when a default value is defined. 
1. If Default value == newValue being passed // not serialized

**To Reproduce**

```
@Serializable
data class Bar(
    // unsorted isn't serialized
    var unsorted: Int = 12,
    // not serialized
    val sorted: Boolean = false,
    // serialized when test case uses false as value in main
    val empty: Boolean = true
)

@Serializable
data class Foo(
    val bar: Bar,
    val arg: Boolean,
    val arg1: Boolean,
   // This is not serialized when false is passed as new value 
    val arg2: Boolean = false
)

fun main(){
    println(
            Json.encodeToString(
                Foo.serializer(), Foo(
                    Bar(
                        unsorted = 12,
                        sorted = false,
                        empty = false
                    ),
                    arg = true,
                    arg1 = true,
                    // Not serialized
                    arg2 = false
                )
            )
        )
}
```

**Expected behavior**
Since default values aren't serialized. In a scenario the value is similar to the default value. 
The value should still be serialized, as for some instances with just two states i.e true/false 
the behavior isn't consistent. 

**Environment**
```build.gradle.kts
plugins {
    kotlin("jvm") version "1.5.31"
    kotlin("plugin.serialization") version "1.5.31"
}

repositories {
    mavenCentral()
}

dependencies {
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.0")
    testImplementation(kotlin("test", version = "1.5.31"))
}

tasks.test {
    useTestNG()
}

tasks.withType<KotlinCompile>() {
    kotlinOptions.jvmTarget = "13"
}
```

**Comment by pdvrieze** [comment]
In your example case the default for `Bar.empty` is true, but the test case uses the value `false`. So from your example it seems that it actually behaves as expected.

**Comment by BreimerR** [comment]
Was presenting the error in both cases :). Bar. empty does serialize since it's set value is different from the default value but arg2 does not serialize when it's value is false.

**Comment by BreimerR** [comment]
Neither is unsorted serialized

**Comment by sandwwraith** [comment]
Sorry, I don't quite get the question. Your example works as expected, because values that are _equal to the default_ are not serialized (with default JSON settings). To change that, create new json instance with different setting: `Json { encodeDefaults = true }`
