### ISSUE TITLE
When ProtoBuf is moving to stable state?

### ISSUE THREAD

**Issue by mithileshpp** [Kotlin/kotlinx.serialization#1724]
Hello Guys, 

Is there any plan to move ProtoBuf to stable state and support all ProtoBuf 3 syntax.

**Comment by rvijayraghavan** [comment]
@sandwwraith is there a project timeline which you could share? We wanted to use this library on a production app and wanted to know when do you plan to attain stability for ProtoBuf. Would there be a lot of breaking changes expected between the current state to stable state? This information would be helpful. Thanks.

**Comment by pdvrieze** [comment]
@mithileshpp I've implemented a pull request (#1830) to support packed fields. Per the protobuf documentation reading must support either form independent of the `.proto` specification. The reading support does this, which is the main compatibility issue (there is still limited support for unsigned integer types). Packing can be enabled with an annotation.
