### ISSUE TITLE
Cannot get custom serializer reflectively when using named companion objects

### ISSUE THREAD

**Issue by ansman** [Kotlin/kotlinx.serialization#1726]
**Describe the bug**
Calling the `serializer` function to get a serializer reflectively fails if a custom serializer is used and that serializer is a named companion object.

If the name is removed then the function behaves as expected.

**To Reproduce**
Here is an example:
```kotlin
@Serializable(with = Foo.Creator::class)
data class Foo(val foo: String) {
    companion object Creator : KSerializer<Foo> {
        override val descriptor: SerialDescriptor get() = TODO("not implemented")
        override fun deserialize(decoder: Decoder): Foo {
            TODO("not implemented")
        }
        override fun serialize(encoder: Encoder, value: Foo) {
            TODO("not implemented")
        }
    }
}

// Fails
serializer<Foo>()
```

**Expected behavior**
The correct serializer should be returned.

**Environment**
 - Kotlin version: 1.5.31
 - Library version: 1.3.0
 - Kotlin platforms: JVM
 - Gradle version: 7.0.2

**Comment by sandwwraith** [comment]
Fixed by #2381 and corresponding changes in the compiler plugin
