### ISSUE TITLE
Json.encodeToString() does not include a property of enum type when it has a default value

### ISSUE THREAD

**Issue by Shpota** [Kotlin/kotlinx.serialization#1735]
Default properties of an enum type are not included in JSON payloads when converted using `Json.encodeToString()`

The following snippet prints `{}` instead of expected `{"status":"OFFLINE"}`:
```
import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json

enum class Status { ONLINE, OFFLINE }

@Serializable
data class User(val status: Status = Status.OFFLINE)

fun main() {
    println(Json.encodeToString(User()))
}
```
If I remove a default parameter from the `User` class and create a user passing status, this would print the expected result of `{"status":"OFFLINE"}`:
```
@Serializable
data class User(val status: Status)

fun main() {
    println(Json.encodeToString(User(Status.OFFLINE)))
}
```

**Environment**
 - Kotlin version: `1.5.31`
 - Library version: `1.3.0`
 - Kotlin platforms: `JVM`
 - Gradle version:  `7.1`

**Comment by Whathecode** [comment]
> Why does a serialization library decide for me if certain parts of my class have to be sterilized based on the fact of presence/absence of a default value assigned to it?

The assumption here is that the defaults are _shared/known_ across platforms doing serialization, either by using the same serialization library, or by convention/documentation:

- If the same serialization library is used, using the same classes containing the default information, encoding the defaults is _redundant_. It will work out of the box.
- If a different serialization library is used and encoding defaults is enabled, it implies the defaults are "documented". The field is not nullable, so _needs to be assigned_. It is the responsibility of the serialization library used to implement correct mapping, using whatever mechanism those libraries have available to deal with this.

>  By not serializing default values as standard behavior, I would have to make the clients know that on the implementation side a particular set of properties have default values and let the clients know what those defaults are in order for them to handle the case when a JSON doesn't include a particular property.

Exactly; this is a feature. That's in essence what a type with default values _is_. If no default values can be assumed, then don't specify a default value in the type. Or, if default values are only known/can be assumed on one specific client (using one serialization library), then enable serialization of defaults on the client.

Semantically speaking, serializing a type with default values is not the same as serializing a type without default values. From a domain perspective, they are distinct objects.
