### ISSUE TITLE
Generate exportable external interfaces for encodeToDynamic/decodeFromDynamic

### ISSUE THREAD

**Issue by ankushg** [Kotlin/kotlinx.serialization#1744]
**What is your use-case and why do you need this feature?**
We use `kotlinx.serialization` to map json strings from our API response into Kotlin data classes.

We **also** use `kotlinx.serialization` to 
- map our Kotlin `data class`es into standard JS objects using `encodeToDynamic` for JS consumers of our KMP library and 
- JS Objects back to `data class`es using `decodeFromDynamic` when JS consumers pass in data

This is great because it allows us to reuse our existing serialization logic for network requests, while exposing data in a shape that JS consumers expect.

It's **much** faster than manually declaring `external interface`s for each `data class` and writing mapping methods.

However, these methods only return/consume `dynamic`. This means that we don't get Typescript definitions like we would with a standard `external interface` in the new JS IR Backend.

Ideally, we would be able to have `external interface`s generated based on our `SerialDescriptor`s, and be able to export them for use in our JS clients so they know what to expect.

**Describe the solution you'd like**

- Serializer walks through the `SerialDescriptor`s for each option
- Serializer generates `external interface` representations of what it's spitting out
  - acceptable if there are reasonable limitations on what can be converted to an `external interface`
- allows users to mark `external interface` with `@JsExport` to get type definitions
- `encodeToDynamic` can be cast to that generated `external interface`

**Comment by ankushg** [comment]
Thanks @sandwwraith -- definitely valid that this may be out of scope for the core serialization library.

Do you have any pointers on where to start?

Maybe an example of a plugin or format that can look up and iterate over all `SerialDescriptor`s at compile-time? 

My goal would probably not be to directly generate TS interfaces, but instead to generate Kotlin `@JsExport external interface`s via KotlinPoet.

**Comment by ankushg** [comment]
@aSemy That seems like exactly what I'm looking for! I'll definitely take a look and leave some feature requests 😉 

Happy to see if there's a way I can contribute too

**Comment by sandwwraith** [comment]
@aSemy Looks great!

I assume ticket can be closed now, as I said, this is a bit out of scope of the core library

**Comment by aSemy** [comment]
@sandwwraith Actually I was hoping I could contribute kxs-ts-gen to this repo, just like `ProtoBufSchemaGenerator`. I was going to make a PR, but I can make a new issue of course.
