### ISSUE TITLE
XML Support

### ISSUE THREAD

**Issue by martmists-gh** [Kotlin/kotlinx.serialization#1747]
**What is your use-case and why do you need this feature?**

Many applications still use XML files and parsing them using Kotlinx serialization would be much nicer compared to doing it manually.

**Describe the solution you'd like**

Add an Xml serializer similar to Json and Protobbuf

**Comment by pdvrieze** [comment]
I have an extensive XML format as community format: https://github.com/pdvrieze/xmlutil

**Comment by qwwdfsad** [comment]
We do not have plans to develop an XML format and recommend using the community-develop format instead.
Paul's library seems to be the right choice here

**Comment by sschuberth** [comment]
Also see https://github.com/Kotlin/kotlinx.serialization/issues/188.
