### ISSUE TITLE
Add support `Apache Thrift`

### ISSUE THREAD

**Issue by xiaobailong24** [Kotlin/kotlinx.serialization#1751]
**What is your use-case and why do you need this feature?**
[Thrift](https://thrift.apache.org/) is used to serialize object to bytes and deserialize bytes to object in network, how to work with kotlinx.serialization?

**Describe the solution you'd like**

**Comment by sandwwraith** [comment]
We do not currently plan to add support for more formats (see detailed explanation [here](https://github.com/Kotlin/kotlinx.serialization/issues/160#issuecomment-401008239)). However, you can write your own [custom serial format](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/formats.md#custom-formats-experimental) that we can add to the list of community-curated formats.
