### ISSUE TITLE
EncodeDefault Annotation not affect serialization

### ISSUE THREAD

**Issue by lbasek** [Kotlin/kotlinx.serialization#1755]
**Bug**

I spotted some weird behavior on model serialization with default values. 

Regarding example from [here](https://kotlin.github.io/kotlinx.serialization/kotlinx-serialization-core/kotlinx-serialization-core/kotlinx.serialization/-encode-default/index.html) ,
I tried the same example on the Android project but received a totally different output.

<img width="1041" alt="Screenshot 2021-11-09 at 4 27 32 PM" src="https://user-images.githubusercontent.com/555829/140953280-b471db6b-5826-4109-ab77-99981182d950.png">

Looks like a missing `a` element annotated with `@EncodeDefault(ALWAYS)` after serialization.

Also, `encodeDefaultsAnnotationWithFlag()` test should fail in [Kotlinx serialization - test ](https://github.com/Kotlin/kotlinx.serialization/blob/176310c582f6a30f7a8c815023f7eecca6ead338/formats/json/commonTest/src/kotlinx/serialization/features/SkipDefaults.kt) ? Or I missed something?

**Expected behavior**

Expected behavior should be the same as [HERE](https://kotlin.github.io/kotlinx.serialization/kotlinx-serialization-core/kotlinx-serialization-core/kotlinx.serialization/-encode-default/index.html).

```
@Serializable
data class Foo(
    @EncodeDefault(ALWAYS) val a: Int = 42,
    @EncodeDefault(NEVER) val b: Int = 43,
    val c: Int = 44
)

Json { encodeDefaults = false }.encodeToString((Foo()) // {"a": 42}
Json { encodeDefaults = true }.encodeToString((Foo())  // {"a": 42, "c":44}
```

**Environment**
 - Kotlin version: [1.5.20]
 - Library version: [1.3.0]
 - Kotlin platforms: Android
 - Gradle version: [7.0.2]

Thanks a lot!

**Comment by lbasek** [comment]
Looks like the Kotlin version is out of date. Have to update from `1.5.20` to `1.5.31` .
Closing the issue.

**Comment by sandwwraith** [comment]
Yes, `@EncodeDefault` is recognized only by compiler plugin 1.5.30 or higher
