### ISSUE TITLE
Experimental Status - How long?

### ISSUE THREAD

**Issue by Ademord** [Kotlin/kotlinx.serialization#1759]
**What is your use-case and why do you need this feature?**
When will the library get out of Experimental ? I want to use json.decodeFromString<Clazz>(json) in production code and I am wondering how many years left :)

**Describe the solution you'd like**
Production-ready deserialization!

**Comment by sandwwraith** [comment]
Most of the core and JSON parts of the library are stable for quite some time, since 1.0. Major experimental parts left for now are only protobuf/CBOR and custom formats.

Regarding `decodeFromString`, it was a bug with experimentality leaked from supertype: #1668

**Comment by Ademord** [comment]
sorry as correction, the markdown ate the correct code I referenced: `json.decodeFromString<ClassA>(jsonString)`

**Comment by sandwwraith** [comment]
@Ademord That shouldn't make a difference. Are you using `1.3.0` / `1.3.1` version?

**Comment by Ademord** [comment]
@sandwwraith, thanks for your reply.

i am using `1.2.2` for my serialization. what are the advantages / disadvantages of this?

**Comment by Ademord** [comment]
@sandwwraith should I upgrade... ?

**Comment by sandwwraith** [comment]
1.3.0 contains correct supertypes that aren't marked with `@ExperimentalSerializationApi`, so if you want to get rid of warning, yes, you should upgrade.

`@Serializable` is also applicable on types:


```kotlin
    val amountsByDay: Map<@Serializable(LocalDateSerializer::class) LocalDate, @Serializable(BigDecimalSerializer::class) BigDecimal>
```

You may also want to check out `@file:UseSerializers` annotation

**Comment by Ademord** [comment]
@sandwwraith excuse my last question, for a non-primitive type such as LocalDate or BigDecimal, what would you say is the correct implementation of a serializer? I am hacking things together as follows but I want to do it properly:
```
object BigDecimalSerializer : KSerializer<BigDecimal> {
    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("BigDecimal", PrimitiveKind.DOUBLE)

    override fun deserialize(decoder: Decoder): BigDecimal =
        decoder.decodeDouble().toBigDecimal()

    override fun serialize(encoder: Encoder, value: BigDecimal) {
        encoder.encodeDouble(value.toDouble())
    }
}

object LocalDateSerializer : KSerializer<LocalDate> {
    override val descriptor = PrimitiveSerialDescriptor("LocalDate", PrimitiveKind.STRING)

    override fun deserialize(decoder: Decoder): LocalDate {
        return LocalDate.parse(decoder.decodeString())
    }

    override fun serialize(encoder: Encoder, value: LocalDate) {
        encoder.encodeString(value.toString())
    }
}

```

**Comment by pdvrieze** [comment]
> @sandwwraith thanks a lot for your feedback and the reference to `@file:UseSerializers`. If I may one last question, for a non-primitive type such as `LocalDate` or `BigDecimal`, what would you say is the correct implementation of a serializer? I am hacking things together as follows but I want to do it properly, if you could take a look:

For `BigDecimal` there is no single best way. It could be done as an array of ints or a string (doing it as int/double looses information), most formats don't actually support this natively. For a textual format a string makes most sense, never double.

For dates again there are various serializations (including ISO standards) that are used in different contexts. Bottom line is that it is mostly serialized as a specially formatted string. Your example is "correct" although it doesn't specify the format explicitly.

**Comment by Ademord** [comment]
@pdvrieze thank you! this helps a lot. And the point about the JsonException on a test? @Test(expected = Exception::class)? I wish I could catch a more concrete Exception...

**Comment by Ademord** [comment]
@sandwwraith @pdvrieze  thanks for the reply! and what about nullable types? What is the best way to implement a serializer with a nullable type? for example above, the `BigDecimal` to be `BigDecimal?`, I see that the encoder does not have a `encodeDoubleOrNull()` method.
