### ISSUE TITLE
Type mismatch: inferred type is ProvisionedDid but SerializationStrategy<TypeVariable(T)> was expectedkotlin(TYPE_MISMATCH)

### ISSUE THREAD

**Issue by FrankC01** [Kotlin/kotlinx.serialization#1760]
**Describe the bug**
Can't serialize data class
**To Reproduce**
```kotlin
@Serializable
data class ProvisionedDid(var seed: ByteArray, var longDid: String, var provHashStr: String)

fun foo() {
    val provDid =
            ProvisionedDid(
                    // ByteArray
                    seed,           
                    // String                               
                    unpublishedDid.did.toString(),
                    // String
                    createDidInfo.operationHash.hexValue)

    val jsonString = Json.encodeToString(provDid) // Compile error

}
```
Attach a code snippet or test data if possible.

**Expected behavior**
Data class is serialized

**Environment**
 - Kotlin version: 1.5.31-release-548 (JRE 11.0.13+8-LTS)
 - Library version: implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.1")
 - Kotlin platforms: JVM
 - Gradle version: 7.3
 - Other relevant context [Mac OS X 11.6 x86_64]

**Comment by pdvrieze** [comment]
The single-argument version of `encodeToString` is an extension method that needs to be imported. Alternatively you can of course specify the serializer to use explicitly.

**Comment by sandwwraith** [comment]
It's easier to `import kotlinx.serialization.*`. Everything should work correctly with this import.
