### ISSUE TITLE
upgrade serialization and can a error for JsonDecodingException 

### ISSUE THREAD

**Issue by MartinWong-H** [Kotlin/kotlinx.serialization#1763]
serialization update 0.2 to 1.2.1 and that can not found  JsonDecodingException .

SerializationException replace it ?

**Comment by sandwwraith** [comment]
Yes, most of the exceptions were hidden to provide only SerializationException.
You can check out detailed changelog here: https://github.com/Kotlin/kotlinx.serialization/blob/master/CHANGELOG.md#100-rc--2020-08-17
