### ISSUE TITLE
Deserialize Json with Dynamic Key

### ISSUE THREAD

**Issue by EMIN3M1986** [Kotlin/kotlinx.serialization#1771]
Hi. 
How can I deserialize this json to Hashmap ?

favourite, irt and usdt are the keys.

```
> 
> {
>    "markets":{
>       "favourite":[  ],
>       "irt":[
>          {
>             "symbol":"usdt",
>             "pair":"irt",
>             "lastRate":0
>          },
>          {
>             "symbol":"btc",
>             "pair":"irt",
>             "lastRate":0
>          }
>       ],
>       "usdt":[
>          {
>             "symbol":"btc",
>             "pair":"usdt",
>             "lastRate":"58766.88197299"
>          },
>          {
>             "symbol":"bch",
>             "pair":"usdt",
>             "lastRate":"573.08756077"
>          }
>       ]
>    }
> }
```

**Comment by sandwwraith** [comment]
You may want to check out `parseToJsonElement` (https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#parsing-to-json-element)

**Comment by EMIN3M1986** [comment]
> You may want to check out `parseToJsonElement` (https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#parsing-to-json-element)

I thinks it does not work for my situation. I have keys (irt, usdt,...) witch are dynamic and change after a while. This is a API response.

**Comment by sandwwraith** [comment]
JsonElement is not a static model, it's a key-value json hash map

**Comment by NanoSpicer** [comment]
Something that has worked for me for optional keys is a property with a default value whenever you want a class for something:
```kotlin
@Serializable
data class Something(val somethingThatMightNotBeThere: String?=null)
```
