### ISSUE TITLE
JsonDecodingException: Unexpected JSON token at offset 181: Expected start of the array '[', but had ' ' instead

### ISSUE THREAD

**Issue by NanoSpicer** [Kotlin/kotlinx.serialization#1773]
**Describe the bug**
I am trying to parse a JSON file from Reddit and I am unable to parse JSON while the browser and nodejs are able to do so.

It crashes with:

> JsonDecodingException: Unexpected JSON token at offset 181: Expected start of the array '[', but had ' ' instead

**To Reproduce**
```kotlin
// main.kt
fun main() {
    val json = File("./weevils.json").readText()
    println(Json.decodeFromString<NewResponse>(json))
}
```

```kotlin
import kotlinx.serialization.Serializable


@Serializable
data class NewResponse(
    val kind: String,
    val data: NewData
)

@Serializable
data class NewData(
    val after: String,
    val dist: Int,
    val modhash: String,
    val geo_filter: String,
    val children: List<Post>?,
    val before: String?
)

@Serializable
data class Post(
    val kind: String,
    val data: List<PostData>?
)

@Serializable
data class PostData(
    val title: String,
    val url: String,
    val upvote_ratio: Float,
    val gallery_data: GalleryData
)

@Serializable
data class GalleryData(
    val items: List<GalleryItem>?
)

@Serializable
data class GalleryItem(
    val caption: String,
    val media_id: String,
    val id: Long
)
```

[The weevils.json file](https://gist.githubusercontent.com/NanoSpicer/9718cb497037e1b90f8a18f1045d001b/raw/c3e5401911ec60a826829fe0b564a95379cb7c1d/weevils.json)

**Expected behavior**

A pretty print of my data-classes, no crash

**Environment**
 - Kotlin version: 1.5.31
 - Library version: 1.3.1
 - Kotlin platforms: JVM
 - Gradle version: 7.1
 - Other relevant context, Ubuntu 20

**Comment by bartvanheukelom** [comment]
```
@Serializable
data class Post(
    val kind: String,
    val data: List<PostData>?
)
```

from a glance at the JSON file, it looks like `data` should be just a single `PostData`, not a list

**Comment by NanoSpicer** [comment]
And you would be correct.

Sorry, way too many hours in front of the computer!

**Comment by bartvanheukelom** [comment]
Np, these things can be like one of those "spot the differences" puzzles. That said, the error message could be improved, e.g. by including "List<PostData>?" in it. Or even breadcrumbs all the way from the top level to the element currently being decoded.
