### ISSUE TITLE
Create .proto file from serializer

### ISSUE THREAD

**Issue by justinhj** [Kotlin/kotlinx.serialization#1778]
**What is your use-case and why do you need this feature?**

When using the proto buffer serializer it would be great to be able to share the schema in proto language format with other services implemented in different languages. 

**Describe the solution you'd like**

An option to export the proto2 language schema from a class, perhaps using a flag in the ProtoBuf SerialFormat instance.

**Comment by sandwwraith** [comment]
Check out https://kotlin.github.io/kotlinx.serialization/kotlinx-serialization-protobuf/kotlinx-serialization-protobuf/kotlinx.serialization.protobuf.schema/-proto-buf-schema-generator/index.html

(this should have been added to general protobuf docs in `docs/formats.md`)

**Comment by justinhj** [comment]
I've added some documentation in the spot that would have helped me best find this...

https://github.com/Kotlin/kotlinx.serialization/pull/1855

**Comment by justinhj** [comment]
Fixed with #1855
