### ISSUE TITLE
Json.decodeToSequence is unable to parse a stream of whitespace-separated json objects

### ISSUE THREAD

**Issue by yevsev** [Kotlin/kotlinx.serialization#1779]
**Describe the bug**
A call to `next()` function throws the following exception:
`kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 96: Expected beginning of the string, but got {`

I am trying to decode a string containing two objects separated by a whitespace:
`{...} {...}`

After stepping through the library code in android studio I got to the point where `JsonTreeReader` read the first object. But I did not get to the point where `stackDepth` is decremented back to `0`.

I am sure that the type `com.example.package.MyType` is parseable because I tried it with `Json.decodeFromString()` which works fine.

It seems that the inputstream is not split by whitespace before it is parsed and the parser is also not taking care of this.

**To Reproduce**
Given the following string in `byteArray`: 
`{"type":"com.example.package.MyType","id":"user2117487202","id2":"user2117487202","someInt":2} {"type":"com.example.package.MyType","id":"user2117487202","id2":"user2117487202","someInt":2}`
It has 1 whitespace as separator between the two objects.
```
val sequence = Json.decodeToSequence<Message>(ByteArrayInputStream(byteArray), 
                                              DecodeSequenceMode.WHITESPACE_SEPARATED)
val iter = sequence.iterator()
val m1 = iter.next() // <-- here is throws 
```

**Expected behavior**
First call to `iter.next()` gives the first value of type `MyType` and second call gives the second value.

**Environment**
I am not sure where to find the versions but I found this:
`implementation 'org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.1'`

 - Kotlin version: [e.g. 1.3.30]
 - Library version: [e.g. 0.11.0]
 - Kotlin platforms: [e.g. JVM, JS, Native or their combinations]
 - Gradle version: [e.g. 4.10]
 - IDE version (if bug is related to the IDE) [e.g. IntellijIDEA 2019.1, Android Studio 3.4]
 - Other relevant context [e.g. OS version, JRE version, ... ]

**Comment by sandwwraith** [comment]
For me, this code works correctly:

```kotlin
@Serializable
    data class Message(val type: String, val id: String, val id2: String, val someInt: Int)

    @Test
    fun testMessage() {
        val input = """ {"type":"com.example.package.MyType","id":"user2117487202","id2":"user2117487202","someInt":2} {"type":"com.example.package.MyType","id":"user2117487202","id2":"user2117487202","someInt":2}"""
        val sequence = Json.decodeToSequence<Message>(ByteArrayInputStream(input.encodeToByteArray()),
            DecodeSequenceMode.WHITESPACE_SEPARATED)
        val iter = sequence.iterator()
        println(iter.next())
        println(iter.next())
    }
```

Can you provide another reproducer?

**Comment by yevsev** [comment]
Thanks for the quick reply.

I have to admit that I was bit frustrated yesterday and didn't make a proper reproducible example.

One thing that might be important is that I am using `sealed class` with `abstract` attributes instead of `data class`. I need polymorphic encoding/decoding. 
The example you provided worked correctly.

Reproducible example:
```
    @Serializable
    sealed class MyTypeAbstract {
        abstract val id1: String
    }
    @Serializable
    sealed class MyTypeAbstract2 : MyTypeAbstract() {
        // nothing here
    }
    @Serializable
    class MyType(override val id1: String) : MyTypeAbstract2()
    @Serializable
    class MyType2(override val id1: String, val id2: String, val someInt : Int) : MyTypeAbstract2()

    @Test
    fun testMyType() {
        val serialized = Json.encodeToString<MyTypeAbstract>(MyType("user"))
        val input = "$serialized $serialized"
        println("input = $input")
        val sequence = Json.decodeToSequence<MyTypeAbstract>(ByteArrayInputStream(input.encodeToByteArray()),
            DecodeSequenceMode.WHITESPACE_SEPARATED)
        val iter = sequence.iterator()
        println("iter.next() = ${iter.next()}")
        println("iter.next() = ${iter.next()}")
    }
    @Test
    fun testMyType2() {
        val serialized = Json.encodeToString<MyTypeAbstract>(MyType2("user1", "user2", 2))
        val input = "$serialized $serialized"
        println("input = $input")
        println(input)
        val sequence = Json.decodeToSequence<MyTypeAbstract>(ByteArrayInputStream(input.encodeToByteArray()),
            DecodeSequenceMode.WHITESPACE_SEPARATED)
        val iter = sequence.iterator()
        println("iter.next() = ${iter.next()}")
        println("iter.next() = ${iter.next()}")
    }
```

**Comment by sandwwraith** [comment]
Thank you for the detailed reproducer! It is indeed the problem with polymorphism, to be precise, with decoding to the JsonElement that is involved inside it.
