### ISSUE TITLE
Unexpected JSON token at offset xx: Expected numeric literal

### ISSUE THREAD

**Issue by FutureIsHereX** [Kotlin/kotlinx.serialization#1781]
Normally, the json data I receive looks like this:
```json
{
  "datas":  { },
  "sessionid": "...",
  "status": 1
}
```
In this case, the program runs correctly. 
But If my `sessionid` expires, then the json data returned by the backend looks like this:
```json
{
  "error": [
    "..."
  ],
  "sessionid": "...",
  "status": [
    -2
  ]
}
```
As you can see, the data type of the `status` field has changed, and my application has the following exception at runtime:
```java
W/System.err: kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset xx: Expected numeric literal
W/System.err: JSON input: {"sessionid":"...","error":["..."],"status":[-2]}
```
Related configurations:
```kotlin
@Serializable
data class XXXResp(
  @SerialName("datas")
  val datas: Datas? = null,
  @SerialName("sessionid")
  val sessionid: String,
  @SerialName("status")
  val status: Int = 600,
) 
```

```kotlin
private val contentType = "application/json".toMediaType()
private val json = Json {
  prettyPrint = true
  ignoreUnknownKeys = true
  coerceInputValues = true
}
```

How do I fix it If I want to be compatible with both types? Thanks :-)

### Environment:
- kotlin version: 1.5.31
- Library version: 1.3.1
- Kotlin platforms: JVM, Android
- Gradle version: 7.0.3

**Comment by sandwwraith** [comment]
The exception here is reasonable: since your `status` is declared as `Int`, the JSON parser expects a number in the input, not an array. 

Ideally, you want to fix your backend, but to work around the problem you can use untyped `JsonElement`, which can contain both numbers or arrays:


```kotlin
@Serializable
data class SomeResp(
    @SerialName("status") private val mStatus: JsonElement
) {
   val status: Int get() = (j as? JsonPrimitive)?.int ?: (j as JsonArray).first().jsonPrimitive.int
}
```

**Comment by FutureIsHereX** [comment]
@sandwwraith That workaround works great, thank you! 😉

**Comment by FutureIsHereX** [comment]
In fact, I just called a third-party api, so I can't fix the bug by contacting the backend. I believe many people should also have this trouble.
Keep up the awesome work!
