### ISSUE TITLE
Add message on exception #1613

### ISSUE THREAD

**Issue by caffeine-mgn** [Kotlin/kotlinx.serialization#1783]
**What is your use-case and why do you need this feature?**
#1613

**Describe the solution you'd like**
In this case print message like "Make sure you add kotlinx-serialization plugin"

**Comment by sandwwraith** [comment]
Now, SerialInfo annotations are instantiated using [Annotation Instantiation] feature (https://kotlinlang.org/docs/annotations.html#instantiation) and should not require compiler plugin to be applied
