### ISSUE TITLE
easier encodeToString by generic type

### ISSUE THREAD

**Issue by eman1986** [Kotlin/kotlinx.serialization#1785]
**What is your use-case and why do you need this feature?**

I often will save a json result from an API within my app to help curb data costs and I try to make the code as reusable as possible.

**Describe the solution you'd like**

currently you need to do the following to serialize an object to json:

```
Json.encodeToString(User.serializer(), data)
```

it'd be nice if I could do it like so:

```
Json.encodeToString<User>(data)
```

the issue at hand is the class is setup to use generics so it won't know the object up front.

**Comment by sandwwraith** [comment]
We do have this function, it's an extension. Import it or just `import kotlinx.serialization.*`

**Comment by eman1986** [comment]
Is there an example of this somewhere?

**Comment by sandwwraith** [comment]
https://github.com/Kotlin/kotlinx.serialization#introduction-and-references

**Comment by eman1986** [comment]
I'll give that a go, I saw that and then experienced a different way it asked to work. Thanks

**Comment by eman1986** [comment]
I tried that got the following message back:

> Cannot use 'T' as reified type parameter. Use a class instead.

```
    fun <T>saveData(data: T, destination: String)
    {
        // ...
        val json = Json.encodeToString(data)
    }
```

**Comment by eman1986** [comment]
after playing around I figured it out, closing this ticket,
