### ISSUE TITLE
Support null keys in maps

### ISSUE THREAD

**Issue by justinhj** [Kotlin/kotlinx.serialization#1786]
**What is your use-case and why do you need this feature?**

I ran into the issue when using the protobuf serializer that null keys are not supported in maps. Is this something that will supported in the future, or is there some technical issue with the Protobuf encoding? 
I can work around it by not using null keys but wanted to check if I'm missing something in the docs.

**Describe the solution you'd like**

Null keys work.

**Comment by sandwwraith** [comment]
This is a limitation of the protobuf format. It does not have a concept of `null`, it only has present (required) and missing (optional) properties. Because if a key is missing from the map, it is, well, missing, it is impossible to use `null` as a key in the protobuf map.

**Comment by justinhj** [comment]
Ah, that's clear now thanks.
