### ISSUE TITLE
Polymorphic deserialization fails when deserializing using custom Composite Serializer

### ISSUE THREAD

**Issue by snowe2010** [Kotlin/kotlinx.serialization#1791]
**Describe the bug**

I'm attempting to map one object to another using serialization. For example, say we have the structure:

```kotlin
@Serializable
@RegisterForReflection
data class Input(
    val sealedClass: ExampleTopLevelClass,
)

@Serializable
sealed class Letters {
    abstract val parameterJustForDataClasses: String // only provided for data class example
    abstract val productType: ProductType
}

@Serializable
@SerialName("A")
data class A(
    override val parameterJustForDataClasses: String,
    val aData: String,
) : Letters() {
    override val productType: ProductType
        get() = ProductType.A
}

@Serializable
@SerialName("B")
data class B(
    override val parameterJustForDataClasses: String,
    val bData: String,
) : Letters() {
    override val productType: ProductType
        get() = ProductType.B
}

```

where our input takes a sealed class, that can either be `A` or `B`. There's nothing goofy about this, it works as advertised, I can serialize to it, deserialize from it, etc. 

The problem shows up when I try to use a custom serializer to map it to another object that is _exactly the same_, except we have a wrapper class around the types.

```kotlin
@Serializable
data class InputRuleUnit(val sealedClass: SingletonStore<Letters>) : RuleUnitData {
    constructor() : this(
        DataSource.createSingleton<Letters>(),
    )
}

class SingletonStoreSerializer<T>(private val dataSerializer: KSerializer<T>) : KSerializer<SingletonStore<T>> {
    override val descriptor: SerialDescriptor = dataSerializer.descriptor
    override fun serialize(encoder: Encoder, value: SingletonStore<T>) =
        dataSerializer.serialize(encoder, value.first())

    override fun deserialize(decoder: Decoder) =
        DataSource.createSingleton<T>().apply {
            set(dataSerializer.deserialize(decoder))
        }
}

...
        val string = json.encodeToString(serializer(), input) // where input is Input
        val ruleUnitData: RuleUnitData = json.decodeFromString(serializer(type), string) as RuleUnitData // where type is InputRuleUnit
...
```

So, this should just take the `sealedClass`, create a `DataSource`, and insert the `sealedClass` into it, returning the new `InputRuleUnit` type. This _works_ as long as the type isn't a sealed polymorphic structure (I haven't tested with non-sealed). But as soon as I include a sealed type into the input, it fails with 
```json
{
    "errorType": "java.lang.IllegalArgumentException",
    "errorMessage": "Polymorphic value has not been read for class null"
}
```

**To Reproduce**

Here is a full project showing the issue. 
[example.zip](https://github.com/Kotlin/kotlinx.serialization/files/7679431/example.zip)

hit `localhost:8082` with the json payload

```json
{
    "sealedClass": {
        "parameterJustForDataClasses": "blah",
        "productType": "A",
        "aData": "hi"
    }
}
```

**Expected behavior**

I would expect the polymorphic deserialization to correctly deserialize the polymorphic type, instead of throwing an error.

**Environment**
 - Kotlin version: **1.6.0**
 - Library version: **1.3.2-SNAPSHOT** (tested using head at 471f4bbfa28d0dd1d4af869dc992d7604374e4ac)
 - Kotlin platforms: **JVM**
 - Gradle version: N/A. Using Maven
 - Maven version: **3.8.3** set using `.tool-versions`
 - IDE version: N/A
 - Other relevant context: graalvm-21.3.0+java11 (set in .tool-versions`), macOS 12.0.1

**Comment by pdvrieze** [comment]
Looking at your data I see an obvious issue, you don't have a type discriminator. It might be that `productType` is intended to be the discriminator, but it isn't (also it's not the first child). As such the format doesn't know what to deserialize to.

**Comment by snowe2010** [comment]
@pdvrieze I've declared `classDiscriminator = "productType"` in both of my serializer objects (in KotlinxRuleUnitService and RequestStreamWrapper). And this works perfectly fine when serializing and deserializing to the same object, in this case `Input`, so I don't think that could be it. Even if it's a nested issue, why would that work for the case of serializing `Input > JSON` and then back to Input `JSON > Input`.

**Comment by snowe2010** [comment]
oh, sorry you mean first child as in, index=0. Still why does it work just fine when serializing and deserializing `Input`, but fails as soon as I try to deserialize into `InputRuleUnit`?

**Comment by sandwwraith** [comment]
Same as https://github.com/Kotlin/kotlinx.serialization/issues/2838#issuecomment-2457868144
