### ISSUE TITLE
Serialization fails for classes extended from open classes

### ISSUE THREAD

**Issue by vnermolaev** [Kotlin/kotlinx.serialization#1792]
**What is your use-case and why do you need this feature?**
I am working with a codebase over which I have a very limited influence.

That codebase features the following (utterly simplified) class hierarchy:

```kotlin
interface State {
    val i: Int
}

@Serializable
open class InternalState(
    override val i: Int
): State

@Serializable
data class ExternalState(
    override val i: Int
): InternalState(i)
```

This code produces a compilation error
`Serializable class has duplicate serial name of property 'i', either in the class itself or its supertypes`.
Clearly, the serialization engine thinks that there are _two_ fields with the same name.
Of course, one option to address the issue is to redeclare `ExternalState` as

```kotlin
@Serializable
data class ExternalState(
    @SerialName("j")
    override val i: Int
): InternalState(i)
```

but this will lead to a double encoding of the same values under a different name.

**Describe the solution you'd like**
Serializer derivation must be possible for classes extended from open classes.

**Comment by vnermolaev** [comment]
And there is this bug reported 2 years ago
https://youtrack.jetbrains.com/issue/KT-38958

**Comment by sandwwraith** [comment]
It is a known limitation related to the fact that a pair of `open/override` properties creates two backing fields (https://github.com/Kotlin/kotlinx.serialization/issues/427#issuecomment-939982702)

**Comment by vnermolaev** [comment]
All right, I guess it is not addressable within `kotlinx.serialization`. Thanks for clearing it up.
