### ISSUE TITLE
classDiscriminator is not treated as known key for JSON deserialization and requires ignoreUnknownKeys

### ISSUE THREAD

**Issue by fmagin** [Kotlin/kotlinx.serialization#1797]
**Describe the bug**

The field used as the `classDiscriminator` is not treated as a known key and  `ignoreUnknownKeys = true` is required to deserialize successfully.

**To Reproduce**

I am deserializing data coming from the Python `jsonpickle` module with ` jsonpickle.encode(make_refs=False)`
which I deserialize with the following code example code:

```kotlin
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.builtins.ListSerializer
import kotlinx.serialization.json.Json

@Serializable
@SerialName("some.python.module.Definition")
data class Definition(val atom: Atom)

@Serializable
sealed class Atom

@Serializable
@SerialName("some.python.module.Register")
data class Register(val reg_offset: Int, val _size: Int) : Atom()


@Serializable
@SerialName("some.python.module.MemoryLocation")
data class MemoryLocation(
    val addr: Address,
    val _size: Int
) : Atom()

@Serializable
sealed class Address

@Serializable
@SerialName("some.python.module.SpOffset")
data class SpOffset(
    val is_base: Boolean,
    val _bits: Int,
    val reg: String,
    val offset: Int
) : Address()

fun main() {
    val json = Json {
        classDiscriminator = "py/object"
    }

    val input = """
        [
           {
                "py/object": "some.python.module.Definition",
                "atom": {
                    "py/object": "some.python.module.Register",
                    "reg_offset": 264,
                    "_size": 8
                }
            },
            {
                "py/object": "some.python.module.Definition",
                "atom": {
                  "py/object": "some.python.module.MemoryLocation",
                  "addr": {
                    "py/object": "some.python.module.SpOffset",
                    "is_base": false,
                    "_bits": 64,
                    "reg": "sp",
                    "offset": -16
                  },
                  "_size": 8
                }
            }
        ]
        
        """.trimIndent()
    val def = json.decodeFromString(ListSerializer(Definition.serializer()), input)
    println(def)
}
```

Fails with:

```
Exception in thread "main" kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 16: Encountered an unknown key 'py/object'.
Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
```

Adding `ignoreUnknownKeys = true` does indeed "fix" the issue and results in the expected output:
`[Definition(atom=Register(reg_offset=264, _size=8)), Definition(atom=MemoryLocation(addr=SpOffset(is_base=false, _bits=64, reg=sp, offset=-16), _size=8))]`.
But know I adding any kind of unexpected key will still work and it will be silently discarded, which I would rather avoid.

Annotating each class with `@JsonClassDiscriminator("py/object")` doesn't fix the unknown key issue, but allows removing `classDiscriminator = "py/object"` argument to the Json configuration.

**Expected behavior**

If the JSON configuration has `classDiscriminator  = "py/object"` then `"py/object"` is treated as a known key
or at least if the class itself is explicitly annotated with `@JsonClassDiscriminator("py/object")`  it implicitly has the key `"py/object"`

**Environment**
 - Kotlin version: `1.6.0`
 - Library version: `1.3.1`
 - Kotlin platforms: JVM
 - Gradle version: 6.7

**Comment by sandwwraith** [comment]
The class discriminator is used only during polymorphic deserialization — i.e. for abstract and sealed classes. For regular data classes, such as `Definition`, the discriminator is not needed and thus parser is not expecting it.

However, it indeed looks like some kind of UX problem. Probably another use-case for #1247 / #1128
