### ISSUE TITLE
Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.

### ISSUE THREAD

**Issue by soniccat** [Kotlin/kotlinx.serialization#1798]
**Describe the bug**
Hi, I’ve recently switched to kotlin 1.6.10 and started getting this error messages from my gradle :buildSrc:compileKotlin:
`
/Users/<me>/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-serialization/1.6.10/4052dd14b5f3264b5d91598f6db4a7b5983cf9cf/kotlin-serialization-1.6.10.jar!/META-INF/kotlin-serialization.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
`
and
`
/Users/alexeyglushkov/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-serialization/1.6.10/4052dd14b5f3264b5d91598f6db4a7b5983cf9cf/kotlin-serialization-1.6.10.jar!/META-INF/kotlinx-serialization-compiler-plugin.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.6.0, expected version is 1.4.2.
`

With kotlin 1.5.31 I was able to build my convention plugins without problems. 

**To Reproduce**
Checkout this branch https://github.com/soniccat/WordTeacher/tree/serialization-buildsrc-conflict and run `./gradlew :android:assembleDebug`. 

The main setup is in two files.
buildSrc settings file: https://github.com/soniccat/WordTeacher/blob/serialization-buildsrc-conflict/buildSrc/settings.gradle.kts
and KMM convention plugin file:  https://github.com/soniccat/WordTeacher/blob/serialization-buildsrc-conflict/buildSrc/src/main/kotlin/kmmlib-convention.gradle.kts

**Expected behavior**
The convention plugin compiles without problems as before. You can get the previous version of the code with kotlin 1.5.31 at this commit https://github.com/soniccat/WordTeacher/commit/0ae62bb76ea1be9dd6d60fc0d23a524f68618aca

The current workaround for me is to move serialization dependency out of buildSrc. The code is here https://github.com/soniccat/WordTeacher/commit/a8ef2e35ba80fb042f3532229c87204528a1c179
I moved plugin importing in the KMM shared lib here https://github.com/soniccat/WordTeacher/blob/a8ef2e35ba80fb042f3532229c87204528a1c179/shared/build.gradle.kts

**Environment**
 - Kotlin version: 1.6.10
 - Library version: 1.3.1
 - Kotlin platforms: JVM
 - Gradle version: 7.1.1
 - IDE version (if bug is related to the IDE): Android Studio Arctic Fox | 2020.3.1 Patch 4, Build #AI-203.7717.56.2031.7935034, built on November 21, 2021
 - Other relevant context: macOS BigSur 11.2.3 (20D91)

**Comment by sandwwraith** [comment]
Maybe it's a conflict between the embedded version and the specified. Try to specify the kotlin plugin version here, too: https://github.com/soniccat/WordTeacher/blob/serialization-buildsrc-conflict/buildSrc/settings.gradle.kts#L14. Or update your Gradle version. 

If the problem still persists, please create a YouTrack issue. It looks like more of a Kotlin Gradle plugin problem rather than a compiler plugin or runtime.

**Comment by Lacritz** [comment]
Hi @soniccat, 
I had a similar issue and fixed it by applying the Kotlin plugins in the root `build.gradle.kts`.
Unfortunately, I don't quite understand why it's solving the issue, but at least it's working for the moment.

**Comment by soniccat** [comment]
@sandwwraith @Lacritz thanks guys for your help, the issue just disappeared after switching from gradle-7.1.1-bin.zip to gradle-7.3.2-bin.zip without any additional changes. That's really weird...

**Comment by sandwwraith** [comment]
@soniccat I think that's because Gradle 7.1.1 and 7.3.2 embed different Kotlin versions

**Comment by JavierStuart** [comment]
@sandwwraith I am facing this issue but the problem is with 1.7.0

```
.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-serialization/1.7.0/37a22a5af9c7ca016d7001b19e0fe2e830e16401/kotlin-serialization-1.7.0.jar!/META-INF/kotlinx-serialization-compiler-plugin.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
```

And the problem is there is no Gradle version with 1.7.0 yet.

**Comment by nulls** [comment]
@JavierStuart we got the same issue in our project and we applied a workaround:
```kotlin
plugins {
    // workaround https://github.com/gradle/gradle/issues/16345
    `kotlin-dsl`.version("2.3.3")
}
```
It upgraded embedded version of kotlin to 1.6.x and allows to work with 1.7.0, but it leads to warning message during a build:
```
This version of Gradle expects version '2.1.7' of the `kotlin-dsl` plugin but version '2.3.3' has been applied to project ':buildSrc'. Let Gradle control the version of `kotlin-dsl` by removing any explicit `kotlin-dsl` version constraints from your build logic.
```

**Comment by cheesepp** [comment]
> @sandwwraith I am facing this issue but the problem is with 1.7.0
> 
> ```
> .gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-serialization/1.7.0/37a22a5af9c7ca016d7001b19e0fe2e830e16401/kotlin-serialization-1.7.0.jar!/META-INF/kotlinx-serialization-compiler-plugin.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.
> ```
> 
> And the problem is there is no Gradle version with 1.7.0 yet.

I'm having the same problem. Did you fix it??

**Comment by MuhammadAliGhaffar** [comment]
In my case firebase BOM is causing issue ,degrade version solved my issue

**Comment by ashishrajvanshi01** [comment]
I was also facing this issue because of firebase BOM, as suggested by @MuhammadAliGhaffar  I degraded its version to 30.0.0 solved the problem.

**Comment by shindenitish** [comment]
If you came here to solve a Kotlin incompatibility issue in November 2022, try once: https://github.com/facebook/react-native/issues/35210

**Comment by sgtpsibin** [comment]
@shindenitish  you saved our life!
