### ISSUE TITLE
Errors needs to be reported at compile time, not runtime

### ISSUE THREAD

**Issue by shafirov** [Kotlin/kotlinx.serialization#18]
```
data class A(val name: String)
@Serializable data class B(val a: A)
```
Compiles just fine but serialization fails at runtime with exception

**Comment by sandwwraith** [comment]
If serializator encounters class, which is not marked as serializable, it is formatting library who decides how to write this class - we pass it as `writeValue(value: Any)`. Binary formats in current implementation throw exceptions, and JSON have a fallback with writing `value.toString()`. 

I think in future we should provided linting hints/warning like "Non-serializable class will be written as Any, not all formats support this"

**Comment by sandwwraith** [comment]
Collected use-cases and similar issues in #37
