### ISSUE TITLE
Serialization not working in multiplatform project

### ISSUE THREAD

**Issue by Whathecode** [Kotlin/kotlinx.serialization#180]
I am in the process of converting a Kotlin/JVM library using `kotlinx.serialization` to a Multiplatform library targeting both JavaScript and the JVM. I am using version 0.6.0 and have the matching IntelliJ plugin installed.

However, apparently serializers can no longer be found when I try to call `JSON.stringify( o )`.

> Can't locate default serializer for class ....

IntelliJ recognizes the static method `SomeObject.serializer()`, but when I try to compile, I get:

> Unresolved reference: serializer

**Comment by sandwwraith** [comment]
Have you applied `kotlinx-serialization' plugin to common module in Gradle?

**Comment by Whathecode** [comment]
I have; only in 'common' though, in case that matters. I believe the problem might be due to serializing `expected` and `actual` types. Having a hard time figuring out what is going on (multiple errors). Will add more information once I do.

**Comment by sandwwraith** [comment]
You need to specify it both in common and platform modules

**Comment by Whathecode** [comment]
Yes, that was the problem. I do have other errors as well, related to `expect` and `actual`, but I will post a different issue in case I figure out what is going on there.

Thank you!

**Comment by sandwwraith** [comment]
What do you mean by 'news'? Issue is closed, applying serialization plugin for all modules is required. I don't see any problems in setup you've described in the stackoverflow post; but from the stacktrace I can see that you've launched tests from IDEA, which is not supported by now. Make sure that `Settings - Build, Execution, Deployment - Build Tools - Gradle - Runner - Delegate IDE build/run actions to gradle` is enabled.
