### ISSUE TITLE
Obtaining a deserializer for a subclass of a sealed class from just the class discriminator value

### ISSUE THREAD

**Issue by inthewaves** [Kotlin/kotlinx.serialization#1802]
**What is your use-case and why do you need this feature?**

I am working with a JSON protocol where some messages have the following structure:

```kotlin
sealed class TypedException

sealed class JsonMessageWrapper<out Response> {
    public abstract val data: Response?

    public open val error: TypedException? = null

    public open val errorType: String? = null
}
```

The class discriminator for the `TypedException` is the `errorType` which is in the parent object. The JSON body doesn't include the class discriminator in the nested object itself, making it harder to just use the generated serializers as is.

**Describe the solution you'd like**

(I did notice https://github.com/Kotlin/kotlinx.serialization/pull/686 and https://github.com/Kotlin/kotlinx.serialization/issues/471, and there's probably a better way to handle this entire situation with a`JsonContentPolymorphicSerializer`, although the type variable in `JsonMessageWrapper` might make things a bit more complex)

Currently, the class is structured like this:

```kotlin
sealed class JsonMessageWrapper<out Response> {
    public abstract val data: Response?

    public open val error: JsonObject? = null

    public open val errorType: String? = null
}
```

I'm currently working with obtaining a polymorphic deserializer for the `TypedException` based on the value of the `errorType`  :

```kotlin
val deserializer: DeserializationStrategy<out TypedExceptionV1> = jsonInstance.serializersModule.getPolymorphic(TypedExceptionV1::class, response.errorType)!!
val typedExceptionBody: TypedExceptionV1 = jsonInstance.decodeFromJsonElement(deserializer, response.error!!)
```

For this method, all the sealed subclasses of `TypedException` had to be registered with the `serializersModule`. I am wondering if there is a way to obtain a deserializer for a sealed class from just providing a class discriminator value without needing to register them all in the module.

**Comment by sandwwraith** [comment]
SealedClassSerializer should expose its inner module — #1865, #2199
