### ISSUE TITLE
Decoding json-data gives error about expecting '{' instead of ':' even though the json-data matches the data-structure

### ISSUE THREAD

**Issue by TorRanfelt** [Kotlin/kotlinx.serialization#1803]
When using kotlinx serialization 1.1.0 a valid json-string is decoded into a matching data-structure, but with 1.3.1 a nonsensical error is thrown about unexpected token:

Start of json-string: {"0":{"0":{"solution":{"modules":["SK","VK","DP"],"package":"PROFESSIONEL"},

Error with 1.3.1: "Unexpected JSON token at offset 32: Expected start of the object '{', but had ':' instead
JSON input: .....0":{"0":{"solution":{"modules":["SK","VK","DP"],"package":"P....."

I have checked the data-structure and modules is not supposed to be an object but a list and a ':' would be needed anyway.
To reiterate 1.1.0 does not have this problem.

**Environment**
 - Kotlin version: 1.6.10
 - Library version: 1.3.1
 - Kotlin platforms: JS
 - Gradle version: 7.1

**Comment by sandwwraith** [comment]
Can you share your data structure and input string, please?

**Comment by TorRanfelt** [comment]
The data-structure is defined over multiple files and thousands lines of code and the input-string is 48KB, so I'll truncate the part where it trips up which is at the beginning (that seems very coincidental so the same problem is probably found other places too). I'll also rename variables and classes, but that is not a problem since we use `@SerialName`.

```
@Serializable
class BoksData(
    @SerialName("0")
    val foo: Foo,
    @SerialName("1")
    val bar: Bar?,

    // And so it continues
}
```
```
@Serializable
class Foo{
    @SerialName("0")
    val foo: FooFoo = FooFoo()

    @SerialName("1")
    val bar: Array<FooBar> = Array(2) { FooBar() }
}
```
```
@Serializable
class FooFoo{
    var solution: Solution = Solution(listOf(SolutionModule.SK), SolutionPackage.PROFESSIONEL)

    @SerialName("52")
    var fooFooFoo: Int = 0

    // And so it continues
}
```
```
// Solution is defined in another project.

@Serializable
class Solution{
    val modules: List<SolutionModule>,
    val `package`: SolutionPackage
}
```

The first 83 characters of input-string:
{"0":{"0":{"solution":{"modules":["SK","VK","DP"],"package":"PROFESSIONEL"},"52":0,

**Comment by sandwwraith** [comment]
Sorry, but I'm unable to reproduce the problem. This code works fine for me:

```kotlin
@Serializable
    class BoksData(
        @SerialName("0")
        val foo: Foo,
    )

    // And so it continues

    @Serializable
    class Foo {
        @SerialName("0")
        val foo: FooFoo = FooFoo()

    }

    @Serializable
    class FooFoo {
        var solution: Solution = Solution(listOf(SolutionModule.SK), SolutionPackage.PROFESSIONEL)

        @SerialName("52")
        var fooFooFoo: Int = 0

        // And so it continues
    }

    @Serializable
    class Solution (
        val modules: List<SolutionModule>,
        val `package`: SolutionPackage
    )

    @Serializable
    enum class SolutionModule {
        SK, VK, DP
    }

    @Serializable
    enum class SolutionPackage {
        PROFESSIONEL
    }

    private val json = Json

    @Test
    fun test() {
        val input  = """{"0":{"0":{"solution":{"modules":["SK","VK","DP"],"package":"PROFESSIONEL"},"52":0}}}"""
        val parsed = json.decodeFromString(BoksData.serializer(), input)
        println(parsed)
    }
```

If you can provide a minimal reproducer this would help

**Comment by TorRanfelt** [comment]
@sandwwraith The actual data-structure is huge (thousands of variables, lists, arrays, maps and in many cases nested).
It might be the size/complexity that trips up some bug.
I hope it won't be too long before I can get time to look into it.

**Comment by TorRanfelt** [comment]
@sandwwraith 
I have looked into it, and if I save the data with 1.1.0 it is saved as you would expect like this {"0":{"0":{"solution":{"modules":["SK","VK","DP"],"package":"PROFESSIONEL"},"52":0}}}.

However, with 1.3.2 (and no other changes) it is saved like this {"0":{"0":{"solution":{"modules":{"0":"SK","1":"VK","2":"DP"},"package":"PROFESSIONEL"},"52":0}}}

So data saved with 1.1.0 cannot be opened with 1.3.2, but data saved with 1.3.2 can be opened by 1.3.2.
Don't know why kotlinx-serialization suddenly wants an array to be expressed in this weird way.

Our json-mapper configuration:
```
val jsonMapper = Json {
            encodeDefaults = true
            useArrayPolymorphism = true
            ignoreUnknownKeys = true
            allowStructuredMapKeys = true
        }
```

**Comment by TorRanfelt** [comment]
When our original problem in https://github.com/Kotlin/kotlinx.serialization/issues/1577 started no class used in the component that took care of communication was used in the data-blobs in the main projects. - The previous problem wasn't solved, but it turned out that the feature triggering the problem wasn't needed anymore.
With that problem out of the way this problem turned up, but this is because one class is now shared between the common dependency and the main projects, and hence they need to be build with the same version of kotlinx.serialization. When that is done this problem disappears.

However, it's important that the previous years main projects don't have to use the same version of kotlinx.serialization as the newest one (breaking changes and what have you). Therefore, for this particular shared class I will have to create a serializer in the communication-component and another in the main project. For this I want to use the forClass feature, but that gives compile-time errors: https://github.com/Kotlin/kotlinx.serialization/issues/1844
