### ISSUE TITLE
Serialization without annotations

### ISSUE THREAD

**Issue by rrva** [Kotlin/kotlinx.serialization#1807]
**What is your use-case and why do you need this feature?**

It is cumbersome to have to annotate all classes you want to be able to serialize with @Serializable. Switching between for example jackson and kotlinx-serialization is more work. Code without annotations looks cleaner. 
 
**Describe the solution you'd like**

Some config option to tell the compiler plugin that "mark all classes in packages foo.bar, foo.xyz as serializable", and you would not have to use annotations. If this is not easy to do / less clear, then perhaps a compromise would be to allow a file-level annotation that marks all classes (or all data classes) in that file as serializable (`@file:Serializable`)

**Comment by sandwwraith** [comment]
See the answer to similar question here: https://github.com/Kotlin/kotlinx.serialization/issues/1808#issuecomment-1001512246
