### ISSUE TITLE
Automatic serialization of annotation classes.

### ISSUE THREAD

**Issue by isXander** [Kotlin/kotlinx.serialization#1811]
**What is your use-case and why do you need this feature?**
Since Kotlin 1.6, instantiation of annotation classes have become stable however annotating them with `@Serializable` produces this error: `@Serializable annotation is ignored because it is impossible to serialize automatically interfaces or enums. Provide serializer manually via e.g. companion object` this error doesn't seem to apply to annotation classes (maybe it's a bug?)

My use case is annotation processing. Rather than discovering annotations at runtime, I use a simple KSP AP to serialize these annotations into a json file, to be read at a later date. Currently, I have to write a `KSerializer` for simple annotations, exactly the same as a data class.

**Describe the solution you'd like**
Implement automatic serialization of annotation classes.

**Comment by elizarov** [comment]
See a related comment here https://github.com/Kotlin/kotlinx.serialization/issues/1808#issuecomment-1009764644
