### ISSUE TITLE
Links Broken In Documentation for Custom Formats

### ISSUE THREAD

**Issue by johnmidgley** [Kotlin/kotlinx.serialization#1814]
Many links in the documentation for custom formats result in 404s.

**To Reproduce**
- Navigate to (https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/formats.md#custom-formats-experimental)
- Click "Encoder" link - results in 404

**Expected behavior**
Links resolve correctly

**Environment**
 - Github

**Comment by sandwwraith** [comment]
Sorry, this was caused by https://github.com/Kotlin/kotlinx.serialization/commit/8be6845927414a844ffebedc871dd8bc0d4b8aee — it required re-uploading GH pages. 

Updated pages now.
