### ISSUE TITLE
Can't decode a FloatArray with Protobuf

### ISSUE THREAD

**Issue by achojoao** [Kotlin/kotlinx.serialization#1829]
**Describe the bug**

I am trying to decode an object coming from the server in my Android app using kotlinx-serialization-protobuf library version 1.3.2. The object has a FloatArray attribute, and while decoding, I'm getting the error:

`W/System.err: kotlinx.serialization.protobuf.internal.ProtobufDecodingException: Expected wire type 5, but found 2
W/System.err:     at kotlinx.serialization.protobuf.internal.ProtobufReader.readFloat(ProtobufReader.kt:197)
W/System.err:     at kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeTaggedFloat(ProtobufDecoding.kt:157)
W/System.err:     at kotlinx.serialization.protobuf.internal.ProtobufTaggedDecoder.decodeFloatElement(ProtobufTaggedDecoder.kt:66)
W/System.err:     at kotlinx.serialization.internal.FloatArraySerializer.readElement(PrimitiveArraysSerializers.kt:229)
W/System.err:     at kotlinx.serialization.internal.FloatArraySerializer.readElement(PrimitiveArraysSerializers.kt:220)
W/System.err:     at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51)
W/System.err:     at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36)
W/System.err:     at kotlinx.serialization.protobuf.internal.ProtobufDecoder.decodeSerializableValue(ProtobufDecoding.kt:190)
W/System.err:     at kotlinx.serialization.protobuf.internal.ProtobufTaggedDecoder.decodeSerializableElement(ProtobufTaggedDecoder.kt:82)`

I'm positive that the server is sending the array of floats back to the Android app. I can even successfully execute the inverse process: encode the object in the Android app, send it to the server and decode it in the server.

By the way, the object in the server has the proto3 format, but I tried proto2 getting the same problem.

Does anybody know why this error? Any help will be appreciated!

Thanks!

**To Reproduce**

```
@Serializable
class MyClassProtobuf {  
    

    @Serializable
    data class Template(
        @ProtoNumber(1)
        val createdAt: Long,
        @ProtoNumber(2)
        val vector: FloatArray
    )

}
```

`val serverTemplate = protobuf.decodeFromByteArray(MyClassProtobuf.Template.serializer(), response)
`

**Expected behavior**

A successful decoded object

**Environment**
 - Kotlin version: 1.5.10
 - Library version: 1.3.2
 - Kotlin platforms: Android
 - Gradle version: 6.5

**Comment by pdvrieze** [comment]
Looking at the [protobuf definition](https://developers.google.com/protocol-buffers/docs/encoding) it states that the format sent back is a list of strings, not a list of floats (type 5: fixed32, sfixed32, float). To resolve this, try to inspect the actual data with an inspection too

**Comment by achojoao** [comment]
Thanks @pdvrieze for your help.

I've done a test. The server side responses with simple data:

`MyClassProtobuf.Template.newBuilder().addAllVector(mutableListOf(1.0f, 2.0f,3.0f)).setCreatedAt(1234567890).build()`

The inspection of the resultant object shows an object of type MyClassProtobuf.Template with the "createdAt_" attribute filled with the correct value and a "vector_" attribute as a FloatArrayList of size 3, being each element a Float object with the correct value.

On the Android application side, the response is the following array of bytes:

[16, -46, -123, -40, -52, 4, 26, 12, 0, 0, -128, 63, 0, 0, 0, 64, 0, 0, 64, 64]

Performing the decoding, I'm getting the same error.

Maybe is an error in the definition on the server side?

```
syntax = "proto3";
package mypackage;
option java_outer_classname = "MyClassProtobuf";

message Template {
    int64 createdAt = 1;
    repeated float vector = 2 [packed=true];
}
```

**Comment by pdvrieze** [comment]
I've had a look at your data. There is one issue in that the field indices you give are incorrect. It uses index 2 for createdAt and index 3 for the vector. Note also that the protocol buffer (using a packed field) doesn't encode the type of the 12 bytes contained in the vector (therefore it requires the decoder to handle this).

I've had a look at the implementation. It doesn't support packed fields (in the comments of `ProtoBuf.kt`). It isn't quire a simple fix either to support them (although it is possible).

Overall, you have a feature request to support at least reading packed fields.

**Comment by achojoao** [comment]
@pdvrieze Thanks again for your time.

Yeah, it looks like I did not change the indices in the test, because the original class had other fields, but I left them out for test purposes.

I'll wait for the new feature, now that I see you are working on it right now. Hope it is released soon and I can test it.

Thanks!

**Comment by sandwwraith** [comment]
Also #192

**Comment by sandwwraith** [comment]
Fixed by adding `packed` support in ProtoBuf
