### ISSUE TITLE
Cannot parse escaped json

### ISSUE THREAD

**Issue by Shusek** [Kotlin/kotlinx.serialization#183]
I got json files from external api escaped by quote char ("), unfortunately I can not parse this value by JSON.parse method because i got error
> java.lang.IllegalArgumentException: JSON at 6: Expected string or non-null literal

Replication code:
```

    @Test
    fun testForEscapedString() {
        val escapedJson = """{\"name":\"myName\" ,\"secondValue\":\"mySecondValue\"}"""
        val myObj = JSON.parse<EscapedClass>(escapedJson)
        assertNotNull(myObj)
    }
  @Serializable
    data class EscapedClass(val name: String, val secondValue: String)
```

**Comment by JakeWharton** [comment]
This is not JSON. You have unquoted keys and values whose string delimiters are escaped. Seems like at worst you should pre-process this to remove the escaping and then use `JSON.unquoted`.
