### ISSUE TITLE
Sealed class object subtype does not serialize correctly

### ISSUE THREAD

**Issue by seyedjafariy** [Kotlin/kotlinx.serialization#1833]
**Describe the bug**
Trying to follow the Polymorphic guide on `sealed classes` that have an `object` as a subtype:
https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md#objects

If I pass the object alone (not wrapped in a list), the output string will not contain the `type` parameter:
```Kotlin
import kotlinx.serialization.encodeToString

fun main() {
    println(Json.encodeToString(EmptyResponse))
}
```
results in `{}`

**To Reproduce**
tried with any sealed class and it was the same story

**Expected behavior**

according to the docs it should be:
`{"type":"example.examplePoly08.EmptyResponse"}`

**Environment**
 - Kotlin version: 1.6.10
 - Library version: 1.3.2
 - Plugin version: 1.6.10
 - Kotlin platforms: JVM
 - Gradle version: 7.1
 - IDE version: IC-213.6461.79, built on December 28, 2021
 - Other relevant context: adopt-openj9-15.0.2

**Comment by sandwwraith** [comment]
There is important note in https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md#sealed-classes : 

> Pay attention to the small, but very important detail in the above example that is related to Static types: the val data property has a compile-time type of Project, even though its run-time type is OwnedProject. When serializing polymorphic class hierarchies you must ensure that the compile-time type of the serialized object is a polymorphic one, not a concrete one.

In other words, if the compile-time type of property is a concrete one, polymorphism is not enabled and thus discriminator is not included. You can fix this by specifying type explicitly, e.g. `Json.encodeToString<MyBaseResponse>(EmptyResponse)`

See also https://github.com/Kotlin/kotlinx.serialization/issues/1194 and https://github.com/Kotlin/kotlinx.serialization/issues/1247
