### ISSUE TITLE
MissingFieldException error will occur for empty objects

### ISSUE THREAD

**Issue by SongHuaixu** [Kotlin/kotlinx.serialization#1834]
**Describe the bug**

kotlinx.serialization.MissingFieldException: Fields [token, user] are required for type with serial name 'LoginData', but they were missing

expects data to be null

**To Reproduce**

``` Json
{
    "data" : {}
} 
```

``` Kotlin 

@Serializable
data class Response<T>(
    val data: T? = null
)

@Serializable
data class LoginData(val token: String, val user: String)

```

**Expected behavior**

**Environment**
 - Kotlin version: [1.6.10]
 - kotlin-serialization version: [1.6.10]

**Comment by sandwwraith** [comment]
That's correct behavior. `data` can be null if it's said in the input: `{ "data": null}` or if the key is missing completely. Here, `"data": {}` is an empty object.

**Comment by SongHuaixu** [comment]
> That's correct behavior. `data` can be null if it's said in the input: `{ "data": null}` or if the key is missing completely. Here, `"data": {}` is an empty object.

But the description of data is nullable, so if it doesn't match, shouldn't it resolve successfully and data == null?
