### ISSUE TITLE
@Serializer's forClass gives compile error

### ISSUE THREAD

**Issue by TorRanfelt** [Kotlin/kotlinx.serialization#1844]
Background: In a component A a class is defined that I need to create a serializer for. However, component B that depends on component A needs its own serializer for the same component. This is because some variants of component A will be from previous years and not get updates to dependencies, and hence the version of kotlinx.serialization will not always be the same in component A and component B. This is normally not a problem because classes used for serialization by A is not used by B and vice versa. However, this particular class is an exception. Because of this, component B can't depend on a serializer that might have been compiled with another version of kotlinx.serialization.

I use @Serializer(forClass = Bar::class) for each serializer I need of the same class.
However if Bar doesn't get `@Serializable` an error is thrown.

Does not work:

```
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.Serializable
import kotlinx.serialization.Serializer

//@Serializable
data class Bar(
    val modules: String,
)

@OptIn(ExperimentalSerializationApi::class)
@Serializer(forClass = Bar::class)
object BarSerializer
```

Error:
```
org.jetbrains.kotlin.js.facade.exceptions.TranslationRuntimeException: Unexpected error occurred compiling the following fragment: 'import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.Serializable
import kotlinx.serialization.Serializer

//@Serializable
data class Bar(
    val modules: String,
)

@OptIn(ExperimentalSerializationApi::class)
@Serializer(forClass = Bar::class)
object BarSerializer' at (1,1) in <my file>
	at org.jetbrains.kotlin.js.translate.general.Translation.translateFile(Translation.java:385)
<long stack-trace>
```

If Bar gets its `@Serializable` the problem disappears.

Works:
```
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.Serializable
import kotlinx.serialization.Serializer

@Serializable
data class Bar(
    val modules: String,
)

@OptIn(ExperimentalSerializationApi::class)
@Serializer(forClass = Bar::class)
object BarSerializer
```

The other component B that depends on component A defining the above gives the same error when an serializer is created this way. But in this case the error can't be circumvented by adding `@Serializable` to Bar in component B.

**Environment**
 - Kotlin version: 1.6.10
 - Library version: 1.3.2
 - Kotlin platforms: JS
 - Gradle version: 7.1

**Comment by sandwwraith** [comment]
I'm not sure external serializer generation was supported for legacy JS at all

**Comment by TorRanfelt** [comment]
Legacy JS? Do you mean that not using the IR compiler is considered legacy even though it is still in beta?

**Comment by sandwwraith** [comment]
Well, 'Beta' is as close to stable as possible, and I don't think there will be big issues with binary compatibility between IR-produced Kotlin/JS libraries. Again, I'm not sure old backend was giving any guarantees on that matter, too

**Comment by pdvrieze** [comment]
@TorRanfelt I would add that in my experience there are quite some limitations with the old compiler as well. At least for experimentation and development (not testing) builds the new one is plenty stable. The biggest issue is that some features aren't quite supported (but others aren't quite supported in the old one).

**Comment by sandwwraith** [comment]
Also: #967
