### ISSUE TITLE
java.lang.ClassCastException kotlin.reflect.jvm.internal.KTypeImpl cannot be cast to kotlin.jvm.internal.TypeReference

### ISSUE THREAD

**Issue by emartynov** [Kotlin/kotlinx.serialization#1845]
**Describe the bug**
We see a crash on the Android runtime and actually looks like working fine on the JVM:
```
Fatal Exception: java.lang.ClassCastException
kotlin.reflect.jvm.internal.KTypeImpl cannot be cast to kotlin.jvm.internal.TypeReference
kotlin.jvm.internal.ReflectionFactory.mutableCollectionType (ReflectionFactory.java:107)
kotlin.jvm.internal.Reflection.mutableCollectionType (Reflection.java:196)
package.NotificationIdsStorage.addNotificationId (NotificationIdsStorage.kt:72) 
...
```

**To Reproduce**
I see the crash in the reporting tool and I can not reproduce it on the JVM unit test. I wrote two tests - adding a new notification id to empty json, and adding new notification id to already existing json.
```
    fun getNotificationIds(): MutableMap<String, MutableList<Int>> {
        val string = prefs.getString(NOTIFICATION_ID_MAP, "")
        if (string.isNullOrEmpty()) return mutableMapOf()
        return json.decodeFromString<Map<String, List<Int>>>(string)
            .mapValues { it.value.toMutableList() }
            .toMutableMap()
    }

    fun addNotificationId(conversationId: String, notificationId: Int) {
        val ids = getNotificationIds()
        val list = ids[conversationId] ?: mutableListOf()
        list.add(notificationId)
        ids[conversationId] = list
        prefs.edit {
            putString(
                NOTIFICATION_ID_MAP,
                json.encodeToString(ids) <-- here is the crash
            )
        }
    }
```

**Expected behavior**
No crash

**Environment**
 - Kotlin version: 1.6.10
 - Library version: 1.3.2
 - Kotlin platforms: Android
 - Gradle version: 7.3.3

**Comment by sandwwraith** [comment]
Does it present on a particular version of the Android emulator/device or on every version? Also, is the line 72 (`package.NotificationIdsStorage.addNotificationId (NotificationIdsStorage.kt:72)`) is the one with ` json.encodeToString(ids)`?

**Comment by sandwwraith** [comment]
Maybe it is some kind of `typeOf` intrinsic function problem. Can you try the following: `json.encodeToString(serializer(typeOf<...>), ids))` where `...` is the actual type of `ids`

**Comment by RaySmith-ttc** [comment]
@sandwwraith I also get exception, but not on Android, but on JVM

Kotlin version: 1.6.10
Library version: 1.3.2

It happens with all mutable collections.

```
@Test
fun encodeMutableCollection() {
    val json = Json
    val obj1 = mutableMapOf("foo" to "bar").toMap()
    val obj2 = mutableMapOf("foo" to "bar")

    val expected = "{\"foo\":\"bar\"}"

    assert(json.encodeToJsonElement(obj1).toString() == expected) // fine
    assert(json.encodeToJsonElement(obj2).toString() == expected) // throw

    assert(json.encodeToString(serializer(typeOf<Map<String, String>>()), obj1) == expected) // fine
    assert(json.encodeToString(serializer(typeOf<MutableMap<String, String>>()), obj1) == expected) // throw 
}
```

```
java.lang.ClassCastException: kotlin.reflect.jvm.internal.KTypeImpl cannot be cast to kotlin.jvm.internal.TypeReference
	at kotlin.jvm.internal.ReflectionFactory.mutableCollectionType(ReflectionFactory.java:107)
	at kotlin.jvm.internal.Reflection.mutableCollectionType(Reflection.java:196)
	at UnitTests.encodeMutableCollection(UnitTests.kt:1155)
```

Also i noticed that the exception messages are different in different Java versions
Java 8: `kotlin.reflect.jvm.internal.KTypeImpl cannot be cast to kotlin.jvm.internal.TypeReference`
Java 17: `class kotlin.reflect.jvm.internal.KTypeImpl cannot be cast to class kotlin.jvm.internal.TypeReference (kotlin.reflect.jvm.internal.KTypeImpl and kotlin.jvm.internal.TypeReference are in unnamed module of loader 'app')`

**Comment by emartynov** [comment]
> Does it present on a particular version of the Android emulator/device or on every version? Also, is the line 72 (`package.NotificationIdsStorage.addNotificationId (NotificationIdsStorage.kt:72)`) is the one with ` json.encodeToString(ids)`?

As I wrote - I was not able to reproduce it in JVM test on JDK 15. From crash reporting I see it is happening on Android 11 only (however, not many people we caught in the internal testing).

**Comment by emartynov** [comment]
> @sandwwraith I also get exception, but not on Android, but on JVM
> 
> Kotlin version: 1.6.10 Library version: 1.3.2
> 
> It happens with all mutable collections.
> 
> ```
> @Test
> fun encodeMutableCollection() {
>     val json = Json
>     val obj1 = mutableMapOf("foo" to "bar").toMap()
>     val obj2 = mutableMapOf("foo" to "bar")
> 
>     val expected = "{\"foo\":\"bar\"}"
> 
>     assert(json.encodeToJsonElement(obj1).toString() == expected) // fine
>     assert(json.encodeToJsonElement(obj2).toString() == expected) // throw
> 
>     assert(json.encodeToString(serializer(typeOf<Map<String, String>>()), obj1) == expected) // fine
>     assert(json.encodeToString(serializer(typeOf<Map<String, String>>()), obj2) == expected) // fine
>     assert(json.encodeToString(serializer(typeOf<MutableMap<String, String>>()), obj2) == expected) // throw 
> }
> ```
> 
> ```
> java.lang.ClassCastException: kotlin.reflect.jvm.internal.KTypeImpl cannot be cast to kotlin.jvm.internal.TypeReference
> 	at kotlin.jvm.internal.ReflectionFactory.mutableCollectionType(ReflectionFactory.java:107)
> 	at kotlin.jvm.internal.Reflection.mutableCollectionType(Reflection.java:196)
> 	at UnitTests.encodeMutableCollection(UnitTests.kt:1155)
> ```
> 
> Also I noticed that the exception messages are different in different Java versions Java 8: `kotlin.reflect.jvm.internal.KTypeImpl cannot be cast to kotlin.jvm.internal.TypeReference` Java 17: `class kotlin.reflect.jvm.internal.KTypeImpl cannot be cast to class kotlin.jvm.internal.TypeReference (kotlin.reflect.jvm.internal.KTypeImpl and kotlin.jvm.internal.TypeReference are in unnamed module of loader 'app')`

Great you can reproduce it on the JVM!

And I fixed it similarly - convert all mutable maps to not mutable. That is also surprising since looking to the source of the `toMap` I still see the mutable map creation.

**Comment by sandwwraith** [comment]
Unfortunately, I still can't reproduce this on Java 11, 14, and Android emulator API 30. Anyway, It is clear that this is some kind of `typeOf`/kotlin-reflect issue. So I suggest doing the following:

1. Make sure that this issue is reproducible in a fresh project (and this is not some kind of misconfiguration e.g. different versions of kotlin-reflect and kotlin-stdlib)
2. Or make a minimal reproducer with all libraries and dependencies you use
3. Submit it to YouTrack (https://youtrack.jetbrains.com/issues/KT) so the team can assign and verify it properly

**Comment by unoexperto** [comment]
I have same problem on java 18.0.2 + kotlin 1.7.10. I don't even think it's related to kotlinx.serialization. It's happening in reified function in the project that doesn't even have kotlin-reflect in dependencies.

**Comment by martypitt** [comment]
Commenting for future google searchers - this comment from @sandwwraith fixed it for me:

> Make sure that this issue is reproducible in a fresh project (and this is not some kind of misconfiguration e.g. different versions of kotlin-reflect and kotlin-stdlib)

I had a fresh project, and had forgotten to declare `kotlin-reflect` as a dependency.

Adding the dependency with the correct version resolved the issue.

**Comment by sandwwraith** [comment]
Note that normally kotlinx.serialization does not require reflect in dependencies, so it is probably some other library misconfiguration

**Comment by jtaub** [comment]
I got this same error when using `ktor-client-java-jvm`, in a project which has no dependency on `kotlinx-serialization`. Can confirm that adding this to my pom resolved the issue:

```xml
<!-- https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-reflect -->
<dependency>
    <groupId>org.jetbrains.kotlin</groupId>
    <artifactId>kotlin-reflect</artifactId>
    <version>${kotlin.version}</version>
</dependency>
```
