### ISSUE TITLE
Unable to serialize sealed interface with enums

### ISSUE THREAD

**Issue by lammertw** [Kotlin/kotlinx.serialization#1847]
I have the following code:
```
sealed interface DeviceModel

@Serializable
enum class TrackerDeviceModel(val scanId: String): DeviceModel {
    V100S("V100S")
}

@Serializable
enum class BloodPressureDeviceModel(val scanId: String): DeviceModel {
    BP7350("BP7350")
}
```

Now when I try to serialize/deserialize a property of type `DeviceModel` I get the following exception:
```
Uncaught Kotlin exception: kotlinx.serialization.SerializationException: Class 'TrackerDeviceModel' is not registered for polymorphic serialization in the scope of 'DeviceModel'.
Mark the base class as 'sealed' or register the serializer explicitly.
```

According to the documentation, serialising sealed interfaces should work and serializing enums should work. I suspect that the combination of the two is causing the issue.

**Environment**
 - Kotlin version: 1.5.30
 - Library version: 1.3.1
 - Kotlin platforms: Native/iOS

**Comment by sandwwraith** [comment]
Does it work with `@Serializable sealed class`? Sealed interfaces are supported only from Kotlin 1.6.20 (#1576), before that, they're treated like regular interfaces and their subclasses should be registered

**Comment by lammertw** [comment]
Thanks for the info. Once we update to 1.6 I'll try that.
I cannot use a sealed class since it's not possible for Enums to inherit from classes.

**Comment by sandwwraith** [comment]
Note that 1.6.20-M1 is yet to be released
