### ISSUE TITLE
Not compatible with Kotlin 1.2.60

### ISSUE THREAD

**Issue by ScottPierce** [Kotlin/kotlinx.serialization#185]
Please do a release of `0.6.1` so we don't need to use a snapshot to upgrade to Kotlin `1.2.60`, which is [now released](https://blog.jetbrains.com/kotlin/2018/08/kotlin-1-2-60-is-out/).

It'd be great if kotlinx libraries were kept in sync with the kotlin library official releases.

**Comment by sandwwraith** [comment]
`0.6.1` has been released. Gradle plugin and library available on bintray, IDEA plugin will be built soon.
