### ISSUE TITLE
Empty json and `Serializable` class with no properties or only `@EncodedDefault` properties

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [Kotlin/kotlinx.serialization#1850]
**Describe the bug**

I am getting a server response which is an empty json { }, I am setting a Serializable class with no properties but I get this exception:

**To Reproduce**

Set an empty json (`{}`) and a `@Serializable class SomeClass` with no properties.

```
Exception in thread "main" kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 0: Expected start of the object '{', but had '{' instead
JSON input: {}
```

**Expected behavior**

If I get an empty json and I set a `@Serializable` class with no properties, I expect it to directly work (use case strong typing some error responses by the backend).

If I set a `data class` which contains one or more `@EncodedDefault` properties, they should be set.

**Environment**
 - Kotlin version: 1.6.10
 - Library version: 1.3.2
 - Kotlin platforms: KMP with JVM
 - Gradle version: 7.3.3

**Comment by ArcticLampyrid** [comment]
There is no `@EncodedDefault` but `@EncodeDefault`.
And `@EncodeDefault` is not for marking a property to be optional. What you mean may be a property with default value.
> ```
> @Target(allowedTargets = [AnnotationTarget.PROPERTY])
> annotation class EncodeDefault(mode: EncodeDefault.Mode)
> ```
> Controls whether the target property is serialized when its value is equal to a default value, regardless of the format settings. Does not affect decoding and deserialization process.

**Comment by sandwwraith** [comment]
I executed the following test:

```kotlin
    @Serializable class SomeClass

    @Test
    fun testEmpty() {
        val input = "{}"
        println(Json.decodeFromString<SomeClass>(input))
        println(default.decodeFromString<SomeClass>(input))
        println(lenient.decodeFromString<SomeClass>(input))
    }
```

and it works just fine. 

Maybe it has something to do with the encoding of server's response. For example, it may be incorrectly inserted BOM in UTF-8: https://github.com/Kotlin/kotlinx.serialization/issues/1168

**Comment by JavierSegoviaCordoba** [comment]
Yeah, looks like Ktor issue, I will move to it
