### ISSUE TITLE
@Transient not working anymore

### ISSUE THREAD

**Issue by mp3killa** [Kotlin/kotlinx.serialization#1858]
**Describe the bug**
@Transient no longer working after Android Studio update on data class

**To Reproduce**
class MyObject {
    @Transient
    var text: String = ""
    var moreText = ""
}

Actual Result: {text="", moreText=""}

**Expected behavior**

Expected Result: {moreText=""}

**Environment**
 - Kotlin version: 1.6.10
 - Library version: 
 org.jetbrains.kotlinx:kotlinx-serialization-json:1.2.2
 apply plugin: 'kotlinx-serialization'
 classpath "org.jetbrains.kotlin:kotlin-serialization:1.6.10"

 - Kotlin platforms: JVM
 - Gradle version: 7.1.1
 - IDE version  Android Studio Bumblebee 2021.1.1 Patch 1
 - Other relevant context macOS Monterey 12.1

**Comment by sandwwraith** [comment]
You've updated only Android Studio, Kotlin & serialization runtime versions are the same?

That sounds weird. Make sure that you haven't accidentally imported `kotlin.jvm.transient` instead

**Comment by mp3killa** [comment]
I'm not sure what you mean, they're both 1.6.10, i've double checked everything , Transient still being included.

```
import kotlinx.serialization.Serializable
import kotlinx.serialization.Transient

@Serializable
data class Thing(
    @Transient var id: String = "",
    var thing: String = ""
) {
    override fun toString(): String {
        return thing + " more"
    }
}
```

**Comment by mp3killa** [comment]
I see now it may not be this things fault, if I do this:

`Json.encodeToString(thing) `

versus my original implementation of just parsing the object to my Firebase Document Reference set it retains the Transient property. Any ideas on how to resolve?

`firestore.collection("thing").document(thing.id).set(thing)`
