### ISSUE TITLE
Gradle: Cannot Find runtime-common 0.6.0

### ISSUE THREAD

**Issue by electricjones** [Kotlin/kotlinx.serialization#186]
This may be related to or fixed by https://github.com/Kotlin/kotlinx.serialization/issues/185.

It also may be user error, but I've spent well over an hour on this and all seems correct.

I am building a `common` module for JSON Patch in pure Kotlin and using the `kotlinx.serialization` library. But, I cannot get the build to work. I am trying to build with `0.6.0` and am using Kotlin `1.2.51` because `0.6.1` has not been released.

Using IDEAJ, the import and autocompletion work. The IDE itself is finding the classes. But, when I try to run on the JVM, I get the error:

```
Could not find org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:0.6.0.
Searched in the following locations:
  - https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/kotlinx-serialization-runtime-common/0.6.0/kotlinx-serialization-runtime-common-0.6.0.pom
  - https://repo.maven.apache.org/maven2/org/jetbrains/kotlinx/kotlinx-serialization-runtime-common/0.6.0/kotlinx-serialization-runtime-common-0.6.0.jar
Required by:
    project :jpatch-kotlin-jvm > project :jpatch-kotlin-common
```

When I change the kotlinx version in mygradle script to `0.5.1`, just with an older version.

Personally, I would like to use Kotlin 1.2.60 and serializer 0.6.1.

My full gradle script is below:

```
buildscript {
    ext.kotlin_version = '1.2.51'
    ext.serialization_version = '0.6.0'

    repositories {
        jcenter()
        maven { url "https://kotlin.bintray.com/kotlinx" }
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlinx:kotlinx-gradle-serialization-plugin:$serialization_version"
    }
}

plugins {
    id 'kotlin-platform-common' version '1.2.51'
}

apply plugin: 'kotlinx-serialization'

repositories {
    jcenter()
    maven { url "https://kotlin.bintray.com/kotlinx" }
}

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-common"
    testCompile "org.jetbrains.kotlin:kotlin-test-annotations-common"
    testCompile "org.jetbrains.kotlin:kotlin-test-common"
    compile "org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:$serialization_version"
}
```

**Comment by sandwwraith** [comment]
Based on `Searched in the following locations:` report, looks like you've missing `maven { url "https://kotlin.bintray.com/kotlinx" }` in one of your `repositories` block, likely in `jvm` module, because `common` module have it. Note that repositories in gradle script are defined per module build and are not transitive.

**Comment by electricjones** [comment]
Thanks. I see what I'm not understanding, and it's not an issue with the library. I'll close this ticket.

But, I still can't get it to work, and I feel like I'm going the wrong direction. I want to create a library that can be used by applications on different platforms (`common` seems like to me), but it doesn't actually require any platform implementations.

Now, when I try to run the test, I get class not found error. It can't find the serialization classes.

**Comment by sandwwraith** [comment]
@electricjones this probably can help you: https://github.com/sandwwraith/KotlinSerializationPlayground 
It's a stub project with all modules defined properly.

note, if you want multiplatform library, you still have to publish artifacts from common, jvm and js modules, even if they don't contain `expect/actual` declarations.

**Comment by electricjones** [comment]
@sandwwraith That is exactly what I was hoping for. Thank you.
