### ISSUE TITLE
Support sealed interface

### ISSUE THREAD

**Issue by MEJIOMAH17** [Kotlin/kotlinx.serialization#1861]
**What is your use-case and why do you need this feature?**
Usage of sealed interface 
sealed interface IdHolder{
  val id:Long
}

class Entity:IdHolder{
   override val id:Long
}

class Request(val entity:IdHolder)

**Describe the solution you'd like**

Same with sealed class

**Comment by pdvrieze** [comment]
This is a duplicate of #1576

**Comment by MEJIOMAH17** [comment]
@pdvrieze, yes you are right. https://github.com/Kotlin/kotlinx.serialization/issues/1576 is closed now. If you reopen it, I will close this issue.

**Comment by sandwwraith** [comment]
#1576 is closed because corresponding commit is added to Kotlin master and sealed interfaces would be supported from 1.6.20-M1 and further

**Comment by MEJIOMAH17** [comment]
@sandwwraith great!
