### ISSUE TITLE
Incorrect serialization of an empty HashMap on KotlinJS

### ISSUE THREAD

**Issue by AltmanEA** [Kotlin/kotlinx.serialization#1862]
**Describe the bug**
Incorrect serialization of an empty HashMap on KotlinJS

**To Reproduce**

Main.kt:

```
fun main() {
    console.log(JSON.stringify(A()))
}
@Serializable
class A(
    val map: HashMap<Int, Int> = HashMap()
)
```

build.gradle.kts
```
plugins {
    kotlin("js") version "1.6.10"
    kotlin("plugin.serialization") version "1.6.10"
}
repositories { mavenCentral() }
dependencies{
    implementation(kotlin("stdlib-common"))
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.2")
}
kotlin {
    js(LEGACY) {
        binaries.executable()
        browser {}
    }
}
```

**Expected behavior**
{"map":{}}

**Real behavior**
{"map":{"_keys_up5z3z$_0":null,"_values_6nw1f1$_0":null,"_keys_qe2m0n$_0":null,"_values_kxdlqh$_0":null,"internalMap_uxhen5$_0":{"equality_mamlu8$_0":{},"backingMap_0":{},"size_x3bm7r$_0":0},"equality_vgh6cm$_0":{},"_entries_7ih87x$_0":null}}

**Environment**
 - Kotlin version: 1.6.10
 - Library version: 1.3.2
 - Kotlin platforms: JS
 - Gradle version: 7.1

**Comment by qwwdfsad** [comment]
`JSON.stringify` is a JS-specific API not intended to be used with Kotlin classes.

What you need is `Json.encodeToString`
