### ISSUE TITLE
A property determines the type of another property that should be deserialized  

### ISSUE THREAD

**Issue by lauglam** [Kotlin/kotlinx.serialization#1876]
I looked at the related polymorphic deserialization [documentation](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#content-based-polymorphic-deserialization)
& [Class discriminator](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#class-discriminator-for-polymorphism)

but now the situation is that I have a class with a property in it that determines the type of another property that should be deserialized and the deserialized name is the same , please advise how to do it in this case, thanks 

![image](https://user-images.githubusercontent.com/58240137/156313823-6566cc6f-c231-49ce-a342-86165098dd65.png)

TagAttributes:

![image](https://user-images.githubusercontent.com/58240137/156313585-971b92ae-bd77-451b-b9c2-65655a709acf.png)

UserAttributes:

![image](https://user-images.githubusercontent.com/58240137/156313653-e878ba8c-8444-4ca3-bc83-e76c7c79b443.png)

**Comment by sandwwraith** [comment]
Unfortunately, the only way to do this for now is to write a custom serializer for the whole `Relationship` class.
