### ISSUE TITLE
Cbor kotlinx-serialization encode increases string size rather than reducing the size

### ISSUE THREAD

**Issue by sw-tt-chunilalgamit** [Kotlin/kotlinx.serialization#1880]
Use of kotlinx-serialization CBOR encode increases string size rather than reducing the size. Is there any thing to reduce size for request response over network.

**To Reproduce**
val bytes = Cbor.encodeToByteArray(jsonStringDatat)

**Environment**
 - Ktor version: [org.jetbrains.kotlinx:kotlinx-serialization-cbor:1.3.2]

**Comment by pdvrieze** [comment]
A number of things:

- You need to be encoding the original data, not the json string. That is how serialization works.
- CBor size reduction is mainly through using binary keys and value types. This is more relevant for larger data
- Compressing the resulting binary data can still improve the size

**Comment by sandwwraith** [comment]
@pdvrieze is absolutely right. You need to encode your serializable class, not the json string. Strings aren't really compressed in CBOR.
