### ISSUE TITLE
Conflict between default constructor parameters using multiplatform expect/actual and Transient attribute

### ISSUE THREAD

**Issue by Whathecode** [Kotlin/kotlinx.serialization#189]
In a multiplatform project in which class definitions are expected and implemented as `actual` in a separate module, default values for constructor parameters may only be defined on the common `expect` definition.

When applying the `@Transient` attribute on a field defined in the primary constructor, I get the following exception:

> Transient field someField in primary constructor of serializable actual class SomeClass must have default value

However, I cannot define a default value due to the `expect` restriction. Is there any way around this?

**Comment by sandwwraith** [comment]
I didn't test it, but I think you can try to specify `@Transient` only on `expect` part of classes.

**Comment by arkivanov** [comment]
I faced the same issue and in my case I don't want to specify `@Transitent`, I only want the annotation to be applied in a specific source set. E.g. have the property serializable only on Android, and have it transient on all other source sets.

**Comment by pdvrieze** [comment]
@arkivanov While disparate semantics across different platforms were possible in older versions of the multiplatform support, this has significantly reduced in the implementation of Kotlin 2.0 and newer. The language very much wants you to use different strategies if you want inconsistent semantics.
