### ISSUE TITLE
Serialisation of interfaces doesn't work

### ISSUE THREAD

**Issue by beretis** [Kotlin/kotlinx.serialization#1891]
**Describe the bug**
When I tried **Serializing interfaces** example from docs but im getting 
`On Kotlin/Native explicitly declared serializer should be used for interfaces and enums without @Serializable annotation`
**To Reproduce**
Just run the example code from the docs.

`import kotlinx.serialization.*
import kotlinx.serialization.json.*

import kotlinx.serialization.modules.*

val module = SerializersModule {
    polymorphic(Project::class) {
        subclass(OwnedProject::class)
    }
}

val format = Json { serializersModule = module }

interface Project {
    val name: String
}

@Serializable
@SerialName("owned")
class OwnedProject(override val name: String, val owner: String) : Project

fun main() {
    val data: Project = OwnedProject("kotlinx.coroutines", "kotlin")
    println(format.encodeToString(data))
}    `

**Expected behavior**

**Environment**
 - Kotlin version: 1.6.10
 - Library version: 1.6.10
 - Kotlin platforms: Native
 - Gradle version: 7.0.0
 - IDE version: IntelliJ IDEA 2021.3.2 (Community Edition)
 - Other relevant context OS: MacOs Monterey

**Comment by aSemy** [comment]
Does this answer your question?

https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md#registered-subclasses

>Please note that this example works only on JVM because of `serializer` function restrictions.
>For JS and Native, explicit serializer should be used: `format.encodeToString(PolymorphicSerializer(Project::class), data)`
>You can keep track of this issue [here](https://github.com/Kotlin/kotlinx.serialization/issues/1077).

**Comment by beretis** [comment]
@aSemy you're right, im sorry. Thank you for reply, closing the issue :).
