### ISSUE TITLE
Are there any options to tune kotlinx.serilization in regards to object allocations?

### ISSUE THREAD

**Issue by u6f6o** [Kotlin/kotlinx.serialization#1893]
**What is your use-case?**
In the last few weeks I migrated one of our services from spring to quarkus. In the process, I also had a look on alternatives to jackson json serialization as there are still some issue when using jackson in a native image. Kotlinx.serialization looked very promising, specifically as most of the setup is done in during compile time. After integrating kotlinx.serilization, I did some load tests and the latencies looked quite nice. 

Shortly afterwards, I deployed this service on our prod environment and realised that the garbage collection memory pressure was much higher than before. Given these circumstances, I repeated my load tests and compared the impact on garbage collections before and after kotlinx.serialization was integrated: 

**Before**: 
![image](https://user-images.githubusercontent.com/1176370/161556540-d8af93ad-3c00-49d2-bcb1-0e134f650caa.png)

**After**: 
![image](https://user-images.githubusercontent.com/1176370/161556589-c08e7c38-2d88-44a8-8e0b-ccb9c95e7ed1.png)

Are there any possibility to tune kotlinx.serilization in regards to object allocations? Given the much higher garbage collection pressure, I had to stick with our current serializer for the time being.

**Comment by qwwdfsad** [comment]
Hi, we frequently do tune our performance and try to stay on par with existing solutions (though we do not talk about it much as advertising performance wins on synthetic benchmarks is rarely a good way to go) and I'm surprised to see such high memory pressure.

Could you please show the heavy hitters of your load?
The best way to do so will be to show a dump from [`async-profiler`](https://github.com/jvm-profiling-tools/async-profiler), either CPU or alloc (it's likely that it can be seen on both).

I would suspect some forgotten place like `Enum.values()` allocation or some non-trivial serializer (e.g. sealed-classes related) is not properly cached

**Comment by u6f6o** [comment]
Hi, 

Yeah, I agree, synthetic tests tend to be a bit artificial. I noticed analogue numbers on our production systems as well though. So far I did not use any custom serializers and the like, just pure data classes and relying on the quarkus integration. Here are two flame graphes (obj allocations) before and after: 

![flamegraph jackson alloc copy](https://user-images.githubusercontent.com/1176370/161561735-62505297-5aa7-4b88-9691-df592efdd55b.svg)
![flamegraph kotlinx alloc copy](https://user-images.githubusercontent.com/1176370/161561761-d0ef9a64-abdd-4e49-9b69-5351db3b1b44.svg)

**Comment by u6f6o** [comment]
Hi @qwwdfsad, Just wanted to ask if there is any progress on this topic?

**Comment by qwwdfsad** [comment]
yes, it should've been fixed in #1901

**Comment by sandwwraith** [comment]
I think so. Thank you again for your investigation and useful data!

**Comment by qwwdfsad** [comment]
@u6f6o thanks!

Could you please share both of the flamegraphs again? Or a benchmark, if that is possible.
I'm glad it helped with the overall load and the reported problem is gone, but I would like to push it further and make kotlinx-serialization faster than or being on-par with jackson

**Comment by u6f6o** [comment]
@qwwdfsad  
Sure happy to help 👍. I'll post the flame graphs as soon as I am ready (could take some days though).

**Comment by u6f6o** [comment]
@qwwdfsad: I attached a zip with the async-profiler alloc flamegraphs for kotlinx-serialization and jackson. 
 
[Flamegraphs.zip](https://github.com/Kotlin/kotlinx.serialization/files/10004509/Flamegraphs.zip)

**Comment by qwwdfsad** [comment]
Thanks!

**Comment by qwwdfsad** [comment]
We should cache char arrays in `ReaderJsonLexer`, they are definitely way too big for the unconditional allocations.
We'll improve it futher 👍

**Comment by u6f6o** [comment]
@qwwdfsad : I noticed that quite a few changes have been applied. Is there already a kotlinx.serialization version available that I could test and create benchmarks for?

**Comment by qwwdfsad** [comment]
Nope, it will arrive a bit later in 1.5.0-RC (around a week or two from now)

**Comment by u6f6o** [comment]
The latest load tests look really good. Great work 👍 

Kotlinx.serialization
![image](https://user-images.githubusercontent.com/1176370/228184909-1de23c57-a854-4d67-9ebf-c96ec6fc151a.png)

Jackson: 
![image](https://user-images.githubusercontent.com/1176370/228185261-0a4bd197-3f9c-41d2-8c1c-b939a09866ba.png)
