### ISSUE TITLE
Can`t make prettyPrint for json

### ISSUE THREAD

**Issue by arstagaev** [Kotlin/kotlinx.serialization#1898]
**Describe the bug**
I make enableprettyprint, but my output json file appear  without spaces

**To Reproduce**
```
val json = Json() {
        prettyPrint = true
    }

println(json.encodeToString(tripPath))
```
`[{"Latitude":56.352594746276736,"Longitude":37.24611712619662},{"Latitude":56.352594746276736,"Longitude":37.24611712619662},{"Latitude":56.352594746276736,"Longitude":37.24611712619662},{"Latitude":56.352594746276736,"Longitude":37.24611712619662},{"Latitude":56.352594746276736,"Longitude":37.24611712619662},{"Latitude":56.352594746276736,"Longitude":37.24611712619662},...`

**Expected behavior**
```
[
  {
    "lat": 56.352594746276736,
    "lan": 37.24611712619662
  },
  {
    "lat": 56.352594746276736,
    "lan": 37.24611712619662
  },
  {
    "lat": 56.352594746276736,
    "lan": 37.24611712619662
  },
```

**Environment**
Inteliji Idea

**Comment by qwwdfsad** [comment]
Could you please provide a complete reproducer so we can copy-and-run it?

**Comment by arstagaev** [comment]
thanks for response, haha actualy I try again launch Kotlinx Serial. instead Gson, and everything work  with pretty print :)
