### ISSUE TITLE
JS serialize default value is not defined runtime error

### ISSUE THREAD

**Issue by mvanassche** [Kotlin/kotlinx.serialization#1904]
**Describe the bug**

Serializing to JSON a class with a default value that depends on another constructor value crashes at runtime with `ReferenceError: [field] is not defined` when running on JS (it works fine on JVM)

**To Reproduce**
```
import kotlinx.serialization.Serializable
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import kotlin.test.Test

@Serializable
class Test1(val id: String, val bcm: Int, val problem: Boolean = bcm > 10)

class Test {
    @Test
    fun test1() {
        val encoded = Json.encodeToString(Test1("1", 1))
        println(encoded)
        Json.decodeFromString<Test1>(encoded)
    }
}
```

**Expected behavior**

Not crashing, same behavior for JS and JVM

**Environment**
 - Kotlin version: 1.6.20
 - Library version: 1.3.2
 - Kotlin platforms: JS
 - Gradle version: 7.3.3

**Comment by sandwwraith** [comment]
Do you use Legacy JS? I believe this bug is fixed in JS IR

**Comment by mvanassche** [comment]
Great!
`js(LEGACY)` is still the default, so yes I am using the legacy.

I will switch to IR.
Thanks.
