### ISSUE TITLE
Fatal Exception: kotlinx.serialization.MissingFieldException

### ISSUE THREAD

**Issue by walaa118** [Kotlin/kotlinx.serialization#1905]
how to parse only needed properties from API JSON no need for all properties to be parsed 

non of the following works:

Json  {
            this.coerceInputValues = true
            this.encodeDefaults = true
            this.isLenient = true
            this.ignoreUnknownKeys = true
            this.prettyPrint = true
            this.coerceInputValues = true
        }.asConverterFactory(contentType)

**Comment by sandwwraith** [comment]
`ignoreUnknownKeys = true` should work. Can you please show an example of code where it doesn't?

**Comment by walaa118** [comment]
the JSON model class as the following: may have a key that does not exist on the API JSON OR may do not have a key from JSON

just need to include needed data 

`@Serializable
data class BrokerageCustomerInfo(
    var bcid:Int?,
    var accountId: Int?,
)`

**Comment by sandwwraith** [comment]
I still don't get how exactly you deserialize json
