### ISSUE TITLE
How to create custom Serializer for PersistentList?

### ISSUE THREAD

**Issue by dennykurniawan48** [Kotlin/kotlinx.serialization#1908]
I have a list of classes and I need to save it into my datastore, probably related to issue [#635](https://github.com/Kotlin/kotlinx.serialization/issues/635).

The code is like so:
```
@Serializable
data class OrderData(
    @Serializable(with = CartData::class)
    val cartData: PersistentList<CartData> = persistentListOf()
)
```
and my subclass:
```
@Serializable
data class CartData(
    val price: double,
    val id: Int,
    val product_name: String,
    var qty: Int,
    val error: Boolean = false,
    val message: String = ""
)
```

But I got a warning when tried to serialize 

> @Serializable(with = CartData::class)

> Type mismatch.
> Required:
> KClass<out KSerializer<*>>
> Found:
> KClass<CartData>

How to solve this problem? Thanks in advance.

**Comment by dennykurniawan48** [comment]
Got It the answer is in #1114  

But get a new error:

> error: incompatible types: Class<PersistentListSerializer> cannot be converted to Class<? extends KSerializer<?>>

Possibly related to bug #685

**Comment by a1vv** [comment]
I stumbled upon the same issue, and removing the type parameter <T> from the class name and explicitly specifying a type for the rest solved it for me.
`
@Serializable
data class AppSettings(
    @Serializable(PersistentListSerializer::class)
    val favoriteApps: PersistentList<String> = persistentListOf()
)

@OptIn(ExperimentalSerializationApi::class)
@kotlinx.serialization.Serializer(forClass = PersistentList::class)
class PersistentListSerializer(private val dataSerializer: KSerializer<String>) : KSerializer<PersistentList<String>> {
    private class PersistentListDescriptor : SerialDescriptor by serialDescriptor<List<String>>() {
        @ExperimentalSerializationApi
        override val serialName: String = "kotlinx.serialization.immutable.persistentList"
    }
    override val descriptor: SerialDescriptor = PersistentListDescriptor()
    override fun serialize(encoder: Encoder, value: PersistentList<String>) {
        return ListSerializer(dataSerializer).serialize(encoder, value.toList())
    }
    override fun deserialize(decoder: Decoder): PersistentList<String> {
        return ListSerializer(dataSerializer).deserialize(decoder).toPersistentList()
    }
}`

**Comment by realityexpander** [comment]
> I stumbled upon the same issue, and removing the type parameter from the class name and explicitly specifying a type for the rest solved it for me.
> 
> ```
> @Serializable
> data class AppSettings(
>     @Serializable(PersistentListSerializer::class)
>     val favoriteApps: PersistentList<String> = persistentListOf()
> )
> 
> @OptIn(ExperimentalSerializationApi::class)
> @kotlinx.serialization.Serializer(forClass = PersistentList::class)
> class PersistentListSerializer(private val dataSerializer: KSerializer<String>) : KSerializer<PersistentList<String>> {
>     private class PersistentListDescriptor : SerialDescriptor by serialDescriptor<List<String>>() {
>         @ExperimentalSerializationApi
>         override val serialName: String = "kotlinx.serialization.immutable.persistentList"
>     }
>     override val descriptor: SerialDescriptor = PersistentListDescriptor()
>     override fun serialize(encoder: Encoder, value: PersistentList<String>) {
>         return ListSerializer(dataSerializer).serialize(encoder, value.toList())
>     }
>     override fun deserialize(decoder: Decoder): PersistentList<String> {
>         return ListSerializer(dataSerializer).deserialize(decoder).toPersistentList()
>     }
> }
> ```

So, you would have to create an individual custom serializer for each type of PersistentList, instead of using the generics?

**Comment by am3712** [comment]
So, you would have to create an individual custom serializer for each type of PersistentList, instead of using the generics?

**Comment by simonalveteg** [comment]
> So, you would have to create an individual custom serializer for each type of PersistentList, instead of using the generics?

I suppose. I just needed it for one type of Persistent List, so for me that didn't matter, but a better solution should be possible

**Comment by realityexpander** [comment]
I don’t know how to make them generic, do you?

**Comment by simonalveteg** [comment]
I don't, the code I posted is a modified version of the code in this issue:
https://github.com/Kotlin/kotlinx.serialization/issues/1114
and I remember reading this medium article when I worked on the project that needed serialization:
https://medium.com/androiddevelopers/datastore-and-kotlin-serialization-8b25bf0be66c

You've probably seen both of those links before, but I'm afraid I can't be of more help than that

**Comment by realityexpander** [comment]
Idk... from what I can see its not clear to be that kotlinx serialization supports generics.

But since I have no need for generic use case (its easy enough to make a serializer for each data class that I need in my app), Im going to end my investigations here, unless you have any better ideas?

Best,
Chris
