### ISSUE TITLE
Request： support pb3

### ISSUE THREAD

**Issue by s83sun** [Kotlin/kotlinx.serialization#1911]
**What is your use-case and why do you need this feature?**

kmm support pb3 send and receive

**Comment by qwwdfsad** [comment]
We do not currently plan to add support for more formats (see detailed explanation [here](https://github.com/Kotlin/kotlinx.serialization/issues/160#issuecomment-401008239)). However, you can write your own [custom serial format](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/formats.md#custom-formats-experimental) that we can add to the list of community-curated formats.
