### ISSUE TITLE
repeated packed ints in protobuf

### ISSUE THREAD

**Issue by fabmax** [Kotlin/kotlinx.serialization#192]
I want to deserialize repeated packed uint32 fields from protobuf. So I added a pretty dirty hack for the  [Protobuf parser](https://github.com/fabmax/kotlinx.serialization/commit/cf8f8d36b67710e58c0da1bf00672b2fbccddd44).

It works quite well, but there's another state variable (remainingSize) to count the remaining bytes of repeated int field and the way I count the number of bytes consumed by a varint is also a bit hacky. Is there any nicer way to do this?

**Comment by sandwwraith** [comment]
Hard to tell. Personally I think that packed fields are a higher level abstraction, and should be expressed somehow in `ProtobufRepeatedReader`. Decoder then should be able to give reader a current int without reading its tag and wire type beforehand.

**Comment by fabmax** [comment]
That's what I figured after diving a bit deeper into the code. Now I override readTaggedInt() and readTaggedLong() in RepeatedReader, which forward to nextRepeatedInt/Long in ProtobufDecoder. The ProtobufDecoder methods still need to evaluate the wire type in order to distinguish between packed and non-packed ints. But at least this now is done for repeated ints only:

https://github.com/fabmax/kotlinx.serialization/blob/proto_packed_ints/runtime/common/src/main/kotlin/kotlinx/serialization/protobuf/ProtoBuf.kt

My current version is also more memory-efficient by not copying bytes for nested objects, although that's a bit experimental.

**Comment by f7o** [comment]
Are there plans to support packed fields in the future natively in kotlinx?

**Comment by sandwwraith** [comment]
We should definitely implement it some day.

**Comment by pdvrieze** [comment]
I've created an implementation as #1830. It works completely (for arrays). There are probably some ways to merge the new encoder/decoder into classes such as `ProtobufRepeatedReader`. The implementation doesn't copy bytes for reading (using the existing support for sub-readers - adding an `eof` property), but does so for writing (it packed writes the size first, so writing to a temporary buffer is kind of the only option (seeking/patching cannot work as size is encoded with variable length).

**Comment by shanshin** [comment]
Implemented in https://github.com/Kotlin/kotlinx.serialization/pull/1830
