### ISSUE TITLE
Values with EncodeDefault(Mode.NEVER) annotation get serialized with `encodeDefaults = true`.

### ISSUE THREAD

**Issue by EarthyOrange** [Kotlin/kotlinx.serialization#1922]
**Describe the bug**
Values with EncodeDefault(Mode.NEVER) annotation get serialized with `encodeDefaults = true`.

**To Reproduce**
<pre>
@Serializable
data class X(val a: Int, val b: Int)

@Serializable
data class Y(
  @EncodeDefault(Mode.NEVER) val xArray: List< Y> = emptyList(),
)

val json = Json { encodeDefaults = true }
json.encodeToString(Y())
</pre>

**Actual output**
`{"xArray": []}`

**Expected output**
`{}`

**Environment**
 - Kotlin version: 1.5.10
 - Library version: 1.3.2
 - Kotlin platforms: JVM
 - Gradle version: 7.2
 - IDE version: Android Studio Bumblebee | 2021.1.1 Patch 2
 - Other relevant context [e.g. OS version, JRE version, ... ]

**Comment by sandwwraith** [comment]
Support for `@EncodeDefault` was added only in serialization plugin only in 1.5.30. Therefore, you need to update Kotlin at least to this version
