### ISSUE TITLE
SerialInfo Annotation: getElementAnnotation(index) is empty

### ISSUE THREAD

**Issue by hfhbd** [Kotlin/kotlinx.serialization#1923]
**Describe the bug**
I want to get the value from the element annotation for a specific element during encoding inside a custom Encoder.

**To Reproduce**
```kt
import kotlinx.serialization.*

@ExperimentalSerializationApi
fun main() {
    print(Sample.serializer().descriptor.getElementAnnotations(0).filterIsInstance<Foo>().single().foo)
}

@ExperimentalSerializationApi
@SerialInfo
annotation class Foo(val foo: Int)

@ExperimentalSerializationApi
@Serializable
data class Sample(
    @Foo(42)
    val data: Int
)
```
`java.util.NoSuchElementException: List is empty.` from `single()`

[reproducer.zip](https://github.com/Kotlin/kotlinx.serialization/files/8618669/untitled2.zip)

**Expected behavior**

`42`

**Environment**
 - Kotlin version: 1.6.21
 - Library version: 1.3.2
 - Kotlin platforms: JVM
 - Gradle version: 7.4.2

**Comment by sandwwraith** [comment]
Unfortunately, it is really not documented anywhere, but default target for annotations in Kotlin are fields, and serial info annotations should target properties. To fix this, add explicit target to your Foo:

```kotlin
@SerialInfo
@Target(AnnotationTarget.PROPERTY)
annotation class Foo(val foo: Int)
```

**Comment by hfhbd** [comment]
Thank you! 
Explicit adding the target works. But why is it necessary? According to the docs, the annotation is applicable to `PROPERTY`.

```
If the target meta-annotation is not present on an annotation declaration, the annotation is applicable to the following elements: CLASS, PROPERTY, FIELD, LOCAL_VARIABLE, VALUE_PARAMETER, CONSTRUCTOR, FUNCTION, PROPERTY_GETTER, PROPERTY_SETTER.
```

**Comment by sandwwraith** [comment]
I think it is due to [this](https://kotlinlang.org/docs/annotations.html#java-annotations): 

```
If you don't specify a use-site target, the target is chosen according to the @Target annotation of the annotation being used. If there are multiple applicable targets, the first applicable target from the following list is used:

- param

- property

- field
```

Param has a higher priority than a property, so `@Foo` is applied to a constructor parameter `foo`, not the `val foo` property (despite they're the same thing)
