### ISSUE TITLE
how to use serialization in common platform using (apply plugin: 'kotlin-platform-common')?  

### ISSUE THREAD

**Issue by sunilmishra** [Kotlin/kotlinx.serialization#193]

**Comment by JakeWharton** [comment]
What have you tried? It kinda just works.

**Comment by sandwwraith** [comment]
Probably #180. `apply plugin: 'kotlinx-serialization'` should be in each module.

**Comment by sunilmishra** [comment]
@JakeWharton @sandwwraith 
This is my common module (build.gradle) 

`buildscript {
    repositories {
        maven { url 'https://plugins.gradle.org/m2/' }
        maven { url "https://kotlin.bintray.com/kotlinx" }
        jcenter()
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlinx:kotlinx-gradle-serialization-plugin:$serialization_version"
    }
}

repositories {
    maven { url 'https://kotlin.bintray.com/kotlinx' }
    maven { url 'https://dl.bintray.com/kotlin/ktor' }
    jcenter()
}

apply plugin: 'kotlin-platform-common'
apply plugin: 'kotlinx-serialization'

sourceSets {
    main.kotlin.srcDir 'src'
}

dependencies {
    implementation 'org.jetbrains.kotlin:kotlin-stdlib-common'
    testCompile 'org.jetbrains.kotlin:kotlin-test-annotations-common'
    testCompile 'org.jetbrains.kotlin:kotlin-test-common'

   implementation 'io.ktor:ktor-client:0.9.4-alpha-2'
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:$serialization_version"
}
kotlin.experimental.coroutines 'enable'`

Error Message: Could not find org.jetbrains.kotlinx:kotlinx-gradle-serialization-plugin:'0.6.1'.
     Searched in the following locations:


Without using serialization plugin, being able to make network request(using KTOR) and get response successfully. 
Trying to parse those responses using Serialization libraries, Hence the Android/IOS projects can directly use my Model/DTO classes.

**Comment by sandwwraith** [comment]
I'd rather say you've specified invalid version string? `'0.6.1'` instead of just `0.6.1`. Don't know how you've did it.

**Comment by sunilmishra** [comment]
Thank you!, Now able to build for Android following  #180.

BUT for IOS:
ios:compileDebugIos_arm64KotlinNative
 error: cannot access 'Serializable': it is internal in 'kotlin.io'
@Serializable

Getting same above error even tried using implementation "org.jetbrains.kotlinx:jsonparser-native:0.6.1"

**Comment by sandwwraith** [comment]
`@Serializable` is not available on Kotlin/Native yet.

**Comment by xavierliancw** [comment]
@sandwwraith , is @Serializable still not available on Kotlin/Native yet?
