### ISSUE TITLE
Non-reified type parameters with recursive bounds are not supported yet: T

### ISSUE THREAD

**Issue by Trqhxrd** [Kotlin/kotlinx.serialization#1932]
**Describe the bug**
I don't really know if it's a bug... I just don't know what it means or how to get around it...
I have a generic class and try to serialize it from a method inside the class. When I try to compile the project I get the error `Non-reified type parameters with recursive bounds are not supported yet: T` with a link to a line, that reads like this: ´override fun save() = Json.encodeToString(this)´

**To Reproduce**
Attach a code snippet or test data if possible.

**Expected behavior**
```kotlin
@Serializable
@SerialName("BlockData")
abstract class BlockData<T : BlockData<T>>(override val id: ModuleKey) : BlockDataAPI<T> {
    override fun save() = Json.encodeToString(this)
}
```

**Environment**
 - Kotlin version: 1.6.21 (JDK 18)
 - Library version: 1.3.2
 - Kotlin platforms: JVM
 - Gradle version: 7.3.3
 - Other relevant context: Linux 5.17.5-arch1-1

**Comment by sandwwraith** [comment]
`Json.encodeToString` has reified type argument, and practically it means that you have to know in advance the exact argument. `this` has the type `BlockData<T : BlockData<T>>`, and T is unknown. Kotlin compiler therefore can't use it as a reified argument for `typeOf` (https://youtrack.jetbrains.com/issue/KT-40173)
