### ISSUE TITLE
fileSerializer not properly recognized by IntelliJ

### ISSUE THREAD

**Issue by Ademord** [Kotlin/kotlinx.serialization#1933]
I have a class that looks like this

```kotlin
@file:UseSerializers(BigDecimalSerializer::class, LocalDateSerializer::class)

@Serializable 
data class MyRecordKeeper(val records: Map<LocalDate, BigDecimal>)
```
with
```kotlin
// FIXME
// compiler gives error when this class is not in business
// other serializers (BigDecimalSerializer) can stay in technical
// https://youtrack.jetbrains.com/issue/KT-44417

object LocalDateSerializer : KSerializer<LocalDate> {
    override val descriptor = PrimitiveSerialDescriptor("LocalDate", PrimitiveKind.STRING)

    override fun deserialize(decoder: Decoder): LocalDate {
        return LocalDate.parse(decoder.decodeString())
    }

    override fun serialize(encoder: Encoder, value: LocalDate) {
        encoder.encodeString(value.toString())
    }
}
```
and
```kotlin
object BigDecimalSerializer : KSerializer<BigDecimal> {
    override val descriptor = PrimitiveSerialDescriptor("BigDecimal", PrimitiveKind.STRING)

    override fun deserialize(decoder: Decoder): BigDecimal {
        return decoder.decodeString().toBigDecimal()
    }

    override fun serialize(encoder: Encoder, value: BigDecimal) {
        encoder.encodeString(value.toPlainString())
    }
}
```

for some reason I get the error:
<img width="738" alt="image" src="https://user-images.githubusercontent.com/4501464/167843362-0864c84c-6e2b-4c53-9ffb-3cd8d6628972.png">

**Side notes & Qs:**
- the serializers are in a different modules (imagine module1 "business", module2 "technical")
- to add to my confusion IntelliJ is giving me an error only for LocalDate and not for BigDecimal. But when I move the LocalDateSerializer to the `business` module, the error is gone.
- conclusion: building the project works but its the editor that shows there is an error only for this one serializer. what can one do so that LocalDate is not underlined as error and future developers dont think there is something wrong?

**Comment by sandwwraith** [comment]
Does error go away if you annotate `LocalDate` explicitly? Like `Map<@Serializable(LocalDateSerializer::class) LocalDate, BigDecimal>`?

**Comment by fzhinkin** [comment]
The problem is not reproducible with latest Kotlin and serialization versions.
