### ISSUE TITLE
Serializer expects discriminator to decode but does not incluide when encoding

### ISSUE THREAD

**Issue by JonoAugustine** [Kotlin/kotlinx.serialization#1936]
My polymorphic serializer expects a class discriminator when decoding, but does not include one when encoding.

I have a multi-module project with a client, server, and common modules. In `common`, the Json module is defined for the sealed class `Action` like this:

```kotlin
val jsonConfig = Json {
    prettyPrint = true
    ignoreUnknownKeys = true
    encodeDefaults = true
    serializersModule = SerializersModule {
        polymorphic(Action::class) {
            subclass(CreateMatch::class)
            subclass(Start::class)
            //etc
        }
}
```

Using `jsonConfig.encodeToString(Start())` will produce a string `{ "match": { ... } }` with no class discriminator, which afaik is the expected behavior for sealed classes (closed polymorphism). The problem arises when trying to decode from string, where `jsonConfig.decodeFromString<Action>(string)` will throw an exception regarding the missing discriminator:

```
Exception in thread "main" kotlinx.serialization.json.internal.JsonDecodingException: Polymorphic serializer was not found for missing class discriminator ('null')
JSON input: {"player":{"id":"ab2b1b63-6c4e","matchID":null,"name":"ab2b1b63-6c4e"}}
```

Aside from using open polymorphism and forcing the encoder to include a discriminator, what are some solutions to this issue?

Thanks in advance

**Comment by sandwwraith** [comment]
That's the common polymorphism pitfall. From the [docs](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md#sealed-classes):

>  When serializing polymorphic class hierarchies you must ensure that the compile-time type of the serialized object is a polymorphic one, not a concrete one.

To solve your problem, try to do the following: `jsonConfig.encodeToString<Action>(Start())`

Also see: #1194, #1247

**Comment by qwwdfsad** [comment]
>That's the common polymorphism pitfall. 

Maybe it's time to design/introduce the corresponding inspection?

**Comment by sandwwraith** [comment]
@qwwdfsad I doubt it's possible. Better to implement #1247
