### ISSUE TITLE
JVM compiler error after upgrading to 1.6.21

### ISSUE THREAD

**Issue by Whathecode** [Kotlin/kotlinx.serialization#1943]
**Describe the bug**
I'm trying to upgrade a project from Kotlin 1.6.10 and serialization 1.3.2 to Kotlin 1.6.21 and serialization 1.3.3. [Compilation fails when trying to upgrade](https://github.com/imotions/carp.core-kotlin/pull/387).

**To Reproduce**
You can check out the project [for which compilation is failing](https://github.com/imotions/carp.core-kotlin/runs/6556653849?check_suite_focus=true).

```
e: org.jetbrains.kotlin.backend.common.BackendException: Backend Internal error: Exception during IR lowering

File being compiled: /home/runner/work/carp.core-kotlin/carp.core-kotlin/carp.protocols.core/src/commonMain/kotlin/dk/cachet/carp/protocols/application/StudyProtocolSnapshot.kt
> Task :carp.protocols.core:compileKotlinJvm FAILED
The root cause java.lang.RuntimeException was thrown at: org.jetbrains.kotlin.backend.jvm.codegen.FunctionCodegen.generate(FunctionCodegen.kt:50)
	at org.jetbrains.kotlin.backend.common.CodegenUtil.reportBackendException(CodegenUtil.kt:238)

...

Caused by: java.lang.RuntimeException: Exception while generating code for:
FUN name:write$Self visibility:public modality:FINAL <> (self:dk.cachet.carp.protocols.application.StudyProtocolSnapshot, output:kotlinx.serialization.encoding.CompositeEncoder, serialDesc:kotlinx.serialization.descriptors.SerialDescriptor) returnType:kotlin.Unit
  annotations:
    JvmStatic

...
```

I'm currently trying to pinpoint the exact issue. [Maybe a regression](https://github.com/Kotlin/kotlinx.serialization/issues/1770)? In the meantime, I hope the open-source project can already be of some help in identifying the issue.

**Expected behavior**
Compilation to succeed, similar to how it did on Kotlin 1.6.10 and serialization 1.3.2.

**Environment**
 - Kotlin version: 1.6.21
 - Library version: 1.3.3
 - Kotlin platforms: JVM
 - Gradle version: 7.4

**Comment by sandwwraith** [comment]
That's the same error as in #1692
