### ISSUE TITLE
SerialInfo annotation: Default parameters in custom annotation cause compiler exception

### ISSUE THREAD

**Issue by slava110** [Kotlin/kotlinx.serialization#1956]
**Describe the bug**
I'm using custom annotation `@YamlComment` annotated with `@SerialInfo`. If `@YamlComment` annotation contains default parameters compiler will throw an [error](https://gist.github.com/slava110/5fbd17b290e390815ef496571d2c2ddc)

**To Reproduce**
```kotlin
@Target(AnnotationTarget.PROPERTY)
@SerialInfo
public annotation class YamlComment(
    val comment: String,
    val trimIndent: Boolean = false // Throws an error
)
```

**Environment**
 - Kotlin version: 1.6.21
 - Library version: Plugin: 1.6.21, SerializationCore: 1.3.3
 - Kotlin platforms: JVM
 - Gradle version: 7.4.2
 - Other relevant context: JDK 8 is used for project code, JDK 11 is used for Gradle

**Comment by ProVir** [comment]
Hi!

As I understand it, default parameters are still not supported?
I have such a case - it does not collect with caches and strange problems in Kotlin/Native

https://youtrack.jetbrains.com/issue/KT-53475/KotlinNative-for-iOS-IllegalArgumentException-Sequence-has-more-than-one-element
