### ISSUE TITLE
Best approach for parametrized enum serializtion

### ISSUE THREAD

**Issue by fistuk** [Kotlin/kotlinx.serialization#196]
In my case, I have a lot of the following enums:
```
enum class Enum(val value: Int) {
    ONE(Int),
    TWO(Int),
    THREE(Int),
    ...
}
```

For example:
```
@Serializable
enum class Buttons(val value: Int)  {
    ONE(-1),
    TWO(0),
    THREE(1);

    @Serializer(forClass = Buttons::class)
    companion object : KSerializer<Buttons> {
        override val serialClassDesc: KSerialClassDesc
            get() = TODO("not implemented")

        override fun save(output: KOutput, obj: Buttons) {
            output.writeIntValue(obj.value)
        }

        override fun load(input: KInput): Buttons {
            return Buttons.values().first {
                it.value == input.readIntValue()
            }
        }
    }
}
```
The code above is not working as stated here: #5. For now my solution is to write a custom "object EnumSerializer" for each enum and use it with "@Serializable(with = EnumSerializer::class)" when needed. Is there a better approach to serialize parametrized enums?

**Comment by sandwwraith** [comment]
Not for now. In observable future, we're gonna develop mechanism to override serializers for particular type in whole class or source file.

**Comment by itome** [comment]
@fistuk I'm trying to deserialize Enum with custom serializer but I get
```kotlinx.serialization.json.JsonParsingException: Invalid JSON at 213: Expected string or non-null literal```
Can you show me your EnumSerializer ?

**Comment by ankushg** [comment]
@sandwwraith Is this sort of thing still unsupported?

**Comment by sandwwraith** [comment]
@ankushg what kind of thing? For custom enum serializers you can look at this discussion: https://github.com/Kotlin/kotlinx.serialization/issues/31. Overriding serializers at file-level is now supported with `@UseSerializers` annotation.
