### ISSUE TITLE
`@SerialInfo` is broken for annotations accepting a `KClass`

### ISSUE THREAD

**Issue by vnermolaev** [Kotlin/kotlinx.serialization#1984]
Annotations annotated with `@SerialInfo` may not contain `KClass`-s as values.

**To Reproduce**
```kotlin
class MyClass

@SerialInfo
@Target(AnnotationTarget.CLASS)
annotation class Ann(val klass: KClass<*>)

@Serializable
@Ann(MyClass::class)
data class Container(
    val i: Int
)
```

produces the following error
```bash
e: .../src/main/kotlin/Main.kt: (10, 18): Accidental override: The following declarations have the same JVM signature (klass()Lkotlin/reflect/KClass;):
    fun <get-klass>(): KClass<*> defined in Ann.Impl
    fun klass(): KClass<*> defined in Ann.Impl
```

**Expected behavior**
This must be OK, unless I am missing something in the [documentation](https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-core/kotlinx.serialization/-serial-info/).

**Environment**
 - Kotlin version: 1.5.31
 - Library version: 1.3.3

**Comment by aSemy** [comment]
You're correct, this is a bug https://github.com/Kotlin/kotlinx.serialization/issues/1672
