### ISSUE TITLE
Update builtin-classes.md to mention Duration

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.serialization#1986]
After release with our Duration support and Kotlin 1.7.20: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/builtin-classes.md

**Comment by ihostage** [comment]
@qwwdfsad #1988 was merged, so can be close now? 🤔

**Comment by sandwwraith** [comment]
It will be closed automatically when corresponding commit hits `master` branch. Currently it's still in `dev`
