### ISSUE TITLE
Add support for unsigned numbers arrays

### ISSUE THREAD

**Issue by osipxd** [Kotlin/kotlinx.serialization#1989]
**What is your use-case and why do you need this feature?**

Use-cases for `U[X]Array`, are similar as for `[X]Array`.

**Describe the solution you'd like**

Add serializers for `UByteArray`, `UShortArray`, `UIntArray` and `ULongArray`.

```kotlin
val bytes = Json.decodeFromString<UByteArray>("[0, 127, 255]")
prtintln(bytes.contentToString()) // [0, 127, 255]
```

**Comment by osipxd** [comment]
I can try to implement this feature myself if it is needed

**Comment by shanshin** [comment]
@osipxd, thanks for the offer, but this improvement requires changing not only the serialization runtime, but also the plugin.
The feature will be available after several Kotlin releases.
