### ISSUE TITLE
Serializer for identifiers

### ISSUE THREAD

**Issue by CLOVIS-AI** [Kotlin/kotlinx.serialization#1998]
**What is your use-case and why do you need this feature?**

My project is currently organized into model classes and API classes.
- Domain classes have validation logic (in their `init` block)
- Domain classes have references to other domain classes
- API classes do not have validation logic
- API classes have fields which stores identifiers instead of storing references (API data is not recursive)

This causes the following problems:
- Necessity to copy all classes with these minor differences
- API classes do not validate themselves automatically upon deserialization (they need to be converted to domain classes)
- Converting between both classes is painful

**Describe the solution you'd like**

When writing a class like this:
```kotlin
@Serializable
data class Foo(
    val id: String,
    val name: String,
    val foo: Foo? = null,
) {
    init {
        require(name.isNotBlank()) { "The 'name' cannot be blank: $name" }
    }
}
```

Ideally, I'd like to be able to configure KotlinX.Serialization, either via annotations or via configuration when creating the `Json` object, that this class should be serialized to:

```json
{
    "id": "...",
    "name": "...",
    "foo": "<the ID here, as a String>"
}
```

When deserializing, KotlinX.Serialization should call the (suspend!) function that de-references the identifier to a proper object.

**Current state**

I think the first half is doable using [surrogates](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#composite-serializer-via-surrogate)?

Maybe the second part can be done with the [serializer module](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#serializers-module)?

Reading the documentation, it seems to me like this is possible, but I don't really understand what needs to be done for it to work.

**Comment by pdvrieze** [comment]
@CLOVIS-AI I would say that surrogates are the approach to do this (it is what I do). You may be able to it with pure data surrogates. In many ways the surrogates and API classes would be the same/similar, but you could limit the visibility of the surrogates (either private in the same file or using the optin mechanism.

The reality of resolving ids is that this needs to be done on the container, probably when all items with ids have been read (be aware of circular references - even if they are not supposed to happen you don't want them to hang/crash your system). As such you would have a surrogate for your container. That surrogate would then have "surrogates" for the data elements directly. Once the container surrogate is complete you use that to create the container proper. The elements in the container themselves can still be serializable, but don't even need to be.

**Comment by sandwwraith** [comment]
Isn't custom serializer for `Foo` is enough?

**Comment by pdvrieze** [comment]
> Isn't custom serializer for `Foo` enough?

Probably, but there are nodes inside `Foo` that should have references to other nodes (not nested, more like XML's `ID`/`IDREF`). As such there needs to be a difference between the deserialization and the domain class for that node. The serialization classes for the domain class can be generated and private (converted to the domain classes directed by the serializer for `Foo`).

**Comment by CLOVIS-AI** [comment]
I see. I don't really like the need to have all classes be written twice though.

**Comment by CLOVIS-AI** [comment]
I'm trying to make sense of "Contextual serialization and generic classes".

```kotlin
val correctModule = SerializersModule {
    // args[0] contains Int.serializer() or String.serializer(), depending on the usage
    contextual(Box::class) { args -> BoxSerializer(args[0]) } 
}
```

What does that mean? What does the list represent?

When I try to use it locally, the list is empty, what does that mean?

**Comment by pdvrieze** [comment]
> I see. I don't really like the need to have all classes be written twice though.

One of the reasons is that kotlinx.serialization is designed to "assume" immutable datatypes, in combination with non-nullable types. This means that patching up structures once a pending id has been found isn't something supported in a straightforward way.

If you have a more complex idref datatype you could possibly have a postprocessing step in the constructor of the container that forces these to be resolved, and use getters to hide the abstraction from callers.

**Comment by CLOVIS-AI** [comment]
My goal was to have the validation code in `init` because users forget any post-processing step necessary.

In the end what I did is create a custom serializer for a reference type and use the contextual annotations to manage the exact implementation.
