### ISSUE TITLE
Serialization of overriden fields

### ISSUE THREAD

**Issue by pseusys** [Kotlin/kotlinx.serialization#2000]
As far as I know, classes of following structure can not be serialized currently:
```kotlin
@Serializable
open class Project {
    open var name: String = "project"
}

@Serializable
class OwnedProject(val owner: String) : Project() {
    override var name: String = "ownedProject"
}
```
At least for me it produces `Serializable class has duplicate serial name of property 'name', either in the class itself or its supertypes` exception.

Adding support for this feature could help in case of different default values for parent and child properties.

**Comment by sandwwraith** [comment]
It's not currently supported because these properties are actually two different ones: 

> The problem with open vars is that if you override them, you get two backing fields: in the parent and in the subclass (and subclass can't access parent field!). Depending on what exact runtime type you serialize, you serialize different fields, and since we traverse all hierarchy (including private fields), we end up having two same json properties.

https://github.com/Kotlin/kotlinx.serialization/issues/427#issuecomment-939982702
