### ISSUE TITLE
how to add JsonContentPolymorphicSerializer

### ISSUE THREAD

**Issue by periva101** [Kotlin/kotlinx.serialization#2002]
**I want to add ProjectSerializer to the ktor json without the annotation  **
```
object ProjectSerializer : JsonContentPolymorphicSerializer<Project>(Project::class) {
    override fun selectDeserializer(element: JsonElement) = when {
        "owner" in element.jsonObject -> OwnedProject.serializer()
        else -> BasicProject.serializer()
    }
}
```
**I want to add JsonContentPolymorphicSerializer to the json**
```
fun createJson() = Json {
    encodeDefaults = false
    isLenient = true;
    ignoreUnknownKeys = true
    prettyPrint = true

    serializersModule = SerializersModule {
     
    }
```

}

**Comment by sandwwraith** [comment]
See https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#specifying-serializer-on-a-property

**Comment by periva101** [comment]
@sandwwraith , I want to specify the serializer on the JSON object kotlinx.serialization.json not on the accnoation

**Comment by periva101** [comment]
@sandwwraith

**Comment by sandwwraith** [comment]
Sorry, I don't get your idea. Why you don't want to use the annotation? 
If you want to override some serializer using `SerializersModule`, you still need to specify `@Contextual` in the proper places: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#contextual-serialization

**Comment by periva101** [comment]
thank you, because I use the open-API generator , I do not have a control over the annotation .
