### ISSUE TITLE
Cannot use custom DurationSerializer nor library DurationSerializer

### ISSUE THREAD

**Issue by sigma-libra** [Kotlin/kotlinx.serialization#2021]
**Describe the bug**

Upgrading from kotlinx.serialization:1.3.2 (where I used a custom DurationSerializer) to 1.4.0.

Libraries involved: 
```
kotlin("jvm")
kotlin("plugin.serialization") version "1.7.10"    
implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.3.2") -> 1.4.0
```

Before removing my custom serializer:
`For serial name Duration there already exist DurationSerializer`

After removing my custom serializer, cleaning, and rebuilding:
`Serializer has not been found for type 'Duration'`

**To Reproduce**
```
import kotlin.time.Duration
import kotlinx.serialization.Serializable

@Serializable
data class MyDurationEnvelope(
  val myDuration: Duration,
)
```

**Expected behavior**

New `DurationSerializer` object should be used to serialize `myDuration` object.

**Environment**
 - Kotlin version:1.7.10
 - Library version: 1.4.0
 - Kotlin platforms: JVM
 - Gradle version: 7.1.1
 - IDE version (if bug is related to the IDE) IntelliJ IDEA 2022.2.1

**Comment by shanshin** [comment]
Hi,
could you clarify, you create your custom serializer like this?
```
internal object MyDurationSerializer : KSerializer<kotlin.time.Duration> {
    override val descriptor: SerialDescriptor =
        PrimitiveSerialDescriptor("Duration", PrimitiveKind.STRING)
```
if so, try to change the serial name in descriptor to something other than `"Duration"` and `"kotlin.Duration"`.

Full support for the `kotlin.time.Duration` type will be added to the compiler version `1.7.20`

**Comment by sigma-libra** [comment]
Our serial name was "kotlin.time.Duration". Once we changed that to "CustomerDurationSerializer" it worked. 
Thank you for your help, and we will keep an eye out for the compiler update.
