### ISSUE TITLE
Class 'SomeClass' is not registered for polymorphic serialization in the scope of 'Any'.

### ISSUE THREAD

**Issue by zhimbura** [Kotlin/kotlinx.serialization#2032]
Unexpected behavior, object can't be serializing with sealed type

Why after cast to Response<Result> I'm getting "Class 'Result1' is not registered for polymorphic serialization in the scope of 'Any'."

**To Reproduce**

Run attached code

**Expected behavior**

Success serializing

**Environment**
- Kotlin version: JVM 1.7.10
- Library version: io.ktor:ktor-serialization-kotlinx-json:2.1.0
- Kotlin platforms: JVM
- Gradle version: 7.4
- Java: 18

```kotlin
package test

import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import org.junit.Test

class SealedGenericClassesTest {
    @Serializable
    sealed class Result {
        @Serializable
        data class Result1(val s: String) : Result()
    }

    @Serializable
    sealed class Response<T> {
        abstract val result: T?

        @Serializable
        class Success<T>(override val result: T) : Response<T>()
    }

    // Test should be success serializing with serializable generic
    @Test
    fun testSerializableWithSerializer() {
        val result = Result.Result1("test")
        val response = Response.Success(result as Result)
        // Success
        Json {}.encodeToString(response)

        // fail "Class 'Result1' is not registered for polymorphic serialization in the scope of 'Any'."
        Json {}.encodeToString(response as Response<Result>)
    }
}
```

**Comment by sandwwraith** [comment]
This is correct behavior. See, in `Success<T>` T is an unbound type parameter — it means its upper bound is `Any`, so any type can be there, not only the `Result`. Thus, polymorphic serialization is enabled which gives this error. 

If you want it to be polymorphic, consult documentation on polymorphism for how to register serializers in correct scope.
Otherwise, just add the upper bound to T: `T: Result`

**Comment by Tihon-Ustinov** [comment]
> This is correct behavior. See, in `Success<T>` T is an unbound type parameter — it means its upper bound is `Any`, so any type can be there, not only the `Result`. Thus, polymorphic serialization is enabled which gives this error.
> 
> If you want it to be polymorphic, consult documentation on polymorphism for how to register serializers in correct scope. Otherwise, just add the upper bound to T: `T: Result`

I now that T is Any, but still 
result: Response.Success<Result> -> success serialized
result: Response<Result> -> fail 

There are both generic type have one type, then why is first correct and isn't second correct?

**Comment by pdvrieze** [comment]
That is a weird one indeed. Both are statically known as being of type `Success<Result>` but the first one is determined by inference of the type for `response`, where the second one is determined through casting. Both should create/use a serializer for `Response` that has the serializer for (sealed) `Result` as parameter, not a generic PolymorphicSerializer on the upper bound of `T`.
