### ISSUE TITLE
Consider using `String::intern` when deserializing strings (K/JVM)

### ISSUE THREAD

**Issue by SerVB** [Kotlin/kotlinx.serialization#2036]
**What is your use-case and why do you need this feature?**

Sometimes we have a lot of equal strings in incoming data like JSONs that we deserialize to Kotlin/JVM objects. However, the current kx.serialization implementation creates separate objects for such strings (which, for example, results in not-so-optimal RAM usage).

Examples:

```kotlin
@Serializable
data class Data(val m: Map<String, String>)

val ser = Data.serializer()
val s = "abcdef".repeat(1050)
val original = Data(mapOf(s to s))
println(original.m.toList().first().first === original.m.toList().first().second)  // prints true! (same key and value in the original data?)
val data = Json.Default.encodeToString(ser, original)
val decoded = Json.Default.decodeFromString(ser, data)
println(decoded.m.toList().first().first === original.m.toList().first().first)  // prints false! (same keys in the original and the decoded data?)
println(decoded.m.toList().first().first === decoded.m.toList().first().second)  // prints false! (same key and value in the decoded data?)

// other cases are equal strings in any other places, like in a list, in different lists, in different maps or objects and so on
```

**Describe the solution you'd like**

Internally in kx.serialization, before returning strings to the user code after deserialization, the [`.intern()`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#intern()) method could be used. This would make previous examples return `true` and reduce the amount of memory used (as well as improve the comparison performance if those strings are used in any comparison). This can be checked by adding `.intern()` calls in the example code.

I guess the current solution for this on the user side is to create a custom String serializer that just calls `.intern()` before returning a string, but I see this as a useful change for all kx.serialization users, so I think it could be implemented from the framework side by default.

**Comment by JakeWharton** [comment]
> reduce the amount of memory used

But this isn't free. You reduce the amount of memory used for this specific case at the expense of caching those strings forever. Therefore you are increasing the memory used over the lifetime of the process.

**Comment by SerVB** [comment]
> the expense of caching those strings forever. Therefore you are increasing the memory used over the lifetime of the process.

I understand this isn't free but aren't unused strings cleared out of that cache during gc?

> But in such scenarios, kotlinx.serialization is not an answer -- the logic should either be in class' constructors or even in setters on the postprocessing phase after the deserialization.

Good to hear it was already considered in jackson.

Having the logic the ways you describe (on the user side) will significantly increase the user code base with similar boilerplate code, I think.

Probably if not making interning as the default behavior, it could be done via a setting of kotlinx.serialization – a way of deduplicating deserialized values – and actually, it can be generalized not only for strings then?

**Comment by qwwdfsad** [comment]
>I understand this isn't free but aren't unused strings cleared out of that cache during gc?

They do, and it affects pause times and GC performance in unpredictable ways. I.e. AFAIR G1 treats string table as old gen root, meaning that it's rarely collected. STW young gen collectors used to treat it as part of the root set, introducing a significant STW pause increase. 

Keys interning and, especially, **values** interning you are proposing will **definitely** introduce a non-trivial performance degradation. Not to mention that `String.intern` is far from being reasonably fast on itself.

>will significantly increase the user code base with similar boilerplate code, I think.

That's what libraries are for :) But I would like to highlight that interning is a subtle matter without "one-size-fits-all" solution, thus I'm against making it a non-granular feature of any serialization framework.
And adding a complex layer of configuration (eviction, timeouts, cache size, class/field-basis etc.) for the sake of a dozen users is unlikely worth it.

>actually, it can be generalized not only for strings then?

Rephrasing my previous statement, interning is a subtle and domain-specific topic. Introducing a generic, non-use-case-driven API surface won't do any good in the long term.
The final solution should both be driven by the reasonable number of requests for such functionality, as well as backed with real data that the interning does more good than harm

**Comment by ben-manes** [comment]
FYI: As hinted to, caffeine/guava both offer a [weak interner](https://github.com/ben-manes/caffeine/wiki/Interner) for these use cases. That is a weak reference cache by equality (whereas user built weak caches are by identity).

**Comment by qwwdfsad** [comment]
Closing as "won't fix"

**Comment by sandwwraith** [comment]
I can note that, in fact, this feature request was rather about string deduplication. `String.intern()` is not the correct way to do it, but we may consider others in the future.

**Comment by VladRassokhin** [comment]
I'd appreciate something as simple as accepting additional argument of type `(String) -> String` so one could use:
```
    val cache = HashMap<String, String>()
    val intern: (String) -> String = { s -> cache.getOrPut(s) { s } }
    ...
    Json.decodeFromStream<T>(it, intern)
```
