### ISSUE TITLE
Support I/O stream

### ISSUE THREAD

**Issue by chenfei0928** [Kotlin/kotlinx.serialization#204]
If I deserialize  a json from file system, deserialize method require me full read the file to a string.
Can it support read and write json content from I/O stream, like Gson done?

**Comment by sandwwraith** [comment]
We are planning migration to kotlin multiplatform IO library – https://github.com/Kotlin/kotlinx-io . JSON parser would support both strings and kotlinx.io inputs.

**Comment by gajicm93** [comment]
This is quite a bummer because I know for a fact that Android can crash when a very large JSON payload is converted to a String at once.

When can we expect a streaming parse? Thanks.

**Comment by jcraane** [comment]
We indeed face this issue when per persist large json (the apps data) which sometimes triggers OutOfMemory.

**Comment by sdeleuze** [comment]
We are interested by that one for Spring Framework support, beware that for Spring MVC we typically deal with `InputStream` / `OutputStream` while on Spring WebFlux side we typically deal with `java.nio.ByteBuffer`, potentially in combination with the upcoming JSON streaming support (#1073).

**Comment by epicstar** [comment]
> This is quite a bummer because I know for a fact that Android can crash when a very large JSON payload is converted to a String at once.

Yes, this should be considered a stopper for all Android applications.

**Comment by mobiletoly** [comment]
Any news or roadmap?

**Comment by sandwwraith** [comment]
It's planned for 1.1 or 1.2

**Comment by ln-12** [comment]
Seems like the feature didn't make into 1.1.0-RC. Currently, it's the only reason why I would not feel confident shipping it in a production app.

**Comment by cherryleafroad** [comment]
Really sad, I was looking forward to this being supported

**Comment by sdeleuze** [comment]
Could you please add support for that in 1.2 in order to allow Spring to use it in Spring Boot 2.5 ?

**Comment by slavonnet** [comment]
+100500 votes! How read big

**Comment by chris-hatton** [comment]
I'm developing an application with `kotlinx.serialization` and came to a point where I really want to implement a `Flow<T>` of objects from Server to Client.  It seems unfeasible to do this at the moment due to lack of stream processing support with `kotlinx.serialization`.  This is the biggest weakness I can see with this otherwise great library...

**Comment by chris-hatton** [comment]
If `kotlinx.io` has been put on hold; could maintaining developers of `kotlinx.serialization` consider a separate effort to expose a streaming API?  I have seen suggestions that parsing is modelled around a stream internally, but for some reason this isn't exposed.

**Comment by sandwwraith** [comment]
> I have seen suggestions that parsing is modelled around a stream internally 

that (wasn't) true

We currently have progress on working implementation over Java's InputStream/OutputStream (#1569 ) You can take a look and tell if that fits your needs.

**Comment by qwwdfsad** [comment]
Fixed in 1.3.0-RC

**Comment by slavonnet** [comment]
random EOF exceptions  on heavy loads.

**Comment by sandwwraith** [comment]
@slavonnet Can you please create a separate issue with a reproducer or at least a description of conditions under which exception occurs?

**Comment by martinbonnin** [comment]
Is there a separate issue for multiplatform streaming ?

**Comment by sandwwraith** [comment]
@martinbonnin I've cerated one for you: https://github.com/Kotlin/kotlinx.serialization/issues/1714
