### ISSUE TITLE
@SerialName removed by R8 despite the rules (Android)

### ISSUE THREAD

**Issue by valeriyo** [Kotlin/kotlinx.serialization#2042]
**Describe the bug**
I'm using `kotlin-reflect` to access property annotations like this:

```
kClass.declaredMemberProperties.first().findAnnotation<SerialName>()?.value
```

and it works in Debug builds. However, in Release builds, `findAnnotation<SerialName>()` returns `null` and the `annotations` list is empty. I have the R8 rule to keep annoations:

```
-keepattributes RuntimeVisibleAnnotations,AnnotationDefault
```

and it makes no difference for `@SerialName`.

When I added `@Keep` to the `@Serializable` class - then the `@SerialName` was retained -- but that's a horrible workaround, because it's very error-prone.

Help?

**To Reproduce**:

```
@Serializable
data class MyClass {
  @SerialName("foobar") val foobar: String,
}
```

**Expected behavior**
`@SerialName` is kept for properties of a `@Serializable` class.

**Environment**
 - Kotlin version: 1.7.10
 - AGP: 7.3.0 (w/Android Studio Dolphin)
 - Library version: 1.4.0
 - Kotlin platforms: JVM/Android
 - Gradle version: 7.5.1

**Comment by sandwwraith** [comment]
This looks like some proguard misconfiguration, rather than serialization issue. @shanshin Maybe you have ideas about proguard?

Also, you can use `MyClass.serializer().descriptor.elementNames()` — it already has all the values with respect to `@SerialName`

**Comment by sandwwraith** [comment]
Please reopen if your question is actual
