### ISSUE TITLE
JsonNames not support with a default value

### ISSUE THREAD

**Issue by zhlinh** [Kotlin/kotlinx.serialization#2044]
JsonNames not support with a default value, something like that

// add a default value with JaonNames anotation
// @JsonNames("title", "other_name")  with default value error
// @JsonNames("title")  withe default value works fine
@Serializable
data class Project(@JsonNames("title", "other_name") val name: String = "")
fun main() {
  val project = Json.decodeFromString<Project>("""{"name":"kotlinx.serialization"}""")
  println(project)
  val oldProject = Json.decodeFromString<Project>("""{"title":"kotlinx.coroutines"}""")
  println(oldProject)
}

`
Caused by: java.lang.IllegalArgumentException: Can't use arguments with defaults for serializable annotations yet 	at org.jetbrains.kotlinx.serialization.compiler.backend.jvm.SerializerCodegenImpl.addSyntheticAnnotationsToDescriptor(SerializerCodegenImpl.kt:122) 	at org.jetbrains.kotlinx.serialization.compiler.backend.jvm.SerializerCodegenImpl.addElementsContentToDescriptor(SerializerCodegenImpl.kt:115) 	at org.jetbrains.kotlinx.serialization.compiler.backend.jvm.SerializerCodegenImpl.generateSerialDescriptor(SerializerCodegenImpl.kt:76) 	at org.jetbrains.kotlinx.serialization.compiler.backend.jvm.SerializerCodegenImpl.generateSerialDesc(SerializerCodegenImpl.kt:144) 	at org.jetbrains.kotlinx.serialization.compiler.backend.common.SerializerCodegen.generate(SerializerCodegen.kt:36) 	at org.jetbrains.kotlinx.serialization.compiler.backend.jvm.SerializerCodegenImpl$Companion.generateSerializerExtensions(SerializerCodegenImpl.kt:45)
`

**Environment**
 - Kotlin version: 1.7.10
 - Library version: 1.4.0
 - Kotlin platforms: 1.7.10
 - Gradle version: 7.4

**Comment by sandwwraith** [comment]
This sample code works fine for me, so problem must be somewhere else. 

Error `Can't use arguments with defaults for serializable annotations yet` is usually connected with custom serialinfo annotations — in case they have default arguments, like that:

```
@SerialInfo
annotation class MyAnnotation(val foo: String = "")
```

Do you use such annotations?

**Comment by zhlinh** [comment]
> This sample code works fine for me, so problem must be somewhere else.
> 
> Error `Can't use arguments with defaults for serializable annotations yet` is usually connected with custom serialinfo annotations — in case they have default arguments, like that:
> 
> ```
> @SerialInfo
> annotation class MyAnnotation(val foo: String = "")
> ```
> 
> Do you use such annotations?

Hi, @sandwwraith thanks for reply.

@serializable
data class Project(@JsonNames("title", "other_name") val name: String = "")   // MEET ERROR

@serializable
data class Project(@JsonNames("title") val name: String = "")                   // WORKS FINE

**Comment by sandwwraith** [comment]
Ah, you're using old Kotlin backend? Unfortunately annotations with varargs, such as `@JsonNames`, are not supported there. Try switching to the default JVM IR backend.

**Comment by zhlinh** [comment]
Ah, maybe with kapt? Is kapt disable ir backend?  I found that if kapt being removed, everything works fine. 
Find something similar [Generic custom serializer breaks kotlin\-kapt compilation · Issue \#685 · Kotlin/kotlinx\.serialization]( https://github.com/Kotlin/kotlinx.serialization/issues/685 )

**Comment by sandwwraith** [comment]
I'm not sure that KAPT disables the IR backend, that shouldn't happen. You can try specifying an array, yes.

**Comment by zhlinh** [comment]
This commit just turn array to vararg...
[Replace Array<String> in JsonNames with vararg · Kotlin/kotlinx\.serialization@436cf83]( https://github.com/Kotlin/kotlinx.serialization/commit/436cf833b523c85bfc28d66b4e0cccc11396d238 )

umm, another interface name? To support both.
Gson use the format like @SerializedName(value = "name1", alternate = ["name2", "name3"])

**Comment by sandwwraith** [comment]
I don't see any reasons not to use vararg.

**Comment by sandwwraith** [comment]
Closing as it is reproducible only on old JVM BE. Please use JVM IR
