### ISSUE TITLE
Deserialization into non-annotated type class using manual DeserializationStrategy causes JsonDecodingException 

### ISSUE THREAD

**Issue by hrafnthor** [Kotlin/kotlinx.serialization#2047]
Deserialization of a JSON structure from a `JsonElement` and a raw `String` has behaviour differences depending on if the target type class is annotated with `@Serializable` or not. Passing in a specific `DeserializationStrategy`  functions correctly when deserializing a `JsonElement` but  results in a `JsonDecodingException` when attempting to deserialize the same JSON structure as a raw `String`. 

**To Reproduce**

Please observe the following simplified example:

```kotlin
@Serializable
data class Test(val value: Int)
```

and the following manual construction of a `JsonObject` 

```kotlin
val jsonObject = buildJsonObject {
   put("value", 1)
}
```

Executing either  `Json.decodeFromJsonElement<Test>(jsonObject)` or `Json.decodeFromString<Test>(jsonObject.toString())` will result in output `Test(value=1)` as expected.

Now modify the `Test` data class by removing the `@Serializable` annotation:

```kotlin
data class Test(val value: Int)
```
and create a manual KSerializer for the class:

```kotlin
class TestSerializer: KSerializer<Test> {
   override val descriptor: SerialDescriptor
	get() = buildClassSerialDescriptor("test") {
	   element<Int>("value")
	}

   override fun deserialize(decoder: Decoder): Test {
	return decoder.decodeStructure(descriptor) {
	   val value = decodeIntElement(
		descriptor,
		descriptor.getElementIndex("value")
	    )
	   Test(value)
	}
   }
    // .... omitting serialize() method
}
```
Executing `Json.decodeFromJsonElement(TestSerializer(), jsonObject)` will result in output `Test(value=1)` as expected.

**However** executing `Json.decodeFromString(TestSerializer(), jsonObject.toString())` will result in the following `JsonDecodingException`:

```shell
Unexpected JSON token at offset 1: Unexpected symbol 'v' in numeric literal at path: $
kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 1: Unexpected symbol 'v' in numeric literal at path: $
JSON input: {"value":1}
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:24)
	at kotlinx.serialization.json.internal.JsonExceptionsKt.JsonDecodingException(JsonExceptions.kt:32)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail(AbstractJsonLexer.kt:530)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.fail$default(AbstractJsonLexer.kt:528)
	at kotlinx.serialization.json.internal.AbstractJsonLexer.consumeNumericLiteral(AbstractJsonLexer.kt:566)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeInt(StreamingJsonDecoder.kt:300)
	at kotlinx.serialization.encoding.AbstractDecoder.decodeIntElement(AbstractDecoder.kt:53)
	at <>...DeSerializationTest$1$4$TestSerializer.deserialize(KSerializationTests.kt:175)
	at <>...DeSerializationTest$1$4$TestSerializer.deserialize(KSerializationTests.kt:167)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:95)
```

**Expected behavior**

The behaviour of both `Json.decodeFromJsonElement` and `Json.decodeFromString` should match when given the same DeserializationStrategy for the same target type.

**Environment**
 - Kotlin version: 1.7.10
 - Library version: 
    - kotlinx.serialization.core: 1.4.0
    -  kotlinx.serialization.json: 1.4.0
 - Kotlin platforms: JVM
 - Gradle version: 7.5

**Comment by sandwwraith** [comment]
The problem is, your custom serializer is written incorrectly. You have to call `decodeElementIndex` before every other `decodeXxElement` call so that the format can read and parse JSON keys. The fact that your serializer worked with `JsonObject` is merely a coincidence given that JsonObject is already a map inside (regular JSON parser doesn't use maps). See the detailed guide here: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#hand-written-composite-serializer

**Comment by hrafnthor** [comment]
I had completely missed the importance of `decodeElementIndex`. Using it on my end, the issue described above has disappeared. Thank you for the taking the time for clarifying this for me @sandwwraith,
