### ISSUE TITLE
Json format for serialization 

### ISSUE THREAD

**Issue by Cxxshyy** [Kotlin/kotlinx.serialization#2051]
**What is your use-case and why do you need this feature?**
![image](https://user-images.githubusercontent.com/74113508/194707356-18d5a6c4-1e61-4d06-8d42-9bdca1f0880a.png)
from what i read quickly of the docs there was no way for me to access the values inside location because if i tried location for example i would get an error like Unexpected JSON token at offset 217: Expected beginning of the string, but got {
**Describe the solution you'd like**
Either please guide me how i could fix this or add in a fix for allowing the next char to be a curly bracket then expect another value tobe read from then use that to read the string

**Comment by sandwwraith** [comment]
Sorry, I do not understand what you're trying to achieve. Are you trying to parse a JSON string? Then you need to choose a data form you want to see as a result — Kotlin classes. If Location is a nested object, it should have its own Kotlin class.

Alternatively, you can replace a class with `JsonObject` or just use `Json.parseToJsonElement`.

**Comment by Cxxshyy** [comment]
what i wanted was to access the values in the json object but dont know how

**Comment by sandwwraith** [comment]
Please read https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/basic-serialization.md#referenced-objects or https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#parsing-to-json-element or
