### ISSUE TITLE
Regression in 1.4.1: serializers cache does not distinguish the same class loaded by multiple classloaders

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.serialization#2065]
See 
https://youtrack.jetbrains.com/issue/KT-54523/Regression-kotlinxserialization-141-caches-the-same-serializer-for-ArrayListFoo-for-ktypes-from-different-class-loaders

**Comment by shanshin** [comment]
Relates https://youtrack.jetbrains.com/issue/KT-54611
