### ISSUE TITLE
`kotlinx.serialization.SerializationException` message can be misleading/confusing

### ISSUE THREAD

**Issue by myronmarston** [Kotlin/kotlinx.serialization#2066]
**Describe the bug**

I recently tried setting up kotlinx.serialization in a project as part of using [graphql-kotlin](https://opensource.expediagroup.com/graphql-kotlin/docs/) in order to replace the jackson serializer we were using.  I unfortunately didn't read the setup instructions very thoroughly (and the setup instructions don't fully apply to us since we use bazel instead of gradle).  After adding the necessary package dependencies, ensuring `@Serializable` annotations were on the data classes and trying to use the kotlinx serializer, I started getting errors like this: 

```
kotlinx.serialization.SerializationException: Serializer for class 'Result' is not found.
Mark the class as @Serializable or provide the serializer explicitly.
```

This was incredibly confusing: The `Result` class _was_ marked with `@Serializable`, but the error message made it seem like the annotation was missing.  I didn't (yet) understand that I had to configure a kotlin compiler plugin and the error message did nothing to point me in that direction.  I've since figured out how to setup the the compiler plugin and now have it working, but the misleading error message was quite unhelpful.

So, my request is to consider improving the `kotlinx.serialization.SerializationException` so that if the type _is_ annotated with `@Serializable` it doesn't suggest that you add it.  Instead could it suggest checking to see if the compiler plugin is setup correctly.

Separate from that, having some bazel instructions in the README would be nice.  I wound up following this example:

https://github.com/bazelbuild/rules_kotlin/tree/48cc40371b071f0c11da4493cfe46617eac4da9b/examples/plugin/src/serialization

...so maybe the README could just link there if y'all don't want to maintain the necessary bazel instructions.

**To Reproduce**

Try using this library with `@Serializable` annotations but without the compiler plugin setup.  The resulting exception is quite confusing.

**Expected behavior**

The exception should ideally point the user in the direction of what they did wrong instead of misleading them.

**Environment**
 - Kotlin version: 16.20
 - Library version: 1.4.1
 - Kotlin platforms: JVM
 - Gradle version: N/A--I was using bazel (I believe this same issue would happen on any gradle version if you didn't setup the compiler plugin, though)
 - IDE version (if bug is related to the IDE): N/A
 - Other relevant context: N/A

**Comment by sandwwraith** [comment]
We have an IDE warning about the non-applied plugin. Unfortunately, it's not available during CLI build, because it's, well, located in the plugin. Probably that can be changed somehow.

Regarding error message: 'provide serializer explicitly' meant that you should use `Result.serializer()` which is available only if the module was processed. But I agree, the message can be more clear.

**Comment by qwwdfsad** [comment]
I've opened #2068 to improve the exception message.

>Separate from that, having some bazel instructions in the README would be nice. I wound up following this example:

Unfortunately, none of us is any close to being proficient in Bazel. We are happy to receive a PR into out README with the section about Bazel

**Comment by myronmarston** [comment]
> I've opened #2068 to improve the exception message.
> 
> > Separate from that, having some bazel instructions in the README would be nice. I wound up following this example:
> 
> Unfortunately, none of us is any close to being proficient in Bazel. We are happy to receive a PR into out README with the section about Bazel

Done in #2086.
