### ISSUE TITLE
SerialName annotation being ignored for enums present in data classes

### ISSUE THREAD

**Issue by Joao360** [Kotlin/kotlinx.serialization#2079]
Take this example
```
@Serializable
data class Product(
    val state: State,
    val name: String
)

@Serializable
enum class State {
    @SerialName("shipped")
    SHIPPED,

    @SerialName("completed")
    COMPLETED
}
```

If `Product` is a data class, the deserialization and serialization of it will ignore the `SerialName` annotations present on the `State` class

#### Deserialization
As you can see on the following code snipped, the printed result ignores the annotation
```
val data = Product(state = State.COMPLETED, name = "Random name")
println(Json.encodeToString(data)) // will print { "state": "COMPLETED", "name": "Random name"}
```

#### Serialization
The serialization of  `{ "state": "completed", "name": "Random name"}` would cause a crash with the following exception
```
kotlinx.serialization.SerializationException: State does not contain element with name 'completed' at path $.state
```

The current way to fix this issue is by replacing the `data class` by a normal `class`
```
@Serializable
class Product(
    val state: State,
    val name: String
)
```
Or creating a custom serializer 

**Expected behavior**

`@SerialName` should work even though it is on an `enum` inside a `data class`

**Environment**
 - Kotlin version: 1.7.10
 - Library version: 1.4.0
 - Kotlin platforms: Native
 - Gradle version: 7.5.1

**Comment by sandwwraith** [comment]
I've just checked and your example prints `{"state":"completed","name":"Random name"}` for me as expected. 
Do you experience problems on Native target only, have you tested it on JVM?  What exact Native target do you use (ios, linux, etc)?

**Comment by sandwwraith** [comment]
I think the original bug probably had something with split compilation when `State` was recompiled with the serial name separately, and `Product` serializer didn't realize it.

 @pdvrieze 
> maybe a warning generated by the plugin for this case would be a good idea

I think we already have one, IIRC
