### ISSUE TITLE
Improve name of gradle plugin

### ISSUE THREAD

**Issue by hastebrot** [Kotlin/kotlinx.serialization#208]
I think the name of the gradle plugin should be changed to have a `-gradle-plugin` suffix like other gradle plugins:

- before: `kotlinx-gradle-serialization-plugin`
- after:  `kotlinx-serialization-gradle-plugin`

~~~gradle
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$compilerVersion"
classpath "org.jetbrains.kotlin:kotlin-native-gradle-plugin:${property('konan.version')}"
classpath "org.jetbrains.kotlin:kotlinx-gradle-serialization-plugin:$serializationPluginVersion"
~~~

**Comment by sandwwraith** [comment]
There is another option of naming, to be consistent with the rest of Kotlin compiler plugins: just `kotlinx-serialization`. (https://kotlinlang.org/docs/reference/compiler-plugins.html).

**Comment by sandwwraith** [comment]
So it's renamed to `kotlin-serialization` now.
