### ISSUE TITLE
Presence of (transient) delegated field in the serialized class breaks deserialization

### ISSUE THREAD

**Issue by AngryGami** [Kotlin/kotlinx.serialization#2091]
**Describe the bug**
When I add a delegated field via Map instance - deserialization starts throwing exception:
```
Exception in thread "main" java.lang.NoSuchFieldError: someInt$delegate
	at com.acme.SimpleDTO.<init>(Dtos.kt:796)
	at com.acme.SimpleDTO$$serializer.deserialize(Dtos.kt:796)
	at com.acme.SimpleDTO$$serializer.deserialize(Dtos.kt:796)
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:70)
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:95)
	at org.jetbrains.kotlin.idea.scratch.generated.ScratchFileRunnerGenerated$ScratchFileRunnerGenerated.generated_get_instance_res2(tmp.kt:13)
	at org.jetbrains.kotlin.idea.scratch.generated.ScratchFileRunnerGenerated.main(tmp.kt:29)
```

**To Reproduce**
```
@Serializable
data class SimpleDTO(
    val someString: String,
) {
    @Transient
    private val additionalProperties: Map<String, Int> = mapOf("someInt" to 123)
    val someInt: Int? by additionalProperties
}

val dto = SimpleDTO("ddd")
println(dto.someInt) // prints 123, i.e. value is correctly extracted via delegate
println(dto.someString) // prints ddd

val ser = SimpleDTO.serializer()
Json.decodeFromString(ser,"""{
    |"someString" : "something"
    |}""".trimMargin()) // throws exception
```

**Expected behavior**
Deserialization must not be affected by these fields.

**Environment**
 - Kotlin version: 1.7.20
 - Library version: 1.4.1
 - Kotlin platforms: JVM (android and desktop)
 - Gradle version: 7.4
 - Plugin version: `kotlin("plugin.serialization") version "1.7.20"`

**Comment by shanshin** [comment]
Duplicates #1578

**Comment by AngryGami** [comment]
I don't want them to be serialized or deserialized - I just want these fields to not mess up deserialization. This same code works just fine with 1.7.0.

**Comment by shanshin** [comment]
To exclude field from serialization, mark it with the `@Transient` annotation.
e.g.
```
@Serializable
data class SimpleDTO(
    val someString: String,
) {
    @Transient
    private val additionalProperties: Map<String, Int> = mapOf("someInt" to 123)
    @Transient
    val someInt: Int? by additionalProperties
}
```

**Comment by AngryGami** [comment]
Don't you think I've tried that? This doesn't work :) and any field with delegate is "transient" by default as said here: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/basic-serialization.md#backing-fields-are-serialized.

**Comment by AngryGami** [comment]
I'm pretty sure this is related to this: https://kotlinlang.org/docs/whatsnew1720.html#more-optimized-cases-of-delegated-properties

**Comment by shanshin** [comment]
Thanks, we will look into the cause of this issue.

As a workaround you may use the following "trick", however, it may not be suitable for your applications.

```
@Serializable
data class SimpleDTO(
    val someString: String,
) {
    @Transient
    private val xxx: Map<String, Int> = mapOf("someInt" to 123)
    @Transient
    private val `someInt$delegate`: Map<String, Int> = emptyMap()

    val someInt: Int? by xxx
}
```

**Comment by sandwwraith** [comment]
Apparently, `IrProperty` of such a delegate (someInt) always have `backingField` property, even if it is optimized later, so this line gets executed and `SETFIELD` to non-existing `someInt$delegate` is emitted: https://github.com/JetBrains/kotlin/blob/5a1c2c56bd342fa5a8afa54dedee61a66e5f5066/plugins/kotlinx-serialization/kotlinx-serialization.backend/src/org/jetbrains/kotlinx/serialization/compiler/backend/ir/SerializableIrGenerator.kt#L84

**Comment by AngryGami** [comment]
Will this get fixed anytime soon?

**Comment by sandwwraith** [comment]
Cross-reference: https://youtrack.jetbrains.com/issue/KT-56537
