### ISSUE TITLE
Support repeated @SerialName annotations for a class

### ISSUE THREAD

**Issue by mgroth0** [Kotlin/kotlinx.serialization#2095]
I would like to be able to specify multiple `@SerialName` annotations for a class in a polymorphic class hierarchy.

For example:
```kotlin
@SerialName("Heroku")
@SerialName("heroku")
@Serializable class HerokuJvmExecConfig: JvmExecConfig {
   ...
}
```

The reason is so that when a JSON string is being deserialized, the "type" can be specified as either "Heroku" or "heroku" and be accepted without throwing an error.

**Comment by sandwwraith** [comment]
You can use `default` function in polymorphic module builder for that: https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-core/kotlinx.serialization.modules/-polymorphic-module-builder/default.html

SerialName annotation is not repeatable and likely won't be. However, `JsonNames` probably can be extended to `Target.CLASS` to support what you asked for if there's significant demand for it (new issues)

**Comment by Fanvadar** [comment]
I'd find it useful if `JsonNames` could be used on classes. Default serializer/deserializer doesn't quite fit my use case. 

Updated default serializer links for posterity: 
* https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md#default-polymorphic-type-handler-for-deserialization
* https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-core/kotlinx.serialization.modules/-serializers-module-builder/

**Comment by sandwwraith** [comment]
@Fanvadar Why `polymorphicDefault {}` doesn't work for you?
