### ISSUE TITLE
jsonparser-native incompatible with kotlin native 0.9 

### ISSUE THREAD

**Issue by luca992** [Kotlin/kotlinx.serialization#210]
Would you guys mind creating a jsonparser-native eap13 release which uses kotlin native 0.9?

**Comment by sandwwraith** [comment]
I've published 0.6.2 version which is based on Kotlin 1.2.70 and Kotlin/Native 0.9. Build for 1.3-M2 contains full library with plugin preview for native and can be found [here](https://github.com/Kotlin/kotlinx.serialization/issues/86#issuecomment-420281515).
