### ISSUE TITLE
JSON Serialization of enum classes cause an unbounded IR error

### ISSUE THREAD

**Issue by JarnaChao09** [Kotlin/kotlinx.serialization#2102]
**Describe the bug**
I have an enum class in one file and a data class that serializes that enum class in another file (along with other fields) and I get an error during the build stage: `Symbol with IrConstructorSymbolImpl is unbound`

Gradle Stacktrace: [gradle_log.txt](https://github.com/Kotlin/kotlinx.serialization/files/10045462/gradle_log.txt)

If the enum is in the same file as the data class, then the error goes away.

If the enum class’s definition is commented out including an `@OptIn(ExperimentalSerializationApi::class)` (since I am using the @JsonNames annotation as well) in the same file as the data class, then the error does not appear. However, if I remove the `@OptIn(ExperimentalSerializationApi::class)` annotation, the error returns.

If the enum class's definition is in a different file, but at the top of the file that contains the data class, the imports
```kt
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.SerialName
import kotlinx.serialization.json.JsonNames
```
are imported, the error goes away. Taking any one of these imports away, the error returns

Why must the enum’s definition be in the same file as the data class?
Why does commenting out the whole definition in the same file cause the error to go away?
Why does having the imports also cause the error to go away?

**To Reproduce**
Enum File
```kt
package command
​
import kotlinx.serialization.ExperimentalSerializationApi
import kotlinx.serialization.SerialName
import kotlinx.serialization.json.JsonNames
​
@OptIn(ExperimentalSerializationApi::class)
enum class Command {
    @SerialName("connect")
    @JsonNames("connect", "CONNECT")
    CONNECT,
​
    @SerialName("join")
    @JsonNames("join", "JOIN")
    JOIN,
​
    @SerialName("list")
    @JsonNames("ls", "list", "LIST")
    LS,
​
    @SerialName("show")
    @JsonNames("show", "SHOW")
    SHOW,
​
    @SerialName("send")
    @JsonNames("send", "SEND")
    SEND,
​
    @SerialName("leave")
    @JsonNames("leave", "LEAVE")
    LEAVE,
​
    @SerialName("exit")
    @JsonNames("exit", "EXIT")
    EXIT,
}
```

Data class file (uncommenting the imports or taking out the comments of the enum's definition will cause it to compile successfully)
```kt
package command
​
import content.ClientContent
import kotlinx.serialization.Serializable
​
//import kotlinx.serialization.ExperimentalSerializationApi
//import kotlinx.serialization.SerialName
//import kotlinx.serialization.json.JsonNames

//@OptIn(ExperimentalSerializationApi::class)
//enum class Command {
//    @SerialName("connect")
//    @JsonNames("connect", "CONNECT")
//    CONNECT,
//
//    @SerialName("join")
//    @JsonNames("join", "JOIN")
//    JOIN,
//
//    @SerialName("list")
//    @JsonNames("ls", "list", "LIST")
//    LS,
//
//    @SerialName("show")
//    @JsonNames("show", "SHOW")
//    SHOW,
//
//    @SerialName("send")
//    @JsonNames("send", "SEND")
//    SEND,
//
//    @SerialName("leave")
//    @JsonNames("leave", "LEAVE")
//    LEAVE,
//
//    @SerialName("exit")
//    @JsonNames("exit", "EXIT")
//    EXIT,
//}
​
@Serializable
data class ClientCommand(val user: String, val command: Command, val content: ClientContent)
```

**Expected behavior**
Successfully compile

**Environment**
 - Kotlin version: 1.7.21
 - Library version: 1.4.1
 - Kotlin platforms: JVM
 - Gradle version: 7.4.2

**Comment by sandwwraith** [comment]
I can't reproduce this on Kotlin 2.0.20. Please re-open if still actual.
