### ISSUE TITLE
a question about  the class type

### ISSUE THREAD

**Issue by Xiaobaishushu25** [Kotlin/kotlinx.serialization#2115]
hello,thank you,i want to konw how to convert the string to class that i need,when i use gson,i can write like this:
```
override  fun <T> deserialize(clazz: Class<T>, bytes: ByteArray): T {
            return Gson().fromJson(String(bytes, charset("UTF-8")),clazz)
        }
```
 when i use kotlinx.serialization.json.Json, i write like this:
```
   override  fun <T> deserialize(clazz: Class<T>, bytes: ByteArray): T {
            return kotlinx.serialization.json.Json.decodeFromString<T>(String(bytes))
        }
```
but that is wrong, it seems like that  only specific class can be use ,so how can i use  kotlinx.serialization achieve the same effect like Gson?

**Comment by sandwwraith** [comment]
Check out https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#plugin-generated-serializer

Generally, using `Class<T>` is the wrong approach for using kotlinx.serialization. You either need an inline function with reified type parameter or `KType` reference that can be used in `serializer()` function. (KType can be obtained from `typeOf` stdlib function).
