### ISSUE TITLE
Comatibility with K2 compiler

### ISSUE THREAD

**Issue by charlee-dev** [Kotlin/kotlinx.serialization#2118]
kotlin 1.7.20
serialization 1.7.20
gradle 7.5
KMM Project

Tried to enable K2 in the project.
Added `kotlin.useK2=true`in `gradle.properties`

Running task `assembleMoboxSdkReleaseXCFramework`to build stuff for iOS, but it fails on `compileReleaseJavaWithJavac`

```
e: There are some plugins incompatible with K2 compiler:
  org.jetbrains.kotlinx.serialization.compiler.extensions.SerializationComponentRegistrar

```

**Comment by sandwwraith** [comment]
We plan to release support for K2 in kotlinx.serialization in Kotlin 1.8.20. You can track the progress here: https://youtrack.jetbrains.com/issue/KT-49983/Implement-prototype-of-kotlinx.serialization-for-K2-compiler

**Comment by charlee-dev** [comment]
Thanks
