### ISSUE TITLE
Dont use runtime existence of java.lang.ClassValue to check for Android

### ISSUE THREAD

**Issue by sgjesse** [Kotlin/kotlinx.serialization#2119]
The comment in
https://github.com/Kotlin/kotlinx.serialization/blob/28f7fcb1b4ff4ec77b932d9ffaeaf3f206598b3a/rules/common.pro#L32 indicates that `Class.forName("java.lang.ClassValue")` is used in the library code to check at runtime if the code is running on Android or on the JVM. This has the potential of breaking the code when running on Android and the Android runtime supports `java.lang.ClassValue` in the future. Besides that, the `-dontwarn java.lang.ClassValue` rule is a global rule which might hide issues in other libraries or user code when depending on this library.

I suggest the following changes 1 and either 2a or 2b below.

__1)__ Instead of `-dontwarn java.lang.ClassValue` use `-dontwarn concrete.class.extending.ClassValue`

That way there is no `-dontwarn` which will globally hide this issue for unrelated code in other libraries

__2a__ Change the library to never use `java.lang.ClassValue` on Android, so
```
  if (isAndroid()) {
    // Code which does not use ClassValue
  } else {
    // Code which use ClassValue
  }
```
and here `isAndroid()` is _not_ checking the existence of `java.lang.ClassValue`, but is something like
```
  boolean isAndroid() {
    return System.getProperty("java.runtime.name").contains("Android");
  }
```
__2b)__ (alternative to 2a) Keep using reflection to see if `java.lang.ClassValue` is present at runtime and add the following rule:
```
  -keep class concrete.class.extending.ClassValue {
    ** computeValue(java.lang.Class);
  }
```
The `-dontwarn` from 1 is still needed. This way the `computeValue` method will stay in the program even when compiled with an `android.jar` which does not include `java.lang.ClassValue`.

**Comment by shanshin** [comment]
Hi,
thank you for issue

>  is used in the library code to check at runtime if the code is running on Android or on the JVM.

the comment is incorrectly worded, but at the moment it is relevant. The important thing is not the platform on which the code is run, but the presence of the `ClassValue` - if there is such a class, then we use it, because it is faster. 
If such a class ever appears in Android, then on the contrary it is good, the cache will work faster.

 >   if (isAndroid()) {
 >   // Code which does not use ClassValue
 > } else {
 >   // Code which use ClassValue
 > }

R8 performs static checks, so if a class using `ClassValue` is reachable, then there will still be a warning from R8.
