### ISSUE TITLE
JsonPrimitive string representation for 0.0 is 0 on JS.

### ISSUE THREAD

**Issue by rhdunn** [Kotlin/kotlinx.serialization#2128]
**Describe the bug**
When using `JsonPrimitive` with a `Double` argument to specify a decimal JSON type, the `0.0` value is serialized as an integer `0` value instead on the JS (IR and Legacy).

__Note:__ This breaks JSON schemas or protocols that specify decimal types (e.g. Language Server Protocol [decimal](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#decimal) type).

**To Reproduce**
`JsonPrimitive(0.0).toString()`

**Expected behavior**
Returns `0.0`.

**Actual behavior**
Returns `0` on JS, `0.0` on JVM and Native.

**Environment**
 - Kotlin version: 1.7.20
 - Library version: [e.g. 0.11.0]
 - Kotlin platforms: `[jsIr, browser, Firefox107.0, Windows10]`, `[jsIr, node]`, `[jsLegacy, browser, Firefox107.0, Windows10]`, `[jsLegacy, node]`
 - Gradle version: 7.5
 - IDE version: 2022.3
 - OS version: Windows 11

**Comment by xn32** [comment]
I am in the process of porting a third-party format to Kotlin Multiplatform and came across this issue as well. Note that it is not limited to just the value `0.0`. Instead, it seems to be related to how `Double.toString()` works in general.

See the following test code:
```kotlin
val json = Json { prettyPrint = true }
val values = listOf(0.0, 0.9e-6, 1.0e-6, 0.9e-3, 1.0e-3, 0.9e+7, 1e+7, 0.9e+21, 1e+21)
println("Json.encodeToString: ${json.encodeToString(values)}")
```

Executed using both Kotlin/JVM and Kotlin/Native, this code produces the following output:
```
Json.encodeToString: [
    0.0,
    9.0E-7,
    1.0E-6,
    9.0E-4,
    0.001,
    9000000.0,
    1.0E7,
    9.0E20,
    1.0E21
]
```

This is the default JVM behavior that seems to be emulated by [this Kotlin/Native code](https://github.com/JetBrains/kotlin/blob/1be39cb50516b7a48833e0ba263d15ab7f7e56c6/kotlin-native/runtime/src/main/kotlin/kotlin/native/internal/NumberConverter.kt#L40). For the JS target (Node.js), however, it produces the following output on my Linux machine:
```
Json.encodeToString: [
    0,
    9e-7,
    0.000001,
    0.0009,
    0.001,
    9000000,
    10000000,
    900000000000000000000,
    1e+21
]
```

This seems to be the default JS behavior documented [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toString?retiredLocale=de).

**Comment by sandwwraith** [comment]
Yes, because numbers on JS are represented as JS's `number` type, they have a different format in the string representation. I'm not sure we can do anything meaningful here except by writing `Double.toString()` logic from scratch.

**Comment by rhdunn** [comment]
For my use case I'm now allowing both integer and decimal numbers and converting the integers to `Double`. In the tests, I'm checking that the deserialized value is either `0` or `0.0`.

**Comment by sandwwraith** [comment]
Answered here: https://github.com/Kotlin/kotlinx.serialization/issues/2823#issuecomment-2382745072
