### ISSUE TITLE
Access the underlying JsonPrimitive storage value.

### ISSUE THREAD

**Issue by rhdunn** [Kotlin/kotlinx.serialization#2131]
**What is your use-case and why do you need this feature?**
Given a boolean value, there is an overhead in getting the underlying `Boolean` type.

    JsonPrimitive(true).content == "true"

This converts the `body` to a string and then back to a `Boolean`. The same applies for the numeric values.

**Describe the solution you'd like**
Have more type checks:
1. `isNumber` -- true if this is a numeric type
2. `isBoolean` -- true if this is a boolean type

Have conversion helpers:
1. `toBoolean()` / `toBooleanOrNull()` -- Convert to a `Boolean`. If body is a Boolean, don't use content.
2. `toInt()` / `toIntOrNull()` / etc. -- Convert to the various signed/unsigned and floating-point numeric types. If body is a Number/unsigned type, don't use content.

**Comment by sandwwraith** [comment]
There's a discussion on the topic here: https://github.com/Kotlin/kotlinx.serialization/issues/1298#issuecomment-997910136

In general, separating numbers from booleans is a reasonable request, but we can't give any commitments to that.
