### ISSUE TITLE
How To Get Serializer From Reified Generic Parameter?

### ISSUE THREAD

**Issue by MrThreepwood** [Kotlin/kotlinx.serialization#214]
I am attempting to use this library in order to serialize things generically for all routes handled by my Api in order to contain references to serialization/deserialization. Currently with Jackson I can do this, but I don't know how to manage it with this library.

```
fun <reified T> deserializeData(request: String): T {
    //typetoken/serializer stuff with reified T
    JSON.parse(serializer, request)
}
```

The goal here being to avoid any reference to this library about how serialization/deserialization is done outside of the few functions that actually handle that.

**Comment by MrThreepwood** [comment]
I kept poking at it a bit and realized that serializer is an extension function added by this package, so I can simply change it to 
```
fun <reified T: Any> deserializeData(request: String): T {
    JSON.parse(T::class.serializer(), request)
}
```

**Comment by mochadwi** [comment]
For custom serialization, you might want to use this example [here](https://github.com/kotlin/kotlinx.serialization/blob/a4c41392bb735a36788db1d789ec60afdbad3ca8/runtime/jvm/src/test/kotlin/kotlinx/serialization/features/GenericCustomSerializerTest.kt)

**Comment by leinardi** [comment]
Any solution for Kotlin Native? `T::class.serializer()` uses reflection and is not available on Kotlin/Native.

**Comment by sandwwraith** [comment]
@leinardi try to use `serializer<T>()`

**Comment by leinardi** [comment]
@sandwwraith If I use `kotlinx.serialization.serializer`, I get the error `Cannot use 'T' as reified type parameter. Use a class instead.`

**Comment by sandwwraith** [comment]
Maybe your `T` is not `reified`?

**Comment by leinardi** [comment]
Even with the `reified` I get the warning
`This declaration is experimental and its usage must be marked with '@kotlinx.serialization.ImplicitReflectionSerializer' or '@OptIn(kotlinx.serialization.ImplicitReflectionSerializer::class)'`
which I assume won't work on non JVM platforms, right?

**Comment by Xerosigma** [comment]
Can't get this to work right either.

**Comment by sandwwraith** [comment]
It may work for some limited cases, so give it a try

**Comment by spragucm** [comment]
> I kept poking at it a bit and realized that serializer is an extension function added by this package, so I can simply change it to
> 
> ```
> fun <reified T: Any> deserializeData(request: String): T {
>     JSON.parse(T::class.serializer(), request)
> }
> ```

This needs a little more explanation...

I'm using Android Studio and the Kotlin Serialization library.

Simple data class:
```
import kotlinx.serialization.Serializable

@Serializable
data class DataTest(val name: String = "YoMamma")
```

The extension functions:
```
inline fun <reified T: Any> deserialize(data: String): T {
    return Json.parse(T::class.serializer(), data)
}

inline fun <reified T: Any> T.serialize(): String {
    return Json.stringify(T::class.serializer(), this)
}
```

Using the functions:
```
val serialIn = DataTest("yoPappa").serialize()
Log.d("Serialize In: $serialIn")
val deserialize : DataTest = deserialize(serialIn) //YOU MUST SPECIFY THE THE TYPE, that's how the type gets reified
Log.d("Serialize Out: $deserialize")
```

If you don't specify the type, e.g. val ... : DataTest, then you get the following error:

> Can't locate companion serializer for class
