### ISSUE TITLE
How to use kotlinx.serialization with Compose Desktop?

### ISSUE THREAD

**Issue by yantlord** [Kotlin/kotlinx.serialization#2141]
I am trying to use JSON serialization in a Compose Desktop app, and I'm unable to use _@ Serializable_ or even pull in the dependencies successfully, apparently.

I was able to get it to build by dropping the version number down to 1.7.10, but I still can't use the annotations in my app.

Am I missing KSP or something else that I need? I've scoured the docs but it's pretty light since everything is so fresh.

Would appreciate any pointers, thanks!

**Comment by sandwwraith** [comment]
Have you added the serialization compiler plugin to Gradle config? 

Although there are some issues regarding using several compiler plugins in one module, so the guaranteed way to make this work is to make a separate Gradle module with serialization enabled.

**Comment by yantlord** [comment]
Thanks for the reply. I believe so, my plugins directive looks like this atm:

```
plugins {
    kotlin("multiplatform") version "1.7.20"
    id("org.jetbrains.compose")
    kotlin("plugin.serialization") version "1.7.20"
}

// Dependency
    sourceSets {
        val jvmMain by getting {
            dependencies {
                ....
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.1")
                ...
            }
        }
    }

```

I just tried building the project with ver 1.8.0, and it wouldn't build, giving some message about incompatibility and this link: 
https://github.com/JetBrains/compose-jb/blob/master/VERSIONING.md#kotlin-compatibility. 

I followed the instructions there and dropped the versions down to 1.7.20, and now the project will build and run, but I am still unable to use @ Serializable annotations in Intellij IDEA IDE

**Comment by yantlord** [comment]
I don't know what the problem ended up being, but I created a brand new project and everything is working fine now!
