### ISSUE TITLE
Sealed Interfaces with named companion objects do not generate serializers

### ISSUE THREAD

**Issue by Shengaero** [Kotlin/kotlinx.serialization#2163]
**Describe the bug**
Named companion objects of sealed interfaces do not auto-generate serializers when tagged with `@Serializable`.

Note that this only occurs when the companion object is *named*, if unnamed this error will not occur.

**To Reproduce**
```kotlin
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json

@Serializable
sealed interface MyInterface {
    companion object NamedCompanionObject {
        const val Example = "testing"
    }
}

@Serializable
@SerialName("FooBar")
data class FooBar(val value: String): MyInterface

fun main() {
    // error will be thrown here, reporting that MyInterface is not tagged with @Serializable
    val text = Json.encodeToString<MyInterface>(FooBar(MyInterface.Example))
    println(text)
}
```

**Expected behavior**
This should not throw an error, or at least I don't believe it should.
Nothing in the documentation I could find implies this is expected behavior.

**Environment**
 - Kotlin version: 1.8.0
 - Library version: 1.4.1
 - Kotlin platforms: JVM
 - Gradle version: 7.4.2
 - IDE version: Unsure if related but IntelliJ IDEA 2022.2.3

**Comment by shanshin** [comment]
Related #1291, #1207

**Comment by sandwwraith** [comment]
Not reproducible on Kotlin 2.0.20, I believe it was fixed recently
