### ISSUE TITLE
`decodeFromString` should annotate `string` parameter with `@Language`

### ISSUE THREAD

**Issue by endorh** [Kotlin/kotlinx.serialization#2166]
**What is your use-case and why do you need this feature?**
Writing tests that pass string literals to `decodeFromString` would be easier with IDE support.

**Describe the solution you'd like**
All `decodeFromString` methods should annotate their `string` parameter with `@org.intellij.lang.annotations.Language` so the IDE can inject the appropriate language on String literals passed as arguments.

For example, `Json.decodeFromString` would have as signature
```Kotlin
fun <T> decodeFromString(deserializer: DeserializationStrategy<T>, @Language("JSON") string: String): T
inline fun <reified T> Json.decodeFromString(@Language("JSON") string: String): T
```

This should also apply to any other formats supporting deserialization from String languages supported by the IDE.

**Additional notes**
Currently, the `inline` overload without `DeserializationStrategy` is defined as an extension function on all `StringFormat` formats.

```Kotlin
inline fun <reified T> StringFormat.decodeFromString(string: String): T
```

This'd need to be changed in order to provide different annotations per format language.

I propose defining a member function on each relevant format (e.g., `Json`), while keeping the extension function available for backwards compatibility, as well as for formats which don't declare the function themselves for whichever reason. This way, the annotated member function would win overload resolution and there's no need for any deprecation.

**Comment by aSemy** [comment]
I'd really like to see this.

However, the problem with the `@Language` annotation is that it's JVM-only. The workaround [suggested by JetBrains](https://github.com/JetBrains/java-annotations/issues/34) is to copy-paste the annotation into a multiplatform project, and make sure to keep the same package name. IntelliJ doesn't care where the annotation comes from, or if it's JVM or another platform; all IntelliJ cares about is the FQN of the annotation.

I applied this workaround recently in Kotest https://github.com/kotest/kotest/pull/3328


There are a couple of other limitations too. Languages aren't injected into 

* receivers https://youtrack.jetbrains.com/issue/KTIJ-12951/
* infix parameters 
   <img width="577" alt="image" src="https://user-images.githubusercontent.com/897017/210421340-89520461-e7ff-4f84-9282-a374c466e621.png">

**Comment by pdvrieze** [comment]
@aSemy The bigger problem is that this adds an additional dependency upon the annotation library.

**Comment by pdvrieze** [comment]
@aSemy I don't want to add it as a mandatory dependency (which it would be as the annotation becomes part of the API). It would require all consumers of the library to also use include it. In production code you would normally not expect hardcoded strings to be parsed, so this is only useful in a test context. To me this is the perfect use case for [external annotations](https://www.jetbrains.com/help/idea/external-annotations.html).

**Comment by aSemy** [comment]
@pdvrieze Yeah, external annotations would be better. But I don't think it's a problem to have a dependency on `org.jetbrains:annotations` because it's [an API dependency of `kotlin-stdlib`](https://github.com/JetBrains/kotlin/blob/4060cc2750221f70fed67937e2204453b71be00b/libraries/stdlib/jvm/build.gradle#L80), so it's already present. The annotation retention is [set to `CLASS`](https://github.com/JetBrains/java-annotations/blob/0d08bfd616e8ac8fa582de1ef5f4a0cbc6e89f5f/common/src/main/java/org/intellij/lang/annotations/Language.java#LL46-L46C11) so it shouldn't be present at runtime.
