### ISSUE TITLE
Cannot inline a value class with a custom sealed class serializer surrogate for inline Json strings (1.5.0-RC, experimental, kotlin 1.8.0))

### ISSUE THREAD

**Issue by v79** [Kotlin/kotlinx.serialization#2177]
Not sure if this is a bug or a feature request. I am attempting to include an unescaped, unencoded Json string as part of a bigger serialized object. The object is a sealed class with several implementations, including a generic (of type R) which requires me to write a custom serializer via a surrogate. The Json string is represented by a value class.

Starting with the sealed interface (or class, same result):
```kotlin
@JvmInline
@Serializable(with = RawJsonStringSerializer::class)
value class RawJsonString(val content: String) : CharSequence by content

@Serializable(with = ResultSerializer::class)
sealed interface APIResult<out R : Any> {
    @Serializable
    data class Success<out R : Any>(val value: R) : APIResult<R>

    @Serializable
    @JvmInline
    value class JsonSuccess(val jsonString: RawJsonString) : APIResult<RawJsonString>

    @Serializable
    data class Error(val message: String) : APIResult<Nothing>

    @Serializable
    data class OK(val message: String) : APIResult<Nothing>
}
```
An `APIResult` could be an `OK`, an `Error`, a `Success` (which takes an object of type `R`; this is working), or a `JsonSuccess`, which will contain a `RawJsonString` which should not be escaped or serialized or processed - just included as-as.

The `ResultSerializer` almost works:

```kotlin
@OptIn(ExperimentalSerializationApi::class)
class ResultSerializer<R : Any>(rSerializer: KSerializer<R>) : KSerializer<APIResult<R>> {

    @Serializable
    @SerialName("result")
    data class APIResultSurrogate<R : Any> constructor(
        @Transient
        val type: ResultType = ResultType.OK,
        @EncodeDefault(EncodeDefault.Mode.NEVER)
        val myCustomData: R? = null,
        @EncodeDefault(EncodeDefault.Mode.NEVER)
        val message: String? = null,
        @Serializable(with = RawJsonStringSerializer::class)
        @EncodeDefault(EncodeDefault.Mode.NEVER)
        val jsonString: RawJsonString = RawJsonString("")
    ) {
        enum class ResultType { Success, Error, OK, JSON }
    }

    private val surrogateSerializer = APIResultSurrogate.serializer(rSerializer)
    override val descriptor: SerialDescriptor = surrogateSerializer.descriptor

    override fun deserialize(decoder: Decoder): APIResult<R> {
        val surrogate = surrogateSerializer.deserialize(decoder)
        println("Deserializing via surrogate for ${surrogate.type}")
        return when (surrogate.type) {
            APIResultSurrogate.ResultType.Success -> {
                if (surrogate.myCustomData != null) {
                    APIResult.Success(surrogate.myCustomData)
                } else {
                    throw SerializationException("Unable to serialize object with null data for Result.Success")
                }
            }
            APIResultSurrogate.ResultType.JSON -> {
               TODO("NOT YET IMPLEMENTED DESERIALIZATION OF ARBITRARY JSON BODY AND I DON'T NEED TO ANYWAY")
            }
            APIResultSurrogate.ResultType.OK -> {
                APIResult.OK(surrogate.message ?: "")
            }
            APIResultSurrogate.ResultType.Error -> {
                APIResult.Error(surrogate.message ?: "")
            }
        }
    }

    override fun serialize(encoder: Encoder, value: APIResult<R>) {
        val surrogate = when (value) {
            is APIResult.Error -> APIResultSurrogate(type = APIResultSurrogate.ResultType.Error, message = value.message)
            is APIResult.OK -> APIResultSurrogate(type = APIResultSurrogate.ResultType.OK, message = value.message)
            is APIResult.Success -> APIResultSurrogate(type = APIResultSurrogate.ResultType.Success, myCustomData = value.value)
            is APIResult.JsonSuccess -> {
                APIResultSurrogate(type = APIResultSurrogate.ResultType.JSON, jsonString = value.jsonString)
            }
        }
        surrogateSerializer.serialize(encoder, surrogate)
    }
}
```

And finally the `RawJsonStringSerializer` uses `encodeJsonElement` and `JsonUnquotedLiteral` from 1.5.0-RC to "paste in" the raw Json:

```kotlin
@OptIn(ExperimentalSerializationApi::class)
object RawJsonStringSerializer : KSerializer<RawJsonString> {
    override val descriptor = PrimitiveSerialDescriptor("org.liamjd.cantilever.api.models.RawJsonString", PrimitiveKind.STRING)
    override fun deserialize(decoder: Decoder): RawJsonString = RawJsonString(decoder.decodeString())
    override fun serialize(encoder: Encoder, value: RawJsonString) {
        return when (encoder) {
            is JsonEncoder -> {
                println("RawJsonStringSerializer: raw encoding")
                encoder.encodeJsonElement(JsonUnquotedLiteral(value.content))
            }
            else -> {
                println("RawJsonStringSerializer: plain encoding $value")
                encoder.encodeString(value.content)
            }
        }
    }
}
```

The end result of all this becomes Json like:

```{"statusCode":200,"headers":{"Content-Type":"application/json"},"body": {"jsonString":{"layouts":"templates": // etc etc etc... }```

But what I hoped for, and kinda expect given that `APIResult.JsonSuccess` is an inline value class, is this:

```{"statusCode":200,"headers":{"Content-Type":"application/json"},"body": { "layouts": {"templates": // etc etc etc... }```

I.e. the `jsonString` value property is inlined and doesn't use the key `jsonString`.

It's a weird scenario, I know. If I strip out all the sealed class `APIResult` classes with that nasty-but-needed `data<R>` generic and the surrogate, I can get it to work. But the introduction of the surrogate forces in the inclusion of the `jsonString` key.

I've briefly tried changing the `APIResultSurrogate` into a sealed class but that didn't go well... It would almost suit being a union type?

My gut feeling is that this sort of behaviour would be very useful when [encoding literal json content](https://github.com/Kotlin/kotlinx.serialization/blob/v1.5.0-RC/docs/json.md#encoding-literal-json-content-experimental), as introduced in 1.5.0-RC.

**Comment by sandwwraith** [comment]
I'm a bit confused: I don't see `val body` in your code, so I can't see which exact class serialization went wrong. Anyway, given that your serializers are custom, maybe you're missing a call to [encodeInlineElement](https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-core/kotlinx.serialization.encoding/-composite-encoder/encode-inline-element.html) somewhere. We have a documentation section for encoding value classes in custom serializers: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/value-classes.md#using-value-classes-in-your-custom-serializers
