### ISSUE TITLE
Cannot generate external serializer, class is defined in another module

### ISSUE THREAD

**Issue by aftabahmadTW** [Kotlin/kotlinx.serialization#2182]
**Error message:**
```
Cannot generate external serializer 'DiskItemSerializer<T>': class 'DiskItem<*>' is defined in another module
```

**To Reproduce**
I've attached a sample project.  [Serialization.zip](https://github.com/Kotlin/kotlinx.serialization/files/10547684/Serialization.zip)

It has two modules `app and data`. The `data` module contains one class called `DiskItem` and `app` contains the serializer `DiskItemSerializer`.

If you try and run the project you'll see the error. If you bump the kotlin version to 1.8.0 and try either the kotlinx-serialization versions (1.4.1 or 1.5.0-RC) you'll see the compile error.

If you try kotlin 1.7.21 and kotlinx-serialization 1.4.1 it compiles and runs.

**Environment**
 - Kotlin version: Tested on 1.7.21 and 1.8.0
 - Library version: Tested on 1.4.1 and 1.5.0-RC
 - Kotlin platforms: JVM
 - Gradle version: 7.6
 - IDE version: Android Studio Electric Eel | 2022.1.1

**Comment by shanshin** [comment]
Hi,
in your case, the `@Serializer` annotation is useless for `DiskItemSerializer`, because you override all the required members yourself.
Try deleting this annotation.

**Comment by aftabahmadTW** [comment]
Nice! Yeah that fixes the issue. Thanks for the help 👍

**Comment by HoffiMuc** [comment]
@shanshin well it works without the `@Serializer(forClass = '...'`, yes, but according to documentation it should be "ok" to have the annotation in place ... shouldn't it?
In what case a `@Serializer` annotation is necessary and in which cases it is a compile error? and why?

**Comment by shanshin** [comment]
@HoffiMuc 
> In what case a @Serializer annotation is necessary and in which cases it is a compile error? and why?

`@Serializer` annotation is necessary if you want the plugin to automatically generate the serializer code (`descriptor`, functions `serialize` or `deserialize`) for an already compiled class.

The current limitation of the compiler does not allow us to get all the necessary information about a class that was compiled in another module (see #532), so the `Cannot generate external serializer...` diagnostics was added.

However, this diagnosis did not take into account the case when the annotation is useless (nothing is generated automatically, or inheritance from `KSerializer` is only added), so such an error began to be thrown.
This case will be added to diagnostics in the next Kotlin releases.

**Comment by zjarlin** [comment]
kotlinx-serialization = "1.9.0"
the problem persists

**Comment by zjarlin** [comment]
<img width="1095" height="691" alt="Image" src="https://github.com/user-attachments/assets/36324229-dcfe-4570-8998-42b13af33c58" />

<img width="1052" height="672" alt="Image" src="https://github.com/user-attachments/assets/ec27c952-3968-4fc4-8ad9-e28ba5e4e877" />

**Comment by pdvrieze** [comment]
@zjarlin See the comment by @shanshin:
> The current limitation of the compiler does not allow us to get all the necessary information about a class that was compiled in another module (see https://github.com/Kotlin/kotlinx.serialization/issues/532), so the Cannot generate external serializer... diagnostics was added.

This is the diagnostic here, in other words, this is by design.
