### ISSUE TITLE
Can't serialize class with generic type

### ISSUE THREAD

**Issue by mmolosay** [Kotlin/kotlinx.serialization#2190]
I get:
```
Exception in thread "main" kotlinx.serialization.SerializationException: Class 'Animal' is not registered for polymorphic serialization in the scope of 'Any'.
Mark the base class as 'sealed' or register the serializer explicitly.
```
when trying to do the following (`main()` function):

**To Reproduce**
``` kotlin
fun main() {
    val animal = Animal(0L, Animal.Species.Cat, "Cassy", 4)
    val resource = Resource.Success(animal)
    val response = AnimalResponse(resource)
    val encoded = Json.encodeToString<AnimalResponse>(response)
    println(encoded)
}
```
``` kotlin
@Serializable
data class Animal(
    val id: Long,
    val species: Species,
    val name: String,
    val age: Int,
) {

    @Serializable
    enum class Species {
        Cat, Dog, Owl, Rat,
    }
}
```
``` kotlin
@Serializable
sealed interface Resource<out T> {

    @Serializable
    class Success<out T>(val value: T) : Resource<T>
}
```
``` kotlin
@Serializable
data class AnimalResponse(
    val resource: Resource<Animal?>,
) : Response()

@Serializable
sealed class Response
```

How do I fix this?

**Environment**
 - Kotlin version: [1.8.0]
 - Library version: [kotlinx-serialization-json:1.4.1]
 - Kotlin platforms: [JVM]
 - Gradle version: [7.4.2]

**Comment by sandwwraith** [comment]
It is a design limitation: given that `T` in `Resource/Success` does not have any upper bound, it is considered to have upper bound `Any` (https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md#polymorphism-and-generic-classes). Therefore, as message suggests, you should register your `Animal` class as a subclass of `Any`: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md#registered-subclasses
