### ISSUE TITLE
Can`t open Kotlin Desktop App with kotlinx.serialization 

### ISSUE THREAD

**Issue by arstagaev** [Kotlin/kotlinx.serialization#2195]
**Describe the bug**
When I launch app with kotlinx.serialization in IntelijiIDEA - I dont have problem. After gradle compile to .exe, and open this file I have a error:

![image](https://user-images.githubusercontent.com/53790451/219337721-8685459f-478c-4669-8f6c-425dbd8b0049.png)
But I have @Serializable annotation in code, you can see this on the screenshoot.

**To Reproduce**
-

**Expected behavior**
Launch program without errors:)

**Environment**
plugins {
    kotlin("jvm") version "1.8.0"
    id("org.jetbrains.compose") version "1.3.0"
    kotlin("plugin.serialization") version "1.8.0"
}
org.jetbrains.kotlinx:kotlinx-serialization-json:1.4.1

 - Gradle version: [7.1]
 - IDE version IntelliJ IDEA 2022.3.2
 - Windows 10, PC, 8GB RAM, i5

**Comment by arstagaev** [comment]
What should I do? Need add some comparator of this?:)

**Comment by sandwwraith** [comment]
Given that your code compiles and runs in the IDE fine, I suggest searching for the problems in the .exe packaging. Is Jetbrains Compose itself producing .exe file? Then you probably want to file an issue to them.

You can check if the 'provide serializer explicitly' workaround works for you: just use `Json.decodeFromString(ParameterCommon.serializer(), s)` instead of `Json.decodeFromString(s)` (or whatever function you use there)

**Comment by arstagaev** [comment]
Is Jetbrains Compose itself producing .exe file?
- yes it is. I work with Kotlin Multiplatform (by Gradle I generate .msi file, and after installing I get .exe).

Now I use model with array, according by your suggestions:
```
val PCListSerializer: KSerializer<List<ParameterCommon>> = ListSerializer(ParameterCommon.serializer())
 
val obj = Json.decodeFromString(PCListSerializer, file.readText(Charsets.UTF_8)) 
```
But have same error. Hmm.. this weird

![image](https://user-images.githubusercontent.com/53790451/219435529-4006d4ee-2107-4895-a16d-2b4647ede83b.png)

**Comment by sandwwraith** [comment]
It's hard to say where the problem is without a stacktrace or attached reproducer. If you instantiated the serializer manually, and still get this error, I can recommend you file ticket in the Compose Desktop issue tracker
