### ISSUE TITLE
Can't serialize a type with a abstract/interface  property even when passing a SerializersModule

### ISSUE THREAD

**Issue by lalongooo** [Kotlin/kotlinx.serialization#2197]
**Describe the bug**
Can't serialize a type with a generic/abstract  property even when passing a `SerializersModule`

I get:
`SerializationException: Class 'Porsche' is not registered for polymorphic serialization in the scope of 'SdkExtraData'. Mark the base class as 'sealed' or register the serializer explicitly.`

This is the GitHub repo to reproduce the ussue:
https://github.com/lalongooo/kotlin-serialization-issue

**To Reproduce**
I have 3 modules `:sdk-api`, `:sdk`, `:app`, with their corresponding classes:

---------

An **Android library** module`:sdk-api`
``` kotlin
class SdkApi<EventData : Any> constructor(
    private val eventDataKClass: KClass<EventData>,
    private val appSerializersModule: SerializersModule
) {
    private val json by lazy {
        Json {
            serializersModule = appSerializersModule
        }
    }

    @OptIn(InternalSerializationApi::class)
    fun send(event: EventData) {
        val element = encodeToJsonElement(eventDataKClass.serializer(), event)
        val jsonString = json.encodeToString(element)
        println(jsonString)
    }
}
```
---------
An **Android library** module `:sdk`:
``` kotlin
@Serializable
abstract class SdkExtraData // I have tried making this an interface
```

``` kotlin
@Serializable
class Action(
    private val foo: String,
    private val extraData: SdkExtraData? = null
)
```

``` kotlin
class Sdk constructor(private val sdkApi: SdkApi<Action>) {
    companion object {
        fun create(
            projectSerializersModule: SerializersModule
        ): Sdk {
            val sdkApi = SdkApi(Action::class, projectSerializersModule)
            return Sdk(sdkApi)
        }
    }
    fun sendAction(action: Action) {
        sdkApi.send(action)
    }
}
```
---------
An **Android app** module: `:app`:

``` kotlin
@Serializable
data class Porsche(
    private val model: String,
    private val generation: Int
) : SdkExtraData()
```

``` kotlin
fun buildSerializersModule() = SerializersModule {
    polymorphic(SdkExtraData::class) {
        subclass(Porsche::class) // also tried with subclass(Porsche::class, Porsche.serializer())
    }
}
```

``` kotlin
fun serializeStuff() {
    val action = Action(
        foo = "Android",
        extraData = Porsche(model = "911", generation = 992)
    )
    val module = buildSerializersModule()
    val sdk = Sdk.create(module)
    sdk.sendAction(action)
}
```

**Expected behavior**
- Serialization succeeds

**Environment**
 - Kotlin version: 1.7.21
 - Library version: 1.2.2
 - Kotlin platforms: JVM
 - Gradle version: 7.5
 - IDE version: Android Studio Electric Eel | 2022.1.1
 - Mac OS Monterrey 12.6.3

If there's an alternative to not use `SerializerModule`, I'm up for it.

**Comment by sandwwraith** [comment]
You've accidentally imported `Json.Default.encodeToJsonElement` which does not use your module. Use `json.encodeToJsonElement` instead.
