### ISSUE TITLE
Incorrect warning about lateinit when used in conjunction with @Transient

### ISSUE THREAD

**Issue by TorRanfelt** [Kotlin/kotlinx.serialization#2203]
**Describe the bug**
```
    @Transient
    lateinit var parentHandle: InputKontoHandle
```

This gives a warning in IntelliJ IDEA and Kotlin compiler's log about lateinit even though it is used in conjunction with @Transient: "Lateinit is unnecessary: definitely initialized in constructors"

**Expected behavior**
No warning.

**Environment**
 - Kotlin version: [e.g. 1.8.10]
 - Library version: [e.g. 1.4.1]
 - Kotlin platforms: [JS]
 - Gradle version: [e.g. 7.1]
 - IDE version (if bug is related to the IDE) [e.g. IntellijIDEA 2022.3.2]

**Comment by sandwwraith** [comment]
Why this warning shouldn't be there though? `init` blocks are executed during deserialization process, so If your `parentHandle` is initialized in `init` block, there shouldn't be problems

**Comment by TorRanfelt** [comment]
It is not initialized during the init block. It is initialized at a later time, but before it is used (Hence lateinit. If that wasn't permissible there would never be a use-case for lateinit on a Transient variable.).

It is because I have a bunch of serializable child objects that each belongs to a parent non-serializable object. After deserialization these child objects are given to the corresponding parent objects, and at that point the parent object initialize parentHandle of the child object. Why this is a good idea is a long story, and not relevant here. The point is that lateinit should not cause a warning because the whole idea with lateinit is that the programmer knows it will be initialized before it is used.

**Comment by sandwwraith** [comment]
Can you post an example code, please?

**Comment by TorRanfelt** [comment]
```
class Foo {
  private var bar: Bar? = null // Foo can create a Bar instance.
  // Lots of variables and methods.
}
```

```
@Serializable
class Bar {
    // When a bar is created by foo the constructor is ran.
    constructor(foo: Foo) {
      this.foo = foo
    }

   // After deserialization bar gets reattached to foo and finally rebootPostLoad is ran.
   fun rebootPostLoad(foo: Foo) {
      this.foo = foo
    }

    @Transient
    lateinit var foo: Foo // If a Bar instance is created it references the Foo it was created by and belongs to.

    // Lots of variables and methods.
}
```

Every foo is also part of a map. The map along with a lot of other stuff is serialized. When deserialized every Bar at this point in time naturally doesn't have foo initialized, but right after they are reattached to their respective Foo and get foo initialized through rebootPostLoad(). Only after this point will Bar be used and hence lateinit is correct.

The alternative is a dummy value for foo that is never used and that would be not be elegant because of the complexity of Foo() (was it an int or list I would just set it to 0 or emptyList()).

**Comment by sandwwraith** [comment]
Moved to https://youtrack.jetbrains.com/issue/KT-73961
