### ISSUE TITLE
Make it possible to hide the synthetic constructors from binary compatibility validator

### ISSUE THREAD

**Issue by martinbonnin** [Kotlin/kotlinx.serialization#2209]
Follow up from [this slack discussion](https://slack-chats.kotlinlang.org/t/9592145/i-m-using-https-github-com-kotlin-binary-compatibility-valid#b708d17e-a0c6-4ef0-8b28-cd7f7a3a2b09):

I'm using [binary-compatibility-validator](https://github.com/Kotlin/binary-compatibility-validator) and kotlinx.serialization synthetic constructors show up in the API dump (the ones that take a SerializationConstructorMarker as last parameter). My understanding is that they're only used from the companion serializer and this is cluttering the API dump. 

I don't think it's a BCV issue as some synthetic functions can still be part of the ABI (like default arguments synthetic functions)

Would it be possible to hide those constructors? Maybe mark them `internal`?

**Comment by sandwwraith** [comment]
See the discussion here: https://github.com/Kotlin/kotlinx.serialization/issues/2108

In fact, these synthetic declarations are also a part of an ABI. A deserialization constructor may be called from a deserialization constructor of an inherited class — and if you change one by e.g. adding a property, it may break your application. So you should pay attention to these declarations as well when changing API.

However, for final classes, they can indeed be internal.
