### ISSUE TITLE
Plugin with id 'com.android.library' not found in a multi-platform project

### ISSUE THREAD

**Issue by yuriry** [Kotlin/kotlinx.serialization#221]
I'm trying to integrate kotlinx-serialization into a multi-platform project:
- project
  - common
  - android
  - ios

Root project has the following build script
```gradle
buildscript {
    ext.kotlin_version = '1.2.71'
    ext.konan_version = '0.9.1'

    repositories {
        google()
        jcenter()
        maven {
            url  "https://dl.bintray.com/jetbrains/kotlin-native-dependencies"
        }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0-alpha11'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlin:kotlin-native-gradle-plugin:$konan_version"
    }
}

subprojects {
    repositories {
        google()
        jcenter()
    }
}
```
Common applies
```gradle
apply plugin: 'kotlin-platform-common'
```
iOS applies
```gradle
apply plugin: 'kotlin-platform-native'
```
Android applies
```gradle
apply plugin: 'com.android.library'
apply plugin: 'kotlin-platform-android'
```
At this pont everyting compiles and runs.

As soon as I add kotlinx-serialization classpath to the root build script:
```gradle
dependencies {
    // ...
    classpath "org.jetbrains.kotlinx:kotlinx-gradle-serialization-plugin:$serialization_version"
}
``` 
Android project says: ```Plugin with id 'com.android.library' not found.```

Is it a known problem or my project setup is incorrect?

Thank you in advance!

P.S: The full (failing) build script of the root project is:
```gradle
buildscript {
    ext.kotlin_version = '1.2.71'
    ext.konan_version = '0.9.1'
    ext.serialization_version = 'v0.8.0-rc13'

    repositories {
        google()
        jcenter()
        maven {
            url  "https://dl.bintray.com/jetbrains/kotlin-native-dependencies"
        }
        maven {
            url "https://kotlin.bintray.com/kotlinx"
        }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.3.0-alpha11'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlin:kotlin-native-gradle-plugin:$konan_version"
        classpath "org.jetbrains.kotlinx:kotlinx-gradle-serialization-plugin:$serialization_version"
    }
}

subprojects {
    repositories {
        google()
        jcenter()
    }
}
```

**Comment by sandwwraith** [comment]
I don't know why it complains about missing `com.android.library`, but kotlinx.serialization plugin is definitely missing because `0.8.0-rc13` is intended to use with Kotlin 1.3-RC, where serialization is bundled, and therefore there are no artifact with coordinates `org.jetbrains.kotlinx:kotlinx-gradle-serialization-plugin:0.8.0-rc13`.

To use it with Kotlin 1.2.71, use 0.6.2 version. To use with 1.3-RC, use updated maven coordinates which are stated in this doc: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/eap13.md

**Comment by yuriry** [comment]
Thank you for the prompt response!

When I changed serialization_version to ```v0.6.2``` I got the same error.  My setup is such that the multi-platform root project is a part of [a gradle composite build](https://docs.gradle.org/current/userguide/composite_builds.html), i.e., a git sub-module of a larger Android App project and included into the larger Android App project using ```includeBuild 'my-mpp'```.

When I cloned the root project into a seperate folder as a stand-alone project (not as a git sub-module of the larger Android App project), the error has gone away.  It is definetly related to my setup.

After getting rid of the original ```Plugin with id 'com.android.library' not found``` problem I applied ```kotlinx-serialization``` to my common project, so that it looks like this now:
```
apply plugin: 'kotlin-platform-common'
apply plugin: 'kotlinx-serialization'
// ...
```
Now the error is ```Plugin with id 'kotlinx-serialization' not found.```. 

Do I need to apply this plugin?  Both [example-native](https://github.com/Kotlin/kotlinx.serialization/blob/eap13/example-native/build.gradle) and [example-ios](https://github.com/Kotlin/kotlinx.serialization/blob/eap13/example-ios/build.gradle) don't apply ```kotlinx-serialization``` and only apply ```kotlin-platform-native```, but [documentation](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/eap13.md) says it should be applied.

**Comment by yuriry** [comment]
The problem was in my setup.  Putting all dependencies into build.gradle of the root project does not work.  After moving buildscripts into individual projects, leaving only required parts for each project, I was able to assemble all sub-projects of the multi-platform prject, and event integrated back the multi-platform prject into the larger Android App project using Gradle composite build (```includeBuild 'my-mpp'```).

The setup looks like this:

Root gradle.build:
```gradle
buildscript {
    ext.kotlin_version = '1.2.70'
    ext.kotlinNativeUrl = "https://dl.bintray.com/jetbrains/kotlin-native-dependencies"
    ext.kotlin_native_version = '0.9.2'
    ext.serializationUrl = "https://kotlin.bintray.com/kotlinx"
    ext.serialization_version = '0.6.2'
}
```

Common gradle.build:
```gradle
buildscript {
    repositories {
        jcenter()
        maven { url serializationUrl }
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlinx:kotlinx-gradle-serialization-plugin:$serialization_version"
    }
}

apply plugin: 'kotlin-platform-common'
apply plugin: 'kotlinx-serialization'

repositories {
    jcenter()
    maven { url serializationUrl }
}
// ...
```

iOS gradle.build:
```gradle
buildscript {
    repositories {
        jcenter()
        maven { url  kotlinNativeUrl }
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlin:kotlin-native-gradle-plugin:$kotlin_native_version"
    }
}

apply plugin: 'kotlin-platform-native'

repositories {
    jcenter()
}
// ...
```

Android gradle.build:
```gradle
buildscript {
    repositories {
        jcenter()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
    }
}

apply plugin: 'com.android.library'
apply plugin: 'kotlin-platform-android'

repositories {
    jcenter()
    google()
}
// ...
```

**Comment by tajalagawani** [comment]
apply plugin: 'kotlin-platform-native'
