### ISSUE TITLE
Failure to decode nullable enum when coerceInputValues and explicitNulls are set to true. 

### ISSUE THREAD

**Issue by vshivam** [Kotlin/kotlinx.serialization#2224]
Given, ` coerceInputValues` and `explicitNulls` are set to `true`. 

When decoding a json string after converting it to a json element, a nullable enum is not parsed to `null` when the property does not exist in the json string. 

```
java.util.NoSuchElementException: Key theme is missing in the map.
	at kotlin.collections.MapsKt__MapWithDefaultKt.getOrImplicitDefaultNullable(MapWithDefault.kt:24)
```
The same string when parsed directly (without converting to json element) successfully parses and the enum value is set to null. 

**To Reproduce**
```
class InfoCardRawTest {

    @Serializable
    sealed class Card {
        abstract val theme: Theme?
    }

    @Serializable
    enum class Theme {
        @SerialName("dark")
        DARK
    }

    @Serializable
    @SerialName("card")
    data class InfoCard(
        val type: String,
        val title: String?,
        override val theme: Theme?
    ) : Card()

    val json = Json {
        coerceInputValues = true
        explicitNulls = false
    }

    private val raw = """
        {
            "type": "card"
        }
    """.trimIndent()

    // Fails
    @Test
    fun verifyDecodingFromJsonElement() {
        assertEquals(
            json.decodeFromJsonElement(json.parseToJsonElement(raw)),
            InfoCard(
                type = "card",
                title = null,
                theme = null
            )
        )
    }

    // passes
    @Test
    fun verifyDecodingFromJsonString() {
        assertEquals(
            json.decodeFromString(raw), InfoCard(
                type = "card",
                title = null,
                theme = null
            )
        )
    }
}
```

**Expected behavior**
Json element is parsed successfully and enum is set to null (since `explicitNulls` is set to `false`) 

**Environment**
 - Kotlin version: 1.7.21
 - Library version: 1.3.3
 - Kotlin platforms: Android
 - Android gradle plugin: 7.3.0

**Comment by vshivam** [comment]
Seems to be a duplicate of this: https://github.com/Kotlin/kotlinx.serialization/issues/2222

**Comment by sandwwraith** [comment]
#2170 ? Check 1.5.0 version

**Comment by vshivam** [comment]
@sandwwraith Thanks for taking a look! I just tried the 1.5.0 version but ran into the same problem. The [linked PR](https://github.com/Kotlin/kotlinx.serialization/pull/2176) likely solves this problem when parsing json strings. When I try to decode a Json element however, this problem still exists.

**Comment by sandwwraith** [comment]
Then it's a duplicate of #2222 indeed.
