### ISSUE TITLE
How to use 1.3.0-rc-57?

### ISSUE THREAD

**Issue by yuriry** [Kotlin/kotlinx.serialization#223]
I'm following [eap13 document](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/eap13.md), use configuration described in the document, but am getting an error:
```
Could not find org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.0-rc-57.
Searched in the following locations:
    https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.0-rc-57/kotlin-gradle-plugin-1.3.0-rc-57.module
    https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin/1.3.0-rc-57/kotlin-gradle-plugin-1.3.0-rc-57.pom
```
It looks like there is no 1.3.0-rc-57 at this URI:

https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-gradle-plugin

How to configure build script to start using 1.3.0-rc-57?

I use IntelliJ 2018.2.4 (CE), [Kotlin 1.3.0-rc-57-IJ2018.2-1 Plugin](https://plugins.jetbrains.com/plugin/6954-kotlin/update/50135), Gradle 4.7, serialization 0.8.1-rc13, delegated build to Gradle as described in [eap13 document](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/eap13.md), and re-imported the project from scratch after updating to the new Kotlin plugin.

Thank you in advance!

**Comment by sandwwraith** [comment]
Add  `https://dl.bintray.com/kotlin/kotlin-eap` as a repository for the build script and your projects, like:

```gradle
repositories {
        jcenter()
        maven { url "https://dl.bintray.com/kotlin/kotlin-eap" }
}
```

Sorry I forgot to mention that in the document, it was in the [blogpost](https://blog.jetbrains.com/kotlin/2018/09/kotlin-1-3-rc-is-here-migrate-your-coroutines/) for 1.3-RC.

**Comment by yuriry** [comment]
Thank you very much, that fixed it!
