### ISSUE TITLE
Sealed interface can't be deserialized with default Json configuration

### ISSUE THREAD

**Issue by syt0r** [Kotlin/kotlinx.serialization#2233]
**Describe the bug**
I have sealed interface with nested sealed interfaces called `MainDestination`, I'm serializing data with following snippet:
`Json.encodeToString(MainDestination.serializer(), destination)`

When it's getting serialized `type` field is added to json with class, but if I try to deserialize it with default `Json` using `decodeFromString(String)` method it throws an exception

```
Process: ua.syt0r.kanji.fdroid.dev, PID: 24110
                 kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 2: Encountered an unknown key 'type' at path: $
                 Use 'ignoreUnknownKeys = true' in 'Json {}' builder to ignore unknown keys.
                 JSON input: {"type":"ua.syt0r.kanji.presentation.screen.main.MainDestination.PracticePreview","id":1}
```
Object is properly deserialized when ignoreUnknownKeys = true option is used

**Expected behavior**
I think sealed interface deserialization should work out of the box without using ignoreUnknownKeys = true option

**Environment**
 - Kotlin version:1.7.20
 - Library version: 1.5.0
 - Kotlin platforms: Android

**Comment by sandwwraith** [comment]
It looks like that `decodeFromString` is using an incorrect return type. Try to use `decodeFromString<MainDestination>()`

**Comment by syt0r** [comment]
I see, I was using generic reified function with the exact type. I can confirm it works with interface + class cast
