### ISSUE TITLE
We can't restore deserialize after error

### ISSUE THREAD

**Issue by alekseytomin** [Kotlin/kotlinx.serialization#2238]
**Describe the bug**

1. Write you own Serializer.
2. Try to support old format - string instead of object.
3. deserialize will be failed.

**To Reproduce**
Attach a code snippet or test data if possible.

```
object MyClassSerializer : KSerializer<MyClass> {
...
override fun deserialize(decoder: Decoder): MyClass {
    return try {
           val composite = decoder.beginStructure(descriptor)
...
    } catch (e: Exception) {
        MyClass(String.serializer().deserialize(decoder))
    }
}
```

It can be fixed in `StreamingJsonDecoder#beginStructure` (for example):
Before:
```
        lexer.path.pushDescriptor(descriptor)
        lexer.consumeNextToken(newMode.begin)
```
After:
```
        lexer.path.pushDescriptor(descriptor)
        try {
            lexer.consumeNextToken(newMode.begin)
        } catch (e: Exception) {
            lexer.path.popDescriptor()
            throw e
        }
```

**Expected behavior**

**Environment**
 - Kotlin version: 1.8.20-RC
 - Library version: 1.5.0
 - Kotlin platforms: JVM
 - Gradle version: 8.0.2

**Comment by sandwwraith** [comment]
There are no exception safety guarantees for decoders (see 'Exception safety' section here: https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-core/kotlinx.serialization.encoding/-decoder/). To implement various fallback strategies, it is recommended to use various techniques of json transformation: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#json-transformations
