### ISSUE TITLE
Serialization dependency for building an iOS framework

### ISSUE THREAD

**Issue by yuriry** [Kotlin/kotlinx.serialization#224]
After migrating to Kotlin 1.3 RC and serialization 0.8.1-rc13 with the help of [this post](https://github.com/Kotlin/kotlinx.serialization/issues/223#issuecomment-424595546) I can build common and android subprojects, and wanted to ask about iOS build.  What should I put in ```dependencies``` sections of the iOS project to support serialization?

When I have
```gradle
dependencies {
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime:$serialization_version"
    expectedBy project(':common')
}
```
(```ext.serialization_version = '0.8.1-rc13'```)

I get
```
> Task :ios:compileDebugIos_arm64KotlinNative
error: compilation failed: Unexpected file extension: jar

 * Source files: Foo.kt, Bar.kt
 * Compiler version info: Konan: 0.9.2 / Kotlin: 1.3.0
 * Output kind: FRAMEWORK

exception: java.lang.IllegalStateException: Unexpected file extension: jar
	at org.jetbrains.kotlin.konan.library.impl.KonanLibraryLayoutImplKt.zippedKonanLibraryChecks(KonanLibraryLayoutImpl.kt:40)
	at org.jetbrains.kotlin.konan.library.impl.ZippedKonanLibraryLayout.<init>(KonanLibraryLayoutImpl.kt:18)
    ...
```
which makes sense because iOS build does not work with jars.
When I remove dependency on sertialization rutime:
```gradle
dependencies {
    expectedBy project(':common')
}
```
I get errors about unresolved symbols
```
> Task :ios:compileDebugIos_arm64KotlinNative FAILED
common/src/main/kotlin/com/microsoft/sharepoint/communication/serialization/sharepoint/SiteActivities.kt:3:16: error: unresolved reference: serialization
import kotlinx.serialization.KSerializer
               ^
common/src/main/kotlin/com/microsoft/sharepoint/communication/serialization/sharepoint/SiteActivities.kt:4:16: error: unresolved reference: serialization
import kotlinx.serialization.Serializable

...
 ```
which also makes sense.

[This sample](https://github.com/Kotlin/kotlinx.serialization/blob/eap13/example-ios/build.gradle) uses ```implementation "org.jetbrains.kotlinx:jsonparser-native:0.6.1"```, but when I put this line in my dependencies section, I'm getting this error:
```
jsonparser-native.klib. The compiler versions don't match. Expected '[0.9.2]', found 'null'
```
What is the right serialization dependency for building an iOS framework?

**Comment by yuriry** [comment]
It seems the answer is ```kotlinx-serialization-runtime-native```
```gradle
dependencies {
    implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime-native:$serialization_version"
    expectedBy project(':common')
}
```
I probably can close this issue.

**Comment by yuriry** [comment]
@sandwwraith  It is nice that you guys give easy to understand compilation errors when compiling an iOS framework if [unsupported features](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/eap13.md#native) are used.

**Comment by LOG-TAG** [comment]
@yuriry so we can't run other normal java dependency jar in ios/macOS using konan? for example, say slf4j-api-1.7.21.jar ? we need a native version of slf4j?

**Comment by sandwwraith** [comment]
@LOG-TAG No, Kotlin/Native does not compile jars for macOS, it works another way.
