### ISSUE TITLE
Polymorphic problems with String

### ISSUE THREAD

**Issue by Ray-MS** [Kotlin/kotlinx.serialization#2249]
The same key may correspond to different types of values in json

```
import kotlinx.serialization.Polymorphic
import kotlinx.serialization.Serializable
import kotlinx.serialization.decodeFromString
import kotlinx.serialization.json.Json
import kotlinx.serialization.modules.SerializersModule
import kotlinx.serialization.modules.polymorphic
import kotlinx.serialization.modules.subclass

@Serializable
class Rank(
    val name: String,
    @Polymorphic
    val rank: Any
){
    override fun toString(): String {
        return "Rank(name=$name,rank=$rank)"
    }
}


fun main() {
    val module = SerializersModule {
        polymorphic(Any::class) {
            subclass(Int::class)
            subclass(String::class)
        }
    }
    val parser = Json {
        serializersModule = module
    }

    val json1 = """{"name":"Alice","rank":99}"""
    val rank1 = parser.decodeFromString<Rank>(json1)
    println(rank1)

    val json2 = """{"name":"Alice","rank":"3%"}"""
    val rank2 = parser.decodeFromString<Rank>(json2)
    println(rank2)
}
```

But it seems failed with STRING
Serializer for String of kind STRING cannot be serialized polymorphically with class discriminator.

**Comment by sandwwraith** [comment]
I think it shouldn't work with Int too. As these types are primitive, there's no place to include `type` key with type info. Therefore, primitive types are prohibited from polymorphic serialization.

To get 'Int or String' field, use `JsonElement` instead of `Any`

**Comment by pdvrieze** [comment]
Primitives might/should work if the polymorphic information is external (not the "normal" way to serialize types in JSON). You'd get `rank={type='kotlin.Int' value=99 }`.

**Comment by Ray-MS** [comment]
> 

tkx, it works. I am quite a beginer in both java and kt.

**Comment by Ray-MS** [comment]
> Primitives might/should work if the polymorphic information is external (not the "normal" way to serialize types in JSON). You'd get `rank={type='kotlin.Int' value=99 }`.

It seems that I have a misunderstanding about polymorphic. "JsonElement" works. And I will learn more about java and kt.
