### ISSUE TITLE
Gets Class 'ArrayList' is not registered for polymorphic serialization in the scope of 'List'. error when using KClass

### ISSUE THREAD

**Issue by ShindongLee** [Kotlin/kotlinx.serialization#2250]
**Describe the bug**

I am implementing generic serializer/deserializer using `KClass<T>`. When I put List of certain class I get `Gets Class 'ArrayList' is not registered for polymorphic serialization in the scope of 'List'.` error. But in the document lists of serializable are serializables. 

**To Reproduce**
Attach a code snippet or test data if possible.

```kotlin
@Serializable
data class Something(
    val a: String,
    val b: Int,
)

@OptIn(InternalSerializationApi::class)
inline fun <reified T : Any> genericEncodeToString(value: T): String { // here reified/inlined is used for simple reproducing
    return Json.encodeToString(T::class.serializer(), value)
}

val somethings: List<Something> = listOf(Something("a", 1), Something("b", 2))
println(Json.encodeToString(somethings)) <--- works // [{"a":"a","b":1},{"a":"b","b":2}]
println(genericEncodeToString(somethings)) <--- error 
```

```
Class 'ArrayList' is not registered for polymorphic serialization in the scope of 'List'.
kotlinx.serialization.SerializationException: Class 'ArrayList' is not registered for polymorphic serialization in the scope of 'List'.
To be registered automatically, class 'ArrayList' has to be '@Serializable', and the base class 'List' has to be sealed and '@Serializable'.
Alternatively, register the serializer for 'ArrayList' explicitly in a corresponding SerializersModule.
	at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:102)
	at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:114)
	at kotlinx.serialization.PolymorphicSerializerKt.findPolymorphicSerializer(PolymorphicSerializer.kt:109)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:233)
	at kotlinx.serialization.json.internal.JsonStreamsKt.encodeByWriter(JsonStreams.kt:28)
	at kotlinx.serialization.json.Json.encodeToString(Json.kt:81)
```

I know Json.encodeToString(somethings) works, but in my code T is already general and not reified/inlined, so I want to use KClass or KType. With KClass I got above error and `KType` I gets Any type losing type T, since `serializersModule.serializer(type: KType)` returns type `KSerializer<Any?>`. How can I resolve this?

**Expected behavior**

serialized

**Environment**
 - Kotlin version: 1.8.10
 - Library version: 1.5.0
 - Kotlin platforms: JVM
 - Gradle version: 7.6

**Comment by sandwwraith** [comment]
It is not recommended to use `KClass.serializer()` function. See the [docs](https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-core/kotlinx.serialization/serializer.html): 

> This method uses platform-specific reflection available for the given erased KClass and is not recommended to use this method for anything, but last-ditch resort, e.g. when all type info is lost, your application has crashed and it is the final attempt to log or send some serializable data.

> The recommended way to retrieve the serializer is inline [serializer](https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-core/kotlinx.serialization/serializer.html) function and [serializer(KType)](https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-core/kotlinx.serialization/serializer.html)

Therefore you should use `KType`. You can obtain it with e.g., `typeOf<T>()` call. If your code is not reified, you do not have access to type T anyway, so KSerializer<Any> should work fine. If that's not good for you, you can make an unchecked cast to `KSerializer<T>`. 

Note that we deliberately accept only `List` KType, but not `ArrayList` or `LinkedList` classes because the serializer does not preserve the implementation type (it always returns an array list regardless of what the original implementation was).
