### ISSUE TITLE
Base KSerializer for multiple types (KSerializer to consume parse errors for optional fields)

### ISSUE THREAD

**Issue by ersen-lw** [Kotlin/kotlinx.serialization#2254]
**What is your use-case and why do you need this feature?**

Hi all, 

I want to increase the application's resilience by consuming JSON parse errors for specific fields that are optional and continue with the rest of the data. An entire response shouldn't be regarded as an error because one field that is optional could not be parsed due to bad or unexpected data. 

This is the data on a very small scale. We got an `Article` and that article object can contain some publish information among many other things. The frontend application marks `PublishInfo` as optional. It handles the case if the date is not present in which it will just display as much as it can from the `Article` object. 

```
@Serializable
class Article(
    val id : String,
    val publishInfo : PublishInfo? = null
)

@Serializable
class PublishInfo(
    val date : String? = null,
)
```

One day the API sends `PublishInfo` as an array instead of an object. Lets imagine this is not intended but an error on the API side. This causes a parse error because an object is expected instead of an array. Even though its optional the entire article will not show even though the remaining data is fine. 

This issue could happen potentially anywhere not just this article so I looked into making a `KSerializer` for the nullable type to check if its a `JsonObject` and to either delegate parsing or to return null. Since it could happen anywhere I figured I could make a marker interface and make each type implement it. If the data is fine then use the delegate seralizer otherwise return null.

```
interface SafetyMarker
```

```
@Serializable
class Article(
    val id : String,
    @Serializable(with = SafeOptionalObject::class)
    val publishInfo : PublishInfo? = null
): SafetyMarker

@Serializable
class PublishInfo(
    val date : String? = null,
) : SafetyMarker
```

```
class SafeOptionalObject(private val serializer: KSerializer<SafetyMarker?>) : KSerializer<SafetyMarker?> {

    override val descriptor: SerialDescriptor = buildClassSerialDescriptor("SafeOptionalObject")

    override fun deserialize(decoder: Decoder): SafetyMarker? {
        require(decoder is JsonDecoder)
        val json = decoder.decodeJsonElement()
        return if(json is JsonObject){
            decoder.decodeSerializableValue(serializer)
        } else {
            null
        }
    }

    override fun serialize(encoder: Encoder, value: SafetyMarker?) {
        encoder.encodeSerializableValue(serializer, value)
    }
}
```

This does not work. I get an error when compiling. 

```
org.jetbrains.kotlin.backend.common.BackendException: Backend Internal error: Exception during IR lowering

...


Caused by: java.lang.IllegalStateException: Null argument in ExpressionCodegen for parameter VALUE_PARAMETER name:serializer index:0 type:kotlinx.serialization.KSerializer<com.myapp.SafetyMarker?>
```

My understanding, the list of subclasses that are serialized cannot be determined at compile-time and must be explicitly registered at runtime. I looked into setting polymorphic serializers but this did not work.

If I replace `SafetyMarker` with `PublishInfo`, it works in my tests. 

```
    @Test
    fun `my test`(){
        val goodJson = """
            {
              "id": qwerty123,
              "publishInfo": {
                "date": "date1",
              }
            }
        """.trimIndent()


        val badJson = """
            {
              "id": qwerty123,
              "publishInfo": [
                {
                  "date": "date1",
                }
              ]
            }
        """.trimIndent()

        val goodData = jsonParser.decodeFromString<Article>(goodJson)
        val badData = jsonParser.decodeFromString<Article>(badJson)

        Assert.assertEquals(null, goodData.publishInfo?.date)
        Assert.assertEquals(badData, badData.publishInfo)
    }
```

**Describe the solution you'd like**

A KSerializer to serialize and deserialize many types in one implementation. 

- OR -

A way to consume JSON parse errors for optional fields.

**Comment by sandwwraith** [comment]
Have you read about creating custom json transformers here? https://github.com/JetBrains/kotlin/commit/8233421030104335a508822c9142c88d66183de8
Also pay attention to this doc: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#custom-serializers-for-a-generic-type

> An implementation of [KSerializer](https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-core/kotlinx.serialization/-k-serializer/index.html) for a regular type is written as an object, as we saw in this chapter's examples for the Color type. A generic class serializer is instantiated with serializers for its generic parameters. We saw this in the [Plugin-generated generic serializer](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#plugin-generated-generic-serializer) section. A custom serializer for a generic class must be a class with a constructor that accepts as many [KSerializer](https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-core/kotlinx.serialization/-k-serializer/index.html) parameters as the type has generic parameters.

In your code, `SafeOptionalObject` has one `KSerializer` parameter, but you apply it to `PublishInfo` that doesn't have any generic parameters, and this crashes the compiler. You should have no arguments in the `SafeOptionalObject` serializer (and therefore, it's likely to be specific). What you mean by 'A KSerializer to serialize and deserialize many types in one implementation.' is likely related to #1169, so I'll close this as a duplicate for now.
