### ISSUE TITLE
RPC/RMI support -- serialization of interface method calls

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.serialization#2259]
When writing RPC/RMI support with the help of kotlinx.serialization, we can model all the parameter and result types as serializable classes, but there is currently no way to conveniently model the request calls themselves. For example, consider the following RPC interface:

```
@Serializable // or new annotation - TBD
interface RemoveService {
    fun doSomething(request: SomethingRequest): SomethingResponse
    // may have other methods as well
}

@Serializable class SomethingRequest(...) 
@Serializable class SomethingResponse(...) 
```

What is needed, as a part of the Kotlin serialization library is a way to automatically construct a proxy object for the `RemoteService` (or any other "serializable" interface) that converts calls into the serialized form that can be later deserialized and converted back into invocations on an instance of such interface.

**Comment by elizarov** [comment]
Just add a note here that this kind of RPC/RMI infrastructure can be indeed implemented separately as a pure code-generation plugin like it was usually done in the olden days, e.g. given my `RemoveService` example, you can generate all the scaffolding code like this:

```
@Serializable class RemoteService_doSomething_Arguments(val request: SomethingRequest)
@Serializable sealed class RemoteService_doSomething_Result {
    class Success(val result: SomethingResponse) : RemoteService_doSomething_Result()
    class Failure(val faliure: Failure) : RemoteService_doSomething_Result()
}

// followed by generated proxy and stub classes for RemoteService interface.
```

**Comment by sandwwraith** [comment]
We've decided to go with Rpc approach in a separate library — https://github.com/Kotlin/kotlinx-rpc
