### ISSUE TITLE
Feature similar to gson TypeAdapter

### ISSUE THREAD

**Issue by hazra-mms** [Kotlin/kotlinx.serialization#2261]
**What is your use-case and why do you need this feature?**
We are currently using gson for serialization/deserialization in our project and was considering the kotlinx serialization as an alternative to this. We has a requirement where we convert field name for some of the objects for special use case ( i.e. replacing $ in a field name by \uFF04) which is currently implemented by implementing [TypeAdapter](https://www.javadoc.io/doc/com.google.code.gson/gson/2.8.1/com/google/gson/TypeAdapter.html) and registering that type adapter in the GsonBuilder. Does kotlinx serialization have something similar? 
**Describe the solution you'd like**
Would like to have some feature which would be able to accept specific type adapter in the factory while creating the json instance.

In case there are such feature available please feel free to update the ticket accordingly. Thank you.

**Comment by sandwwraith** [comment]
No, we do not have any kind of global configuration. You can use any methods described in the [documentation](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#specifying-serializer-on-a-property) to override serializer: `@file:UseSerializers`, custom type alias, or contextual configuration.

also, it was discussed a bit here: #507, so I'll close this as a duplicate
