### ISSUE TITLE
Inexplicable crash in release build with `implementation` dependency of JSON library

### ISSUE THREAD

**Issue by Michael-pspdf** [Kotlin/kotlinx.serialization#2263]
**Describe the bug**
We're using serialization in a library. Everything works fine in debug mode, but if we do a release build we crash at runtime with

`java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/serialization/builtins/BuiltinSerializersKt;`

We found out that changing the `org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.0` dependency from `implementation` to `api` solves the crash, but we don't really understand why, since serialization is only used within the library and not in the app that uses it.

Any hint why this might happen would be much appreciated.

**To Reproduce**
Instantiating a class like this one causes the crash.

```kotlin
class MyClass {
    val inputSerializer: SerializationStrategy<Unit> = Unit.serializer()
    val resultDeserializer: DeserializationStrategy<List<String>> = ListSerializer(String.serializer())
}
``` 

**Expected behavior**
To not crash if we add the JSON library as non transitive dependency

**Environment**
 - Kotlin version: 1.8.10
 - Library version: 1.5.0
 - Kotlin platforms: JVM
 - Gradle version: 7.5.1
 - IDE version -
 - Other relevant context -

**Comment by sandwwraith** [comment]
You have a library with a dependency on Json and an app with a dependency on the library, right? Do you use anything serialization-related from the app? Like `@Serializable` annotation? Where is `MyClass` located?

**Comment by Michael-pspdf** [comment]
Apologies for the wait.
Yes, you're right - the library depends on Json, the app depends on the library but does not do anything with serialization on its own.
For some reason the issue resolved itself when we switched from referencing the aar directly to use maven to include our library in the app.
