### ISSUE TITLE
Implicit generic doesn't pick up `typealias` serializer

### ISSUE THREAD

**Issue by BenWoodworth** [Kotlin/kotlinx.serialization#2264]
**Describe the bug**
When calling `serializer()` with an implicit type argument for a `@Serializable` typealias, the typealias is effectively ignored, and the actual type is used instead

**To Reproduce**
```kt
import kotlinx.serialization.*
import kotlinx.serialization.builtins.serializer
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.*
import kotlinx.serialization.json.Json

private typealias SerializableMyClass = @Serializable(MyClassSerializer::class) MyClass
//                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

class MyClass(val a: String)

object MyClassSerializer : KSerializer<MyClass> {
    override val descriptor: SerialDescriptor = String.serializer().descriptor

    override fun serialize(encoder: Encoder, value: MyClass): Unit =
        encoder.encodeString(value.a)

    override fun deserialize(decoder: Decoder): MyClass =
        MyClass(decoder.decodeString())
}

fun main(args: Array<String>) {
    val value = SerializableMyClass("A")

    Json.encodeToString(value) // Serializer for class 'MyClass' is not found.

    // inlines to this
    Json.run {
        encodeToString(serializersModule.serializer(), value) // Serializer for class 'MyClass' is not found.
    }

    // But providing a "redundant" explicit generic fixes the issue
    Json.run {
        encodeToString<SerializableMyClass>(serializersModule.serializer(), value)
        //            ^^^^^^^^^^^^^^^^^^^^^ IDE suggests "Remove explicit type arguments"
    }

    // Or here
    Json.run {
        encodeToString(serializersModule.serializer<SerializableMyClass>(), value)
        //                                         ^^^^^^^^^^^^^^^^^^^^^
    }

    // But because the argument is lost during inlining, providing the type here doesn't help
    Json.encodeToString<SerializableMyClass>(value) // Serializer for class 'MyClass' is not found.




    // And similarly, this does not work
    Json.encodeToString(serializer(), value) // Serializer for class 'MyClass' is not found.

    // But this does work
    Json.encodeToString(serializer<SerializableMyClass>(), value)
}
```

**Expected behavior**
Serializer provided in the typealias is used, even when the generic is implicit

**Environment**
 - Kotlin version: 1.8.20
 - Library version: 1.5.0
 - Kotlin platforms: JVM IR
 - Gradle version: 7.4.2

**Comment by osrl** [comment]
I have a similar issue. So I didn't want to open a new issue, it might be related.

I’m trying to implement a serializer for a different kind of date format. which looks like this {"date": {"$date": 1688649908793} }  This is a global type so I wanted to specify a serializer globally as documented [here](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#specifying-serializer-globally-using-typealias). Here is what I did:

```kotlin
@Serializable
data class Result(
    val date: EDate
)

typealias EDate = @Serializable(EDateSerializer::class) Instant

@Serializable
//@SerialName("EDate")
//@SerialName("Instant")
data class InstantSurrogate(
    @SerialName("\$date")
    val date: Long
)

//@OptIn(ExperimentalSerializationApi::class)
//@Serializer(forClass = Instant::class)
object EDateSerializer : KSerializer<Instant> {
    override val descriptor: SerialDescriptor = InstantSurrogate.serializer().descriptor

    override fun serialize(encoder: Encoder, value: Instant) {
        val millisecond = value.toEpochMilliseconds()
        val eDate = InstantSurrogate(millisecond)

        encoder.encodeSerializableValue(InstantSurrogate.serializer(), eDate)
    }

    override fun deserialize(decoder: Decoder): Instant {
        val eDate = decoder.decodeSerializableValue(InstantSurrogate.serializer())
        return Instant.fromEpochMilliseconds(eDate.date)
    }
}
```

When I do this, serializer tries to use `InstantIso8601Serializer` instead of mine. (I've also tried the commented out lines and implementing `KSerializer<EDate>`). Is there something I'm missing here? Is this related to the

**Comment by osrl** [comment]
I guess this was related to #1895 . It works with 1.8.20

**Comment by BenWoodworth** [comment]
I was starting to think the same thing. I'll post an issue to the Kotlin youtrack and link it back here, since typealiases feels like something that should be propagated through implicit type args. And if it turns out to be something that won't be supported, then maybe leaving a note in the kxs docs about @Serializable in typealiases having that limitation

**Comment by sandwwraith** [comment]
By the way, specifying value type explicitly in your example works around the issue: `val value: SerializableMyClass = SerializableMyClass("A")`

**Comment by iseki0** [comment]
Maybe #2358 is more problemetic. The [official guide](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#specifying-serializer-globally-using-typealias) mentions this feature. But the feature is inconsistent when the original `@Serialization` annotation is exists.

**Comment by iseki0** [comment]
@sandwwraith 
Maybe https://github.com/Kotlin/kotlinx.serialization/issues/2358 is more problemetic. The [official guide](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#specifying-serializer-globally-using-typealias) mentions this feature. But the feature is inconsistent when the original @Serialization annotation is exists.

**Comment by sandwwraith** [comment]
As per https://youtrack.jetbrains.com/issue/KT-67252 and #2731, we won't support this use-case, so using explicit serializer is a way to go

**Comment by sandwwraith** [comment]
@iseki0 If you show us an example of such cases, we'll happily prohibit them as well 😄

**Comment by osrl** [comment]
```kotlin
// {"date": {"$date": 1688649908793} } 
@Serializable
data class Result(
    val date: EDate
)

typealias EDate = @Serializable(EDateSerializer::class) Instant

@Serializable
@SerialName("EDate")
data class InstantSurrogate(
    @SerialName("\$date")
    val date: Long,
)

object EDateSerializer : KSerializer<Instant> {
    override val descriptor: SerialDescriptor = InstantSurrogate.serializer().descriptor

    override fun serialize(encoder: Encoder, value: Instant) {
        val millisecond = value.toEpochMilliseconds()
        val eDate = InstantSurrogate(millisecond)

        encoder.encodeSerializableValue(InstantSurrogate.serializer(), eDate)
    }

    override fun deserialize(decoder: Decoder): Instant {
        val eDate = decoder.decodeSerializableValue(InstantSurrogate.serializer())
        return Instant.fromEpochMilliseconds(eDate.date)
    }
}

```

this works on 1.7.1 and kotlin 2.0.0. do what you need to do 🔫

**Comment by iseki0** [comment]
Lol, @osrl I always call it `JsonInstant`，I don't agree that's a good idea, but I have no better solution.

@sandwwraith Could you add a compiler options for static serializer assignation?

**Comment by osrl** [comment]
EDate is a spacial name for [EJSON](https://docs.meteor.com/api/ejson.html)

I couldn't understand what's not a good idea @iseki0

**Comment by iseki0** [comment]
> couldn't understand what's not a good idea @iseki0

You use a special name here. But for other tools? If there's also javax-serialization, databasex-serialization. How to do?

**Comment by osrl** [comment]
Oh okay, as I said, it's a special name for a special json format. so it's okay.

**Comment by sandwwraith** [comment]
> @sandwwraith Could you add a compiler options for static serializer assignation?

you are probably talking about #507, but this is a feature that is postponed for a long time
