### ISSUE TITLE
jvm/1.8.20 returns KSerializer<List<String>> instead of KSerializer<List<String?>>

### ISSUE THREAD

**Issue by simonegiacomelli** [Kotlin/kotlinx.serialization#2265]
**Describe the bug**
The serializer returned should be KSerializer<List<String>> but the expected type is KSerializer<List<String?>>.
In other words, it doesn't honor the nullability of the first generic type of the list.
It happens only on jvm/1.8.20. 
Workaround attached.

**To Reproduce**
[This repository](https://github.com/simonegiacomelli/kotlin-jvm-serializer-issue-1-8-20) reproduces the issue.
Btw all the code needed is this:
```
import kotlinx.serialization.KSerializer
import kotlinx.serialization.descriptors.elementDescriptors
import kotlinx.serialization.serializer
import kotlin.reflect.typeOf
import kotlin.test.Test
import kotlin.test.assertTrue

class IssueTest {

    /** This fails with jvm/1.8.20 */
    @Test
    fun test_issue() {
        assertTrue(listOfNullable<String>().descriptor.elementDescriptors.first().isNullable)
    }

    /** This works with all the combinations mentioned, i.e., js/jvm/1.8.20 and js/jvm/1.8.10 */
    @Test
    fun test_workaround() {
        assertTrue(workaround<String>().descriptor.elementDescriptors.first().isNullable)
    }
}

inline fun <reified T> listOfNullable(): KSerializer<List<Any?>> = serializer<List<T?>>() as KSerializer<List<Any?>>
inline fun <reified T> workaround(): KSerializer<List<Any?>> = serializer(typeOf<List<T?>>()) as KSerializer<List<Any?>>

```

**Expected behavior**
It should return a `KSerializer<List<String?>>`

**Environment**
 - Kotlin version: 1.8.20
 - Library version: org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.0 
 - Kotlin platforms: 1.8.20/jvm affected
 - Gradle version: 7.4.2
 - jvm: 1.8.0_312 (Amazon.com Inc. 25.312-b07)

**Comment by sandwwraith** [comment]
Fixed in Kotlin 1.8.21
