### ISSUE TITLE
Polymorphism on open class does not work if I registered it as polymorphic via SerializersModuleBuilder.

### ISSUE THREAD

**Issue by delopst** [Kotlin/kotlinx.serialization#2269]
Polymorphism of open class does not work even if I registered it as polymorphic via SerializersModuleBuilder.

```
@ExperimentalJsonSerialization
object CustomKotlinJsonSerializer {
    @OptIn(ExperimentalSerializationApi::class)
    val json: Json = Json {
        //namingStrategy = CustomPropertyNamingStrategy
        serializersModule = SerializersModule {
            polymorphic(Value::class) {
                subclass(CodedText::class)
                subclass(Text::class)
            }
            polymorphic(Text::class) {
                subclass(CodedText::class)
                subclass(Text::class)
            }

            //polymorphic(Text::class) {
            //   subclass(CodedText::class)
            //}
        }
        classDiscriminator = "@class"
        ignoreUnknownKeys = false
        encodeDefaults = true
    }
}

@Serializable
@SerialName("VALUE")
abstract class Value  {}

@Serializable
@SerialName("TEXT")
open class Text : Value {
   var value: String? = null
}

@Serializable
@SerialName("CODED_TEXT")
class CodedText : Text {
   var code: String? = null
}
```

I have registered the Text as polymorphic. I have tried both ways:

```
polymorphic(Text::class) {
       subclass(CodedText::class)
}
```

or 

```
polymorphic(Text::class) {
       subclass(CodedText::class)
       subclass(Text::class)
}
```

Even if CodedText is used, the class discriminator will always be TEXT. 
I would expect that since classes are registered as polymorphic in advance, the class discriminator will be CODED_TEXT when CodedText is used.

**Environment**
 - Kotlin version: 1.8.0
 - Library version: 1.5.0-RC
 - Kotlin platforms: JVM

**Comment by Sage-Kreiter** [comment]
Similar problem for me. In version 1.4.1 I had a hierarchy of classes that were marked as `@Polymorphic` and I created a `SerializerModule` to serialize them. It all worked well in 1.4.1 but 1.5.0 seems to break it

**Comment by delopst** [comment]
Tryed to reproduce but after adding @Polymorphic this is working.

Closing the issue.
