### ISSUE TITLE
Support WASM target

### ISSUE THREAD

**Issue by bmalkow** [Kotlin/kotlinx.serialization#2271]
Would you like to add `wasm` target to library, please?

**Comment by icecreamparlor** [comment]
Same issue here.

**Comment by sandwwraith** [comment]
WASM target is being worked on by the wasm team (see work in progress here: #2253). It will be published separately from the main library, though, as WASM is not stable enough yet.

**Comment by andylamax** [comment]
What do you mean it will be publish seperately?? like in seperate maven coordinates?? @sandwwraith

**Comment by sandwwraith** [comment]
Not in maven central. So you'll need to add additional repository

**Comment by igoriakovlev** [comment]
kotlinx-serialization 1.5.1-wasm0 was published to [here](https://maven.pkg.jetbrains.space/kotlin/p/wasm/experimental)
(except kotlinx-serialization-json-okio)

You can use it with dev version of kotlin 1.9.0-dev-6584 or later which is published to [here](https://maven.pkg.jetbrains.space/kotlin/p/kotlin/dev)

**Comment by igoriakovlev** [comment]
The libraries were republished with same version and now they are depends on snapshot version of the Kotlin compiler (which is going to be persistent in repo).
Please use compiler 1.9.0-dev-6584 or later which is published into [here](https://maven.pkg.jetbrains.space/kotlin/p/kotlin/bootstrap)

**Comment by Skaldebane** [comment]
How to use this today (with a Compose Multiplatform project)?
