### ISSUE TITLE
Reading xml with bom

### ISSUE THREAD

**Issue by JajaComp** [Kotlin/kotlinx.serialization#2275]
Hi! Can i deserialize utf-8 string with bom bytes in begin?

Now i wrote plugin, but think is bad solution:
```
private val BOM_START = byteArrayOf(-17, -69, -65)

suspend fun wrapBody(content: ByteReadChannel): ByteReadChannel {
        val bodyArray = content.toByteArray()
        val bomStartOffset = bodyArray.bomStartOffset()
        return ByteReadChannel(bodyArray, bomStartOffset, bodyArray.size - bomStartOffset)
}

private fun ByteArray.bomStartOffset(): Int {
            if (this.size < BOM_START.size) {
                return 0
            }
            BOM_START.forEachIndexed { index, byte ->
                if (this[index] != byte) {
                    return 0
                }
            }
            return BOM_START.size
}
```

**Comment by sandwwraith** [comment]
XML support is located in a separate library, please file the issue there. Are there any problems regarding BOM in JSON?

**Comment by JajaComp** [comment]
I use https://github.com/pdvrieze/xmlutil but i'm not sure if this is the task of the parsing library. Okhttp have build in converter for body reading (https://github.com/siwangqishiq/OkHttpClient/blob/master/app/src/main/java/okhttp3/ResponseBody.java) but i can't use this feature over ktor.

**Comment by sandwwraith** [comment]
I don't see how it is related to kotlinx.serialization then. We do not provide any ByteReadChannel-related methods, so it's either a Ktor or XMLUtil problem.

**Comment by JajaComp** [comment]
Lol. I mixed up the repositories. I thought I was writing to ktor) I need to rest more. Sorry)
