### ISSUE TITLE
Deserializing value with % sign in the end of string 

### ISSUE THREAD

**Issue by froz3nice** [Kotlin/kotlinx.serialization#2281]
Unable to parse json string coming from backend
```
{
    "data": {
	    "percent": "100%",
	    "name": "orange"
    }
}
```
I get the following error: 

`kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset : Expected end of the object or comma at path: $ JSON ,"percent":"100 �??`

Able to reprocude this with Polymorphic deserializer.
 
deserializing works when i change json line into "percent": "100% ", however the % sign is transformed into unicode replacement character �.

using regular ` Json{}.decodeFromString()` function

**Environment**
 - Kotlin version: 1.8.10
 - Library version: 1.5.0
 - Kotlin platforms: jvm
 - Gradle version: 7.4.2
 - IDE version: Android Studio Flamingo | 2022.2.1

**Comment by sandwwraith** [comment]
Hi, I wrote the following test, and it works fine for me:

```
    @Serializable
    data class Outer(val data: Inner)

    @Serializable
    data class Inner(val percent: String, val name: String)

    @Test
    fun testPercent() {
        val str = """{
    "data": {
	    "percent": "100%",
	    "name": "orange"
    }
}"""

        println(Json.decodeFromString<Outer>(str))
        println(Json.parseToJsonElement(str))
    }
```

So maybe your percentage sign is not the real percentage sign but something else. Or it has something to do with non-standard whitespace or quotation characters. Can you please re-check your raw input data and send it to us?

**Comment by froz3nice** [comment]
`@OptIn(ExperimentalMaterial3Api::class, ExperimentalAnimationApi::class)
class MainActivity : ComponentActivity() {

    @OptIn(ExperimentalMaterial3Api::class)
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            ComposetestingTheme {
                Scaffold(
                    content = { innerPadding ->
                        val navController = rememberAnimatedNavController()
                        Spacer(Modifier.padding(innerPadding))
                        AnimatedNavHost(
                            modifier = Modifier,
                            navController =  navController,
                            startDestination = "home",
                            builder = {
                                composable(
                                    route = "screen1?data={data}",
                                    arguments = listOf(
                                        navArgument("data") {
                                            type = NavType.StringType
                                        },
                                    ),
                                ) { backStack ->
                                    val historyData = backStack.arguments?.getString("data") ?: ""
                                    val outer = Json{}.decodeFromString<Outer>(historyData)
                                    Greeting(outer.data.percent)
                                }

                                composable(route = "home") {
                                    HomeScreen(navController)
                                }
                            }
                        )
                    }
                )

            }
        }
    }
}


@Serializable
data class Outer(
    val data: Inner
)
@Serializable
data class Inner(
    val percent: String
)

@Composable
fun HomeScreen(navController: NavHostController) {
    Column(Modifier.fillMaxSize()) {
        Button(onClick = {
            navController.navigate("screen1?data={\"data\": {\"percent\": \"100%\"}}")
        }){
            Text(text = "test")
        }
    }
}

@Composable
fun Greeting(name: String) {
    Column(Modifier.fillMaxSize()) {
        Text(text = "Hello $name!")
    }
}`

here's an example how to reproduce it. Turns out it might be compose navigation problem too

**Comment by froz3nice** [comment]
Turns out it was compose navigation problem. Needed to encode json like this `java.net.URLEncoder.encode(data, "UTF-8")` Closing it
