### ISSUE TITLE
kotlinx.serialization.SerializationException: Serializer for class is not found. When using a generic type.

### ISSUE THREAD

**Issue by frellan** [Kotlin/kotlinx.serialization#2282]
**Describe the bug**
I cannot get serialization to work using this library with ktor. There is some problem with using a generic class but the error messages makes no sense and I have tried all sorts of different combinations. I get this error.

```
kotlinx.serialization.SerializationException: Serializer for class 'DirectusGetItemsResponse' is not found.
Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.
```

I have also seen these when tying to parse a string instead of using the body<T> method.
```
kotlinx.serialization.SerializationException: Class 'ArrayList' is not registered for polymorphic serialization in the scope of 'List'.
```
or
```
kotlinx.serialization Parameter specified as non-null is null
```

None makes any sense to me. Using a generic class should just work?

**To Reproduce**
I have this client that takes a generic parameter on what to return and serialize into. The response from the api looks like this:
```
{
  data: {
    // different structures
  }
}
```
```
@Serializable
private data class DirectusGetItemsResponse<T>(val data: List<T>)

class DirectusClient(private val http: HttpClient) {
  suspend fun <T> getItems(
        collection: String,
    ): List<T> {
        return http.get("items/$collection").body<DirectusGetItemsResponse<T>>().data
    }
}
```

I then call this function like this:

```
suspend fun findAll(): List<Food> = client.getItems(
        collection = "foods",
)
```

Food class
```
@Serializable
data class Food(
    val id: Int,
    @SerialName("banned_in_diets") val bannedInDiets: List<String>,
)
```

**Expected behavior**
The type should be known and it should serialize. The error messages suggest that `Any` is passed or something instead.

**Environment**
 - Kotlin version: 1.8.10
 - Library version: 1.5.0
 - Kotlin platforms: JVM
 - Gradle version: 7.3
 - Other relevant context: Ktor

**Comment by frellan** [comment]
Okay. If I leave out the generics I get this error still. Wtf.
```
kotlinx.serialization.SerializationException: Class 'ArrayList' is not registered for polymorphic serialization in the scope of 'List'.
To be registered automatically, class 'ArrayList' has to be '@Serializable', and the base class 'List' has to be sealed and '@Serializable'.
Alternatively, register the serializer for 'ArrayList' explicitly in a corresponding SerializersModule.
```

**Comment by sandwwraith** [comment]
I think you should have `reified T` in your `getItems`. Without reification, the type is unknown and gets coerced to `Any`.

**Comment by frellan** [comment]
@sandwwraith  Thank you for responding!

I have modified the code like this now:

```
@Serializable
@Polymorphic
sealed class DirectusGetItemsResponse<out T>

@Serializable
data class DirectusGetItemsResponseData<out T>(val data: List<T>) : DirectusGetItemsResponse<T>()

class DirectusClient(val http: HttpClient) {
    suspend inline fun <reified T> getItems(
        collection: String,
    ): List<T> {
        val response = http.get("items/$collection").body<JsonObject>()
        val json = Json.decodeFromString<DirectusGetItemsResponse<T>>(response.toString())
        return if (json is DirectusGetItemsResponseData) json.data else emptyList()
    }
}
```
But now I get this:
```
kotlinx.serialization.json.internal.JsonDecodingException: Polymorphic serializer was not found for missing class discriminator ('null')
```

I also have this config:

```
Json {
                                      serializersModule = SerializersModule {
                                          polymorphic(DirectusGetItemsResponse::class) {
                                              subclass(
                                                  DirectusGetItemsResponseData.serializer(
                                                      PolymorphicSerializer(
                                                          Any::class
                                                      ).nullable
                                                  )
                                              )
                                          }
                                      }
                                  })
```

All I want is for the functions to take a type parameter. I mean, the library dont have to guess the type here, I provide it when I call the function, like above for `findAll(): List<Food>`. I am terribly lost on this...

**Comment by sandwwraith** [comment]
It seems that your Json doesn't have the `type` key in it, therefore polymorphism can't work. You have following options:

1. Use `DirectusGetItemsResponseData` in `decodeFromString`, if it is the only subclass you're deserializing.
2. Add `default` to `serializersModule { polymorphic { }}` builder and specify serializer which you want to use when `type` key is missing. (https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md#default-polymorphic-type-handler-for-deserialization)
3. Use content-based json deserializer (https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#content-based-polymorphic-deserialization)

By the way, `@Polymorphic` is not required for sealed classes, as they have it by default. Module is also not needed (unless you go with option 2).
