### ISSUE TITLE
Provide a way to get the annotated type during serializer initialization

### ISSUE THREAD

**Issue by iseki0** [Kotlin/kotlinx.serialization#2283]
**What is your use-case and why do you need this feature?**
I'm planning to create a KSP-based codegen to generate data class and builder from interface. I found it's difficult to enable the serialization  to the generated data class.

The user need create an interface. And the builder and data class will be auto-generated during build process(by KSP):
```kotlin
@Serialization(???) // problem, should reference generated-serializer of the implementation
interface ISomething{
    val foo: String
}

// The following code is generated by annotation processor
@Serialization
internal data class Something(val foo: String): ISomething
```
The problem is the serializer of the generated class doesn't exists before build. So the user can't reference it on the interface.

**Describe the solution you'd like**

I can provide a delegated serializer. Since I can get the interface type that annotated, dynamic load the correct serializer by a little reflection is possible.

**Comment by sandwwraith** [comment]
Sorry, I'm not sure I understand the request correctly. Do you want to be able to specify `@Serializable(Something.$serializer::class)` on `interface ISomething` during generation of `Something` by your KSP plugin? Synthetic implementations of serializers are deliberately hidden from users, so I doubt it makes sense to open them. It is possible, however, to call `Something.serializer()` to get the serializer and it should be resolved during build time. Does that answer your question?

**Comment by iseki0** [comment]
@sandwwraith 
Is my English too bad? Sorry for my bad English.
In your example. The `Something` is generated on build time, so the user can't use it in their code directly, they can use `ISomething` only. So if I want it's serializable(the interface), I must specify the serializer manually. The problem is I can't reference the generated serializer. My solution is to reference a "helper" serializer, the helper serializer will find the correct generated serializer at runtime.

**Comment by sandwwraith** [comment]
No, problem is not with the language, you just used `@Serialization` annotation that doesn't exist, so I was confused. I see now you meant `@Serializable`. 

Yes, you described what I meant. As I said, we are unlikely to provide anything related to generated serializer publicly, because there are too much internal implementation details. So 'referencing a helper serializer' that would delegate to `Something.serializer()` is a proper way to solve your issue.

There is also #1169 related but it likely won't solve your problems.

**Comment by iseki0** [comment]
@sandwwraith Sorry. It's my typo. 
I'm not plan to access the plugin generated serializer directly. As an instead I want to get the real type which will be serialized (In that case it's the interface), then I will use `serializer()` function query serializer which is generated for the implementation.(Does it impossible? I know the function has been change to intrinsic in the recently versions, does it has a reflection fallback?)

**Comment by sandwwraith** [comment]
@iseki0 Intrinsic should be identical to a relfection one. `serializer(typeOf<Something>())` is always relfective. 
So, as I said, you need to access either `Something.Companion.serializer()` or `serializer<Something>()`. If this works for you, can I close the issue?

**Comment by iseki0** [comment]
Even it doesn't work for you. I found another solution. Thank you
