### ISSUE TITLE
Kotlin 1.3-RC-116/0.8.1-rc13: Example code crashes with SerializationException: Can't locate serializer for class Data

### ISSUE THREAD

**Issue by SebastianAigner** [Kotlin/kotlinx.serialization#229]
Hello, I have spent the last two hours trying to figure out how to get even the basic example serialization with version `0.8.1-rc13` to work with Kotlin `1.3.0-rc-116`.

I initially ran into an issue (`kotlin.jvm.KotlinReflectionNotSupportedError: Kotlin reflection implementation is not found at runtime. Make sure you have kotlin-reflect.jar in the classpath`) by adding `implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"` to my `build.gradle` (as per [this SO post](https://stackoverflow.com/a/36440329/4425952)).

I have also configured IntelliJ to delegate IDE build/run actions to Gradle as is required by the [EAP13 document](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/eap13.md#intellij-ideaandroid-studio).

However, when trying to run my main method with the example code from the [README](https://github.com/Kotlin/kotlinx.serialization#quick-example), I always get

```kotlin
Exception in thread "main" kotlinx.serialization.SerializationException: Can't locate serializer for class Data
	at kotlinx.serialization.PlatformUtilsKt.serializer(PlatformUtils.kt:23)
	at MainKt.main(Main.kt:12)
```

My main method (taken verbatim from the README):

```kotlin
import kotlinx.serialization.*
import kotlinx.serialization.json.JSON

@Serializable
data class Data(val a: Int)

fun main(args: Array<String>) {
    println(JSON.stringify(Data(42))) // {"a": 42, "b": "42"}
    val obj = JSON.parse<Data>("""{"a":42}""") // Data(a=42, b="42")
}
```

My build.gradle, glued together using the instructions in the [EAP13 document](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/eap13.md#intellij-ideaandroid-studio):

```groovy
buildscript {
    ext.kotlin_version = '1.3.0-rc-116'

    // no need in kotlinx repository
    repositories {
        jcenter()
        maven { url "https://dl.bintray.com/kotlin/kotlin-eap" } // while you are on 1.3-RC
    }


    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        // kotlin package, and no "gradle-plugin" in name
        // version matches Kotlin version
        classpath "org.jetbrains.kotlin:kotlin-serialization:$kotlin_version"
    }
}

apply plugin: 'kotlin' // or 'kotlin-platform-***' or 'kotlin-multiplatform'
apply plugin: 'kotlinx-serialization'

group 'io.sebi'
version '1.0-SNAPSHOT'

repositories {
    jcenter()
    maven { url "https://kotlin.bintray.com/kotlinx" }
    maven { url "https://dl.bintray.com/kotlin/kotlin-eap" }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-reflect:$kotlin_version"
    compile "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    compile "org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.8.1-rc13"
}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
```

I do not really know where to go from here - any support for getting started here is very much appreciated 😊

**Comment by sandwwraith** [comment]
Hi, as a quick try, does yout Kotlin plugin in IDEA have the same rc-116 version as you've specified in a buildfile? If so, try to close project, delete .idea folder and import it from Gradle again. 

If it does not help, I'll try to figure things in details tomorrow. You can always fallback to launching buulds from gradle tasks panel, and to add specific 'run' gradle taks via, e.g. application plugin.

**Comment by SebastianAigner** [comment]
Hi! 

<img width="463" alt="screen shot 2018-10-03 at 01 23 11" src="https://user-images.githubusercontent.com/2178959/46382476-6de17700-c6ab-11e8-9af9-d238ca835c04.png">
As you can see, plugin is the same version.

I have closed the project, executed `rm -rf .idea/` in the project folder, and re-imported via Import Project -> Import Model from external model Gradle -> Use auto-import -> run using green arrow again. This alone did not work.

**What does work though is:**

Add package declaration to main method:
```kotlin
package io.sebi.serializationtest
```
Add declaration for the run gradle task using the application plugin:

```groovy
apply plugin: 'application'
mainClassName = 'io.sebi.serializationtest.MainKt'
```

It would appear this successfully links up the gradle tasks with the plugin in IntelliJ (with `delegate IDE build/run actions` enabled).

If this is expected behaviour, this should probably be mentioned in the documents :)

**Comment by sandwwraith** [comment]
No, that's not an expected behaviour, because IDEA should correctly launch app via gradle build without applying 'application' plugin. 

In my sample, I've managed to run code from IDEA via Run icon on gutter with delegated build without any issues, so it seems like some tricky setup issue. Does `Data.serializer()` returns correct serializer or ide complains about unresolved reference?

**Comment by SebastianAigner** [comment]
Invoking `Data.serializer()` returns the same error:
```
Exception in thread "main" kotlinx.serialization.SerializationException: Can't locate serializer for class Data
	at kotlinx.serialization.PlatformUtilsKt.serializer(PlatformUtils.kt:23)
	at MainKt.main(Main.kt:12)
```

**Comment by sandwwraith** [comment]
Resolved reference in IDE means plugin was attached correctly. Are you sure that stacktrace is from an updated project? `Data.serializer()` can't throw that error because it does not involve any reflection calls, `.serializer()` is a method directly generated by plugin on the class. This should work in any way:

```
println(JSON.stringify(Data.serializer(), Data(42))) 
val obj = JSON.parse(Data.serializer(), """{"a":42}""")
```

**Comment by SebastianAigner** [comment]
It seems something in my project filed must have been screwed up, since I just wanted to upload it to GitHub, and when checking out my own latest commit in a separate folder, the library worked without problem. Thank you regardless for having a look and supporting me on this odyssey!
