### ISSUE TITLE
Recursion detected in a lazy value

### ISSUE THREAD

**Issue by h-huss** [Kotlin/kotlinx.serialization#2290]
Adding @Serializable to the test class below yields the IDE error (shown on `TestClass("SPECIAL")`)
```
Internal error occurred while analyzing this expression: 
AssertionError: Recursion detected in a lazy value under LockBasedStorageManager@1cbd9e5
```
Gradle fails with a similar error.

**To Reproduce**
``` kotlin
@Serializable
data class TestClass(val input: String) {
    val isSpecial get() = this === SPECIAL

    companion object {
        val SPECIAL = TestClass("SPECIAL")
    }
}
```

**Expected behavior**
No exception.

Admittedly, this class is somewhat strange and should probably be rewritten.

**Environment**
 - Kotlin version: 1.8.21
 - Library version: 1.5.0
 - Kotlin platforms: JVM
 - Gradle version: 8.1.1

**Comment by sandwwraith** [comment]
Not reproducible on 2.0.0
