### ISSUE TITLE
JsonDecodingException: Expected class kotlinx.serialization.json.JsonObject as the serialized body of Kotlinx. serialization.Polymorphic<List>, but had class kotlinx.serialization.json.JsonArray

### ISSUE THREAD

**Issue by Abdulsalam-j** [Kotlin/kotlinx.serialization#2295]
The exception is thrown only when having a list of interface and works when having it as a class:

`@Serializable(with= LocationJsonContentPolymorphicSerializer::class)`
`interface LocationGeneratedDto {`

`    @SerialName(value = "name")`
`    val name: kotlin.String?`
`    @SerialName(value = "locationId")`
`    val locationId: kotlin.String?`
`    @Contextual @SerialName(value = "type")`
`    val type: LocationTypeGeneratedDto?`
`    @SerialName(value = "geoJson")`
`    val geoJson: GeoJsonGeneratedDto?`
`}`

The serializer
`object LocationJsonContentPolymorphicSerializer :`
`    JsonContentPolymorphicSerializer<LocationGeneratedDto>(`
`        LocationGeneratedDto::class`
`    ) {`
`    override fun selectDeserializer(element: JsonElement): DeserializationStrategy<LocationGeneratedDto> {`
`        return when (element.jsonObject["type"]?.jsonPrimitive?.content) {`
`            "city" -> CityGeneratedDto.serializer()`
`            "airport" -> AirportGeneratedDto.serializer()`
`            "country" -> CountryGeneratedDto.serializer()`
`            else -> throw Exception("Unknown Module: LocationGeneratedDto key 'type' not found or does not matches any module type")`
`        }`
`    }`
`}`

Implementation Class Example:
`@Serializable`
`data class CityGeneratedDto (`

`    @SerialName(value = "name")`
`    override val name: kotlin.String? = null,`

`    @SerialName(value = "locationId")`
`    override val locationId: kotlin.String? = null,`

`    @Contextual @SerialName(value = "type")`
`    override val type: LocationTypeGeneratedDto? = null,`

`    @SerialName(value = "geoJson")`
`    override val geoJson: GeoJsonGeneratedDto? = null,`

`    /* The ISO 3166-1 and 3166-2 code for countries and cities. */`
`    @SerialName(value = "ISO")`
`    val ISO: kotlin.String? = null`

`) : LocationGeneratedDto`

response:

```json
[{"type":"city","name":"Amman1","geoJson":{"coordinates":[24.896356,55.161389],"type":"Point"},"locationId":"AM-DU"},{"type":"city","name":"Amman2","geoJson":{"coordinates":[25.11219978,56.32400131],"type":"Point"},"locationId":"AE-II"},{"type":"airport","name":"DA International Airport","geoJson":{"coordinates":[25.25279999,55.36439896],"type":"Point"},"locationId":"GTT"}]
```

Note: by changing `LocationGeneratedDto` to open class it works fine

**Comment by aplha98** [comment]
it is something related to interface LocationGeneratedDto

**Comment by UnderMybrella** [comment]
I managed to isolate this, it's a possible bug with how ktor gets a serializer from a type (See [KTOR-5898](https://youtrack.jetbrains.com/issue/KTOR-5898)). The issue with `LocationGeneratedDto` is related to existing issues with interfaces (See #1207).
