### ISSUE TITLE
Kotlin x serialization converter for retrofit

### ISSUE THREAD

**Issue by lewan42** [Kotlin/kotlinx.serialization#2296]
hello, i want to use kotlin serialization with retrofit, but i don't understand how can I get a converter. When i used Gson ->         `.addConverterFactory(GsonConverterFactory.create(GsonBuilder().setLenient().create()))`
 
Please tell me, is it possible to set a converter?

**Comment by JakeWharton** [comment]
Please see https://github.com/JakeWharton/retrofit2-kotlinx-serialization-converter/ whose readme details how to set this up. In the future, consider asking general usage questions on StackOverflow or the Kotlinlang Slack instance.

**Comment by lewan42** [comment]
I saw this repository, I was confused that this implementation is supplied separately.

Thank you

**Comment by JakeWharton** [comment]
Details as to why are available in https://github.com/JakeWharton/retrofit2-kotlinx-serialization-converter/issues/58
