### ISSUE TITLE
Can you add a serializer for Dates?

### ISSUE THREAD

**Issue by olivierperez** [Kotlin/kotlinx.serialization#23]
Hi,
at runtime I get `IllegalArgumentException: Can't found internal serializer for class class java.util.Date` when I serialize an object that contains a Date.

I tried to write my own KSerializer but I didn't succeed 😢

**Comment by sandwwraith** [comment]
You can write your custom serializer for Date in this way:

```kotlin
@Serializable
class DateWrapper(val date: Date)

@Serializer(forClass = Date::class)
object DateSerializer: KSerializer<Date> {
    var df: DateFormat = SimpleDateFormat("dd/MM/yyyy HH:mm:ss.SSS")

    override fun save(output: KOutput, obj: Date) {
        output.writeStringValue(df.format(obj))
    }

    override fun load(input: KInput): Date {
        return df.parse(input.readStringValue())
    }

    override val serialClassDesc: KSerialClassDesc = SerialClassDescImpl("Date")
}
```

Then, register it at startup of your application: `kotlinx.serialization.registerSerializer("java.util.Date", DateSerializer)`

And now it should work. Note that `JSON.stringify(DateWrapper(Date()))` will give you `{"date":["Date","11\/10\/2017 11:40:20.265"]}` - Date object is wrapped in array with type info, because polymorphic serialization was enabled.

**Comment by olivierperez** [comment]
Hey,
thanks for the fast answer. I got trouble to implement your idea, at compile time I have
`Error:(17, 18) Conflicting declarations: public open val serialClassDesc: KSerialClassDesc`
on the line
`    override val serialClassDesc: kotlinx.serialization.KSerialClassDesc = SerialClassDescImpl("Date")`.

I pushed a commit about my try if it can help you https://github.com/olivierperez/crapp/commit/6db87562659a75541fec7f12ae9988b8f2997da2

---

I've created the KSerializer
https://github.com/olivierperez/crapp/commit/6db87562659a75541fec7f12ae9988b8f2997da2#diff-918c256547830fc9ac551d28b90ca385R1

I've done the registration
https://github.com/olivierperez/crapp/commit/6db87562659a75541fec7f12ae9988b8f2997da2#diff-763ab1f257351c15e9eafd3f6e439e56R10

I try to parse
https://github.com/olivierperez/crapp/commit/6db87562659a75541fec7f12ae9988b8f2997da2#diff-fbc07e78c4dda45d4eb862c43cdf93a2R78

---

Nothing urges, I was just giving a try to your lib for now ;-)

**Comment by sandwwraith** [comment]
looks like #10, but it was fixed some time ago. I've copied your serializer and data class, and it works fine. Is this definitely gradle build error? (JPS plugin still has some issues, and highlighting/compilation from IDEA may produce incorrect results)

**Comment by cbruegg** [comment]
Unfortunately this doesn't seem to work with the Protobuf backend:

```
java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.single(_Collections.kt:472)
	at kotlinx.serialization.protobuf.ProtoBuf.getProtoDesc(ProtoBuf.kt:41)
	at kotlinx.serialization.protobuf.ProtoBuf.access$getProtoDesc(ProtoBuf.kt:38)
	at kotlinx.serialization.protobuf.ProtoBuf$ProtobufWriter.getTag(ProtoBuf.kt:67)
	at kotlinx.serialization.protobuf.ProtoBuf$ProtobufWriter.getTag(ProtoBuf.kt:47)
	at kotlinx.serialization.TaggedOutput.writeStringElementValue(Tagged.kt:155)
	at kotlinx.serialization.internal.PolymorphicSerializer.save(Polymorphic.kt:42)
	at kotlinx.serialization.KOutput.writeSerializableValue(Serialization.kt:133)
	at kotlinx.serialization.KOutput.writeSerializableElementValue(Serialization.kt:174)

```

**Comment by fab1an** [comment]
Should this work for Javascript as well, because I can't get it to work.

My `kotlinx`(0.1.1) lacks the `registerSerializer` method

**Comment by sandwwraith** [comment]
Yes, currently its unavailable on JS platform because it's relying on Java Reflection for registering/unregistering. We are going to eliminate this restriction soon.

**Comment by fab1an** [comment]
Ok. Thanks for the heads-up.

**Comment by sandwwraith** [comment]
Information about custom serializers updated in latest [doc](../blob/master/docs/custom_serializers.md)

**Comment by bangonkali** [comment]
I know this is closed but I just want to add this here for reference since it seems based on the doc the serialization format is changed and that the first comment on this thread is deprecated.

below works for both timestamp based serialization or if you uncomment the commented lines and comment the duplicates, then it will work using string formatted dates.

please provide feedback if this one isn't efficient or if you have better ideas. i got used to Newtonsoft.JSON from the dotnet world and this never seems to be a huge problem from their, but here it has to be manually written. hoping someday this becomes avaiable by default.

```kotlin
import kotlinx.serialization.*
import kotlinx.serialization.internal.*
import java.text.DateFormat
import java.text.SimpleDateFormat
import java.util.*

@Serializable
class DateSerializer(val s: Date) {
  @Serializer(forClass = DateSerializer::class)
  companion object : KSerializer<DateSerializer> {
//    private val df: DateFormat = SimpleDateFormat("dd/MM/yyyy HH:mm:ss.SSS")

    override val descriptor: SerialDescriptor = StringDescriptor.withName("Date")

    override fun serialize(encoder: Encoder, obj: DateSerializer) {
//      val stringValue = df.format(obj.s)
      val stringValue = obj.s.time.toString()
      encoder.encodeString(HexConverter.printHexBinary(stringValue.toByteArray()))
    }

    override fun deserialize(decoder: Decoder): DateSerializer {
//      val objectValue = df.parse(decoder.decodeString())
      val objectValue = Date(decoder.decodeString().toLong())
      return DateSerializer(objectValue)
    }
  }
}
```

**Comment by sandwwraith** [comment]
Current problem is that kotlin multiplatform stdlib does not have a definition of `Date`. We, however, consider providing additional module to work with standard JVM classes (see #350, WIP )

**Comment by SaifurRahmanMohsin** [comment]
There seems to be a [@Contextual serializer](https://github.com/Kotlin/kotlinx.serialization/blob/master/core/commonMain/src/kotlinx/serialization/ContextualSerializer.kt) that addresses this. Haven't tested it yet by the example in the comment block seems to use the Date object.

**Comment by rgtomaz** [comment]
Hello all,
I know this thread is closed, but I'd like to know if there's any news on this topic. It's been over two years since the last comment, and Date is apparently not yet supported by the serializer. At least not working on my project. 
Any update will be very welcome! Thank you.

**Comment by Icyrockton** [comment]
any progress? I think `Date`  is a important class , we need it out of box

**Comment by sandwwraith** [comment]
> Current problem is that kotlin multiplatform stdlib does not have a definition of Date. 

That's still true. Moreover, different domains may need to represent dates differently, so it is very likely that Date will end up with a custom serializer anyway.

**Comment by pdvrieze** [comment]
From my perspective the "best" resolution for things like this is to have some sort of mechanism that allows for having serializers associated with either packages or modules (perhaps similar to the way jar files have the metadata folders), or with module declarations. (At the worst cased passed as command line arguments/build script arguments). That would remove the boilerplate issue while still addressing the fact that there is no single "best" way to serialize dates/times.

**Comment by gnawf** [comment]
They changed `StringDescriptor.withName` to `PrimitiveSerialDescriptor` so working code is now

```
@Serializer(forClass = Date::class)
object DateSerializer : KSerializer<Date> {
    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("DateSerializer", PrimitiveKind.STRING)

    override fun serialize(encoder: Encoder, value: Date) {
        encoder.encodeString(value.time.toString())
    }

    override fun deserialize(decoder: Decoder): Date {
        return Date(decoder.decodeString().toLong())
    }
}
```

I'm working with `java.time.Instant` and it's pretty annoying how there's no built in serializer or even (additional) Java module that provides it automatically.

**Comment by trenskow** [comment]
I agree. I'm also struggling with this issue right now. Could one of the problems be, that you have all of these different ways of representing a string in JSON, because JSON itself does not define any type for Date nor a specific format for them either.

I think the default way should be, that a default serializer parses to and from ISO-8601. When a Date in JavaScript is serialized it is serialized to a String with this format. Since JSON is a subset og JavaScript, I think this should be the default behaviour.

Also ISO-8601 is _the_ standard for encoding dates into strings these days.

**Comment by ywmei-brt1** [comment]
How can we "register serializer" now?
As the `import kotlinx.serialization.registerSerializer` is not avaliable any more

**Comment by pdvrieze** [comment]
@ywmei-brt1 You can only do this on a per file basis with an annotation `@file:UseSerializers` (if I'm not mistaken on the exact name), or of course specify it on each use. What we are talking about is to have some metadata in a library that allows the plugin to then find these serializers from the library and use them where no different serializers were specified.

**Comment by sandwwraith** [comment]
@ywmei-brt1 Check out https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#specifying-serializer-on-a-property
