### ISSUE TITLE
[Question] Deserializing a list of specific type from a Serializable object

### ISSUE THREAD

**Issue by AshMosahebTAB** [Kotlin/kotlinx.serialization#2309]
Hi, I created this API (for Ktor):

```
class ApiService {
   ...
    suspend fun getEmployees(): List<EmployeeItem> = client.get("http://someapi/employees").body()
}
```
I am setting the return value to a list of a specific item, `EmployeeItem` (which is not owned by me, so I cannot make it Serializable. Under the hood the API returns a Json response that directly maps to this Serializable object `EmployeesResponse`

```
@Serializable
data class EmployeesResponse(
    @SerialName("status") val status: String,
    @SerialName("result") val result: List<EmployeeItemResponse>,
)

@Serializable
data class EmployeeItemResponse(
    @SerialName("id") val id: Int,
    @SerialName("name") val name: String,
    @SerialName("age") val age: Int,
    @SerialName("address") val address: String,
)
```

**How can I automatically map `EmployeesResponse` to `List<EmployeeItem>`?**

_What I’ve done so far:_
I have created a Serializer as such (note, not bothered about the serialize operation atm):
```
object EmployeesSerializer : KSerializer<List<EmployeeItem>> {

    override val descriptor: SerialDescriptor = EmployeesResponse.serializer().descriptor

    override fun deserialize(decoder: Decoder): List<EmployeeItem> {
        val surrogate = EmployeesResponse.serializer().deserialize(decoder)
        return surrogate.result.map { it.toEmployeeItem() }
    }

    override fun serialize(encoder: Encoder, value: List<EmployeeItem>) {
        throw UnsupportedOperationException()
    }

    private fun EmployeeItemResponse.toEmployeeItem() = EmployeeItem(
        id = id,
        name = name,
        age = age
    )
}
```
And I have registered it using the Json builder:
```
...
                Json {
                    ignoreUnknownKeys = true
                    serializersModule = SerializersModule {
                        contextual(EmployeesSerializer)
                    }
                }
...
```
It seemed to work, until I added another API function that returns a list of another type. i.e. see `getJobs()`
```
    suspend fun getEmployees(): List<EmployeeItem> = client.get("http://someapi/employees").body()
...
    suspend fun getJobs(): List<JobItem> = client.get("http://someapi/jobs").body()
```
```
object JobsSerializer : KSerializer<List<JobItem>> {

    override val descriptor: SerialDescriptor = JobsResponse.serializer().descriptor

    override fun deserialize(decoder: Decoder): List<JobItem> {
        val surrogate = JobsResponse.serializer().deserialize(decoder)
        return surrogate.result.map { it.toJobItem() }
    }

    override fun serialize(encoder: Encoder, value: List<JobItem>) {
        throw UnsupportedOperationException()
    }

    private fun JobItemResponse.toJobItem() = JobItem(
        id = id,
        name = name
    )
}
```
```
                Json {
                    ignoreUnknownKeys = true
                    serializersModule = SerializersModule {
                        contextual(EmployeesSerializer)
                        contextual(JobsSerializer)
                    }
                }
```

So I am not confident that this is the correct approach. As this exception is thrown now :
`kotlinx.serialization.modules.SerializerAlreadyRegisteredException: Contextual serializer or serializer provider for interface java.util.List (Kotlin reflection is not available) already registered in this module`

So it seems like its registered the serialiser for List, rather than a list of specific type?

I am new to Kotlinx serialization. I was doing something similar with Moshi custom adapters which worked nicely. So any help here, would be appreciated.
Thanks!

**Comment by sandwwraith** [comment]
You can read this section on binding serializers: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#passing-a-serializer-manually and this: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#contextual-serialization

In short, I'd recommend you to use `@file:ContextualSerialization(JobItem::class, EmployeeItem::class)` and define custom serializers for them without bothering with lists. You can still use `JobsResponse` etc in these serializers.
