### ISSUE TITLE
Value classes are being serialized to null by default

### ISSUE THREAD

**Issue by Deaths-Door** [Kotlin/kotlinx.serialization#2313]
**Value classes are being serialized to null by default**

**To Reproduce**

```kotlin
@Serializable
@JvmInline
internal expect value class UUID private actual constructor(private val uuid : String){
    override fun toString(): String
    companion object {
        fun fromString(string : String) : UUID
        fun random(): UUID
    }
}
```

**Expected behavior**

UUID class should serialize into a non-null string 

**Environment**
 - Kotlin version: 1.8.21
 - Library version ; 1.5.1
 - Kotlin platforms : All platforms
 - Gradle version: 8.0
 - IDE version : Android studio flamingo
- Other Info : it seems as value classes are falsely serialized by default and with custom serializer it is even more problematic. Also i have tried other value classes with seem to have the same issue with serialization ( custom and default)

**Comment by sandwwraith** [comment]
Can you show what do you mean by 'serialized by null'? E.g. how do you call 'encodeToString' and what is actual result

**Comment by Deaths-Door** [comment]
I mean that 
```kotlin
val uuid = UUID.random() // eg on android it calls java.util.UUID.random() and then toString() to set value of uuid
val asString = uuid.encodeToString() // print it shows null
```
But then I also try Firestore serialization, 
```kotlin
Firestore.collection(..).document(..).set(uuid)
```
Then on Firestore it has a value of null , it shows its not an issue that i caused but an issue with the serialization
I have also tried making a custom serializer using both encodeInlineInt and encodeInt which both resulted in the same thing

**Comment by sandwwraith** [comment]
It seems I'm still lacking some context, as I can't reproduce it. This code works fine for me: 

```kotlin
@Serializable
@JvmInline
internal expect value class UUID private actual constructor(private val uuid : String){
    override fun toString(): String
    companion object {
        fun fromString(string : String) : UUID
        fun random(): UUID
    }
}

@Serializable
@JvmInline
internal actual value class UUID private actual constructor(actual val uuid: String) {
    actual override fun toString(): String {
        return uuid
    }

    actual companion object {
        actual fun fromString(string: String): UUID {
           return UUID(string)
        }

        actual fun random(): UUID {
            return UUID("random")
        }
    }
}

@Test
fun someTest() {
        val u = UUID.random()
        println(Json.encodeToString(u)) // prints "random"
}
```

Serialization strategy actually depends on what is written in your 'actual' class because the plugin doesn't process common sources (and `@Serializable` on 'expect' class doesn't do much). Maybe that'll help you.

**Comment by sandwwraith** [comment]
Pls reopen if still actual
