### ISSUE TITLE
Method polymorphicDefaultDeserializer not working for deserialization

### ISSUE THREAD

**Issue by enirsilvaferraz** [Kotlin/kotlinx.serialization#2317]
**Describe the bug**
Hello, I'm trying to deserialize a json that contains polymorphic characteristics and I'm getting an output that I can't understand very well. I think I'm doing this correctly... Could you help me to identify the problem?

The output
```
kotlinx.serialization.json.internal.JsonDecodingException: Expected start of the array '[', but had 'EOF' instead at path: $
JSON input: {"type": "C"}
```

JSON
```json
{"type": "C"}
```

Classes

```kotlin
interface A

@Serializable
@SerialName("B")
data class B(val name: String? = null) : A

@Serializable
data class C(val name: String? = null) : A
```

the format configuration

```kotlin
val format = Json {
    serializersModule = SerializersModule {
        polymorphic(baseClass = A::class, actualClass = B::class, actualSerializer = B.serializer())
        polymorphic(baseClass = A::class, actualClass = C::class, actualSerializer = C.serializer())
        polymorphicDefaultDeserializer(baseClass = A::class, defaultDeserializerProvider = { PolymorphicSerializer(baseClass = C::class) })
    }
    encodeDefaults = true
    ignoreUnknownKeys = true
}
```

Here I have set the default deserializer of type C. If I understand correctly, when an unknown type is returned in the json this default deserializer should be called. Right?

Here is a small test to reproduce the issue.

The test fails
```kotlin
@Test
    fun testDecode() {

        val json = "{\"type\": \"C\"}"

        val aClazz = format.decodeFromString<A>(json)

        assertEquals(aClazz, C())
        println(aClazz)
    }
```

The test succeeds
```kotlin
@Test
    fun testDecode() {

        val json = "{\"type\": \"B\"}"

        val aClazz = format.decodeFromString<A>(json)

        assertEquals(aClazz, B())
        println(aClazz)
    }
```

Look, if I try to deserialize a json with the type equal to "B", the test passes successfully. If I try to deserialize a json with type equal to anything else ("C" for example), the test fails with the exception placed above.

**Expected behavior**
What I expect: The lib will deserialize the json into a class registered in the default deserializer.
And the output of println would be: 

``` 
C(name=null)
```

**Environment**
 - Kotlin version: 1.8.20
 - Library version: 1.4.0
 - Kotlin platforms: JVM
 - Gradle version: 7.4.2

**Comment by pdvrieze** [comment]
The return value of the serializer provider should be a concrete serializer for the "default" type, not a polymorphic serializer itself. Note that the problem with the non-default case is that the serialname of a type by default is the fully qualified name, not the simple class name.

**Comment by enirsilvaferraz** [comment]
It works! Thank you a lot! @pdvrieze
