### ISSUE TITLE
Json feature that adds full input to decoding exceptions.

### ISSUE THREAD

**Issue by mgroth0** [Kotlin/kotlinx.serialization#2320]
**What is your use-case and why do you need this feature?**

I am writing a ktor endpoint that deserializes json input sent from an API. Because this API is not very well documented and has a large polymorphic class hierarchy with many different fields, I am often getting deserialization exceptions since my classes don't correctly match the input data.

I often get exceptions such as

```
kotlinx.serialization.json.internal.JsonDecodingException: Expected JsonPrimitive at message, found ..
```

Which contain a subset of the json input. However, without seeing the full json input it can sometimes be difficult to deduce what exact part of my model is incorrect.

**Describe the solution you'd like**

I suggest a new option in the `Json` builder such as:
```
Json {
    includeFullInputInExceptions = true
}
```

This would cause all json decoders to temporarily cache the full input they receive before they begin decoding. It could be a dangerous memory leak, so it should be off by default. But the benefit would be that when there is an exception, the exception could print the full json data, making debugger easier. Maybe it could even pretty print the json input.

**Comment by sandwwraith** [comment]
Given that plenty workarounds exist for now, we currently would not plan such a feature
