### ISSUE TITLE
JsonTransformingSerializer Null Pointer Exception

### ISSUE THREAD

**Issue by frenchmb** [Kotlin/kotlinx.serialization#2348]
**Describe the bug**
Null pointer encountered when using JsonTransformingSerializer on initialisation

Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlinx.serialization.json.JsonTransformingSerializer.<init>, parameter tSerializer
	at kotlinx.serialization.json.JsonTransformingSerializer.<init>(JsonTransformingSerializer.kt)
	at fortrez.market.app.refinitiv.service.search.model.ExchangeCodeSerializer.<init>(SearchAll.kt:71)
	at fortrez.market.app.refinitiv.service.search.model.ExchangeCodeSerializer.<clinit>(SearchAll.kt)
	... 243 more

**To Reproduce**
Attach a code snippet or test data if possible.

@Serializable()
sealed class FilterCriteria {
    abstract val include: Boolean
}
object ExchangeCodeSerializer : JsonTransformingSerializer<ExchangeCode>(ExchangeCode.serializer()) {
    override fun transformSerialize(element: JsonElement): JsonElement {
        return super.transformSerialize(element)
    }
}

@Serializable(with = ExchangeCodeSerializer::class)
@SerialName("ExchangeCode")
data class ExchangeCode(
    @SerialName("Include")
    override val include: Boolean,
    @SerialName("StringValue")
    val filters: List<FilterValue<String>>
) : FilterCriteria()

// Test Code
 val filter = ExchangeCode(
                include = false,
                filters = listOf(
                    FilterValue(value = "ASX"),
                    FilterValue(value = "CHA")
                )
            )
            val result = Json.encodeToString(ExchangeCode.serializer(), filter)

**Expected behavior**
Serialiser to be called
**Environment**
 - Kotlin version: 1.8.10
 - Library version: Serialisation library 1.5
 - Kotlin platforms: JVM
 - Gradle version: 7.3.3
 - IDE version : IntelliJ 2023.1.2
 - Other relevant context : MacOs

**Comment by sandwwraith** [comment]
When you use `@Serializable(with = ExchangeCodeSerializer::class)`, `ExchangeCode.serializer()` returns exactly `ExchangeCodeSerializer` because it is a default serializer now. See #1169 for details.
