### ISSUE TITLE
Protobuf 3 serialization

### ISSUE THREAD

**Issue by jvgelder** [Kotlin/kotlinx.serialization#2352]
**What is your use-case and why do you need this feature?**

I would like to have a way to serialize and de-serialize protobuf 3 messages.
Internally we use protobuf 3 message with https://github.com/bufbuild/protoc-gen-validate.
This gives us strict validation in our input and makes our message queues interoperable with our APIs.

I did notice protobuf 2 was already there but no 3 support yet :( or I may have searched with my nose.

**Describe the solution you'd like**

- Pointers to protobuf 3 support.
- I created the following until its supported  https://gist.github.com/jvgelder/faf83774b3acb38b351f239d86801aa4

**Comment by jvgelder** [comment]
hmm ye your answer and the update to the docs already make things a bit more clear. 

My use case is slightly different I should have mentioned I use Ktor with content negotiation and use Kotlinx to serialize and deserialize messages to and from our internal types while having some simple serializable messages like our exceptions which we serialize/deserialize directly with Kotlinx. 

I already have a proto file and the respective java object/validation classes, which are generated by [bazel rules proto](https://github.com/bazelbuild/rules_proto) and [pgv rules](https://github.com/bufbuild/protoc-gen-validate) this allows us to generate code with validation for our frontend and other apps that we have.

**Comment by sandwwraith** [comment]
@jvgelder Then you should edit your Kotlin classes to match your schema, if that is possible

**Comment by jvgelder** [comment]
I use the generated java classes as that is what protobuf gen validate needs.
My workflow is `proto file -> compile to java -> generate validation classes` (only java for now unfortunately ).
Using custom serializers I decode/encode the incoming/outgoing json  messages. Within that encoding and decoding I also run the validators which use reflection to find the proper validation class.

In this flow I don't need to create a serializable spec from the proto file.

What we could do however is create a bazel rule like the one for java files to generate the kotlinx spec from a proto file but then we would also need to add a validation mechanism which is compatible.
