### ISSUE TITLE
Cbor.decodeFromByteArray with offset and length

### ISSUE THREAD

**Issue by mgroth0** [Kotlin/kotlinx.serialization#2357]
**What is your use-case and why do you need this feature?**

Say if have a large byte array with an object serialized into it at offset=1. Currently, with `Cbor.decodeFromByteArray()`, I would need to copy the entire byte array to remove the first byte. This seems like a huge performance issue. I tried to go into the implementation of ` Cbor.decodeFromByteArray` and see if I could write my own function that uses an offset, but all of the things used inside this function are internal and inaccessible. 

**Describe the solution you'd like**

`Cbor.decodeFromByteArray<MyClass>(ser=ser,bytes=bytes,offset=offset,length=length)`

**Comment by sandwwraith** [comment]
Adding `offset` and `length` seems very specific and bizzare, so it likely won't be implemented. However, integration with kotlinx-io (when it's ready) is a high possibility. I think IO framework will be able to let you skip bytes.
Meanwhile, you can skip them manually in the underlying source — e.g., if you read from InputStream, just call `read()` to skip one byte before calling `read(myByteArray)`
