### ISSUE TITLE
Allow ignoring JsonNull values during decoding

### ISSUE THREAD

**Issue by Martmists-GH** [Kotlin/kotlinx.serialization#2370]
**What is your use-case and why do you need this feature?**

Currently, I'm working on a project that heavily relies on codegen, which isn't very flexible. The current issue is that it generates `obj["field"]?.jsonObject`, where `obj` is a deserialized `JsonObject`. This works great when fields are missing, however when fields are explicitly null, it's a `JsonNull` instead of `null`. 

**Describe the solution you'd like**

Ideally the `Json{}` configuration gets a new field for deserializing null values as `null` rather than `JsonNull`

**Comment by sandwwraith** [comment]
Given that `JsonObject` implements `Map<String, JsonElement>` we can't put `null`s there, we can only delete the key if its value is equal to `JsonNull`.

**Comment by sandwwraith** [comment]
You can also write your own extension on `JsonObject?/JsonElement?`
