### ISSUE TITLE
Allow SerialName decorator to use composite path

### ISSUE THREAD

**Issue by metehus** [Kotlin/kotlinx.serialization#2376]
**What is your use-case and why do you need this feature?**
So, let's say i have a JSON like this:
```json
{
  "response": {
    "user": {
      "name": "Custom name"
    }
  }
}
```
to decode this, I would have to do something like this:
```kt
@Serializable
data class OuterResponse (
    val response: Response
)

@Serializable
data class Response (
    val user: User
)

@Serializable
data class User (
    val name: String
)

val response = Json.decodeFromString<OuterResponse>("...")
```

I would need to create 3 data classes just to access the `User` object, with the `Response` class being used just to access the `user` field

**Describe the solution you'd like**

I would like to "skip" some fields on those cases, something like that:

```kt
@Serializable
data class Response (
    @SerialName(arrayOf("response", "user"))
    val user: User
)

@Serializable
data class User (
    val name: String
)

val response = Json.decodeFromString<Response>("...")
````
In this example, the `user` property of `Response` would get the json object in `response.user`, without having to create another  data class just for the middle object.

To go a little further, This could also be supported on the data class so, in this case, I could just get the User object directly, like this:
```kt
@Serializable
@SerialName(arrayOf("response", "user"))
data class User (
    val name: String
)

val user = Json.decodeFromString<User>("...")
```

**Comment by sandwwraith** [comment]
Isn't it similar to #292 ?

**Comment by sandwwraith** [comment]
For the time being, it is possible to achieve this result with custom serializers (see https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#json-transformations), so I'm not sure if this is an absolute must

**Comment by sandwwraith** [comment]
You're right, thanks Jake
