### ISSUE TITLE
@Language annotation causes compilation error for Kotlin/JS when using other libraries with same workaround

### ISSUE THREAD

**Issue by Kantis** [Kotlin/kotlinx.serialization#2377]
**Describe the bug**
Trying to compile a project for Kotlin/JS when using another library which also performs the multiplatform `@Language` [workaround](https://github.com/JetBrains/java-annotations/issues/34#issuecomment-701223881) results in:
```
e: java.lang.IllegalStateException: IrClassPublicSymbolImpl for org.intellij.lang.annotations/Language|null[0] is already bound: CLASS ANNOTATION_CLASS name:Language modality:OPEN visibility:public superTypes:[kotlin.Annotation]
	at org.jetbrains.kotlin.ir.symbols.impl.IrBindablePublicSymbolBase.bind(IrPublicSymbolBase.kt:58)
	at org.jetbrains.kotlin.ir.declarations.impl.IrClassImpl.<init>(IrClassImpl.kt:37)
	at org.jetbrains.kotlin.ir.declarations.impl.AbstractIrFactoryImpl.createClass(IrFactoryImpl.kt:55)
	at org.jetbrains.kotlin.ir.declarations.impl.IrFactoryImplForJsIC.createClass(IrFactoryImplForJsIC.kt:67)
> Task :ks3-standard:compileTestDevelopmentExecutableKotlinJs FAILED
```

Also reported at https://youtrack.jetbrains.com/issue/KT-59620

**To Reproduce**
See Youtrack ticked

**Expected behavior**
IntelliJ should ship proper multiplatform `@Language`. Until then it's probably a good idea to remove these workarounds,

**Environment**
 - Kotlin version: 1.8.20
 - Library version: 1.5.1
 - Kotlin platforms: JS
 - Gradle version: 8.2.1

**Comment by sandwwraith** [comment]
Ouch. @shanshin If we remove `org.intellij.lang.annotations.Language` from JS & Native, I suppose IDE highlighting will still work?

**Comment by shanshin** [comment]
> @shanshin If we remove org.intellij.lang.annotations.Language from JS & Native, I suppose IDE highlighting will still work? (at least for JVM sources?)

if we replace the annotation for JS/Native with another one, the syntax highlighting disappears in it

**Comment by sandwwraith** [comment]
And for the common source?

**Comment by shanshin** [comment]
Unfortunately, it does not work for common source even in current version, apparently IntelliJ only looks at the expect annotation, because it does not know for what target the code will be used.

**Comment by sandwwraith** [comment]
Then it kinda doesn't make sense (unless we make `expect annotation class org.intellij.lang.annotations.Language` which we can't do anyway), so let's leave it JVM-only

**Comment by shanshin** [comment]
> Then it kinda doesn't make sense (unless we make expect annotation class org.intellij.lang.annotations.Language which we can't do anyway), so let's leave it JVM-only

OK

It seems to me the best solution in the future will be to add a special annotation to the library, and this annotation should already be supported by IntelliJ.

**Comment by sandwwraith** [comment]
Yeah, it is called 'making org.jetbrains.annotations' MPP library)
