### ISSUE TITLE
Support sequential decoding a collection of structures (classes) with collectionSize -1

### ISSUE THREAD

**Issue by hfhbd** [Kotlin/kotlinx.serialization#2378]
**What is your use-case and why do you need this feature?**
I implement [FixedLengthFile Format](https://www.ibm.com/docs/en/psfa/7.2.1?topic=format-fixed-length-files) which basically stores a instance of a class into a String without any delimiters:
```kotlin
@Serializable
data class Small(
  @FixedLength(2)
  val s: String,
  @FixedLength(1)
  val m: String
 )
    
 @Serializable
 data class Large(
  @FixedLength(6)
  val l: String
)

val smallString = FixedLengthFormat.encodeToString(listOf(Small("Fo", "o"), Small("Ba", "r")) // "FooBar"
val large: Large = FixedLengthFormat.decodeFromString(smallString) // Large("FooBar")
```
Because this format requires a schema with fixed lengths, the serialization of primitives isn't supported, they lack the length annotation. As a consequence, only classes are allowed.
Also, I opt-in to `decodeSequentially() = true` due the schema supports sequential data only.

While converting a `List` of `Small`s into a `Large`r class does work as expected, the opposite isn't possible:
```kotlin
val largeString = "FooBar"
val smalls: List<Small> = FixedLengthFormat.decodeFromString(largeString) // Size must be known in advance when using READ_ALL
```
The main reason is the missing `collectionSize` at the highest level (here `ListSerializer`).
I can't return the number of possible records at the higher level, because the format allows inner lists (with a previous size attribute). This means, the format allows variable record length, so trying to read the possible records actually means serializing the values, and I return `decodeCollectionSize() = -1` at the highest level (here `ListSerializer`). 
This return value causes the size exception (as expected according to the docs).

**Describe the solution you'd like**
Design another api to lazily decode a collection with unknown size. 

Biggest issue: How to signal the deserializer when there are no elements left and the generated list without the remaining unfinished "element" should be returned?

Throwing a well defined exception (`UnfinishedElementExecption`) would allow me to not parse the remaining input but just cancel the deserialization of the current record if there is no input left. This solution would be easy to implement as library author, but throwing exceptions as code control flow have some costs and should be avoided.

A better alternative would be a check, `fun CompositeDecoder.canDecode(): Boolean = true`, and a while loop with an index to keep existing behavior in readAll.
This requires parsing the next record (basically just checking the length) before deserializing it.

```kotlin
interface CompositeDecoder {
  fun canDecode(): Boolean = true
}
```

```kotlin
// CollectionLikeSerializer
final override fun readAll(decoder: CompositeDecoder, builder: Builder, startIndex: Int, size: Int) {
  if (size == -1) {
    var index = 0
    while (decoder.canDecode()) {
      readElement(decoder, startIndex + index, builder, checkIndex = false)
      index += 1
    }
  } else if (size >= 0) {
    for (index in 0 until size) {
      readElement(decoder, startIndex + index, builder, checkIndex = false)
    }
  }
}
```

**Current workaround**
Calculating and parsing the lengths of the whole input string before actually deserializing it. Ideally, I would only need parsing the current part of the input string containing the values for the current records only.

**Comment by recursive-rat4** [comment]
Perhaps in `beginStructure` you can check whether the size is known and return a non-sequential decoder when it is not?

**Comment by sandwwraith** [comment]
Adding something like `canDecode` seems strange, because we already have `decodeElementIndex` for that that can return DECODE_DONE. I wonder if you can simply implement this logic:

```
class MyDecoder: CompositeDecoder {
  override fun decodeSequentially(): Boolean = if (sizeIsKnown) true else false
```

This is exactly what `decodeSequentially` for. It is designed for length-prefixed formats, although your format can probably work too. (I'm not sure I understand how do you handle nested lists). Keep in mind that some serializers (e.g. custom user ones) may not have `decodeSequentially` branch, so you need to support regular decoding anyway.

**Comment by hfhbd** [comment]
Thank you for the answer. I will create a special internal decoder for this partial use-case and also implement `decodeElementIndex`.

**Comment by pdvrieze** [comment]
@hfhbd The way to do this is to use the "merge" function. This does require you to special case the collection serializers in your format. The parsing of the elements just uses `decodeIndex` with the DONE value when finished. The format notes  that the parent is a collection and uses merge to add the element to the list.

**Comment by hfhbd** [comment]
@pdvrieze Do you mean this method?: https://github.com/Kotlin/kotlinx.serialization/blob/4af0f30b11ef2cdddc6d01f444783702f493d0a2/core/commonMain/src/kotlinx/serialization/internal/CollectionSerializers.kt#L26
Thanks, I will try it.
