### ISSUE TITLE
Update documentation about typealias and serialization

### ISSUE THREAD

**Issue by BugsBunnyBR** [Kotlin/kotlinx.serialization#2384]
Recently I needed to serialize a `List<File>` and was struggling to find how to properly setup kotlin serialization to do so,
even after [getting help pointing me to the documentation](https://kotlinlang.slack.com/archives/C7A1U5PTM/p1690794248552319) I couldn't understand how `typealias` could help with my issue. It would be great to have a sample in the docs showing how to use `typealias` to set the serializer for custom types in collections.

For anyone that arrives here, this is my solution

``` kotlin
typealias FileAsString = @Serializable(FileSerializer::class) File


class FileSerializer : KSerializer<File> {
    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("File", PrimitiveKind.STRING)

    override fun deserialize(decoder: Decoder): File {
        return File(decoder.decodeString())
    }

    override fun serialize(encoder: Encoder, value: File) {
        encoder.encodeString(value.absolutePath)
    }
}

data class MyItem(val files: List<FileAsString>)
```

**Comment by sandwwraith** [comment]
Typealias is only one of the ways to do it. Another is to use annotation on the type itself: `data class MyItem(val files: List<@Serializable(FileSerializer::class) File>)`
