### ISSUE TITLE
Question: How closely does this library need to match the Kotlin stdlib?

### ISSUE THREAD

**Issue by nhalase** [Kotlin/kotlinx.serialization#2387]
Per the title, should I worry about using 1.5.1 while upgrading my Kotlin stdlib to 1.9?

**Comment by sandwwraith** [comment]
I'm not sure what you mean by 'closely'. Usually, when talking about dependencies, either backward or forward compatibility is discussed. Kotlin standard library is fully backward compatible, so any library compiled with stdlib 1.8 (including serialization 1.5.1) should work fine with stdlib 1.9. Does that answer your question?

**Comment by nhalase** [comment]
it does. thank you!
