### ISSUE TITLE
Add Apache 2 License Information into pom.xml

### ISSUE THREAD

**Issue by guenhter** [Kotlin/kotlinx.serialization#239]
Hi,

Looking at the `pom.xml` for the serialization libraries like https://bintray.com/kotlin/kotlinx/kotlinx.serialization.runtime/0.8.2-rc13 doesn't contain any license information like other Kotlin modules do https://search.maven.org/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-jdk8/0.30.2-eap13/jar

```
<licenses>
    <license>
      <name>The Apache Software License, Version 2.0</name>
      <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
      <distribution>repo</distribution>
    </license>
  </licenses>
```

This license information should be added.

**Comment by sandwwraith** [comment]
Thanks for noticing!
