### ISSUE TITLE
Missing classes when minifying with R8

### ISSUE THREAD

**Issue by hristogochev** [Kotlin/kotlinx.serialization#2392]
Attempting to obfuscate and shrink any app that uses the `kotlinx.datetime` library (which depends on this library) results in the following errors caused by the proguard rules of this library:

```
> Task :app:minifyReleaseWithR8 FAILED
AGPBI: {"kind":"error","text":"Missing class kotlinx.serialization.KSerializer (referenced from: kotlinx.datetime.serializers.InstantIso8601Serializer)\nMissing class kotlinx.serialization.Serializable (referenced from: kotlinx.datetime.Instant)","sources":[{}],"tool":"R8"}
```

**To Reproduce**
1. Create a new Android app.
2. Add the following dependency: implementation("org.jetbrains.kotlinx:kotlinx-datetime:0.4.0").
3. Create a new class which includes a field that is of type "Instant" and use it somewhere.
4. Attempt to obfuscate and shrink the app in release.

**Environment**
 - Kotlin version: 1.9.0
 - Library version: 1.5.0
 - Kotlin platforms: Android JVM
 - Gradle version: 8.1.0

**Comment by MarcelReiter** [comment]
Isn't this an issue of `kotlinx.datetime` rather than `kotlinx.serialization`?

**Comment by hristogochev** [comment]
I was wondering if I should open it there instead of here, but ultimately decided to post it here because it seems classes annotated with `Serializable` get obfuscated when they should not. If a team members thinks It's more appropriate for me to open it at `kotlinx.datetime` then can close this issue and I will open it in the appropriate repository.

**Comment by sandwwraith** [comment]
Given the line `referenced from: kotlinx.datetime.serializers.InstantIso8601Serialize` I guess it is kotlinx.datetime classes that got incorrectly obfuscated rather than kotlinx.serialiaztion classes. kotlinx.serialization distributes own proguard rules anyway. So I'd recommend open this issue in kotlinx.datetime

**Comment by hristogochev** [comment]
Thank you!
