### ISSUE TITLE
Attempt to invoke virtual method kotlinx.serialization.KSerializer on a null object reference

### ISSUE THREAD

**Issue by tethridge** [Kotlin/kotlinx.serialization#2416]
**Describe the bug**
Updating our existing code base to new versions of kotlinx.serialization cause an exception to be thrown when the serializer is accessed via the companion object.  We use an enum that includes the String name of the event and its Serializer for parsing events in our application.  See EventName.kt in commonMain.  In Greeting#greet() there is a call to access the serializer on one of the events.  I've simplified the code so that the exception we are seeing is thrown.  I left the enum in to show the logic we are using in case there is a recommended work around.

`java.lang.ExceptionInInitializerError
  at com.example.cocoapods.test.eventnamestest.EventName.<init>(EventName.kt:18)
  at com.example.cocoapods.test.eventnamestest.EventName.<clinit>(EventName.kt:20)
  at com.example.cocoapods.test.eventnamestest.SpeechStartEvent.<clinit>(EventName.kt:47)
  at com.example.cocoapods.test.eventnamestest.Greeting.greet(Greeting.kt:7)
  at com.example.cocoapods.test.eventnamestest.android.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:23)
  at com.example.cocoapods.test.eventnamestest.android.ComposableSingletons$MainActivityKt$lambda-1$1.invoke(MainActivity.kt:22)`

**To Reproduce**
I've created a sample repo that demonstrates this issue.  If you revert the version of "kotlinx-serialization-json" to 1.4.1, then it works fine.  Newer versions of the library cause the exception.

https://github.com/tethridge/EventNameTest/

**Expected behavior**
The serializer is returned via the Companion object when serializer() is called without throwing an exception.

**Environment**
 - Kotlin version: 1.8.21
 - Library version: 1.4.1 (works), 1.5.0 (fails), 1.5.1-RC (fails), 1.5.1 (fails), 1.6.0 (fails)
 - Kotlin platforms: Android, Native
 - Gradle version: 8.0
 - IDE version (if bug is related to the IDE) Android Studio Giraffe | 2022.3.1
 - Other relevant context Mac OS 13.4.1

**Comment by sandwwraith** [comment]
Minimized reproducer: 
```
    @Test
    fun run() {
        val foo = UnhandledEvent.serializer()
    }

   @Serializable
    enum class EventName constructor(
        private val serialName: String,
        val deserializationStrategy: DeserializationStrategy<out MyEvent> = UnhandledEvent.serializer()
    ) {
        @SerialName(SN_UNHANDLED_EVENT)
        UNHANDLED_BOT_EVENT(SN_UNHANDLED_EVENT),

        @SerialName(SN_SPEECH_START_EVENT)
        SPEECH_START_EVENT(SN_SPEECH_START_EVENT, SpeechStartEvent.serializer()),
        ;
        companion object {
            private val SN_LIST = entries.associateBy { it.serialName }
        }
    }

    @Serializable
    sealed class MyEvent {
        @SerialName("name")
        abstract val eventName: EventName
    }

    @Serializable
    sealed class SpeechEvent : MyEvent()

    @Serializable
    class SpeechStartEvent : SpeechEvent() {
        @SerialName("name")
        override val eventName: EventName = EventName.SPEECH_START_EVENT
    }

    @Serializable
    data class UnhandledEvent(
        override val eventName: EventName = EventName.UNHANDLED_BOT_EVENT,
        @SerialName("name")
        val unhandledSerialName: String
    ) : MyEvent()

private const val SN_UNHANDLED_EVENT = "unhandled_event"
private const val SN_SPEECH_START_EVENT = "speech_start_event"
```

This looks like cyclic initialization problem:  
To load `UnhandledEvent` class, you need to load `EventName` class, but it tries to load `UnhandledEvent.serializer()` — for `UnhandledEvent` we're currently loading. I can recommend you initialize `deserializationStrategy` more lazily, like this:

```
    enum class EventName constructor(
        private val serialName: String,
        val deserializationStrategy: () -> DeserializationStrategy<out MyEvent>? = { UnhandledEvent.serializer() }
    ) {
        @SerialName(SN_UNHANDLED_EVENT)
        UNHANDLED_BOT_EVENT(SN_UNHANDLED_EVENT),

        @SerialName(SN_SPEECH_START_EVENT)
        SPEECH_START_EVENT(SN_SPEECH_START_EVENT, { SpeechStartEvent.serializer() }),
        ;
```
