### ISSUE TITLE
@EncodeDefault not working in object variables

### ISSUE THREAD

**Issue by denchic45** [Kotlin/kotlinx.serialization#2426]
**Describe the bug**
I have a sealed class which has 2 subclasses: a data class and an object, both have an overridden property with a declared value. The problem is that in the object this value is ignored despite the @EncodeDefault annotation:

**To Reproduce**
```kotlin
import kotlinx.serialization.*
import kotlinx.serialization.json.*

fun main() {
    val telegram = Json.encodeToString(TelegramSocialMedia(50, 0, 0, false))
    println("Telegram: $telegram")
    val youtube = Json.encodeToString(YouTubeSocialMedia)
    println("Youtube: $youtube")
}


@Serializable(SocialMediaSerializer::class)
sealed class SocialMedia {
    abstract val type: SocialMediaType
}

@Serializable
data class TelegramSocialMedia(
    val limit: Int,
    val offsetId: Int,
    val addOffset: Int,
    val reverse: Boolean
) : SocialMedia() {

    @OptIn(ExperimentalSerializationApi::class)
    @EncodeDefault
    override val type: SocialMediaType = SocialMediaType.TELEGRAM_CHANNEL
}

@Serializable
data object YouTubeSocialMedia : SocialMedia() {

    @OptIn(ExperimentalSerializationApi::class)
    @EncodeDefault
    override val type: SocialMediaType = SocialMediaType.YOUTUBE
}

object SocialMediaSerializer : JsonContentPolymorphicSerializer<SocialMedia>(SocialMedia::class) {
    override fun selectDeserializer(element: JsonElement): DeserializationStrategy<SocialMedia> {
        return when (Json.decodeFromJsonElement<SocialMediaType>(element.jsonObject.getValue("type"))) {
            SocialMediaType.TELEGRAM_CHANNEL -> TelegramSocialMedia.serializer()
            SocialMediaType.YOUTUBE -> YouTubeSocialMedia.serializer()
        }
    }
}

enum class SocialMediaType { YOUTUBE, TELEGRAM_CHANNEL }
```
Result:
```
Telegram: {"limit":50,"offsetId":0,"addOffset":0,"reverse":false,"type":"TELEGRAM_CHANNEL"}
Youtube: {}
```
**Expected behavior**
```
Telegram: {"limit":50,"offsetId":0,"addOffset":0,"reverse":false,"type":"TELEGRAM_CHANNEL"}
Youtube: {"type":"TELEGRAM_CHANNEL"}
```
When switching to kotlin 1.9.0 and using data object, the problem is solved
**Environment**
 - Kotlin version: 1.8.20
 - Library version: 1.6.0
 - Kotlin platforms: JVM
 - Gradle version: 8.2

**Comment by pdvrieze** [comment]
The problem is the semantics of object (de)serialization. Deserialization should not create a new object, only add a reference to the existing object. Some objects have state for which serialization may make sense, or even deserialization to update it. The changes in the plugin for 1.9.0 allowed for this limited circumstance and thus expose the properties in the object.

In this case however I would use a custom serializer for `YouTubeSocialMedia` that would handle things correctly.

**Comment by sandwwraith** [comment]
Yes, it is an intended behavior. Objects do no serialize their properties, as they always have the same values (see https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/builtin-classes.md#unit-and-singleton-objects). 

Regarding `data object`, this feels like a bug. `data object` should be the same as a regular `object`.
