### ISSUE TITLE
Add a stable Efficient Binary Format to the library

### ISSUE THREAD

**Issue by arkivanov** [Kotlin/kotlinx.serialization#2428]
Currently, my libraries [Decompose](https://github.com/arkivanov/Decompose) and [Essenty](https://github.com/arkivanov/Essenty) are based on `kotlin-parcelize` plugin, which is made available in `commonMain` and typealiased on `androidMain`. But unfortunately, it appears that this feature won't be supported in K2 (see [KT-58892](https://youtrack.jetbrains.com/issue/KT-58892)).

Im trying to migrate both libraries to `kotlinx-serialization`, and it looks like that the only stable format currently is JSON. As I'm looking for an alternative to Android Parcelable, ideally I would like to have something like the [Efficient Binary Format](https://github.com/Kotlin/kotlinx.serialization/blob/v1.6.0/docs/formats.md#efficient-binary-format). Unfortunately, extending `AbstractEncoder` class or implementing `Encoder` and `Decoder` interfaces is not considered stable, so I can't do it in a library.

Would it be possible to add a stable variant of the Efficient Binary Format? I could contribute. Thanks!

**Comment by pdvrieze** [comment]
@arkivanov The interfaces of Encoder/Decoder are more or less stable, you could even use those to serialize to parcels. The only instability is that the api may change slightly (adding functions you must implement) Alternatively you may want to use protobuf (possibly wrapped in a gzip stream).

**Comment by arkivanov** [comment]
Since I will need this not only for Android, I think I will use ProtoBuf.

**Comment by arkivanov** [comment]
Though, would be really nice to have ProtoBuf stable. I'm a it scared of using it in transitive dependencies.

**Comment by sandwwraith** [comment]
Encoder's instability is a valid concern of implementing a 3rd party format. We try to make changes to it as most compatible is possible, but we'll look into its stabilization soon.

However, I do not understand how protobuf can help you here. Shouldn't you serialize/deserialize primitives directly to `Bundle`? Keep in mind that protobuf and Kotlin's nullability may have some quirks when working together.

**Comment by arkivanov** [comment]
As I mentioned, I'm looking for a replacement for expect/actual Parcelable/Parcelize in KMP, that would work with K2. See [KT-58892](https://youtrack.jetbrains.com/issue/KT-58892) for details of the issue. Currently (with K1) developers who use the Decompose library are able to preserve the state over configuration changes on Android and process death on Android/Apple/JVM targets. The library provides an API that brings Parcelable/Parcelize in `commonMain`.

Since this won't work with K2, I'm trying to replace Parcelable/Parcelize with `kotlinx-serialization`. Users could store their serializable data using the API from Decompose, and then that data could be serialised as a `ByteArray`, and included in a `Bundle` on Android, saved to a file on Desktop (JVM), encoded via NSCoder on Apple, etc.

On Android, when the process crashes or the package is updated via Google Play, all the saved state is automatically dropped. But this might not be the case on other platforms, e.g. on Desktop/JVM with manual saving into a file. So I think using a proper key/value serialization (like JSON or protobuf) there will be an explicit runtime error if the signature of a serializable class has changed. With the Efficient Binary Format I'm able to e.g. swap the order of two `Int` properties and each property will receive the value of its sibling, which is incorrect.

**Comment by arkivanov** [comment]
I think JSON is too verbose for Android, given its hard limits of the `Bundle` size. So protobuf looks like a good trade-off.

**Comment by sandwwraith** [comment]
>  With the Efficient Binary Format I'm able to e.g. swap the order of two Int properties and each property will receive the value of its sibling, which is incorrect.

But this is also true for Protobuf in case you're using automatically assigned field numbers (i.e. do not annotate everything with `@ProtoNumber`).

> What are the quirks with protobuf and nullability?

Protobuf doesn't have a notion of `null`. So if you have a property like `val s: Stirng? = "foo"`, you can't get `null` there by deserializing, it will always be the default value. Also, having `null` in such a property during serialization will lead to an exception.

**Comment by arkivanov** [comment]
> But this is also true for Protobuf

Right, this is true. But at least removing a property will lead to a runtime error, rather automatically assigning the  value to the next serialized class. Also adding a new property would also lead to an error rather than then value being taken from the next serialized class. Still safer than the efficient binary format, I guess.

> Protobuf doesn't have a notion of null

That a very useful comment. Thanks, I will double check everything.
