### ISSUE TITLE
Kotlin-serialization causes LinkageError

### ISSUE THREAD

**Issue by IARI** [Kotlin/kotlinx.serialization#243]
At some point in my project, this started to happen.
Ever since, the IDE highlighting, error reporting and Navigation are unreliable/erroneous.

![image](https://user-images.githubusercontent.com/1053417/47260230-92b15900-d4b7-11e8-9ed9-a1a5dc88694e.png)

    ext.kotlin_version = '1.2.70'
    ext.serialization_version = '0.6.2'

Using IntelliJ IDEA 2018.2.5 (Community Edition)
Build #IC-182.4892.20, built on October 16, 2018
JRE: 1.8.0_152-release-1248-b19 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

What additional information can I supply to get to the bottom of this problem?

**Comment by sandwwraith** [comment]
It is probably caused by the outdated plugin in the IDE. Open "Settings -> Plugins", find "kotlin-serialization" and make sure that it is also 0.6.2

**Comment by sandwwraith** [comment]
Starting from Kotlin 1.3, an additional plugin is not required. If it causes any errors (and it probably does, since it is not updated anymore), just delete it.
