### ISSUE TITLE
Please document typeSerialX arguments for serializers of generic classes

### ISSUE THREAD

**Issue by arkivanov** [Kotlin/kotlinx.serialization#2431]
There seems to be no mention of the following cool feature in the docs, that I discovered by accident.

```kotlin
@Serializable
class Data<out T>(val list: List<T>)

fun foo() {
    val stringDataSerializer = Data.serializer(typeSerial0 = String.serializer()) // This feature is not documented
}
```

**Comment by sandwwraith** [comment]
There's mention about that here: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#plugin-generated-generic-serializer

What parts are missing, in your opinion?

**Comment by arkivanov** [comment]
Nice thanks. Somehow I missed that section.
