### ISSUE TITLE
Polymorphic serializer was not found for missing class discriminator ('null')

### ISSUE THREAD

**Issue by yektasarioglu** [Kotlin/kotlinx.serialization#2445]
**Describe the bug**
`Polymorphic serializer was not found for missing class discriminator ('null') JSON input: .....s fa-reddit","intentLink":"https://reddit.com/submit?url"}]}`

Also tried the polymorphic registration, but that did not help also.

**To Reproduce**
``` kotlin
// Main.kt
Json.decodeFromString<BlogConfiguration>(remoteConfig.configuration)

// BlogConfiguration.kt
@Serializable
data class BlogConfiguration(
    val showMostRecentBlogPosts: Int,
    val features: List<Feature>
)

@Serializable
@SerialName("ShareBlogPostFeature")
data class ShareBlogPostFeature(
    override val isEnabled: Boolean,
    val shareSocialItems: List<ShareSocialItem>
): Feature

@Serializable
sealed interface Feature {
    val isEnabled: Boolean
}

@Serializable
data class ShareSocialItem(
    val name: String,
    val description: String,
    val fontAwesomeClasses: String,
    val intentLink: String
)
```

**Expected behavior**

**Environment**
 - Kotlin version: 1.8.10
 - Library version: 1.5.0
 - Kotlin platforms: JS
 - Gradle version: 8.0.2
 - IDE version: IntelliJ IDEA 2023.2.2

**Comment by sandwwraith** [comment]
Can you show your input? Does it have `type` key in it? To properly deserialize `List<Feature>`, each `Feature` should have a `type` key to determine what implementor of `sealed interface Feature` should be instantiated. (See more docs here: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md#sealed-classes)
