### ISSUE TITLE
Make classDiscriminator accept null as a valid parameter and omit synthetic fields from output

### ISSUE THREAD

**Issue by obask** [Kotlin/kotlinx.serialization#2446]
**What is your use-case and why do you need this feature?**

My frontend doesn't want any artificial fields added to serialized classes(Typescript doesn't have tagged unions anyway), but `classDiscriminator` field doesn't accept `null` or empty strings as a solution. It's not nice that a serializer arbitrary modifies data classes and there is no way to remove these fields without writing a custom serializer.

https://github.com/obask/skillen-server/blob/main/src/main/kotlin/process.kt#L11
PS I don't need to deserialize this json back to polymorphic types

**Describe the solution you'd like**

It looks like `AbstractJsonTreeEncoder` already supports nullable polymorphicDiscriminator, so the solution would be to make it nullable everywhere else (`JsonConfiguration`) and convert "" in JsonClassDiscriminator into null or add another parameter for that.

**Comment by sandwwraith** [comment]
I guess you want NEVER from #1247 (it's a feature that's being worked on)
