### ISSUE TITLE
Android SDK 23: Kotlin Serialization error

### ISSUE THREAD

**Issue by Psijic** [Kotlin/kotlinx.serialization#2457]
I have a bug with SDK 23 but all is fine with SDK 26+. Didn't have such bug before even with SDK 23 (got it after some gradle updates).
```
 java.lang.IllegalArgumentException: Bad position (limit 126): -16132
  at java.nio.Buffer.positionImpl(Buffer.java:351)
  at java.nio.Buffer.position(Buffer.java:345)
  at java.nio.charset.CharsetDecoderICU.setPosition(CharsetDecoderICU.java:205)
  at java.nio.charset.CharsetDecoderICU.decodeLoop(CharsetDecoderICU.java:154)
  at java.nio.charset.CharsetDecoder.decode(CharsetDecoder.java:306)
  at kotlinx.serialization.json.internal.CharsetReader.doRead(CharsetReader.kt:74)
  at kotlinx.serialization.json.internal.CharsetReader.read(CharsetReader.kt:64)
  at kotlinx.serialization.json.internal.JavaStreamSerialReader.read(JvmJsonStreams.kt:261)
  at kotlinx.serialization.json.internal.ReaderJsonLexer.preload(JsonLexer.kt:87)
  at kotlinx.serialization.json.internal.ReaderJsonLexer.ensureHaveChars(JsonLexer.kt:134)
  at kotlinx.serialization.json.internal.ReaderJsonLexer.canConsumeValue(JsonLexer.kt:61)
  at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeObjectIndex(StreamingJsonDecoder.kt:222)
  at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeElementIndex(StreamingJsonDecoder.kt:175)
```

org.jetbrains.kotlinx:kotlinx-serialization-json:1.5.1, 1.6.0
Kotlin 1.9.10
jvm = "17"

**Comment by zoltish** [comment]
+1 Seeing this on API 21 as well.

**Comment by zoltish** [comment]
Sure! Ive been using the same setup for well over a year without issues though, so not sure if it will be helpful. I was upgrading my dependencies when this issue came about; namely kotlin & jetpack compose. 

```
gradle = '8.3.0-alpha11'
kotlin = '1.9.10'
compose = '1.6.0-alpha08'
compose-compiler = '1.5.3'
```

I cant share the exact JSON input unfortunately, but the issue happens when the application is launched initially and imports a bunch of data from JSON files (stored under _/raw/_ in Android). Im simply using the below function to import from 5 different files to make that work.

```
    private inline fun <reified T> parseResource(
        raw: Int,
    ): List<T> {
        return context.resources.openRawResource(raw).use { stream ->
            Json.decodeFromStream(stream)
        }
    }
```

Some sample classes below, its pretty much the same thing across 19 classes in total. Nothing fancy, just simple data classes like below. Their structure matches that of the JSON input exactly; and it works flawlessly on other API levels. Please let me know if theres anything more I can do to help investigate!

```
@Serializable
data class MovementDto(
    val id: String,
    val exerciseId: String,
    val groupId: String? = null,
    val note: String? = null,
    val plans: List<PlanDto>,
)

@Serializable
data class PlanDto(
    val id: String,
    val rest: Long? = null,
    val duration: Long? = null,
    val mark: Mark? = null, // Enum
    val repetitionRange: RepetitionRangeDto? = null,
)

@Serializable
data class RepetitionRangeDto(
    val min: Int = 0,
    val max: Int = 0,
    val amrap: Boolean = false,
)
```

**Comment by sandwwraith** [comment]
@zoltish Is there any possibility you can replace any sensitive data inside Json with `*` (so key and values length will remain the same) and check if the issue is still there, and if so, share it? Given that this is a problem with indices somewhere, without a stable reproducer, it will be just wild guesses over and there.

**Comment by sandwwraith** [comment]
As a workaround in the meantime, you can use `decodeFromString`. Also, given that it doesn't reproduce on a regular JVM (does it?), it maybe an Android SDK bug, although the only issue I found is already fixed: https://issuetracker.google.com/issues/37054036

**Comment by zoltish** [comment]
@sandwwraith As luck would have it, the issue seems to arise no matter which file Im trying to import from.. so heres one that fails. Really simple stuff, hopefully you can recreate it?

```
[
    {
        "type": "ABS",
        "name": "Abs",
        "color": "#4CAF50"
    },
    {
        "type": "BACK",
        "name": "Back",
        "color": "#2962FF"
    },
    {
        "type": "BICEPS",
        "name": "Biceps",
        "color": "#0091EA"
    },
    {
        "type": "CALVES",
        "name": "Calves",
        "color": "#C51162"
    },
    {
        "type": "CARDIO",
        "name": "Cardio",
        "color": "#607D8B"
    },
    {
        "type": "CHEST",
        "name": "Chest",
        "color": "#D32F2F"
    },
    {
        "type": "FOREARMS",
        "name": "Forearms",
        "color": "#795548"
    },
    {
        "type": "LEGS",
        "name": "Legs",
        "color": "#651FFF"
    },
    {
        "type": "SHOULDERS",
        "name": "Shoulders",
        "color": "#F4511E"
    },
    {
        "type": "TRICEPS",
        "name": "Triceps",
        "color": "#009688"
    }
]
```

```
@Serializable
data class MuscleDto(
    val type: MuscleType,
    val name: String,
    val color: String,
) 
```

**Comment by pdvrieze** [comment]
> As a workaround in the meantime, you can use `decodeFromString`. Also, given that it doesn't reproduce on a regular JVM (does it?), it maybe an Android SDK bug, although the only issue I found is already fixed: https://issuetracker.google.com/issues/37054036

Looking at the actual fix for decoder also included in the tracker issue that is a patch on top of one of the lines in the stacktrace. Unfortunately Android has a long compatibility window.

**Comment by sandwwraith** [comment]
Hm, unfortunately, I'm still unable to reproduce the issue. I've tried the following config:

```
compileSdk = 33
    defaultConfig {
        applicationId = "com.example.cocoapods.test.android"
        minSdk = 21
        targetSdk = 21
        versionCode = 1
        versionName = "1.0"
    }
    buildFeatures {
        compose = true
    }
    composeOptions {
        kotlinCompilerExtensionVersion = "1.4.7"
    }
    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }
```

It runs fine on both API 26 and API 33 emulators. Is this issue specific to some particular device? Is it reproducible when your input is just a string converted with `.byteInputStream()` or is a file an absolute must? Maybe some other build differences?

**Comment by zoltish** [comment]
The issue is specific to API 21, did you try that? Emulator is a Pixel 3! Will investigate further tomorrow!

**Comment by sandwwraith** [comment]
If it is reproducible on API 21 (Lollipop 5.0) and not reproducible on higher ones (5.1+), then I believe it is the very same issue from Google Tracker. They said they fixed it in 5.1.1

**Comment by zoltish** [comment]
If thats the case: very strange. It has been working flawlessly for Id say probably 2 years; I just ran into this as I was upgrading my dependencies. Could there be any other explanation?

**Comment by sandwwraith** [comment]
Well, yes, serialization before 1.5.1 didn't use aforementioned CharsetDecoder. It was introduced as optimization.

**Comment by zoltish** [comment]
Ah, okay! Thanks for all the help, the workaround works for my case, especially since its a one time thing.
