### ISSUE TITLE
[Question] Remove type property from sealed class

### ISSUE THREAD

**Issue by furstenheim-goodnotes** [Kotlin/kotlinx.serialization#2458]
I'm using sealed classes. I see from the [docs](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md#sealed-classes) that the full path is included in the serialization as the "type" property. Is there a way to avoid this?

In my particular use case, I have another field that I use to discriminate one type or the other. Maybe in that case that can be done?

In general, I would like to avoid showing internals of the code (in this case class path and name) to external customers.

Thanks

**Comment by pdvrieze** [comment]
@furstenheim-goodnotes The full path is only default. If you specify an `@SerialName` annotation on the type that name will be used instead of the (internal) type name. This works for any format. Specifically for Json, there is also a way to specify the name of the attribute used as type discriminator (using the [`classDiscriminator`](https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-json/kotlinx.serialization.json/-json-builder/class-discriminator.html) property)

**Comment by pdvrieze** [comment]
@furstenheim-goodnotes In such case "status" is the class discriminator, and the serial names for the two options are "failure"/"success". If you need something more complex what you need is basically look at data dependent serialization (you use some sort of delegate, be it a JsonElement or a data object that you then get the right child from - you need a custom serializer in either case - note that a custom serializer isn't actually that hard to write - and if you use some sort of delegation, you can just rename the descriptor from that delegated type).

**Comment by furstenheim-goodnotes** [comment]
Solved, using JsonContentPolymorphicSerializer.

In the main class:

```
@Serializable(with = MyClassSerializer::class)
sealed class MyClass {

}
```
Then on the serializer:

```
@Serializer(forClass = MyClass::class)
object MyClassSerializer : JsonContentPolymorphicSerializer<MyClass>(MyClass::class) {
    override fun selectDeserializer(element: JsonElement): DeserializationStrategy<out MyClass> {
        val status = element.jsonObject["status"]?.jsonPrimitive?.content
        return when (status) {
            Status.SUCCESS.toString() -> MyClass.Success.serializer()
            Status.FAILURE.toString() -> MyClass.Failure.serializer()
            else -> throw Exception("ERROR: Serializer not implemented")
        }
    }
}
```

**Comment by sandwwraith** [comment]
#1247
