### ISSUE TITLE
Use default when passed value is null

### ISSUE THREAD

**Issue by dri94** [Kotlin/kotlinx.serialization#246]
When deserializing a json and we get a null value passed down, an annotation/setting should be allowed to instead use the default value. The following scenario will fail if deserialize because it is looking for a non-null value

```
{ 
"name": "john",
"number": null
}

data class Person(val name: String = "", val number: String ="")
```
If we had an annotation that specified to use default if null, the the following would deserialize correctly using the default value.
```
{ 
"name": "john",
"number": null
}

data class Person(val name: String = "", @UseDefault val number: String ="")
```

If this exists then please point me to the documentation :) Thanks.

**Comment by SpaceBison** [comment]
I think there should be an option to use default values if deserialization fails for any reason.

**Comment by pie-flavor** [comment]
I was shocked that the default behavior was anything other than that.
