### ISSUE TITLE
Json.decodeFromString throwing IllegalStateException when supplied with incorrect JSON string

### ISSUE THREAD

**Issue by karwaankit32** [Kotlin/kotlinx.serialization#2462]
**On passing JSON string with incorrect format, Kotlinx Json.decodeFromString starts throwing "java.lang.IllegalStateException: Reader has not consumed the whole input: JsonReader*" exception which is not mentioned in the documentation https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-json/kotlinx.serialization.json/-json/decode-from-string.html**

**To Reproduce**
Passing input to Json.decodeFromString -
`{
    "Id": "WW",
    "payload": {
        "Id": "WW",
        "DriverTemp": 27,
        "PassengerTemp": 37,
        "SteeringTemp": 63,
        "Location": "6654.31,754.41",
        "OutsideTemp": 90
    }
}
routingRuleName:lambda  
{
    "Id": "QQ",
    "payload": {
        "Id": "QQ",
        "DriverTemp": 27,
        "PassengerTemp": 37,
        "SteeringTemp": 63,
        "Location": "6635.31,735.41",
        "OutsideTemp": 90
    }
}`

starts throwing 

`

[Worker-0f743a2fc97ee117a] java.lang.IllegalStateException: Reader has not consumed the whole input: JsonReader(source='{     "Id": "WW",     "payload": {         "Id": "WW",         "DriverTemp": 27,         "PassengerTemp": 37,         "SteeringWheelTemp": 63,         "Location": "665.31,75.41",         "OutsideTemp": 90     } }routingRuleName:lambda	{     "Id": "QQ",     "payload": {         "Id": "QQ",         "DriverTemp": 27,         "PassengerTemp": 37,         "SteeringWheelTemp": 63,         "Location": "6654.31,754.41",         "OutsideTemp": 90     } }', currentPosition=205, tokenClass=0, tokenPosition=190, offset=190)
`

**Expected behavior**
It should throw SerializationException on being passed incorrect Json string

**Environment**
 - Kotlin version: 1.8.x
 - Library version: 1.8.x
 - Kotlin platforms: JVM
 - Gradle version: 7.x
 - IDE version (if bug is related to the IDE):  N/A
 - Other relevant context [e.g. OS version, JRE version, ... ]

**Comment by sandwwraith** [comment]
Which version of the library do you use? There's no such exception message in kotlinx-serialization-json 1.6.0.

**Comment by sandwwraith** [comment]
1.6.0 exception message is `kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 151: Expected EOF after parsing, but had r instead at path: $`

**Comment by sandwwraith** [comment]
@karwaankit32 I'm asking about the runtime library. `kotlinx-serialization-json` dependency.

**Comment by karwaankit32** [comment]
Hi sandwwraith,
org.jetbrains.kotlinx_kotlinx-serialization-runtime-1.0-M1-1.4.0-rc is the kotlinx runtime dependency we are consuming

**Comment by sandwwraith** [comment]
@karwaankit32 Then you should update it if you want to have this problem fixed — recent versions have correct error message
