### ISSUE TITLE
serializing generics type Any

### ISSUE THREAD

**Issue by orelvis15** [Kotlin/kotlinx.serialization#2467]
**Describe the bug**

Hi guys, I'm trying to do the following

```kotlin
@Serializable
data class ClassA<T>(
    val id: String,
    val status: Boolean,
    val data: ClassB<T>
)

@Serializable
data class ClassB<T>(
    val data: T
)
```

```json
{
    "id": "123",
    "status": true,
    "data": {
        "data": {
            "key1": "value1",
            "key2": 42,
            "key3": true
        }
    }
}
```

I want to deserialize a json to those classes, the generic type would be `Map<String, Any>`

val map: Map<String, Any> = json.decodeFromString(json)

In this case it is throwing the error:
```
Serializer for class 'Any' is not found.
Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.
```

**Environment**
 - Kotlin version: 1.9.10
 - Library version: 1.6.0
 - Kotlin platforms: JVM, JS, Native
 - Gradle version: 8.4
 - IDE version: IntellijIDEA 2023.2.2

**Comment by sandwwraith** [comment]
`Map<String, Any>` is not serializable (see #746 and #296). If your data is untyped, you may want to deserialize it into `JsonElement`. You can use `val map: JsonElement = json.decodeFromString(json)` or `json.parseToJsonElement`. You can also use JsonElement as a type argument: `json.decodeFromString<ClassA<JsonElement>>(json)`.
