### ISSUE TITLE
Missing serializer for @Serializable in tests

### ISSUE THREAD

**Issue by e5l** [Kotlin/kotlinx.serialization#248]
Common test class:
```kotlin
@Serializable
data class User(val id: Long, val login: String)


class KotlinxSerializerTest {

    @Test
    fun myTest() {
        User::class.serializer()
    }
}
```
leads to `SerializationException: Can't locate serializer for class User` for all(jvm, js, native) platforms

**Comment by e5l** [comment]
Resolved

**Comment by mattkranzler5** [comment]
@e5l how did you resolve this? I'm getting the same error when trying to run some unit tests.

**Comment by e5l** [comment]
Hi, @mattkranzler5.

It was related to `kotlin-multiplatform` and `kotlin-platform-*`. I forget to apply the `serialization` Gradle plugin in platform modules.

Hope it fixes your problem.
