### ISSUE TITLE
Missing properties while serialization

### ISSUE THREAD

**Issue by pushpull-npr** [Kotlin/kotlinx.serialization#2486]
**Describe the bug**
I am serializing a data class annotated with Serializable. Sometimes, some properties are missing in json string when serialized while other time it's working as expected
**To Reproduce**
Attach a code snippet or test data if possible.
```
@Serializable
data class Locker(
	val sessionId: String,
	val timestamp: Long = Instant.now().toEpochMilli()
)
```
```
private val json = Json
private var locker: Locker? = null
...
locker = Locker(sessionId = RealmUUID.random().toString())
val lockerString = json.encodeToString(locker)
```
**Expected behavior**
I have added debugger screenshot. `Locker` have `timestamp` but isn't serialized. And this happens once in a while, not every time.

**Environment**
 - Kotlin version: 1.9.0
 - Library version: 1.6.0
 - Kotlin platforms: Android

![A1](https://github.com/Kotlin/kotlinx.serialization/assets/139027251/d56ce18a-97ad-4281-bed6-2e330528c18a)
![a2](https://github.com/Kotlin/kotlinx.serialization/assets/139027251/d0cc877e-e52a-461e-99b4-3b4c0cc6b0ab)

**Comment by pushpull-npr** [comment]
#### Unit test
```
@Test
fun test_locker() {
	var locker  : DyncInator.Companion.Locker? = null
	val json = Json

	repeat(10) {
		locker = DyncInator.Companion.Locker(sessionId = it.toString())
		val jsonStr = json.encodeToString(locker)
		println(jsonStr)
	}
}
```
#### Output
```
{"sessionId":"0","timestamp":1698380767079}
{"sessionId":"1","timestamp":1698380767091}
{"sessionId":"2"}
{"sessionId":"3"}
{"sessionId":"4"}
{"sessionId":"5"}
{"sessionId":"6"}
{"sessionId":"7"}
{"sessionId":"8"}
{"sessionId":"9"}
{"sessionId":"10"}
```

**Comment by pushpull-npr** [comment]
Found another thing, it only happens if `timestamp`  has a default value and not if
```
@Serializable
data class Locker(
	val sessionId: String,
	val timestamp: Long
)
```

**Comment by sandwwraith** [comment]
Default values are not encoded by default: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/basic-serialization.md#defaults-are-not-encoded-by-default

You can use `@EncodeDefault` annotation to fix that or create `Json { encodeDefaults = true }`
