### ISSUE TITLE
Export underlying JsonDecoder to public

### ISSUE THREAD

**Issue by iseki0** [Kotlin/kotlinx.serialization#2488]
**What is your use-case and why do you need this feature?**
I'm trying to create a decoder that decode `java.sql.ResultSet` to `List<Something>`. Some field might be JSON value. In `Decoder` we can return a JsonDecoder in `beginStructure` and `decodeInline...` method. 
So the problem is I can't create a JsonDecoder.

**Comment by pdvrieze** [comment]
To create a json decoder you need to go through the `Json` class itself and request decoding. You can always wrap that in a decoder that delegates parsing to that, but if you're looking at resultsets you probably just want to decode individual columns to individual types.
