### ISSUE TITLE
Gradle Resolution Issue

### ISSUE THREAD

**Issue by kylejbrock** [Kotlin/kotlinx.serialization#249]
After upgrading to org.jetbrains.kotlinx:kotlinx-serialization-runtime-native:0.9.0

I get a resolution issue because of:

Required org.gradle.usage 'java-api' and found incompatible value 'kotlin-api'

In 0.8.3-rc13 variants defined "org.gradle.usage": "java-api"
In 0.9.0 variants define "org.gradle.usage": "kotlin-api"

Is there something else I need to be configuring with gradle?

I'm using gradle 4.7 and:
kotlin_version = "1.3.0"
coroutine_version = "1.0.0"
serialization_version = "0.9.0"

Thanks

**Comment by ilmat192** [comment]
Hi!
There is not enough information to investigate this problem. Could you please provide the full error log? Also do you use the Kotlin/Native cinterop feature?

**Comment by kylejbrock** [comment]
Yes, there is a work around in this ticket: https://github.com/JetBrains/kotlin-native/issues/1828#issuecomment-435715496
