### ISSUE TITLE
[Question] in serialize sealed class, why declare the derive class type can't deserialize the object ?

### ISSUE THREAD

**Issue by nesteiner** [Kotlin/kotlinx.serialization#2490]
to reproduce this issue, you can type this code below
```kotlin
@Serializable
sealed class Item {
    @Serializable
    data class A(val number: Int): Item()
    @Serializable
    data class B(val number1: Int, val number2: Int): Item()
}

class SealedClassSerializationTest {
    @Test
    fun testSerialization() {
        val formatter = Json {
            encodeDefaults = true
            prettyPrint = true
        }

        val item: Item.A = Item.A(1)
        // this code is ok too
        // val item = Item.A(1)
        val s = Json.encodeToString(item)
        println(s)
        val result = Json.decodeFromString<Item>(s)
        println(result)
    }
}

```

when running this test, the result is
![image](https://github.com/Kotlin/kotlinx.serialization/assets/46296608/d87330b4-83cd-4a5e-a5d5-4396064338a4)

but this code in test is ok
```kotlin
val item: Item = Item.A(1)
```

![image](https://github.com/Kotlin/kotlinx.serialization/assets/46296608/0fa73b07-ef6e-4bba-9604-eb74a70a43f3)

why ??

**Comment by sandwwraith** [comment]
I've answered you here: https://github.com/Kotlin/kotlinx.serialization/issues/1382#issuecomment-1789276444. In short, serializers are determined using static type. Therefore, you're using serializer for Item.A, not Item. 

Discussion here: https://github.com/Kotlin/kotlinx.serialization/issues/1194
