### ISSUE TITLE
How to generate .proto file from annotated class during build?

### ISSUE THREAD

**Issue by dzielins42** [Kotlin/kotlinx.serialization#2498]
Hello,

I need `.proto` file to use in [Nanopb](https://github.com/nanopb/nanopb) for IoT project. I understand that `ProtoBufSchemaGenerator` can generate this file's content. I would like to have the file as build output so I can commit it into the repository. Can I do it using current version or will this be supported in the future?

**Comment by sandwwraith** [comment]
Yes, ProtoBufSchemaGenerator is intended for that.

> I would like to have the file as build output so I can commit it into the repository.

You'll need to do it yourself, as a Gradle plugin or as a one-time test, whatever suits you best.
