### ISSUE TITLE
[Question] why kotlinx.serialization won't serialize the field with default value ?

### ISSUE THREAD

**Issue by nesteiner** [Kotlin/kotlinx.serialization#2499]
given such code
```kotlin
class SerializeDefaultValue {
    @Serializable
    class Item(val id: Int = 0)
    @Test
    fun `test serialize with default value`() {
        val s = Json.encodeToString(Item())
        println(s)
    }
}
```

the result is `{}`, what?? I think it should serialize with the `id`, no matter if it is give the default value

**Comment by MikuApp** [comment]
Use `Json { encodeDefaults = true }.encodeToString(Item())`, see [Encoding defaults](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#encoding-defaults).

**Comment by nesteiner** [comment]
oh, thank you
