### ISSUE TITLE
Import problems with JSON

### ISSUE THREAD

**Issue by fab1an** [Kotlin/kotlinx.serialization#25]
Is there a way to configure IntellijIDEA to stop importing the standard `JSON` from kotlin-javascript? This trips me up multiple times per hour :(.

**Comment by flaghacker** [comment]
There's a setting in Idea to blacklist certain imports: https://www.jetbrains.com/help/idea/excluding-classes-from-auto-import.html

**Comment by fab1an** [comment]
I tried that, but kotlin's original `JSON` doesn't want to go away. It also does not have an import in the list.

**Comment by qwwdfsad** [comment]
Closing as outdated. If you still have this problem, please create youtrack ticket here https://youtrack.jetbrains.com/
