### ISSUE TITLE
Add a way to wrap a StringFormat with a text -> binary encoding to get a BinaryFormat

### ISSUE THREAD

**Issue by rnett** [Kotlin/kotlinx.serialization#2500]
**What is your use-case and why do you need this feature?**

In some situations, such as writing a file or sending a HTTP request body, I have an interface that only takes binary data (depending on the libraries used), but sometimes converts it back to text.  In these cases, and even if the content isn't converted back to text, I would like the ability to use a `StringFormat` as a `BinaryFormat`, by providing the text -> binary encoding.

For example, I could serialize things to JSON, then get the UTF-8 bytes of the result.  Or base64 encode the result.

**Describe the solution you'd like**

```kotlin
fun StringFormat.encodeToBinary(): BinaryFormat
```

With a JVM version that takes a `Charset`.  You could have a version with a `(String) -> ByteArray` to allow for things like base64.

I'd implement this just where I need it, but both format interfaces are noted to be unstable for implementing.

**Comment by sandwwraith** [comment]
Given that it is fairly easy to implement your own conversion, e.g.

```kotlin
class MyConversionFormat(val original: StringFormat): BinaryFormat {
  override fun <T> encodeToByteArray(serializer: SerializationStrategy<T>, value: T): ByteArray = base64.encode(original.encodeToString(serializer, value))
}
```

I do not see if it will bring any valuable addition to the library since the use-case is quite rare.

**Comment by rnett** [comment]
I agree it's easy to implement, but the issue is that `BinaryFormat` is [noted as not stable for extension](https://github.com/Kotlin/kotlinx.serialization/blob/d5bc7f7e27834064e8699ad6c9c39d6dcef039ed/core/commonMain/src/kotlinx/serialization/SerialFormat.kt#L53), so if I were to go this route, a user upgrading `kotlinx.serialization` could at any time cause runtime errors from my library.  Which makes this a non-starter.

Do you have any kind of timeline for when those interfaces might become stable?

**Comment by pdvrieze** [comment]
@rnett Your extension defines a new format. At this point writing an extension implies working with "unstable" APIs, most formats cannot be implemented without using these APIs. However, as specified, the interface is stable for use, meaning that the methods provided will stay (not change their interface). This means that your users will not be affected as long as you can commit to updating your format in line with the library updates in a timely fashion (your library could be blocking your users updating the serialization library).

Note that these particular interfaces haven't changed in a long time, and the main changes to expect would be added methods.
