### ISSUE TITLE
Pretty Printing an empty class adds a newline to json object

### ISSUE THREAD

**Issue by luca992** [Kotlin/kotlinx.serialization#2502]
**Describe the bug**

Empty classes get a newline character added to the json object:

```
{
  "some_empty_class": {
  }
}
```
It's not very pretty 😅

**To Reproduce**
```kotlin
@Serializable
data class Test(
    @SerialName("some_empty_class") val someEmptyClass: SomeEmptyClass,
)

@Serializable
class SomeEmptyClass

println(Json{prettyPrint = true}.encodeToString(Test(SomeEmptyClass())))
```

**Expected behavior**
All other libraries I have used when pretty printing would output:
```
{
  "some_empty_class": {}
}
```

**Environment**
 - Kotlin version: [e.g. 1.9.20]
 - Library version: [e.g. 1.6.0]

**Comment by sandwwraith** [comment]
Well, it is a matter of preference, mostly :) But I agree that since most libraries fold empty objects, we should likely do the same.

**Comment by luca992** [comment]
> Well, it is a matter of preference, mostly :) But I agree that since most libraries fold empty objects, we should likely do the same.

Yeah for sure haha. I just haven't seen other libraries do it that way 👍
