### ISSUE TITLE
[Question] Json.decodeToSequence array inside the json structure

### ISSUE THREAD

**Issue by banshifei** [Kotlin/kotlinx.serialization#2536]
Hello!
**What is your use-case and why do you need this feature?**
I have back-end method that return large array. Response JSON looks like
```
{
  "data": [
     { "itemName": "name1" },
     { "itemName": "name2" },
     ......
  ]
}
``` 

To parse this JSON I use `decodeToSequence` method like this
```
decodeToSequence<ItemDTO>(stream, DecodeSequenceMode.ARRAY_WRAPPED)
``` 
but before call `decodeToSequence` I must to skip `{ "data": ` from `stream` on the start and skip `}` from the end to avoiding parsing exception.
I didn't find any feature in kotlinx.serializaion to get rid from skipping. In other words, don't understand how to target decodeToSequence to concreat parameter. In my case, to `data`.

**Describe the solution you'd like**
Does kotlinx.serializaion have any feature to get rid from skipping? Or what is a best practise to use `decodeToSequence`?

**Comment by sandwwraith** [comment]
No, there aren't any embedded methods for this. So you'll need to decode all Json into memory.

**Comment by banshifei** [comment]
Maybe you can create any feature/tool to solve it? 😋

**Comment by sandwwraith** [comment]
That tool would either solve one specific problem like yours (and therefore won't work for other shapes of Json), or there should be a generic streaming tokenizer with a skip option, which doesn't fit into the current architecture. We do not plan to add either of them for now.
