### ISSUE TITLE
How to deal with nested object information unwanted in deserialized data classes

### ISSUE THREAD

**Issue by Bombo** [Kotlin/kotlinx.serialization#2539]
I already found two solutions for my problem, but I don't quite like both, for separate reasons. My hope is that I'm just missing a perfect solution due to sleep deprivation and dad brain.

### My use case

I'm trying to deserialize JSON from a custom API. Every endpoint of this API returns data that looks something like this:
```json
{
  "typeName": {
    "prop1": "value",
    "prop2": "value",
    […]
  }
}
```

I want to avoid having to mirror this exact structure in my data classes.

```kotlin
// I only want this data class
@Serializable
@SerialName("typeName") // Don't know if I actually need this one
data class TypeName(val prop1: String, val prop2: String, […])

// NOT WHAT I WANT
@Serializable
data class TypeNameWrapper(val typeName: TypeName)
```

### Solution 1

The code above would be my first solution to my problem. I'm writing a library for this API, so I could even hide away the `TypeNameWrapper` by making it `internal` and only return the _"inner"_ class from my libraries methods. But I don't quite like to allocate those extra objects just for deserialization and throwing them away immediately after.

### Solution 2

The other solution I came up with is using two custom serializers.

```kotlin
@OptIn(ExperimentalSerializationApi::class)
object TypeNameSerializer : KSerializer<TypeName> {
  override val descriptor: SerialDescriptor =
    buildClassSerialDescriptor("models.TypeName") {
      element("typeName", InnerTypeNameSerializer.descriptor)
    }

  override fun deserialize(decoder: Decoder): TypeName = 
    decoder.decodeStructure(descriptor) {
      lateinit var typeName: TypeName
      if (decodeSequentially()) {
        typeName = decodeSerializableElement(descriptor, 0, InnerTypeNameSerializer)
      } else while (true) {
        when (val index = decodeElementIndex(descriptor)) {
          0 -> typeName = decodeSerializableElement(descriptor, 0, InnerTypeNameSerializer)
          CompositeDecoder.DECODE_DONE -> break
          else -> error("Unexpected index: $index")
        }
      }

      typeName
    }

  override fun serialize(encoder: Encoder, value: TypeName) =
    encoder.encodeStructure(descriptor) {
      encodeSerializableElement(descriptor, 0, InnerTypeNameSerializer, value)
    }
}

@OptIn(ExperimentalSerializationApi::class)
object InnerTypeNameSerializer : KSerializer<TypeName> {
  override val descriptor: SerialDescriptor =
    buildClassSerialDescriptor("models.InnerTypeName") {
      element<String>("prop1")
      element<String>("prop2")
      // […]
    }

  override fun deserialize(decoder: Decoder): TypeName =
    decoder.decodeStructure(descriptor) {
      lateinit var prop1: String
      lateinit var prop2: String
      // […]
      if (decodeSequentially()) {
        prop1 = decodeStringElement(descriptor, 0)
        prop2 = decodeStringElement(descriptor, 1)
        // […]
      } else while (true) {
        when (val index = decodeElementIndex(descriptor)) {
          0 -> prop1 = decodeStringElement(descriptor, 0)
          1 -> prop2 = decodeStringElement(descriptor, 1)
          // […]
          CompositeDecoder.DECODE_DONE -> break
          else -> error("Unexpected index: $index")
        }
      }
      TypeName(prop1, prop2, […])
    }

  override fun serialize(encoder: Encoder, value: TypeName) =
    encoder.encodeStructure(descriptor) {
      encodeStringElement(descriptor, 0, value.prop1)
      encodeStringElement(descriptor, 1, value.prop2)
      // […]
    }
}
```

There's probably room for improvement (especially in `TypeNameSerializer.deserialize`), but still this of course is a lot over boilerplate. Especially when there are many data types and each with a bunch of properties. I'm not sure about performance compared to the first solution. As I need this for my library, I'm willing to write all that code, if the result is more in the interest of the library user.

### What to do?

Both solutions work. I think for now I'll move ahead with the second solution, until I get too annoyed writing all that code. But is there a better solution that I'm just not seeing? The main issue of course is not being able to rely on an auto-generated serializer, as I need to set a custom one to the data class.

Another solution, that I just thought up writing this, is to create a copy of the class definition (`TypeNameClone`) consisting of the exact same class body as `TypeName`, and using that one instead of `InnerTypeNameSerializer`. That would avoid all that boilerplate, but of course does not feel very elegant.

**Comment by pdvrieze** [comment]
What I like to do is to to use a private member (not inner) class that is the raw data for serialization and then have a custom serializer for the actual (public) type that delegates to the serializer for that type. It doesn't avoid the copy (escape analysis should help it to be optimized away).

**Comment by Bombo** [comment]
Thanks for the comment, but I'm afraid I can't quite grasp what you're saying. 😆

Also side note, my third "solution" wouldn't really work. The only thing I think I could reuse there would be the `descriptor`, as the `serialize` and `deserialize` methods would have incompatible signatures due to the actual types being different.

**Comment by JakeWharton** [comment]
> But I don't quite like to allocate those extra objects just for deserialization and throwing them away immediately after.

Deserialization already involves massive allocations such that one more instance of an enveloping object at the root will not even make a meaningful dent. The envelope object should occupy a mere 16 bytes in RAM.

I would choose this solution, especially if you're able to keep it as implementation detail. It's straightforward and simple.

**Comment by Bombo** [comment]
Thanks @JakeWharton. That makes sense to me.

I like that the other solution got me to dig a bit deeper into custom serializers, but in the end I didn't really look forward to all that boilerplate end perceived redundancy. The other solution is easy to understand, simple, and straight-forward. I just needed someone either point me towards what I'm missing or to smack me across the head and choose that path. :)

**Comment by pdvrieze** [comment]
@Bombo The idea with a (private) delegate is that you copy the "actual" object into the delegate for serialization. For deserialization you create the final object from the delegate. As such it is not full delegation, but involves some conversion (two constructor calls, one in each direction) that tends to be one line of code for each function. This approach changes the serialization complexity to simple conversion between two related types, it tends to be clear, compact and very hard to get wrong.
