### ISSUE TITLE
ProtoBuf is experimental, when will it be stable, is it safe to use in a large KMM project?

### ISSUE THREAD

**Issue by codingingBoy** [Kotlin/kotlinx.serialization#2544]

**Comment by pdvrieze** [comment]
You probably want an official answer as well, but my one is: it depends. The experimental is more that there are limitations to the support of certain Kotlin features. In theory there could also be future changes in how the format maps to protobuf, but I expect that those will be enabled behind configuration options. As such, if you want to use protobuf to communicate between two Kotlin programs (client/server) it should be fine. If you want to use it for permanent storage maybe less.

**Comment by codingingBoy** [comment]
> You probably want an official answer as well, but my one is: it depends. The experimental is more that there are limitations to the support of certain Kotlin features. In theory there could also be future changes in how the format maps to protobuf, but I expect that those will be enabled behind configuration options. As such, if you want to use protobuf to communicate between two Kotlin programs (client/server) it should be fine. If you want to use it for permanent storage maybe less.

Thasks for answer, I also want's to know is there any expected time for this function to be stable?

**Comment by xiaozhikang0916** [comment]
I also have a question may be related.
Can I expect that serialization.ProtoBuf will support full specific of Protocol Buffer 2/3, e.g. [Reserving unknown fields](https://protobuf.dev/programming-guides/proto2/#unknowns), [parsing `any` message](https://protobuf.dev/programming-guides/proto2/#any). Or it is just a tool to encode kotlin class to binary in protobuf format?

For context, our groups are using proto3 syntex to define RPC methods and messages, and we are migrating from Java class generated by protoc to kotlin data class.

**Comment by sandwwraith** [comment]
It is marked as 'experimental' mainly because it is not feature-complete (e.g. lack of `oneof` support), and it is not a top-priority project. Therefore, there are no particular time commitments for adding new features.
However, it also means that there are no big API changes expected (even if the features would be added), so it is safe to use it in your projects, given that you are able to sync the dependency version properly.
