### ISSUE TITLE
Kotlinx serialization ignores unknown enum

### ISSUE THREAD

**Issue by huthe98** [Kotlin/kotlinx.serialization#2554]
Kotlinx serialization ignores unknown enums, 
val services: kotlin.collections.List<@Contextual ServiceGeneratedDto>? 

```
Failure(io.ktor.serialization.JsonConvertException: .ServiceGeneratedDto does not contain element with name 'Cars' at path $[1].services[0])
```

**Comment by sandwwraith** [comment]
Take a look here: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#coercing-input-values

**Comment by valeriyo** [comment]
"unknown values for enums" -- what does it mean? literally enum field called "unknown" or something else?

**Comment by sandwwraith** [comment]
@valeriyo Values that are not declared in the enum class in Kotlin. See example in the mentioned section.
