### ISSUE TITLE
Support "Configuration on Demand" when projects are configured without buildscripts.

### ISSUE THREAD

**Issue by mgroth0** [Kotlin/kotlinx.serialization#2557]
**What is your use-case and why do you need this feature?**

I have a large project with many subprojects. It is to chaotic for each module to have its own buildscript, so I place a json file in each module telling gradle how to configure it. At configuration time, I use `allProjects` in the root project (which I plan to move to `gradle.allProjects` in the settings script if possible), and for each project I read the json file located inside its project folder and configure accordingly.

According to [the docs](https://docs.gradle.org/current/userguide/multi_project_configuration_and_execution.html#sec:configuration_on_demand) "Configuration on Demand" works by selectively enabling or disabling the execution of buildscript files. So aparantly this will not work for me, since I do not use buildscripts.

**Describe the solution you'd like**

Provide support for projects that configure subprojects without buildscripts. If "Configure on Demand" can disable the execution of a buildscript for the projects that it determines are not needed, then with a little bit more flexibility even gradle users like myself who don't use buildscripts could leverage the results of the calculated list of required projects in order to benefit from the advantages of decoupled projects.

In the `settings.gradle.kts` DSL, we can do the following:

```kotlin
gradle.allprojects {
    val cfg = Json.decodeFromString<ProjectConfig>(
        projectDir.resolve("cfg.json").readText()
    )
    configureProject(cfg)
}
```

This is a simplified representation of how my project works. Here `ProjectConfig` is a custom data class representing the basic logic for how I can have individual subprojects with different configurations without needing a single buildscript.

What I am proposing is something such as this:

```kotlin
gradle.allRequiredProjects {
    val cfg = Json.decodeFromString<ProjectConfig>(
        projectDir.resolve("cfg.json").readText()
    )
    configureProject(cfg)
}
```

Note the only difference is using a new proposed method `allRequiredProjects` instead of `allprojects`. 

My understanding is that one of the core features of "Configure On Demand" is that Gradle automatically determines which projects are neccesarry based on the tasks that the user asked gradle to execute. Using this filtered list of projects, it determines which buildscripts to execute.

I propose something like `allRequiredProjects` as a way for the gradle user to be able to leverage the results of the calculation of which projects are required. It would work in all ways the same as `allprojects`, except that the only projects that come through the lambda will be ones that were marked as required, and would be the same list of projects that would have their buildscripts executed if they had them (including the root project).

**Comment by pdvrieze** [comment]
You need to file this feature request with gradle, not with kotlinx.serialization as you are asking for a gradle feature (that you want to use in conjunction with kotlinx.serialization).
