### ISSUE TITLE
How do I ignore serializer when a Java class such as MutableLiveData is a member attribute of a serializable class

### ISSUE THREAD

**Issue by SirGong** [Kotlin/kotlinx.serialization#2559]
**I don't want filed favState  serizlized or decode**

```
@Serializable
data class SeriesInfo(
    var heat: Long = 0
){
    //This compilation does not pass
    var favState = MutableLiveData<Boolean>（）
}
```

**Comment by lukellmann** [comment]
Use the [`@Transient`](https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-core/kotlinx.serialization/-transient/) annotation on that property.

**Comment by sandwwraith** [comment]
For reference: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/basic-serialization.md#transient-properties
