### ISSUE TITLE
Change enum serialization/deserialization behavior for Enum

### ISSUE THREAD

**Issue by inemtsev** [Kotlin/kotlinx.serialization#2563]
Hi team,

Sometimes when consuming a backend written in a different tech stack, the Enums are serialized at Integers. Kotlinx currently does not understand this and custom serializer is needed. Sometimes the contract is generated and there are many such enums, this doesn't scale very well. It would be great if there was an option like `Json { enumAsInteger = true }` that would change this behavior.

Best Regards,
Ilya

**Comment by sandwwraith** [comment]
I do not think it is a good idea to have this option. If you rename the enum entry, you quickly get a deserialization error, and you can make a fallback for the old name with `@JsonNames`. If you reorder enum entries, you may not know if this option is enabled and silently get an incorrect result without an option to make behavior backward-compatible. Therefore, such a strategy of enum serialization should be reflected in class definition, not format settings. 

I think it is relatively easy to generalize custom serializer. You define once `EnumSerializer<E: Enum<E>(val entries List<E>: KSerializer<E> {}` with all the logic, and then for each enum, just generate `object MyEnumSerializer: EnumSerializer(MyEnum.entries)` without an additional body.

**Comment by inemtsev** [comment]
> I do not think it is a good idea to have this option. If you rename the enum entry, you quickly get a deserialization error, and you can make a fallback for the old name with `@JsonNames`. If you reorder enum entries, you may not know if this option is enabled and silently get an incorrect result without an option to make behavior backward-compatible. Therefore, such a strategy of enum serialization should be reflected in class definition, not format settings.
> 
> I think it is relatively easy to generalize custom serializer. You define once `EnumSerializer<E: Enum<E>(val entries List<E>: KSerializer<E> {}` with all the logic, and then for each enum, just generate `object MyEnumSerializer: EnumSerializer(MyEnum.entries)` without an additional body.

Half agree, but a bit more challenging when you generate your client's based on swagger spec.

**Comment by inemtsev** [comment]
> From where are the integer values sourced? The implicit ordinal, or explicitly using some other mechanism?

Our API written in Scala provides swagger spec with these values.

**Comment by JakeWharton** [comment]
I was asking from where they are sourced in the Kotlin for use by the serializer.
