### ISSUE TITLE
Fatal Exception: java.util.ServiceConfigurationError kotlinx.coroutines.android.AndroidExceptionPreHandler cannot be stored in an array of type qh.b0[] expo.modules.kotlin.AppContext.<init>   Caused by java.lang.ArrayStoreException 

### ISSUE THREAD

**Issue by Karthika-Kishore** [Kotlin/kotlinx.serialization#2579]
**Describe the bug**

**To Reproduce**
Attach a code snippet or test data if possible.

**Expected behavior**

**Environment**
 - Kotlin version: [e.g. 1.3.30]
 - Library version: [e.g. 0.11.0]
 - Kotlin platforms: [e.g. JVM, JS, Native or their combinations]
 - Gradle version: [e.g. 4.10]
 - IDE version (if bug is related to the IDE) [e.g. IntellijIDEA 2019.1, Android Studio 3.4]
 - Other relevant context [e.g. OS version, JRE version, ... ]

**Comment by Karthika-Kishore** [comment]
buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
        reactNativeVersion = "0.68.0"
        kotlin_version = '1.5.1'

**Comment by sandwwraith** [comment]
It's not related to kotlinx.serialization. Looks like a bug in your ` expo.modules.kotlin.AppContext` constructor.
