### ISSUE TITLE
Protobuf Unknown Fields 

### ISSUE THREAD

**Issue by tamnguyenhuy** [Kotlin/kotlinx.serialization#2582]
Hi, I have a decoding and encoding protobuf unit test scenario.

here is the proto data: e802058203061001200128018a0500
have tags: 45, 48, and 81.
```
@Serializable
class TestProtoBuf {
 @ProtoNumber(number = 45)
 val id: UInt? = null
 @ProtoNumber(number = 48)
 val otherValue: OtherValue? 
}
```

```
@Test
fun testProto() {
  val data = "e802058203061001200128018a0500"
  val result = ProtoBuf.decodeFromHexString<TestProtoBuf>(data)
  val dataAfterSerialize = ProtoBuf.encodeToHexString(result)

  assertEquals(expected = data, actual = dataAfterSerialize)
}
```
When I decode with “e802058203061001200128018a0500" and encode back to a string.
The dataAfterSerialize equals “e80205820306100120012801”, can see “8a0500" is removed.

So how can I keep unknown field data in dataAfterSerialize?

**Comment by tamnguyenhuy** [comment]
Prefer to https://github.com/protobuf-net/protobuf-net/blob/main/assorted/BasicHttp/MyDtoLayer/MySchema.cs#L41-L42
``` csharp
private global::ProtoBuf.IExtension extensionObject;
global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
{ return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
```
The extensionObject variable will be saved in the case of unknown fields. I'm wondering how to implement it in Kotlin.
Thanks!

**Comment by sandwwraith** [comment]
Hi, we do not support this functionality at the moment. See also #398.

You can try Wire-Kotlin (https://square.github.io/wire/#wire-kotlin) instead, although it uses completely different approach.
