### ISSUE TITLE
Provide an option for custom serializers to receive types instead of serializers

### ISSUE THREAD

**Issue by Gaming32** [Kotlin/kotlinx.serialization#2584]
**What is your use-case and why do you need this feature?**

I have a situation where I need the type arguments of an object to construct my custom serializer, but those type arguments will not be serializable themselves.

**Describe the solution you'd like**

I would like the serializer constructor to be able to accept `KClass` or `KType` parameters in addition to `KSerializer` parameters.

For example, say I have a class (this is a toy example, my actual situation is a bit more complex):

```kt
@Serializable(MyDataSerializer::class)
data class MyData<K, V>(val key: String, val value: V) {
    fun uncheckedCast() = value as K
}
```

I would want to define a serializer for this class that takes in the `K` type parameter as a `KClass` or `KType`. Notice how I can still receive `V` as a `KSerializer`, however.

```kt
class MyDataSerializer<K, V>(
    private val kType: KClass<K>, 
    private val vSerializer: KSerializer<V>
) : KSerializer<MyData<K, V>> {
    override val descriptor = SerialDescriptor("MyData", vSerializer.descriptor)

    override fun serialize(encoder: Encoder, value: MyData<K, V>) =
        encoder.encodeSerializableValue(vSerializer, value.value)

    override fun deserialize(decoder: Decoder) =
        MyData(getKeyFromClass(kType), decoder.decodeSerializableValue(vSerializer))
}
```

This would potentially require more complexity in the compiler plugin (this is a compiler plugin feature request, primarily) to locate a constructor that takes in an appropriate number of parameters, and its descriptor (since it could now take any mix of parameter types, not just `"LKSerializer;".repeat(argCount)`).

**Comment by xiaozhikang0916** [comment]
Is it something like #2555 ?

**Comment by Gaming32** [comment]
That issue deals with polymorphic serialization, abstract classes, and type inference. This issue isn't about any of those.

**Comment by sandwwraith** [comment]
We don't have plans to change existing custom serializers conventions, as it seems that the number of use cases for that is very limited; besides. given that the `K` can be generic itself, `KClass` may not be enough to fully support it.
