### ISSUE TITLE
IllegalAccessError when decoding uses a default value from a private companion object

### ISSUE THREAD

**Issue by marcosalis** [Kotlin/kotlinx.serialization#2595]
**Describe the bug**
This is a bit of a mistery, to be honest. I get an unjustifiable `IllegalAccessError` on an Android project at runtime, when decoding a JSON string from an object with a default value which is placed in a `private companion object`. No compilation errors nor warnings obviously.
I was able to reproduce the issue *occasionally* (the test is flaky) with JUnit4 test.

This was also reproduced on different MacOS machines (Silicon) and on our C.I. builds (Bitrise).

**To Reproduce**
```
    @Serializable
    data class WithPrivateCompanionDefaultValue(private val myString: String = DEFAULT) {
        private companion object {
            // if I move the private to the const, the test passes
            const val DEFAULT = "private_default"
        }
        fun getValue() = string
    }
```

```
    @Test(expected = IllegalAccessError::class)
    fun `GIVEN a model with a private companion object WHEN decoding a string field with kotlinX THEN exception is thrown`() {
        json.decodeFromString<WithPrivateCompanionDefaultValue>("{}") // myString should be set to `private_default`
    }
```

The full exception is the following:
```
java.lang.IllegalAccessError: class {package omitted}.JsonSerializationPlaygroundTest tried to access private field {package omitted}.WithPrivateCompanionDefaultValue.Companion ({package omitted}.JsonSerializationPlaygroundTest and {package omitted}.WithPrivateCompanionDefaultValue are in unnamed module of loader 'app')
	at {package omitted}.JsonSerializationPlaygroundTest.GIVEN a model with a private companion object WHEN decoding a string field with kotlinX THEN exception thrown(JsonSerializationPlaygroundTest.kt:191)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
```

**Expected behavior**
No crash!

**Environment**
 - Kotlin version: 1.9.22
 - Library version: "1.6.3"
 - Kotlin platforms: Android
 - Gradle version: 8.4
 - IDE version: Android Studio Iguana (2023.2.1) 
 - Other relevant context: default Studio JVM (OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874))

**Comment by sandwwraith** [comment]
Serialization plugin adds `Companion.serializer()` function to every `@Serializable` class. This function is looked up when we need to do a lookup for serializer with reflection (e.g., in `serializer(typeOf< WithPrivateCompanionDefaultValue>())` case). So, if the companion is private, modern JVMs do not allow it to be touched with reflection.
I'm not sure if there is any possibility of working around this except by making the companion non-private.
Perhaps we need to add a special diagnostic to the compiler plugin to warn about private companions in serializable classes.

**Comment by sandwwraith** [comment]
I've filed https://youtrack.jetbrains.com/issue/KT-66462 for that.

**Comment by marcosalis** [comment]
Thank you for the actionable response @sandwwraith, it makes sense.
To be honest, I wasn't aware that the serializers would be using reflection in this case.
The warning is much better than the runtime failure obviously 👌
