### ISSUE TITLE
docs: Provide the gradle plugin ID, not only the DSL syntax.

### ISSUE THREAD

**Issue by iseki0** [Kotlin/kotlinx.serialization#2600]
**What is your use-case and why do you need this feature?**
Sometimes when I use gradle in a way that cannot use `plugins{}` syntax directly. I need the plugin id and the plugin maven coordinate.
Such as in [version catalog](https://docs.gradle.org/current/userguide/platforms.html#sec:sharing-catalogs) and [precompiled script plugin](https://docs.gradle.org/current/userguide/custom_plugins.html#sec:precompiled_plugins).
If you can't ensure the syntax `kotlin("plugin.serialization")` is suitable for any cases, you'd better provide the plugin id and maven coordinate in the docs also.

**Comment by sandwwraith** [comment]
Groovy variant mentions `id 'org.jetbrains.kotlin.plugin.serialization'`. Is that enough?
