### ISSUE TITLE
Nested classes in ProtoBuf produce empty array for native release binary

### ISSUE THREAD

**Issue by whyoleg** [Kotlin/kotlinx.serialization#2608]
**Describe the bug**

Nested classes in ProtoBuf produce empty array for native release binary.
No such issue with Cbor or with any other target and Native debug binary. (all cases are provided in repository with reproducer)

**To Reproduce**
```kotlin

@Serializable
data class OuterClass(val data: InnerClass)

@Serializable
data class InnerClass(val data: String)

@OptIn(ExperimentalSerializationApi::class, ExperimentalStdlibApi::class)
class SerializationTest {
    @Test
    fun testProtobufNested() {
        val model = OuterClass(InnerClass("something"))

        val data = ProtoBuf.encodeToByteArray(OuterClass.serializer(), model)
        // `data` is an empty array on Native in release mode
        assertEquals("0a0b0a09736f6d657468696e67", data.toHexString()) 
    }
}
```
Repository with reproducer: https://github.com/whyoleg/kx-serialization-protobuf-reproducer
To reproduce: `./gradlew macosArm64ReleaseTest` or `[TARGET_NAME]ReleaseTest` for other targets, or just `check` to run all tests (to compare behaviour)

**Expected behavior**

Correct serialised value is returned independent to the target or debug/release mode.

**Environment**
 - Kotlin version: 1.9.23 (same for 2.0.0-Beta5)
 - Library version: 1.6.3
 - Kotlin platforms: Native

Note: I can create the same issue in Kotlin YT, as most likely the issue is there, but thought it would be better to create it here to keep track and may be introduce some kind of tests in repository.

**Comment by sandwwraith** [comment]
Thanks for report. It happens for me for both `linuxX64ReleaseTest` on Linux machine and `macosArm64ReleaseTest` on Apple Silicon machine. Looks like the Native issue though.

**Comment by whyoleg** [comment]
just in case: does it make sense additionally run tests in `RELEASE` mode to the library (and possibly other `kotlinx.*` libraries), to be proactive with such bugs?
If you think it could be useful, I'm ready to provide PR.

**Comment by sandwwraith** [comment]
Yes, it makes sense. I'll ask Native team additionally of the best way to do so. We are now refactoring our build scripts (#2654), so you'll have to wait with your PR a little bit :)
