### ISSUE TITLE
Not possible to specify serializer for top level class and jsontransformingserializer

### ISSUE THREAD

**Issue by strindberg** [Kotlin/kotlinx.serialization#2609]
**Describe the bug**
We have a large number of classes implementing a class hierarchy with composition instead of traditional inheritance, and we therefore have many instances of an inner class being an attribute of an outer class. We want to create a json serialization where the attributes of the wrapped inner class are serialized as attributes of the outer class, but without writing a specific serializer for each class.

There seems to be no way of using `JsonTransformingSerializer`and at the same time specify a specific serializer for a top level class.

**To Reproduce**
We have the following example class (our actual classes are of course much larger):

```kotlin
@Serializable
data class Wrapper(val name: String, val body: Body)

@Serializable
data class Body(val instruction: String)
```

We have written a generic "un-wrapping" serializer that puts all the attributes of the wrapped object into the parent level:

``` kotlin
open class UnwrappingJsonSerializer<T : Any>(
    serializer: KSerializer<T>,
    private val childName: String,
) : JsonTransformingSerializer<T>(serializer) {

    override fun transformDeserialize(element: JsonElement): JsonElement {
        val content = element.jsonObject.toMutableMap().apply {
            put(childName, JsonObject(element.jsonObject.toMap()))
        }
        return JsonObject(content)
    }

    override fun transformSerialize(element: JsonElement): JsonElement {
        val content = mutableMapOf<String, JsonElement>()
        element.jsonObject.entries.forEach { (key, value) ->
            if (key == childName) {
                content.putAll(value.jsonObject)
            } else {
                content[key] = value
            }
        }
        return JsonObject(content)
    }
}
```

Then we specify a particular serializer object for the `Wrapper`class:
```kotlin
object WrapperSerializer : UnwrappingJsonSerializer<Wrapper>(Wrapper.serializer(), "body")
```

We can find no way of specifying that `WrapperSerializer`should be used for serializing `Wrapper` instances.

It works when specifying the serializer expicitly: 
```kotlin
val wrapper = Wrapper(...)
json.encodeToString(WrapperSerializer, wrapper)
```
but we want to specify `WrapperSerializer`as the default serializer for `Wrapper`without having to specify it explicitly when serializing:
```kotlin
val wrapper = Wrapper(...)
json.encodeToString(wrapper) // Does not work, the original serializer is used
```

This does (obviously) not work ,since it specifies a circular dependency:
```kotlin
@Serializable(with=WrapperSerializer::class)
data class Wrapper(val name: String, val body: Body)
```

Specifying a type alias as is hinted to in the documentation does not change the serialization (the original non-unwrapping serializer is till used):
```kotlin
typealias UnwrappedWrapper = @Serializable(WrapperSerializer::class) Wrapper

val data = UnwrappedWrapper("name 1", Body("instruction 1"))

val content = json.encodeToString(data) // Still serializes with the inner class wrapped
```

**Environment**
 - Kotlin version: 1.9.22
 - Library version: 1.6.3
 - Kotlin platforms: JVM
 - Gradle version: 8.6

**Comment by sandwwraith** [comment]
This is a known problem; see https://github.com/Kotlin/kotlinx.serialization/issues/941 and https://github.com/Kotlin/kotlinx.serialization/issues/1169. We expect that feature solving this issue will land in Kotlin 2.0 or Kotlin 2.0.20. In the meanwhile, typealias in conjunction with `json.encodeToString(WrapperSerializer, wrapper)` is a good and recommended workaround.

**Comment by pdvrieze** [comment]
@strindberg Assuming that your attributes/properties actually work correctly I would suggest the following:
- A custom serializer.
- The descriptor is a combination of the outer and inner class members
- in `encode` and `decode` you use a delegating (composite)encoder/decoder. Both these delegating encoders/decoders would intercept the beginStructure and endStructure calls and would renumber the property indices (to translate between the outer/inner numbers) when forwarding to the actual decoder/encoder (json in your case)
