### ISSUE TITLE
 TypeError: this.descriptor.addElement_ivxn3r$ is not a function

### ISSUE THREAD

**Issue by Binghammer** [Kotlin/kotlinx.serialization#261]
I am working on writing object to Firebase. Writing the object as-is I get an unusual error _Argument "data" is not a valid Document._ So I have tried to utilize serialization to hopefully serialize my objects appropriately. 
This is my test:

[SampleTest.kt](https://bitbucket.org/chadbingham/kotlinx-serialization-issue/src/master/js-module/src/test/kotlin/sample/SampleTests.kt)

```
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JSON


@Serializable
class FooBar(val s: String, val i: Int, val b: Boolean)

class SerializationTest {
    @Test
    fun writeObject() {
        val fooBar = FooBar("we didnt start the fire", 1988, true)
        console.dir(fooBar)
        val serialized = JSON.indented.stringify(FooBar.serializer(), fooBar)  <-- CRASH
        console.error("serialized: $serialized")
        
        /* writing to firebase removed for brevity */

    }
}
```

Test output: 
```  
1) sample
       SerializationTest
         writeObject:
     TypeError: this.descriptor.addElement_ivxn3r$ is not a function
      at new FooBar$$serializer (functions/src/test/index_test.js:38:21)
      at FooBar$$serializer_getInstance (functions/src/test/index_test.js:98:7)
      at FooBar$Companion.serializer (functions/src/test/index_test.js:22:12)
      at SerializationTest.writeObject (functions/src/test/index_test.js:128:97)
      at Context.<anonymous> (functions/src/test/index_test.js:149:42)
```

Sample project: 
https://bitbucket.org/chadbingham/kotlinx-serialization-issue/src/master/

**Comment by Binghammer** [comment]
It turns out the problem was with my build.gradle and the fact I had a the serialization dependency in my package.json file. Following this fixed it for me https://github.com/Kotlin/kotlinx.serialization/issues/106

**Comment by sandwwraith** [comment]
So this can be closed?

**Comment by Binghammer** [comment]
yes, this can be closed
