### ISSUE TITLE
Expose tagged encoder/decoder as public API

### ISSUE THREAD

**Issue by rnett** [Kotlin/kotlinx.serialization#2610]
**What is your use-case and why do you need this feature?**

I'm working on a custom format (that flattens everything) and being able to extend `TaggedEncoder/`TaggedDecoder` would be hugely helpful.  However, they are marked as internal serialization APIs.  Despite this, they seem fairly straightforward, there's not anything hacky going on that I can see.  If they were just kept internal due to inertia, it would be great to make them public.

**Describe the solution you'd like**
Make `TaggedEncoder` and `TaggedDecoder` public API. Might as well do the named value ones, too.

**Comment by sandwwraith** [comment]
The main reason they're internal for now is that they have never been properly designed; instead, code patches appeared 'here and there' to meet various needs, and as a result, they do not have a solid mental model nor proper invariants. See the discussion here, for example: https://github.com/Kotlin/kotlinx.serialization/issues/538#issuecomment-522931624. So it is tricky to properly document and explain various nuances connected with this API (e.g., the need for a separate `PrimitiveDecoder` implementation that correctly handles empty stack).
We also want to keep this approach in case we need to fix a bug that may be specific for Json but related to the internal decoder state. So, the behavior of these classes may change, which is inappropriate for stable API. If you're sure this API works well for you, you can copy it over to your implementation. By doing so, you will be able to maintain it without unexpected changes in upstream, and you'll be able to make minor tweaks if necessary, for example, making tag stack a primitive array (as in ProtobufTaggedBase) or exposing it further.

**Comment by rnett** [comment]
Makes sense, that's pretty much what I've done.
