### ISSUE TITLE
KotlinxSerializationPlugin failing with kapt.use.k2=true

### ISSUE THREAD

**Issue by aftabahmadTW** [Kotlin/kotlinx.serialization#2615]
**Describe the bug**
When running the codebase with Kotlin 2.0 and `kapt.use.k2=true` I get the following error.

```
[kapt] An exception occurred: org.jetbrains.kotlin.utils.exceptions.KotlinIllegalArgumentExceptionWithAttachments: Error while resolving org.jetbrains.kotlin.fir.declarations.impl.FirSimpleFunctionImpl
from STATUS to EXPECT_ACTUAL_MATCHING
current declaration phase STATUS
origin: Plugin[KotlinxSerializationPlugin]
session: class org.jetbrains.kotlin.analysis.low.level.api.fir.sessions.LLFirSourcesSession
module data: class org.jetbrains.kotlin.analysis.low.level.api.fir.project.structure.LLFirModuleData
KtModule: class org.jetbrains.kotlin.analysis.project.structure.impl.KtSourceModuleImpl
platform: JVM (1.8)

Caused by: java.lang.IllegalStateException: Expected body resolve phase for origin Plugin[KotlinxSerializationPlugin] but found ResolvedTo(STATUS)
```

**Expected behavior**
Not sure if this is something more generic or specific to our codebase.

**Environment**
 - Kotlin version: 2.0 Beta 5
 - Library version: 1.6.3
 - Kotlin platforms: Android and JVM
 - Gradle version: 8.6

**Comment by sandwwraith** [comment]
Do you have a project with a reproducer, by any chance? Or at least declarations of `@Serializable` classes

**Comment by aftabahmadTW** [comment]
I'll try and create a reproducer

**Comment by aftabahmadTW** [comment]
Hi @sandwwraith sorry for the delay on this. I've created a reproducer but found the issue. It's with an incorrect usage of `@Serializer(forClass = ...)`

**Comment by sandwwraith** [comment]
@aftabahmadTW No problem!
