### ISSUE TITLE
How to get rid of nullability?

### ISSUE THREAD

**Issue by Fleshgrinder** [Kotlin/kotlinx.serialization#2619]
I'm writing Kafka serdes where `null` has a very special meaning (tombstones). I do want to keep the nullability information for the type parameters, but I don't want the serializer to support `null`. The problem is that it's not possible to unwrap a serializer that has been wrapped with nullability. As such I'm forced to check every result the serializer or deserializer gives me to ensure it doesn't return `null`, and fail at runtime. Here's a deserializer example:

```kotlin
@OptIn(ExperimentalSerializationApi::class)
public class JsonDeserializer<T>(
    private val strategy: DeserializationStrategy<T & Any>,
    json: Json? = null,
) : Deserializer<T> {
    private val json = json ?: JSON

    init {
        // We cannot do this, because of the reified factory method.
        // require(!strategy.descriptor.isNullable)
    }

    override fun deserialize(topic: String?, data: ByteArray?): T? {
        if (data == null) {
            return null
        }
        val result = try {
            json.decodeFromStream(strategy, ByteArrayInputStream(data))
        } catch (cause: kotlinx.serialization.SerializationException) {
            throw SerializationException("Kotlinx JSON deserialization failed", cause)
        }
        @Suppress("SENSELESS_COMPARISON")
        if (result == null) {
            throw SerializationException(
                "Kotlinx JSON deserialization returned null which is forbidden as it's not " +
                    "possible anymore to tell the difference between a tombstone and a datum " +
                    "that is null, the actual error is with the producer of the data, since it " +
                    "should never have produced a serialized literal JSON null value in the " +
                    "first place"
            )
        }
        return result
    }
}

public inline fun <reified T> JsonDeserializer(json: Json? = null): JsonDeserializer<T> =
    JsonDeserializer(serializer(), json)
```

Users who use the constructor with a manually created `strategy` get a serializer with no nullability, but those who use the reified factory method always get a serializer that supports `null`. The `T & Any` on the `DeserializationStrategy` is ignored entirely by the `serializer()` call.

```kotlin
JsonDeserializer<String>(serializer())           // 🟢 all good
JsonDeserializer<String?>(serializer<String>())  // 🟡 ok but inconvenient
JsonDeserializer<String>()                       // 🟢 all good
JsonDeserializer<String?()                       // 🔴 not good
```

Adding an `Any` bound to `T` would obviously work, but it would mean that it's not possible anymore to automatically create serdes for topics where the key and/or value is actually nullable (supports tombstones).

I haven't looked into why it's possible that I can pass a `KSerializer<T>` to a `DeserializationStrategy<T & Any>` and whether this is actually an issue of this library or a Kotlin issue. But, it's strange…

I have no idea on how to work around this. Obviously I could use reflection and unwrap the inner serializer from the `NullableSerializer`, but that wouldn't help me with custom serializers that might be created from the `serializer()` factory method where `isNullable` is `true` but no inner serializer exists that could be unwrapped.

I'm not sure if it's even possible to do anything about this here, and I would have used the GitHub discussion feature if available. Anyway, looking for any help, ideas, and insights.

**Comment by sandwwraith** [comment]
Definitely non-nullable types `T & Any` are aimed mainly for Java interop (https://kotlinlang.org/docs/generics.html#definitely-non-nullable-types). If you want to declare something as non-nullable in Kotlin, simply use `: Any` upper bound: `public class JsonDeserializer<T: Any> / public inline fun <reified T: Any> JsonDeserializer`. By doing so, the compiler will verify that you cannot pass `String?` there.

Regarding nullability serializers — you're right that 
> wouldn't help me with custom serializers that might be created from the serializer() factory method where isNullable is true but no inner serializer exists that could be unwrapped

So even if we eventually provide `.unwrap` function for NullableSerializer, it would be still unclear what to do with custom serializers. Perhaps wrapping them in serializer similar to yours (one that rejecting `null`s) will be the only way.

Hope that answers your question.
