### ISSUE TITLE
JsonDecodingException: Unexpected JSON token at offset 23: Expected string literal but 'null' literal was found at path: $.result.

### ISSUE THREAD

**Issue by Scorcher100** [Kotlin/kotlinx.serialization#2620]
I dont know how to describe but this is what happens when I refresh my list on aniyomi. I suddenly cant refresh new episodes of any kind of anime i have saved
![Screenshot_2024-03-28-19-36-42-733_xyz jmir tachiyomi mi debug](https://github.com/Kotlin/kotlinx.serialization/assets/159228365/713dab9d-3575-43ba-a7c4-afa9a75da50d)

**To Reproduce**
I don't know how to reproduce this error since it was also sudden thing to happen and I just refresh it normally and this problem occurred.

**Expected behavior**

**Environment**
 - Kotlin version: [e.g. 1.3.30]
 - Library version: [e.g. 0.11.0]
 - Kotlin platforms: [e.g. JVM, JS, Native or their combinations]
 - Gradle version: [e.g. 4.10]
 - IDE version (if bug is related to the IDE) [e.g. IntellijIDEA 2019.1, Android Studio 3.4]
 - Other relevant context [e.g. OS version, JRE version, ... ]

**Comment by sandwwraith** [comment]
Given that the input contains `"result":null`, the error thrown here is correct. It seems that the application was not designed to handle a case when the server returns 403 status without a result, or it sends an incorrect request to a server. Please report this issue to an application developer.
