### ISSUE TITLE
Stabilize explicitNulls in Json

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.serialization#2636]
It is here from 1.3, we get the overall positive feedback and there is not many reasons to keep it experimental any longer

**Comment by sandwwraith** [comment]
Apparently it depends on #2586 now, so it makes sense to think about them together

**Comment by sandwwraith** [comment]
Other issues that may be related to `explicitNulls`: #2422, #1542. But that seem to be all of them, there isn't a lot going with this feature in the tracker.
