### ISSUE TITLE
Protobuf Generator Build Task

### ISSUE THREAD

**Issue by Pseudow** [Kotlin/kotlinx.serialization#2645]
**What is your use-case and why do you need this feature?**
To make my application more easily scalable it would be interesting to make the data classes used by my api generated into proto files. In order to make other applications in other languages take those proto files to create classes.

**Describe the solution you'd like**
A new gradle task to customize the generation of proto files.

**Comment by Pseudow** [comment]
If it is not possible, how is the serializer module attached to serializable classes? In order to create a custom gradle task by myself.

**Comment by JakeWharton** [comment]
See https://github.com/Kotlin/kotlinx.serialization/blob/master/docs%2Fformats.md#protobuf-schema-generator-experimental

**Comment by Pseudow** [comment]
I think we misunderstood I am trying to create a gradle task that generates proto files and to manage that I have created a annotation processor but I can't access to my class serializers since it requires the class.

**Comment by JakeWharton** [comment]
They will not be available inside an annotation processor. They are only available at runtime. If you want to accomplish this with a task I would create a JavaExec task that inherits your runtime classpath as well as uses a main method to dump from the descriptors, as shown in my link.

**Comment by Pseudow** [comment]
The main method part is easy but how can I make java exec that inherits the classpath generated by this plugin?

**Comment by pdvrieze** [comment]
@Pseudow You are now deep into Gradle territory, but you need a configuration for the task, that configuration inherits/depends on the runtimeclasspath (or other configuration) as well as the classpath of the protobuf generation code. You can set the classpath of this configuration to be the classpath of the exec task.

**Comment by sandwwraith** [comment]
Yes, @pdvrieze is right. We do not provide any tasks out of the box, so you need to write a custom Gradle task (probably in your buildSrc directory), take your `@Serializable` classes, and apply a schema generator to them. 

Providing such a task may be a future point for improving the serialization gradle plugin, but we do not intend to have it now.
