### ISSUE TITLE
It is not possible to write custom serializer for simple objects like UUID into ByteArray to serailize it into ProtoBuf "bytes" field.

### ISSUE THREAD

**Issue by ComBatVision** [Kotlin/kotlinx.serialization#2666]
**Describe the bug**
It is not possible to write custom serializer for simple objects like UUID into ByteArray to serailize it into ProtoBuf "bytes" field.

An exepion occurs "java.lang.ClassCastException: kotlinx.uuid.UUID cannot be cast to byte[]"

It is due to ProtobufEncoding.kt has strange krunch for ByreArray desctiptor in method encodeSerializableValue:
```
override fun <T> encodeSerializableValue(serializer: SerializationStrategy<T>, value: T) = when {
        serializer is MapLikeSerializer<*, *, *, *> -> {
            serializeMap(serializer as SerializationStrategy<T>, value)
        }
        serializer.descriptor == ByteArraySerializer().descriptor -> serializeByteArray(value as ByteArray)
        else -> serializer.serialize(this, value)
    }
```

**To Reproduce**
Here is an example of custom UUID to ByteArray serializer for https://github.com/hfhbd/kotlinx-uuid
```
object UUIDByteArraySerializer : KSerializer<UUID> {
    private val serializer = ByteArraySerializer()
    override val descriptor: SerialDescriptor = serializer.descriptor

    override fun serialize(encoder: Encoder, value: UUID) {
        encoder.encodeSerializableValue(serializer, value.encodeToByteArray())
    }

    override fun deserialize(decoder: Decoder): UUID {
        return decoder.decodeSerializableValue(serializer).let { array ->
            if (array.size != 16) {
                throw SerializationException("UUID byte array should consist of 16 elements")
            }

            UUID(array)
        }
    }
}
```
**Expected behavior**
Expected behavior to have "bytes" field with proto number, length equals 16 and following 16 bytes to be serialized.
This data should be deserialized using Google Protobuf using:
`ByteString.toByteArray().let { array -> ByteBuffer.wrap(array).let { buf -> UUID(buf.long, buf.long) } } `
But instead an error UUID casting to ByteArray appears.

**Environment**
 - Kotlin version: 1.9.23
 - Library version: 1.6.3
 - Kotlin platforms: JVM
 - Gradle version: 8.5

**Comment by pdvrieze** [comment]
Serialnames must be unique within a serialization graph. Formats are allowed to cache information based on serialName, or use the serial name to special case handling bytes. This means that the line:
```
override val descriptor: SerialDescriptor = serializer.descriptor
```
is not valid. You need: `SerialDescriptor("SomeNewName", serializer)`
If you do that, it should work.

**Comment by ComBatVision** [comment]
Thanks.

It is definitely works.
`override val descriptor = SerialDescriptor("UUID", serializer.descriptor)`
Topic may be closed.

One additional question - is it possible to define serializer to produxe ByteArray in Protobuf and CBOR but produce String in Json and XML?
