### ISSUE TITLE
Deserialization of Generic optional field when value is omitted in Json still tries to instantiate an instance of the generic type

### ISSUE THREAD

**Issue by simplatek** [Kotlin/kotlinx.serialization#2672]
**Describe the bug**
I have a class which contains an optional generic property.  I have given it a default value of null, when the value is not present in the json, the serializer still attempts to deserialize the field and complians about missing fields.  Only workaround is to make all the fields on the optional property type also be optional and provide default values for those as well, which is not intended as the class itself is only optional within the Result<T> type and not all AuthResponse properties.  I set explicitNulls = false also in the Json config block.

**To Reproduce**
```

private val httpClient = HttpClient {
        install(ContentNegotiation) {
            json(Json {
                isLenient = true
                explicitNulls = false
                ignoreUnknownKeys = true
                useAlternativeNames = false
            })
        }

@Serializable
data class Result<T>(val errorCode: Int, val payload: T? = null)

@Serializable
data class AuthResponse(val sessionKey: String, val property1: String, val property2: String)

usage:

val apiResponse: Result<AuthResponse> = httpClient.post(url) {
            contentType(ContentType.Application.Json)
            setBody(AuthRequest(username, password)
        }.body()

json returned:
{
   "errorCode": 1001
}
```

**Expected behavior**

As you can see, the response json did not return a payload field as it is marked as optional, I would expect that the serializer would return a valid Result<AuthResponse> which only has the errorCode value set, the payload should still be null as there was no json to deserialize.  But instead I get an error saying:

Illegal input: Fields [property1, property2, sessionKey] are required for type with serial name 'domainObjects.authentication.AuthResponse', but they were missing at path: $.response

If I define AuthResponse as below it works, but these fields are not optional.  I would expect defining the payload: T? = null would be all that is required.

```

@Serializable
data class AuthResponse(val sessionKey: String? = null, val property1: String? = null, val property2: String? = null)
```

**Environment**

 - Kotlin version 1.9.23
 - Library version: 1.9.23
 - Kotlin platforms: Android, iOS

**Comment by xiaozhikang0916** [comment]
Deserializing this json string in unit test passed as expected, maybe an issue in ktor?

**Comment by sandwwraith** [comment]
Indeed. This test:

```kotlin
    @Serializable
    data class Result<T>(val errorCode: Int, val payload: T? = null)

    @Serializable
    data class AuthResponse(val sessionKey: String, val property1: String, val property2: String)

    val j = Json {
        isLenient = true
        explicitNulls = false
        ignoreUnknownKeys = true
        useAlternativeNames = false
    }

    @Test
    fun testAuthResponse() {
        val input = """{
   "errorCode": 1001
}"""
        println(j.decodeFromString<Result<AuthResponse>>(input))
    }
}
```

prints `Result(errorCode=1001, payload=null)` as expected. So this is likely Ktor's `post` or `body` problem. Check if they accept explicit serializer, passing `Result.serializer(AuthResponse.serializer())` may help. Or file an issue to Ktor.
