### ISSUE TITLE
generics type inline function call `serializer<T>()` fail in kotlin/native

### ISSUE THREAD

**Issue by Gargantua7** [Kotlin/kotlinx.serialization#2676]
**Describe the bug**
Here is the sample

```
class Greeting {
    private val platform = getPlatform()

    fun greet(): String {
        foo<@Serializable(with = ValueSerializer::class) Value>()
        return "Hello, ${platform.name}!"
    }
}

inline fun <reified T> foo() {
    serializer<T>()
}

class Value(val value: Int)

object ValueSerializer : KSerializer<Value> {
    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor(Value::class.qualifiedName.toString(), PrimitiveKind.INT)

    override fun deserialize(decoder: Decoder): Value {
        return Value(decoder.decodeInt())
    }

    override fun serialize(encoder: Encoder, value: Value) {
        encoder.encodeInt(value.value)
    }
}
```
and call it in swift 
```
Greeting().greet()
```
then crash
```
Uncaught Kotlin exception: kotlinx.serialization.SerializationException: Serializer for class 'Value' is not found.
Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.
To get enum serializer on Kotlin/Native, it should be annotated with @Serializable annotation.
To get interface serializer on Kotlin/Native, use PolymorphicSerializer() constructor function.

    at 0   Shared                              0x10a90a38e        kfun:kotlinx.serialization.internal#platformSpecificSerializerNotRegistered__at__kotlin.reflect.KClass<*>(){}kotlin.Nothing + 174 
    at 1   Shared                              0x10a8ed95f        kfun:kotlinx.serialization#serializer__at__kotlinx.serialization.modules.SerializersModule(kotlin.reflect.KType){}kotlinx.serialization.KSerializer<kotlin.Any?> + 1631 
    at 2   Shared                              0x10a8ed2ca        kfun:kotlinx.serialization#serializer(kotlin.reflect.KType){}kotlinx.serialization.KSerializer<kotlin.Any?> + 138 
    at 3   Shared                              0x10a98132b        objc2kotlin_kfun:Greeting#greet(){}kotlin.String + 379 
```

**Environment**
 - Kotlin version: 1.9.23
 - Library version: 1.6.3
 - Kotlin platforms: KMP(K/N for iOS)
 - Gradle version: 8.4
 - IDE version (if bug is related to the IDE) Android Studio JellyFish 2023.3.1 & XCode 15.0.1

**Comment by Gargantua7** [comment]
if defined a module like
```
SerializersModule {
    contextual(Value::class, ValueSerializer)
}
```
can fix this issue, but it is not flexible

**Comment by pdvrieze** [comment]
@Gargantua7 You need to add `@Serializable(ValueSerializer::class)` to `Value`. At that point it will be available directly (as the default, you can still override it at the use site).

**Comment by Gargantua7** [comment]
> @Gargantua7 You need to add `@Serializable(ValueSerializer::class)` to `Value`. At that point it will be available directly (as the default, you can still override it at the use site).

`Value` just a sample. In my real project, the class defined in a third party lib, so i cant add any annotation to it.

And this sample work fine on Android or JVM, so i think it maybe a bug on Native

**Comment by xiaozhikang0916** [comment]
`foo<@Serializable(with = ValueSerializer::class) Value>()` is it even a valid statement?

I ran the code snippet in jvm test but failed with `Serializer for class 'kotlinx.serialization.Value' is not found.`

**Comment by Gargantua7** [comment]
Amazing that this sample also throw exception even on Android，but in my real project, the business logic has been work fine for a few week. It seems I need check it and turn to use `SerializersModule`.

thx for answers

**Comment by Gargantua7** [comment]
> `foo<@Serializable(with = ValueSerializer::class) Value>()` is it even a valid statement?
> 
> I ran the code snippet in jvm test but failed with `Serializer for class 'kotlinx.serialization.Value' is not found.`

Sorry that I not apply `org.jetbrains.kotlin.plugin.serialization` plugin in my sample project, so it will failed on Android.
And after I apply plugin, this sample work fine.

So `foo<@Serializable(with = ValueSerializer::class) Value>()` is a valid statement

**Comment by xiaozhikang0916** [comment]
Can you share your demo project? As I am failing both in unit test and Android application.

------

> `foo<@Serializable(with = ValueSerializer::class) Value>()` is it even a valid statement?

I doubt that if it is possible to add an annotation to an existing type when passing to an inline function, or create a new type for the plugin.

**Comment by Gargantua7** [comment]
> Can you share your demo project? As I am failing both in unit test and Android application.
> 
> > `foo<@Serializable(with = ValueSerializer::class) Value>()` is it even a valid statement?
> 
> I doubt that if it is possible to add an annotation to an existing type when passing to an inline function, or create a new type for the plugin.

this is the sample project, maybe you should configuration the android sdk in local.properties:

[EmptyProject 2.zip](https://github.com/Kotlin/kotlinx.serialization/files/15344867/EmptyProject.2.zip)

**Comment by xiaozhikang0916** [comment]
Intresting, if the statement `foo<@Serializable(with = ValueSerializer::class) Value>(Value(42))` is in a library module ( `shared` in the demo project ), it runs fine. But if move it to the application module ( `composeApp` there ), `SerializationException` is thrown.

**Comment by Gargantua7** [comment]
Will plans to fix it or remove the feature ? This will determine if I end up keeping it as is or using `SerializationException`

**Comment by pdvrieze** [comment]
@Gargantua7 I meant to put that annotation at the class declaration. It doesn't work as part of a function type parameter (erasure). If you want to have the function work, have another (non-reified) version of the function that takes the serializer as parameter.

**Comment by Gargantua7** [comment]
>  I meant to put that annotation at the class declaration. 
Sorry that the class is declaration at third party library (eg. Number, BigDecimal), so I have no way to put to the annotation

> It doesn't work as part of a function type parameter (erasure)
In fact it will work fine in the JVM's library module, discussed above
