### ISSUE TITLE
Are there any fully documentation or specification for codec developer?

### ISSUE THREAD

**Issue by iseki0** [Kotlin/kotlinx.serialization#2682]
**What is your use-case and why do you need this feature?**
When I almost completed my decoder. I found I was fallen into a big problem. After reading the document for `StructureKind.Kind`, I think I can always returning *zero* in `decodeElementIndex` when list decoding. And then, I got a reversed list. 😋
**Describe the solution you'd like**
I understand it's my problem, I misunderstood the documentation. But, where's the fully documentation? For someone, who're writing codec.
So embarrassing。🤗😣😥

**Comment by pdvrieze** [comment]
@iseki0 Unfortunately the "codec"/format writing documentation is somewhat lacking. Generally the best way to figure out how things work is to look at the source code of the library (and other formats).

**Comment by iseki0** [comment]
I feel difficult to understand why the ListSerializer returns a _reversed list_, if I always return index _zero_. @pdvrieze

**Comment by pdvrieze** [comment]
@iseki0 The reason is that `AbstractCollectionSerializer` uses the `insert` function with the index as inserting point (through `AbstractCollectionSerializer.merge`). And of course inserting (repeatedly) at the start of the list effectively reverses it.

**Comment by iseki0** [comment]
> @iseki0 The reason is that `AbstractCollectionSerializer` uses the `insert` function with the index as inserting point (through `AbstractCollectionSerializer.merge`). And of course inserting (repeatedly) at the start of the list effectively reverses it.

I got it. But I just feel difficult to understand why it designed as-it.

**Comment by iseki0** [comment]
Before I begin to implement the codec. I read the source code of `ListSerializer` family and `MapLikeSerializer`. So I was so depression when I found I fall into a trap.(I forgot the _insertion_ behaviour.)

**Comment by sandwwraith** [comment]
There's a little section in documentation for custom formats: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/formats.md#adding-collection-support

Also, documentation for `SerialDescriptor` itself:

>  For collections and maps indices don't have fixed bound. Regular collections descriptors usually
have one element (`T`, maps have two, one for keys and one for values), but potentially unlimited
number of actual children values. Valid indices range is not known statically
and implementations of such descriptor should provide consistent and unbounded names and indices.
In practice, for regular classes it is allowed to invoke `getElement*(index)` methods
with an index from `0` to [elementsCount] range and element at the particular index corresponds to the
serializable property at the given position.
For collections and maps, index parameter for `getElement*(index)` methods is effectively bounded
by the maximal number of collection/map elements.

But I agree that the amount of guidance for format authors is very limited now. We are definitely going to look into this when stabilizing all internal machinery.
