### ISSUE TITLE
[Feature] Maybe a better code to use this non-object Json { someFeature = Boolean }.encodeToString, which is not allowed in Kotlin.

### ISSUE THREAD

**Issue by SMFDrummer** [Kotlin/kotlinx.serialization#2684]
## What is your use-case and why do you need this feature?

When I try to transform my json serialize thirdparty from com.alibaba.fastjson2 to kotlinx.serialization.json

here are the fastjson2 goes:(parse is JSONObject)

`parse.toJSONString(JSONWriter.Feature.WriteMapNullValue, JSONWriter.Feature.PrettyFormat)`

then I can get a contains nullValue and prettyPrint JsonString

and when I transform this to serialization-json

`Json { prettyPrint = true; explicitNulls = true }.encodeToString(parse)`

I got a damn warning: Redundant creation of Json format. Creating instances for each usage can be slow.

I should bring it to like this:

``` Kotlin
val format = Json { prettyPrint = true; explicitNulls = true }
format.encodeToString(parse)
```

I really KNOW that I need to defind a customize Json to fit my code but I really like to use it when I want to use instead of defind a damn value for use for a period, that's idiot, maybe I never use this defind value yet later.

## Describe the solution you'd like

Here are my solution, I hope it can give you some inspiration for generating Json singleton objects. Of course, using it this way seems to just avoid Kotlin warnings, and it cannot achieve a relatively suitable real singleton that is destroyed when used. It is just an example. I hope you can adopt the idea.

``` Kotlin
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonBuilder

enum class JsonFeature {
    PrettyPrint,
    ExplicitNulls,
    IgnoreUnknownKeys,
}

private fun JsonBuilder.config(vararg features: JsonFeature): JsonBuilder {
    features.forEach {
        when (it) {
            JsonFeature.PrettyPrint -> this.prettyPrint = true
            JsonFeature.ExplicitNulls -> this.explicitNulls = true
            JsonFeature.IgnoreUnknownKeys -> this.ignoreUnknownKeys = true
        }
    }
    return this
}

fun Json.by(vararg features: JsonFeature): Json {
    return Json(builderAction = { config(*features) })
}
```

and use it like this:

`Json.by(JsonFeature.ExplicitNulls, JsonFeature.PrettyPrint).encodeToString(parse)`

that's it, wish for your response, have a nice day fellas.

**Comment by pdvrieze** [comment]
> `Json { prettyPrint = true; explicitNulls = true }.encodeToString(parse)`
> 
> I got a damn warning: Redundant creation of Json format. Creating instances for each usage can be slow.

First of all, you should understand the warning. This is slow if you create a lot of messages in a tight loop. Not if you serialize once in a blue moon. The Json format is not particularly expensive to create, but this might change in the future (things like initialisation of shared caches). Just having a local variable isn't really the solution (it shuts up the warning, but doesn't change the character)

The format should be safe to reuse (Json is). But it would be the user that initialises the format for their use case (this can be done in a global variable or companion).

As to using enums to initialize, this doesn't really work well. It certainly doesn't reduce the cost of creating the format - all candidates need to be looped over - it doesn't allow for non-boolean parameters. The reason that a builder is used is to allow scaleable updating of the options available. The alternative, directly as constructor arguments would require many constructor overloads.

**Comment by SMFDrummer** [comment]
You're right, and I clearly understand that my approach has not reduced any memory overhead. Relax, this is just a crooked idea, just to show you that users may need more of a singleton serializer.

As you said, indeed, users can integrate all the JsonConfiguration combinations they need in the project for centralized one-time definition, and some definitions can also be reused by overriding JsonDefault to reduce memory overhead. I admit that this is great and the effect is also good, but the current Json serializer does not support an instant combination serializer. For example, when receiving Json data, when the data is A, I may execute a combination of several configurations, and when the data is B, I may execute another combination of configurations. There are some combinations that I have used this time and never use again, and finding each combination to define an independent Json serializer will actually slow down the process, and I am not conducive to code maintenance. This is what I want, a singleton serializer that can be created-used-and-released.


I am not very familiar with the basic implementation of the current Json serializer, and I am unable to provide appropriate suggestions from the basic code. You can only focus on my custom implementation, Json.by(). Before the singleton warning is eliminated, I think this is quite convenient. Just write the fixed state I want to define as an enumeration and combine it in by, without worrying about specific settings and values, or whether it is a Boolean or a string. Each individual feature name represents its state, and as long as I reference it, it can give me the desired state. I think this is cool, don't you think?

**Comment by SMFDrummer** [comment]
> > `Json { prettyPrint = true; explicitNulls = true }.encodeToString(parse)`
> > 
> > I got a damn warning: Redundant creation of Json format. Creating instances for each usage can be slow.
> 
> First of all, you should understand the warning. This is slow if you create a lot of messages in a tight loop. Not if you serialize once in a blue moon. The Json format is not particularly expensive to create, but this might change in the future (things like initialisation of shared caches). Just having a local variable isn't really the solution (it shuts up the warning, but doesn't change the character)
> 
> The format should be safe to reuse (Json is). But it would be the user that initialises the format for their use case (this can be done in a global variable or companion).
> 
> As to using enums to initialize, this doesn't really work well. It certainly doesn't reduce the cost of creating the format - all candidates need to be looped over - it doesn't allow for non-boolean parameters. The reason that a builder is used is to allow scaleable updating of the options available. The alternative, directly as constructor arguments would require many constructor overloads. 


You're right, and I clearly understand that my approach has not reduced any memory overhead. Relax, this is just a crooked idea, just to show you that users may need more of a singleton serializer.

As you said, indeed, users can integrate all the JsonConfiguration combinations they need in the project for centralized one-time definition, and some definitions can also be reused by overriding JsonDefault to reduce memory overhead. I admit that this is great and the effect is also good, but the current Json serializer does not support an instant combination serializer. For example, when receiving Json data, when the data is A, I may execute a combination of several configurations, and when the data is B, I may execute another combination of configurations. There are some combinations that I have used this time and never use again, and finding each combination to define an independent Json serializer will actually slow down the process, and I am not conducive to code maintenance. This is what I want, a singleton serializer that can be created-used-and-released.

I am not very familiar with the basic implementation of the current Json serializer, and I am unable to provide appropriate suggestions from the basic code. You can only focus on my custom implementation, Json.by(). Before the singleton warning is eliminated, I think this is quite convenient. Just write the fixed state I want to define as an enumeration and combine it in by, without worrying about specific settings and values, or whether it is a Boolean or a string. Each individual feature name represents its state, and as long as I reference it, it can give me the desired state. I think this is cool, don't you think?

**Comment by sandwwraith** [comment]
While the suggested `Json.by` function may be more convenient to use (although I do not see benefits over regular `Boolean` flags), it entirely misses the point of warning: you shouldn't create a `Json()` instance each time you want to deserialize something. There are a lot of internal caches bound to it (such as `@JsonNames` cache), and by doing so, you may impact both your performance and memory consumption negatively. So `parse.toJSONString(JSONWriter.Feature.WriteMapNullValue, JSONWriter.Feature.PrettyFormat)` cannot be directly translated into Kotlin, as we have settings per instance, not per parse operation. What I can recommend here is to have a couple of top-level Json formats, e.g. 
```
val prettyPrintJson = Json { prettyPrint = true }
val explicitNullsJson = Json { explicitNulls = true }
// etc
```

Or you can improve your `Json.by` function, so it has `Map<Set<JsonFeature>, Json>` internally.

**Comment by SMFDrummer** [comment]
> While the suggested `Json.by` function may be more convenient to use (although I do not see benefits over regular `Boolean` flags), it entirely misses the point of warning: you shouldn't create a `Json()` instance each time you want to deserialize something. There are a lot of internal caches bound to it (such as `@JsonNames` cache), and by doing so, you may impact both your performance and memory consumption negatively. So `parse.toJSONString(JSONWriter.Feature.WriteMapNullValue, JSONWriter.Feature.PrettyFormat)` cannot be directly translated into Kotlin, as we have settings per instance, not per parse operation. What I can recommend here is to have a couple of top-level Json formats, e.g.
> 
> ```
> val prettyPrintJson = Json { prettyPrint = true }
> val explicitNullsJson = Json { explicitNulls = true }
> // etc
> ```
> 
> Or you can improve your `Json.by` function, so it has `Map<Set<JsonFeature>, Json>` internally.

ok buddy, I changed my code. It maybe actually a real convenient and reusable Json.by function. Could you help me checking my code again?

``` Kotlin
enum class JsonFeature {
    PrettyPrint,
    ExplicitNulls,
    IgnoreUnknownKeys,
    AllowTrailingComma,
    AllowSpecialFloatingPointValues
}

@OptIn(ExperimentalSerializationApi::class)
private fun JsonBuilder.config(vararg features: JsonFeature): JsonBuilder {
    features.forEach {
        when (it) {
            JsonFeature.PrettyPrint -> this.prettyPrint = true
            JsonFeature.ExplicitNulls -> this.explicitNulls = true
            JsonFeature.IgnoreUnknownKeys -> this.ignoreUnknownKeys = true
            JsonFeature.AllowTrailingComma -> this.allowTrailingComma = true
            JsonFeature.AllowSpecialFloatingPointValues -> this.allowSpecialFloatingPointValues = true
        }
    }
    return this
}

class JsonCache {
    private val cache = mutableMapOf<Set<JsonFeature>, Json>()

    fun getJson(vararg features: JsonFeature): Json {
        val featureSet = features.toSet()
        return cache.getOrPut(featureSet) {
            Json { config(*features) }
        }
    }
}

private val jsonCache = JsonCache()

fun Json.by(vararg features: JsonFeature): Json {
    return jsonCache.getJson(*features)
}
```

**Comment by SMFDrummer** [comment]
use `private val cache = ConcurrentHashMap<Set<JsonFeature>, Json>()` will be more safety in threads I think...

**Comment by sandwwraith** [comment]
Yes, a concurrent hash map is a must if you have several threads. The rest of the code looks legit. If you don't have any other questions, I'll close the issue.
