### ISSUE TITLE
Fallback nested json errors to default value

### ISSUE THREAD

**Issue by amir1376** [Kotlin/kotlinx.serialization#2693]
Let's suppose I have this class
```kotlin
@Serializable
class Settings(
  val uiScale:Float=1f,
  val theme:String="dark",
)
```

I have serialized this class to a file which the result is 

```json
{
  "uiScale":1.0,
  "theme":"dark"
}
```

now some folk comes and change the json file content to this
```json
{
  "uiScale":2.0, //from 1.0 to 2.0 (accpetable)
  "theme":1 //from "dark" to 1 (not acceptable and cause the whole serialization to fail because it must be string)
}
```

now when I try to deserialize my `Settings` class 
it will throw an exception

Is there any way when a key can't be deserialized use a default value and make the deserialization success ?

I need this result
```json
{
  "uiScale":2.0,
  "theme":"dark" //because previous (1) is invalid for string type use default value that defined in data class
}
```

this is a simple example it could be very nested

**Comment by amir1376** [comment]
but If I have to write custom serializer or transformer,  I have to write it for all of my nested `serializable classes` is that right?

**Comment by sandwwraith** [comment]
Generally, yes, each class has its own serializer. However, you can move some common parts to a serializers' common ancestor

**Comment by pdvrieze** [comment]
Just make sure that each one has a different name (serialname of the typeis used as unique identifier for caching etc.)
