### ISSUE TITLE
Provide public API to create typed collection serializers

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.serialization#27]
There is a need to have top-level serializer extension properties named `list`, `set`, and `map` that construct build-in collection serializers from the element serializers with the following signatures:

```
val <T> KSerializer<T>.list: KSerializer<List<T>>
val <T> KSerializer<T>.set: KSerializer<Set<T>>
val <K, V> Pair<KSerializer<K>, KSerializer<V>>.map: KSerializer<Map<K, V>>
```

So, a list of serializable `Data` items received via REST API in `str: String` could be deserialized conveniently with:

```
val list = JSON.parse(str, Data.list) // inferred type of list is List<Data>
```

**Comment by sandwwraith** [comment]
Implemented.

**Comment by hagabaka** [comment]
The [test case](https://github.com/Kotlin/kotlinx.serialization/blob/4340912c313879dbe748d342af051a3a5a8c52de/runtime/common/src/test/kotlin/kotlinx/serialization/CustomSerializersTest.kt#L96) shows how to use it with custom serializers, but how can we use it with a list of objects using the default serializer from `@Serializable`?

**Comment by dany-kun** [comment]
You can get your List/Set... serializer from the default serializer of class Foo with `Foo.class.serializer().list`
