### ISSUE TITLE
`createAnnotatedEnumSerializer` and `createSimpleEnumSerializer` functions must be made ABI-public

### ISSUE THREAD

**Issue by broadwaylamb** [Kotlin/kotlinx.serialization#2703]
These functions:
- https://github.com/Kotlin/kotlinx.serialization/blob/4bf4113c2c6936e841caf2a8670382e701e7fcc2/core/commonMain/src/kotlinx/serialization/internal/Enums.kt#L83
- https://github.com/Kotlin/kotlinx.serialization/blob/4bf4113c2c6936e841caf2a8670382e701e7fcc2/core/commonMain/src/kotlinx/serialization/internal/Enums.kt#L54

are `internal`, but the kotlinx.serialization compiler plugin generates calls to these functions in user code. This is access violation.

Why this is important to us (the Kotlin compiler team): we're trying to [enable visibility checks during IR validation](https://youtrack.jetbrains.com/issue/KT-68784) in the compiler. Basically, these checks try to ensure that e.g. an internal function is only ever called from the same module it's declared in. We're trying to enable these checks in compiler tests, however, the kotlinx.serialization-related tests are failing because of access violations.

We suggest annotating these functions (and potentially other `internal` functions, calls to which may be emitted into user code by the compiler plugin) as `@PublishedApi`, or making them public.

**Comment by sandwwraith** [comment]
Yes, they should. We usually annotate everything that can be called from generated code with `@PublishedApi` (see e.g. https://github.com/Kotlin/kotlinx.serialization/blob/b811fa3ec06c8dfdd9a0a669c8654c008f24e542/core/commonMain/src/kotlinx/serialization/Serializers.kt#L379), but it was forgotten for these particular functions.
