### ISSUE TITLE
@file:UseContextualSerialization doesn't work with actual typealias on Kotlin 2.0.0

### ISSUE THREAD

**Issue by rjaros** [Kotlin/kotlinx.serialization#2704]
When using a `@file:UseContextualSerialization` annotation with an expected type declared in common target and defined as `actual typealias` on other targets, the compiler reports an error about missing serializer.

**To, Reproduce**
common code:
```kotlin
expect class LocalDateTime
```
common code, different file:
```kotlin
@file:UseContextualSerialization(LocalDateTime::class)

@Serializable
data class Person(
    val id: Int? = 0,
    val firstName: String? = null,
    val lastName: String? = null,
    val createdAt: LocalDateTime? = null,
)
```
jvm code:
```kotlin
actual typealias LocalDateTime = java.time.LocalDateTime
```

The compiler fails with an error message:
```
Serializer has not been found for type 'java.time.LocalDateTime?'. To use context serializer as fallback, explicitly annotate type or property with @Contextual
```
**Expected behavior**
No error. The same code works fine with Kotlin 1.9.24.
Using `@Contextual` annotation directly on a property works as well.

**Environment**
 - Kotlin version: 2.0.0
 - Library version: 1.7.0-RC
 - Kotlin platforms: JS, JVM

**Comment by sandwwraith** [comment]
Quick question: does it work with 2.0 when `typealias LocalDateTime = java.time.LocalDateTime` is not `actual`, just a regular one?

**Comment by rjaros** [comment]
Apparently it doesn't work with regular typealias as well. This is all you need to have a compile error with 2.0.0:

```kotlin
@file:UseContextualSerialization(MyDate::class)
package com.example

import kotlinx.serialization.Serializable
import kotlinx.serialization.UseContextualSerialization

typealias MyDate = java.time.LocalDate

@Serializable
data class MyClass(val d: MyDate?)

fun main() {
}
```
The same file compiles fine with 1.9.24.

**Comment by sandwwraith** [comment]
Thanks, I'll take a look on it.

**Comment by sandwwraith** [comment]
By the way, your original reproducer (with `@file:UseContextualSerialization(LocalDateTime::class)` and `expect class LocalDateTime` in common code) works fine on 2.0.0. So you probably had UseContextualSerialization in the platform sources.

**Comment by rjaros** [comment]
You are right. I've simplified my example too much without checking. In my project, the expect class and typealias are defined in a multiplatform library. But the rest of the code is the same and the  `UseContextualSerialization` is used in the common sources.

**Comment by vladimirfx** [comment]
I just rechecked with 2.0.20-RC and the problem was reproduced.

**Comment by sandwwraith** [comment]
Can you post your reproducer? The one mentioned in the issue works fine for me.

**Comment by vladimirfx** [comment]
> Can you post your reproducer? The one mentioned in the issue works fine for me.

It is crashed several projects. I have try to extract reproducer.

**Comment by vladimirfx** [comment]
Reproducer:

[use-contextual-serializer-bug.zip](https://github.com/user-attachments/files/16608997/use-contextual-serializer-bug.zip)
