### ISSUE TITLE
Support enumerating polymorphic descriptor's subclass information

### ISSUE THREAD

**Issue by rnett** [Kotlin/kotlinx.serialization#2711]
**What is your use-case and why do you need this feature?**

I'm experimenting with a fixed-length serialization format. To be able to support polymorphism, I need to be able to calculate the sizes of each subclass, based on the `SerialDescriptor`. This currently does not seem to be possible.  In particular, I need the following data:

- For closed serialization, the list of subclasses
- For open serialization:
  - the list of registered subclasses
  - whether there is a default deserializer (which is an error for this format, since the max size is unknown)
  - whether there is a default serializer (which is an error for this format, since the max size is unknown)

I think it would be reasonable to include the default serializer and deserializer functions themselves, even though I don't need them for this particular use-case.

**Describe the solution you'd like**
Include the above information in the polymorphic `SerialDescriptor`, or provide methods to look it up from a `SerializersModule`

**Comment by pdvrieze** [comment]
@rnett This is possible through the ability of `SerializersModule` to dump its content. Using that feature you can retrieve all registered serialilizers. There is also an extension function to get the related (base) class from a serialDescriptor (IIRC `contextClass`).

**Comment by rnett** [comment]
Oh nice, thanks, that does look like a workaround.  I think it's still worth having a better way to do this, however, as that's a bit clunky, and `SerializersModuleCollector` is marked as not stable for inheritance.

**Comment by xiaozhikang0916** [comment]
There is some simular use case in [ProtoBuf](https://github.com/Kotlin/kotlinx.serialization/blob/d2dc7d2978bd62971e8ab00de197d59d7e378ed2/formats/protobuf/commonMain/src/kotlinx/serialization/protobuf/internal/Helpers.kt#L113) may be helpful.

**Comment by rnett** [comment]
Ah thanks, I had somehow missed `getPolymorphicDescriptors`.  Between that and using a collector to throw errors if a default is set, I think I should be good.
