### ISSUE TITLE
kotlinx-serialization-hocon 1.7.0 is not published

### ISSUE THREAD

**Issue by osipxd** [Kotlin/kotlinx.serialization#2717]
**Describe the bug**
The HOCON library seems to be missing from 1.7.0 and 1.7.0-RC publications, according to [Maven Central repo](https://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-serialization-hocon/).

**To Reproduce**
1. Add the dependency to your project:
   ```kotlin
   dependencies {
       implementation("org.jetbrains.kotlinx:kotlinx-serialization-hocon:1.7.0")
   }
   ```
2. Sync the project
3. See the error:
    ```
    > Could not resolve all dependencies for configuration ':my-project'.
      > Could not find org.jetbrains.kotlinx:kotlinx-serialization-hocon:1.7.0.
    ```

**Expected behavior**
Dependency resolved successfully

**Environment**
 - Library version: 1.7.0
 - Kotlin platforms: JVM
 - Gradle version: 8.7

**Comment by sandwwraith** [comment]
It is indeed missing.  I thought I've checked all artifacts when migrating to KTS...🤦🏻
@shanshin Can you pls take a look? It looks like something in `publishing-conventions` went wrong for a non-MPP project
