### ISSUE TITLE
Are there any plan add on-the-fly JSON Schema validation?

### ISSUE THREAD

**Issue by iseki0** [Kotlin/kotlinx.serialization#2724]
**What is your use-case and why do you need this feature?**
For the JSON format, do validation during deserialization is absolutely effecienct. Are there any plan or suggestion to complete it?

**Comment by sandwwraith** [comment]
Can you elaborate, please? We do not have any integrations with Json Schema for now, any kind of advanced validation should happen in `init {}` block of serializable classes

**Comment by iseki0** [comment]
Thank you, I means if we can add some feature for it, compose the decoding and validation process, it will be more effeciency. Such as we needn't tokenize the input again.

In that case, JSON schema is a good choice, because it's standardized and widely supported.

**Comment by sandwwraith** [comment]
I still don't get how it should look like. And what do you mean by 'needn't tokenize the input again.'? If you have your validation in `init{}`, it happens after the class is deserialized as usual.

**Comment by iseki0** [comment]
I understand we can do validation during class init, but here's a problem that it's not standardized and it can't cross platform.(I means programming language.).

**Comment by sandwwraith** [comment]
No plans for now, can be discussed as a part of #1115
