### ISSUE TITLE
Provide a default serializer for kotlin.uuid.Uuid class

### ISSUE THREAD

**Issue by sandwwraith** [Kotlin/kotlinx.serialization#2730]
Kotlin 2.0.20 is expected to have a new MPP UUID class (https://youtrack.jetbrains.com/issue/KT-31880, https://github.com/JetBrains/kotlin/commit/25ea5e81af6a1e3638228498f0dea57b7efe5d15). It is reasonable to provide a built-in serializer for it, like we did for `kotlin.time.Duration` when it was moved to stdlib.

Adding a built-in serializer requires changes in the plugin too, so they have to be made in time, preferably in the same Kotlin 2.0.20 or Kotlin 2.1

**Comment by hfhbd** [comment]
How do you want to serialize it for different formats? In string formats, like JSON, properties, xml etc., it is common to use the string representation, but for binary formats, a compact binary (using the two longs directly) would be preferred than encoding the string.

**Comment by sandwwraith** [comment]
Good question. Initially, I was planning to add only String representation, but maybe binary serializer is also required as an additional one

**Comment by sandwwraith** [comment]
Apparently there is no standardized way of storing UUIDs in protobuf (https://github.com/protocolbuffers/protobuf/issues/2224, https://groups.google.com/g/protobuf/c/THxuTQKsz54). Implementation use either `string`, `bytes`, or pair of `fixed64`/`uint64`.

For CBOR, there is tag 37 for UUID byte string (https://www.iana.org/assignments/cbor-tags/cbor-tags.xhtml), which is an accepted extension described here: https://github.com/lucas-clemente/cbor-specs/blob/master/uuid.md

**Comment by Chuckame** [comment]
On the avro binary format, the uuid is officially represented as a string as said by the spec (the default official uuid type), but is also commonly serialized as a fixed-16 to save space (36 characters/bytes vs 16 bytes), so we may also want to handle a uuid differently.

**Comment by sandwwraith** [comment]
Well, in the case of format-specific serializers, you can always mark `Duration` or `Uuid` with `@Contextual` and provide a module for Avro/Cbor. If `SerializersModule` is empty, a default serializer will be used for e.g. Json.
