### ISSUE TITLE
Cannot serializer flow of Objects

### ISSUE THREAD

**Issue by inemtsev** [Kotlin/kotlinx.serialization#2733]
Hi team,

I would like to start serializing a Flow of objects as they come in from a data source. But, when I try to use in this way, I get an error like this:

```
kotlinx.serialization.SerializationException: Class 'SafeFlow' is not registered for polymorphic serialization in the scope of 'Flow'.
To be registered automatically, class 'SafeFlow' has to be '@Serializable', and the base class 'Flow' has to be sealed and '@Serializable'.
Alternatively, register the serializer for 'SafeFlow' explicitly in a corresponding SerializersModule.
	at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:102)
	at kotlinx.serialization.internal.AbstractPolymorphicSerializerKt.throwSubtypeNotRegistered(AbstractPolymorphicSerializer.kt:114)
	at kotlinx.serialization.PolymorphicSerializerKt.findPolymorphicSerializer(PolymorphicSerializer.kt:109)
	at kotlinx.serialization.json.internal.StreamingJsonEncoder.encodeSerializableValue(StreamingJsonEncoder.kt:233)
	at kotlinx.serialization.json.internal.JsonStreamsKt.encodeByWriter(JsonStreams.kt:28)
	at kotlinx.serialization.json.Json.encodeToString(Json.kt:81)
```

Usage in Ktor endpoint:
```

get("/person") {
            val pplFlow: Flow<Person> = getDataFlow()
            call.respondText(Json.encodeToString(pplFlow), ContentType.Application.Json )
        }
```

Is this already achievable somehow?

**Comment by sandwwraith** [comment]
I'm not sure why you are trying to put `Flow` into the response. `Flow` is intended to be a (potentially infinite) asynchronous stream of objects, not a collection. Depending on your `Flow` usage, you may want to do one of the following:
1. Convert it to list and encode `List<Person>`: `Json.encodeToString(pplFlow.toList())`.
2. Send items one-by-one into an open response socket with `pplFlow.collect { item -> ...}`. I'm not sure if this is possible to do with Ktor's `call.respond...`, consult their documentation.

**Comment by inemtsev** [comment]
I was hoping to achieve some extra efficiency, by starting to serialize a flow of results as they are read from several database queries, instead of waiting for all of them to come back first.

A method that yields each query result is what getDataFlow() was hoping to achieve.

**Comment by sandwwraith** [comment]
> as they are read from several database queries, instead of waiting for all of them to come back first.

But you still need to send them all at once using `call.respond` — you will wait for them to come before starting to respond. So I doubt that it will be more efficient than regular `List`. 

In case you wish to stream the content, use either websockets or Ktor's `respondTextWriter/respondOutputStream` with `Flow.collect`. Note that in that case, you'll write a several Json objects into output, not a single Json array

**Comment by sandwwraith** [comment]
See also https://youtrack.jetbrains.com/issue/KTOR-5846/Kotlin-Flow-as-Response
