### ISSUE TITLE
[Possible duplicate] Small inconsistency in the logic of encoding of fields with defaults 

### ISSUE THREAD

**Issue by orchestr7** [Kotlin/kotlinx.serialization#2735]
**(!)** I am aware of the **encoding of defaults** and understand that they are not encoded by default: [Encoding Defaults Documentation](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#encoding-defaults).

**Please close this issue as a duplicate with a reference to the original one, if it exists.**

Consider the following scenario where I have a **default value** for my field `b`:

```kotlin
@Serializable
data class A(
    val a: String?,
    val b: String = "b"
)
```

If I pass a **different** value explicitly:
```kotlin
val value = A("a", "b1")
Json.encodeToString(value)
```
The encoded output is as expected:
```json
{ "a": "a", "b": "b1" }
```

However, if I pass the **default** **value** **explicitly**:
```kotlin
val value = A("a", "b")
Json.encodeToString(value)
```
The encoded output is not what you might expect:
```json
{ "a": "a" }
```

My team encountered a production error because they did not check if the **default compile-time** value was equal to the **non-default runtime** value, and they expected this field to be serialized.

The motivation behind this behavior is clear: it is challenging to distinguish between the default value and an explicitly set value at the frontend level. However, it would be beneficial to mention this explicitly in the README.

**Comment by sandwwraith** [comment]
There's no way to distinguish between these two `"b"`s. In the same way, you can't distinguish between these calls in Kotlin:

```kotlin
fun foo(b: String = "b") {
// you can't tell if "b" is a default value or not
}


foo()
foo("b") // identical call
```

Actually, the very purpose of default values is to be indistinguishable from user-passed ones. Consider using `null`s or wrappers if you need a special differentiation.
