### ISSUE TITLE
very strange serialization

### ISSUE THREAD

**Issue by AdminQQZ** [Kotlin/kotlinx.serialization#2750]
**Describe the bug**
):product version:
jetbrains-kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version = "1.6.3" }

): bug describe the:

The todo code in the ActionResult is set to 100 by default, and the code in the success method is set to 100. Call Json.encodeToString(success); The code field will be flushed out
kotlin tool serialization result {"msg":" not logged in ","date":"1721875124006"}
Serialized result in Gson tool is {"code":100,"msg":" not logged in ","date":"1721875124006"}

![QQ_1721875389163](https://github.com/user-attachments/assets/27b1898f-f494-4d4a-b12e-17e36664ba4a)

**To Reproduce**
Attach a code snippet or test data if possible.

**Expected behavior**

**Environment**
 - Kotlin version: [e.g. 1.3.30]
 - Library version: [e.g. 0.11.0]
 - Kotlin platforms: [e.g. JVM, JS, Native or their combinations]
 - Gradle version: [e.g. 4.10]
 - IDE version (if bug is related to the IDE) [e.g. IntellijIDEA 2019.1, Android Studio 3.4]
 - Other relevant context [e.g. OS version, JRE version, ... ]

**Comment by sandwwraith** [comment]
See https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/basic-serialization.md#defaults-are-not-encoded-by-default and https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#encoding-defaults

**Comment by AdminQQZ** [comment]
thanks,!  i got it
