### ISSUE TITLE
Support for `serializer<@Contextual T>`

### ISSUE THREAD

**Issue by UnknownJoe796** [Kotlin/kotlinx.serialization#2767]
The following incomplete code cannot be used because `@Contextual` doesn't work in `serializer<T>()` .

This code would allow for very short definitions of server endpoints that handle serialization across multiple `Content-Type`s.

```kotlin
inline fun <reified IN, reified OUT> ServerSystem.postHandler(action: (IN) -> OUT) {
    // Get the types for documentation purposes
    val inputType = serializer<IN>()
    val outputType = serializer<OUT>()
    // ... other setup ...
    // set up the underlying server library's request handler
    handler { request ->
        val format = Formats.lookup(headers["Content-Type"])
        val input = format.decodeFromBody(inputType, request.body)
        val output = action(input)
        return@handler HttpResponse(
            body = Formats.lookup(headers["Accept"]).encodeToBody(outputType, output)
        )
    }
}

// ...

val lookup = postHandler { input: @Contextual UUID ->
    database.get(input)
}
```

Attempting to use this crashes because the `@Contextual` annotation isn't carried through.

```kotlin
println(serializerOrNull(typeOf<@Contextual java.util.UUID>()))  // prints null
```

What I would expect is to get a `ContextualSerializer` for the type.

**Comment by xiaozhikang0916** [comment]
The `context` is registered in the [Serializers module](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#contextual-serialization), which means you need to provide a customized format. And if a customized format is provided, you may need not the `@Contextual` here.

**Comment by pdvrieze** [comment]
@UnknownJoe796 As @xiaozhikang0916 says, you can just look up the serializer from the module. `serializerOrNull` is for statically determined serializers. Contextual needs a context.

**Comment by sandwwraith** [comment]
I'm not sure what you are trying to achieve here since a) the `@Contextual` annotation has meaning only inside the `@Serializable` class b) ContextualSerializer is never returned from the `serializer<T>` function since it requires the `SerializersModule` to work. However, there are `serializer<T>` extensions on the `SerializersModule` as well, so I believe you want to do the following:

```kotlin
class Uuid

object UuidSerializer: KSerializer<Uuid> {
    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor("MyUuid", PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: Uuid) {
        TODO("Not yet implemented")
    }

    override fun deserialize(decoder: Decoder): Uuid {
        TODO("Not yet implemented")
    }
}

val myModule = SerializersModule {
    contextual(Uuid::class, UuidSerializer)
}

inline fun <reified IN> postHandler(action: (IN) -> Unit) {
    println(myModule.serializer<IN>().descriptor)
}

@Test
fun contextualDemo() {
    postHandler<Uuid> {  } // prints PrimitiveDescriptor(MyUuid)
} 
```
