### ISSUE TITLE
@file:UseContextualSerialization doesn't work on Kotlin 2.0.20-RC2

### ISSUE THREAD

**Issue by vladimirfx** [Kotlin/kotlinx.serialization#2783]
**Describe the bug**

`@file:UseContextualSerialization` annotation simply doesn't work starting from Kotlin 2.0.0 up to 2.0.20-RC2. Compilation fails with:

`Serializer has not been found for type 'java.util.UUID'. To use context serializer as fallback, explicitly annotate type or property with @Contextual`

**To Reproduce**

```kotlin
@file:UseContextualSerialization(
    forClasses = [
        UUID::class,
    ]
)

package reproducer

import kotlinx.serialization.Serializable
import kotlinx.serialization.UseContextualSerialization
import java.util.UUID

@Serializable
data class ContextualSerializer(val uuid: UUID)

```

Reproducer project: 
[use-contextual-serializer-bug.zip](https://github.com/user-attachments/files/16625074/use-contextual-serializer-bug.zip)

**Expected behavior**

The code above should compile normally.

**Environment**
 - Kotlin version: 2.0.0 - 2.0.20-RC2
 - Library version: 1.7.1
 - Kotlin platforms: JVM
 - Gradle version: 8.10
 - Java: 21

**Comment by sandwwraith** [comment]
Thanks for the report. Apparently `@file:UseContextualSerialization(UUID::class)` or  `@file:UseContextualSerialization(UUID::class, Date::class)` work as expected but `@file:UseContextualSerialization(forClasses = [UUID::class])` does not. That is... not what I expected from compiler plugin API.
