### ISSUE TITLE
Implement additional extension serializers for frequently utilized data types in web requests.

### ISSUE THREAD

**Issue by jamhour1g** [Kotlin/kotlinx.serialization#2786]
**What is your use case and why do you need this feature?**

While developing a bot to extract job data from websites, I needed to handle date and time information in the requests, along with links to the job listings. I expected these common data types to have built-in serializers, akin to those for String or Int, but they were absent. Consequently, having to create serializers for these types in each project becomes a repetitive and burdensome task.

**Describe the solution you'd like**

1. Add extension serializers to [java.time](https://docs.oracle.com/en/java/javase/21/docs/api//java.base/java/time/package-summary.html) interfaces and classes
2. Add extension serializers to [java.net.URI](https://docs.oracle.com/en/java/javase/21/docs/api//java.base/java/net/URI.html) and [java.net.URL](https://docs.oracle.com/en/java/javase/21/docs/api//java.base/java/net/URL.html)

It's worth noting that certain `java.time` classes may require contextual serializers. Perhaps a `ContextualSerializers` factory class could be offered for scenarios where serialization remains consistent, but the input formatting varies, such as with `java.time.ZonedDateTime`.

```kotlin
 class ZonedDateTimeSerializer(
    val format: DateTimeFormatter
) : KSerializer<ZonedDateTime> {
    override val descriptor = PrimitiveSerialDescriptor(ZonedDateTime::javaClass.name, PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: ZonedDateTime) = encoder.encodeString(value.toString())
    override fun deserialize(decoder: Decoder) = ZonedDateTime.parse(decoder.decodeString(), format)
}
``` 
In the future, it may be beneficial to consider adding extensions to `StringFormat` that facilitate its conversion to [HttpResponse.BodyHandler](https://docs.oracle.com/en/java/javase/21/docs/api//java.net.http/java/net/http/HttpResponse.BodyHandler.html), as illustrated in this example.

```kotlin
inline fun <reified T> StringFormat.toBodyHandler() = HttpResponse.BodyHandler {
    HttpResponse.BodySubscribers.mapping(
        HttpResponse.BodySubscribers.ofString(Charsets.UTF_8)
    ) {
        runCatching { decodeFromString<T>(it) }.getOrNull()
    }
}
```

**Comment by sandwwraith** [comment]
I think it was being discussed in #1931, see also #1806 and #507. In short, this is something that is reasonable to have, but we can't make any serializer for time.* default (because different applications need different purposes), and we currently do not have any mechanisms to globally declare serializers per application module. So the only option we do have for now is a separate library with just serializers that can be used with existing `@file:UseSerializers` annotations.
