### ISSUE TITLE
In Kotlin/JS, compiled file size is a little bit too large, is it possible to use native browser JSON to do ser/de?

### ISSUE THREAD

**Issue by EricDeng1001** [Kotlin/kotlinx.serialization#2800]
I use KMP and share same model between mty server and client. In order to pass data between them, I use kotlinx.serialization. But in js browser, this project at least introduced 400kb compiled js file.
I think it is a little bit unnecessary, since my model file is just 1~2 KB. And for web distrubution, it is important to reduce js file size to improve load speed. To simply be able to ser/de a few koltin classes, it doesn't make sense to pay 100x cost.
The idea is, is it possible to implement kotlinx.serialization in js with native browser JSON, and only carry few necessary info (like what field is in a class etc.), so the final size of js file could be down to around 10KB not 400KB?

**Comment by sandwwraith** [comment]
You can try to use `decodeFromDynamic` and see if unused code from `decodeFromString` will be minimized out. However, there are some significant differences that make it hard to use as drop-in replacement. #1894 can give more details
