### ISSUE TITLE
Kotlin version check is finding the wrong version

### ISSUE THREAD

**Issue by sproctor** [Kotlin/kotlinx.serialization#2804]
**Describe the bug**
KotlinX serialization 1.7.0 are not finding the correct Kotlin version for one of my projects.

"Your current Kotlin version is 1.9.21, while kotlinx.serialization core runtime 1.7.2 requires at least Kotlin 2.0.0-RC1. Please update your Kotlin compiler and IDE plugin."

**To Reproduce**
libs.versions.toml:
```
[plugins]

kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[versions]

kotlin = "2.0.20"
kotlinx-serialization = "1.7.2"

[libraries]

kotlinx-serialization-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
```

build.gradle.kts:
```
plugins {
    application
    alias(libs.plugins.kotlin.jvm)
    alias(libs.plugins.kotlin.plugin.serialization)
    ...
}

dependencies {
    ...
    implementation(libs.kotlinx.serialization.core)
    ...
}
```

Gradle: 8.8

**Comment by larkes-cyber** [comment]
any ideas?

**Comment by sproctor** [comment]
It seems like, for whatever reason, the serialization plugin is finding the Kotlin version used by Gradle, not the version used by the project. This only happens for me with this particular project. It's a fairly simple project. The only notable exceptions from my projects without issue is it's JVM-only, and a single module.

**Comment by pdvrieze** [comment]
The only thing I can think of is that you use `buildSrc` and load the version from the kts support. There is an known issue with classloaders if you use that - using includeBuild tends to work better (and handles conflicting versions).

**Comment by sproctor** [comment]
Well, that was funny. After creating a project that was almost identical that refused to reproduce the issue, I finally ran the `clean` task on the original. That fixed the issue.
