### ISSUE TITLE
How the deserialization failures are supposed to be catched?

### ISSUE THREAD

**Issue by unclechu** [Kotlin/kotlinx.serialization#2805]
I’m trying to catch a deserialization error (from a call like this: `Json.decodeFromString<Foo>("...")`) and transform it into a pure value (e.g. `Either<JsonDeserializationFailure, Foo>`). But I couldn’t find a solution, I don’t want to catch a wide-scoped `Exception` that can be totally not related to deserialization issue. I see that the library throws `kotlinx.serialization.json.internal.JsonDecodingException` but I can’t access it because it’s _internal_. How is it supposed to be done?

I went through a bunch of articles about _kotlinx.serialization_ but apparently none of them are talking about errors handling which leaves me confused.

**Comment by unclechu** [comment]
I wonder why does the `kotlinx.serialization.json.internal.JsonDecodingException` has to be internal and not a publicly exposed one?

**Comment by pdvrieze** [comment]
@sandwwraith Just note that `require` throws `IllegalArgumentException` (`check` throws `IllegalStateException`). In this case `require`/`IllegalArgumentException` would be the appropriate exceptions as it is "input" validation.

**Comment by sandwwraith** [comment]
Yeah, I mixed them up in my comment, documentation clearly mentions IllegalArgument.
