### ISSUE TITLE
Bogus error messages in IntelliJ IDEA after switching to 1.7.2

### ISSUE THREAD

**Issue by mipastgt** [Kotlin/kotlinx.serialization#2810]
**Describe the bug**
As soon as I switch to version 1.7.2 (from 1.7.1) of `org.jetbrains.kotlinx:kotlinx-serialization-json` I see bogus error messages in my code like the one in the screen shot below. I call this bogus because neither gradle nor the compiler nor the runtime system seem to have a problem. The code still compiles and runs nicely as before. It's only IntelliJ which seems to be confused. As soon as I switch back to 1.7.1 the error also vanishes. I already tried a complete re-build with deletion of .gradle and .idea but that did not make any difference.

**Environment**
 - Kotlin version: [e.g. 2.0.20]
 - Kotlin platforms: [e.g. JVM, Android, iOS]
 - Gradle version: [e.g. 8.7]
 - IDE version (if bug is related to the IDE) [IntelliJ IDEA 2024.2.1 (Community Edition)]
 - Other relevant context [e.g. OS version, JRE version, ... ] macOS 14.6.1

<img width="1221" alt="Bildschirmfoto 2024-09-07 um 08 58 43" src="https://github.com/user-attachments/assets/9a25009e-604b-4328-a05e-c2ed0eed50d1">

**Comment by sandwwraith** [comment]
Can it be connected to #2809? Do you see any errors in Gradle sync?

**Comment by mipastgt** [comment]
I get the attached output when I change "1.7.1" to "1.7.2" in "libs.versions.toml" and then hit the blue sync icon in IntelliJ IDEA. When I then revert this action and hit the icon again I get no error message.
[gradle_sync.txt](https://github.com/user-attachments/files/16932159/gradle_sync.txt)

**Comment by sandwwraith** [comment]
Yes, it looks like the same issue. Perhaps you can provide a small reproducer project?

**Comment by mipastgt** [comment]
I think I found a reproducer. I generated a compose multiplatform project via the Jetbrains wizard. I then added my libs.versions.toml and added several dependencies from my project to this new project. I did not modify any code. Therefore most of the dependencies are not actually used (including serialization) but I still can reproduce this error when I toggle between 1.7.1 and 1.7.2 in the libs.versions.toml. Please let me know if you can reproduce this too.

[IdeErrorProject 2.zip](https://github.com/user-attachments/files/16934832/IdeErrorProject.2.zip)

**Comment by sandwwraith** [comment]
Thanks, I was finally able to reproduce the issue. It looks like some misunderstanding between Kotlin and Android plugins: if you comment out `kotlin { androidTarget { ... }}` section, Gradle sync finishes without issues. So for now this problem only affects Kotlin MPP with Android projects. I'll continue investigation and will post updates.

**Comment by mipastgt** [comment]
That seems to indicate a hidden Kotlin or Gradle issue. What are you going to do with it?

**Comment by OumaSyuu** [comment]
I`m facing the same issue by adding version 1.7.2 to gradle dependencies. But it`s fine after downgraded to 1.7.1.

**Comment by sandwwraith** [comment]
@mipastgt It is most likely a Kotlin Gradle plugin issue, as POMs of kotlinx.serialization 1.7.1 and 1.7.2 have a lot of differences. I've filed https://youtrack.jetbrains.com/issue/KT-71443, and it is likely to be fixed from the Kotlin side. In the meantime, I'll try to workaround this issue in the next kx.serialization release.

**Comment by hmy65** [comment]
tried kotlin 2.1.0-Beta1 with 1.7.2 for kmp project, still has this issue
