### ISSUE TITLE
How to inject a extra non-existed property when encoding object without data copying

### ISSUE THREAD

**Issue by hzk8000** [Kotlin/kotlinx.serialization#2811]
**What is your use-case and why do you need this feature?**
Hi, I have a data class definition which cannot be changed or inherited. for example:
```kotlin
@Serializable
class Cat(val id:Int)
```
I want to define a customed KSerializer (let's call it `magicSerializer`) that can add `_type` property which doesn't exist in original `Cat` class definition. Just like this:
```kotlin
Json.encodeToString(magicSerializer,Cat(3)) shouldBe """ {"id":3, "_type": "cat"} """
```
Of Cause I Know a way but not very gracefully: copy value to new defined class like:
```
@Serializable class CatSurrogate(val id:Int, @SerialName("_type") val _type:String)
```
So,  is there any simple way to define `magicSerializer` to handle this in case of no any extra data copying?

**Comment by sandwwraith** [comment]
Have you checked out https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#custom-serializers ? I think it lists several ways to do it, with a surrogate or without — writing a pure serializer from scratch operating `Encoder` and `Decoder` interfaces.

**Comment by hzk8000** [comment]
> Have you checked out https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#custom-serializers ? I think it lists several ways to do it, with a surrogate or without — writing a pure serializer from scratch operating `Encoder` and `Decoder` interfaces.

Yes, I have learnt. I know handwrite a `KSerializer` via `encoder.encodeStructure(descriptor) {...} ` DSL can handle this.
However, I don't think it's a perfect way.
Assume that the data class `Cat` is a heavy domain class which hold 100+ fields. 
What I only want is to insert a simple `_type` field.  It seems a too much work to handwrite all 100+ fields.

**Comment by xiaozhikang0916** [comment]
[`@KeepGeneratedSerializer`](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#simultaneous-use-of-plugin-generated-and-custom-serializers) may be help.

**Comment by sandwwraith** [comment]
I'm afraid we currently do not have any ways to achieve this. It's either a written by hand custom serializer, or a surrogate with `@KeepGeneratedSerializer`/`JsonTransformingSerializer`.
