### ISSUE TITLE
Enum is not get serialized

### ISSUE THREAD

**Issue by yandroidUA** [Kotlin/kotlinx.serialization#2812]
**Describe the bug**
I'm experiencing an issue when `Enum` that is present in my `data class` is not get serialized, it just not present in the final object that got passed to the REST call.

**To Reproduce**
- My `data class` definition looks like:
```
@Serializable
data class NewOrganizationUserEntity(
    @SerialName("organisation_id")
    val organizationId: Long,
    @SerialName("user_id")
    val userUuid: String,
    @SerialName("role")
    val role: UserRole = UserRole.Worker,
)
```
- My `UserRole` definition:
```
@Serializable
enum class UserRole {
    @SerialName("worker")
    Worker,

    @SerialName("manager")
    Manager,
}

```

Running the following code:
```
                json.encodeToJsonElement(
                    listOf(
                        NewOrganizationUserEntity(
                            userUuid = userUuid,
                            role = UserRole.Worker,
                            organizationId = organizationId
                        )
                    )
                ).jsonArray
```

Results in the following serialization object, which is not what I've expected:
```
[{"organisation_id":11,"user_id":"d33a1123-22aa-428c-9dbb-e0099c005428"}]
```

P.S. Same result if use `encodeToString` or `encodeToJsonElement`.

**Expected behavior**
I'd expect `role` to be a part of serialized object.

**Environment**
 - Kotlin version: 2.0.20
 - Library version: 1.7.2
 - Kotlin platforms: Android, iOS (Native)
 - Gradle version: 8.7
 - IDE version (if bug is related to the IDE): IntelliJ IDEA 2024.2.0.2 (Community Edition) / Build #IC-242.20224.419, built on August 19, 2024

**Comment by yandroidUA** [comment]
Nice to know, but in my example I'm setting the `role` explicitly, so it shouldn't use default value 🤔 

```
              json.encodeToJsonElement(
                    listOf(
                        NewOrganizationUserEntity(
                            userUuid = userUuid,
                            role = UserRole.Worker,
                            organizationId = organizationId
                        )
                    )
                ).jsonArray
```

The line `role = UserRole.Worker` is an explicit set, isn't it ?

**Comment by sandwwraith** [comment]
> The line role = UserRole.Worker is an explicit set, isn't it 

It is, but it is still equal to the default value:  ` val role: UserRole = UserRole.Worker,`. We compare value with default one, regardless of whether it was set explicitly (because actually there is no way if it was set or not).

**Comment by yandroidUA** [comment]
Got it, thanks for explanation
