### ISSUE TITLE
Serializer Will Sometimes Skip Fields

### ISSUE THREAD

**Issue by chrisjenx** [Kotlin/kotlinx.serialization#2817]
**Describe the bug**
When testing some large looping serialization I found that the serialized values of a Test `data class` didn't always get all there fields serialized (as in some were just missing)

```
insertAll value: TestObject(id=6efba538-b73e-4802-a629-9675bd58eb5a, name=Name 5502317, value=695399686, description=55)
insert entity.value: {"id":"6efba538-b73e-4802-a629-9675bd58eb5a","name":"Name 5502317","value":695399686,"description":"55"}
insertAll value: TestObject(id=a11b8031-1281-42b2-bd1e-1c798634ac42, name=Name 8067562, value=894813584, description=62)
insert entity.value: {"id":"a11b8031-1281-42b2-bd1e-1c798634ac42","name":"Name 8067562","value":894813584,"description":"62"}
insertAll value: TestObject(id=f1edeaad-a1e5-4c15-97f4-5dd9172beb8e, name=Name 9684460, value=882548006, description=0)
insert entity.value: {"id":"f1edeaad-a1e5-4c15-97f4-5dd9172beb8e","name":"Name 9684460","value":882548006}
```
First line is `toString` second is the `json.encodeToString(serializer, value)`, see how description is sometimes missing?

**To Reproduce**

```
private val json = Json {
        ignoreUnknownKeys = false
        isLenient = false
        serializersModule = serializersModuleOf(Uuid.serializer())
    }
```
```
@OptIn(ExperimentalUuidApi::class)
@Serializable
data class TestObject(
    val id: @Contextual Uuid = Uuid.random(),
    val name: String = "Name ${Random.nextInt(10000000)}",
    val value: Int = Random.nextInt(1000000000),
    val description: String = Random.nextInt(100).toString()
)
```
// Serializer fetched through a refied <T> method
val serializer = T::class.serializer()

Loop through a bunch of generated classes and sometimes the description field is missing, seems to be related to putting numbers, in Strings, if I add a bit of "text" to the  randomNumber" it fixes it. 
```
json.encodeToString(serializer, value)
```

**Expected behavior**
Probably should serialize valid fields....

**Environment**
 - Kotlin version: 2.0.20
 - Library version: 1.7.2
 - Kotlin platforms: Multiplatform, Tests Running on JVM target
 - Gradle version: 8.9
 - Other relevant context OSx, Java Target 11, JRE Zulu 21

**Comment by chrisjenx** [comment]
Downgraded to 1.7.1 and it's worse, so the good news is that looks like if there was a fix in place it helped but didn't fix it in 1.7.2

**Comment by chrisjenx** [comment]
Added a space to the description to force it to string, still get odd behavior:
```
insertAll value: TestObject(id=8f68943d-e943-4a97-96c6-e76044714a1e, name=Name 6711561, value=510574470, description=4 )
insert entity.value: {"id":"8f68943d-e943-4a97-96c6-e76044714a1e","name":"Name 6711561","value":510574470,"description":"4 "}
insertAll value: TestObject(id=81e263bb-6ef0-4c09-b3b0-8a9a892745b7, name=Name 7327191, value=284640134, description=6 )
insert entity.value: {"id":"81e263bb-6ef0-4c09-b3b0-8a9a892745b7","name":"Name 7327191","value":284640134}
insertAll value: TestObject(id=c9fa9813-efd1-48f0-907d-f7d465378faa, name=Name 8034254, value=385221483, description=3 )
insert entity.value: {"id":"c9fa9813-efd1-48f0-907d-f7d465378faa","name":"Name 8034254","value":385221483}
insertAll value: TestObject(id=31528910-0576-4666-9494-929a8d0912df, name=Name 8422955, value=714402308, description=7 )
insert entity.value: {"id":"31528910-0576-4666-9494-929a8d0912df","name":"Name 8422955","value":714402308}
```

**Comment by sandwwraith** [comment]
Have you checked out `encodeDefaults` Json setting? https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#encoding-defaults

**Comment by chrisjenx** [comment]
Interesting that does seem to fix it, so I'm guessing it's evaluating if the value that it got when the class was created, matches the default, but because I'm using random, the default will sometimes be the same as the one when it was generated causing it to none encodeDefaults.

I guess no bug, but for sure wasted a bunch of time :(
