### ISSUE TITLE
Chrome headless, webJS removes decimal precision

### ISSUE THREAD

**Issue by chrisjenx** [Kotlin/kotlinx.serialization#2823]
**Describe the bug**

```
AssertionError: Expected <{"description":"description","currency":"usd","type":"SERVICE","split":{"name":"weighted_user","unitAmount":100,"quantity":2.0,"entityWeights":{"1":4.0,"2":2.0},"type":"WEIGHTED_USER"}}>, actual <{"description":"description","currency":"usd","type":"SERVICE","split":{"name":"weighted_user","unitAmount":100,"quantity":2,"entityWeights":{"1":4,"2":2},"type":"WEIGHTED_USER"}}>.
```

**To Reproduce**
Serialize a Double in WebJS to JSON, it will remove the `.0` from floats/doubles. I.e. `4.0` -> `4`
(Only a problem on WebJS, wasm/jvm/android/ios all serialize 4.0 -> 4.0)

**Expected behavior**
WebJS double should respect precision for floating point numbers (inline with JVM/iOS/Native/Wasm etc)

**Environment**
 - Kotlin version: 2.0.20
 - Library version: 0.7.3
 - Kotlin platforms: JS (Web)
 - Gradle version: 8.9.0
 - Other relevant context: OSx, (KMP)

**Comment by chrisjenx** [comment]
Just to clarify, 4.5 will parse to 4.5 etc, it only removes the precision when `.0`

**Comment by sandwwraith** [comment]
That's how `Double.toString()` works in Kotlin/JS, so we can't really do anything with that: https://youtrack.jetbrains.com/issue/KT-21235. This, in turn, is dictated by how JS's `Number` is converted into a string — always dropping a fractional part if it is zero. So, it is dictated by platform implementation.

**Comment by sandwwraith** [comment]
Using any other method would mean that we don't use native implementation anymore, which would likely give a big performance hit
