### ISSUE TITLE
SerializersModule handling

### ISSUE THREAD

**Issue by PhilNikS** [Kotlin/kotlinx.serialization#2826]
In our project, we plan to generate models of serializable classes in a separate JAR file. For some classes, custom serialization is required, which is located in a separate module where we link interfaces with a specific serializer, as well as connect implementation classes with custom serialization. At the moment, this only works if the class requiring custom serialization does not have the @Serializable annotation. However, this variation makes it more difficult to generate a JAR file with the classes, as some classes need to have the annotation while others do not. Is there a way in SerializersModule to replace the default serializer with a custom one?
<img width="458" alt="Снимок экрана 2024-10-08 в 11 02 46" src="https://github.com/user-attachments/assets/9989c695-1b24-4712-957d-16c1ec2ab042">
<img width="1045" alt="Снимок экрана 2024-10-08 в 10 40 06" src="https://github.com/user-attachments/assets/5e77cc0f-664d-4569-8c3f-a67857367d98">

**Comment by sandwwraith** [comment]
See https://github.com/Kotlin/kotlinx.serialization/issues/507 and https://github.com/Kotlin/kotlinx.serialization/issues/2279#issuecomment-1513255471. In short, we do not have currently plans for such a feature, as it contradicts framework design. However, it may be implemented in future.
