### ISSUE TITLE
`@KeepGeneratedSerializer ` cannot be used with `typealias`

### ISSUE THREAD

**Issue by sschuberth** [Kotlin/kotlinx.serialization#2836]
**Describe the bug**

When I have

    internal typealias DependencyMap = @Serializable(DependencyMapSerializer::class) Map<String, Dependency>

I'd expect to be able to do

    internal typealias DependencyMap = @Serializable(DependencyMapSerializer::class) @KeepGeneratedSerializer Map<String, Dependency>

but that does not compile, saying `WRONG_ANNOTATION_TARGET`.

**Environment**
 - Kotlin version: 2.0.21
 - Library version: 1.7.3
 - Kotlin platforms: JVM
 - Gradle version: 8.10.2

**Comment by pdvrieze** [comment]
@sschuberth `@KeepGeneratedSerializer` is only useful on class/type declarations, not on usage. In the specific case of a Map, there is no generated serializer, but rather a standard one in the library. If you want the default serializer, just use `serializer<Map<String,Dependency>>)`.

**Comment by sschuberth** [comment]
You're right, thanks @pdvrieze!
