### ISSUE TITLE
This declaration is opt-in and its usage should be marked

### ISSUE THREAD

**Issue by druzhininSergey** [Kotlin/kotlinx.serialization#2844]
**This declaration is opt-in and its usage should be marked with @kotlinx. serialization. InternalSerializationApi or @OptIn(markerClass = kotlinx. serialization. InternalSerializationApi. class)
I recive this message in my @Serializable annotation.

I have the same code in my other project. but i dont have this message
![image](https://github.com/user-attachments/assets/a0f72278-63fa-4ddc-9f2d-fd11ca2a0499)
plugins {
    alias(libs.plugins.android.application) apply false
    alias(libs.plugins.jetbrains.kotlin.android) apply false
    id("com.google.devtools.ksp") version "2.0.21-1.0.26" apply false
    id("com.google.dagger.hilt.android") version "2.52" apply false
    id("com.google.gms.google-services") version "4.4.2" apply false
    alias(libs.plugins.google.firebase.crashlytics) version "3.0.2" apply false
    alias(libs.plugins.compose.compiler) apply false
    kotlin("jvm") version "2.0.21"
    kotlin("plugin.serialization") version "2.0.21" apply false
}

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.jetbrains.kotlin.android)
    id("com.google.devtools.ksp")
    id("com.google.dagger.hilt.android")
    alias(libs.plugins.google.gms.google.services)
    alias(libs.plugins.google.firebase.crashlytics)
    alias(libs.plugins.compose.compiler)
    kotlin("plugin.serialization")
}

android {
    namespace = ""
    compileSdk = 34

    defaultConfig {
        applicationId = ""
        minSdk = 21
        targetSdk = 34
        versionCode = 12
        versionName = "0.20"
        vectorDrawables {
            useSupportLibrary = true
        }
    }

    buildTypes {
        release {
            isMinifyEnabled = true
            isShrinkResources = true
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = "1.8"
    }
    packaging {
        resources {
            excludes += "/META-INF/{AL2.0,LGPL2.1}"
        }
    }
}

dependencies {
    //Firebase
    implementation(platform(libs.firebase.bom))
    implementation(libs.firebase.analytics)
    implementation(libs.firebase.crashlytics)

    //accompanist.systemuicontroller
    implementation(libs.accompanist.systemuicontroller)

    //kotlinx.serialization
    implementation(libs.kotlinx.serialization.json)

    //navigation
    implementation(libs.androidx.navigation.compose)

    //hilt
    implementation(libs.hilt.android)
    implementation(libs.androidx.hilt.navigation.compose)
    ksp(libs.hilt.android.compiler)

    //liveData observer
    implementation(libs.androidx.runtime.livedata)

    //lifecycle ViewModel
    implementation(libs.androidx.lifecycle.viewmodel.compose)

    //okhttp3
    implementation(libs.okhttp)

    //logging interceptor
    implementation(libs.logging.interceptor)

    //retrofit
    implementation(libs.retrofit)
    implementation (libs.converter.kotlinx.serialization)
//    implementation(libs.retrofit2.kotlinx.serialization.converter)

    // DataStore
    implementation(libs.androidx.datastore.preferences)

    //Coil
    implementation(libs.coil.compose)

    //Paging 3
    implementation(libs.androidx.paging.runtime)
    implementation(libs.androidx.paging.compose)

    //Media3 ExoPlayer
    implementation(libs.androidx.media3.exoplayer)
    implementation(libs.androidx.media3.exoplayer.dash)
    implementation(libs.androidx.media3.ui)
    implementation(libs.androidx.media3.exoplayer.hls)
    implementation(libs.androidx.media3.common)
    implementation(libs.androidx.media3.session)

    //material
    implementation(libs.androidx.material)
    implementation(libs.androidx.material3)

    //compose
    implementation(platform(libs.androidx.compose.bom))
    implementation(libs.androidx.compose.foundation)
    implementation(libs.androidx.activity.compose)

    //runtime-compose
    implementation(libs.androidx.lifecycle.runtime.compose)

    //Splash screen
    implementation(libs.androidx.core.splashscreen)

    implementation(libs.androidx.core.ktx)
    implementation(libs.androidx.appcompat)
    implementation(libs.androidx.ui.tooling.preview)
    implementation(libs.androidx.tv.foundation)
    implementation(libs.androidx.tv.material)
    implementation(libs.androidx.lifecycle.runtime.ktx)
    androidTestImplementation(platform(libs.androidx.compose.bom))
    androidTestImplementation(libs.androidx.ui.test.junit4)
    debugImplementation(libs.androidx.ui.tooling)
    debugImplementation(libs.androidx.ui.test.manifest)
}
**

**To Reproduce**
Attach a code snippet or test data if possible.

**Expected behavior**

**Environment**
 - Kotlin version: [2.0.21]
 - Library version: [1.7.3]
 - Kotlin platforms: [JVM]
 - Gradle version: [gradle-8.9]
 - IDE version [Android Studio Ladybug | 2024.2.1]

**Comment by druzhininSergey** [comment]
I've tried re-syncing the project with Gradle several times and also attempted to copy-paste the code into another file. Neither of these solutions helped resolve the issue.

**Comment by asfdfdfd** [comment]
In my case the culprit was "Enable K2 mode".

Settings -> Languages & Frameworks -> Kotlin.

**Comment by druzhininSergey** [comment]
> In my case the culprit was "Enable K2 mode".
> 
> Settings -> Languages & Frameworks -> Kotlin.

Thanks man! It helped me

**Comment by bgColorGray** [comment]
Still not working properly with Enable K2 mode?

**Comment by druzhininSergey** [comment]
> Still not working properly with Enable K2 mode?

![image](https://github.com/user-attachments/assets/44eaa55a-f28e-4149-b2e8-10e90e8e65da)
Now works fine!

**Comment by ben-gooding-hub** [comment]
I'm also getting this issue, using k2 mode

Latest canary AS + using kotlin 2.1.0

**Comment by GabeK0** [comment]
Can we re-open this issue please @druzhininSergey? It’s still reproing for me and the suggested fix to enable K2 mode does not resolve it. Kotlin version 1.9.0

**Comment by Andy-Cuong** [comment]
@bgColorGray @ben-gooding-hub @GabeK0 Did you try turning off K2 mode, restarting AS, then turning it on again and restarting AS? I had the error with K2 mode on at the beginning, and it stopped showing after I tried the above method

**Comment by Andy-Cuong** [comment]
I'm having the same issue here. Turning K2 mode off and on again doesn't seem to work

**Comment by ben-gooding-hub** [comment]
Resolved this by bumping all my libraries versions to the latest

**Comment by SakurajimaMaii** [comment]
> In my case the culprit was "Enable K2 mode".
> 
> Settings -> Languages & Frameworks -> Kotlin.

Good solution！

**Comment by eriknyk** [comment]
>I'm also getting this issue, using k2 mode
>
>Latest canary AS + using kotlin 2.1.0

Same here solved upgating kotlin version to `2.1.0` thanks @ben-gooding-hub

**Comment by Lucian-Criveanu** [comment]
Enabling/Disabling K2 does not work! Just tested out!

Also using Kotlin 2.1.0 & kotlinx.serialization 1.8.0.

Please fix this issue is very very annoying!

**Comment by sandwwraith** [comment]
@Lucian-Criveanu Are you using the latest version of Android Studio / IntelliJ IDEA?

**Comment by pdvrieze** [comment]
@Lucian-Criveanu You may also need to do a clean cache/indices if some indices are now "stale".

**Comment by Lucian-Criveanu** [comment]
> [@Lucian-Criveanu](https://github.com/Lucian-Criveanu) Are you using the latest version of Android Studio / IntelliJ IDEA?

Android Studio Meerkat Feature Drop | 2024.3.2 Canary 2
Build #AI-243.22562.218.2432.12959061, built on January 23, 2025
Runtime version: 21.0.5+-12932927-b750.29 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Kotlin plugin: K2 mode

**Comment by Lucian-Criveanu** [comment]
> [@Lucian-Criveanu](https://github.com/Lucian-Criveanu) You may also need to do a clean cache/indices if some indices are now "stale".

I've tested this theory, and the outcome is unchanged. Android Studio is encountering problems in the remote module, where kotlinx.serialization is heavily used.

**Comment by Sottti** [comment]
I have same issue.

**Comment by sandwwraith** [comment]
Check out https://youtrack.jetbrains.com/issue/KTIJ-31549 comments — it seems like some problem in one of the oldest versions in AS/IJ. Re-importing project/re-initializing studio settings may help.

**Comment by tangible-idea** [comment]
In my case I had to turn off `K2 mode` then It no longer shows red lines.

**Comment by tangible-idea** [comment]
In my case, I had to turn off K2 mode then It no longer shows the red lines.

**Comment by tangible-idea** [comment]
In my case, I had to turn "off" the K2 mode then It no longer shows the red lines.

**Comment by nickgitnick** [comment]
For me I have to also turn off K2 for this problem to go away.  Updating Android Studio did not fix.  On Android Studio Meerkat | 2024.3.1 Patch 2

**Comment by pdvrieze** [comment]
To me, I've had issues with indices/caches when switching between k2 and normal. Invalidating caches may be needed when switching to k2.

**Comment by dev-gvs** [comment]
Still reproducible on Android Studio Narwhal Canary 1

**Comment by Lucian-Criveanu** [comment]
why is this bug closed ? still happens!

**Comment by CongDuang** [comment]
Is there any maintainer of kotlin.serialization who can explain this problem? As far as the problem is still there, why close it?Is there no other solution? Can I just turn off k2 mode???

**Comment by fzhinkin** [comment]
@CongDuang @Lucian-Criveanu, the issue seems to be on the IDE side and the corresponding issue (https://youtrack.jetbrains.com/issue/KTIJ-31549) is still open. You can share conditions that led to the problem for you there to help developers with reproducing and investigating it.

**Comment by jsjeon** [comment]
> the issue seems to be on the IDE side and the corresponding issue (https://youtrack.jetbrains.com/issue/KTIJ-31549) is still open. 

FYI, ported to https://issuetracker.google.com/issues/426642727

**Comment by AHuminskyi** [comment]
> In my case the culprit was "Enable K2 mode".
> 
> Settings -> Languages & Frameworks -> Kotlin.

Thanks, mate! Have a nice day! 😘

**Comment by ThenAndNoThen** [comment]
For me, upgrading `androidx-annotation-experimental` fixes the issue


`androidx-annotation-experimental = "1.5.1"`

**Comment by GabeK0** [comment]
Update: Even though we weren't using androidx-annotation-experimental anywhere, simply adding that dependency to our affected modules fixed the issue for us!

**Comment by jojoclt** [comment]
I tried adding
```
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
    kotlin {
        compilerOptions.jvmTarget.set(JvmTarget.JVM_21)
    }
```
The error disappear
