### ISSUE TITLE
Missing json validation on parsing with intermediate JsonObject representation

### ISSUE THREAD

**Issue by kunyavskiy** [Kotlin/kotlinx.serialization#2849]
**Describe the bug**

Long values are not validated to be actual longs when parsed from JsonObject

**To Reproduce**
```
import kotlinx.serialization.json.*
import kotlinx.serialization.*

@Serializable
data class A(val a: Long)

fun main() {
    val str = """{"a":"12:34:45"}"""
    println(Json.decodeFromJsonElement<A>(Json.decodeFromString<JsonObject>(str)))
    println(Json.decodeFromString<A>(str))
}
```

**Expected behavior**

Both crash with SerializationException. 
Actually first prints `A(a=12)`, while second one crashes. Btw, the error message in the second one is really misleading. 

**Environment**
 - Kotlin version: 2.0.20
 - Library version: 1.7.3
 - Kotlin platforms: JVM

**Comment by sandwwraith** [comment]
Another incorrect input for the same snippet: `"""{"a": "3 digit then random string"}"""`
From #2656

**Comment by sandwwraith** [comment]
Related issues with JsonLiteral: #2511 #2375 #1298
