### ISSUE TITLE
Android, Gradle, Serialization plugin not working in KMP project

### ISSUE THREAD

**Issue by ssuukk** [Kotlin/kotlinx.serialization#2851]
This might be the same as issue 2508, which is closed. 

`@Serializable` annotation doesn't generate any code.

Also note this stack: 

https://stackoverflow.com/questions/76684973/kotlinx-serialization-serializable-not-being-applied-to-module

**To Reproduce**
Create a fresh KMP project, might be from KMP wizard. Add this code:

```
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

@Serializable
internal data class Project(val name: String, val language: String)

fun test() {
    val data = Project("kotlinx.serialization", "Kotlin")
    val string = Json.encodeToString<Project>(data)
    println(string) // {"name":"kotlinx.serialization","language":"Kotlin"}
    // Deserializing back into objects
    val obj = Json.decodeFromString<Project>(string)
    println(obj) // Project(name=kotlinx.serialization, language=Kotlin)
}
```

It will be impossible to compile it, because: "Argument type mismatch: actual type is 'Project', but 'kotlinx. serialization. SerializationStrategy<T>' was expected."

I observed it first in 1.9.25 KMP project, but the very same behavior happens in 2.021 KMP project.

catalog entries used:
libraries
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
plugins
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

serialization plugin IS included in project gradle and module gradle, I can see it being downloaded when project is first built.

**Expected behavior**

Proper wrappers are generated for annotated file.

**Environment**
 - Kotlin version: 2.0.21 AND 1.9.25
 - Library version: same as Kotlin
 - Kotlin platforms: KMP
 - Gradle version: [e.g. 4.10]
 - IDE version: Android Studio Ladybug | 2024.2.1 Patch 2
Build #AI-242.23339.11.2421.12550806, built on October 24, 2024
Runtime version: 21.0.3+-12282718-b509.11 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 6.8.0-48-generic
Kotlin plugin: K2 mode (Beta)
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 3864M
Cores: 12
Registry:
  ide.experimental.ui=true
  i18n.locale=
Non-Bundled Plugins:
  com.github.copilot (1.5.28.7313)
Current Desktop: KDE

**Comment by sandwwraith** [comment]
Add `import kotlinx.serialization.*` — `encodeToString` extensions are located in this package. #2850 will help with that.
