### ISSUE TITLE
MinifyEnabled = true strips away Serializable objects

### ISSUE THREAD

**Issue by mahmed1987** [Kotlin/kotlinx.serialization#2861]
I am attaching a working project in which the issue can be observed. 

As per the documentation of this library , we are not to change add or modify the proguard files (if we are not using named companion objects).

That hasn't been my observation . 

I am attaching a code sample to demonstrate the issue i obtain with minifyEnabled true. The project zip file is uploaded [here](https://drive.google.com/file/d/1PrT8kHc-qmmZlXo-ByZaaGBCjAdfl2Ej/view?usp=sharing). 

Just open this project in android studio and run the android app on a device or simulator. The app would crash with the following stacktrace . 

![image](https://github.com/user-attachments/assets/38f08663-6eb6-4ca3-9e55-ca77ab021ea3)

Adding `-keep @kotlinx.serialization.Serializable class * {*;}`  to the proguard file would fix this situation , but this is against what the docs say

**Comment by sandwwraith** [comment]
Why did you post it as a separate issue from #2858 though?

**Comment by sandwwraith** [comment]
It seems there are some problems in the connection between serializable objects and R8 full mode. This code:

```kotlin
@Serializable
class Klas

@Serializable
object Obj

println(serializer(typeOf<Klas>()))
println(serializer(typeOf<Obj>()))
```

prints 

```
com.syphyr.kmpplayground.android.Klas$$serializer@424ad69
kotlinx.serialization.internal.ObjectSerializer@5aa608f
```

when R8 full mode is disabled, and throws

```
com.syphyr.kmpplayground.android.Klas$$serializer@424ad69

kotlinx.serialization.SerializationException: Serializer for class 'Obj' is not found.
Please ensure that class is marked as '@Serializable' and that the serialization compiler plugin is applied.
```

when R8 full mode is enabled (which is the default for recent versions of AGP). 
Perhaps proguard rules inside the library indeed have to be updated.

To workaround this, you can either disable full mode (`android.enableR8.fullMode=false` in `gradle.properties`) or apply the `-keep @kotlinx.serialization.Serializable class * {*;}` rule, which you've already mentioned.

Tested on
```
agp = "8.6.1"
kotlin = "2.0.20"
```

**Comment by mahmed1987** [comment]
@sandwwraith I would raise the issue on android issue tracker channel too

I too believe this must be something to do with the navigation library
