### ISSUE TITLE
Small error in documentation of JsonPrimitive.isString

### ISSUE THREAD

**Issue by gekylafas** [Kotlin/kotlinx.serialization#2863]
**Describe the bug**
In https://github.com/Kotlin/kotlinx.serialization/blame/31ab68caec3a448e1485f0d924106044fef112a7/formats/json/commonMain/src/kotlinx/serialization/json/JsonElement.kt#L39 and above it says:

```
    /**
     * Indicates whether the primitive was explicitly constructed from [String] and
     * whether it should be serialized as one. E.g. `JsonPrimitive("42")` is represented
     * by a string, while `JsonPrimitive(42)` is not.
     * These primitives will be serialized as `42` and `"42"` respectively.
     */
```

I believe the serialization examples should be the other way around, i.e. "...as `"42"` and `42` respectively".

**Comment by sandwwraith** [comment]
Yeah, I think you're right, thanks for heads-up!
