### ISSUE TITLE
Allow specifying transients and serializers per encoder

### ISSUE THREAD

**Issue by Aphexus** [Kotlin/kotlinx.serialization#2876]
I have some need to mix different serializes for optimal happiness value.

Much of my data is "json compatible" by which I mean is amenable to json visualization and editing. Some of the data, though, is not compatible with json. These are large binary arrays of data(file contents) that either have to be converted to Base64 or some other string compatible format(which will double or triple their already significantly significant size) or hacks have to be used that reduce overall optimal happiness value.

To combat the declining happiness values and maximize routine robustness it would be nice if one could specify the serializer type for @Transient and @Serializable. E.g., @Transient(Json) @Serializable(with = SomeSerializer::class, Cbor, Json)

The effects are obvious. They only apply when the current serializer type is specified.

It should be an extremely simple implementation with minimal likelihood of bugs that provides additional functionality. It should likely work also with the same type. I think to express this one might want to wrap other serializes: @Transient(json2)

Maybe one could specify a unique string and then apply that to the serializer itself: 

@Transient("MySerializer") 

var json = Json { SerializerName = "MySerializer" }

with the defaults being what is obviously obvious.

It may seem odd that one would want to have multiple serializes but it really isn't odd at all. Json provides a nice way to visualize and change settings in file while cbor provides a nice compact data representation which handles large binary data seemlessly. Json does not and cannot handle this.

What would be nice, but this is asking for the moon, would be to extend cbor to enable a json type which one could embed json into it and then have references to cbor values that contain the binary data. This probably wouldn't be too hard to do and likely backwards compatible without issues.

**Comment by pdvrieze** [comment]
@Aphexus Due to the fact that serializers are compile-time constructs by default it is not quite as easy as you say. There are some options:
- Use `@Contextual` for the serializer and look it up in the serializersModule - this displaces it to the runtime configuration and works for all formats
- Have each format detect and "magically" substitute the serializer they are called with with a different one.
- Have a custom serializer that checks the encoder/decoder and based on its type forwards to different implementations. Or as in XML:
  - Have a format recognize a interface of `SerializationStrategy`/`DeserializationStrategy` to treat specially.

Note that the library is primarily designed for serialization, not for visualisation (where you may want to omit some data because it is not useful in that context).

**Comment by sandwwraith** [comment]
Given that there are potentially infinite number of formats (anyone can implement their own Encoder and Decoder), I have a hard time imagining how this can be implemented. Maybe we can make a difference between `BinaryFormat` and `StringFormat`; however, such approach would also mean that any format author has to respect such annotation and implement support for them.

So, the more feasible approach I can see for now is that one can implement specific serializers that check whether `encoder is JsonEncoder` or `encoder is CborEncoder`. By doing so, it becomes your responsibility to determine all different formats, with having a sane default when you can't figure out details past generic `Encoder`. Perhaps this can even be baked in a DSL for serializers, if we will have one.

**Comment by Aphexus** [comment]
@sandwwraith I don't understand why it would be a problem. One is not forced to specify any formats. The default still holds.

@Transient itself doesn't have to specify any "infinite number formats" because it actively accepts any possibility.

@Transient blocks all formats, @Transient("x") just blocks the all formats but x.  That is, it excludes X.

When the serializer comes across or is parsing @Transient and it is of a specific format type, if it's name is in the list then it simply acts as if @Transient was never annotated. One doesn't have to know anything about any future formats.

I don't know how the code works but in general it shouldn't be a problem.

As the serializer checks for @Transient It should be able to do a more specialized check to see if the current format being serialized exists in the list, either branch would be exactly the same as @Transient.

E.g., instead of  "if (member.TransientAnnotated) { ignore } else { process }" it becomes "if (member.TransientAnnotated && !member.Transient.contains(currentFormat)) { ignore } else { process } " with the negation could go either way(inclusive or exclusive)

It really should be no more complex than this in general, I would imagine... unless the code is very strange.

I can't find where the @Transient check occurs in the code so I can't see how it works but surely it is just an if check and I'm only saying to make that check more intricate. 

There is literally no reason to have to know all the possible formats to exclude them all. @Transient already does that and doesn't have to know them all. I'm just saying to have a finer grain control over that to allow *know* ones to bypass the annotation is necessary.

**Comment by pdvrieze** [comment]
@Aphexus Note that this is all done at compile time, and independent of the format. From a format perspective, transient attributes don't exist at all. They are not included in the descriptor. The serializer doesn't include code to write transient members. The deserializer doesn't have code to read the member, instead when the actual object is constructed the transient member is initialised per the default in the class. Your desired behaviour seems to be more like what optional attributes do. Also, there is no registry of format names

**Comment by Aphexus** [comment]
I may be being dumb but I don't understand unless you are saying that the serializer is completely computed and fixed at compile time before any formats are specified in any way shape or form and one cannot in any way reference them.

But I still don't understand how that could be possible since @Transient works in excluding members from being serialized in some way.

What if, say, instead of event talking about @Transient being in any way related to a format we had, as just an example: @Transient(k) where k is an integer: so something like @Transient(3) var f: String = ""

Then the serialization process has to process the annotation @transient and in that process it can choose to exclude the field(as if just specified with @Transient which we know works) if "k = 3" whatever that means. You are saying there is no way to connect "k = 3" to the format. E.g., 

var json = Json { TrasientVal = 3 }  
// or maybe: var json = @TransientVal(3) Json { TrasientVal = 3 }  
var j = json.encodeToString(dat) // Won't encode f

You are saying there is no way in any shape or form that the json "encodeToString" can figure out that f has a @Transient marked on it because all that stuff is "done at compile time" and outside the scope of encodeToString. Can one not add additional meta data at compile time where one can do the check? In, say, the D language this would be trivial thing to do as one builds the serializer. 

Whatever serializer the encodeToString uses, could you not build a unique serializer that depends on the Transient value and then use that serializer for the format?

E.g., Can you not, in Kotlin compile time programming, be able to use annotations in such a way to shape the creation of different serializes? Basically parameterized serializes? And then instantiate the correct one(we know we can do at least one, so why not variants?) and use that with the format?

E.g., in the example above there is no reference to formats, essentially @Transient is parameterized and that parameter then parameterized the entire serializer just as we do, analogously, in parameterizing functions. Then we can select the serializer we want to use based on setting the parameter value and it then corresponds to the annotated structure that matches. (so this could be done with any annotations we attach to shape the serialization process.

Basically it's like we are just duplicating the class structure but changing the annotations for different cases.

At the end of the day there has to be some way because it's literally just a basic `if` check/branch.

I'm not necessarily saying it has to work in some specific way because I don't know enough about Kotlin or the serializer design to know what the method is.

What I'm wanting to do, though, is extremely simple. I could achieve this, for example, by completely duplicating my project and simply removing @Transient annotations in one. Of course I can't achieve what I want overall(since I need to mix the two together) in this case but it proves that the problem is essentially a rewrite rule. I can't understand why Kotlin would not have some way be able essentially parameterize the annotation and produce the corresponding serializer and then we can use that in the way we need.

e.g.,
public inline fun <reified T> StringFormat.encodeToString(value: T): String =
    encodeToString(serializersModule.serializer(), value)

public inline fun <reified T> SerializersModule.serializer(): KSerializer<T> {
    return serializer(typeOf<T>()).cast()

should be extendable like:
public inline fun <reified T> StringFormat.encodeToString(value: T, type: SerializerVariant = DefaultVariant): String =
    encodeToString(serializersModule.serializer(), value, type)

public inline fun <reified T> SerializersModule.serializer(type: SerializerVariant = DefaultVariant): KSerializer<T> {
    return serializer(typeOf<T>(), type).cast()


Then somehow(and maybe it is impossible due to the "meta programming" limitations of koltin) when the field is checked for @Transient it's "value" can be extracted if specified and then that compared with the variant type passed.

But you basically seem to be telling me that at run time there is no way to query anything about any field annotations(even though there is an ::class.annotations which I would expect to hold @Transient in it along with the values passed which then could be compared with type.

Is kotlin really this limiting in compile time programming that there is no any way to do any of this at all?
