### ISSUE TITLE
Ability to turn off pretty print for specific members and classes

### ISSUE THREAD

**Issue by Aphexus** [Kotlin/kotlinx.serialization#2878]
I'm pretty printing json and some it is rather bloated looking when it always puts an entry on a new line for arrays of types.
                        {
                            "a": 0.4,
                            "b": 1
                        },
                        {
                            "a": 0.5,
                            "b": 2
                        },
                        {
                            "a": 0.6,
                            "b": 3
                        },
                        {
                            "a": 0.7,
                            "b": 4
                        },
                        {
                            "a": 0.8,
                            "b": 5
                        }

rather than something more concise like

 { "a": 0.4,"b": 1 }, { "a": 0.5, "b": 2 }, { "a": 0.6, "b": 3 }, { "a": 0.7, "b": 4 }, { "a": 0.8, "b": 5 }

I know one can make a custom serializer but.

**Comment by sandwwraith** [comment]
NB: No, custom serializers can't control Json formatting, it is entirely in the format.

I'm not sure it is reasonable to add this directly to the library, perhaps what you want is to turn off pretty printing completely and then use custom json formatter on the output.

**Comment by Aphexus** [comment]
That's what I switched to doing. I'm now just writing out the json to disk and formatting it the way I want.

I guess my confusion comes from the fact that I don't understand why the serializer and the format are completely separated and there is no way to pass information from one to the other. In other languages like D it would be no problem to query information about one from the other and make decisions based on that.
