### ISSUE TITLE
 How to handle default values in custom format implementation

### ISSUE THREAD

**Issue by jamal-ahmad** [Kotlin/kotlinx.serialization#2881]
Apologies if this is the wrong place / issue-type to ask questions

> ℹ️ I've also asked this [question on stackoverflow](https://stackoverflow.com/questions/79281756/kotlinx-serialization-how-to-handle-default-values-in-custom-format-implement) as well to hopefully get an answer

**Context For The Question**

I've been following the `kotlinx-serialization` [Custom formats guide](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/formats.md#custom-formats-experimental) to implement a custom binary protocol and have run into a wall

The `Decoder` in question reads from a `kotlinx-io` [Buffer](https://github.com/Kotlin/kotlinx-io?tab=readme-ov-file#overview) and creates `data class` instances

I'm not sure how to handle default values in classes:

```kotlin
@Serializable
data class Foo(
    val one: Int,
    val two: Int,
    val three: Short,
    val four: Short = 10, // notice the default value
)
```

Because field `four` has a default value, it shouldn't matter if the source `Buffer` has a value for it. This source `Buffer` can sequentially contain either:

- 12 bytes / 4 fields
```text
|int  |int  |short |short |
|bbbb |bbbb |bb    |bb    |
```

- or 10 bytes / 3 fields
```text
|int  |int  |short |
|bbbb |bbbb |bb    |
```

This decoder implementation is pretty trivial at the moment (testcase and stacktrace are further below)_

```kotlin
class BufferDecoder(
    private val buffer: Buffer
    private var elementsCount: Int = 0,
) : AbstractDecoder() {
    private var elementIndex = 0
    override val serializersModule: SerializersModule = EmptySerializersModule()

    override fun decodeBoolean(): Boolean = buffer.readByte().toInt() != 0

    override fun decodeByte(): Byte = buffer.readByte()

    override fun decodeShort(): Short = buffer.readShort()

    override fun decodeInt(): Int = buffer.readInt()

    override fun decodeLong(): Long = buffer.readLong()

    override fun decodeFloat(): Float = buffer.readFloat()

    override fun decodeDouble(): Double = buffer.readDouble()

    override fun decodeChar(): Char = buffer.readByte().toInt().toChar()

    override fun decodeString(): String = buffer.readString()

    override fun decodeEnum(enumDescriptor: SerialDescriptor): Int = decodeByte().toInt()

    override fun decodeSequentially(): Boolean = true

    override fun decodeElementIndex(descriptor: SerialDescriptor): Int =
        if (elementIndex == elementsCount) {
            CompositeDecoder.DECODE_DONE
        } else {
            elementIndex++
        }

    override fun beginStructure(descriptor: SerialDescriptor): CompositeDecoder =
        BufferDecoder(
            buffer = buffer,
            elementsCount = descriptor.elementsCount,
        )
}
```

**To Reproduce**

```kotlin
class OptionalFieldTest {
    @Test
    fun `options fields default when not enough bytes are available`() {
        val buffer =
            Buffer().apply {
                writeInt(1)
                writeInt(2)
                writeShort(3)
                // notice missing writeShort() here
            }
        val decoder = BufferDecoder(buffer)
        val decoded = decoder.decodeSerializableValue(serializer(), null)
        println("decoded into value=$decoded")
    }
}
```

```text
Buffer doesn't contain required number of bytes (size: 0, required: 2)
java.io.EOFException: Buffer doesn't contain required number of bytes (size: 0, required: 2)
    at kotlinx.io.Buffer.throwEof(Buffer.kt:163)
    at kotlinx.io.Buffer.readShort(Buffer.kt:103)
    at com.acme.corp.serde.BufferDecoder.decodeShort(BufferDecoder.kt:<line_number>)
    at kotlinx.serialization.encoding.AbstractDecoder.decodeShortElement(AbstractDecoder.kt:52)
    at com.acme.corp.serde.OptionalFieldTest$Foo$$serializer.deserialize(OptionalFieldTest.kt:<line_number>)
```

The buffer is exhausted when field `four` needs to be decoded _(which is fine)_ but `kotlinx-serialization` tries to decode another `Short`

**Question**

How does one tell `kotlinx-serialization` to use the default value for the last/remaining fields in such a scenario?
i.e. if in `BufferDecoder`, `buffer.exhausted()` is `true`, then how do i make `decodeShort()` return the default value for field `four` or any thereafter?

Is this even the right approach?

**Environment**
 - Kotlin version: `2.0.20`
 - Library version: `2.0.20`
 - Kotlin platforms: JVM
 - Gradle version:  `8.11.1`
 - IDE version (if bug is related to the IDE): IntelliJIDEA  2024.3 _(including for completion)_
 - Other relevant context [e.g. OS version, JRE version, ... ] `MacOS Sonoma 14.7.1`, `Eclipse Temurin 17`

**Comment by jamal-ahmad** [comment]
From the stackoverflow answer: https://stackoverflow.com/questions/79281756/kotlinx-serialization-how-to-handle-default-values-in-custom-format-implement/79281871#79281871

I followed `Simon Jacobs`'s advice and set

```kotlin
override fun decodeSequentially(): Boolean = true
```

additionally i tweaked the following:

```kotlin
override fun decodeElementIndex(descriptor: SerialDescriptor): Int {
    if (elementIndex == elementsCount) {
        return CompositeDecoder.DECODE_DONE
    }
    val elemKind = descriptor.getElementDescriptor(elementIndex).kind
    return when {
        buffer.exhausted() && elemKind != PrimitiveKind.STRING -> CompositeDecoder.DECODE_DONE
        else -> elementIndex++
    }
}
```

the `elemKind != PrimitiveKind.STRING` check is required because in the protocol string of 0 length can arrive.

Concretely for a type like so:

```kotlin
data class Error(val code: Int, val message: String)
```

A buffer of length 4 (a single `Int`) can be decoded successfully 

**Is this the right approach? any anti-patterns/smells?**

**Comment by sandwwraith** [comment]
Hi! You can get an idea how the generated code looks like from this chapter: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#handwritten-composite-serializer

You can see there, that if `decodeElementIndex` returns some index, then corresponding `decodeElement` is called. The deserializer is calling `decodeShort(descriptor, 3)` because your `decodeElementIndex` returned 3 at some point. If you won't return it, default value will be inserted automatically.

```kotlin
when {
        buffer.exhausted() || elementIndex == elementsCount -> CompositeDecoder.DECODE_DONE
        else -> elementIndex++
    }
```

is a good approximation. However, with this approach default values will work only if they're placed last in the class. Given that your format does not support keys for values, it may be enough.

Hope this answers your question.

**Comment by jamal-ahmad** [comment]
> Hi! You can get an idea how the generated code looks like from this chapter: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/serializers.md#handwritten-composite-serializer
> 
> You can see there, that if `decodeElementIndex` returns some index, then corresponding `decodeElement` is called. The deserializer is calling `decodeShort(descriptor, 3)` because your `decodeElementIndex` returned 3 at some point. If you won't return it, default value will be inserted automatically.
> 
> ```kotlin
> when {
>         buffer.exhausted() || elementIndex == elementsCount -> CompositeDecoder.DECODE_DONE
>         else -> elementIndex++
>     }
> ```
> 
> is a good approximation. However, with this approach default values will work only if they're placed last in the class. Given that your format does not support keys for values, it may be enough.
> 
> Hope this answers your question.

yup, it does answer the question 🙂 

And you're right that this approach will only support default values for fields that show up last in the class.
This is the expectation from the protocol i'm implementing so all is good!

The only exception is a `String` i.e. a `String` can show up at the end of a of class and should consume the remaining buffer bytes.
If there are no bytes left, then it should default to an empty string even if no default value is defined for the field.

and so to support his i've done:

```kotlin
when {
        buffer.exhausted() && elemKind != PrimitiveKind.STRING -> CompositeDecoder.DECODE_DONE
        else -> elementIndex++
    }
```

**Comment by sandwwraith** [comment]
Of course, you can tune it further to the specifics of your protocol. Good luck!
