### ISSUE TITLE
KClass<T>.serializer() Contains @ImplicitReflectionSerializer Annotation

### ISSUE THREAD

**Issue by jrob5756** [Kotlin/kotlinx.serialization#291]
Just upgraded from version 0.6.2 to 0.9.1.  In our app, we have the need to do some dynamic serialization where the type is only known at runtime. This requires a bit of reflection as well as the use of the KClass<T>.serializer() function.  I noticed starting in version 0.9.0 the @ImplicitReflectionSerializer annotation was added to the serializer() and compiledSerializer() functions in the PlatformUtils.kt file.

Of course I can get around this by adding the following annotations.

```
@Suppress("EXPERIMENTAL_IS_NOT_ENABLED")
@UseExperimental(ImplicitReflectionSerializer::class)
```

I completely understand why this was added as one of the design goals is "to serialize objects without reflection."  That said, in my case, reflection is somewhat unavoidable.  As we move forward with our app, it gives me pause to be using "experimental" features.  Does the team plan on removing/internalizing some of these features down the road?

**Comment by sandwwraith** [comment]
We don't have any plans for now to remove these annotations. In some future, reflective methods could be replaced with compiler intrinsics, but we can't give the timeframe yet.

It is perfectly fine to use these methods if you have carefully read the documentation for `@ImplicitReflectionSerializer` and understood its restrictions. If you don't like suppressing a warning and using `@UseExperimental` a lot, you can enable experimental features for the whole module using command-line [compiler argument](https://kotlinlang.org/docs/reference/using-gradle.html#compiler-options), like [here](https://github.com/Kotlin/kotlinx.serialization/blob/master/build.gradle#L111).

**Comment by jrob5756** [comment]
Perfect, thanks for the update!
