### ISSUE TITLE
Can't locate companion serializer for class class List

### ISSUE THREAD

**Issue by flaghacker** [Kotlin/kotlinx.serialization#30]
The documentation mentiones that serializing lists is supported, but I can't seem to get it working.

When running this code in **Kotlin-JS**:
```Kotlin
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JSON

fun main(args: Array<String>) {
    val list = listOf(Foo("a"), Foo("b"))
    println(JSON.stringify(list))
}

@Serializable
data class Foo(val foo: String?)
```

I get the exception `SerializationException "Can't locate companion serializer for class class List"`. I'm using Kotlin version `1.1.50` and kotlinx.serialization version `0.2`.

**Comment by sandwwraith** [comment]
For root-level collections you must specify serializers explicitly: #27

**Comment by jivimberg** [comment]
@sandwwraith Just for reference can you provide an example? 
In particular I'm trying to work with a map and I'm not sure from which Pair to get the map property. So far I couldn't find any example to illustrate this use case.

**Comment by sandwwraith** [comment]
@flaghacker it was recently added: https://github.com/Kotlin/kotlinx.serialization/commit/9f198711c8baca3dfb4f6435cced2395cc013b8e#diff-04c6e90faac2675aa89e2176d2eec7d8R75

**Comment by sandwwraith** [comment]
@jivimberg You should use `.map` function on `Pair<KeySerializer, ValueSerializer>`. For `@Serializable` marked types serializer is companion object, and for built-ins you can use `IntSerializer`, etc from `internal` package

**Comment by flaghacker** [comment]
Hmm I still don't really get what I'm supposed to do. An edaptation of @elizarov's (proposed) example in #27 doesn't compile:

    val list = JSON.parse("""{"foo": "Hello World!"""", Foo.list)

And I'm looking to go the other way around, _serializing_ an object.

**Comment by sandwwraith** [comment]
seems like arguments just messed up: `KSerializer` goes first argument in function, so you need `JSON.stringify(Foo.list, """[{"foo": "List"}]""")

You can find more examples in tests: https://github.com/Kotlin/kotlinx.serialization/blob/master/runtime/common/src/test/kotlin/kotlinx/serialization/CustomSerializersTest.kt#L88

**Comment by flaghacker** [comment]
Hmm, with that exact code the gradle build fails with:

```Type inference failed: Cannot infer type parameter T in fun <T> stringify(saver: KSerialSaver<T>, obj: T): String
None of the following substitutions
(KSerialSaver<String>,String)
(KSerialSaver<List<Foo>>,List<Foo>)
can be applied to
(KSerializer<List<Foo>>,String)```.

Also `Foo.list` is an unresolved reference according to Idea, is that normal?

**Comment by sandwwraith** [comment]
Sorry, of course `.stringify` should have `List<Foo>` as second argument - it's serializing; and `.parse` should have string as second argument to get back `List<Foo>`

Yes, that's normal because regular Kotlin plugin don't know about synthetic objects. We will release small additional plugin soon.

**Comment by flaghacker** [comment]
Hmm the signature of `.stringify`: `fun <T> stringify(saver: KSerialSaver<T>, obj: T): String`, so it looks like `Foo.list` has to go in the first place after all? Maybe I had to specify the type argument explicitly?

I can't reproduce my issue from yesterday anymore, now `gradle build` also complains: "Unresolved reference: list", still your exact code. My `build.gradle`: (should be the same as yesterday really)
```buildscript {
    ext.kotlin_version = "1.1.51"

    ext.kotlinx_html_version = "0.6.4"
    ext.kotlinx_serialization_version = "0.2"

    ext.kotlin_src = "src/"

    ext.web_dir = "web"
    ext.build_dir = "build/kotlin/main"

    repositories {
        mavenCentral()
        jcenter()

        maven { url "https://plugins.gradle.org/m2/" }
        maven { url "https://kotlin.bintray.com/kotlinx" }
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlinx:kotlinx-gradle-serialization-plugin:$kotlinx_serialization_version"
    }
}

apply plugin: "kotlin2js"
apply plugin: "kotlin-dce-js"
apply plugin: "kotlinx-serialization"

repositories {
    mavenCentral()
    jcenter()

    maven { url "http://dl.bintray.com/kotlin/kotlin-eap-1.1" }
    maven { url "https://kotlin.bintray.com/kotlinx" }
}

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-js:$kotlin_version"
    compile "org.jetbrains.kotlinx:kotlinx-html-js:$kotlinx_html_version"
    compile "org.jetbrains.kotlinx:kotlinx-serialization-runtime-js:$kotlinx_serialization_version"
}

sourceSets {
    main.kotlin.srcDirs = [kotlin_src]
}

compileKotlin2Js {
    kotlinOptions.moduleKind = "plain"
    kotlinOptions.outputFile = "${build_dir}/main.js"

    kotlinOptions.sourceMap = true
    kotlinOptions.sourceMapEmbedSources = "always"
}

task copyJsBuildFiles(type: Copy) {
    dependsOn runDceKotlinJs

    from "${build_dir}/min"
    into web_dir
}

task web {
    dependsOn copyJsBuildFiles
}```

I'm sorry for the mess.

**Comment by sandwwraith** [comment]
You build file looks OK, can you provide some example code?

**Comment by flaghacker** [comment]
```import kotlinx.serialization.Serializable
import kotlinx.serialization.json.JSON

fun main(args: Array<String>) {
    val list = listOf(Foo("a"), Foo("b"))
    println(JSON.stringify(Foo.list, """[{"foo": "bar"}]"""))
}

@Serializable
data class Foo(val foo: String?)```
Is my full code right now.

**Comment by sandwwraith** [comment]
You've just mixed up JSON methods:

```kotlin
val list = listOf(Foo("a"), Foo("b"))
println(JSON.stringify(Foo.list, list))
```

will print **se**rialized list, and

```kotlin
println(JSON.parse(Foo.list,  """[{"foo": "bar"}]"""))
```

will print **de**serialized list

**Comment by coolemza** [comment]
this one working:
        val map = mapOf(1 to "1", 2 to "2")
        val serial = (IntSerializer to StringSerializer).map
        val s = JSON.unquoted.stringify(serial, map)
        assertEquals("{1:1,2:2}",s)
but not this:
        val map23 = mapOf(1 to mapOf(3 to "4"), 2 to mapOf(4 to "5"))
        val serial = (IntSerializer to StringSerializer).map
        val s = JSON.stringify(serial, map23)

is it possible to serialize nested maps?

**Comment by sandwwraith** [comment]
Yes, @coolemza , it's possible, but you need to specify a nested serializer too:
`val serial = (IntSerializer to (IntSerializer to StringSerializer).map).map`

I suggest you to wrap this structure in a `@Serializable` class to let the compiler plugin build serializer for you

**Comment by pmiklos** [comment]
Do you have an example of how to get it right with Map? I have been desperately trying all possible combinations with or without generics, can't get it working:

```
JSON.parse(Pair.map, message)
JSON.parse(Pair<String, Int>.map, message)
JSON.parse<Map<String, Int>>(Pair.map, message)
...
```

**Comment by sandwwraith** [comment]
@pmiklos you need to call `.map` extension function on instance of `Pair<KSerializer<K>, KSerializer<V>>` to get `KSerializer<Map<K,V>>`. So serializer for your example would be `Pair(StringSerializer, IntSerializer).map`. `IntSerializer` and etc located in the `kotlinx.serialization.internal` package

**Comment by pmiklos** [comment]
Thanks, that works indeed. I just realized that StringSerializer and IntSerializer are objects and not classes...

**Comment by sandwwraith** [comment]
Most of use-cases described here are now mentioned in [documentation](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/runtime_usage.md#obtaining-serializers).

Feel free to open new issues if you have some problems.

**Comment by IARI** [comment]
is it possible to serialize nested maps of dynamic unknown depth?

**Comment by pdvrieze** [comment]
@IARI There is nothing in the architecture that prevents the dynamic unknown depth. If it works for depth 2 it works for depth 10 it works for depth 50. (There are practical limits due to JVM stack size)
