### ISSUE TITLE
JsonArray doesn't equals-compare with other lists correctly.

### ISSUE THREAD

**Issue by reitzig** [Kotlin/kotlinx.serialization#301]
As far as I can tell, the (implicit?) convention for Kotlin collections is that different instances of `List` (or `Set`) should be equal if the (sequence of) elements is equal -- no matter what the concrete type is.

For example, this test (added to `kotlinx/serialization/json/JsonTreeTest.kt`) is green:

```kotlin
@Test
fun equalCollections() {
    val hashSet: Set<JsonElement> = HashSet(listOf(JsonLiteral(3), JsonLiteral(4)))
    val linkedHashSet: Set<JsonElement> = LinkedHashSet(listOf(JsonLiteral(3), JsonLiteral(4)))
    assertEquals(hashSet, linkedHashSet)
}
```

However, comparing a `JsonArray` -- which implements `List<JsonElement>` -- with another `List` we get a red test:

```kotlin
val jsonList: List<JsonElement> = JsonArray(listOf(JsonLiteral(3), JsonLiteral(4)))
val arrayList: List<JsonElement> = ArrayList(listOf(JsonLiteral(3), JsonLiteral(4)))
assertEquals(jsonList, arrayList)
```

**Comment by sandwwraith** [comment]
I think same issue will happen with maps?

**Comment by reitzig** [comment]
Didn't think of `JsonObject` in terms of `Map`, but yes, certainly! Will include that in the PR.

FWIW, I feel delegation should have taken care of this. Added a post to [a related discussion on the forums](https://discuss.kotlinlang.org/t/how-to-implement-equals-and-hashcode-on-list-subtypes/7708?u=reitzig.1).
