### ISSUE TITLE
JsonLiteral doesn't expose the type of unquoted JSON literal

### ISSUE THREAD

**Issue by reitzig** [Kotlin/kotlinx.serialization#303]
The public interface of `JsonLiteral` does not expose the type of the JSON literal. `content` is always available (via `toString()`), and e.g. `int[OrNull]` are delegated to `toInt()` which make integer values available even if the JSON literal was not one.

It is thus impossible to distinguish

```json
{
	"foo": 7
}
```

from

```json
{
	"foo": "7"
}
```

_Use case:_ implementing a JSON Schema validator (cf. [here](https://github.com/reitzig/kovalscj)). In order to verify whether a `:"type": "integer"` assertion is violated, one needs to be able to distinguish values/literals `"7"` and `7`.

**Comment by reitzig** [comment]
This is indeed baked into `JsonTreeParser`: there are no separate token classes for the separate JSON types; those that are not `string` or `null` -- specifically, `number`, `true`, `false` all fall under `TC_OTHER` (and not even _that_ difference is exposed).

Several approaches can be taken, including:

 1. Keep the current parser, but
    a. expose the type of `JsonLiteral.body` directly or
    b. provide `isNumberLiteral`, `isBooleanLiteral`, ... on `JsonLiteral`.
 2. Change the parser to distinguish literal types and have it create instances of corresponding subtypes of `JsonLiteral`.

**Comment by sandwwraith** [comment]
I suppose this is kinda fixed in `dev` since property `isString` of `JsonLiteral` is now public: https://github.com/kotlin/kotlinx.serialization/blob/dev/runtime/common/src/main/kotlin/kotlinx/serialization/json/JsonElement.kt#L147

However, there are indeed no tools to determine a type of the unquoted literal. You can fallback for such checks for now: https://github.com/kotlin/kotlinx.serialization/blob/dev/runtime/common/src/main/kotlin/kotlinx/serialization/json/internal/JsonElementSerializer.kt#L105

**Comment by shanshin** [comment]
Class `JsonPrimitive` contains `isString` property for this purpose

**Comment by Tihon-Ustinov** [comment]
> Class `JsonPrimitive` contains `isString` property for this purpose

and if this number or boolean?

**Comment by qwwdfsad** [comment]
We do not have out-of-the-box extensions for that, but they can be written according to your needs.
E.g. `isNumber` is `!isString && content.toIntOrNull() != null`. One of the pitfalls here is `lenient` mode that allows having non-quoted string literals, but in that case detection of whether something is number or boolean is shifted towards the specific application domain
