### ISSUE TITLE
ByteBuffer endianes on iOS

### ISSUE THREAD

**Issue by maciejpigulski** [Kotlin/kotlinx.serialization#308]
Hello,

I am not sure if I have stumbled upon a bug or I am doing something wrong. Probably the latter.

I am trying to use kotlinx.io.ByteBuffer on Android and iOS. I am able to successfully compile and all. Problem appears in runtime on iOS. Same code that runs on Android and uses ByteBuffer configured to read values in LITTLE_ENDIAN order fails to run on iOS. In fact I am getting BIG_ENDIAN there instead of LITTLE_ENDIAN as configured.

When I change my code to use the buffer in BIG_ENDIAN order then iOS works and bytes are read correctly.

Seems to be very unlikely that there is a bug here but there is nothing else that I can find.

I use this version: https://github.com/Kotlin/kotlinx.serialization/blob/v0.9.1/runtime/native/src/main/kotlin/kotlinx/io/Buffers.kt

**Comment by sandwwraith** [comment]
Hi, do you have an example of code using it with this bug?

**Comment by sandwwraith** [comment]
It seems that naming is just got messed up:

```kotlin
       val bb = ByteBuffer.allocate(4)
        bb.order(ByteOrder.BIG_ENDIAN)
        bb.put(0)
        bb.put(0)
        bb.put(5)
        bb.put(57)
        bb.flip()
        println(bb.getInt())
        bb.flip()
        bb.order(ByteOrder.LITTLE_ENDIAN)
        println(bb.getInt())
        bb.flip()
        bb.order(ByteOrder.BIG_ENDIAN)
        println(bb.getInt())
```

Prints
```
956628992
1337
956628992
```
on Native

and 
```
1337
956628992
1337
```

on JVM. ¯\_(ツ)_/¯

Is this your case?

All these ByteBuffer things were intended to be internal, and they would be completely removed after #253 . Take a look at `kotlinx.io`'s `IoBuffer` to perform multiplatform endiness operations.
