### ISSUE TITLE
JS:  too many arguments provided for a function call 

### ISSUE THREAD

**Issue by runkelstein** [Kotlin/kotlinx.serialization#314]
Hi,

I have a problem with deserialization:

```kotlin

@Serializable
data class StorageInfo(val key : String, val size : Int,
                       @Serializable(with=DateSerializer::class)
                       val updated : Date)
@Serializable
data class StorageEntry( val info : StorageInfo, val  content: String)

// thats the line where the exception gets thrown
JSON.parse(StorageEntry.serializer().list, jsonContent }
```

I get the javascript error: RangeError: too many arguments provided for a function call

So I tried to find the root cause of the problem and debbuged the java script code.

This is kinda where I ended up in kotlin.js
![image](https://user-images.githubusercontent.com/37014620/50403562-d4a09900-079f-11e9-86e2-54276b1b1471.png)

![image](https://user-images.githubusercontent.com/37014620/50403567-e41fe200-079f-11e9-8685-9ae0783d58b1.png)

The content String is very big, in this case its more than 4MB. But I've got also even bigger entries which are roughly about 65MB. So what I can see is that the java script code tries to apply every single char of the entire JSON-String to this function, and that is to much.

I use the API for storing data into the brower-storage for a web-extensions

**Comment by runkelstein** [comment]
```kotlin
@SinceKotlin("1.2")
@kotlin.internal.InlineOnly
public actual inline fun String(chars: CharArray): String {
    return js("String.fromCharCode").apply(null, chars)
}
```

So the actual bug is in the kotlinJs standard library right? Should I open an issue there?

And also, what can I do to circumvent this problem? Converting the object to a string actually worked. Only the other way around is a problem

**Comment by sandwwraith** [comment]
I think that this should be filed as a bug to stdlib, yes

**Comment by runkelstein** [comment]
Now I tried protobuf for storing and retrieving my object.
But I just get a different error: MissingFieldException

```kotlin
    private inline fun StorageEntry.toBytes() = ProtoBuf.dump(StorageEntry.serializer(), this)
/... later .../
    ProtoBuf.load(StorageEntry.serializer(), it[info.key])
```

**Comment by runkelstein** [comment]
And CBOR gives me: Expected byte bf, but found ffffffff ...

I think this might be a problem with storing bytes into the web-extension storage ...
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/StorageArea

Because what I put in is not what I get out ... either a kotlin javascript interop issue or related to the storage ... I don't know

String would probably be less complicated. With JSON it does work, if the object is smaller, then what I tried ...

**Comment by runkelstein** [comment]
Ok I just noticed that there is a "dumps" and "loads" function, which stores the protobuf data as string. With that approach it is now working. For me it seemed that protobuf was alot faster then CBOR.

Still I would love to know how I can store and retrieve in a safe manner a byte array from the storage.

**Comment by runkelstein** [comment]
Btw: I created a bug ticket: https://youtrack.jetbrains.com/issue/KT-29003
However I don't know if that is the place where it belongs

**Comment by sandwwraith** [comment]
Not sure if `kotlin.ByteArray` may be saved in the storage area you've mentioned. You could write a separate test for an arbitrary array (without using kotlinx.serialization) and come to youtrack if you face any issues (or here if issue can be reproduced with serialization only)
