### ISSUE TITLE
Check for no-arg constructor in parent should be disabled if custom serializer is provided

### ISSUE THREAD

**Issue by rnett** [Kotlin/kotlinx.serialization#317]
I was following the example [here](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/custom_serializers.md) for Representing classes as a single value (specifically for an Exposed DAO class), and was getting errors.

The example itself works fine, but with what I was trying to do, the class (and its superclasses) are not Serializable.

Example:
```kotlin
abstract class Test<T>(val id: T)
abstract class TestInt(id: Int) : Test<Int>(id)

class MyTest(val i: Int) : TestInt(i){
    @Serializer(MyTest::class)
    companion object {
        override val descriptor: SerialDescriptor
            get() = StringDescriptor.withName("MyTest")

        override fun serialize(output: Encoder, obj: MyTest) {
            output.encodeString(HexConverter.printHexBinary(obj.id.toString().toByteArray()))
        }

        override fun deserialize(input: Decoder): MyTest {
            return MyTest(String(HexConverter.parseHexBinary(input.decodeString())).toInt())
        }
    }
}
```

As it is, this works.

However, when I mark MyTest `@Serializable`, as is done in the example, it breaks (on compile) because "Non-serializable parent of serializable class MyTest must have no arg constructor".

It seems this is more a problem with the documentation (not needing the `@Serializable` annotation in that example) that anything major.

**Comment by sandwwraith** [comment]
No, the annotation is needed so the class serializer can be auto-discovered. As a workaround, you can specify `@Serializable(with=MyTest.Companion::class)` on MyTest.

Check for no-arg constructor in parent should be disabled if custom serializer is provided.

**Comment by sandwwraith** [comment]
Seems this check is not performed now
