### ISSUE TITLE
Support properties naming configuration

### ISSUE THREAD

**Issue by raderio** [Kotlin/kotlinx.serialization#319]
Is it possible to configure that in Kotlin classes have properties in camel case, but on serialization/deserialization json properties are in snake case?

To configure globally for all classes, not each property like
```
@Serializable
data class(
   @SerialName("my_string") val myString: String
)
```

This is supported in Jackson 
```
val mapper = ObjectMapper();
mapper.setPropertyNamingStrategy(PropertyNamingStrategy.CAMEL_CASE_TO_LOWER_CASE_WITH_UNDERSCORES);
        return mapper;
```

**Comment by gildor** [comment]
Duplicate of #33
