### ISSUE TITLE
Can SerialName annotation support class alias?

### ISSUE THREAD

**Issue by Stzx** [Kotlin/kotlinx.serialization#326]
```
@Serializable
@SerialName("data")
data class Person(val name: String)
```

expect

```
val json = """ { "data": { "name": "Swift" } } """

JSON.unquoted.parse<Person>(json)
```

And I haven't found out what it does when the class uses the SerialName annotation.

**Comment by sandwwraith** [comment]
It does alternate `serializer.descriptor.name`, which is used e.g. in PolymorphicSerializer (and equals by default to a full-qualified name of the class). 

What you're asking is kind of "inverse flat"? (#292) It can be easily emulated by wrapping `Person` into another class.

**Comment by Stzx** [comment]
Yes, I know that it can be implemented by wrapping `Person`. If I don't use the wrapper class, is there a way to do this now or in the future?

**Comment by sandwwraith** [comment]
Now there's no way to do it except customizing
