### ISSUE TITLE
ImplicitReflectionSerializer at every function?

### ISSUE THREAD

**Issue by henry1986** [Kotlin/kotlinx.serialization#327]
In KotlinJS,
I want to serialize JSON objects to kotlin data objects and vica versa. 

I did this by 
`JSON.stringify<DATA>(data)`

and 

`JSON.parse<DATA>(json)`

With version 0.9.1, I need to add an annotation ImplicitReflectionSerializer at almost every function of my code.

How can I avoid this? Searched everywhere but did not find any chance to get around this.

EDIT:

I have tried using stringify(DATA::class.serializer, data), as recommended at ImplicitReflectionSerializer, but I still have to add @ImplicitReflectionSerializer

I've also read, that if I want to disable this Annotations, I've to put compiler option.

I'm using gradle, how can I add a compiler option there? The suggestion found here:

https://github.com/Kotlin/kotlinx.serialization/blob/master/build.gradle#L111

seems not to work in KotlinJS. By using

`    compileKotlin2Js {
        kotlinOptions.freeCompilerArgs +=experimentalsInTestEnabled
        kotlinOptions.freeCompilerArgs +=experimentalsEnabled
    }
`
InteliJ says:
Could not get unknown property 'experimentalsInTestEnabled' for task ':frontend-lib:compileKotlin2Js' of type org.jetbrains.kotlin.gradle.tasks.Kotlin2JsCompile.

**Comment by henry1986** [comment]
Solved the issue by using 

`JSON.parse(DATA.serializer(),json)`

Did not know, that serialzer can be called that way. Always used it with ::class in this way `DATA::class.serializer()`

Best Regards

**Comment by sandwwraith** [comment]
It was in [docs](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/runtime_usage.md#obtaining-serializers) for a some time. Also, manual addition of compiler arguments you've mentioned should work for all platforms. `experimentalsEnabled` is a custom project property: https://github.com/Kotlin/kotlinx.serialization/blob/master/build.gradle#L35

Related: https://github.com/Kotlin/kotlinx.serialization/issues/291#issuecomment-443273688
