### ISSUE TITLE
Make @SerialInfo Annotation.Impl constructor public

### ISSUE THREAD

**Issue by LanderlYoung** [Kotlin/kotlinx.serialization#328]
I'm current writting a [tool](https://github.com/landerlyoung/kproto) to generate kotlin serialization code from protobuf source code.

In order to support `oneof` I need to write my own KSerializer like this:

```kotlin
    @Serializable(with = CompoundItem.Serializer::class)
    data class CompoundItem(
            @Optional
            val item: Any? = null
    ) { ...}
```

But on my user-defined KSerializer class, something won't compile
```kotlin
val serialDescriptor = SerialClassDescImpl("proto.package.CompoundItem")
serialDescriptor.addElement("oneOfType")
serialDescriptor.pushAnnotation(SerialId.Impl(1)) // compiler complains there not constructor form SerialId.Impl
```

AFAIK SerialId.Impl implements SerialId, which may be generated by the kotlinx.serialization compiler extension. And also, kotlin language doesn't allow programmer implements annotation interfaces.

So, for now, I'm kinda stuck on User-Implemented KSerializer.

The only solution here is to make SerialId.Impl(id:Int) public.

Thanks.

**Comment by qwwdfsad** [comment]
Thanks for your interest in custom formats!
After a short discussion, we've decided that this functionality is not the responsibility of `kotlinx.serialization`, but rather a missing Kotlin feature. We are going to discuss its support during Kotlin 1.5 planning.

Thus closing as won't fix.
