### ISSUE TITLE
Custom serializer to keep nested object as plain JSON format

### ISSUE THREAD

**Issue by ClementTroesch** [Kotlin/kotlinx.serialization#345]
Hi,

Is there a way to create a custom serializer that would keep a nested object as plain JSON format ?

For instance, I've got the following JSON data:
```json
{
    "id": "v1",
    "index": {
        "data": "value"
    }
}
```

And the following data class and custom serializer:
```kotlin
@Serializable
data class MyData {

    var id: String = "" // expecting "v1"

    @Serializable(with = IndexSerializer::class)
    var index: String = "" // expecting "{ "data": "value" }"
}

object IndexSerializer : KSerializer<String> {

    override val descriptor: SerialDescriptor
        get() = StringDescriptor.withName("index")

    override fun serialize(output: Encoder, obj: String) {
        // Does nothing for now
    }

    override fun deserialize(input: Decoder): String {
        return "" // Not sure how to retrieve plain JSON
    }
}
```

But I get the following error:
```
kotlinx.serialization.json.JsonParsingException: Invalid JSON at 24: Expected string or non-null literal
```

Any idea on how to avoid this error and retrieve nested JSON ?
Thanks

**Comment by sandwwraith** [comment]
You can cast `input` in `IndexSerializer` to `JsonInput` and then use `.decodeJson` to obtain JsonElement. Its `.toString()` can give you what you want.

**Comment by ClementTroesch** [comment]
Works great, thanks!

**Comment by ccc-sseylani** [comment]
> Works great, thanks!

Can you please show how did you do it ?

**Comment by thejunglegiant** [comment]
> > Works great, thanks!
> 
> Can you please show how did you do it ?

Now `Decoder` have `decode()` methods for any type of primitive value. So, you can use `decodeString()` method and then use it as a regular json string while parsing to your custom object.
