### ISSUE TITLE
How serialize models by superclass?

### ISSUE THREAD

**Issue by ImanX** [Kotlin/kotlinx.serialization#348]
I use kotlinx.serialization on Kotlin native project, I a defined Super class for my models and all of the models extends from it. I defined a function to called toJSON() for serialize variables and fields inside model that all of class models have it.

`@Serializable
open class Model {
   fun toJSON(): String = JSON.stringify(this);
}`

And I created a subclass:

`class Me : Model() {
  var name:String = "Jack";
}`

but when I invoke JSON.stringify(this), IDE get a Warning to me:

>This declaration is experimental and its usage must be marked with 
  '@kotlinx.serialization.ImplicitReflectionSerializer' or 
  '@UseExperimental(kotlinx.serialization.ImplicitReflectionSerializer::class)'

I paid attention and I used @ImplicitReflectionSerializer annotation while not worked. Where is my problem?

**Comment by sandwwraith** [comment]
`@ImplicitReflectionSerializer`, as mention in its name, uses reflection, which is not available on Kotlin/Native. For Native code, prefer using the two-argument form of `stringify` and other functions, passing, e.g. `Me.serializer()`

Please also be aware that serializable classes with inheritance are not supported in Kotlin/Native serialization plugin for now.
