### ISSUE TITLE
Contextual serialization of primitives

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.serialization#349]
```
@file:ContextualSerialization(Float::class)

@Serializable
class F(val f: Float)

fun main() {
    println(Json.stringify(F.serializer(), F(42.0f)))
}
```

will trigger BE error with `Internal error: wrong code generated`

**Comment by sandwwraith** [comment]
Seems like this code anyway can't be compiled outside of JVM backend: https://youtrack.jetbrains.com/issue/KT-28927
