### ISSUE TITLE
Use @file:ContextualSerialization for nullable types

### ISSUE THREAD

**Issue by rjaros** [Kotlin/kotlinx.serialization#351]
I have:

``@file:ContextualSerialization(Date::class)``

``data class A(
val name: String? = null, 
val createdAt: Date? = null
)``

and it doesn't work. 

``Caused by: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Serializer for element of type Date? has not been found.``

I can use:

``data class A(
val name: String? = null, 
@ContextualSerialization val createdAt: Date? = null
)``

but I would prefer not to pollute my model classes.

**Comment by chrisjenx** [comment]
@sandwwraith can we get a snapshot or a point release, as I have just run into this.

**Comment by sandwwraith** [comment]
@chrisjenx  Kotlin 1.3.21 has this fix
