### ISSUE TITLE
Register multiple lists to serializer

### ISSUE THREAD

**Issue by santoshastagi** [Kotlin/kotlinx.serialization#353]
I get a list back from API call, so I have a kotlinxSerializer where I am registering two lists, as 

val kotlinxSerializer = KotlinxSerializer()
kotlinxSerializer.register(FirstList.serializer().list)
kotlinxSerializer.register(SecondList.serializer().list)

However, when I  make the call, only the last registered serializer is used. How can I  register multiple lists to the serializer?

**Comment by jrocharodrigues** [comment]
I have the same problem.

Did you manage to solve it @santoshastagi ?

Thanks

**Comment by DroidPulkit** [comment]
I was thinking maybe using Generics with List, might solve the problem. But did anyone found any work around?
