### ISSUE TITLE
JsonObject.equals throws an exception if keys aren't the same

### ISSUE THREAD

**Issue by charleskorn** [Kotlin/kotlinx.serialization#358]
If I have two `JsonObject` instances, `first` with keys "a" and "b", and `second` with keys "a" and "c", calling `first.equals(second)` throws a `java.util.NoSuchElementException`. 

This behaved correctly in 0.9.1 and is a regression in 0.10.0.

**Comment by sandwwraith** [comment]
Unfortunately, behaviour of `.get` is dictated by a `Map`'s contract, so we the right way to solve this is to either change `.get` so it will return null or to make `JsonObject` not to implement `Map`.

**Comment by qwwdfsad** [comment]
>how do the other Kotlin Map types deal with this problem?

`get` returns nullable type.

**Comment by charleskorn** [comment]
The `get()` / `getValue()` pattern sounds good to me, especially if that makes it consistent with other Kotlin `Map` types.
