### ISSUE TITLE
kotlinx.serialization.json.JsonParsingException: Invalid JSON at 24576: Unexpected end in string

### ISSUE THREAD

**Issue by jrocharodrigues** [Kotlin/kotlinx.serialization#360]
Hi,

I'm using kotlinx.serialization 0.10.0 with ktor 1.1.2 on a multiplatform (Android & ios) project.

When i run my app in android everything works fine,  but on ios, the deserialization fails for the same request (with the same answer) with `kotlinx.serialization.json.JsonParsingException: Invalid JSON at 24576: Unexpected end in string`. 

I've done some tests and the error only occurs if the length of my json is bigger then:

- 16384 - if the json body is all in one line

- 32768 - if the json has mutiple lines

If my json is smaller than that all works fine also on ios.

Is there any limitation to the size of the json body on ios? If so is there any way to circumvent this?

**Comment by sandwwraith** [comment]
This seems like a bug somewhere in ktor-client, we'll try to investigate this

**Comment by jrocharodrigues** [comment]
Probably related with https://github.com/ktorio/ktor/issues/453 ?

**Comment by sandwwraith** [comment]
I suppose this is gonna be fixed by https://github.com/Kotlin/kotlinx-io/pull/36

**Comment by jrocharodrigues** [comment]
Forced the use of kotlinx-io-0.1.5-dev-4 and org.jetbrains.kotlinx:kotlinx-coroutines-io-0.1.5-dev-4  and confirm this issue is solved.
