### ISSUE TITLE
How create nested JSON?

### ISSUE THREAD

**Issue by ImanX** [Kotlin/kotlinx.serialization#365]
I creating a Shared lib by Kotlin multiplatform and I use Kotlin Serialization library for Serialize and Deserialize, I Implementing Graph QL on my project and I use below struct

```json
{
 "operationName":"Operation",
 "query":"query Operation($id: ID){rres: Cards(id: $id){id}}",
 "variables":{"id": 1}
}
```
for communication with API, now I have a issue that I should fill a Json as a Object in variables by Kotlinx.Serialization but I don't find a way for it while I fill varibales as String and API get exception to me.

my code:
```kotlin
return JsonObject(
            mapOf(
                "operationName" to JsonLiteral(getOperationName()),
                "query" to JsonLiteral(toQuery()),
                "variables" to
            )
        )
```

How I create a nested Json by Kotlinx.Serialization?

**Comment by qwwdfsad** [comment]
Why can't you mark your class with `@Serializable` and let the compiler do that for you except for manual deconstruction of the object?

Manual way:
```
return   json {
  "operationName" to getOperationName()
  "query" to toQuery()
  "variables" to json { "id" to variables.id }            
}
```

We have a sample of hand-rolled deserialization: https://github.com/Kotlin/kotlinx.serialization/tree/master/runtime/common/src/test/kotlin/kotlinx/serialization/json/parser/examples

**Comment by ImanX** [comment]
@qwwdfsad Thank's
I will create plain and custom JSON because that's dynamic.
I test your way provided me but not work even that does not joint `variables` segment to strucs

**Comment by ImanX** [comment]
And other a question I create a `var j = json{"a" to 1}`, now How append new value to `j` ?

**Comment by sandwwraith** [comment]
You can create a `MutableMap<String, JsonElement>`, mutate it as you like, and then call a constructor of `JsonObject`

**Comment by ImanX** [comment]
@sandwwraith `MutableMap` is interface and it should create `Anonymous`. have you any sample it?

**Comment by sandwwraith** [comment]
@ImanX use any suitable inheritor or constructor function, e.g. `HashMap` or `mutableMapOf`

**Comment by ImanX** [comment]
@sandwwraith Thanks 
I use `HashMap<String,JsonElement>` when I will put value, It should `JsonElement` type while I cast my `Value` to `JsonElement` but Koltlin get `Exception` to me.  How to I `Strring`, `Integer` & `Boolean` types provide to `HashMap<String,JsonElement>` as `JsonElement`?
