### ISSUE TITLE
Allow `@Serializable(with=...)` on a type usage

### ISSUE THREAD

**Issue by sandwwraith** [Kotlin/kotlinx.serialization#367]
E.g. `class A(val urlList: List<Serializable(URLSerializer::class) URL>)`

See #366.

**Comment by irgaly** [comment]
I want this feature. I want use custom serializer with List.

**Comment by sandwwraith** [comment]
This is implemented in Kotlin 1.3.30

**Comment by irgaly** [comment]
In Kotlin 1.3.30, `List<Serializable(MyDayOfWeekSerializer::class) DayOfWeek>` shows the error, `Expecting a top level declaration`.

Which is right way to do it?

**Comment by sandwwraith** [comment]
Did you forget `@` symbol before the annotation?

**Comment by irgaly** [comment]
With `@`, that is `List<Serializable(@KlockDayOfWeekShortStringSerializer::class) DayOfWeek>` shows `This annotation is not applicable to target 'type usage'`

![2019-04-17 18 18 35](https://user-images.githubusercontent.com/1311446/56276436-737d4680-613d-11e9-99cc-052923e4f597.png)

**Comment by sandwwraith** [comment]
Make sure you also have library version `0.11.0`. Example: https://github.com/kotlin/kotlinx.serialization/blob/b947e6b259f0447d7f1a88a5e598f3d6fcc5d837/runtime/common/src/testWithNative/kotlinx/serialization/features/SerializableOnTypeUsageTest.kt#L14

**Comment by irgaly** [comment]
My project uses Kotlin 1.3.30, Ktor 1.1.4, but Kotlinx.serialization is 0.10.0 by dependencies of ktor.

Adding explicit dependencies `implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.11.0"`, and it works fine.
Thank you. 👍
