### ISSUE TITLE
Uncaught TypeError: ArrayList_init_0 is not a function

### ISSUE THREAD

**Issue by DenisVoloshin** [Kotlin/kotlinx.serialization#369]
Using version '0.10.0' in the multi-paltform project.   
           kotlin 1.3.20  

the sample code is 

```
@Serializable
class Data(val s: String, val i: Int, val b: Boolean)
```

```
val data = TDate("test_data", 1111, true)
Json.indented.stringify(Data.serializer(), data)
```

in the JVM platfrom it works porfect although in JS I'm getting

Uncaught TypeError: ArrayList_init_0 is not a function
  SerialClassDescImpl	
  JsonElementSerializer$descriptor$ObjectLiteral	
  JsonElementSerializer	
  JsonElementSerializer_getInstance	
  Json_init$ObjectLiteral.registerIn_slu7av$	
  AbstractSerialFormat.install_7fck8k$	
  Json	
  Json$Companion	
  Json$Companion_getInstance	
  main	
  (anonymous function)	
  (anonymous function)

**Comment by sandwwraith** [comment]
I can't reproduce your issue. Could there be a possibility that you have a broken dependency on kotlin JS stdlib?
