### ISSUE TITLE
Could not build Objective-C module

### ISSUE THREAD

**Issue by ImanX** [Kotlin/kotlinx.serialization#370]
I use `.framework` file in Xcode project but Xcode got alert `Could not build Objective-C module my_module_name`
 
I opened `.h` file in `.framework` and I know problems are by `JsonPrimitive` code.

<img width="1105" alt="screen shot 2019-02-09 at 10 08 37 pm" src="https://user-images.githubusercontent.com/10783524/52525072-7e3cda80-2cb9-11e9-8c7a-69ca619d95c2.png">

Kotlinx serialization: 0.9.1
Kotlin version: 1.3.10
Gradle version: 4.7

**Comment by sandwwraith** [comment]
#306
