### ISSUE TITLE
Annotating list fields with external serializers

### ISSUE THREAD

**Issue by andylamax** [Kotlin/kotlinx.serialization#372]
As the heading suggests, I fail to get the sytax to annotate list fields of the members with external serializations. See below

```
@Serializable
data class Data1(val a: String = "",val b: String="")

@Serializable(with=AnExternalSerializer::class)
class Data2{
    var p1=1
    var p2=2
}

@Serializable
class BigOne(var p1: Int=0) {
    val data1: Data1 = Data1()
    var datas: List<Data2> = listOf() // brings error, serializer not found
}
```

What do I do to be able serialize lists of externally serialized members/properties?

**Comment by fvasco** [comment]
See https://github.com/Kotlin/kotlinx.serialization/issues/366
