### ISSUE TITLE
Long is stringified incorrectly in 0.10.0

### ISSUE THREAD

**Issue by ildarsharafutdinov** [Kotlin/kotlinx.serialization#373]
```
@Test
fun test() {
    val x =Json.plain.stringify(JsonLiteral(7987654321L))
    assertEquals("7987654321", x)
}
```

results in
```
org.junit.ComparisonFailure: expected:<7[987654321]> but was:<7[.987654321E9]>
```

Is it a known issue? Is there a workaround?

**Comment by qwwdfsad** [comment]
This is indeed a bug with no simple workaround :(
Will be fixed in the next release

**Comment by avently** [comment]
Now .stringify() generates from: 
```
val map = mapOf<Long. String>(123L to "123")
```
this:
```
{ 123: "123"}
```

Shouldn't it be as @sandwwraith mentioned here https://github.com/Kotlin/kotlinx.serialization/issues/368#issuecomment-462252860 this result:
```
{ "123": "123" }
```

Which is comforms to JSON spec as I understood.

We can get quoted long/int key only with toJson().toString() but it will prevent from using indentation and it is slower than stringify(). So maybe let's switch to String as a map key and everything for value key? What do you think?

**Comment by sandwwraith** [comment]
@avently I've opened a separate issue for this: #379

**Comment by ildarsharafutdinov** [comment]
@qwwdfsad ,

any eta for the next release to have this issue fixed?
