### ISSUE TITLE
Custom Boolean serialiser not working

### ISSUE THREAD

**Issue by markGilchrist** [Kotlin/kotlinx.serialization#376]
I have created a custom Boolean serialiser as the server I am working with models "Y" as true and "N" as false

I have  the below serialiser 

``` kotlin
@Serializer(forClass = Boolean::class)
class CustomBooleanSerializer : KSerializer<Boolean> {
    override val descriptor: SerialDescriptor
        get() = BooleanDescriptor.withName("customBooleanDescriptor")

    override fun deserialize(decoder: Decoder): Boolean = when (decoder.decodeString().toLowerCase()) {
        "true", "y" -> true
        "false", "n" -> false
        else -> {
            print("passing error")
            false
        }
    }
}
```
In my data class I am 

``` kotlin
@Serializable
data class Alert(
...
    @SerialName("hf") @Serializable(with = CustomBooleanSerializer::class) val hasFired: Boolean = false,
   ...
) ...
```

when I put a break point in my CustomBooleanSerializer- >deserialise the function doesn't appear to be called.

all my test case switch to default.
kotlin version 1.3.21
serialization version 0.10.0

I have inverted the else case in my deserialiser and there is no change in outcome

have I missed a step here?

**Comment by sandwwraith** [comment]
It works in master for `Long`s, see here: https://github.com/Kotlin/kotlinx.serialization/blob/82e4ba536beba1e2df065e2c4781fc81ee14b282/runtime/common/src/test/kotlin/kotlinx/serialization/features/LongAsStringTest.kt#L26 . I couldn't reproduce your issue, maybe the problem is somewhere around?

**Comment by markGilchrist** [comment]
would it be easier if I forked the project and tried to add a failing test?

do you have an example of this for Boolean or just long?

**Comment by markGilchrist** [comment]
@sandwwraith I have run this in another project and it works fine, the problem has to be with my code, happy to close this as it is not an issue
