### ISSUE TITLE
Dependency on kotlin-reflect

### ISSUE THREAD

**Issue by klassm** [Kotlin/kotlinx.serialization#38]
Hi,

thanks for that nice library! I am wondering when you plan to remove the dependency of kotlinx-serialization-runtime on kotlin-reflect. "In thefuture" seems a little vague :-).

The dependency on kotlin-reflect seems to cause problems with dex on Android, breaking the 64k limit even though using multidex.

Thanks,
Matthias

**Comment by apatrida** [comment]
This is already covered in the README as:

> Add serialization runtime library in addition to Kotlin standard library and reflection (optional). For now, library requires small amount of reflection on runtime to find corresponding serializer for root-level type. In the future, we plan to move all resolving to separate module so the runtime library itself would not contain dependency on kotlin-reflect.

**Comment by klassm** [comment]
Well, actually I've read the readme. However, you are only speaking of future plans, not even of a future release or something.

**Comment by sandwwraith** [comment]
Because Android is important target, I can say that in release version of this library dependency will be definitely removed. However, for now the library is still under design, and there is no clean roadmap yet, so the exact thing I can tell you is "one of the future updates".

**Comment by sandwwraith** [comment]
Newly released version `0.4` does not contain dependency on `kotlin-reflect`. It still uses Java Reflection for resolving in some places, though.
