### ISSUE TITLE
Support non blocking IO

### ISSUE THREAD

**Issue by raderio** [Kotlin/kotlinx.serialization#382]
Does this library support non blocking deserialization?

Reason https://github.com/micronaut-projects/micronaut-core/issues/1255

**Comment by elizarov** [comment]
This library does not really do any IO. It parses ready-to-be-parsed chunks of data (that should contain complete Json documentas, for example) into objects. Our existing parsers are optimized for performance and we'd like to keep them as performant as possible. This goal rules out the idea of JacksonProcessor-like approach. However, we can add a different implementation of parsers that would support parsing on incomplete documents as a separate feature. 

What you please elaborate what is your use-case for "non blocking deserialization"? What are exactly are you trying to achieve?

**Comment by raderio** [comment]
Well, I just wnat to use Micronaut library + Kotlin serialization.
Micronaut uses Jackson, and it supports non-blocking IO.
So, the request is more from Micronaut library than from me.
I asked same question here https://github.com/micronaut-projects/micronaut-core/issues/1255#issuecomment-465643499

**Comment by elizarov** [comment]
I'm lost. I don't see how serialization is related to non-blocking IO for your use-case. You can read incoming bytes in any way (either blocking or no blocking), then deserialize them.

**Comment by fvasco** [comment]
Now serialization requires a random access resource to unmarshall (`ByteArray` or `String`), instead marshalling produces a whole allocated buffer (`ByteArray` or `String`).

A future library improvement is to parse streams or dump object into streams (blocking or non blocking).

@raderio currently this library does not perform any IO operations.

**Comment by raderio** [comment]
Ok, understood, this library just do the deserialization. The IO operations should be one by other libraries.

**Comment by sandwwraith** [comment]
see #253
