### ISSUE TITLE
Caused by: org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Serializer for element of type ByteArray has not been found. To use context serializer as fallback, explicitly annotate element with @ContextualSerialization

### ISSUE THREAD

**Issue by mochadwi** [Kotlin/kotlinx.serialization#384]
I'm trying to use ByteArray in my data class. is it possible?

**Comment by mochadwi** [comment]
Well, after a lot of research. This already been issued before [here](https://github.com/Kotlin/kotlinx.serialization/issues/342#issuecomment-457146447)

Use the @ContextSerialization, to fix the issue.

AS: 3.2.1
Kotlin: 1.3.21
Kotlin Serialization: 0.10.0

Worked, like expected. You can use this powerful utility class

**Comment by mochadwi** [comment]
I've also occurred this error: Can't locate default serializer for class kotlin.Any [here](#240 )

**Comment by mochadwi** [comment]
Then another error come out:  **_kotlinx.serialization.SerializationException: Can't locate argument-less serializer for class kotlinx.serialization.KSerializer. For generic classes, such as lists, please provide serializer explicitly._**

**Comment by sandwwraith** [comment]
Yes, ByteArrays are not officially supported yet. However, if you use `@ContextualSerialization` or, which is better, `@Serializable(with=...)` on a property with bytearray, you should get rid of exception 'Can't locate argument-less serializer for class kotlin.ByteArray' (unless you're trying to serialize it on the root-level of hierarchy). 

For lists, I've created #385 .

**Comment by mochadwi** [comment]
After awhile. I refactor my model to use only primitive values. Until it supported any other types

**Comment by mochadwi** [comment]
> I've also occurred this error: **_Can't locate default serializer for class kotlin.Any_** #240
> 
> After using that solution, I rather choose to use the object or data class itself for convenience.
> 
> ```
> val body: Any
> 
> val serial: KSerialization<out Any> = body::class.serializer() // only receive (out Data type)
> Mapper.map(body)
> 
> // I chooses to build using this approach for now
> 
> val body: MyDataClass()
> 
> Mapper.map(body)
> ```

@sandwwraith how about `Any` data type?

Here's my use case:

```
fun Any.toPartMap(): Map<String, RequestBody> {
   val res: HashMap<String, String> = hashMapOf()
   Mapper.map(this).forEach { (key, value) -> // this line resulting an error
     res[key] = value.toAnotherLibsConvertToReqBody()
   }

   return res
}
```

Using the above approach still not possible, does we have to create custom `AnySerializer`?

Would you mind give us the reference

**Comment by sandwwraith** [comment]
What do you want from serializing `Any`? Since compile-time information about type is lost, you can only either use reflection or pass serializer explicitly (e.g. make it a parameter of `toPartMap`). For reflection options, take a look at `KClass.serializer()` or `serializerByTypeToken`

**Comment by mochadwi** [comment]
> What do you want from serializing `Any`? Since compile-time information about type is lost, you can only either use reflection or pass serializer explicitly (e.g. make it a parameter of `toPartMap`). For reflection options, take a look at `KClass.serializer()` or `serializerByTypeToken`

okay, nice. looks like for readable and reflectionless approach, I rather choose your method.

`MyObjSerializer.toPartMap` or `toPartMap(obj: MyObjSerializer)`

I want to be generic as `Any` for this `toPartMap` function, because not only `MyObj` but also any other `MyObj[1-N]`. So, with `Any` I think I can only build one method. But, looks like it's impossible without reflection? @sandwwraith

**Comment by sandwwraith** [comment]
Why don't use a generic version? `fun <T: Any> T.toPartMap(serializer: KSerializer<T>)`

**Comment by mochadwi** [comment]
> Why don't use a generic version? `fun <T: Any> T.toPartMap(serializer: KSerializer<T>)`

Okay, I'm trying this, and will get the result, to you~

**Comment by mochadwi** [comment]
> Why don't use a generic version? `fun <T: Any> T.toPartMap(serializer: KSerializer<T>)`

Does the implementation will be like this?

```
@UseExperimental(ImplicitReflectionSerializer::class)
fun <T : Any> T.toPartMap(serializer: KSerializer<T>): Map<String, RequestBody> {
    val res: HashMap<String, RequestBody> = hashMapOf()

    Mapper.map(serializer).forEach { (t, u) ->
        if (t != "isEmpty") res[t] = "$u".toRequestBody()
    }

    return res
}
```

@sandwwraith

**Comment by sandwwraith** [comment]
Not sure what 'client side implementation' you're talking about. I assume you have to pass object you want to serialize, too: `Mapper.map(serializer, this)`. You don't have to use `ImplicitReflectionSerializer`.

**Comment by mochadwi** [comment]
> fun <T : Any> T.toPartMap(serializer: KSerializer<T>): Map<String, RequestBody> {
>     val res: HashMap<String, RequestBody> = hashMapOf()
> 
>     Mapper.map(serializer).forEach { (t, u) ->
>         if (t != "isEmpty") res[t] = "$u".toRequestBody()
>     }
> 
>     return res
> }

I'm sorry, I've incorrectly stated the "client-side mean" with, what object I pass to the function. E.g:

the above function, the invocation is receiving `KSerializer<T>`

```
MyModel.toPartMap("should I convert the MyModel into KSerializer first?")
```

@sandwwraith

**Comment by sandwwraith** [comment]
yes, it is stated in the docs.

**Comment by sandwwraith** [comment]
ByteArrays are now temporary banned in JVM code generator, too. They would be supported in one of the future releases.
