### ISSUE TITLE
JsonParsingException if value not set for key

### ISSUE THREAD

**Issue by SimonSchubert** [Kotlin/kotlinx.serialization#387]
I'm using kotlinx-serialization-runtime version 0.10.0 in a mpp.

**Code:**
The following example works fine:
```
@Serializable
data class Test(val bar: Long = 0)

val s = "{foo:, bar:2}"
val test: Test = Json.nonstrict.parse(Test.serializer(), s)
```

But if I change the order of foo and bar in the json string it crashes.

```
val s = "{bar:2, foo:}"
val test: Test = Json.nonstrict.parse(Test.serializer(), s)
```
**Exception:**
kotlinx.serialization.json.JsonParsingException: Invalid JSON at 13: Expected '}'

This is probably a bug or?

**Comment by sandwwraith** [comment]
Actually, JSON in your example is not valid and it is OK for the parser to throw an exception. But I'll take look on how can I improve error message and reach consistency in both cases.

**Comment by SimonSchubert** [comment]
OK thanks. The json is not valid but I have no control over the json response. And since the first eample works out of the box it would be really great to get the second example working too. If it's not an option it would be great to have an effeicient workarround fot it.

**Comment by qwwdfsad** [comment]
Both values are now rejected, even in lenient mode, which is a correct behaviour -- lenient mode allows some insignificance to slip in, but it does not intended to be used with malformed json
