### ISSUE TITLE
Serializable/Serializer on expect/actual classes doesnt work

### ISSUE THREAD

**Issue by spand** [Kotlin/kotlinx.serialization#388]
```
@Serializable
class Response(val localDate: LocalDate)

@Serializable(with = LocalDateSerializer::class)
expect class LocalDate

@Serializer(LocalDate::class)
expect object LocalDateSerializer : KSerializer<LocalDate>
```

And I get the error: `Serializer for element of type LocalDate has not been found`

After suggestions on Slack I tried annotating the actual classes but to no avail:
If I annotate:
* Both expect/actual `LocalDate` and not `LocalDateSerializer`: Internal error `Recursion detected on input: LocalDate...`
* Both expect/acutal `LocalDateSerializer` and not `LocalDate`: `Serializer for element of type LocalDate has not been found`

**Comment by sandwwraith** [comment]
I've annotated all classes (expect/actual LocalDate and expect/actual LocalDateSerializer) and didn't face any issues on JVM or JS. On Native, there is separate bug: #396.

However, we should probably improve diagnostics and decide what to do when annotations are applied only partially.

**Comment by spand** [comment]
Did you try in a single gradle module or multi module setup ?

**Comment by sandwwraith** [comment]
In a single, with 1.3 multiplatform project model

**Comment by spand** [comment]
My case is the multiple module setup. Is that deprecated ?

**Comment by sandwwraith** [comment]
Yes. Closing as obsolete
