### ISSUE TITLE
Invalid JSON at 0: Expected '{, kind: kotlinx.serialization.StructureKind$CLASS@558169d3'

### ISSUE THREAD

**Issue by RiccardoM** [Kotlin/kotlinx.serialization#399]
Hello everyone. 

I'm working on a multiplatform project trying to parse the given JSON:
```json
{
  "pairwiseDid": "pairwise_did",
  "nonce": 123,
  "signature": {
    "hash": "signature_hash",
    "content": {
      "pairwiseDid": "pairwise_did",
      "nonce": 123
    }
  }
}
```

The model class is the following: 
```kotlin
@Serializable
data class Content(
    val pairwiseDid: String,
    val nonce: Long,
    val signature: Signature
)  {

    @Serializable
    data class Signature(
        val content: Content,
        val hash: String
    )  {

        @Serializable
        data class Content(
            val pairwiseDid: String,
            val nonce: Long
        )
    }
}
```

Everytime I execute `Json.parse<Content>()` I get the following error: 
```bash
Invalid JSON at 0: Expected '{, kind: kotlinx.serialization.StructureKind$CLASS@558169d3'
kotlinx.serialization.json.JsonParsingException: Invalid JSON at 0: Expected '{, kind: kotlinx.serialization.StructureKind$CLASS@558169d3'
```

**Comment by qwwdfsad** [comment]
Hi, which version are you using (and which platform)?
I cannot reproduce it in current `dev` on JVM, but it may be a bug in the previous versions

**Comment by RiccardoM** [comment]
My current Gradle setup is the following: 

```
commonMain {
    dependencies {
        implementation deps.kotlin.stdlib.common
        implementation deps.kotlinx.coroutines.common
        implementation deps.kotlinx.serialization

        implementation deps.rx.common
    }
}
commonTest {
    dependencies {
        implementation deps.kotlin.stdlib.common

        implementation deps.kotlinx.coroutines.common
        implementation deps.kotlinx.coroutines.test

        implementation deps.kotlin.test.common
        implementation deps.kotlin.test.annotations

        implementation deps.mockk
    }
}
```

The platform I am using is currently only Android

```
configure([androidMain, androidTest]) {
    dependencies {
        implementation deps.kotlinx.serialization
        
        implementation deps.gson
        implementation deps.web3j
        implementation deps.commons.codec
        implementation deps.rx.jdk
    }
}
```

The version I am using is the (I suppose) latest: `0.10.0`

**Comment by pdvrieze** [comment]
The error message says that the character at position 0 is not a `{` character.. Your sample does have it at that position. Use the debugger to find out what the actual string is that is being parsed.

**Comment by RiccardoM** [comment]
@pdvrieze The string being parsed is that one, I've printed it out and copy/pasted it. I've even tried using the following one: 

```
{"pairwiseDid":"pairwise_did","nonce":123,"signature":{"hash":"signature_hash","content":{"pairwiseDid":"pairwise_did","nonce":123}}}
```

which is the same, removing any possible EOL character. Still getting the same error

**Comment by luxw** [comment]
I had the same problem. I believe it's a BOM character at the beginning of the string that causes serialization to fail. I couldn't find a solution so I hacked my way through this by forcibly removing the first char of the string.

**Comment by sandwwraith** [comment]
Well, I think this can be closed now.

**Comment by WellingtonCosta** [comment]
I'm facing a similar issue:

`kotlinx.serialization.json.JsonParsingException: Invalid JSON at 0: Expected '[, kind: kotlinx.serialization.StructureKind$LIST@47db50c5'`

I have a `.json` file with content that represents a empty array (`[]`) and when I call the API (and consequently deserializing the JSON content) I getting the error above.

**Comment by WellingtonCosta** [comment]
I'm facing a similar issue:

`kotlinx.serialization.json.JsonParsingException: Invalid JSON at 0: Expected '[, kind: kotlinx.serialization.StructureKind$LIST@47db50c5'`

I have a `.json` file with content that represents a empty array (`[]`) and when I call the API (and consequently deserializing the JSON content) I getting the error above.

PS: It works when I put a string that represents an empty JSON array (`"[]"`)
