### ISSUE TITLE
@Serializable objects cause compilation errors

### ISSUE THREAD

**Issue by pauliusrum** [Kotlin/kotlinx.serialization#400]
Hi when i run this code i get `java.lang.NoSuchFieldError: Companion exception`.
```kotlin
fun main() {
    val a = A // Throws java.lang.NoSuchFieldError: Companion
}

@Serializable
object A

@Serializer(forClass = A::class)
object ASerializer : KSerializer<A> {

    override val descriptor = SerialClassDescImpl("ASerializer")

    override fun serialize(encoder: Encoder, obj: A) = encoder.encodeString(obj::class.qualifiedName!!)

    override fun deserialize(decoder: Decoder): A = decoder.decodeString().run { A }
}
```

**Comment by q-litzler** [comment]
You `A` object doesn't have a companion.

I think that what you are trying to achieve could look like this:

```kotlin
@Serializable(A.Companion::class)
object A {

@Serializer(forClass = A::class)
companion object : KSerializer<A> {

    override val descriptor = SerialClassDescImpl("ASerializer")

    override fun serialize(encoder: Encoder, obj: A) = encoder.encodeString(obj::class.qualifiedName!!)

    override fun deserialize(decoder: Decoder): A = decoder.decodeString().run { A }
}
```

**Comment by pauliusrum** [comment]
It works if I install a `SimpleModule`. I could not manage to get it working with annotations it would always throw an exception that serializer could not be found. Is this the correct way to solve this issue?
```Kotlin
@Test
fun main() {
    Json.install(SimpleModule(A::class, ASerializer)
    val a = Json.stringify(A)
}

object A

object ASerializer : KSerializer<A> {

    override val descriptor = SerialClassDescImpl("ASerializer")

    override fun serialize(encoder: Encoder, obj: A) = encoder.encodeString(obj::class.qualifiedName!!)

    override fun deserialize(decoder: Decoder): A = decoder.decodeString().run { A }
}
```

**Comment by q-litzler** [comment]
Did you simply try this ?

```kotlin
@Test
fun main() {
    Json.stringify(A, "A")
    val a = Json.stringify(A)
}

@Serializable(A.Companion::class)
object A {

   @Serializer(forClass = A::class)
   companion object : KSerializer<A> {

       override val descriptor = SerialClassDescImpl("ASerializer")

       override fun serialize(encoder: Encoder, obj: A) = encoder.encodeString(obj::class.qualifiedName!!)

       override fun deserialize(decoder: Decoder): A = decoder.decodeString().run { A }
   }
}
```

I'm not really sure to understand why you are trying to serialize `obj::class.qualifiedName!!` though

**Comment by pauliusrum** [comment]
One can not create a `companion object` inside of an `object`:
```Kotlin
object A {
    companion object { // Compiler error: Modifier 'companion' is not applicable inside 'object'
        
    }
}
```
I just want to serialize objects because at this moment it does not work if I add `@Serializable` annotation to `object A`.

**Comment by q-litzler** [comment]
Sorry, in my code sample you should replace `object` by `class`. I don't really understand your use case. Why do you need to serialize an `object` in your application ?

**Comment by pauliusrum** [comment]
I have a sealed class that represents different errors and i want to make it serializable:

```Kotlin
sealed class Error {
     object Forbidden : Error()
     object Unauthorized : Error()
     @Serializable
     data class Fatal(val message: String) : Error()
}

@Serializable
data class Envelope<T : Any>(val payload: T?, val error: Error?)
```

**Comment by q-litzler** [comment]
```kotlin
@Serializable(Error.Companion::class)
public sealed class Error {

    public object Forbidden : Error()

    public object Unauthorized : Error()

    public data class Fatal(val message: String) : Error()

    @Serializer(Error::class)
    internal companion object : KSerializer<Error> {

        override fun serialize(encoder: Encoder, obj: Error) {
             // Write your own serialization logic, here's an example
            val json = when (obj) {
                is Forbidden -> JsonLiteral(403)
                is Unauthorized -> JsonLiteral(401)
                is Fatal -> JsonLiteral(obj.message)
            }
            encoder.asJsonOutput().encodeJson(json)
        }

        override fun deserialize(decoder: Decoder): Error {
            // Write your own deserialization logic, , here's an example
            val json = decoder.asJsonInput()
            val int = json.primitive.intOrNull

            if (int != null) {
                return when (int) {
                    401 -> Unauthorized
                    403 -> Forbidden
                    else -> throw Exception("Unhandled error")
                }
            }
            return Fatal(json.content)
        }
    }
}
```

**Comment by pauliusrum** [comment]
Your solution makes sense I will try to incorporate it into my code. But i'm still concerned about the issue when it throws an exception on object when you add annotations. If this is an error in serialization configuration it should happen at compile time not at runtime because if I remove the annotations the code runs fine.
```Kotlin
fun main() {
    val a = A // Throws java.lang.NoSuchFieldError: Companion
}

@Serializable
object A

@Serializer(forClass = A::class)
object ASerializer : KSerializer<A> {

    override val descriptor = SerialClassDescImpl("ASerializer")

    override fun serialize(encoder: Encoder, obj: A) = encoder.encodeString(obj::class.qualifiedName!!)

    override fun deserialize(decoder: Decoder): A = decoder.decodeString().run { A }
}

**Comment by q-litzler** [comment]
For that I will let a library maintainer answer you, as I am just an user like you.

**Comment by sandwwraith** [comment]
I think the main problem here is that compiler plugin does not have special support for `@Serializable` objects and tries to generate companion for them, which is forbidden and cause glitches. For now, it is better to use external serializer.

Anyway, I see the good use case for object serialization, but what output you are expecting? `"error": "Forbidden"`?

**Comment by pauliusrum** [comment]
> Anyway, I see the good use case for object serialization, but what output you are expecting? `"error": "Forbidden"`?

Yes that would be fine as long as the values differ one from the other. I need this because deserialization will happen in TypeScript so I need a different value for each object to be able to map the error structure.

**Comment by fvasco** [comment]
In the above example using `"error": "Forbidden"` looks too simplistic for me.
`Fatal` cannot be serialized as a String.

If unconsidered, I suggest to take a look to [Jackson Polymorphic Deserialization](https://github.com/FasterXML/jackson-docs/wiki/JacksonPolymorphicDeserialization)

```json
"error": { "class" : "Forbidden"}

"error": { "class" : "Fatal", "message": "Not found" }
```

**Comment by pauliusrum** [comment]
I used `PolymorphicSerializer`. This way it was easy for me to deserialize the data both in Kotlin and Typescript.
```Kotlin
{"payload":null,"error":["Error.Unauthorized",{}]}
{"payload":null,"error":["Error.Forbidden",{}]}
{"payload":null,"error":["Error.Fatal",{"message":"error message"}]}
```

**Comment by danielebartorilla** [comment]
@pauliusrum can you provide the full source code of your example using `PolymorphicSerializer`?

**Comment by pauliusrum** [comment]
> @pauliusrum can you provide the full source code of your example using `PolymorphicSerializer`?

```Kotlin
object ErrorUnauthorizedSerializer : KSerializer<Error.Unauthorized> {

    override val descriptor = SerialClassDescImpl(Error.Unauthorized::class.qualifiedName!!)

    override fun serialize(encoder: Encoder, obj: Error.Unauthorized) = encoder.encodeUnit()

    override fun deserialize(decoder: Decoder): Error.Unauthorized = decoder.decodeUnit().run { Error.Unauthorized }
}

object ErrorForbiddenSerializer : KSerializer<Error.Forbidden> {

    override val descriptor = SerialClassDescImpl(Error.Forbidden::class.qualifiedName!!)

    override fun serialize(encoder: Encoder, obj: Error.Forbidden) = encoder.encodeUnit()

    override fun deserialize(decoder: Decoder): Error.Forbidden = decoder.decodeUnit().run { Error.Forbidden }
}

sealed class Error {

    companion object {
        init {
            Json.install(SimpleModule(Unauthorized::class, ErrorUnauthorizedSerializer))
            Json.install(SimpleModule(Forbidden::class, ErrorForbiddenSerializer))
        }
    }

    object Unauthorized : Error()

    object Forbidden : Error()

    @Serializable
    data class Fatal(val message: String) : Error()
}

@Serializable
data class Envelope<T : Any>(val payload: T?, val error: Error?)

class A {

    @Test
    fun main() {
        val a = Json.stringify(Envelope.serializer(UnitSerializer), Envelope<Unit>(payload = null, error = Error.Forbidden))
        val b = Json.stringify(Envelope.serializer(UnitSerializer), Envelope<Unit>(payload = null, error = Error.Unauthorized))
        val c = Json.stringify(Envelope.serializer(UnitSerializer), Envelope<Unit>(payload = null, error = Error.Fatal("error message")))

        println(a)
        println(b)
        println(c)
    }
}
```

Running this code will produce:

```Kotlin
{"payload":null,"error":["tasker.rpc.Error.Forbidden",{}]}
{"payload":null,"error":["tasker.rpc.Error.Unauthorized",{}]}
{"payload":null,"error":["tasker.rpc.Error.Fatal",{"message":"error message"}]}
```

**Comment by pdvrieze** [comment]
Object serialization in any case is a very tricky topic (beyond the issues around the current codegen). It all starts with the concept that an object has a single (rather independent) existence. If you have some data structure that you want to serialize but that contains a reference to an object what should it store? Should it just store a reference, or should it store the data. And then when reading it back in, what does that mean. A reference is easy (works like an enum), but reading object state is harder as there is no sensible meaning on how to relate it to existing object state (deserializing an object cannot create it as it "always exists"). What when the deserializing has multiple conflicting data sets for the same object?

From my perspective the only safe way to serialize an object is to special case it if it is not merely a reference to its identity. Identity references have the same issue that polymorphism has in terms of cross-platform support. If you want really portable serialization you also don't want java fqns in your serialization.

**Comment by pauliusrum** [comment]
@pdvrieze I agree with what you are saying but this is a very early stage of the project so it will do for now. In the future I will have to change it to be more portable with a custom serializer for `sealed class Error`.

**Comment by sandwwraith** [comment]
`@Serializable object` is supported starting from Kotlin 1.3.60/kotlinx.serialization 0.14.0
