### ISSUE TITLE
Associate property with two types

### ISSUE THREAD

**Issue by webfrea-k** [Kotlin/kotlinx.serialization#403]
I have a JSON property which is `Object {}` if populated, and `List [] ` if empty. Is it possible to skip such property (or set it to null) in custom deserializer? I have a `deserialize` code which handles the object part, and now I need to handle the list part. If I just skip it by not calling `decoder.decode...()`, the next object throws error as it is not on the correct position of a source string.

As a workaround we have implemented `EmptyListDescriptor: SerialDescriptor` which overrides `kind` with `LIST`.

If the initial deserialization fails, we try to deserialize again with custom descriptor (emptyList) which works ok for now. 

Is there any other (better) way of achieving this?

Feature suggestion: Add actual `kind` to `Decoder` interface (to easily switch descriptors - without try-catch).

**Comment by zokabazoka** [comment]
this would be example of JSON in question:

```
{
  "test": {
    "first": "123",
    "second": 123
  }
}
```

and when empty:

```
{
  "test": []
}

```
in **deserialize** we now handle this with  **try catch** and in **catch** block we fallback to different descriptor. Ideally we would like to know what kind of JSON property are we planing to deserialize (JSON Object, JSON Array) and that would be a feature request 😃 because in our case we can't change the JSON due to the legacy reasons.

**Comment by raderio** [comment]
Can you please add an example of `class` to which to deserialize?
Because in Kotlin ca property can not have 2 types.

**Comment by webfrea-k** [comment]
@raderio , you are correct. There can only be 1 type associated with specific property in model class. Unfortunately, our JSON returns that property as {object} when the value exists, and as [array] when it is actually `null`. We would like to handle such cases in `deserialize` function without try-catching the JSON Format exception. We could do that if decoder in deserialize would know the actual `KIND` of object in the pipeline (next to the expected one).

**Comment by raderio** [comment]
I think you can add here https://github.com/Kotlin/kotlinx.serialization/issues/380 one more option
- Polymorphism by field type

**Comment by sandwwraith** [comment]
You still could try to use `JsonElement` and then determine if it is `JsonObject` or `JsonArray` – afair, it should work in this scenario

**Comment by webfrea-k** [comment]
Works like a charm! Thanks again @sandwwraith  :)
