### ISSUE TITLE
Deserialize object of key-value pairs

### ISSUE THREAD

**Issue by webfrea-k** [Kotlin/kotlinx.serialization#405]
JSONs that we consume are often structured as objects of key-value pairs.
```
"types": {
    "40": "Red flags",
    "45": "Green flags",
    "50": "Blue flags",
    "124": "Orange flags"
}
 ```
Number of items and keys are not known prior.

We would like to deserialize above example into `list` of key-value pairs e.g. `List<Pair(String, String)>`. 

Is this possible with current lib functionality?
Feature suggestion: add option to return the entire expecting object or list into `deserialize` method as string (with begin and end structure) where special cases like this can be handled manually.

**Comment by sandwwraith** [comment]
You can try to use `val types: JsonObject` in your data class. It is a map, but can be easily converted to list, I think.

**Comment by webfrea-k** [comment]
Great! It works just as expected. Thank you @sandwwraith
