### ISSUE TITLE
How to handle nullable fields

### ISSUE THREAD

**Issue by kastork** [Kotlin/kotlinx.serialization#41]
This is a question.

I want to parse the output of an API that is not under my control.  This API emits JSON that can contain the word `null` as the value of a field that might otherwise contain a string.  Example:

`{"description": null}`

or

`{"description": "Best dog in 6 counties"}`

How would one go about defining this field in the data class they wish to serialize/deserialize?

**Comment by sandwwraith** [comment]
As far as I remember, JSON parser supports null literals, so you can use `descroption: String?` in your data class, and it would contain `null` in the first example, and `"Best dog in 6 counties"` in the second

**Comment by kastork** [comment]
You're right, it does indeed seem to be working.
When I first tried to use nullable vals, I was getting an exception about `Any` type not being acceptable, but now I'm not.  I must have had some other problem.

Thanks for setting me straight
