### ISSUE TITLE
Add support for normalization

### ISSUE THREAD

**Issue by raderio** [Kotlin/kotlinx.serialization#412]
Add support for normalization on object creationn ot after creation.
For example `{ "email": "MyCompany@corp.COM" }` to normalize to `{ "email": "mycompany@corp.com" }`

**Comment by JakeWharton** [comment]
A normalization concept does not seem appropriate for this layer of abstraction. You can mix in normalizers using the pluggable serializer concept but they shouldn't be intrinsically supported by a generic serialization library.

**Comment by shanshin** [comment]
Closed as not planned

**Comment by sandwwraith** [comment]
Given that generated serializers execute all initializers, you can just write your normalization code in `init {}` block
