### ISSUE TITLE
Proguard config

### ISSUE THREAD

**Issue by klassm** [Kotlin/kotlinx.serialization#42]
Hi,
can you provide a proguard configuration for kotlinx.serialization? When running proguard over an Android application, the app will crash with
```kotlinx.serialization.SerializationException: Can't locate companion serializer for class class```
Thanks,
Matthias

**Comment by klassm** [comment]
Please note that 

```
-keep class de.my.package.** { *; }
-keep class de.my.package.*$* { *; }
-keepattributes *Annotation*
-keep class kotlin.reflect.** { *; }
-dontwarn kotlin.reflect.**
-keep class org.jetbrains.** { *; }
```
is not sufficient to make this work.

**Comment by sandwwraith** [comment]
You need to add `-keepattributes InnerClasses` to your config as well. I will see, if some of restrictions you provided can be weakened, and publish it to docs later

**Comment by klassm** [comment]
Even adding that attribute does not make it work - unfortunately, I still get the same exception.

**Comment by sandwwraith** [comment]
Strange. I have another idea: does `de.my.package` contains all serializable classes or they are located in subpackages too? In latter case `-keep class de.my.package.*$* { *; }` seems to be not working.

Anyway, in my experiments, I've manage to launch serialization with following config:
```proguard
-keepattributes *Annotation*, InnerClasses
-dontnote kotlinx.serialization.SerializationKt
-keep,includedescriptorclasses class com.yourcompany.yourpackage.**$$serializer { *; }
```

Also better to leave 
```proguard
-keep class kotlin.reflect.** { *; }
-dontwarn kotlin.reflect.**
-keep class org.jetbrains.** { *; }
```
as well, until the dependency on `kotlin-reflect` is removed

**Comment by klassm** [comment]
Thanks for your configuration options - however, it still does not work.

Actually, by now, I treat the opinion that Proguard is not the reason for the crashing application and the unfound serializer class. When looking into the generated dex file, I can actually see all those Companiion and $$serializer classes. They are not gone, not even obfuscated.

My current guess is that this has something to do with classloading issues in multidex applications (even if those classes are located in the primary dex file). However, I have no idea how to continue to look for the actual reason.

I guess I'll have to stick with Jackson for now and migrate to the new serialization library when kotlin-reflect has been removed.

BTW: Why do you need to locate those serializer classes via reflection? At compile time the chain of serializer for decoding and assembling objects should be already clear, shouldn't it? Couldn't you generate some code at compile time (like Dagger2) to do the mapping then? This would even solve those Proguard problems, as those classes would be used at compile time.
I am sure this is not that simple, but ... :-)

**Comment by sandwwraith** [comment]
You're definitely right, that's how it works - compiler plugin generates code for serializers that are known in compile time.

The sole purpose of presence of kotlin-reflect here is to locate serializer for the root of hierarchy. If you have KClass, or TypeToken, or something else, it's not possible to determine at compile time which serializer should be called, and so we find it via reflection. If you take a look at source code, you'll find that reflection is only used in methods like `KClass.serializer()` and `findSerializerByTypeToken(..)`, so if you're not using them and obtaining serializers directly via calling `.serializer()` on companions, there should be no problems with kotlin-reflect. Also, there is a fallback to Java Reflection. I'm not very familiar with multidex classloading, so it would be appreciated if you give me a clue what may go wrong with it.

**Comment by klassm** [comment]
@sandwwraith 
I finally found the issue - and it has nothing to do with proguard or anything.

The classes I use for JSON deserialization also have to implement Serializable, as I did not yet get rid of object serialization storage within my application. In effect, this means that the class has two imports to serialiable:

```
import kotlinx.serialization.SerialName
import java.io.Serializable

@kotlinx.serialization.Serializable
data class MyClass(...)
) : Serializable
```
Unfortunately, kotlinx.serialization does not seem to handle fully qualified imports of kotlinx.serialization.Serilizable. To make it work, I just swapped Kotlin Serializable to be imported and java.io.Serializable to a fully qualified import - and it works. Whatever, this is really strange behaviour. However, that way it works.

Now I got one more question: Android Studio always shows the serializer object as compile error (it compiles, but it is shown as red) - do I have to include more source folders?

```JSON.parse(MyClass.serializer(), jsonAsString)```

And one last note: As you told me about reflection only being a fallback, I tried to remove kotlin-reflect as transitive dependency of kotlinx-serialization-runtime. This just works - thanks for the note!

... and thank you for all your work concerning this library!
Matthias

**Comment by sandwwraith** [comment]
Indeed, very strange behaviour. If you saw that `$$serializer` classes in dex file, it means that annotation was recognised by plugin. I didn't manage to reproduce it on a new project - both qualified and short annotation work with conjunction with `java.io.Serializable`. If it's not difficult for you, can you provide some small project, where this problem reproduces?

About your question: Code is shown as red, because usual AS Kotlin plugin don't know about such synthetic objects, and there are no source files for it - plugin emits bytecode directly. To improve your experience inside an IDE, you can follow [this](https://github.com/kotlin/kotlinx.serialization#working-in-intellij-idea) instructions.

Yes, it can work without reflect, but if you try to use functions I mentioned above (like `findSerializerBy...`), you'll get a runtime error, so remember it's kinda dangerous

**Comment by sandwwraith** [comment]
I think it's now reflected in the readme
