### ISSUE TITLE
org.gradle.api.tasks.SourceSetContainer example-native

### ISSUE THREAD

**Issue by anonym24** [Kotlin/kotlinx.serialization#420]
I can't compile `kotlinx.serialization-master\example-native` in IntelliJ IDEA:

```
Unable to load class 'org.gradle.api.tasks.SourceSetContainer'.
Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)

The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)

Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

```

I tried to press "Re-download dependencies and sync project (requires network)" and "Stop Gradle build processes (requires restart)" but nothing of that worked

```
IntelliJ IDEA 2019.1 (Community Edition)
Build #IC-191.6183.87, built on March 27, 2019
JRE: 1.8.0_202-release-1483-b39 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```

**Comment by sandwwraith** [comment]
It seems that it is idea problem: https://youtrack.jetbrains.com/issue/IDEA-210131

I've updated today and also faced it :) So, unfortunately, this project can be opened only in 2018.3 for now

**Comment by anonym24** [comment]
@sandwwraith I installed 2018.3 but now I have the next issue:

![image](https://user-images.githubusercontent.com/8851301/55380749-c6de7a80-5529-11e9-84bb-4cd05378a64c.png)

**Comment by sandwwraith** [comment]
See https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/building.md :
 
> To open project in Intellij IDEA, first run ./gradlew generateTestProto from console. You may also need to mark runtime/build/generated/source/proto/test/java as 'Generated source root' to build project without delegating a build to Gradle. This requires Kotlin 1.3.11 and higher.

I'm not fully understanding what you're trying to achieve, open the sample project or open the project with the runtime library itself? In case of first, you need to import project from `example-***/build.gradle` file, not the root one. Please also take a note that `example-native` can't be currently imported as it uses old native plugin without IDE support. However, JS and JVM samples should be fine. There is also an `example-multiplatform` sample in the dev branch.

**Comment by anonym24** [comment]
@sandwwraith so it's not possible to open `example-native` in IDE anyway?

**Comment by anonym24** [comment]
but it's good that `/gradlew build` inside `example-native`  works fine (already tested .exe file in Windows)

**Comment by sandwwraith** [comment]
Yes, it is a working project which can be built, but there's no ide support for `kotlin-platform-native` Gradle plugin.
