### ISSUE TITLE
1.3.30 plugin breaks Android Kapt with generic classes

### ISSUE THREAD

**Issue by jcraane** [Kotlin/kotlinx.serialization#429]
We have a Kotlin native project and upgraded to Kotlin 1.3.30 (the version we used before was 1.3.21). The new version gives a compiler error with the following code:

@Serializable
data class Box<T>(val t: T) 

The folllowing error is produced:
error: non-static type variable T cannot be referenced from a static context
    com.eneco.enecoapp.common.persistence.cache.Box<T> self, @org.jetbrains.annotations.NotNull()

I tried adding a custom serializer/deserializer but the same error is thrown. The generated java code (which gives the error, looks like this):

public static final void write$Self(@org.jetbrains.annotations.NotNull()
    com.eneco.enecoapp.common.persistence.cache.Box<T> self, @org.jetbrains.annotations.NotNull()
    kotlinx.serialization.CompositeEncoder output, @org.jetbrains.annotations.NotNull()
    kotlinx.serialization.SerialDescriptor serialDesc, @org.jetbrains.annotations.NotNull()
    kotlinx.serialization.KSerializer<T> typeSerial1) {
    }

If you need any more information please let me know. Thanks!

**Comment by sandwwraith** [comment]
Kotlin/Native currently does not maintain binary compatibility between releases, and so serialization plugin does. A compatible version of the runtime library will be released in the next hours.

By the way, this problem does not look like a Native one, it is JVM bytecode. Can you share more details about your project? Is `Box` class in a common module or in platform one? Do you use `0.10.0` version of the library or older?

**Comment by jcraane** [comment]
The Box class resides in the Android module of the Kotlin/Native project which also has the plugin kotlinx-serialization applied. We use version 0.10.0 of the serialization library. Our project structure is as follows:

- root
  - android (The android module)
     - app (The Android app module which references project:common)
  - common (our shared code)
  - commonTest (tests for our shared code)
  - ios (Our IOS project which references common)
  - builcSrc (our build utilities)

**Comment by sandwwraith** [comment]
Can you try with `0.11.0-1.3.30-eap-125`?

**Comment by sandwwraith** [comment]
Do you have a build log for this? Does this error occur during `compileKotlin` phase or `kapt` phase?

**Comment by jcraane** [comment]
I tested with version 0.11.0-1.3.30-eap-125  but it gives the same error. I have added the (partial) output of the Gradle build logs (change the actual app name with myapp).

`
> Task :android:app:checkFlavor_myappStage_accDebugManifest
> Task :android:app:createFlavor_myappStage_accDebugCompatibleScreenManifests FROM-CACHE
> Task :android:app:mainApkListPersistenceFlavor_myappStage_accDebug
> Task :android:app:processFlavor_myappStage_accDebugManifest FROM-CACHE
> Task :android:app:fabricGenerateResourcesFlavor_myappStage_accDebug
> Task :android:app:generateFlavor_myappStage_accDebugBuildConfig FROM-CACHE
> Task :android:app:prepareLintJar UP-TO-DATE
> Task :android:app:generateFlavor_myappStage_accDebugSources
> Task :android:app:dataBindingExportBuildInfoFlavor_myappStage_accDebug
> Task :android:app:dataBindingMergeDependencyArtifactsFlavor_myappStage_accDebug FROM-CACHE
> Task :android:app:generateFlavor_myappStage_accDebugResValues FROM-CACHE
> Task :android:app:generateFlavor_myappStage_accDebugResources UP-TO-DATE
> Task :android:app:mergeFlavor_myappStage_accDebugResources
> Task :android:app:transformDataBindingBaseClassLogWithDataBindingMergeGenClassesForFlavor_myappStage_accDebug
> Task :android:app:dataBindingGenBaseClassesFlavor_myappStage_accDebug
> Task :android:app:dataBindingExportFeaturePackageIdsFlavor_myappStage_accDebug FROM-CACHE
> Task :android:app:processFlavor_myappStage_accDebugResources
> Task :android:app:kaptGenerateStubsFlavor_myappStage_accDebugKotlin FROM-CACHE

> Task :android:app:kaptFlavor_myappStage_accDebugKotlin FAILED
e: /Users/jamiecraane/develop/AndroidStudio/myapp/myapp-app/android/app/build/tmp/kapt3/stubs/flavor_myappStage_accDebug/com/myapp/myappapp/common/persistence/cache/Box.java:26: error: non-static type variable T cannot be referenced from a static context
    com.myapp.myappapp.common.persistence.cache.Box<T> self, @org.jetbrains.annotations.NotNull()
`

**Comment by sandwwraith** [comment]
Oh, this seems to be a kapt problem which occurs only on android projects... I'll try to fix this in a patch update.

**Comment by jcraane** [comment]
Ok. Thanks for the feedback!

**Comment by sandwwraith** [comment]
This should be fixed in Kotlin 1.3.31
