### ISSUE TITLE
Default values for optional fields serialized even when encodeDefaults set to false

### ISSUE THREAD

**Issue by sav007** [Kotlin/kotlinx.serialization#431]
After upgrading to the latest version `0.11.0` `@Optional` annotation is deprecated.

The doc says:
> All properties with default values are considered optional now

But it seems that without this annotation the flag `encodeDefaults=false` in `JsonConfiguration` is ignored for optionals fields without deprecated `@Optional` annotation, and default values (such as `null` for instance) serialized to the result json.

**Comment by sandwwraith** [comment]
Can you post more details about the problem, please (code sample, platform, versions, ...)? I can't reproduce it.

**Comment by sav007** [comment]
Sure, here is the sample:
```
val json = Json(
            JsonConfiguration(
                encodeDefaults = false,
                strictMode = false
            )
        ).stringify(
            AppliedDiscount.serializer(), AppliedDiscount(
                amount = "0.00",
                title = null,
                description = "Description"
            )
        )
```

For `AppliedDiscount` with deprecate `@Optional` annotation:
```
@Serializable
internal data class AppliedDiscount(
    val amount: String,
    @Optional
    val title: String? = null,
    val description: String
)
```

The emitted json string will be:
```
{"amount":"0.00","description":"Description"}
```

For `AppliedDiscount` without `@Optional`:
```
@Serializable
internal data class AppliedDiscount(
    val amount: String,
    val title: String? = null,
    val description: String
)
```

The output will be:
```
{"amount":"0.00","title":null,"description":"Description"}
```

**Comment by sandwwraith** [comment]
Which version of Kotlin compiler do you use? Make sure it is `1.3.30`. Previous versions, indeed, still need the annotation.

**Comment by sav007** [comment]
Agh, I see. Yeah I was using 1.3.21, so it depends on the version of kotlin compiler TIL. Thanks!

**Comment by marlonlom** [comment]
how can i handle optional fields from json using retrofit, since @Optional  is deprecated?

**Comment by pdvrieze** [comment]
@marlonlom There is an opposite annotation: `@Required` that is able to specify that a type must be present even if it is optional due to having a default value.

**Comment by sandwwraith** [comment]
@marlonlom all Kotlin properties with default values are automatically optional now

**Comment by marlonlom** [comment]
@sandwwraith great! :)
