### ISSUE TITLE
Update for Gradle Metadata 1.0

### ISSUE THREAD

**Issue by benasher44** [Kotlin/kotlinx.serialization#433]
Now that metadata is stable, [some libraries](https://github.com/square/sqldelight/releases/tag/1.1.3) have begun releasing updates with 1.0 support. It’d be great to do a small release to update metadata to the new stable format, to ease upgrading for  those of us using kotlinx libs mixed with others.

**Comment by sandwwraith** [comment]
As far as I know, 1.0 metadata is almost compatible with 0.4 one, and Gradle 5.1+ should be able to read it. Do you face any issues with that?

We are going to update it anyway, but it shouldn't be a blocker.

**Comment by benasher44** [comment]
Sounds great! Even though the format versions might be close to compatible, Gradle won’t allow you to mix installing dependencies on different versions (at least prior to 1.0). That’s the main issue with that. I’m not sure about Gradle 5.1. I believe Gradle 5.3.x is required for 1.0 metadata.

**Comment by benasher44** [comment]
Turns out you are correct! I asked, and [apparently it will work until it doesn't (no guarantees)](https://twitter.com/CedricChampeau/status/1118044214061932544). So, I agree this is more of a nice-to-have (but sooner in case someone finds whatever combination of 1.0 and < 1.0 metadata that breaks). In my current setup, I'm able to install the latest SQLDelight (1.0) with kotlinx.serialization (0.4).

**Comment by sandwwraith** [comment]
We also have a concern that Google recommends using Gradle 4.10 for the latest Gradle Android plugin (3.3.x) and users may experience issues in Android Studio after updating to Gradle 5.x.

**Comment by benasher44** [comment]
That is a valid concern. I’m looking at the plugin release notes though, and it does have specific notes on what to expect using it with Gradle 5: https://developer.android.com/studio/releases/gradle-plugin. This leads me to believe it is compatible / tested with Gradle 5, just not totally free of problems (recommending at least 4.10, but doesn’t seem to discourage 5?)?

**Comment by JakeWharton** [comment]
As of 20 minutes ago, AGP 3.4 is the latest stable which requires Gradle 5.1

**Comment by sandwwraith** [comment]
That's great, but 1.0 metadata was released only in Gradle 5.3

**Comment by JakeWharton** [comment]
But your concern was that users would have problems with 5.x. AGP 3.4.0
works fine with 5.1, 5.2, 5.3, and 5.4.

**Comment by yshrsmz** [comment]
FYI Android Studio 3.5 beta 1 is released and it requires Gradle 5.4.
