### ISSUE TITLE
Serialization support does not "work out of the box"

### ISSUE THREAD

**Issue by bolinfest** [Kotlin/kotlinx.serialization#445]
According to the README:

> Serialization support should work out of the box

I have an up-to-date Kotlin plugin and compiler toolchain. In IntelliJ, I created a new Kotlin project with a single file (I have no Maven or Gradle file):

```
package com.example

import kotlinx.serialization.Serializable
import kotlinx.serialization.list
import kotlinx.serialization.json.Json

@Serializable
data class Foo(val foo: String)

fun yay() {
    val result = Json.parse(Foo.serializer().list, """["foo", "bar"]""")
    println(result)
}
```

At first, nothing compiles. I downloaded http://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-serialization-runtime/0.11.0/:kotlinx-serialization-runtime-0.11.0.jar and added it to the classpath.

Now the file mostly compiles, except for:

> Unresolved reference: serializer

I suspect the problem is still along the lines of what I have already reported: https://youtrack.jetbrains.com/issue/KT-30998.

That said, there is nothing in the README that claims that your IntelliJ project must build with either Gradle or Maven. It sounds like 1.3.30 should have made this unnecessary, but that does not seem to be the case.

**Comment by sandwwraith** [comment]
Yes, sorry for misleading. As I said,

> Serialization plugin is bundled into Kotlin plugin starting from 1.3.0, so you don't have to install it manually. However, the plugin enables only after importing correct project build settings from a build system.
