### ISSUE TITLE
Json.stringify: how configure encoding.

### ISSUE THREAD

**Issue by MairwunNx** [Kotlin/kotlinx.serialization#447]
```kotlin
val telemetryData = Json.stringify(
            TelemetryData.serializer(),
            TelemetryData(
                "Русский язык ТЕСТ", // ← this have problem with encoding
                LocalDateTime.now().toString(),
                project.name,
                TemporaryData.sourcesDirectory,
                TemporaryData.editedFileDataList
            )
        )
```

after `println(telemetryData)` i have `{"user":"??????? ???? ????"...`

| library name  | version |
| ------------- | ------------- |
| kotlinx serialization runtime  | `0.11.0`  |
| kotlin serialization  | `1.3.30`  |
| kotlin version  | `1.3.30`  |

**Comment by sandwwraith** [comment]
I doubt that this is a library problem, it's rather your console/environment printing them incorrectly. Printing to file should help.

**Comment by MairwunNx** [comment]
@sandwwraith no. It library problem, I send json string to server and save string to file, I see ??? After stringify. Before ok.

**Comment by sandwwraith** [comment]
@MairwunNx My local tests are running fine. Which platform (JVM/JS/Native) do you use?

**Comment by MairwunNx** [comment]
@sandwwraith JVM 1.8

**Comment by sandwwraith** [comment]
Can you verify the issue by running a local test, without sending something over network?

**Comment by MairwunNx** [comment]
It incorrectly encoding caused "???", but it also send to server \ save to file with "???". but debugger show good result as need. 

How do I solve the problem - I will describe the solution here. It would be not cultural to leave without leaving an answer :)

Thanks, please mark it issue as `false problem`.
