### ISSUE TITLE
Kotlin Multiplatform kotlin gradle support/update readme

### ISSUE THREAD

**Issue by Reedyuk** [Kotlin/kotlinx.serialization#455]
**Describe the bug**
I am finding it very difficult to get my current kotlin multiplatform project using kotlinx serialization to work with the new kotlin gradle syntax.
I currently have a working groovy gradle file but it seems to not work correctly using the kotlin gradle file.

**To Reproduce**
In the plugins section of kotlin gradle:
plugins {
    maven-publish
    kotlin("multiplatform") version "1.3.30"
    id("kotlinx-serialization") version "1.3.30"
}

And then in the kotlin section
kotlin {
    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core-common:1.1.1")
                implementation("org.jetbrains.kotlin:kotlin-stdlib-common")
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:1.3.30")
            }
        }
        iosArm64().compilations["main"].defaultSourceSet {
            dependencies {
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-runtime-native:1.3.30")
            }
        }
    }
}

The error returned by gradle:
"Could not find org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:1.3.30."

**Expected behavior**
The readme doesn't show how to include serialization runtime in the kotlin gradle file. 

**Environment**
 - Kotlin version: 1.3.30
 - Kotlin platforms: ios, android, multiplatform
 - Gradle version: 5.3.1

**Comment by sandwwraith** [comment]
You need to use `1.3.30` version only for `kotlinx-serialization` `plugin`, for `runtime` part use the current version of the library (latest is 0.11.0)
