### ISSUE TITLE
Didn't find class "Color$$serializer"

### ISSUE THREAD

**Issue by nshcat** [Kotlin/kotlinx.serialization#458]
I am using this library on **Android** and I have come across a weird runtime exception when creating my own serializers:

```
2019-05-18 01:59:24.504 22679-22679/com.bla E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.bla.android.ascii.Color$$serializer" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file 
```

My class code:

```
@Serializable
data class Color(var r: Int, var g: Int, var b: Int)
{
    @Serializer(forClass = Color::class)
    companion object : KSerializer<Color>
    {
        override val descriptor: SerialDescriptor =
            StringDescriptor.withName("Color")

        override fun serialize(output: Encoder, obj: Color)
        {
            /* do stuff */
        }

        override fun deserialize(input: Decoder): Color
        {
           /* do stuff */
        }

    }
}
```
Did I do something wrong? Thanks in advance!

**Comment by sandwwraith** [comment]
Hm, if you have custom serializer inside a companion object, `$serializer` class is not generated. Probably you try to access it from somewhere manually? E.g. `Color::class.serializer()` will try to find it via reflection.

**Comment by nshcat** [comment]
Thanks for your answer. I never directly try to serialize the Color class, I am using it as part of other classes like this:

I have a data class:

```
@Serializable
data class Test(val clr: Color)
```

And I deserialize it this way:

```
val result = Json.parse(Test.serializer(), /*...*/)
```

Is this wrong?

**Comment by sandwwraith** [comment]
No, it should be OK. Does error disappear if you remove custom serializer for Color?

**Comment by nshcat** [comment]
Okay error disappears if I put it outside and do this:

```
data class Test(@Serializable(with=ColorSerializer::class)  val clr: Color)
```

Otherwise same error. Very weird. It works now.

**Comment by sandwwraith** [comment]
Probably error has gone after `clean build`?

**Comment by nshcat** [comment]
I did reverse my changes back to the serializer being a companion object inside the `Color` class, same error even with `clean build`. Same code works on normal desktop project. Only Android has problems.

But having external serializer works and I guess I will use that. Thank you for replying

**Comment by MariusVolkhart** [comment]
I was able to reproduce this. In my case, removing the `@Serializable` annotation from the data class and only keeping the `@Serializer` on the companion object made the error go away and my companion object serialization logic was used as expected.

I'm on runtime `0.11.+` and on plugin `1.3.31`
