### ISSUE TITLE
Unqouted should not cover string-values

### ISSUE THREAD

**Issue by TorRanfelt** [Kotlin/kotlinx.serialization#463]
It is possible to remove quotes via JsonConfiguration's unquoted=true.

However, normally (or rather I have not encountered anything else) this would only mean the field names and not the string values.
For example in Jackson it is only possible to unquote field names: JsonParser.Feature.ALLOW_UNQUOTED_FIELD_NAMES

Is it possible to either sync up the meaning of unqouted or introduce a third option?

**Comment by qwwdfsad** [comment]
During 1.0 API stabilization, we've decided to remove unquoted mode from JSON
