### ISSUE TITLE
Json "wrapper object" support

### ISSUE THREAD

**Issue by jimirocks** [Kotlin/kotlinx.serialization#468]
Is there an easy to use syntax to configure `@Serializable` wrapper object similar to jacksons`
```
@JsonTypeName("someName")
@JsonTypeInfo(include = JsonTypeInfo.As.WRAPPER_OBJECT, use = JsonTypeInfo.Id.NAME)
```

in order to produce read jsons like 
```
{ "someName": {...}}
```
There are many APIs in the wild using this pattern. I know I could achieve this using another "wrapper" class, but that's too verbose.

May be the existing `@SerialName` annotation with some some wrapping indication could be used for that?

**Comment by jimirocks** [comment]
Well here is the code for wrapping object serializer, the ugly thing on that is that I need to explicitly write the inner Serializer instead of let it have generated.

```kotlin

@Serializer(forClass = WrappedObject::class)
objectWrappedObjectSerializer: KSerializer<WrappedObject> {

    private val innerSerializer = object : KSerializer<WrappedObject> {
        override val descriptor: SerialDescriptor = object : SerialClassDescImpl("WrappedObjectInner") {
            init {
                addElement("test")
            }
        }

        override fun deserialize(decoder: Decoder): WrappedObject {
            TODO("not implemented")
        }

        override fun serialize(encoder: Encoder, obj: WrappedObject) {
            encoder.beginStructure(descriptor).apply {
                encodeStringElement(descriptor, 0, obj.test)
                endStructure(descriptor)
            }
        }

    }

    override val descriptor: SerialDescriptor = object : SerialClassDescImpl("WrappedObject") {
        init {
            addElement("someName")
        }
    }

    override fun serialize(encoder: Encoder, obj: WrappedObject) {
        val compositeEncoder = encoder.beginStructure(descriptor)
        compositeEncoder.encodeSerializableElement(descriptor, 0, innerSerializer, obj)
        compositeEncoder.endStructure(descriptor)
    }
}

```

**Comment by micheljung** [comment]
@sandwwraith I looked through the documentation but failed to find a strategy that solves this problem - could you please point me to it?

**Comment by sandwwraith** [comment]
@micheljung There's no built-in strategy for that, but I believe it can be easy implemented using [skeleton classes for Json transformations](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json.md#json-transformations)

**Comment by jimirocks** [comment]
@sandwwraith Got into this after few years. I am sorry but I don't see any possibility to easily deserialize or serialize like it's possible with Jackson wrapped object concept. Would be nice if you can provide some example.

Suppose you want to deserialize
`{ "someName": { "someProp": "..."}}`

into

```
@Serializable
data class SomeName(val someProp: String)
```
