### ISSUE TITLE
Json.parse throws MissingFieldException

### ISSUE THREAD

**Issue by PaulWoitaschek** [Kotlin/kotlinx.serialization#469]
The kdoc of `Json.parse` states:

    /**
     * Deserializes given json [string] into a corresponding object of type [T] using provided [deserializer].
     * @throws [JsonException] subclass in case of serialization error.
     */

However it doesn't throw a `JsonException` in case of a missing field, but a `MissingFieldException`

    kotlinx.serialization.MissingFieldException: Field 'minimumVersion' is required, but it was missing

Using kotlin 1.3.31 and 0.11.0 runtime

**Comment by PaulWoitaschek** [comment]
sscce:

```kotlin
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonException

@Serializable
data class Data(val a: Int)

fun main() {
  try {
    Json.parse(Data.serializer(), "{}")
  } catch (ignored: JsonException) {
  }
}
```

**Comment by QiBaobin** [comment]
You might need add default value to a when it will be missing in the json text.

**Comment by PaulWoitaschek** [comment]
> You might need add default value to a when it will be missing in the json text.

That's not the point. What this issue is about is that the wrong type of exception is thrown (or the documentation is wrong).

**Comment by sandwwraith** [comment]
Yeah, documentation needs fix. Because generated serializers are format-agnostic, effectively any format can throw generic `SerializationException` if the problem is detected on the serializer side.
