### ISSUE TITLE
@UseSerializers ignores nullable serializer

### ISSUE THREAD

**Issue by SpaceBison** [Kotlin/kotlinx.serialization#473]
When using `UseSerializers` with a serializer of a nullable type, the build fails. 

> Cause: Back-end (JVM) Internal error: Serializer for element of type Date has not been found.

The same serializer works when specified explicitly on a property using `@Serializable(with=...)`.

**To Reproduce**

```kotlin
@file:UseSerializers(NullableDateSerializer::class)

/* ... */

@Serializable
class Foo(val nullable: Date?)

/* ... */

@Serializer(forClass = Date::class)
class NullableDateSerializer : KSerializer<Date?> {
    /* ... */
}
```

**Expected behavior**

The specified serializer should be used for both nullable and non-null values.

**Environment**
 - Kotlin version: 1.1
 - Library version: 0.11.0
 - Kotlin platforms: JVM
 - Gradle version: 5.1.1
 - IDE version (if bug is related to the IDE) Android Studio 3.4.1

**Comment by BoxResin** [comment]
Same problem. It occurs after update *kotlinx.serialization* dependency to `v0.11.0` from `v0.10.0`.

**Comment by sandwwraith** [comment]
Why do you want exactly nullable serializer for Date? Regular `KSerializer<Date>` would work fine with nullable fields, the compiler plugin handles this.

**Comment by pdvrieze** [comment]
Semantically a `KSerializer` that has a nullable parameter type could map certain values to null. For example invalid values. I'm not sure that it is a good idea to do this, but there may be value to it.

**Comment by SpaceBison** [comment]
I'm have a bad API that sometimes returns empty strings for some data types (dates, URLs) instead of nulls. `KSerializer<Date>` won't work form, because it won't let me return `null` from `deserialize()` or handle null values in `serialize()`.

**Comment by edenman** [comment]
Related: https://github.com/Kotlin/kotlinx.serialization/issues/984
