### ISSUE TITLE
Is there any kotlin class generator based on .proto file available?

### ISSUE THREAD

**Issue by acc110789** [Kotlin/kotlinx.serialization#477]
just as title

**Comment by qwwdfsad** [comment]
There isn't any and we have no plans to add it in the nearest future.

This project has a purpose drastically different from the Protobuf generation: **Kotlin-first** data model that is format-agnostic and can be shared between all the platforms Kotlin supports.
Kotlin classes are the core of the data model, not the formats or schemas.

Protobuf inverses this principle: `.proto` file is the core of the data model and every "backend" (language, service, w/e) decides exactly to process it complying the given schema.

What we have in mind is generating `.proto` files from the given serializable Kotlin class, so it's possible to share (Kotlin-first) schema with other languages if there is need for.

**Comment by mikezliu** [comment]
Any idea when we will be able to generate .proto from kotlin files? I'm working on a project that has a front-end (vue), iOS, and we only want to keep one source of truth for proto files, which currently seems like we must use .proto files rather the kotlin data classes.

**Comment by qwwdfsad** [comment]
Probably around 1.1.0, probably the end of this year

**Comment by Marlinski** [comment]
Hi, any update about this issue ?

**Comment by qwwdfsad** [comment]
We have a prototype of .proto file generator that is aiming for the next release: #1255

We do not plan to implement `.proto` -> Kotlin conversion tho, for that purpose, I'd recommend using third-party solutions such as https://github.com/streem/pbandk

**Comment by Marlinski** [comment]
I am actually interested in having .proto file generated from my @Serializable data class. This is because I was using serialization-protobuf library but then those data class needed to be sent over the wire to a backend in golang and I unfortunately had to redo all my classes the old way instead to make it work (with .proto and protobuf-lite).

Happy to see the generator for the next release!

**Comment by Dogacel** [comment]
Hi, I am actually working on a project to auto-generate kotlin classes from `.proto` that are `@Serializable`. It is a very new project and I am waiting for your feedbacks and contributions 🙏 

On the way, I have realized several bugs and missing features on `kotlinx.serialization` part as well. I am hoping we can leverage each other's code quality while I am working on this project by fixing bugs and implementing missing features.

https://github.com/Dogacel/kotlinx-protobuf-gen
