### ISSUE TITLE
Obtaining serializer from KClass is not available on native due to the lack of reflection

### ISSUE THREAD

**Issue by alan-camilo** [Kotlin/kotlinx.serialization#479]
**Description**
I'm using Kotlinx serialization library in a multiplatform library for iOS and Android to share the code for HTTP requests. But I have this message when I'm using my request function on iOS, what is the workaround ?
**kotlin.NotImplementedError: An operation is not implemented: Obtaining serializer from KClass is not available on native due to the lack of reflection. Use .serializer() directly on serializable class.**

**To Reproduce**
This is the function I wrote 
```kotlin
@ImplicitReflectionSerializer
private suspend fun authenticationRequest(email: String, password: String): Either<ErrorMessage, Authentication> {
    return try {
        val response: Authentication = client.post {
            url("${Constants.API_URL}/security/login")
            body = jsonSerializer.write(LoginType(email, password))
        }
         Either.Right(response)
    } catch (e: ResponseException) {
        val message = Json.parse<ErrorMessage>(e.response.content.readUTF8Line() ?: "").apply {
            codeHttp = e.response.status.value
            reason = e.response.status.description
        }
        Either.Left(message)
    }
}
```

**Environment**
 - Kotlin version: 1.3.31
 - Library version: 0.11.0
 - Kotlin platforms: iOS and Android
 - Gradle version: 5.1.1

**Comment by sandwwraith** [comment]
Well, have you tried

>  Use .serializer() directly on serializable class.

?

(`Json.parse(ErrorMessage.serializer(), e.response.content.readUTF8Line())`)

**Comment by alan-camilo** [comment]
Ok thank you for your response. I did not understood the message at first glance but it's clearer. For the record, I now also use the setMapper function when initialising my KotlinxSerializer 
```kotlin
KotlinxSerializer(Json.nonstrict).apply {
        setMapper(Foo::class, Foo.serializer())
```
