### ISSUE TITLE
Guava and kotlinx.immutables collections prefab serializers

### ISSUE THREAD

**Issue by cgruber** [Kotlin/kotlinx.serialization#48]
Not sure what the best way to arrange artifacts for this, but it would be very handy to have prefab seralizers for Guava collections and kotlinx.immutables.  For kotlinx.immutables, one could maybe do that in the immutables project itself, but for Guava, it would be very nice to have kotlinx recognize those and pull in appropriate serializers.

**Comment by sandwwraith** [comment]
Closing as part of #1931
