### ISSUE TITLE
Current `dev` incorrectly ship jvm stdlib in common runtime

### ISSUE THREAD

**Issue by Prototik** [Kotlin/kotlinx.serialization#481]
45aa7c7ab97f25f205408b46a7069886408bce6b brings jvm stdlib in common runtime scope, should be `kotlin-stdlib-common` here:

https://github.com/Kotlin/kotlinx.serialization/blob/c846636093165dc2c748cdfca9afdb9b6cab6655/runtime/build.gradle#L74

**Comment by sandwwraith** [comment]
Indeed, thanks!
