### ISSUE TITLE
Serializer classes result in swift warnings (Kotlin native)

### ISSUE THREAD

**Issue by NilsLattek** [Kotlin/kotlinx.serialization#483]
**Describe the bug**
When creating a class in a Kotlin native project with the `Serializable` annotation it will produce a warning in the generated Objective-C code.
When having lots of these classes it will clutter the Xcode project with many warnings, making it difficult the see warnings from the main project.

It does not seem to cause issues when running the app, but as a best practice it would be nice to avoid those warnings.

**To Reproduce**
```kotlin
@Serializable
data class UpdateNoticeResponse(
    val result: String
)
```

**Expected behavior**
When using this code in a Swift project the second line 
```
__attribute__((objc_subclassing_restricted))
__attribute__((swift_name("UpdateNoticeResponse.$serializer")))
@interface SharedCodeUpdateNoticeResponse$serializer : KotlinBase <SharedCodeKotlinx_serialization_runtime_nativeGeneratedSerializer>
// ...
```
generates the following warning `'swift_name' attribute has invalid identifier for base name`.
My guess is that the dollar sign is not accepted as a swift name character.

**Environment**
 - Kotlin version: 1.3.31
 - Library version: 0.11.0
 - Kotlin platforms: JVM & Native
 - Gradle version: 5.4.1
 - IDE version: Xcode 10.2.1

**Comment by SvyatoslavScherbina** [comment]
See https://github.com/JetBrains/kotlin-native/issues/3094#issuecomment-506650648

**Comment by NilsLattek** [comment]
> See [JetBrains/kotlin-native#3094 (comment)](https://github.com/JetBrains/kotlin-native/issues/3094#issuecomment-506650648)

Fix mentioned in linked ticket, so I am closing this one.
