### ISSUE TITLE
The serialization of lambda expressions

### ISSUE THREAD

**Issue by Drjacky** [Kotlin/kotlinx.serialization#484]
One of Java 8 features that [Android doesn't support](https://developer.android.com/studio/write/java8-support) it is the serialization of lambda expressions.

I want to know can we do this with the help of this library?
If no, is there any plan to add this feature?

**Comment by pdvrieze** [comment]
While Kotlin lambda's should support serialization when created as serializable this is brittle. It is not supported by this library (yet). Lambda's are not generated as serializable. It could be implemented, but it should be implemented in the compiler plugin. It would require the function signature to be specified with the serializable annotation and then the lambda containing class to actually have the right serialization methods.

A significant challenge here is the security of lambda function deserialization. Effectively the way you would use serialized lamdas is by reflection. All the issues of reflective deserialization hold here as well. In addition, lambda class name generation is not quite stable which makes serialization even more fragile.

**Comment by sandwwraith** [comment]
We don't have it on the roadmap because we don't see much use cases for serializing lambdas. Unless you have a big distributed cluster framework (like Spark), you probably ain't gonna need this feature.

However, we can consider it when we collect more use cases. Why, for example, you need serializable lambdas on Android?

**Comment by Drjacky** [comment]
@sandwwraith Yes, for example, that, the Android.

**Comment by rnett** [comment]
I have a use case for serializing closures: storing/caching side effects from method execution.  I want something like:
```kotlin
@Memoize
fun myFun(file: File){
  sideEffect{ file.writeText("Hello World") }
}
```
where I would end up caching the lambda passed to `sideEffect`

**Comment by sandwwraith** [comment]
Seems there's no a lot of demand for this feature, so I'm closing this now as won't fix

**Comment by DanySK** [comment]
I do have the need for lambda serialization, too. We are trying to support [Aggregate Programming](https://ieeexplore.ieee.org/document/7274429) within Kotlin-multiplatform as a DSL. It is still at low TRL, but it is very likely that this kind of technology will be part of the solution to the [emerging cloud-edge continuum](https://eucloudedgeiot.eu/). The EU is funding several actions in this direction.

Lambda serialization is necessary for advanced use cases, see e.g. [this paper](https://ieeexplore.ieee.org/document/7274429), which use [Protelis](https://protelis.github.io/), a JVM-only language.

It would be much nicer to be able to use Kotlin multiplatform, be able to serialize lambdas in a multiplatform fashion, and send them across the network.

I am tagging a few people working on related tooling. Even if it is not interesting for JetBrains/Kotlin, having guidance on how to bring this to a compiler plugin would be useful to us.

@ElisaTronetti (Kotlin compiler plugins expert)
@AngeloFilaseta (Kotlin multiplatform, JS/JVM interop and serialization expert)
@nicolasfara (Kotlin MP expert and architect of an edge-cloud continuum platform)
@cric96 (Scala wizard, JS/JVM interoperability expert, language designer)

**Comment by sandwwraith** [comment]
@DanySK There's a bit of documentation in the plugin folder itself (https://github.com/JetBrains/kotlin/tree/master/plugins/kotlinx-serialization) although it's mainly outdated. However, there are several third-party articles that describe how to write Kotlin compiler plugins

**Comment by DanySK** [comment]
@sandwwraith I meant if there's any specific hint on how to realize a (possibly multiplatform) plugin that supports lambda serialization. We can write Kotlin compiler plugins (although the documentation is pretty scarce), but (speaking for myself here) I have no clear idea what the plugin should do. It's more of a conceptual/understanding obstacle than a practical/implementation one, right now.

**Comment by sandwwraith** [comment]
Well, that's why the lambda serialization topic is broad and complex — it is up to you to define what 'lambda serialization' is :). If you need a start point, I can say that lambdas are essentially synthetic classes that hold all captured variables as fields.
