### ISSUE TITLE
[Question]setMapper deserializer for an Array of JSON objects

### ISSUE THREAD

**Issue by alan-camilo** [Kotlin/kotlinx.serialization#488]
I want to deserialize a Json describing an array. For example an array of color objects:
```json
[
	{
		"color": "red",
		"value": "#f00"
	},
	{
		"color": "green",
		"value": "#0f0"
	}
]
```

How can I explicitly set the deserializer of this array of color object when initializing my KotlinxSerializer ?

```kotlin
val jsonSerializer = KotlinxSerializer(Json.nonstrict).apply {
    setMapper(?, ?)
}
```

I tried `setMapper(Array<Color>::class, Color.serializer().list)` but the arguments types are wrong

**Comment by e5l** [comment]
Hi @alan-camilo, thanks for the report. 
Unfortunately, top-level lists are supported only for serialization in ktor.

The deserialization will be supported in 1.3.40 on jvm and 1.3.50 on other platforms.

**Comment by sandwwraith** [comment]
For serialization you can use `setListMapper`, I assume

**Comment by alan-camilo** [comment]
In the meantime, I use another function to deserialize this array of Json objects
```kotlin
Json.parse(Foo.serializer().list, client.post(requestBuilder))
```
