### ISSUE TITLE
Provide way to specify which values to elide

### ISSUE THREAD

**Issue by MariusVolkhart** [Kotlin/kotlinx.serialization#489]
**What is your use-case and why do you need this feature?**
Consider the following Kotlin class
```kotlin
data class Ball(val action: String = "Bounce")
```

The `action` property has a default value of `Bounce` because in my program, most balls bounce. There may be instances where balls do not `Bounce` however.

When I serialize this class to JSON, my `action` is elided if the value of the action is `Bounce`. This is undesirable. I want the action to be in the JSON, as other programs in my system may not have the same default. Put differently, the default is a trait of my program, not of the data itself. For example, a program for a bowling alley would probably not consider all balls to `Bounce`.

One option I have for making sure that my `action` is always in the JSON is to write a custom `KSerializer<Ball>`. This may be feasible in the simple case presented here, but doesn't scale as the number of properties on `Ball` increases. Maintaining a custom `KSerializer` for the purposes of a single property seems sub-optimal.

**Describe the solution you'd like**
A solution that appears simple on the surface is an annotation that lets me specify what the default value is.

For example,
```kotlin
@Serializable
data class Ball(
    @Default(null) val action: String = "Bounce",
    @Default(5) val diameter: Int = 5,
    @Default(0) val age: Int
)

fun main() {
    val json = Json(JsonConfiguration.Stable.copy(encodeDefaults = false))
    val encoded = json.stringify(Ball.serializer(), Ball(age = 0))
    if (encoded.contains("\"action\"")) {
        throw AssertionError("Action was not elided but should have been.")
    }
    if (encoded.contains("\"diameter\"")) {
        throw AssertionError("Diameter was not elided but should have been.")
    }
    if (encoded.contains("\"age\":")) {
        throw AssertionError("Age was not elided but should have been.")
    }
}
```

A solution that I think addresses more use cases is a way to plugin to the serialization pipeline via `SerialModule`. Some sort of way for the serialization mechanism to tell me "this is Type being serialized, and this is it's value" and for me to respond "do|don't serialize it, use <this> value, and make <this> the name".

For example, when serializing the `Ball` class, I would be told, "a `String` called `action` with value of `Bounce` is being serialized. I could then reply with, "Serialize a `String` called `action` with value `Bounce`. If I were told, "a `String` called `action` with value of `null` is being serialized" I could reply with, "skip this property".

***Contextual Serialization***
`@ContextualSerialization` does not meet my requirements. Firstly, having to specify it on every property is error prone. Secondly, by the time the contextual serializer is invoked, the property name has already been written, so at most the value can be modified.

Consider a scenario in which I want to make sure that all properties called `password` are always replaced with `********`. At no point am I made aware of what the property name is during serialization. I have to specify the `@ContextualSerialization` annotation on every `password` property. But if I have multiple "rules" that apply to `String` types, then this doesn't work either.

**Comment by sandwwraith** [comment]
So there's actually two features you want:
- Decouple a default value in JSON from the default value in Kotlin constructor
- Have the ability to encode some property even if it has `= something` and `encodeDefaults=false` and also the ability to elide some property even if it does not have default Kotlin value and `encodeDefaults=false`
?

I also do not fully understand how `@Default(null)` should work if the property is not-nullable.

We tend to stick to the paradigm 'Deserialization is just another class constructor', so introducing two possibly different default values for one property would make dissonance, because class could behave differently depends on an approach it was created with: deserialization from JSON or from another format or regular constructor call.

However, it seems that with reasonable extensibility mechanism a lot of issues like this could be closed, so it is worth looking into.

**Comment by MariusVolkhart** [comment]
Thanks for getting back so quickly! Yes, that is an excellent summary of the 2 features I want.

You're absolutely right about `@Default(null)` not making sense, I hadn't even realized the disconnect between the not-nullable property and what I was annotating with. I like the 'Deserialization is just another class constructor' paradigm, and with how easy it was for me to make a mistake just while describe my request I definitely think a extensibility mechanism would be better.

**Comment by MariusVolkhart** [comment]
I've created a set of tests that demonstrate the two features described above

**Comment by pdvrieze** [comment]
It seems that the issue you are having is that properties with default values are made optional (and therefore elided). To change this you can use the `@Required` annotation. What would be really good is if default values would be supported for annotations so that it would be possible to make this requirement only for writing (write always, but allow missing value on reading).

**Comment by MariusVolkhart** [comment]
@pdvrieze thanks for the hint. `@Required` doesn't quite address my problem.

### @Required
Consider a class `class Person(@Required age: Int = 18)`. In this case, the default age of `18` is used b/c my _program_ considers this the default age of a person. However, I want to configure serialization to occur such that when `age` is `0`, it is elided from the JSON. When `age` is `18`, it should still be part of the JSON.

The `serializeContainerWithRequiredMember()`  test I wrote demonstrates this scenario.

The other part of what I'm missing is the concept of "multiple" default values. Take a slight modification of the previous class `class Person(age: Int? = null)`. I want to configure the serialization such that when `age` is `0` *or* `null`, it is elided from the JSON.

### Write-only @Default
The second part you mentioned, about "write always, but allow missing value on reading" I absolutely agree with. For example, a server that accepts logging events from many different clients might define a protocol like `Event(message: String, type: String?)` (psuedo-code, consider a server not using kotlinx.serialization). That same server may send the event as `{"message": "message text"}` if the `type` is `null` or empty.

One of the clients might define the same protocol as (psuedo-kotlinx.serialization; not an API proposal):
```kotlin
class Event(
  val message: String,
  @Required // So that "CustomKey" gets serialized
  @Default(deserialization = NULL) // So that missing "type" gets deserialized as null
  val type: String? = "CustomKey"
)
```
The client should produce a JSON of `{"message":"my message", "type": "CustomKey"}`. This client only ever sends events with `type` of `CustomKey`, hence the default value. In other words, the default value is unique to the client, not the protocol. This same client should be able to parse events sent from the server that don't have a `type` property, and the program-default should not be applied.

### Final thoughts
I've used single classes as my examples here, but in general, I think the solution needs to be configurable at the "Module/context" level, or at least at the compilation unit level. For example, I want all `Int?`s that are `0` or `null` to be elided during serialization and to default to `null` during deserialization, within the `SerialModule` I'm using, or within the same gradle project (or whatever compilation unit is used).

**Comment by pdvrieze** [comment]
@MariusVolkhart Your problem can be handled using custom serializers (either by going through an intermediate type, or fully specifying custom serialization), but I assume that you don't want to do this for the case. There are however two gotchas:

- Any default that is not a valid entry in the constant pool/annotation (class, string, int) must be provided in serialized form - this in turn implies the choice of a specific format for this. It is possible, my XML format does it at format level.
- Some formats, for example protobuf, have their own meaning for missing values.

**Comment by MariusVolkhart** [comment]
@sandwwraith thanks for your work on this!
