### ISSUE TITLE
Gradle configuration error: Cannot add extension with name 'kotlinNodeJs'

### ISSUE THREAD

**Issue by alshan** [Kotlin/kotlinx.serialization#499]
In multiplatform project which is also muiltiproject: as soon as I add `id 'kotlinx-serialization' version '1.3.40'` to `plugins` of one of subprojects, gradle can no longer configure other subprojects and fails with the following error: 

> Cannot add extension with name 'kotlinNodeJs', as there is an extension already registered with that name.

**Environment**
 - Kotlin version: 1.3.40
 - Kotlin platforms: Multiplatform 
 - Gradle version: 4.10.3

**Comment by sandwwraith** [comment]
Can you post whole contents of your `build.gradle`, please? Or just give a link to github/gist with your project

**Comment by alshan** [comment]
This is the entire project: [datalore-plot](https://github.com/JetBrains/datalore-plot)
See: base/build.gradle

**Comment by sandwwraith** [comment]
I'm still investigating the issue (this is more about Gradle infrastructure and new JS multiplatform plugin rather than serialization), but as a workaround, you can try to include both kotlin and serialization plugins to the root project (use `apply false` if necessary) and let me know if that works for you

**Comment by alshan** [comment]
When both plugins are in root project (with `apply false`) all subprojects are configured with no errors, thank you!

Unfortunately, I wasn't able to deserialize JSON to Map<String, Any>.

I've tried to use `Json.parseMap<String, Any>(s)` but got 

SerializationException:

> Can't locate argument-less serializer for class null. For generic classes, such as lists, please provide serializer explicitly.


JSON I needed to parse: 
```
{   "data":    {      "time": ["Lunch","Lunch", "Dinner", "Dinner", "Dinner"]   }           ,   "mapping": {             "x": "time"           },   "layers": [               {                  "geom": "bar"               }           ]}
```

Aren't you supporting lists in values?

**Comment by sandwwraith** [comment]
Yes, but for security reasons, we don't support deserializing to arbitrary `Any`. You can use `Map<String, JsonElement>` (i.e. `JsonObject`) to deserialize to Json AST or take a look at  polymorphic deserialization which requires to list all possible classes in advance: https://github.com/Kotlin/kotlinx.serialization/blob/master/runtime/commonMain/src/kotlinx/serialization/Polymorphic.kt#L30

**Comment by alshan** [comment]
But this is just recursive map with strings, numbers and lists of the same types, which is very typical case I think. 
Isn't this supposed to work out of the box?

**Comment by sandwwraith** [comment]
Well, when you read `Any` in the code, you usually think 'there could be any type', not 'there could be only strings, numbers, and maps'. That was the motivation behind design decision on supporting separate `JsonObject` instead of `Map<String, Any>`.

**Comment by alshan** [comment]
Up to you of course but string, number, boolean, null, object and array is pretty much all what JSON has. The default mapping would be: String, Double, Boolean, null, Map<String,*>, List<*>, and function `Json.parseMap` just looks like a perfect helper function with these defaults inside.

**Comment by eugenio1590** [comment]
I get this issue when I try to apply the plugin into a Kotlin JS project for browsers. This is the complete error:

````
Could not create an instance of type org.jetbrains.kotlin.gradle.targets.js.subtargets.KotlinBrowserJs.
> Failed to apply plugin [class 'org.jetbrains.kotlin.gradle.targets.js.nodejs.NodeJsRootPlugin']
   > Cannot add extension with name 'kotlinNodeJs', as there is an extension already registered with that name.
````

I am using these plugins:

````
plugins {
    id("org.jetbrains.kotlin.js") version "1.3.72"
    kotlin("plugin.serialization") version "1.3.72"
}
````

I tried to use (apply false) but this did not work.

**Comment by sandwwraith** [comment]
@eugenio1590 Try to use the plugin in the root module of your Gradle project. With `apply: false` if it is not really needed there

**Comment by eugenio1590** [comment]
I'll try it. I let you know If this issue persists. Thanks.

**Comment by eugenio1590** [comment]
I was able to replicate the problem. The issue occurs when I include a Kotlin multi-platform project with browser support in another that uses "kotlinx.serialization" library. I will create a project with that problem later.

**Comment by eugenio1590** [comment]
This is the project: https://github.com/eugenio1590/DemoTest

**Comment by Kabbura** [comment]
> I was able to replicate the problem. The issue occurs when I include a Kotlin multi-platform project with browser support in another that uses "kotlinx.serialization" library. I will create a project with that problem later.

I am facing the same problem. However, I am not working with a multi-platform project. I am working on a multi-project ([gradle multi project](https://docs.gradle.org/current/userguide/multi_project_builds.html#multi_project_builds)) and I include the koltlinx.serialization in one project but not the other. If I include the plugin in both projects, it build successfully.

**Comment by shanshin** [comment]
Unable to reproduce with the recommended latest Kotlin Multiplatform plugin.
Feel free to open new bug issue if the problem reproduced again.
