### ISSUE TITLE
Annotating a @Serializable class's property with SerialName with a value that is equal to another property's name causes the IDE analyzer to hang

### ISSUE THREAD

**Issue by natanfudge** [Kotlin/kotlinx.serialization#503]
**Describe the bug**
Annotating a @Serializable class's property with SerialName with a value that is equal to another property's name causes the IDE analyzer to hang. 
**To Reproduce**
Paste this code into a file with IntelliJ:
```kotlin
@Serializable
class Test(
    @SerialName("hanger")
    val Foo : String,
    val hanger: String
)
```

**Expected behavior**
IDE analyzer won't hang. Instead it will mark  the `"hanger"` in `@SerialName("hanger")` red and show a " Another property is already named "hanger"  "  error.

**Actual behavior**
IDE analyzer hangs. (Try typing some garbage and see it won't recognize it as an error)

**Environment**
 - Kotlin version: 1.3.40
 - Library version: 0.11.1
 - Kotlin platforms: JVM
 - Gradle version: gradle-4.10.3, happened with 5.4.1 too.
 - IDE version IntelliJ IDEA (Ultimate Edition) version 2019.1.3
- OS : Windows 10

**Comment by sandwwraith** [comment]
This is a known problem; IDE diagnostics for kotlinx.serialization would be added in Kotlin 1.3.50

**Comment by natanfudge** [comment]
OK. In how long do you expect we will get Kotlin 1.3.50?
