### ISSUE TITLE
How I serialized arrayListOf(object) on Json Array to send post

### ISSUE THREAD

**Issue by danielgssp** [Kotlin/kotlinx.serialization#504]
Plz Helpe-me,

I trying to send list of objects to other REST API with post
my code

```
 suspend fun sendCan(listCan: List<Can>): String {
        val stringJson= Json.nonstrict.stringify(Can.serializer().list, listCan)
        val json = Json.nonstrict.parseJson(stringJson)

        return client.post {
            url("$baseUrl/insert")
            header("content-type", "application/json")
            body = json
        }
    }
```
I have to send a list of objects is what the REST is waiting for 
example
header:
`"content-type", "application/json"
`
body:
```
[
	{
		"x":"x",
		"data":"xx",
		"y":"xx",
		"id_can": "x"
	}
]
```
my Model : 

```
@Serializable
data class Can(
        val id_can: String,
        val x: String,
        val y: String, val data: String
)

```
Error: `kotlinx.serialization.json.JsonObject cannot be cast to java.lang.String`

**Comment by sandwwraith** [comment]
`parseJson` returns `JsonObject`, but it seems that somewhere far in the pipeline a `String` was expected. Why don't try to send `stringJson` instead?

**Comment by danielgssp** [comment]
Yeah! I Tryed but response of request return error `400<Bad Request>`, because header outgoing is string and API REST expect's `application/json `

**Comment by mirceanis** [comment]
> Yeah! I Tryed but response of request return error `400<Bad Request>`, because header outgoing is string and API REST expect's `application/json `

This does not look like a serialization issue. The API is complaining about something else. From a format perspective all looks ok.
@sandwwraith is right that you probably need to pass `stringJson` to that method.

**Comment by Leeeeerich** [comment]
Hey maybe to whom need:
