### ISSUE TITLE
Serializable class with secondary constructor causes build to fail

### ISSUE THREAD

**Issue by Whathecode** [Kotlin/kotlinx.serialization#508]
**Description**
A very simple class which contains a secondary constructor and a property defined outside of the primary constructor causes the compilation to fail.

Interestingly, it is neither the secondary constructor, nor the property in isolation which causes this issue. It is the combination of the two.

> e: java.lang.IllegalStateException: Backend Internal error: Exception during code generation
> Cause: Back-end (JVM) Internal error: wrong code generated
> org.jetbrains.kotlin.codegen.CompilationException Back-end (JVM) Internal error: Couldn't transform method node:
> <init> (ILjava/lang/String;ILkotlinx/serialization/SerializationConstructorMarker;)V:
>   @Lkotlin/Deprecated;(message="This synthesized declaration should not be used directly", replaceWith=@Lkotlin/ReplaceWith;(expression="", imports={}), level=Lkotlin/DeprecationLevel;.HIDDEN)
>     // annotable parameter count: 4 (visible)
>     // annotable parameter count: 4 (invisible)
>     @Lorg/jetbrains/annotations/Nullable;() // invisible, parameter 1
>     @Lorg/jetbrains/annotations/Nullable;() // invisible, parameter 3
>    L0
>     ALOAD 0
>     INVOKESPECIAL java/lang/Object.<init> ()V
>   ...

**To Reproduce**
```
@Serializable
class WithSecondaryConstructor( var someProperty: Int )
{
    var test: String = "Test"

    constructor() : this( 42 )
}
```

**Expected behavior**
I see no reason why it fails on this. In fact, I believe this worked in 0.10.0. I only encountered this while upgrading to 0.11.1. But, this is not a blocker for me at the moment.

**Environment**
 - Kotlin version: 1.3.41
 - Library version: 0.11.1
 - Kotlin platforms: Multiplatform JVM and JS
 - Gradle version: 5.5

**Comment by eanekrasov** [comment]
Faced the same issue, the only difference is that the constructor is generated by the kotlin.jpa plugin. Tried different versions of serialization - the same result.
