### ISSUE TITLE
Class<PolymorphicSerializer> cannot be converted to Class<? extends KSerializer<?>>

### ISSUE THREAD

**Issue by AhsenSaeed** [Kotlin/kotlinx.serialization#510]
It's been two days since I'm trying to create a serializer for my sealed class. Before creating an issue I already have seen [this](https://github.com/Kotlin/kotlinx.serialization/issues/127) and [this](https://github.com/Kotlin/kotlinx.serialization/issues/126). 

Here is my sealed classes structure.

```
sealed class AnsweredContent {

    @Serializable
    @SerialName(value = "AnsweredContent\$SingleTextContent")
    data class SingleTextContent(var answer: String = "") : AnsweredContent()

    @Serializable
    @SerialName(value = "AnsweredContent\$LocationContent")
    data class LocationContent(var latitude: Double = 0.0, var longitude: Double = 0.0, var accuracy: Float = 0F) :
        AnsweredContent()
}
```

And this my **AnsweredContentHolder** class.
```
@Serializable
    data class Question(
        val id: Int,
        val title: String,
        val order: Int,
        @Serializable(with = PolymorphicSerializer::class)  val answeredContent: AnsweredContent
    )
```

Now when I try to build the application the compiler throws the following error.
```
error: incompatible types: Class<PolymorphicSerializer> cannot be converted to Class<? extends KSerializer<?>>
        @kotlinx.serialization.Serializable(with = kotlinx.serialization.PolymorphicSerializer.class)
```

**Comment by sandwwraith** [comment]
Use `@Polymorphic` instead of ` @Serializable(with = PolymorphicSerializer::class) `

**Comment by sandwwraith** [comment]
Also probably you've imported some different class because PolymorphicSerializer is definitely a KSerializer
