### ISSUE TITLE
Outdated documentation for `Json.install`

### ISSUE THREAD

**Issue by Whathecode** [Kotlin/kotlinx.serialization#511]
In [`Json.kt`](https://github.com/Kotlin/kotlinx.serialization/blob/master/runtime/commonMain/src/kotlinx/serialization/json/Json.kt), the following is stated:

>  It is typically used by constructing an application-specific instance, registering custom serializers via [Json.install] and then using it either as regular [SerialFormat] or [StringFormat] or for converting objects to [JsonElement] back and forth.

However, `Json.install` is deprecated: `override fun install(module: SerialModule) = throw IllegalStateException("You should not install anything to global instance")`

```
private const val INSTALL_DEPRECATION_TEXT = "Install is no longer supported, module can be added to format only in constructor"

interface SerialFormat {
    val context: SerialModule

    @Deprecated(INSTALL_DEPRECATION_TEXT, level = DeprecationLevel.ERROR)
    fun install(module: SerialModule) {}
}
```

What is the recommended way to install polymorphic serializers dynamically? I would still have to register them somewhere globally. The only difference is I need to reinitialize a `Json` instance with the updated `SerialModule` each time.

**Environment**
 - Kotlin version: 1.3.41
 - Library version: 0.11.1

**Comment by sandwwraith** [comment]
Take a look a `Json(JsonConfiguration, SerialModule)` constructor

**Comment by Whathecode** [comment]
Thank you for the fast response, @sandwwraith!

I understand using that constructor is an alternative. But, the way I see it this simply moves the global state from within the `Json` object to a globally accessible `SerialModule` variable from which each time serialization needs to occur, a new `Json` object is instantiated in order to guarantee all expected polymorph types are registered.

I was more wondering about the reasoning behind this design decision. It seems like you want to prevent global registration of types which can be serialized. Does this mean it is a bad idea to have a base library with abstract serializable classes which other libraries can extend?

**Comment by sandwwraith** [comment]
The key point of deprecating `install` was to get rid of global mutable state. `SerialModule` is an immutable class, so there's nothing wrong with its instance globally accessible. 

We imagine the usage of this combination as following: at application startup, you create a `SerialModule` with all classes you need and then create a `Json` instance. Then you can inject this instance whenever you need it. If you need to change settings/add classes/restrict classes, you can always create another `Json` with other configuration or another module.

If you're writing a library with an abstract class and some implementations of it, you can export your own `MyLibrarySerialModule` for your clients to use. Serial modules are composable (see `dumpTo` function, or [`SerializersModuleBuilder#include`](https://github.com/kotlin/kotlinx.serialization/blob/45aa7c7ab97f25f205408b46a7069886408bce6b/runtime/commonMain/src/kotlinx/serialization/modules/SerialModuleBuilders.kt#L78)), so a client can combine your module with its own modules (probably the ones that have client's implementation of your library's abstract class).
