### ISSUE TITLE
How to serialize/unserialize a generic list for my wrapper function

### ISSUE THREAD

**Issue by salamanders** [Kotlin/kotlinx.serialization#512]
I'm trying to create a very generic wrapper around function calls that take a long time, and would prefer to use the hopefully faster serialization rather than the slower java ObjectOutputStream.

However, this borks with `Exception in thread "main" kotlinx.serialization.SerializationException: Can't locate argument-less serializer for class kotlin.collections.List. For generic classes, such as lists, please provide serializer explicitly.`

But AFAIK after reading the examples I can't just call MyClass.serializer().list, because I don't know what class we are talking about.  All I have is `<T>`.

Is what I'm trying to do impossible?  Do I need to pass in an extra parameter?

```kotlin
@ImplicitReflectionSerializer
inline fun <reified T:Any> cachedOrCalculated(sourceFileNameOrLabel: String, exec: () -> T): T {
    val serializer = Cbor()
    val file = labelToFile(sourceFileNameOrLabel)
    if (file.canRead()) {
        file.inputStream().use { ins ->
            return serializer.load(ins.readAllBytes()!!)
        }
    }
    val result = exec()
    labelToFile(sourceFileNameOrLabel).outputStream().use { os ->
        os.write(serializer.dump(result))
    }
    return result
}
```

**Environment**
 - Kotlin version: 1.3.40
 - Library version: 0.11.1
 - Kotlin platforms: JVM
 - Other relevant context: JRE version: 8+

**Comment by salamanders** [comment]
This works, but I was hoping to use reflection so I don't need the extra `serializer` param.

```
fun <T> cachedOrCalculated(
    sourceFileNameOrLabel: String,
    serializer: KSerializer<T>,
    exec: () -> T
): T {
    val file = labelToFile(sourceFileNameOrLabel)
    val cbor = Cbor()
    if (file.canRead()) {
        return cbor.load(serializer, file.readBytes())
    }
    val result = exec()
    file.writeBytes(cbor.dump(serializer, result))
    return result
}

val myStuff: List<List<Int>> = cachedOrCalculated(
    sourceFileNameOrLabel = "mycache_lum_thumbs",
    serializer = IntSerializer.list.list
) {
    mySlowFunction()
}

**Comment by sandwwraith** [comment]
Unfortunately, due to generic erasure, you have to pass serializer manually. You can try to use type tokens with `serializerByTypeToken` function (https://github.com/kotlin/kotlinx.serialization/blob/45aa7c7ab97f25f205408b46a7069886408bce6b/runtime/jvmMain/src/kotlinx/serialization/JvmResolving.kt) if you're limited to JVM.
