### ISSUE TITLE
Android Studio: Serialization unresolved Reference

### ISSUE THREAD

**Issue by EdwardW2** [Kotlin/kotlinx.serialization#513]
**Description**
I am trying to build an iOS framework with kotlin/native and each time I attempt to run the app or build said framework, android studio states that everything to do with kotlinX serialization is an unresolved reference. This only happens on version 0.11.1 of serialization and does not exist on 0.11.0 (though that version is incompatible with the versions of other plugins I am using.)

**To Reproduce**
`buildscript {
    ext.kotlin_version = '1.3.41'
    ext.kotlin_native_version = '1.3.40'
    ext.ktor_version = '1.2.2'
    ext.coroutines_version = '1.0.1'
    ext.kotlinx_coroutines_version = '1.3.0-M2'
    ext.serialization_version = '0.11.1'

    repositories {
        maven { url 'https://dl.bintray.com/kotlin/ktor' }
        maven { url 'https://kotlin.bintray.com/kotlinx' }
        maven { url 'https://plugins.gradle.org/m2/' }
        maven { url 'https://dl.bintray.com/jetbrains/kotlin-native-dependencies' }
        maven { url 'http://dl.bintray.com/kotlin/kotlin-eap' }
        google()
        jcenter()
        
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "org.jetbrains.kotlin:kotlin-native-gradle-plugin:$kotlin_native_version"
        classpath "org.jetbrains.kotlin:kotlin-serialization:$kotlin_version"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        maven { url 'https://kotlin.bintray.com/kotlinx' }
        maven { url 'https://kotlin.bintray.com/ktor' }
        google()
        jcenter()
        
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}`

<img width="2074" alt="Screenshot 2019-07-09 at 09 54 46" src="https://user-images.githubusercontent.com/44901854/60874257-a7917080-a22f-11e9-8039-d5646b6be43b.png">

**Environment**
 - Kotlin version: 1.3.41
 - Library version: 0.11.1
 - Kotlin platforms: Native
 - Gradle version: 5.1.1
 - IDE version:  Android Studio 3.4.1

**Comment by sandwwraith** [comment]
Hmm... What exact project model do you use? If you're writing a multiplatform application, then dependency  should be configured for each source set, as here: https://github.com/Kotlin/kotlinx.serialization/blob/master/examples/example-multiplatform/build.gradle#L49

If your `Shared` module is pure common, try using `kotlinx-serialization-runtime-common` as runtime dependency artifact id

**Comment by EdwardW2** [comment]
My Shared module uses common, android and iOS. This is the configuration I used with 0.11.0 and it worked, just not with 0.11.1. Here is the build.gradle file for my Shared module

`apply plugin: 'kotlin-multiplatform'
apply plugin: 'kotlinx-serialization'

kotlin {
    targets {
        final def iOSTarget = System.getenv('SDK_NAME')?.startsWith("iphoneos") \
                              ? presets.iosArm64 : presets.iosX64

        fromPreset(iOSTarget, 'ios') {
            binaries {
                framework('SharedCode')
            }
        }

        fromPreset(presets.jvm, 'android')
    }

    sourceSets {
        commonMain.dependencies {
            api 'org.jetbrains.kotlin:kotlin-stdlib-common'
            implementation "io.ktor:ktor-client-core:$ktor_version"
            implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core-common:$coroutines_version"
            implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime:$serialization_version"
        }

        androidMain.dependencies {
            api 'org.jetbrains.kotlin:kotlin-stdlib'
            implementation "io.ktor:ktor-client-android:$ktor_version"
            implementation "org.jetbrains.kotlinx:kotlinx-coroutines-android:$kotlinx_coroutines_version"
        }

        iosMain.dependencies {
            implementation "io.ktor:ktor-client-ios:$ktor_version"
            implementation "org.jetbrains.kotlinx:kotlinx-coroutines-core-native:$kotlinx_coroutines_version"
            implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime-native:$serialization_version"
        }
    }
}

task packForXCode(type: Sync) {
    final File frameworkDir = new File(buildDir, "xcode-frameworks")
    final String mode = project.findProperty("XCODE_CONFIGURATION")?.toUpperCase() ?: 'DEBUG'
    final def framework = kotlin.targets.ios.binaries.getFramework("SharedCode", mode)

    inputs.property "mode", mode
    dependsOn framework.linkTask

    from { framework.outputFile.parentFile }
    into frameworkDir

    doLast {
        new File(frameworkDir, 'gradlew').with {
            text = "#!/bin/bash\nexport 'JAVA_HOME=${System.getProperty("java.home")}'\ncd '${rootProject.rootDir}'\n./gradlew \$@\n"
            setExecutable(true)
        }
    }
}
tasks.build.dependsOn packForXCode

// workaround for https://youtrack.jetbrains.com/issue/KT-27170
configurations {
    compileClasspath
}`

**Comment by sandwwraith** [comment]
Use `implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:$serialization_version"` in `commonMain.dependencies`, and `implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime:$serialization_version"` in `androidMain`

**Comment by rodionov-andrei** [comment]
Same issue.

> Use `implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:$serialization_version"` in `commonMain.dependencies`, and `implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime:$serialization_version"` in `androidMain`

Tried it.

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app_android:transformResourcesWithMergeJavaResForDebug'.
> More than one file was found with OS independent path 'META-INF/kotlinx-serialization-runtime.kotlin_module'`

**Comment by sandwwraith** [comment]
@rodionov-andrei https://stackoverflow.com/a/44509660

**Comment by Gennady77** [comment]
I have the same issue. I updated my Studio to 3.5. Kotlin 1.3.41.
Someone will solve this shit?

**Comment by sandwwraith** [comment]
@Gennady77 There's several issues here; most of them caused by misconfiguration of dependencies on a use-site
