### ISSUE TITLE
The baseclass property of PolymorphicSerializer is private

### ISSUE THREAD

**Issue by pdvrieze** [Kotlin/kotlinx.serialization#515]
For my XML parsing I'm trying to enumerate all possible polymorphic children of a parent (as declared in the serialmodule). To do so I need to know the actual base class. This information is encapsulated in the baseclass parameter of Polymorhpic serializer.

Currently I'm using a hack where trigger a lookup on a dummy context which will tell me the base class. It's much easier to just get the property value directly.

**Comment by sandwwraith** [comment]
I don't know where in your code you can try to obtain this information, but if you have `SerialModule`, its `dumpTo` function will list all its content. Or you want only a portion of this information for a particular base class somewhere inside `encodeSerializableValue` if given serializer is polymorphic?

**Comment by pdvrieze** [comment]
I want it only for a specific base class (basically so that I can use that to find all child (de)serializers). Parsing will then be able to recognize the name of this child and handle it appropriately. Technically it may be possible to ignore the base class all together, but this would prevent multiple polymorphic fields in the same structure (it wouldn't be possible to match a tag to a specific field). Encoding works well with just retrieving the base class on the polymorphic serializer (and perhaps ignoring the base class).

When decoding it is important to know the actual base class based upon the descriptor of the container of the polymorphic value. Basically the code that reads the member of polymorhpic type will need to decide which of the subtypes to use. In XML you would do this most naturally by having different tag names for different types. Basically this means that before a value is read, all possible child tags are enumerated so when it finds a tag it knows what to do with it. (Btw. it would be even easier if the base class could be determined from the SerialDescriptor rather than the serializer.

**Comment by pdvrieze** [comment]
I've finished making things work for now (but using ugly workarounds and references to impl classes). What I believe would solve the problem in the most elegant way is if the SerialDescriptors would be able to provide type parameters (class and/or serializer): For polymorphic descriptors the base type, for list descriptors the element type... Note that this information is already there to be able to serialize (as such I can use some hacks to get it), but it is in implementation classes etc.

**Comment by sandwwraith** [comment]
I'll look into adding base class descriptor into `PolymorphicClassDescriptor`. 

In the meantime, you can send us a PR with `public val baseClass: KClass<T>`

**Comment by pdvrieze** [comment]
I've created the pull request.
https://github.com/Kotlin/kotlinx.serialization/pull/520

I think that adding something to PolymorphicClassDescriptor would be good, but the problem is broader. In general it would be good to be able to programmatically query the serializers for all children.
