### ISSUE TITLE
kotlinx.serialization.cbor.CborDecodingException: Expected byte bf, but found a2

### ISSUE THREAD

**Issue by slipdef** [Kotlin/kotlinx.serialization#517]
**Describe the bug**
Can't deserialize data serialized with https://github.com/peteroupc/CBOR-Java on a server side. Got the following exception: kotlinx.serialization.cbor.CborDecodingException: Expected byte bf, but found a2 

**To Reproduce**
```
val test = SomeClass()
test.prop = 99
var bytes = CBORObject.FromObject(test).EncodeToBytes()
Cbor.load<SomeClass>(bytes)
```

**Expected behavior**
Should just work. It works well on iOS side when deserializing using this lib https://github.com/myfreeweb/SwiftCBOR. So I post here instead of CBOR-Java repo.

**Environment**
 - Kotlin version: 1.3.41
 - Library version:  0.11.1
 - Kotlin platforms: JVM

**Comment by sandwwraith** [comment]
Could you post, please, what is `SomeClass` definition?

**Comment by slipdef** [comment]
```
@Serializable
class SomeClass {
    public var prop: Int = 0
}
```

**Comment by slipdef** [comment]
@sandwwraith any ETA for this fix in releases? It's a blocking issue for us, so either we wait when the next release arrives or try to build kotlinx.serialization from dev branch (is it safe to do it, btw?).

**Comment by sandwwraith** [comment]
@slipdef Current dev is stable, I think, but it is built using Kotlin 1.3.50-eap-5. If you are OK with compiler eaps, you can take it, otherwise better checkout `16dae19e42f33492a64cc4d94f0dbf99f3e9586e` (before 'move to 1.3.50' commit).

New library versions are usually released with new Kotlin versions, in current case, 1.3.50

**Comment by slipdef** [comment]
@sandwwraith sounds like kotlinx.serialization is not released with 1.3.50 (https://github.com/JetBrains/kotlin/blob/1.3.50/ChangeLog.md). What is actually the policy of releasing  kotlinx.serialization? You said "usually", like it's an arbitrary decision?

**Comment by sandwwraith** [comment]
@slipdef Well, "with" does not mean the exact same time. All kotlinx libraries (coroutines, serialization, ktor, etc) are updated in a several days after release.

**Comment by slipdef** [comment]
Thanks, looking forward for new kotlinx.serialization release. It's quite a pain to build it from sources now.
