### ISSUE TITLE
Invalid codegeneration for serialDesc for custom serializer

### ISSUE THREAD

**Issue by pdvrieze** [Kotlin/kotlinx.serialization#524]
When using an Companion object to stand in as custom serializer it is possible to make it inherit GeneratedSerializer (it does this anyway). Unfortunately the initialisation for the companion object is incorrect. Look at the following snippet:

```
  public kotlinx.serialization.SerialDescriptor getDescriptor();
    Code:
       0: getstatic     #69                 // Field $$serialDesc:Lkotlinx/serialization/SerialDescriptor;
       3: areturn

  static {};
    Code:
       0: new           #125                // class kotlinx/serialization/internal/SerialClassDescImpl
       3: dup
       4: ldc           #127                // String childModel
       6: getstatic     #106                // Field nl/adaptivity/process/processModel/engine/XmlChildModel.Companion:Lnl/adaptivity/process/processModel/engine/XmlChildModel$Companion;
       9: checkcast     #7                  // class kotlinx/serialization/internal/GeneratedSerializer
      12: invokespecial #130                // Method kotlinx/serialization/internal/SerialClassDescImpl."<init>":(Ljava/lang/String;Lkotlinx/serialization/internal/GeneratedSerializer;)V

```
Unfortunately, there is a circular reference here. In the class initialiser the Companion field in the owner object is not (can not) yet initialised, resulting in a null value.

This could be solved by generating the code as instance field/method on the companion object, where instead of a field reference a this reference is used.

**Comment by sandwwraith** [comment]
It is not recommended to inherit `GeneratedSerializer` manually

**Comment by sandwwraith** [comment]
In case of custom serializer, better to define `descriptor` manually

**Comment by pdvrieze** [comment]
This is a custom serializer. Unfortunately there are annotations that are needed and almost the only way to provide annotations is to get them from actual annotations that have been pulled into a descriptor that is automatically serialized. As to the use of `GeneratedSerializer` explicitly. This was actually not in the code in question, but is needed for a workaround (to register the child serializers in the descriptor)

**Comment by pdvrieze** [comment]
I will have a look at fixing the actual code generation bug. In the meantime it seems that it may be an option to allow somehow generating a list of members with annotations that can be used for a custom serializer without having to resort to a synthetic class whose only purpose is to extract these properties for serialization purposes..

**Comment by pdvrieze** [comment]
I've had a deep dive into the code generation (it's a lot better with the new API). The problem occurs due to ordering issues in class initialisation. If the serialDescriptor is created in a class initialiser (the default), and the class initialised is the serializer class itself this will be invoked before the class can be used in any way. As such the static field that records the serializer (and which is intended to be referenced) can not be initialised yet and will have a null value.

As a result the value of the `generatedSerializer` parameter to the constructor of `SerialClassDescImpl` will have a null value. This will always be the case if the descriptor is initialised in the static initialiser of the serializer class. The code actually asserts that this is only in object context.

Therefore there seem to be two possible solutions:

- Initialise the descriptor in the instance initialiser `<init>` (rather than class initialiser `<clinit>`) of the object. It seems that this is valid as the (companion) object instance would be initialised before it is used anywhere (as long as related class initialisers don't reference it - which they shouldn't). The instance will indeed be assigned to a static field which I believe has sufficient concurrency protection.
- Initialise the descriptor lazily. Either through hardcoding or as if using the `by lazy {...}` delegate with appropriate concurrency protections.

**Comment by sandwwraith** [comment]
There are two separate problems: First, creating a new instance of annotation class is not a valid kotlin code, and therefore it is impossible to do it in the custom serializer. It is a known limitation, and probably a language design discussion will be raised. Or at least some synthetic bridge could be generated to be used in user code (e.g. `instantiate<MyAnnotation>()`).

Problem with `descriptor` being in `<clinit>` is mentioned here: https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/custom_serializers.md#about-generic-serializers

> Current limitation: Because primary constructor in such case is generated by the compiler itself, not the plugin, you have to override descriptor manually since it can't be initialized in non-synthetic constructor.

When serializer is fully generated, `SerialClassDescImpl` initialization is indeed moved to `<init>`. However, the plugin can't alter the code of user-defined functions, therefore it is required to create descriptor manually, which returns us to the problem number one.

**Comment by pdvrieze** [comment]
@sandwwraith It seems that the only "correct" way to do it would be to go for lazy initialisation. Btw. in the cases that I'm looking at `<init>` is not hand-written either, only created implicitly (if at all). It's a pitty if a plugin can't append/prepend to existing functions (or rename & replace them).
