### ISSUE TITLE
Gradle can't consistently fetch 0.11.2-1.3.50-eap-5 but 0.11.1 works

### ISSUE THREAD

**Issue by TorRanfelt** [Kotlin/kotlinx.serialization#530]
On multiple computers this gives Gradle headaches:
compile 'org.jetbrains.kotlinx:kotlinx-serialization-runtime-js:0.11.2-1.3.50-eap-5'

Whereas this works:
compile 'org.jetbrains.kotlinx:kotlinx-serialization-runtime-js:0.11.1'

I get this odd error that mentions React. But it seems weird to me that React would have anything to do with this:

Execution failed for task ':extractLibs'.
> Could not resolve all files for configuration ':compile'.
   > Could not find org.jetbrains.kotlin:kotlin-stdlib-js:1.3.50-eap-5.
     Searched in the following locations:
       - https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.pom
       - https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.jar
       - https://kotlin.bintray.com/kotlin-js-wrappers/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.pom
       - https://kotlin.bintray.com/kotlin-js-wrappers/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.jar
       - https://kotlin.bintray.com/kotlinx/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.pom
       - https://kotlin.bintray.com/kotlinx/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.jar
     Required by:
         project :
   > Could not find org.jetbrains.kotlin:kotlin-stdlib-js:1.3.50-eap-5.
     Searched in the following locations:
       - https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.pom
       - https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.jar
       - https://kotlin.bintray.com/kotlin-js-wrappers/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.pom
       - https://kotlin.bintray.com/kotlin-js-wrappers/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.jar
       - https://kotlin.bintray.com/kotlinx/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.pom
       - https://kotlin.bintray.com/kotlinx/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.jar
     Required by:
         project : > org.jetbrains:kotlin-react:16.6.0-pre.70-kotlin-1.3.21
         project : > org.jetbrains:kotlin-react-dom:16.6.0-pre.70-kotlin-1.3.21
         project : > org.jetbrains:kotlin-react-router-dom:4.3.1-pre.70-kotlin-1.3.21
         project : > org.jetbrains:kotlin-react:16.6.0-pre.70-kotlin-1.3.21 > org.jetbrains:kotlin-extensions:1.0.1-pre.70-kotlin-1.3.21
   > Could not find org.jetbrains.kotlin:kotlin-stdlib-js:1.3.50-eap-5.
     Searched in the following locations:
       - https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.pom
       - https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.jar
       - https://kotlin.bintray.com/kotlin-js-wrappers/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.pom
       - https://kotlin.bintray.com/kotlin-js-wrappers/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.jar
       - https://kotlin.bintray.com/kotlinx/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.pom
       - https://kotlin.bintray.com/kotlinx/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.jar
     Required by:
         project : > org.jetbrains.kotlinx:kotlinx-serialization-runtime-js:0.11.2-1.3.50-eap-5
   > Could not find org.jetbrains.kotlin:kotlin-stdlib-common:1.3.50-eap-5.
     Searched in the following locations:
       - https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.50-eap-5/kotlin-stdlib-common-1.3.50-eap-5.pom
       - https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.50-eap-5/kotlin-stdlib-common-1.3.50-eap-5.jar
       - https://kotlin.bintray.com/kotlin-js-wrappers/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.50-eap-5/kotlin-stdlib-common-1.3.50-eap-5.pom
       - https://kotlin.bintray.com/kotlin-js-wrappers/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.50-eap-5/kotlin-stdlib-common-1.3.50-eap-5.jar
       - https://kotlin.bintray.com/kotlinx/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.50-eap-5/kotlin-stdlib-common-1.3.50-eap-5.pom
       - https://kotlin.bintray.com/kotlinx/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.50-eap-5/kotlin-stdlib-common-1.3.50-eap-5.jar
     Required by:
         project : > org.jetbrains.kotlinx:kotlinx-serialization-runtime-js:0.11.2-1.3.50-eap-5
   > Could not find org.jetbrains.kotlin:kotlin-stdlib-js:1.3.50-eap-5.
     Searched in the following locations:
       - https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.pom
       - https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.jar
       - https://kotlin.bintray.com/kotlin-js-wrappers/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.pom
       - https://kotlin.bintray.com/kotlin-js-wrappers/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.jar
       - https://kotlin.bintray.com/kotlinx/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.pom
       - https://kotlin.bintray.com/kotlinx/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.jar
     Required by:
         project : > org.jetbrains:kotlin-react:16.6.0-pre.70-kotlin-1.3.21 > org.jetbrains.kotlinx:kotlinx-html-js:0.6.12
   > Could not find org.jetbrains.kotlin:kotlin-stdlib-common:1.3.50-eap-5.
     Searched in the following locations:
       - https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.50-eap-5/kotlin-stdlib-common-1.3.50-eap-5.pom
       - https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.50-eap-5/kotlin-stdlib-common-1.3.50-eap-5.jar
       - https://kotlin.bintray.com/kotlin-js-wrappers/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.50-eap-5/kotlin-stdlib-common-1.3.50-eap-5.pom
       - https://kotlin.bintray.com/kotlin-js-wrappers/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.50-eap-5/kotlin-stdlib-common-1.3.50-eap-5.jar
       - https://kotlin.bintray.com/kotlinx/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.50-eap-5/kotlin-stdlib-common-1.3.50-eap-5.pom
       - https://kotlin.bintray.com/kotlinx/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.50-eap-5/kotlin-stdlib-common-1.3.50-eap-5.jar
     Required by:
         project : > org.jetbrains:kotlin-react:16.6.0-pre.70-kotlin-1.3.21 > org.jetbrains.kotlinx:kotlinx-coroutines-core-common:1.1.1
         project : > org.jetbrains:kotlin-react:16.6.0-pre.70-kotlin-1.3.21 > org.jetbrains.kotlinx:kotlinx-coroutines-core:1.1.1 > org.jetbrains.kotlin:kotlin-stdlib:1.3.20
   > Could not find org.jetbrains.kotlin:kotlin-stdlib-js:1.3.50-eap-5.
     Searched in the following locations:
       - https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.pom
       - https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.jar
       - https://kotlin.bintray.com/kotlin-js-wrappers/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.pom
       - https://kotlin.bintray.com/kotlin-js-wrappers/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.jar
       - https://kotlin.bintray.com/kotlinx/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.pom
       - https://kotlin.bintray.com/kotlinx/org/jetbrains/kotlin/kotlin-stdlib-js/1.3.50-eap-5/kotlin-stdlib-js-1.3.50-eap-5.jar
     Required by:
         project : > org.jetbrains:kotlin-react:16.6.0-pre.70-kotlin-1.3.21 > org.jetbrains.kotlinx:kotlinx-coroutines-core-js:1.1.1
   > Could not find org.jetbrains.kotlin:kotlin-stdlib-common:1.3.50-eap-5.
     Searched in the following locations:
       - https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.50-eap-5/kotlin-stdlib-common-1.3.50-eap-5.pom
       - https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.50-eap-5/kotlin-stdlib-common-1.3.50-eap-5.jar
       - https://kotlin.bintray.com/kotlin-js-wrappers/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.50-eap-5/kotlin-stdlib-common-1.3.50-eap-5.pom
       - https://kotlin.bintray.com/kotlin-js-wrappers/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.50-eap-5/kotlin-stdlib-common-1.3.50-eap-5.jar
       - https://kotlin.bintray.com/kotlinx/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.50-eap-5/kotlin-stdlib-common-1.3.50-eap-5.pom
       - https://kotlin.bintray.com/kotlinx/org/jetbrains/kotlin/kotlin-stdlib-common/1.3.50-eap-5/kotlin-stdlib-common-1.3.50-eap-5.jar
     Required by:
         project : > org.jetbrains:kotlin-react:16.6.0-pre.70-kotlin-1.3.21 > org.jetbrains.kotlinx:kotlinx-html-js:0.6.12 > org.jetbrains.kotlinx:kotlinx-html-common:0.6.12

**Comment by sandwwraith** [comment]
To try eap compiler versions, you need to add `maven { url 'https://kotlin.bintray.com/kotlin-eap' }` into your `repositories` Gradle section

**Comment by TorRanfelt** [comment]
@sandwwraith  Thanks.
