### ISSUE TITLE
[Question] How Decoder detect optional properties?

### ISSUE THREAD

**Issue by jershell** [Kotlin/kotlinx.serialization#531]
I write an addon. I don`t understand how to properly handle the absence of properties in the input

**Comment by sandwwraith** [comment]
It is detected by the generated serializer. If property value equals to its default value, then `CompositeDecoder#shouldEncodeElementDefault` is called to determine whether the property should be serialized (i.e. call to `encodeSomeElement` is performed)

**Comment by jershell** [comment]
Thank you for your answer. What do when necessary values not found in raw input by parse?

**Comment by sandwwraith** [comment]
This is also handled by the generated serializer in the `deserialize` method. It will throw an exception if a property is not optional and was not read. Validation happens right after `endStructure` call.

**Comment by jershell** [comment]
Thx! I get it
