### ISSUE TITLE
Release with Kotlin 1.3.50 EAP 3

### ISSUE THREAD

**Issue by MariusVolkhart** [Kotlin/kotlinx.serialization#534]
**What is your use-case and why do you need this feature?**
I am trying to confirm a bug fix in the 1.3.50 EAP 3 release when used with `kotlinx.serialization`. I'd also like to confirm that the 1.3.50 EAP 3 release works for all my use cases.

**Describe the solution you'd like**
A release of the `0.11.1` or `0.11.2` code with Kotlin 1.3.50 EAP 3, similar to the `0.11.2-1.3.50-eap-5` release.

**Comment by sandwwraith** [comment]
1.3.50 complete release is near, so it would not take much time before new library release. Meanwhile, to test the fix, you can build the library locally from `dev` branch. Kotlin version is set in `gradle.properties` file.

**Comment by sandwwraith** [comment]
Version `0.12.0` is compatible with `1.3.50`
