### ISSUE TITLE
Missing isQuoted property for decoder/JsonInput/JsonElement to asssit in Mixed Type Deserializer

### ISSUE THREAD

**Issue by diegomontoya** [Kotlin/kotlinx.serialization#536]
**What is your use-case and why do you need this feature?**

We need to decode a mixed type array that can be either Long or String.sing current API, we cannot distinguish between json long/number literal of 1 vs "1" since JsonInput.decodeJson().primitive or other methods does not expose wether the json value was actually quoted or not.  Please note "7" and 7 are not equal for us. Without isQuoted for JsonElement, it is impossible to distinguish the two. 

**Describe the solution you'd like**

We need a isQuoted property for JsonElement or related API so we can accurately decode Mixed Values via our custom serializers.

jsonInput.decodeJson().primitive.isQuoted 

Please help. Thank you.

**Comment by diegomontoya** [comment]
Note that even though JsonLiteral has a isString property, using it to do decoding still cannot distinguish "7" and 7 since during the decode stage, it calls decoder.decodeString which strips all quotes and jsonLiteral assumes isString is true.

```
    override fun deserialize(decoder: Decoder): JsonLiteral {
        verify(decoder)
        return JsonLiteral(decoder.decodeString())
    }
```

Our primary issue is that decoder.decodeString() retuns UNQUOTED string value of json literals regadless if they are actually non-string json primitives or real json quoted strings. There must be a way to distinguish them.

**Comment by diegomontoya** [comment]
May also be a bug. https://github.com/Kotlin/kotlinx.serialization/issues/537

**Comment by diegomontoya** [comment]
Related to pull request https://github.com/Kotlin/kotlinx.serialization/pull/386

**Comment by sandwwraith** [comment]
So when #537 get fixed, it would be sufficient to check `isString` property for your use-case, right?

**Comment by diegomontoya** [comment]
@sandwwraith  Yes if #537 fixed, this issue is also fixed since user can use isString to resolve this issue.
