### ISSUE TITLE
JsonLiteralSerializer deserialize is broken. isString is always true. 

### ISSUE THREAD

**Issue by diegomontoya** [Kotlin/kotlinx.serialization#537]
**Describe the bug**

JsonLiteralSerializer cannot correctly set isString to false for json primitives such as boolean/number that are unquoted.

**To Reproduce**

Call JsonLIteralDeserializer for "7" and 7.

**Expected behavior**

"7" should return a JsonIteral with isString set to true.
7 should return a jsonLiteral with isString set to false.

Code for JsonLiteralSerializer code below.

```
    override fun deserialize(decoder: Decoder): JsonLiteral {
        verify(decoder)
        return JsonLiteral(decoder.decodeString())
    }
```

decoder.decodeString will always return a string which sets isString to true.

**Comment by diegomontoya** [comment]
Related: https://github.com/Kotlin/kotlinx.serialization/issues/536

**Comment by diegomontoya** [comment]
Related: https://github.com/Kotlin/kotlinx.serialization/pull/386

**Comment by nanodeath** [comment]
FWIW, this actually worked as expected:

```kotlin
override fun deserialize(decoder: Decoder): Id {
    decoder as JsonInput
    val el = decoder.decodeJson() as? JsonLiteral ?: throw JsonException("id was not a literal")
    return if (el.isString) Str(el.content)
    else el.intOrNull?.let { Int(it) } ?: throw JsonException("${el.content} was neither string nor int")
}
```

**Comment by diegomontoya** [comment]
@nanodeath You misunderstand the issue. The problem is the decoder/end-user absolutely need to distinguish "7" and 7. They are completely different values. 

Example, imagine you encode an array of mixed values of both string and int. 

[ "7", 7, "1", 1 ]

And then try to decode to ArrayList<Any>. 

Due to the current decodeLiteral code, JsonLiteral.isString() will always return true. This is wrong. Without this change, how can we implement mixed value decoders on the native platform?

**Comment by nanodeath** [comment]
It was a workaround, not a long-term solution 🙂
