### ISSUE TITLE
TaggedEncoders / TaggedDecoders can't serialize primitives types directly

### ISSUE THREAD

**Issue by natanfudge** [Kotlin/kotlinx.serialization#538]
**Describe the bug**
If you have a `TaggedEncoder` and try to directly encode a primitive using its serializer (i.e encode `2` using `IntSerializer`) then you get a `kotlinx.serialization.SerializationException: No tag in stack for requested element` error. You also get a `IndexOutOfBoundsException` if you decode using the primitive serializer without encoding first (same root cause). 

**To Reproduce**
- Put this code in `kotlinx.serialization.example.example-jvm.srcNamedMapDemo`:
```kotlin
fun main() {
    val obj = 2
    val serializer = Int.serializer()
    // save
    val out = MapOutput()
    out.encode(serializer, obj)
}
```
- Hit on run
Observe error:
```
Exception in thread "main" kotlinx.serialization.SerializationException: No tag in stack for requested element
	at kotlinx.serialization.TaggedEncoder.popTag(Tagged.kt:160)
	at kotlinx.serialization.TaggedEncoder.encodeInt(Tagged.kt:98)
	at kotlinx.serialization.internal.IntSerializer.serialize(Primitives.kt:75)
	at kotlinx.serialization.internal.IntSerializer.serialize(Primitives.kt:72)
	at kotlinx.serialization.Encoder$DefaultImpls.encodeSerializableValue(Coders.kt:42)
	at kotlinx.serialization.TaggedEncoder.encodeSerializableValue(Tagged.kt:33)
	at kotlinx.serialization.CoreKt.encode(Core.kt:73)
	at NamedMapDemoKt.main(NamedMapDemo.kt:70)
	at NamedMapDemoKt.main(NamedMapDemo.kt)
```
To get `IndexOutOfBounds` do this instead:
```kotlin
fun main() {
    val serializer = Int.serializer()
    // load
    val inp = MapInput(mapOf())
    inp.decode(serializer)
}
```

**Expected behavior**
The `TaggedEncoder` will successfully encode the `int`. Then if you decode with the matching `TaggedDecoder` it will retrieve `2`. 
With the `IndexOutOfBounds` I expect to get an error of the form "missing field" instead of an `IndexOutOfBoundsException`.

**Environment**
- Kotlin version: 1.3.50-eap-5
- Library version: Master branch, also in 0.11
- Kotlin platforms: JVM at least
- Gradle version: 4.10.3, also in 5.6
IDE version Intellij IDEA 2019.2.1
OS: Windows 10, JDK: the one used in the master branch and also jdk8

**Comment by sandwwraith** [comment]
Well, it may be a bug, but this also a design issue. See, `TaggedEncoder` is called tagged because it tries to associate some _tag_ with a given value. E.g. for `NamedEncoder`, it is a property name in class; for a more general case, it is something that can be obtained from a descriptor and index (via `getTag`) – i.e. from the containing structure.

Now, if we put some primitive in it, we don't have the index in a class or a property name – because this primitive is not inside any class. Probably this issue can be resolved via some synthetic `<root>` tag, but this looks more like a workaround.

**Comment by pdvrieze** [comment]
@natanfudge If you are doing this as part of making your own encoder, it may be better to directly implement `Encoder` and `CompositeEncoder` (as well as the decoder counterparts). `TaggedEncoder` is a utility class that makes some things easier, but also introduces limitations.

**Comment by natanfudge** [comment]
@pdvrieze Indeed, I have my own version of `TaggedEncoder` that allows for further customization. 

However, the default implementation should produce predictable results - either by just working or by throwing an error indicating this operation is not supported.

**Comment by sandwwraith** [comment]
In 1.0, `TaggedEncoder/Decoder` will be an internal class: it was not designed for general use, and the result is issues like this one.
