### ISSUE TITLE
TaggedEncoders / TaggedDecoders can't serialize nullable types directly

### ISSUE THREAD

**Issue by natanfudge** [Kotlin/kotlinx.serialization#539]
**Describe the bug**
If you have a` TaggedEncoder` and try to directly encode a nullable value using its serializer (i.e encode `MyData?` using `makeNullable(MyData.serializer())` ) then you get a `java.util.NoSuchElementException: List is empty` error.   
Seems related to #538.
**To Reproduce**
Attach a code snippet or test data if possible.
- Put this code in `kotlinx.serialization.example.example-jvm.srcNamedMapDemo`:
```kotlin
@Serializable
data class MyData(val int : Int, val str :String)

fun main() {
    val obj : MyData? = MyData(123,"hello")
    val serializer = makeNullable(MyData.serializer())
    // save
    val out = MapOutput()
    out.encode(serializer, obj)
}
```
- Hit on run
Observe error:
```
Exception in thread "main" java.util.NoSuchElementException: List is empty.
	at kotlin.collections.CollectionsKt___CollectionsKt.last(_Collections.kt:360)
	at kotlinx.serialization.TaggedEncoder.getCurrentTag(Tagged.kt:148)
	at kotlinx.serialization.TaggedEncoder.encodeNotNullMark(Tagged.kt:91)
	at kotlinx.serialization.internal.NullableSerializer.serialize(NullableSerializer.kt:35)
	at kotlinx.serialization.Encoder$DefaultImpls.encodeSerializableValue(Coders.kt:42)
	at kotlinx.serialization.TaggedEncoder.encodeSerializableValue(Tagged.kt:33)
	at kotlinx.serialization.CoreKt.encode(Core.kt:73)
	at NamedMapDemoKt.main(NamedMapDemo.kt:60)
	at NamedMapDemoKt.main(NamedMapDemo.kt)
```
**Expected behavior**
The `TaggedEncoder` will successfully encode the `MyData?`. Then if you decode with the matching `TaggedDecoder` it will retrieve `MyData(123,"hello")`.

**Note**
This is NOT related to the fact `MapOutput()` does not support nullable values. If it was so a  "null is not supported" error would be printed. Additionally, my own encoder does support nulls and faces the same problem.

**Environment**
- Kotlin version: 1.3.50-eap-5
- Library version: Master branch, also in 0.11
- Kotlin platforms: JVM at least
- Gradle version: 4.10.3, also in 5.6
- IDE version Intellij IDEA 2019.2.1
- OS: Windows 10, JDK: the one used in the master branch and also jdk8

**Comment by pdvrieze** [comment]
This is related to the fact that the system is designed with the idea that the top level element (the element that you initially call serialization on) is not nullable. Note that such a thing would not be supported by many formats anyway (JSON and XML don't support it).

In general you are expected to encode a null root value as the absence of any serialized form (missing file). Having said that, while various encoders/decoders cannot support it, I see no reason why TagEncoder and TagDecoder could not do so for a format where a null base value is acceptable.

**Comment by JakeWharton** [comment]
JSON supports top-level nullable types with just the scalar "null" sent (as
4 bytes, without quotes). Other scalar values such as strings and numbers
can be sent top-level as well, it's not just objects or arrays.

**Comment by pdvrieze** [comment]
@JakeWharton You're right.

**Comment by sandwwraith** [comment]
The cause is basically the same as in #538: `null` is a primitive element.

See my [comment](https://github.com/Kotlin/kotlinx.serialization/issues/538#issuecomment-522931624) there.
