### ISSUE TITLE
.serializer() function unresolved in test module for classes from main module (gradle)

### ISSUE THREAD

**Issue by mukoki** [Kotlin/kotlinx.serialization#54]
I have the following data class
```
@Serializable
data class Toto<T>(
    @Serializable(with=ClassSerializer::class) val type:Class<T>
)
```
(ClassSerializer is an object defined with the tag @Serializer(forClass = Class::class))

I try to serialize an instance of my Class Toto this way
```
@Test
public fun testToto() {
    val toto = Toto(String::class.java)
    println(JSON.stringify(Toto.serializer(StringSerializer), toto))
}
```

After many troubles including the java.lang.NoSuchFieldException: INSTANCE problem, I could serialize the Toto class when its definition is included in the same file as my Test, but I did not succeed with the Toto class defined in another file. I always have the following error 

```
Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public fun <T : Any> KClass<Toto<String>>.serializer(): KSerializer<Toto<String>> defined in kotlinx.serialization
```
Could you please give me some hint to explain where my mistake is

**Comment by sandwwraith** [comment]
Seeing this error is rather strange. It means that lookup was trying to use extension function on `KClass` instead of function from companion object. You can try to write explicitly `Toto.Companion.serializer(..)`. If there would be no companion object, it means that plugin didn't work on your another file for some reason. I think it would be nice if submit an example project, where this issue reproduces.

Btw, can I take a look at yours `ClassSerializer`? Just curious.

**Comment by mukoki** [comment]
Thanks for your response.

If I write `Toto.Companion.serializer()` instead of just `Toto.serializer()`, I get exactly the same error message.
In both cases (working case with local Toto class and not working case with distant Toto class), the method "serializer" (or word "Companion") are not recognized by the IDE (IntelliJ IDEA) : it is written in red.
My testing class is in the test directory while Toto class is in the main directory. Toto class is in the import section of the test class.
And finally here is my ClassSerializer,
```
@Serializer(forClass = Class::class)
object ClassSerializer: KSerializer<Class<*>> {

    override fun save(output: KOutput, obj: Class<*>) {
        output.writeStringValue(obj.name)
    }

    override fun load(input: KInput): Class<*> {
        return Class.forName(input.readStringValue())
    }

    override val serialClassDesc: KSerialClassDesc = SerialClassDescImpl("java.lang.Class")
}
```

**Comment by sandwwraith** [comment]
It's okay that it is not recognized by IDE (see [here](https://github.com/kotlin/kotlinx.serialization#working-in-intellij-idea)). Does gradle build also gails in your case?

**Comment by mukoki** [comment]
Thanks again. I found this is probably a problem with gradle. When I refresh my gradle project, it seems it creates two subprojects, one containing main directory and the other containing test directory. If I put all my classes in the same subdirectory, it seems to work.
Sorry for the noise, I must familiarize with gradle first,

**Comment by sandwwraith** [comment]
Classes from main module should be visible in test module.

Anyway, I suppose this issue can be closed now?

**Comment by mukoki** [comment]
I un-checked option "Create separate module per source set", but I still get the exception.
My Toto class is visible from the test directeory as I can print an instance of Toto
println(toto) -> OK
println(JSON.stringify(Toto.serializer(StringSerializer), toto)) -> Exception
Sorry, probably a misuse of the library, I will try to simplify my test case to the bare minimum.

**Comment by mukoki** [comment]
I uploaded a few files to demonstrate the problem :
[https://github.com/mukoki/serialization-test]
In this project, testTiti succeeds but testToto fails
Thanks for your patience

**Comment by sandwwraith** [comment]
Yep, now I understand what you're talking about. Seems gradle can't resolve synthetic function descriptors across modules for some reason. It's not limited to generics only, usual `.serializer()` don't work too. I need to investigate more to determine if it's plugin, compiler or gradle issue.

**Comment by sandwwraith** [comment]
BTW: running tests from IDEA (build is not delegated to gradle, additional serialization plugin installed to idea) makes them work :)

**Comment by sandwwraith** [comment]
Okay, the problem is that some extension points in compiler (particularly, that one that call plugin for resolve extension function) were merged in upstream recently and are not available in stable release yet. You can set kotlin version to `1.2.20-eap-11` (don't forget to add ` maven { url "https://dl.bintray.com/kotlin/kotlin-eap" }` to repositories; that makes things work

**Comment by mukoki** [comment]
Yeah ! works fine with 1.2.20-eap-11, thanks ! I close the ticket.
