### ISSUE TITLE
It is possible to parse Array of Arrays?

### ISSUE THREAD

**Issue by mr-gil** [Kotlin/kotlinx.serialization#540]
I have the next valid JSON. but its possible to parse directly the array with the library, i could'nt found information about how to do it . 

> [
>  [
>    {
>      "body": "Text",
>      "bodyType": "Text",
>      "nameType": "Text",
>      "makeDisplay": "Acura"
>    }
>  ],
>  [
>    {
>      "body": "text",
>      "bodyType": "text",
>      "nameType": "text",
>      "makeDisplay": "text"
>    }
>  ]
> ]

**Comment by Dominaezzz** [comment]
Yes this is possible. You can parse it into a `List<List<Type>>`. You can can make a serializer using `Type.serializer().list.list`.
