### ISSUE TITLE
Custom serializer has started yielding "missing context serializer as fallback" error

### ISSUE THREAD

**Issue by TorRanfelt** [Kotlin/kotlinx.serialization#543]
The reason I'm making my own serializers is because primitive arrays (like DoubleArray) are not supported yet. I have done this the way it has been recommended and has so far worked:

```
    @Serializable(DoubleMatrixSerializer::class)
    val foo: Array<DoubleArray> = Array(2) { DoubleArray(2) }
```

```
object DoubleMatrixSerializer : KSerializer<Array<DoubleArray>> {
    override val descriptor = ArrayListClassDesc(DoubleArraySerializer.descriptor)

    override fun serialize(encoder: Encoder, obj: Array<DoubleArray>) {
        encoder.encodeSerializableValue(ArrayListSerializer(DoubleArraySerializer), obj.asList())
    }

    override fun deserialize(decoder: Decoder): Array<DoubleArray> {
        val list = decoder.decodeSerializableValue(ArrayListSerializer(DoubleArraySerializer))
        return list.toTypedArray()
    }
}
```

```
object DoubleArraySerializer : KSerializer<DoubleArray> {
    override val descriptor = ArrayListClassDesc(DoubleDescriptor)

    override fun serialize(encoder: Encoder, obj: DoubleArray) {
        encoder.encodeSerializableValue(ArrayListSerializer(DoubleSerializer), obj.asList())
    }

    override fun deserialize(decoder: Decoder): DoubleArray {
        val list = decoder.decodeSerializableValue(ArrayListSerializer(DoubleSerializer))
        return list.toDoubleArray()
    }
}
```

However, using kotlin 1.3.50, kotlinx-serialization-runtime-js:0.12.0, and IntelliJ 2019.2.1 I suddenly get an error:
Serializer has not been found for type 'DoubleArray'. To use context serializer as fallback, explicitly annotate type or property with @ContextSerialization.

I have read https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/custom_serializers.md#contextualserialization-annotation, but I don't feel it apply here since I have already specified DoubleMatrixSerializer, so the context should be explicit. As in it's the DoubleMatrixSerializer's job to figure out to do with DoubleArray. Could it be any other way, how so, and is that the reason for the error?

**Comment by sandwwraith** [comment]
You can use
```kotlin
@Serializable(DoubleMatrixSerializer::class)
    val foo: Array<@Serializable(DoubleArraySerializer::class) DoubleArray> = Array(2) { DoubleArray(2) }
```

Technically, this shouldn't have been working before 1.3.50 too – serializers for generic classes (such as your `DoubleMatrixSerializer`) should have constructor parameters – serializers for actual generic arguments (see more [here](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/custom_serializers.md#about-generic-serializers)). However, due to plugin's bug/feature serializer `object`s still can be instantiated without passing actual serializers for actual generic arguments (`DoubleArray` in your case). IDE declaration checker does not have this flaw, therefore diagnostic is reported.

**Comment by TorRanfelt** [comment]
@sandwwraith 
Is what I have done something that shouldn't work and will stop working? That is doing what I already was doing and adding @file:ContextualSerialization(DoubleArray::class).

It is a temporary solution until static arrays are supported by kotlinx.serialization (like Array, DoubleArray and IntArray), but if it will suddenly stop working - because DoubleMatrixSerializer must get its internal serializer from a constructor argument - it is better I change the temporary solution now.

**Comment by sandwwraith** [comment]
We may reconsider design decision and allow using `object` serializers on generic classes for any number of arguments. 

By the way, kotlinx.serialization already have `ReferenceArraySerializer` for serializing `Array<T>`, so `val foo: Array<@Serializable(DoubleArraySerializer::class) DoubleArray>` should work even without `DoubleMatrixSerializer`.
