### ISSUE TITLE
Contextual serializations & non-static serializers

### ISSUE THREAD

**Issue by charlag** [Kotlin/kotlinx.serialization#544]
I'm trying to use kotlinx.serialization in my multiplatform project and I'm running into some issues with it.

First or all, I'm operating on the encrypted data. It's a json where some fields are encrypted (AES, then Base64). There's a scheme of what is of which type and and what is encrypted (looks like [this](https://github.com/tutao/tutanota/blob/master/src/api/entities/tutanota/Mail.js)). There's an existing solution in JS (https://github.com/tutao/tutanota/blob/master/src/api/worker/crypto/CryptoFacade.js#L362) and I'm trying to replicate it now. Keys for encryption/decryption depend on one of the fields on the object and I need to look them up dynamically.

After reading documentation I had an idea start contextual serialization is what I need: I would just register one deserializer for all my classes and will look up things in schema & keys in some runtime mapping (and serializer can be non-static then). Unfortunately I don't see how to do two things:
 - Register my serializer for the whole class (as opposed to the field If I put annotation on the whole file and specify the classes, it will still only use it for fields inside the file).
 - Override serializers for the built-ins/primitives. Docs say "on a property with type which **does not have default serializer.**" (emphasis mine). I could re-wrap all my encrypted String fields into the new type EncryptedString but ergonomics are far from great then. Same goes for Number, Date and some other fields.

Maybe I miss something? Maybe kotlinx.serialization is just not for my user case? I would be glad to hear any thoughts about my case.

**Comment by charlag** [comment]
Update: seems like if I'm setting the mapping directly on the deserializer, it picks it up. Setting it in the `serializersModuleOf` doesn't give much

**Comment by sandwwraith** [comment]
`@Serializable(with=MySerializer::class)` or `@ContextualSerialization` should also override default serializers, even for ints, strings, etc. If they do not do so, it's a bug.

The good idea is probably to write a custom serializer for class with encrypted fields which reads stream into `JsonObject` (see [sample](https://github.com/kotlin/kotlinx.serialization/blob/45aa7c7ab97f25f205408b46a7069886408bce6b/runtime/commonTest/src/kotlinx/serialization/json/JsonInputOutputRecursiveTest.kt#L144)) , then decrypt it and return the object instance.

**Comment by charlag** [comment]
Thank you for the answer
I figured what was the problem. I didn't implement dumpTo and it is used right away by `Json`:
https://github.com/Kotlin/kotlinx.serialization/blob/master/runtime/commonMain/src/kotlinx/serialization/json/Json.kt#L63
So any dynamic logic I implement won't work because I have to dump all mappings into some other `SerialModule` right away which kinda defeats the point?
Perfect situation for me would be "give me serializer for this class", "okay, let me look up this class and give you a serializer for it" (which interface kinda implies). Instead I have to load all my classes and models on startup and put them into one huge map which is not perfect for performance. It could be fixed by not dumping all the serial modules into one map but asking each of them in succession (with user defined ones first) but I guess that's not the only solution?

For myself I will probably just use `setMapper` instead but it's just pity that it's more of a workaround.

**Comment by sandwwraith** [comment]
Yeah, collecting all serializers into one module via `dumpTo` was designed with performance and predictability of result (independent from the module order) in mind, but it seems there are some use cases for manual `SerialModule` implementation, where this stops working – some lazy load or default serializer for unknown class (#514).

**Comment by charlag** [comment]
Fwiw I discovered that I need to do network requests which is async (and also SubtleCrypto is async) so my strategy now is to serialize simly into map and do decryption/processing and then JSON outside.

**Comment by charlag** [comment]
Another possible design point: I don't think it's possible to decode byte arrays?
In my situation I took JSON response (as `JsonObject`), decrypted the fields I need and got `Map<String, Any?>`. One of the JSON fields is Base64 encoded byte array so I decoded and decrypted it. But default serializer cannot map `ByteArray` to `ByteArray` because there's no default decoder for it. I tried to write my own: (horribly inefficient one but still)
```kotlin
    override fun deserialize(decoder: Decoder): ByteArray {
        return decoder.decodeSerializableValue(ArrayListSerializer(ByteSerializer))
            .toByteArray()
    }
```

and it fails to compile with
```
e: java.lang.IllegalStateException: Backend Internal error: Exception during code generation
Cause: Class ByteArray have constructor parameters which are not properties and therefore it is not serializable automatically
File being compiled at position: file:///home/charlag/AndroidStudioProjects/Tuta/SharedCode/src/commonMain/kotlin/entities/basic.kt
The root cause was thrown at: SerializerCodegen.kt:38
```

Do I miss something and there's a way to do map `ByteArray`? If not I would argue to extend `Coder`/`Decoder` interfaces to be able to grab binary data. Serializing it to Base64 just to deserialize again sounds... bad.

**Comment by Dominaezzz** [comment]
Have you mark the `ByteArray` property with `@Serializable(with=MySerializer::class)`?

**Comment by charlag** [comment]
Yeah like so:

```kotlin
@Serializable
data class SaltReturn(
    @Serializable(with = ByteArraySerializer::class)
    val salt: ByteArray
) : Entity
```

```kotlin
@Serializer(forClass = ByteArray::class)
object ByteArraySerializer : KSerializer<ByteArray> {
    override fun serialize(encoder: Encoder, obj: ByteArray) {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun deserialize(decoder: Decoder): ByteArray {
        return decoder.decodeSerializableValue(ArrayListSerializer(ByteSerializer))
            .toByteArray()
    }
}
```

**Comment by Dominaezzz** [comment]
Try removing the `@Serializer(forClass = ByteArray::class)`.

**Comment by charlag** [comment]
Woah, thanks a lot, it worked.. more or less

now it did quite weird thing with a key?

<details>
<summary>
stacktrace
</summary>

```
    Process: com.charlag.tuta, PID: 26730
    java.util.NoSuchElementException: Key salt.size is missing in the map.
        at kotlin.collections.MapsKt__MapWithDefaultKt.getOrImplicitDefaultNullable(MapWithDefault.kt:24)
        at kotlin.collections.MapsKt__MapsKt.getValue(Maps.kt:294)
        at kotlinx.serialization.Mapper$InNullableMapper.decodeTaggedValue(Mapper.kt:89)
        at kotlinx.serialization.Mapper$InNullableMapper.decodeTaggedValue(Mapper.kt:82)
        at kotlinx.serialization.TaggedDecoder.decodeTaggedInt(Tagged.kt:197)
        at kotlinx.serialization.Mapper$InNullableMapper.decodeCollectionSize(Mapper.kt:86)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.readSize(CollectionSerializers.kt:65)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.patch(CollectionSerializers.kt:42)
        at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:61)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Coders.kt:113)
        at kotlinx.serialization.TaggedDecoder.decodeSerializableValue(Tagged.kt:169)
        at com.charlag.tuta.entities.ByteArraySerializer.deserialize(basic.kt:31)
        at com.charlag.tuta.entities.ByteArraySerializer.deserialize(basic.kt:23)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Coders.kt:113)
        at kotlinx.serialization.TaggedDecoder.decodeSerializableValue(Tagged.kt:169)
        at kotlinx.serialization.TaggedDecoder$decodeSerializableElement$1.invoke(Tagged.kt:245)
        at kotlinx.serialization.TaggedDecoder.tagBlock(Tagged.kt:258)
        at kotlinx.serialization.TaggedDecoder.decodeSerializableElement(Tagged.kt:245)
        at com.charlag.tuta.entities.sys.SaltReturn$$serializer.deserialize(Unknown Source:53)
        at com.charlag.tuta.entities.sys.SaltReturn$$serializer.deserialize(sys-types.kt:494)
        at kotlinx.serialization.Decoder$DefaultImpls.decodeSerializableValue(Coders.kt:113)
        at kotlinx.serialization.TaggedDecoder.decodeSerializableValue(Tagged.kt:169)
        at kotlinx.serialization.CoreKt.decode(Core.kt:79)
        at kotlinx.serialization.Mapper.unmapNullable(Mapper.kt:118)
        at kotlinx.serialization.Mapper$Companion.unmapNullable(Mapper.kt:143)
        at com.charlag.tuta.API.deserializeEntitity(API.kt:167)
        at com.charlag.tuta.API.getSalt(API.kt:61)
        at com.charlag.tuta.API$getSalt$1.invokeSuspend(Unknown Source:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:215)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:172)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:122)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:215)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:172)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:122)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(PipelineContext.kt:215)
        at io.ktor.util.pipeline.SuspendFunctionGun.loop(PipelineContext.kt:172)
        at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(PipelineContext.kt:67)
        at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(PipelineContext.kt:122)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
        at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```
</details>

current code for it:

```kotlin
//@Serializer(forClass = ByteArray::class)
object ByteArraySerializer : KSerializer<ByteArray> {
    override val descriptor: SerialDescriptor = ArrayListClassDesc(ByteDescriptor)

    override fun serialize(encoder: Encoder, obj: ByteArray) {
        TODO("not implemented") //To change body of created functions use File | Settings | File Templates.
    }

    override fun deserialize(decoder: Decoder): ByteArray {
        return decoder.decodeSerializableValue(ArrayListSerializer(ByteSerializer))
            .toByteArray()
    }
}
```

I'm not sure if it must be some special map to have a key `salt.size`.

<details>
<summary>
Here's more of how it's used:
</summary>

This case is pretty simple and there are only two (value) fields: string and bytes

```kotlin
    suspend fun getSalt(mailAddress: String): SaltReturn {
        val address = Url(baseUrl + "sys/saltservice")
        val postData = SaltData(mailAddress = mailAddress)
        val response = httpClient.get<JsonObject> {
            url(address)
            parameter("_body", json.stringify(serializeEntity(postData)))
        }
        return deserializeEntitity(response, SaltReturn::class)
    }

    private suspend fun <T : Entity> deserializeEntitity(
        map: JsonObject,
        klass: KClass<T>
    ): T {
        val typeModel = getTypeModelByClass(klass)
        val sessionKey = resolveSessionKey(typeModel, map, this)
        val processedMap = decryptAndMapToMap(map, typeModel, sessionKey)
        val serializer = typeModelByName.getValue(klass.noReflectionName).serializer
        println("processedMap $processedMap")
        @Suppress("UNCHECKED_CAST")
        return Mapper.unmapNullable(serializer as KSerializer<T>, processedMap)
    }

    private suspend fun decryptAndMapToMap(
        map: JsonObject,
        typeModel: TypeModel,
        sessionKey: ByteArray?
    ): Map<String, Any?> {
        val decrypted = mutableMapOf<String, Any?>()
        for ((fieldName, valueModel) in typeModel.values) {
            decrypted[fieldName] =
                decryptValue(fieldName, valueModel, map[fieldName]!!, sessionKey)
        }
        for ((fieldName, assocModel) in typeModel.associations) {
            val value = map[fieldName]
            decrypted[fieldName] = if (value == null) {
                if (assocModel.cardinality == Cardinality.ZeroOrOne) null else error("No association $fieldName")
            } else {
                val refTypeModel = typeModelByName[assocModel.refType]!!.typemodel
                @Suppress("UNCHECKED_CAST")
                when (assocModel.type) {
                    AssociationType.AGGREGATION -> when (assocModel.cardinality) {
                        Cardinality.Any -> (value as JsonArray).map {
                            decryptAndMapToMap(it as JsonObject, refTypeModel, sessionKey)
                        }
                        else -> decryptAndMapToMap(
                            value as JsonObject,
                            refTypeModel,
                            sessionKey
                        )
                    }
                    else -> value
                }
            }
        }
        return decrypted
    }

    private suspend fun decryptValue(
        name: String,
        valueModel: Value,
        encryptedValue: JsonElement,
        sessionKey: ByteArray?
    ): Any? {
        return if (encryptedValue.isNull) {
            if (valueModel.cardinality === Cardinality.ZeroOrOne) {
                null
            } else {
                error("Value $name is null")
            }
        } else if (valueModel.encrypted) {
            val decryptedBytes = cryptor.decrypt(base64ToBytes(encryptedValue.primitive.content), sessionKey!!)
            when (valueModel.type) {
                ValueType.BytesType -> decryptedBytes
                else -> valueFromString(encryptedValue.primitive.content, valueModel)
            }
        } else {
            valueFromString(encryptedValue.primitive.content, valueModel)
        }
    }

    private fun valueFromString(value: String, valueModel: Value): Any? {
        return when (valueModel.type) {
            ValueType.BooleanType -> value != "0"
            ValueType.NumberType -> value.toLong()
            ValueType.DateType -> Date((value.toLong()))
            ValueType.BytesType -> base64ToBytes(value)
            ValueType.StringType,
            ValueType.CustomIdType,
            ValueType.GeneratedIdType -> value
        }
    }

```

</details>

**Comment by Dominaezzz** [comment]
That's a lot of code but the problem is probably in `Mapper.unmapNullable(serializer as KSerializer<T>, processedMap)`. :slightly_smiling_face: .

What's wrong with just doing `httpClient.get<SaltReturn>`?

**Comment by charlag** [comment]
In this case I could do it but when some fields are encrypted I need to unencrypted them and map some data types (like proposed above).
I will check that it's correct serialized but I'm pretty sure it is, otherwise my serialized wouldn't be called.

**Comment by charlag** [comment]
Okay I did some experiments and it seems like `Mapper` expect some very specific format:

```kotlin
@Serializable
data class Test(val elements: Array<Int>)
val mapped = Mapper.map(Test.serializer(), Test(elements = arrayOf(1, 2, 3)))
println(mapped.toString()) // {elements.size=3, elements.0=1, elements.1=2, elements.2=3}
```

so it encodes nested elements using dot. Maybe I shouldn't use `Mapper` at all and should use `JsonObject` everywhere. It's just... weird. Why can't it just encode it as array? performance reasons? But this map can get huge then?..
Well, at least one should forget about using `Mapper` I guess

**Comment by sandwwraith** [comment]
I think your first problem was that you forgot to override `descriptor` and plugin was trying to generate its automatically, therefore ` Class ByteArray have constructor parameters which are not properties and therefore it is not serializable automatically`. 

Regarding `Mapper`, it's better to use `JsonObject` because it is anyway backed by the map. `Mapper` should be deprecated and renamed to `Properties`, because it's actually Java properties format (which is also a map, but flat)

**Comment by charlag** [comment]
Ah, okay, now I understand what Mapper does
I actually ended up writing my own simple Mapper, maybe it's not generic enough but it works for me. Is anyone from the project interested in having it?

**Comment by charlag** [comment]
I'm closing this as I understand that what I wanted to do doesn't fit nto the framework. How it works currently is two staged: one is reading JSON from bytes, decrypting and manipulating to make normal Map out of it (could keep it JSON I guess but with some overhead). The second step is invoking serialization using my Mapper as `Decoder` to get a real instance. This way I can do what I need between the two serialization steps.
I'm still fixing bugs in mapper and I could send a PR later, I think it's nice to test against too.

**Comment by charlag** [comment]
(also I wouldn't be able to use Json map because Json has no byte arrays)
