### ISSUE TITLE
Copy function does not work for JsonConfiguration in Java-Script

### ISSUE THREAD

**Issue by TorRanfelt** [Kotlin/kotlinx.serialization#550]
`JsonConfiguration.Stable.copy(classDiscriminator = "foobar")`

Uncaught TypeError: JsonConfiguration.Companion.Stable.copy_qyeq5q$ is not a function

**Comment by sandwwraith** [comment]
`JsonConfiguration.copy` signature was changed between 0.11.1 and 0.12.0. Make sure you have increased version in every dependency configuration and do a clean build.

**Comment by TorRanfelt** [comment]
Thanks. *embarrassed* :)

**Comment by sandwwraith** [comment]
Did it help? Published artifacts should not be broken, but just in case, let me know.

**Comment by TorRanfelt** [comment]
Yes. It helped.
