### ISSUE TITLE
@Transient disallows lateinit

### ISSUE THREAD

**Issue by NikkyAI** [Kotlin/kotlinx.serialization#553]
**Describe the bug**

error: `This property is marked as @Transient and therefore must have an initializing expression`

**To Reproduce**

```
@Transient 
lateinit var rootDir: File
```

the lateinit variable would be initialized after deserialization

full example:

```
import kotlinx.serialization.Serializable
import kotlinx.serialization.Transient
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonConfiguration
import kotlin.random.Random

@Serializable
data class Foo(
    val number: Int
) {
    @Transient
    lateinit var runtimeValue: Int

    val calculated: Int
        get() = runtimeValue / number
}

fun main() {
    val json = Json(JsonConfiguration.Stable)

    val foo: Foo = json.parse(Foo.serializer(), """{ "number": 23 }""")
    foo.runtimeValue = Random.nextInt()

    println(foo.calculated)
}
```

**Expected behavior**

should pass compilation like it did on 1.3.41

**Environment**
 - Kotlin version: 1.3.50
 - Library version: 0.12.0
 - Kotlin platforms: JVM
 - Gradle version: 5.5

**Comment by abelkov** [comment]
Related Youtrack issue: https://youtrack.jetbrains.com/issue/KT-33630
