### ISSUE TITLE
Add support for tvOS and watchOS-based targets

### ISSUE THREAD

**Issue by sbogolepov** [Kotlin/kotlinx.serialization#568]
**What is your use-case and why do you need this feature?**
Kotlin/Native 1.3.60 will add support for tvOS and watchOS-based targets. It's important for application developers to have the same set of libraries for all Apple's targets.

**Describe the solution you'd like**
Since these targets are similar to iOS-based targets, adding them to the appropriate `build.gradle` should be sufficient.
Targets:
* watchos_x86
* watchos_arm32
* watchos_arm64
* tvos_x64
* tvos_arm64

**Comment by sandwwraith** [comment]
They'll be available in next release
