### ISSUE TITLE
FR: please support flatbuffers (tensorflow lite's choice)

### ISSUE THREAD

**Issue by salamanders** [Kotlin/kotlinx.serialization#57]
[Tensorflow Lite](https://www.tensorflow.org/mobile/tflite/) has opted to use [flatbuffers](https://google.github.io/flatbuffers/), which sound great and super efficient.  Can these be added as a supported default?

**Comment by LouisCAD** [comment]
Support for FlatBuffers could be really nice for Kotlin, especially with it's property syntax. It'd be useful for games, and other apps that need to read extremely efficiently from serialized data.

Note that there have been attempts to add Kotlin support to the flatbuffers repo that could be useful for future work. There's 3 pull requests here: https://github.com/google/flatbuffers/pulls?utf8=%E2%9C%93&q=kotlin

**Comment by qwwdfsad** [comment]
It's not our goal to implement and maintain formats beyond the most basic ones, so closing as "Won't fix".

Flatbuffers is a `byte[]`-based format that requires changes in the data classes itself and it's unlikely that it is possible to implement it on top of `kotlinx.serialization`
