### ISSUE TITLE
Cannot import project for kotlin multiplatform

### ISSUE THREAD

**Issue by avjiang** [Kotlin/kotlinx.serialization#573]
Hello guys, i am new to kotlin multiplatform and having issue in importing this library. I have tried to follow other issue that is also discussing about the @serializable issue, but still couldn't find out what is wrong

When I call the @Serializable annotation and Json() function, the compiler wont detect those 2. For serializable, the compiler said it is in internal kotlin.io. Also when I try to manually import the kotlinx. the compiler also wont detect it.  I have no problem in importing other kotlin multiplatform library.

I am trying to call the Json() function inside my common.kt in commonMain folder.

Here are my setups 

 `SharedCode build.gradle `

     apply plugin: 'kotlin-multiplatform
     apply plugin: 'kotlinx-serialization  
        
        kotlin {
            targets {
                final def iOSTarget = presets.iosX64 // Simulator
        
                fromPreset(iOSTarget, 'iOS') {
                    binaries {
                        framework('SharedCode')
                    }
                }
        
                fromPreset(presets.jvm, 'android')
            }
        
            sourceSets {
                commonMain {
                    dependencies {
                        api 'org.jetbrains.kotlin:kotlin-stdlib-common'
                        implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:1.3.50"
                    }
                }
        
                iosMain {
                    dependencies {
                        implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:1.3.50"
                    }
                }
        
                commonTest {
                    dependencies {
                        api 'org.jetbrains.kotlin:kotlin-stdlib-common'
                        implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:1.3.50"
                        implementation kotlin('test-common')
                        implementation kotlin('test-annotations-common')
                    }
                }
        
                androidMain.dependencies {
                    api 'org.jetbrains.kotlin:kotlin-stdlib'
                }
            }
        }

       configurations {
            compileClasspath
        }

        task packForXCode(type: Sync) {
            final File frameworkDir = new File(buildDir, "xcode-frameworks")
            final String mode = project.findProperty("XCODE_CONFIGURATION")?.toUpperCase() ?: 'DEBUG'
            final def framework = kotlin.targets.iOS.binaries.getFramework("SharedCode", mode)
        
            inputs.property "mode", mode
            dependsOn framework.linkTask
        
            from { framework.outputFile.parentFile }
            into frameworkDir
        
            doLast {
                new File(frameworkDir, 'gradlew').with {
                    text = "#!/bin/bash\nexport 'JAVA_HOME=${System.getProperty("java.home")}'\ncd '${rootProject.rootDir}'\n./gradlew \$@\n"
                    setExecutable(true)
                }
            }
        }
        tasks.build.dependsOn packForXCode

 `build.gradle`

          buildscript {
            ext.kotlin_version = '1.3.50'
            repositories {
                google()
                jcenter()
                maven { url "https://kotlin.bintray.com/kotlinx" }
            }
        
            dependencies {
                classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
                classpath "org.jetbrains.kotlin:kotlin-serialization:$kotlin_version"
            }
        }
        
        allprojects {
            repositories {
                google()
                jcenter()
            }
        }
        
        task clean(type: Delete) {
            delete rootProject.buildDir
        }

`settings.gradle`

        include ':app', ':SharedCode'
        include ':SharedCode'
        
        enableFeaturePreview('GRADLE_METADATA')

I am using Gradle version : 5.4.1
Can someone guide me on what I have to do? Thanks

**Comment by sandwwraith** [comment]
Hi,
You need to use `0.13.0` as a version for `kotlinx-serialization-runtime-common`.

You also need to specify `kotlinx-serialization-runtime-native` instead of `-common` inside of `iosMain` block, and `kotlinx-serialization-runtime` inside `androidMain`. See sample here: https://github.com/Kotlin/kotlinx.serialization#multiplatform-common-js-native

**Comment by avjiang** [comment]
Hi @sandwwraith, thanks for the quick reply. 

I can import the library now, but when I want to compile it to iOS, i am having this error 

`The Kotlin source set iosMain was configured but not added to any Kotlin compilation. You can add a source set to a target's compilation by connecting it with the compilation's default source set using 'dependsOn'.`

here is my gradle configuration

                 sourceSets {
                    commonMain {
                        dependencies {
                            implementation kotlin('stdlib-common')
                            implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:$serialization_version"
                        }
                    }
        
                    iosMain {
                       dependsOn commonMain
                        dependencies {
                            implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime-native:$serialization_version"
                        }
                    }
        
                    androidMain.dependencies {
                        api 'org.jetbrains.kotlin:kotlin-stdlib'
                        implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime:$serialization_version"
                    }
        
                    commonTest {
                        dependencies {
                            implementation kotlin('test-common')
                            implementation kotlin('test-annotations-common')
                        }
                    }
                }

Do you know what should I do? Seems like the dependsOn in iOSMain block doesn't work

**Comment by sandwwraith** [comment]
I think it should be called `iOSMain` (with big letters OS) because you have ` fromPreset(iOSTarget, 'iOS')` with name 'iOS'.

**Comment by avjiang** [comment]
@sandwwraith thank you so much for the quick response sir! Really appreciate it, and the warning message now gone. I didn't know how to properly set the target. Thanks to you :). Good library!

**Comment by developer9923** [comment]
Hi All
Getting below error - 

e: /Users/manojkumar/latestBanklets/KMMBanklets/build.gradle.kts:40:13: Unresolved reference: optIn

The Kotlin source set commonTest was configured but not added to any Kotlin compilation. You can add a source set to a target's compilation by connecting it with the compilation's default source set using 'dependsOn'.

**Comment by premjit-develops** [comment]
> Hi All Getting below error -
> 
> e: /Users/manojkumar/latestBanklets/KMMBanklets/build.gradle.kts:40:13: Unresolved reference: optIn
> 
> The Kotlin source set commonTest was configured but not added to any Kotlin compilation. You can add a source set to a target's compilation by connecting it with the compilation's default source set using 'dependsOn'.
> 
> Can anyone help me to resolve this. Thanks



Add this to
```
androidLibrary{

  withHostTestBuilder {
    }

    withDeviceTestBuilder {
        sourceSetTreeName = "test"
    }.configure {
        instrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

    }
 }
```
