### ISSUE TITLE
Serializing into dictionary

### ISSUE THREAD

**Issue by avjiang** [Kotlin/kotlinx.serialization#574]
**What is your use-case and why do you need this feature?**
Serializing from JSON object and generate a dictionary for it 

**Describe the solution you'd like**
Able to serialize any JSON object/string to become a dictionary. So it is not necessarily to create a serializable data class

Is this feature supported already? Thanks!

**Comment by Dominaezzz** [comment]
Yes. Have a look at `JsonObject`.
