### ISSUE TITLE
Primary constructor parameters that are not properties does not give an error with explicit constructor

### ISSUE THREAD

**Issue by TorRanfelt** [Kotlin/kotlinx.serialization#575]
Why do I get the error "This class is not serializable automatically because it has primary constructor parameters of which are not properties" in example A when B doesn't?

A:
```
@Serializable
class Foo(bar: Int) {
    val baz: Int

    init {
        baz = bar
    }
}
```

B:
```
@Serializable
class Foo {
    val baz: Int

    constructor(bar: Int) {
        baz = bar
    }
}
```

**Comment by sandwwraith** [comment]
@lpi Secondary constructors shouldn't block the ability of class being `@Serializable`. If you have problems with them, please file new issue

**Comment by sandwwraith** [comment]
We do not plan to implement this diagnostic — original 'Primary constructor parameters that are not properties' was intended for cases where the parameter is used in the initializer for, say, `@Transient val`. Parameters from in-body constructors are not allowed to be used in initializers for properties, so it doesn't block them from being correctly initialized by serialization plugin.
