### ISSUE TITLE
How to unmap a Map<String, Any?> where one of its values is a `Date`?

### ISSUE THREAD

**Issue by Nimrodda** [Kotlin/kotlinx.serialization#579]
I have `Map<String, Any?>` where one of its values is a `Date`. I read the docs about custom serializer and saw the example serializer for `Date`, but that example is suitable for Json serialization. This is what I have:

```
@Serializable
data class Foo(
  val id: Int,
  val bar: String,
  @Serializable(with = DateSerializer::class) 
  val modified: Date
)

object DateSerializer : KSerializer<Date> {
    override fun serialize(encoder: Encoder, obj: Date) {
      // how to implement this?
    }

    override fun deserialize(decoder: Decoder): Date {
      // how to implement this?
    }

    override val descriptor: SerialDescriptor
        get() = StringDescriptor
}

// using it like this:

val foo = Mapper.unmapNullable(Foo.serializer(), map)
```
I can see that the decoder instance is of type `InNullableMapper`, but none of the API of this decoder is helpful in any way.
Is it even possible to have a custom serializer in this case?

**Comment by sandwwraith** [comment]
So you want to convert `Map<String, Any?>` yo your `Foo` class? You can check if the `decoder` in `deserialize` is `TaggedDecoder` or `InNullableMapper` and call `decodeTaggedValue` which returns `Any`
