### ISSUE TITLE
custom Enum serializer with ImplicitReflectionSerializer

### ISSUE THREAD

**Issue by kalistace** [Kotlin/kotlinx.serialization#584]
Hi,

I am trying to use the implicit reflection experimental feature with Enums but I can't seem to get it to work. I am not sure if it's by design or if I am just doing it wrong.

I know using reflection is discouraged but unfortunately it is a requirement in my team to have generic serialisation(+ we run only on jvm), hence I have the following methods (simplified) :

```kotlin
val defaultJsonFormatter = Json(JsonConfiguration.Stable)

@UseExperimental(ImplicitReflectionSerializer::class)
inline fun <reified T : Any> String.fromJson(): T =
    defaultJsonFormatter.parse(T::class.serializer(), this)

@UseExperimental(ImplicitReflectionSerializer::class)
inline fun <reified T: Any> T.toJson(): String = defaultJsonFormatter.toJson(this).toString()
``` 

This works fine for classes and all is good. We can easily do `MyClass("test").toJson()`, etc.

Now comes a use case where we need an Enum value, from my understanding there is no default serializer for Enums, hence I came up with something like that :

```kotlin
@Serializable(with = TestEnum.TestEnumSerializer::class)
enum class TestEnum(val label: String) {
    ENUM1("label_1"),
    ENUM2("label_2");

    companion object {
        fun getByLabel(label: String?): TestEnum? = values().first { it.label == label }
    }

    @Serializer(forClass = TestEnum::class)
    object TestEnumSerializer : KSerializer<TestEnum> {
        override val descriptor: SerialDescriptor
            get() = StringDescriptor

        override fun deserialize(decoder: Decoder): TestEnum {
            return TestEnum.getByLabel(decoder.decodeString()) ?: run { throw Exception("Error") }
        }

        override fun serialize(encoder: Encoder, obj: TestEnum) {
            encoder.encodeString(obj.label)
        }

    }
}
```

but that doesn't seem to work with implicit serialiser :

```kotlin
        val t1 = defaultJsonFormatter.toJson(TestEnum.TestEnumSerializer, TestEnum.ENUM1).toString() // PASS
        val t2 = defaultJsonFormatter.fromJson(TestEnum.TestEnumSerializer, defaultJsonFormatter.parseJson(t1)) // PASS

        val t3 = TestEnum.ENUM1.toJson() // FAIL
```

it fails with `kotlinx.serialization.SerializationException: Can't locate argument-less serializer for class com.ecg.tns.shared.misc.TestEnum. For generic classes, such as lists, please provide serializer explicitly.`

Which then becomes problematic as we have this enum embedded onto other Serializable classes, making the generic functions unusable.

I would have hoped the implicit serialiser could get the serialiser from context as it configured through the annotations but it doesn't seem to be the case.

I did notice other posts about Enums but none are using it with implicit conversion(as far as I could find).

Is what I am trying to do achievable ? If not, is it by design and it will stay that way or is it something that might be possible in the future ?

Thank you

**Comment by sandwwraith** [comment]
Hi,

Currently, `@Serializable(with=...)` annotation does affect enums only if they are used in another `@Serializable` model if I'm not mistaken (if it does not do so, it is probably a bug; workaround is to use `@Serializable(with=...)` on a property or `@file:UseSerializers`).

Basically, `@ImplicitReflectionSerializer` methods try to find a special generated field in the class, which is not there in case of a custom serializer. What you can do here:

1. Compare `T::class` with your `TestEnum::class` in `.toJson/.fromJson` functions – the simplest solution, but ugly

2. Register TestEnum in some serial module (`val json = Json(context = serializersModuleOf(TestEnum::class, TestEnumSerializer))`) and then use [reified](https://github.com/kotlin/kotlinx.serialization/blob/45aa7c7ab97f25f205408b46a7069886408bce6b/runtime/commonMain/src/kotlinx/serialization/SerialImplicits.kt#L52) versions of parse/stringify of just `module.getContextualOrDefault` directly.

The situation with custom serializers not available via reflection likely would not change, but #572  would eliminate the need for custom enum serializer in your case

**Comment by kalistace** [comment]
Great ! Good to know a bit more how `@Serializable(with=...)` behaves. 

Indeed, option 1 would then make it not generic. 

I will give option 2 a try, I already tried before but it is quite possible I was not using the correct methods (non riefied).

I will follow https://github.com/Kotlin/kotlinx.serialization/pull/572 and give the whole thing another try once it's merged. 

Thanks for the answer !
