### ISSUE TITLE
Replace EnumSerializer class with helper method

### ISSUE THREAD

**Issue by sandwwraith** [Kotlin/kotlinx.serialization#587]
Currently, `class EnumSerializer: CommonEnumSerializer` exists only for binary compatibility with plugin. `CommonEnumSerializer` should be final, and the plugin should emit a call to a helper method instead.

**Comment by pdvrieze** [comment]
Sounds like a good idea in principle. Of course some degree of (temporary) binary compatibility would be good (but it could be `Deprecated(Error)`).

**Comment by altavir** [comment]
Either class or helper is still needed for custom serializers. Of-course helper method like `writeEnum/readEnum` would be good.
