### ISSUE TITLE
When is READ_ALL returned by decodeElementIndex?

### ISSUE THREAD

**Issue by TorRanfelt** [Kotlin/kotlinx.serialization#592]
For custom serializers I had guessed READ_ALL would be returned if you are deserializing in bulk and not streaming, but I get indexes instead. When is READ_ALL ever returned?
https://github.com/Kotlin/kotlinx.serialization/issues/580#issuecomment-548799756

**Comment by pdvrieze** [comment]
The way deserializing elements of a collection is done depends on the format (decoder) you use. For formats like json and xml where the order (or presence) of the fields is arbritrary the decoder must support out of order deserialization either using indices or through memorization. There are also formats with less flexibility and reading all elements is valid and can represent a performance optimization. The existence of `READ_ALL` allows this to be triggered. By default it can always be implemented by hitting all indices sequentially (but it does not generate a `READ_DONE`).

**Comment by TorRanfelt** [comment]
Thank you. That makes sense.
