### ISSUE TITLE
Make PolymorphicClassDescriptor retain type of the base class

### ISSUE THREAD

**Issue by altavir** [Kotlin/kotlinx.serialization#595]
**What is your use-case and why do you need this feature?**
When using custom serializers ant tools one seldom needs to work with descriptors directly without a `Decoder` in those cases, `PolymorphicClassDescriptor` does not provide sufficient information since it is not possible to know, which field does it represent. 

**Describe the solution you'd like**

The simplest solution is to use base class name for descriptor instead of `Any`. It will increase memory consumption because at the moment Polymorphic descriptor is a singleton, but I do not think it is critical. The state could be moved from `PolymorphicSerializer` into descriptor thus making API more uniform.

**Comment by sandwwraith** [comment]
Is serial name of the base class sufficient for your use-case or you need to retain a full `KClass`?

**Comment by sandwwraith** [comment]
Also see https://github.com/Kotlin/kotlinx.serialization/issues/515

**Comment by altavir** [comment]
Full KClass would be better, but string would suffice. Currently the actual case is when you need to manually work with descriptors. We need to be able to find base class of the property from the descriptor without constructing the serializer. A general solution is to move class description from `PolimorphicSerializer` into `PolymorphicClassDescriptor`.

**Comment by pdvrieze** [comment]
I think we need to look carefully at the architecture of the descriptor part of the framework (in conjunction with the serializers). Perhaps it is worthwhile to create a format descriptor/schema system. That should expose all parts where information is not (easily) accessible (or requires looking at internal/implementation details).

**Comment by altavir** [comment]
@pdvrieze I agree. The descriptor should in fact be capable of defining everything needed to work with schema without creating actual serializer. I also think that descriptor should be extensible and in theory allow for advanced features like validation. It would allow to automatically create consistent  advanced schema (like json/XML schema) as well as doing non-serialization tasks like validation with serialization framework.

**Comment by qwwdfsad** [comment]
Fixed in 1.0.0-RC
