### ISSUE TITLE
following stackoverflow question for your kind attention

### ISSUE THREAD

**Issue by svd27** [Kotlin/kotlinx.serialization#598]
[Question](https://stackoverflow.com/questions/58724789/how-can-i-serialize-a-self-dependent-structure-with-kotlin-kotlinx-serialization)
I think this is a problem worth considering and maybe adding a feature that allows attribute dependent deserialisation.

**Comment by sandwwraith** [comment]
I haven't fully understood your question, but I'll try to answer. So, you want to choose a deserializer for some field of the class depending on the contents of another field in the same class, right?

Then indeed, if fields in JSON go in another order, you would not be able to deserialize such class correctly. Note that some serialization formats have fixed order of fields, and some others don't allow you to read arbitrary fields in arbitrary order from the stream; kotlinx.serialization tries to abstract all that out and therefore index handling requires some precision work. 

However, if you are willing to have JSON-only deserializer, you can first read the current object to Json abstract tree, then find the property you want to read first, and then fill up the rest of the object. You can find some examples on that here:

https://github.com/kotlin/kotlinx.serialization/blob/45aa7c7ab97f25f205408b46a7069886408bce6b/runtime/commonTest/src/kotlinx/serialization/json/JsonTreeAndMapperTest.kt#L34

Please let me know if this helps you; if so, I'll cross-post answer on SO.

**Comment by svd27** [comment]
Actually You fully understood my question. 

Your solution seems feasible for the JSON case. 
But for other formats it might not work. So I am still wondering if it would not be desirable for a deserialiser to get the functionality to push back a field for deserialisation until another field was read.
Something like:
```kotlin
val holder : Any? = null
loop@ while (true) {
            when(val idx = dec.decodeElementIndex(descriptor)) {
                CompositeDecoder.READ_DONE -> break@loop
                0 ->  {
                            from = dec.decodeStringElement(descriptor, idx)
                            if(holder!=null) {
                               fromId = dec.decode(... holder)
                            } 
                         }
                1 -> to = dec.decodeStringElement(descriptor, idx)
                2 -> if(from!=null) {
                          fromId = dec.decodeSerializableElement(descriptor, idx, meta(from?:throw 
                          IllegalStateException()).idType.serializer())
                        } else holder = dec.getUnserializedContent(...)
            }
        }
```

where `getUnserializedContent()` would read until the next "field" boundary and return it in raw form.

**Comment by sandwwraith** [comment]
I think seeking and other things related to push-back/mark/etc are highly format-dependent and it requires a lot of work to abstract such features and they still won't work properly all the time

**Comment by pdvrieze** [comment]
@svd27 In line with Leonid, the only way to solve this reliably (in a generic sense) is to somehow determine the size of the unknown (not yet typed) property to store it until the type can be determined. This is not possible for various formats (although they do normally have order in their fields by necessity).
