### ISSUE TITLE
Can't compile project when I use User-defined serial annotations

### ISSUE THREAD

**Issue by fjodorver** [Kotlin/kotlinx.serialization#60]
When I use user-defined serial annotations, it throws compilation exception.
https://gist.github.com/fjodorver/ac31461c5cc9c989c52b1d3c4949c5c4
```
@SerialInfo
@Target(AnnotationTarget.PROPERTY)
@Retention(AnnotationRetention.SOURCE)
annotation class Limit(val min: Long, val max: Long)
```
Annotation class should have at least two double or two long parameters.

**Comment by sandwwraith** [comment]
Fixed in 0.4
