### ISSUE TITLE
Unresolved supertypes KSerializer

### ISSUE THREAD

**Issue by Merseyside** [Kotlin/kotlinx.serialization#603]
I try to make custom serializator because of constructor parameters. Here is my class:
```
@Serializable
class MemberInfo( // Needs to be fixed!
    id: String,
    name: String,
    val percent: Float
) : Member(id = id, name = name) {

    @Serializer(forClass = MemberInfo::class)
    companion object : KSerializer<MemberInfo> {
        override val descriptor: SerialDescriptor =
            StringDescriptor.withName("MemberInfo")

        @UseExperimental(ExperimentalStdlibApi::class)
        override fun serialize(encoder: Encoder, obj: MemberInfo) {
            encoder.encodeString(HexConverter.printHexBinary(obj.id.encodeToByteArray()))
            encoder.encodeString(HexConverter.printHexBinary(obj.name.encodeToByteArray()))
            encoder.encodeFloat(obj.percent)
        }

        @UseExperimental(ExperimentalStdlibApi::class)
        override fun deserialize(decoder: Decoder): MemberInfo {
            return MemberInfo(
                HexConverter.printHexBinary(HexConverter.parseHexBinary(decoder.decodeString())),
                HexConverter.printHexBinary(HexConverter.parseHexBinary(decoder.decodeString())),
                decoder.decodeFloat())
        }
    }
}
```

I get this error:
```
Supertypes of the following classes can not be resolved... Ubresolved supertypes kotlinx.serialization.KSerializer
```
kotlinVersion = 1.3.50
serializationVersion = 0.13.0

**Comment by youlovejohnny** [comment]
Same,  how to resolve this problem?

**Comment by pdvrieze** [comment]
Did you include the runtime library in your dependencies? While it should always be there, you do certainly need it if you use it in your own code (the plugin "knows" the library, so doesn't actually use it for code generation).

**Comment by sandwwraith** [comment]
Is it the IDE error (highlighting stops) or compiler error? Does the CLI (Gradle) build passes correctly? Anyway, a project with a reproducible sample could help.

**Comment by Merseyside** [comment]
Yes, I've got implementation "org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:$serialization" in my commonMain. 
IDE says nothing, but when compiling starts this error happens

**Comment by sandwwraith** [comment]
Have you provided corresponding platform artifacts? (i.e. `kotlinx-serialization-runtime` for jvmMain, `kotlinx-serialization-runtime-native` for iosMain, etc)

**Comment by Merseyside** [comment]
Sure, it works well in another cases

**Comment by sandwwraith** [comment]
What do you mean by 'another cases'? You can't compile common code, you always compile for one of the platforms

**Comment by Merseyside** [comment]
Yeah, I mean that I can use library for another needs and it works. I implement it in androidMain also

**Comment by qwwdfsad** [comment]
Please reopen if the problem still exists in the latest version
