### ISSUE TITLE
Runtime JS dependency not created since kotlin 1.3.50

### ISSUE THREAD

**Issue by bsimon36** [Kotlin/kotlinx.serialization#606]
As of kotlin 1.3.41, the kotlin js plugin would create dependency js files, including the necessary kotlinx-serialization-kotlinx-serialization-runtime.js

With kotlin 1.3.50 and 1.3.60, these files are no longer created and it is unclear how one is supposed to obtain them.

**To Reproduce**
Create a kotlin js project with this as a dependency. Run compileKotlinJs and only the js file for the project itself is produced. Trying to use this file throws an error at runtime because of the missing kotlinx-serialization dependency.

**Expected behavior**
The kotlinx-serialization-kotlinx-serialization-runtime.js should be created automatically or there should be instructions for how it can be obtained.

**Environment**
 - Kotlin version: 1.3.60
 - Library version: 0.14.0
 - Kotlin platforms: JS 
- Gradle version: 5.6

**Comment by sandwwraith** [comment]
I think there were some changes in Kotlin/JS plugin that may lead to such behavior, so it's better to report your problem to Kotlin's issue tracker (https://youtrack.jetbrains.com/issues/KT).

I also have an example project which uses 1.3.60 and doesn't have any problems, so you can study it and probably find some differences in configuration: https://github.com/Kotlin/kotlinx.serialization/tree/master/examples/example-js

**Comment by bsimon36** [comment]
Thank you. I've discovered the problem actually stems from using "implementation" or "api" instead of "compile" for the build dependencies. I've reported the problem on Kotlin's issue tracker.
