### ISSUE TITLE
Superclass field has wrong name when subclass is in different source set or module

### ISSUE THREAD

**Issue by maltaisn** [Kotlin/kotlinx.serialization#611]
I'm trying to test the serialization of an abstract class by creating a subclass in the test source set. However the super class field is not getting serialized with the correct name. Instead, the superclass field takes the name of the subclass field... 

**Steps to reproduce**
With the following files:
###### main/kotlin/com/example/test/A.kt
```kotlin
@Serializable
abstract class A {
    var a = 0
}
```
###### test/kotlin/com/example/test/MyTest.kt
```kotlin
internal class MyTest {
    @Serializable
    @SerialName("B")
    class B : A() {
        var b = 0
    }

    @Test
    fun test() {
        val module = SerializersModule {
            polymorphic(A::class) {
                B::class with B.serializer()
            }
        }
        val json = Json(JsonConfiguration.Stable.copy(unquoted = true), context = module)

        val b = B()
        b.a = 1
        b.b = 2

        val str = json.stringify(A.serializer(), b)
        assertEquals("""{type:"B",a:1,b:2}""", str)
    }
}
```
I get the string `{type:"B",b:1,b:2}` instead of `{type:"B",a:1,b:2}`. Notice how the `a` field becomes `b` but the correct value is used. The problem does not happen if both classes are in the same file or in the same source set. It only happens if the classes are declared in different source sets or different modules.

I don't think this is expected behavior but again there's not much documentation on polymorphic serialization. Is there something wrong with my code? I tried the same code in earlier versions up to 0.11.0 but the same results are obtained.

**Sample project: [example.zip](https://github.com/Kotlin/kotlinx.serialization/files/3882744/example.zip)**

**Environment**
 - Kotlin version: 1.3.60
 - Library version: 0.14.0
 - Kotlin platforms: JVM
 - Gradle version: 6.0.1
 - IDE: IntellijIDEA Ultimate 2019.2.4
 - JDK version: OpenJDK 11

**Comment by sandwwraith** [comment]
Unfortunately, this is a known issue for the case where classes are located in different modules: #378

**Comment by maltaisn** [comment]
Is there any hope of this being fixed soon? As someone said in the other issue this makes inheritance pretty much unusable... If I understand, the issue is with the Kotlin compiler and not with the library?

**Comment by sandwwraith** [comment]
Yes, you understood correctly. There are some problems with internal compiler API and ordering in data structures.

**Comment by sandwwraith** [comment]
https://github.com/Kotlin/kotlinx.serialization/issues/378#issuecomment-663134060
