### ISSUE TITLE
Throwing of exception on creating of Json from decoder context

### ISSUE THREAD

**Issue by InsanusMokrassar** [Kotlin/kotlinx.serialization#616]
**Description**

If you are using custom serializer and trying to create new `Json` format (via `Json` with `context` constructor) and parent decoder is from `Json` formatter - it will throw exception.

**To reproduce**

```kotlin
object : KSerializer<T> {
    ...
    override fun deserialize(decoder: Decoder): T {
        val jsonFormat = Json(context = decoder.context)
    }
    ...
}
```

**Expected behavior**

It is expected, that will be created new format with context of decoder.

**Environment**
 - Kotlin version: 1.3.61
 - Library version: 0.14.0
 - Kotlin platforms: JVM
 - Gradle version: 6.0.1

**Comment by sandwwraith** [comment]
Am I right, it `SerializerAlreadyRegisteredException` for Json-related objects?

**Comment by sandwwraith** [comment]
By the way, what's your use-case for creating a new json instance inside `Decoder`?

**Comment by InsanusMokrassar** [comment]
@sandwwraith I have created DI (for my personal use) https://git.insanusmokrassar.com/InsanusMokrassar/SDI and here I am looking into json to create serializers basing on config. In two words: I need to recreate json format (with decoder context) to deserialize a json object which used as arguments container.
