### ISSUE TITLE
Custom enum serialization since 0.14.0

### ISSUE THREAD

**Issue by azabost** [Kotlin/kotlinx.serialization#617]
**What is your use-case and why do you need this feature?**
I would like to serialize enums in such a way that allows reading "unsupported enum value" as a `String` instead. It can be achieved by using a sealed class for representing either supported or unsupported enum. I have an implementation that works with pre-0.14.0 version but I have just seen there are a lot of `@InternalSerializationApi` annotations everywhere in `Enums.kt` now and I'm worried I can lose that functionality sooner or later. I would like you to review that solution and advise if I should do it differently to avoid future compatibility issues.

**Describe the solution you'd like**
Currently what I have works like this:

```
interface Codified<T> {
    val code: T
}
```

```
sealed class CodifiedEnum<T, C> : Serializable where T : Enum<T>, T : Codified<C> {
    data class Known<T, C>(val value: T) : CodifiedEnum<T, C>() where T : Enum<T>, T : Codified<C>
    data class Unknown<T, C>(val value: C) : CodifiedEnum<T, C>() where T : Enum<T>, T : Codified<C>

    fun knownOrNull() = (this as? Known<T, C>)?.value
    fun code(): C = when (this) {
        is Known -> value.code
        is Unknown -> value
    }
}
```

```
@Serializer(forClass = CodifiedEnum::class)
open class CodifiedEnumSerializer<T, C> constructor(
    enumSerializer: CommonEnumSerializer<T>,
    private val codeSerializer: KSerializer<C>
) : KSerializer<CodifiedEnum<T, C>> where T : Enum<T>, T : Codified<C> {

    override val descriptor = codeSerializer.descriptor

    private val enumValuesByCode = enumSerializer.values.associateBy { it.code }

    override fun deserialize(decoder: Decoder): CodifiedEnum<T, C> {
        val code = decoder.decode(codeSerializer)
        val valueForCode = enumValuesByCode[code]
        return if (valueForCode == null) {
            CodifiedEnum.Unknown(code)
        } else {
            CodifiedEnum.Known(valueForCode)
        }
    }

    override fun serialize(encoder: Encoder, obj: CodifiedEnum<T, C>) {
        when (obj) {
            is CodifiedEnum.Known -> encoder.encode(codeSerializer, obj.value.code)
            is CodifiedEnum.Unknown -> encoder.encode(codeSerializer, obj.value)
        }
    }
}
```

```
enum class TestEnum(override val code: String) : Codified<String> {
    PIZZA("foo"),
    CHEESE("bar");

    @Serializer(forClass = CodifiedEnum::class)
    object CodifiedSerializer : KSerializer<CodifiedEnum<TestEnum, String>> by CodifiedEnumSerializer(
        EnumSerializer(TestEnum::class),
        String.serializer()
    )
}
```

```
@Serializable
data class TestEnumContainer(
    @Serializable(with = TestEnum.CodifiedSerializer::class)
    val testEnum: CodifiedEnum<TestEnum, String>? = null
)
```

Thanks to that I'm able to read `TestEnumContainer` objects having `testEnum` different than `PIZZA` and `CHEESE` and I can specify the exact string for each supported enum value.

**Comment by azabost** [comment]
Alright, I have overlooked how simple it is to obtain the enum values without the need to use the `EnumSerializer` by replacing `enumSerializer.values` with `serializableClass.enumMembers()`.
I think it solves my problem but feel free to suggest other solutions if you think it could be done even better.

**Comment by sandwwraith** [comment]
Well, it's better to use `enumSerializer.values` than `serializableClass.enumMembers()`, since the former does not use reflection and the latter is not available on Kotlin/Native

I think we eventually rethink the surface of internal API and EnumSerializer has huge possibilities of becoming public.

**Comment by azabost** [comment]
@sandwwraith Good point, thank you. It doesn't affect me for now because I do not use Kotlin/Native. Would you advise reverting to `enumSerializer.values` and ignoring the annotation then?

**Comment by pdvrieze** [comment]
@azabost @sandwwraith Currently the descriptor is implemented to provide the enum values as the members in the descriptor: 
https://github.com/Kotlin/kotlinx.serialization/blob/4f39fc70f70021f16de705e3027d0c507c59a17a/runtime/commonMain/src/kotlinx/serialization/internal/Enums.kt#L18-L20

The descriptor also has the enum type. As far as I understand it is intended that this behaviour is part of the official API (although the documentation isn't there yet and the API isn't stable yet). You can get the descriptor from the serializer and don't need to know anything about it (except that the type is `UnionKind.ENUM_KIND`). Any alternative serializers would be able to work as long as they work the same way.

**Comment by sandwwraith** [comment]
In case you don't need actual enum member instance, only its name, then yes, it's better to operate on descriptor without touching serializers at all. `SerialDescriptor` api is definitely public and stable enough (although it indeed lacks proper documentation)

**Comment by azabost** [comment]
I don't think the descriptor is sufficient for my use case since I need to access the enum values because I need their `code` property. It's in the 3rd snippet in the first post: `enumSerializer.values.associateBy { it.code }`
That's why I initially used `CommonEnumSerializer` to access them and had second thoughts after seeing the internal annotations in 0.14.0.
I'm not an expert in writing custom serializers though so please forgive me the dumbness 🙂

**Comment by azabost** [comment]
@sandwwraith Is `TestEnum.values()` better than `serializableClass.enumMembers()`? Does it use reflection under the hood? I don't think so but I prefer to ask than be wrong. Is it available on Kotlin/Native? I could adjust my code to this:

```
class CodifiedEnumSerializer<T, C>(
    enumValues: Array<T>,
    private val codeSerializer: KSerializer<C>
) : ...
```
and then declare the serializer using `TestEnum.values()` instead of `EnumSerializer(TestEnum::class)`.
What do you think?

**Comment by azabost** [comment]
I could also use `enumValues()` from stdlib to access the enum values and use inline functions to create the serializers I want:

```
inline fun <reified T> codifiedEnumSerializer(): KSerializer<CodifiedEnum<T, String>>
        where T : Enum<T>, T : Codified<String> =
    codifiedEnumSerializer(String.serializer())

inline fun <reified T, C> codifiedEnumSerializer(codeSerializer: KSerializer<C>): KSerializer<CodifiedEnum<T, C>>
        where T : Enum<T>, T : Codified<C> =
    CodifiedEnumSerializer(enumValues(), codeSerializer)```

It doesn't use reflection, does it? Would it work on Kotlin/Native?
