### ISSUE TITLE
`Unresolved reference: serializer` when dependencies moved to buildSrc

### ISSUE THREAD

**Issue by xsveda** [Kotlin/kotlinx.serialization#618]
Like #257 and #601 we face the problem that an IDE (Android Studio) does not see the `serializer()` methods on our `@Serializable` class even though the compiler is just fine, and the app is in production for few months already.

In our case we found out the root cause which we might be improved.

In our project we don't use `buildscript` block in root `build.gradle.kts` file at all. Instead we define all our plugin dependencies in `buildSrc` project (`buildSrc/build.gradle.kts`). The output of `buildSrc` project is a `jar` file that is applied on a classpath of each of the Gradle projects. 

This works fine for Kotlin Compiler, but it seems that the IDE Kotlinx Serialization plugin support is somehow not initialized with this configuration and therefore `serializer()` calls are red.

To workaround this issue we need to apply the Kotlin Gradle Plugin *again* in the `buildscript` block of the root `build.gradle.kts` file. 

**To Reproduce**
Attached ([KotlinxSerialization.zip](https://github.com/Kotlin/kotlinx.serialization/files/3910046/KotlinxSerialization.zip)) is a minimal Android project of one class and a unit test. The unit test (`SerializationClassTest`) is passing just fine, but the `serializer()` call in `SerializationClass` is red. Once you uncomment `line 7` of the root `build.gradle.kts` file and sync the project, everything is fine.

**Expected behavior**
The IDE support for Kotlinx Serialization should work also for case when Kotlin Gradle plugin is applied through `buildSrc` project configuration.

**Environment**
 - Kotlin version: [1.3.61]
 - Library version: [0.14.0]
 - Kotlin platforms: [JVM/Android]
 - Gradle version: [5.6.3]
 - IDE version [Android Studio 3.5.2]
 - Java [1.8.0_202]

**Comment by haohcraft** [comment]
I ran into the same issue on kotlin_version=1.3.60 and resolved it by rebuild the project after switching to kotlin_version=1.3.50. The bug is constantly reproducible and resolvable to me.

**Comment by JavierSegoviaCordoba** [comment]
Same here in AS 3.6 RC2

**Comment by nuhkoca** [comment]
Same here in AS 4.0.1

**Comment by fzhinkin** [comment]
The issue is no longer reproducible for the given project after updating all the versions (Kotlin, serialization, AS) to up-to-date values.
