### ISSUE TITLE
Native's StringReader never returns -1

### ISSUE THREAD

**Issue by nanodeath** [Kotlin/kotlinx.serialization#622]
**Describe the bug**
Common's [StringReader](https://github.com/Kotlin/kotlinx.serialization/blob/master/runtime/commonMain/src/kotlinx/io/Writers.kt#L67) is implemented by [java.io.StringReader](https://github.com/Kotlin/kotlinx.serialization/blob/master/runtime/jvmMain/src/kotlinx/io/Writers.kt#L27) on the JVM target and [custom](https://github.com/Kotlin/kotlinx.serialization/blob/master/runtime/nativeMain/src/kotlinx/io/Writers.kt#L95) on the Native target, but you'd expect them to behave similarly. The JVM's Reader, as you probably know, [returns -1 when EOF occurs](https://docs.oracle.com/javase/8/docs/api/java/io/Reader.html#read-char:A-int-int-). The Native one does not, only ever returning 0.

**To Reproduce**
```kotlin
@Test
fun readerBug() {
    val text: Reader = StringReader("Hello world!")
    val buffer = CharArray(1024)
    assertEquals(12, text.read(buffer, 0, 32))
    assertEquals(-1, text.read(buffer, 0, 32))
}
```

Passes on JVM, fails on Native.

**Expected behavior**
I expect the Native implementation to behave similarly to the JVM implementation: return -1 at EOF.

I guess for now I can also check 0, because the JVM Reader will never return 0.

**Environment**
 - Kotlin version: 1.3.61
 - Library version: 0.14.0
 - Kotlin platforms: Native
 - Gradle version: 5.6.4
 - IDE version (if bug is related to the IDE) [e.g. IntellijIDEA 2019.1, Android Studio 3.4]

**Comment by pdvrieze** [comment]
The JVM reader may return 0. This could for example be the case when reading from the network and there is no currently available data and doing opportunistic reading.

**Comment by nanodeath** [comment]
If there's no data available it'll block, not return 0.

**Comment by sandwwraith** [comment]
I'd like to remind that current implementation is an ad-hoc one implemented for internal purposes and will be replaced with kotlinx-io in observable future

**Comment by qwwdfsad** [comment]
This class is slipped to public API surface accidentally and will be removed in the next release
