### ISSUE TITLE
Get rid of MissingDescriptorException

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.serialization#626]
It is actually `IndexOutOfBoundsException`

**Comment by sandwwraith** [comment]
Why so? It indicates that custom serializer is written incorrectly

**Comment by qwwdfsad** [comment]
Because it is `IndexOutOfBoundsException`.
I honestly do not see why `getElementDescriptor(-1)` should throw `MissingDescriptorException` when both `getElementAnnotations(-1)` and `getElementName(-1)` throw `IndexOutOfBoundsException`

**Comment by sandwwraith** [comment]
That makes sense. 
However, for an index in a valid range (i.e. when `getElementName(i)` returns some name) `getElementDescriptor(i)` should either provide descriptor or throw MissingDescriptorException (or SerializationException with meaningful message)
