### ISSUE TITLE
Rename parameter of @Serializer annotation to "for"

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.serialization#629]
`@Serializer(forClass = Data::class)` seems to be a bit redundant, especially when compared to `@Serializer(for = Data::class)`

**Comment by sandwwraith** [comment]
AFAIR, idea was to rename `KSerializer` to `Serializer` and `@Serializer(forClass = ...)` to `@SerializerFor(...)`?

**Comment by qwwdfsad** [comment]
`for` is a keyword, so won't fix
