### ISSUE TITLE
Remove declarations marked with @InternalSerializationApi from auto-completion in IDEA

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.serialization#639]
This is rather an IDE task, filing here for the history

**Comment by sandwwraith** [comment]
I don't think we have any `@InternalCoroutinesApi` declarations in kotlinx.serialization. Do you mean `@InternalSerializationApi`?

**Comment by qwwdfsad** [comment]
Indeed. Muscle memory :)
