### ISSUE TITLE
Maven Central

### ISSUE THREAD

**Issue by nanodeath** [Kotlin/kotlinx.serialization#64]
Any plans/timeline for getting the artifacts for this up on Maven Central?

**Comment by elizarov** [comment]
It is in too early stage (preview, not stable at all), but we'll definitely go to Maven Central when it stabilizes a bit and gets to something we can call alpha.

**Comment by ligi** [comment]
Would really love to see this on maven-central better sooner than later as this currently blocks my updates on fdroid:

https://github.com/walleth/walleth/issues/258

Was also not aware this lib is considered preview and not stable at all. Perhaps a warning on top of the readme would be nice. So far it works fine for me - but a heads up would be nice ;-)

**Comment by jamesward** [comment]
These artifacts really need to be in Maven Central since adding a dependency like:
```
compile("io.ktor:ktor-client-json-jvm:1.1.2")
```
Results in:
```
Could not find org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:0.10.0
```

**Comment by anirban1992** [comment]
Internal tooling makes it hard for us to import packages without maven central. As this is packed as a part of the Kotlin compiler, isn't this stable enough now to release it as a package in Maven Central ? This is blocking us too.

**Comment by JesseCorbett** [comment]
Considering this is not available via jcenter, would it be time to also include this in maven central, for ease of use for maven users?

**Comment by sandwwraith** [comment]
This is available via jcenter: https://jcenter.bintray.com/org/jetbrains/kotlinx/kotlinx-serialization-runtime-common/ (was linked not so long ago). We'll hope to sync with Central via Bintray in some near future, too.

**Comment by sandwwraith** [comment]
It finally appeared: http://repo1.maven.org/maven2/org/jetbrains/kotlinx/kotlinx-serialization-runtime/

We'll sync every release after 0.14.0 to Maven Central, except for the eap ones.
