### ISSUE TITLE
Exclude a property

### ISSUE THREAD

**Issue by avjiang** [Kotlin/kotlinx.serialization#640]
Hi, is there any way to exclude a property from being exported out as JSON string?

I am having date time property and when I want to export it, the library throws me an error.

Thanks!

**Comment by Dominaezzz** [comment]
https://github.com/Kotlin/kotlinx.serialization/blob/a45e71af8bff3f76a3774fd0f8a1425de800a847/docs/examples.md#annotations

**Comment by sandwwraith** [comment]
Probably you want `@kotlinx.serialization.Transient`

**Comment by sschuberth** [comment]
> Probably you want `@kotlinx.serialization.Transient`

However, that also avoids *de*serialization of the value. I was reading @avjiang's question as only avoiding *serialization* of the value, but still deserialize it. Is that also possible?

**Comment by tommyzat** [comment]
@sschuberth did you find a solution?

**Comment by sschuberth** [comment]
Not really (besides a custom serializer). I was looking at this in the context of migrating from Jackson to kotlinx.serialization, but for this part we simply stick to Jackson still.

**Comment by aiguofer** [comment]
:( was really hoping for this. I love the simplicity of `@JsonIgnore` in Jackson.
