### ISSUE TITLE
api is working as implementation (Serialization runtime)

### ISSUE THREAD

**Issue by JavierSegoviaCordoba** [Kotlin/kotlinx.serialization#649]
I created a `libraryA` that uses Kotlin Serialization and Kotlin Reflect. This lib uses `api` instead of `implementation` for both dependencies.

The problem is I am having to add manually the serialization dependency to the project that wants to use the `libraryA`, if not I got `java.lang.ClassNotFoundException: kotlinx.serialization.json.Json`

If I am using `api`, the correct behavior should be I don't need to add the serialization dependency to the project because it is as `api` dependency?

**Environment**
 - Kotlin version: 1.3.61
 - Library version: 0.14.0
 - Kotlin platforms: JVM

**Comment by sandwwraith** [comment]
This is probably connected to the way you publish artifacts. Is there a correct dependency in your library's published `pom.xml` file? Do you have Gradle metadata?

**Comment by JavierSegoviaCordoba** [comment]
I am not using pom directly, only data in Gradle

**Comment by qwwdfsad** [comment]
Closing as obsolete. While it looks like a publication issue not related to `kotlinx.serialization`, feel free to post additional details and we would be glad to help
