### ISSUE TITLE
JSON mapper using unquoted generates strings that it can't parse

### ISSUE THREAD

**Issue by TorRanfelt** [Kotlin/kotlinx.serialization#650]
```
        val jsonMapper = Json(
                JsonConfiguration.Stable.copy(unquoted = true, useArrayPolymorphism = true),
                context = dataSerialModule
        )
```
With this mapper I have experienced objects that it can stringify, but that it then can't reconstitute from this string generated by itself.
Error: "Invalid JSON at 54: Unexpected trailing comma"

Seems unquoted doesn't really work since the mapper works fine without it.

**Comment by sandwwraith** [comment]
`unquoted` is a mode which is primarily intended for printing unquoted JSON for the ease of debugging, so it does not have clear semantics for parsing

**Comment by TorRanfelt** [comment]
Fair enough. Would also put requirements on the contents of strings to work.
