### ISSUE TITLE
Polymorphic json serialization with inherited fields is invalid

### ISSUE THREAD

**Issue by auras** [Kotlin/kotlinx.serialization#652]
**Describe the bug**

If I have an abstract class with a field, and other classes which extend this abstract class, the field from the abstract class will have the same property name as the first field from the concrete class.

**To Reproduce**

```
@Serializable
abstract class Snippet(
    @SerialName("objectFieldName") val objectFieldName: String
)

@Serializable
data class TestSnippet(
    @SerialName("experiments") val experiments: List<KrakenExperiment>
) : Snippet("test")

@Serializable
data class ScreenSnippet(
    @SerialName("name") val name: String,
    @SerialName("uuid") val uuid: String? = null,
    @SerialName("source") val source: String? = null
) : Snippet("screen")

val snippetModule = SerializersModule {
            polymorphic(Snippet::class) {
                ScreenSnippet::class with ScreenSnippet.serializer()
                TestSnippet::class with TestSnippet.serializer()
            }
        }

        val json = Json(
                configuration = JsonConfiguration.Stable,
                context = snippetModule
        )

val testSnippet = TestSnippet(emptyList())
val screenSnippet = ScreenSnippet("one", "two", "three")

println (json.stringify(TestSnippet.serializer(), testSnippet))
println (json.stringify(ScreenSnippet.serializer(), screenSnippet))
```
Outputs:
```
{"experiments":"test","experiments":[]}
{"name":"screen","name":"one","uuid":"two","source":"three"}
```

**Expected behavior**
It should output:
```
{"objectFieldName":"test","experiments":[]}
{"objectFieldName":"screen","name":"one","uuid":"two","source":"three"}
```

**Environment**
 - Kotlin version: 1.3.61
 - Library version: 0.14.0
 - Kotlin platforms: JVM, android; this code is in kotlin MP "common" source set
 - Gradle version: 5.6.4
 - IDE version: Android Studio 4 Canary 8
 - Other relevant context: (AdoptOpenJDK)(build 1.8.0_232-b09)

**Comment by sandwwraith** [comment]
I observe the correct output with `"objectFieldName"` on 1.3.61/0.14.0. Does your `Snippet` and `TestSnippet` placed in the same source set or are they from different, e.g. main and test source sets?

**Comment by sandwwraith** [comment]
Can confirm the issue when classes are located in different source sets.

**Comment by auras** [comment]
Happens in the same "commonMain" source set.

**Comment by altavir** [comment]
It is good old #378. I also had the problems in the same source set. Guys, the issue is critical. Please fix it ASAP. Right now it tremendously hinders library development since I need to duplicate all fields in final classes. The simple proposal is to add serialization order to descriptor and generate those numbers automatically when the descriptor itself is being generated. Maybe there is a better solution.

**Comment by sandwwraith** [comment]
https://github.com/Kotlin/kotlinx.serialization/issues/378#issuecomment-663134060
