### ISSUE TITLE
Parse single object or list of objects

### ISSUE THREAD

**Issue by luca992** [Kotlin/kotlinx.serialization#654]
**What is your use-case and why do you need this feature?**
As described [here](https://stackoverflow.com/questions/53344033/moshi-parse-single-object-or-list-of-objects-kotlin): sometimes api's will return a json value which could contain a single object or a list of objects.

Also see the "data" json values in the json:api [example](https://jsonapi.org/)

**json:api example**
```
{
  "links": {
    "self": "http://example.com/articles",
    "next": "http://example.com/articles?page[offset]=2",
    "last": "http://example.com/articles?page[offset]=10"
  },
  "data": [{
    "type": "articles",
    "id": "1",
    "attributes": {
      "title": "JSON:API paints my bikeshed!"
    },
    "relationships": {
      "author": {
        "links": {
          "self": "http://example.com/articles/1/relationships/author",
          "related": "http://example.com/articles/1/author"
        },
        "data": { "type": "people", "id": "9" }
      },
      "comments": {
        "links": {
          "self": "http://example.com/articles/1/relationships/comments",
          "related": "http://example.com/articles/1/comments"
        },
        "data": [
          { "type": "comments", "id": "5" },
          { "type": "comments", "id": "12" }
        ]
      }
    },
    "links": {
      "self": "http://example.com/articles/1"
    }
  }],
  "included": [{
    "type": "people",
    "id": "9",
    "attributes": {
      "firstName": "Dan",
      "lastName": "Gebhardt",
      "twitter": "dgeb"
    },
    "links": {
      "self": "http://example.com/people/9"
    }
  }, {
    "type": "comments",
    "id": "5",
    "attributes": {
      "body": "First!"
    },
    "relationships": {
      "author": {
        "data": { "type": "people", "id": "2" }
      }
    },
    "links": {
      "self": "http://example.com/comments/5"
    }
  }, {
    "type": "comments",
    "id": "12",
    "attributes": {
      "body": "I like XML better"
    },
    "relationships": {
      "author": {
        "data": { "type": "people", "id": "9" }
      }
    },
    "links": {
      "self": "http://example.com/comments/12"
    }
  }]
}

```

**Describe the solution you'd like**
Maybe use of `vararg`, or an `SingleToArray` annotation like in that moshi example to read single objects into a list

I am attempting to write a custom serializer to handle this case... but is there an example anywhere of how to do this in a clean way?

**Comment by sandwwraith** [comment]
You can use something like this https://github.com/Kotlin/kotlinx.serialization/blob/a45e71af8bff3f76a3774fd0f8a1425de800a847/runtime/commonTest/src/kotlinx/serialization/json/JsonTreeAndMapperTest.kt#L31 in your code

Idea is to write a custom serializer which first parses json dynamically, then do a `when` over structure and finally write down some result
