### ISSUE TITLE
Sealed Class: Remove type

### ISSUE THREAD

**Issue by hfhbd** [Kotlin/kotlinx.serialization#655]
**What is your use-case and why do you need this feature?**
Unfortunately, I have a json string like this:
`[{ "value": "hello"}, {"value": 42}]`

To serialize this types, I use a sealed class with two implementations, StringValue and IntValue.
The default serializer adds the class with a type property, which is critical when a property is named type, and the receiver did not expect this additional attribute during desialization.

 
**Describe the solution you'd like**
```

class TestValuesTest {

    @Serializable
    sealed class TestValues {
        @Serializable
        data class StringValue(val value: String): TestValues()
        @Serializable
        data class IntValue(val value: Int): TestValues()
    }

    private val json = Json(JsonConfiguration.Stable)

    private val expected = """
         [{ "value": "hello"}, {"value": 42}]
    """.trimIndent()

    @Test
    fun incomingJson() {
        val values = json.parse(TestValues.serializer().list, expected)
        assertEquals("hello", (values[0] as TestValues.StringValue).value)
        assertEquals(42, (values[1] as TestValues.IntValue).value)
    }

    @Test
    fun outgoingJson() {
        val testString = TestValues.StringValue("hello")
        val testInt = TestValues.IntValue(42)

        val outgoing = json.stringify(TestValues.serializer().list, listOf(testString, testInt))
        assertEquals(expected, outgoing)
    }
}
```

**Comment by pdvrieze** [comment]
The only way you can support this really is using a custom serializer. I don't think it is possible (nor desirable) to have a general solution for content-dependent deserialization in JSON (note that XML tag names and namespaces make this possible for XML). 

If you want to make it "work", In this particular case it is not the container that varies, but the content.  So a custom serializer/deserializer for the content can attempt to handle this (but will need to be format specific as it needs to look ahead to determine the type of thing to parse).

Note that many formats (protobuf, xml, etc.) don't use quotes to distinguish between strings and numbers, so in those formats it doesn't work. The most robust approach would be to special case the JSON format in the serializer/deserializer and do something special only for JSON.

**Comment by hfhbd** [comment]
I understand, thank you for your answer. After rereading the third party API, I am luckily able to use generics, because the type will be always the same in a specific request.
`@Serializable data class Response<T>(val results: List<T>)`
