### ISSUE TITLE
Getting serializer by object's KClass or KType instance

### ISSUE THREAD

**Issue by cy6erGn0m** [Kotlin/kotlinx.serialization#656]
**What is your use-case and why do you need this feature?**
For object classes, it should be a way to find a serializer. Currently, both `KClass<*>.serializer()` and `serializer<T>()` do not work.

The reason why we need this is that we should somehow serialize objects (that is accepted to be allowed). However, it is not possible if an object is a serialization root.

**Comment by pdvrieze** [comment]
I assume this to mean that you want to write the state of a Kotlin `object` singleton. This is something that is has many potential issues.
