### ISSUE TITLE
Deserialization of List<Any>

### ISSUE THREAD

**Issue by AhsenSaeed** [Kotlin/kotlinx.serialization#660]
Hey, I'm trying to deserialize the List<Any> with the polymorphic technique. Here's my server JSON response.

    {
    "data": [
        {
            "id": 346,
            "title": "Change Theme Dynamically with Circular Reveal Animation on Android",
            "is_user_like_blog": 0
        },
        {
            "id": 346,
            "title": "Change Theme Dynamically with Circular Reveal Animation on Android",
            "is_user_like_blog": 0
        },
        {  
             "status": true,
             "message": "Hello World"
        },
        {
             "response": "Welcome of my app"
        }
      ]
    }

And this is my JSON configuration for Retrofit.
   
       Json(
           configuration = JsonConfiguration(
                strictMode = false,
                useArrayPolymorphism = true
            ),
            context = SerializersModule {
                polymorphic(Any::class) {
                    PolymorphicSerializer(Article::class)
                    PolymorphicSerializer(StatusMessage::class)
                    PolymorphicSerializer(Response::class)
                }
            }
        ).asConverterFactory("application/json".toMediaType())

Below are my response classes.

    @Serializable
    data class Article (   
        @SerialName(value = "id") val articleId: Long,
        @SerialName(value = "title") val articleTitle: String
        @SerialName(value = "is_user_like_blog") val isLike: Short,
    )

    @Serializable
    data class StatusMessage(
        @SerialName(value = "status") val status: Boolean,
        @SerialName(value = "message") val message: String,
    )

    @Serializable
    data class Response(@SerialName(value = "response") val response: String)

    @Serializable
     data class ParentResponse(@SerialName(value = "data") val items: List<@Polymorphic Any>)

The exception I got after running the app.
**kotlinx.serialization.json.JsonDecodingException: Invalid JSON at 47: Expected '[, kind: OPEN'**

Library-Version
implementation 'org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.14.0'

**Comment by pdvrieze** [comment]
The parser probably complains that the document is not valid JSON. At least in the data pasted here, there are some issues with braces. On a more fundamental level, this is not going to work. Basically the JSON format works in certain ways and makes assumptions about the form of the JSON used - your data does not follow that form. Beyond that, there is no way that the format knows which particular type is needed for which particular entry. The JSON format needs to know the type being deserialized before it reads the values. What it doesn't do is read the entry, determine the entries in it, and based upon the entries in that map determine what the type actually is.

As part of your work, try to serialize first. You will find that the format is going to look quite different.

**Comment by AhsenSaeed** [comment]
@pdvrieze Yes, you're right there's one extra curly braces. But you see I typed it myself in JSON when asking question on GitHub that's when I made a typo. The problem is still the same. One thing more if I change the JSON response to a single item list let's say List<Article> and send the only list of articles from my server then no error occurs.

**Comment by sandwwraith** [comment]
Since your list elements do not contain any type information, what you can do is deserialize them to `List<JsonElement>` and then dynamically determine which instance you actually have

**Comment by AhsenSaeed** [comment]
@sandwwraith Yes, someone on reddit already told me about this. That's why I already closed the issue.

**Comment by mochadwi** [comment]
would you mind share your implementations? @AhsenSaeed

**Comment by mochadwi** [comment]
> Since your list elements do not contain any type information, what you can do is deserialize them to `List<JsonElement>` and then dynamically determine which instance you actually have

Is there any docs for this examples? @sandwwraith
