### ISSUE TITLE
Optimize check for missing fields 

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.serialization#662]
Currently, for a serializable class with N fields, the following constructor will be generated:
```
constructor(int mask, p_1, p_2, ... p_n) {
    if (mask & 1 == 0) {
        throw MissingFieldException("p1")
    } 
    if (mask & 2 == 0) {
       throw MissingFieldException("p2")
    }
    ...
}
```

This is both ineffective and inlining unfriendly.

What can be done instead:
```
const golden_mask = 1 shl N
constructor(int mask, p_1, p_2, ... p_n) {
    if (mask != golden_mask) throwMFE(mask, n)
    this.p_1 = p_1 
    ...
}
```

By the way, `throwMFE` can be implemented with a for loop and extract the name from the serial descriptor
(thus it has smaller bytecode that can be shared among **all** serializable classes)

**Comment by sandwwraith** [comment]
Unobvious feature-benefit: we can list _all_ missing fields at one message, which other frameworks do rarely
