### ISSUE TITLE
Getting encoded type of class in polymorphic serialization

### ISSUE THREAD

**Issue by abhilash-swiggy** [Kotlin/kotlinx.serialization#684]
Consider following example:
```
@Serializable
@SerialName("msg_number")
data class IntMessage(val number: Int): Message
```

While using `IntMessage` object in codebase, is there any way I can get its encoded type value through the object. 

Basically, can I get `"msg_number"` using object of IntMessage?

Usecase for this could be to write some code that depends on what type of `Message` is received

**Comment by qwwdfsad** [comment]
Do you mean `IntMessage.serializer().descriptor.name`?

**Comment by abhilash-swiggy** [comment]
Thanks @qwwdfsad this worked. 
Another question, how a person encountering kotlinx for first time could have discovered this.
Some doc for reference would be much much helpful.

**Comment by qwwdfsad** [comment]
We are working on the documentation in this release.
See #630 and #682
