### ISSUE TITLE
DynamicObjectParser: can't parse children of a sealed class

### ISSUE THREAD

**Issue by SerVB** [Kotlin/kotlinx.serialization#687]
**Describe the bug**

It's not possible to use `DynamicObjectParser.parse` for parsing children of sealed classes.

**To Reproduce**
```kotlin
@Serializable
sealed class AAA

@Serializable
data class BBB(val i: Int) : AAA()

fun main() {
    val dynamicObjectParser = DynamicObjectParser()

    val b = BBB(4)

    val serializedB = Json(JsonConfiguration.Stable).stringify(AAA.serializer(), b)
    println(serializedB)

    val nativelyParsedB = JSON.parse<Any>(serializedB)
    println(nativelyParsedB)

    val parsedB = dynamicObjectParser.parse(nativelyParsedB, AAA.serializer())
    println(parsedB)
}
```

It crashes on the line `val parsedB = ...` with "IllegalArgumentException(Polymorphic value has not been read for class null) at AbstractPolymorphicSerializer.deserialize(Decoder)".

If I replace `AAA.serializer()` with `BBB.serializer()` in both places, it works, but it doesn't suit me because I need polymorphic serialization: in real code I have multiple children of a sealed class.

**Expected behavior**

I want it to make `parsedB == b`.

**Environment**
 - Kotlin version: 1.3.61
 - Library version: 0.14.0
 - Kotlin platforms: JS
 - Gradle version: 5.2.1
 - Other relevant context: Tested in Chromium 78

**Comment by JakeWharton** [comment]
I'm pretty sure this means that the DOP needs to accept a `JsonConfiguration` since things like the class discriminator could also have been changed.

And, ideally, in the future the library will also support serializing _to_ a dynamic object where things settings like default encoding will matter.

**Comment by sandwwraith** [comment]
Obsolete
