### ISSUE TITLE
Class contains a property with the same name but different package

### ISSUE THREAD

**Issue by hfhbd** [Kotlin/kotlinx.serialization#689]
**Describe the bug**
A `class Bug` is in package a and b. `a.Bug` contains a property of type: `b.Bug`. 
|
-- a
--- Bug.kt
-- b
---- Bug.kt
**To Reproduce**

````
package a

import b.Bug
import kotlinx.serialization.Serializable

@Serializable
data class Bug(val id: Long = 0) {
    val d get() = Bug()
}

// ------

package b

class Bug
````
or [github project](https://github.com/hfhbd/KotlinxSerializationBugSameName)

**Expected behavior**
a serializable class, valid to JSON `"{"id": 0}"`

**Environment**
 - Kotlin version: 1.3.61
 - Library version: 0.14
 - Kotlin platforms: JVM
 - Gradle version: 5.2.1
 - IDE version: IntelliJ IDEA 2019.3.2
 - Other relevant context: -

**Comment by hfhbd** [comment]
Workaround (for own classes):
```
@Serializable
data class Bug(val id: Long = 0) {
    val d get() = b.Bug()
}
```
How about third party class, eg. custom serializer for external libraries, which use this syntax?

**Comment by hfhbd** [comment]
if `a.bug.d: a.Bug` is also not working with the short notation:

```
package a

import kotlinx.serialization.Serializable

@Serializable
data class Bug(val id: Long = 0) {
    val d get() = Bug()
}
```

Workaround using the explicit and block notation: 

```
package a

import kotlinx.serialization.Serializable

@Serializable
data class Bug(val id: Long = 0) {
   val d: Bug get() { return Bug() }
}
```

**Comment by sandwwraith** [comment]
I don't get the problem, could you clarify what output you get currently and what is expected? It looks like regular name clash that should be avoided by specifying package explicitly or using renaming imports

**Comment by hfhbd** [comment]
@sandwwraith 

> Since Kotlin 1.1, you can omit the property type if it can be inferred from the getter:
> val isEmpty get() = this.size == 0  // has type Boolean
https://kotlinlang.org/docs/reference/properties.html

But with `@Serialization` the Kotlin Compiler is not able to infer the type of the property.
Even this "simple" example without any dependencies or other packages is not working.
You have to define the type, with is easy of course.
```
@Serializable
data class Foo(val bar: String) {
    val f get() = Foo("bar")
}
```

**Comment by sandwwraith** [comment]
https://youtrack.jetbrains.com/issue/KT-39206 is fixed, so this problem is no longer actual

**Comment by hfhbd** [comment]
Correct link?

**Comment by sandwwraith** [comment]
Sorry, I missed correct browser tab :(

**Comment by hfhbd** [comment]
Unfortunately, with 1.7.20-RC I still get a Kotlin frontend error with this code:
```kotlin
@Serializable
data class Foo(val bar: String) {
    val f get() = Foo("bar")
}
```
[untitled.zip](https://github.com/Kotlin/kotlinx.serialization/files/9633816/untitled.zip)
Sure, the workaround is easy, but the error is still interesting: 
```kotlin
@Serializable
data class Foo(val bar: String) {
    val f: Foo get() = Foo("bar")
}
```

**Comment by sandwwraith** [comment]
Not reproducible on 2.0.20 / 1.7.3. The following:

```kotlin
@Serializable
data class Foo(val bar: String) {
    val f get() = Foo("bar")
}

fun main() {
    println(Json.encodeToString(Foo("foo")))
}
```

prints `{"bar":"foo"}`.
