### ISSUE TITLE
Pass `InputStream` to `Protobuf.load`

### ISSUE THREAD

**Issue by fsantanna** [Kotlin/kotlinx.serialization#693]
**What is your use-case and why do you need this feature?**

AFAIU, currently I can only to pass a `ByteArray` when deserializing data.
I wonder if it would be possible to pass an `InputStream` instead.

I want to deserialize a variable-size data structure coming from the network, so I don't know the exact size beforehand to create a `ByteArray`.

(I'm sorry if I missed some important information about the design that invalidates this question.)

**Describe the solution you'd like**

**Comment by fsantanna** [comment]
Forgot to mention that my current solution is to serialize the data structure to a `ByteArray`, get its resulting size, transmit the size in separate and than transmit the buffer.

**Comment by Dominaezzz** [comment]
Not a direct answer but is relevant. https://github.com/Kotlin/kotlinx.serialization/issues/204 and https://github.com/Kotlin/kotlinx.serialization/issues/253

**Comment by sandwwraith** [comment]
It's all will be resolved after #253 – formats would operate `kotlinx.io.Input` and `kotlinx.io.Output`. Unfortunately, kotlinx.io is not mature enough (yet).

**Comment by AlexanderShniperson** [comment]
@fsantanna 
hi, can you please share example of how do you use `protobuf` with serialization/deserialization?
don't understand why it is missed at sample sources

**Comment by fsantanna** [comment]
@AlexanderShniperson ,

This is how I'm doing:

```
import kotlinx.serialization.protobuf.ProtoBuf

@Serializable
data class MyData (...)

val myData = MyData(...)

// from data to bytearray
val bytes: ByteArray = ProtoBuf.dump(MyData.serializer(), myData)

// from bytearray back to data
val myData2 = ProtoBuf.load(MyData.serializer(), bytes)
```

It's actually very straightforward.

**Comment by qwwdfsad** [comment]
Closing as duplicate
