### ISSUE TITLE
Provide a way to handle missing values for non nullable generics.

### ISSUE THREAD

**Issue by gilgamesharcadia** [Kotlin/kotlinx.serialization#705]
**What is your use-case and why do you need this feature?**
  ```kotlin
    @kotlinx.serialization.Serializable
    data class Foo(val foo: String? = null)

    @kotlinx.serialization.Serializable
    data class Bar<T>(val bar: T)

    val json = kotlinx.serialization.json.Json(JsonConfiguration.Stable)
    val jsonString = "{}"

    @Test
    fun parseFoo() {
        // This works.
        val foo: Foo = json.parse(Foo.serializer(), jsonString)
        assert(foo.foo == null)
    }

    @Test
    fun parseBar() {
        // This throws MissingFieldExceptions
        val bar: Bar<String?> = json.parse(
            Bar.serializer(String.serializer().nullable), jsonString
        )
        assert(bar.bar == null)
    }
```
If I understand correctly, we need to provide a default value for any property that isn't required in order to  know the difference between a missing value and a null literal value.

That is what I'm doing in the ```Foo``` test and it works as expected. 

I dind't find a way to do this with the ```Bar``` test since ```T``` isn't nullable, and I cannot specify a default value for ```T```.

I think it's a fairly common scenario where you are consuming a Rest API and that API response has some missing values which you want to handle as null ones. Since most APIs out there are not OOP and two different services in which an OOP API would have returned the same object, that API just returns the fields they need for that specific service, since it's not using objects just dictionaries (key, value), so it would be nice to find a way to handle those missing fields as null literals.

**Describe the solution you'd like**
An option to handle missing fields and null literal values the same way, something like ```missingFieldsNullByDefault``` property in the ```JsonConfiguration``` class would be nice.

**Comment by alexvanyo** [comment]
One way to solve this is with a custom sealed class with a custom serializer, which doesn't change the underlying format of the JSON:

```
sealed class OptionalProperty<out T> {
    object NotPresent : OptionalProperty<Nothing>()

    data class Present<T>(val value: T) : OptionalProperty<T>()
}
```

```
open class OptionalPropertySerializer<T>(
    private val valueSerializer: KSerializer<T>
) : KSerializer<OptionalProperty<T>> {
    final override val descriptor: SerialDescriptor = valueSerializer.descriptor

    final override fun deserialize(decoder: Decoder): OptionalProperty<T> =
        OptionalProperty.Present(valueSerializer.deserialize(decoder))

    final override fun serialize(encoder: Encoder, obj: OptionalProperty<T>) {
        when (obj) {
            OptionalProperty.NotPresent -> throw SerializationException(
                "Tried to serialize an optional property that had no value present." +
                    " Is encodeDefaults false?"
            )
            is OptionalProperty.Present ->
                valueSerializer.serialize(encoder, obj.value)
        }
    }

    final override fun patch(
        decoder: Decoder,
        old: OptionalProperty<T>
    ): OptionalProperty<T> =
        when (old) {
            OptionalProperty.NotPresent -> throw SerializationException(
                "Tried to patch an optional property that had no value present." +
                    " Is encodeDefaults false?"
            )
            is OptionalProperty.Present ->
                OptionalProperty.Present(valueSerializer.patch(decoder, old.value))
        }
}
```

`OptionalPropertySerializer` delegates to the generic `valueSerializer` if a value is present, so the structure of the JSON doesn't change, and a default value of `OptionalProperty.NotPresent` is used to denote a missing value.

So then `Bar` would then look like

```
@Serializable
data class Bar<T>(
    @Serializable(with = OptionalPropertySerializer::class)
    val bar: OptionalProperty<T> = OptionalProperty.NotPresent
)
```

`json.parse(Bar.serializer(String.serializer().nullable), "{}")` would result in `Bar(OptionalProperty.NotPresent)`

`json.parse(Bar.serializer(String.serializer().nullable), """{ "bar": null }""")` would result in `Bar(OptionalProperty.Present(null))`

`json.parse(Bar.serializer(String.serializer().nullable), """{ "bar": "test" }""")` would result in `Bar(OptionalProperty.Present("test"))`

**Comment by gilgamesharcadia** [comment]
@alexvanyo Thanks for your answer, but I didn't want to box the property and neither check ```Bar.bar``` value manually. I could do that with a plain nullable ```bar``` (since I don't need to know the difference from missing value or null literal) and check if it's null or not, but I don't like that approach. I'd rather for the library to throw an exception.

I edited the issue so it's more clear what I want.

**Comment by alexvanyo** [comment]
Oh gotcha, so if the generic type `T` for `Bar` is nullable, then it should be treated as optional property, and if the type is non-nullable, then it should be treated as a required property.

Without changing the library, what do you think of something like this?

```kotlin
sealed class Bar<T> {

    abstract val bar: T

    @Serializable
    data class NullableBar<T>(override val bar: T? = null) : Bar<T?>()

    @Serializable
    data class NonNullableBar<T : Any>(override val bar: T) : Bar<T>()
}
```

```kotlin
class BarSerializer<T>(
    valueSerializer: KSerializer<T>
) : KSerializer<Bar<T>> by getBarSerializer(valueSerializer)

@Suppress("UNCHECKED_CAST")
fun <T> getBarSerializer(valueSerializer: KSerializer<T>): KSerializer<Bar<T>> =
    if (valueSerializer.descriptor.isNullable) {
        Bar.NullableBar.serializer(valueSerializer)
    } else {
        Bar.NonNullableBar.serializer(valueSerializer)
    } as KSerializer<Bar<T>>
```

`BarSerializer` mimics the logic of `KSerializer<T>.nullable`, so that if `T` is nullable, then `Bar.NullableBar` will be used to deserialize, and if `T` is non-nullable, then `Bar.NonNullableBar` will be used.

Thus the return type of `json.parse(BarSerializer(String.serializer().nullable), "{}")` would be `Bar<String?>` and would running it would result in `Bar(null)`.

The return type of `json.parse(BarSerializer(String.serializer()), "{}")` would be `Bar<String>` and running it would throw a `MissingFieldException` for `bar`.

**Comment by sandwwraith** [comment]
Maybe I misunderstood your question, but doesn't simple `data class Bar<T>(val bar: T? = null)` work?

**Comment by gilgamesharcadia** [comment]
@alexvanyo Thanks again for your time. your result is ideal, the proccess is not, at least for me. If I understand you correctly, you have to change the class to a sealed class, to add two properties, to create another class and a function. To do that for every model with a generic would be overkill for me, I'd go with the nullable generic instead in that situation.

@sandwwraith I'll show every case for the same example and the outputs I'd expect in those cases:
```Kotlin
@Test
fun case1() {
    val jsonString = "{\"bar\": \"someValue\"}"
    // bar is required and the json has it, everything is ok.
    val bar: Bar<String> = json.parse(Bar.serializer(String.serializer()), jsonString)
}
```
```Kotlin
@Test
fun case2() {
    val jsonString = "{\"bar\": null}"
    // bar is required but it was null, exception is thrown
    val bar: Bar<String> = json.parse(Bar.serializer(String.serializer()), jsonString)
}
```
```Kotlin
@Test
fun case3() {
    val jsonString = "{}"
    // bar is required but it was missing, exception is thrown
    val bar: Bar<String> = json.parse(Bar.serializer(String.serializer()), jsonString)
}
```
```Kotlin
@Test
fun case4() {
    val jsonString = "{\"bar\": \"someValue\"}"
    // bar isn't required and the json has it, everything is ok.
    val bar: Bar<String?> =
        json.parse(Bar.serializer(String.serializer().nullable), jsonString)
}
```
```Kotlin
@Test
fun case5() {
    val jsonString = "{\"bar\": null}"
    // bar isn't required and it's null, everything is ok.
    val bar: Bar<String?> =
        json.parse(Bar.serializer(String.serializer().nullable), jsonString)
}
```
```Kotlin
@Test
fun case6() {
    val jsonString = "{}"
    // bar isn't required and is missing, everything is ok.
    val bar: Bar<String?> =
        json.parse(Bar.serializer(String.serializer().nullable), jsonString)
}
```
What I want here is for the parser to know about the nullability in the generic instead of delegating that work to the client, since this is Kotlin it would be nice for the parser to know about it. I can imagine that the Type Erasure is a problem here, I just don't know if what I'm asking is a possible feature, I just know it would be nice to have it.

As per why don't I just make bar nullable and check for the nullability, a real world case scenario pseudocode:
```Kotlin
// The generic API response model
@kotlinx.serialization.Serializable
data class Response<T>(
    val statusCode: Int,
    val data: T
)

// We tell to the communications library to use the serializer.
CommunicationsLibrary.setParser(KotlinxSerializer)

// All the API services the app consumes 
// (in a real case it would have a lot, most of them no nullables)
interface Services {
      fun getUsers() : Response<List<User>>
      fun getUserVehicle(userId: Long) : Response<Vehicle?>
}
// An extension for the communications library with coroutines 
// that handles the response including the parsing errors
fun Call<T>.awaitResult(): Result<T> {
    try {
        await()            
    } catch(ignored: Exception) {
        // Here we will handle all exceptions including JSON parser exceptions
    }
}
```
In that example the ```getUsers()``` service never returns ```null```, and if it does return ```null``` or the value is missing I would expect for the parser to throw an exception so I know the response is not ok.
The thing is that right now the only possible solution I know is to make ````Response.data``` nullable, so I will have to check the nullability manually in every service call that by definition sould have a non nullable response. I hope I explained myself better now.

**Comment by sandwwraith** [comment]
Thanks for the explanation! Now I understand your problem. Unfortunately, currently we consider optionality purely as a wrapping object property – e.g. `DataSerializer` can't decide whether its result optional or not, only `ResponseSerializer` can do that. Also, default generated serializer does not check whether `T` is nullable or not, it just knowns whether `data: T` has default value and throws missing field exception if there's no incoming and no default.

What I can suggest you is to either go with sealed class as @alexvanyo suggested or write a custom serializer for `Response` which would do roughly following at the end of `deserialize` method:

```kotlin
if (readData == null && !tSerializer.descriptor.isNullable) throw MissingFieldException("data was not read")
return Response(statusCode, readData)
```

**Comment by gilgamesharcadia** [comment]
@sandwwraith I'll go with @alexvanyo's sealed class in cases where the class will be used a lot, like the ```Response```example above, and for another cases I will handle them manually, thanks to both of you. I hope one day we can get rid of java's Type Erasure.
