### ISSUE TITLE
Can't be used like that?

### ISSUE THREAD

**Issue by lianyueforever** [Kotlin/kotlinx.serialization#72]
`@Serializable
data class Response<out T>(val error: String, val data: T)`

**Comment by sandwwraith** [comment]
Sorry, I don't understand your question. Perhaps you are having issues with generic classes, for now they require explicit construction of serializer:

```kotlin
val respSerial = Response.serializer(StringSerializer)
println(JSON.stringify(respSerial, Response("", "MyPayload"))) // {"error":"","data":"MyPayload"}
```

**Comment by nico-gonzalez** [comment]
@sandwwraith I think @lianyueforever is referring to something like this https://stackoverflow.com/questions/48412340/cannot-parse-json-to-data-class-using-kotlinx-serialization
is it possible to use it like that?

**Comment by sandwwraith** [comment]
@nico-gonzalez According to stacktrace in attached question, it's a kapt or Dagger problem. (or maybe you just forgot to enable plugin). I would appreciate if you could create another issue with sample project which reproduces the problem.

From quick source inspection of kotlinx-serialization-retrofit adapter, I could say that it should work, if retrofit correctly passes type token
