### ISSUE TITLE
Is there support for generic polymorphic serializers?

### ISSUE THREAD

**Issue by biodunalfet** [Kotlin/kotlinx.serialization#720]
**What is your use-case and why do you need this feature?**

I have this class
```
@Serializable
abstract class ClassX<T> {
    abstract val id: String
    @Transient abstract val source: () -> T?
    abstract val active: Boolean
}
```

I'm having trouble creating a custom serializer for subclass of `ClassX` because I can't create a `KSerializer<>` for the type `T` which I don't know about and which I'm excluding from the serialization.

**Comment by pdvrieze** [comment]
You will have to use polymorphic serialization for it. For security reasons the types also need to be specified in a serialization module. For this particular case you need to create a PolymorphicSerializer with Any as base type. Then delegate serialization/deserialization to the serializer. (Of course in some cases where you can determine the type differently you could get the correct serializer for the concrete type)

**Comment by biodunalfet** [comment]
@pdvrieze that's what I did. Thanks 😄

**Comment by nbransby** [comment]
@biodunalfet have you got an example how you did this? I also only use the generic parameter in transient properties and don't want the fact it's a generic class to affect the serialization
