### ISSUE TITLE
Serialization exception when running release

### ISSUE THREAD

**Issue by trondat** [Kotlin/kotlinx.serialization#722]
**Describe the bug**
I'm using kotlinx serialization and have run into a strange problem. When i compile and run the code in DEBUG mode it works fine as expected, but when i compile the same code in RELEASE i get an exception. 

When running in RELEASE I get the following exception :	
Uncaught Kotlin exception: kotlinx.serialization.json.JsonDecodingException: Invalid JSON at 0: Expected '[, kind: LIST'

**To Reproduce**
```
val json = Json(JsonConfiguration.Stable)
var testJson = json.parse<JobInit>("{\"jobId\":\"j8203f1c50abe46338fa4d8955405949e\",\"jobStatus\":\"JobSubmitted\"}")
```

```
@Serializable
data class JobInit (val jobId : String = "", val jobStatus : String ="")	
```

**Expected behavior**
Expected the same behaviour in Debug and Release build.

**Environment**
 - Kotlin version: 1.3.61
 - Library version: 0.14.0
 - Kotlin platforms: Kotlin multiplatform for iOS
 - IDE version AppCode 2019.3.4 , XCode 11.3.1
 - Other relevant context iOS 13.3

**Comment by sandwwraith** [comment]
Sorry for being late, but have you tried to pass serializer explicitly? (`json.parse(JobInit.serializer, ...)`). Error looks like parser was expecting a list for some reason, which may be caused by incorrectly inferred list serializer

**Comment by vipulasri** [comment]
Is there any solution to this?
