### ISSUE TITLE
Make serializer() @JVMStatic

### ISSUE THREAD

**Issue by hfhbd** [Kotlin/kotlinx.serialization#727]
**Describe the bug**
Hey, 
I would like to create a companion object, which extends an abstract class and has a serializer as parameter. The call `.serializer()` results into a NPE, because the `fun serializer()` is not static.

**To Reproduce**
```
package org.example.demo

import kotlinx.serialization.KSerializer
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonConfiguration
import org.example.demo.Test.testing

abstract class TestClass<In : Any>(
    val inSerializer: KSerializer<In>
)

@Serializable
class Demo {
    companion object : TestClass<Demo>(
        Demo
            .serializer() // Results into NPE
    )
}

abstract class Testing(val i: Int)

object Test: Testing(testing()) {
    @JvmStatic // without static, testing() results into NPE
    fun testing(): Int = 42
}

fun main() {
    println(Test.i) // 42
    val json = Json(JsonConfiguration.Stable)

    println(json.stringify(Demo.inSerializer, Demo())) //NPE
}
```

**Expected behavior**
No NPE or alternative a compiler error instead a runtime error. It would be ideal, if you can customize the serialization generator with custom options.

**Environment**
 - Kotlin version: 1.3.61
 - Library version: 0.14.0
 - Kotlin platforms: JVM
 - Gradle version: 6.2.1

**Comment by sandwwraith** [comment]
Such usage of `testing()/serializer()` functions are basically 'leaking this' cases, see https://kotlinlang.org/docs/reference/null-safety.html and https://youtrack.jetbrains.com/issue/KT-19797#focus=streamItem-27-2377104.0-0 . Using `@JvmStatic` is merely a workaround. General recommendation is to avoid writing such code.

**Comment by hfhbd** [comment]
@sandwwraith Okay, thank you for your answer. 
My idea to use this workaround was to create an interface to type safe call the serializer() without reflection and explicite calling. Unfortunately, in Kotlin it is not possible to create following interface and (current) invalid code: 
```
interface KSerializable {
    companion object {
        fun serializer(): KSerializer<T> // T?  Should be the type of the class of the companion object
    }
}

@Serializable // to generate serializer
data class Test(val s: String): KSerializable // to type safe get the serializer instead reflection or explicite 

fun<T: KSerializable> get(url: String): T {
    val response = request(url)
    return json.serialize(this.serializer(), response)
}
````
