### ISSUE TITLE
Automatically give nullables default value

### ISSUE THREAD

**Issue by PhilipSA** [Kotlin/kotlinx.serialization#729]
**What is your use-case and why do you need this feature?**

For backwards compatibility reasons I'm trying to make this work:

```
    private val jsonSerializer = Json(JsonConfiguration(strictMode = false))

    @Test
    fun jsonSerializerIgnoresNonIncludedNullableFields() {
        @Serializable
        data class TestClass(val hello: String, val hello2: String?)

        val helloValue = "test"

        val json = JsonObject(mapOf("hello" to JsonPrimitive(helloValue)))

        val testClassObject = jsonSerializer.parse(TestClass.serializer(), json.toString())
        assertEquals(helloValue, testClassObject.hello)
    }
```

This will be throw:
`kotlinx.serialization.MissingFieldException: Field 'hello2' is required, but it was missing`
Because hello2 does not have a default value. 

But due to backwards compatibility reasons i would need a way for the serializer to automatically assign null to 'hello2' rather than complaining that it is missing. That is how i interpreted
`strictMode = false`
to work but it does not seem to be intended.

**Describe the solution you'd like**

Either make strictMode false assign null to nullables automatically or a new JsonConfiguration option were you can explicitly say you want this feature.

**Comment by sandwwraith** [comment]
The idiomatic way to do this is to add the default value to a property: `data class TestClass(val hello: String, val hello2: String? = null)`
