### ISSUE TITLE
kotlin Multiplatform module: build errors

### ISSUE THREAD

**Issue by daberni** [Kotlin/kotlinx.serialization#73]
I tried using kotlinx.serialization in a kotlin multiplatform project in a commons module with some small model classes looking like the following:

```kotlin

@Serializable
open class Document {
    var _id: String? = null
    var _rev: String? = null
}

@Serializable
class User : Document() {

    var username: String = ""
    var email: String = ""
    var rollen: List<UserRoles> = emptyList()

    companion object {
        val TYPE = "User"
    }
}

```

But when building via command-line I get following errors:

```
Unresolved reference: kotlinx
Cannot access 'Serializable': it is internal in 'kotlin.io'
This class does not have a constructor
```

Its mentioned in the description that it should work with the `kotlinx-serialization-runtime-common` dependency which I am using. The plugin should stay the same as far as I read.

I am using kotlin 1.2.21, but already tried 1.2.20, 1.2.10 with the same results.
Gradle 4.4.1

**Comment by sandwwraith** [comment]
Seems just library dependency was not recognized in buildscript. Can you check it for errors and post it here?

**Comment by daberni** [comment]
The dependency tree by gradle is the following:
```
+--- org.jetbrains.kotlin:kotlin-stdlib-common:1.2.21
\--- org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:0.4
     \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.2.10 -> 1.2.21
```

IntelliJ shows them as known but it really looks like the are not grabbed correctly.

I setup a minimal testproject here: https://github.com/daberni/kotlinx.serialization_test

Another issue which came up is, that `Mapper` isn't recognizing `@Optional` correctly. Parsing JSON works successfully, but working with a map where the key is missing doesn't work.

**Comment by sandwwraith** [comment]
Yes, this is how multiplatform build works for now: you should specify **both** dependency on common part of the library in your common module and dependency on platform part of the library in your platform module – just as same as deps on `kotlin-stdlib` and `kotlin-stdlib-common`

Current `Mapper` implementation assumes that it can just request all properties from the map. It likely will be changed in future.

**Comment by daberni** [comment]
Thank you so far for the update.

When I specify the additional dependency in the jvm target and run the tests from the referenced project I get the following runtime exceptions:

```
kotlinx.serialization.SerializationException: Can't locate companion serializer for class class SomeDataClass (Kotlin reflection is not available)

	at kotlinx.serialization.SerializationKt.serializer(Serialization.kt:25)
	at SampleTest.otherTest(SampleTest.kt:54)
```

I am not sure if the exception is a bit misleading as I assumed that reflection isn't required and Serializers are generated at compile time by the plugin or am I still missing something?

Steps are reproducible in the given repo.

**Comment by sandwwraith** [comment]
You need to `apply plugin: 'kotlinx-serialization'` in platform buildscript too

**Comment by daberni** [comment]
Thanks for the help 👍 

It would nice if the documentation could explain these steps in more detail. Probably I will make a PR for this 😉

**Comment by sandwwraith** [comment]
You're welcome! Any help would be appreciated :)

**Comment by sandwwraith** [comment]
I suppose I can close this now.

**Comment by hlung** [comment]
> You need to `apply plugin: 'kotlinx-serialization'` in platform buildscript too

Do you mean to add that to the build.gradle at the project root folder?

**Comment by sandwwraith** [comment]
@hlung  No. but for every `apply plugin: 'kotlin'` or 'kotlin-platform-xxx' or 'kotlin-multiplatform'.

**Comment by jeremyrempel** [comment]
If anyone else runs into this issue make sure have `enableFeaturePreview('GRADLE_METADATA')` in settings.gradle

**Comment by matthiaswelz** [comment]
I received the same error message ("Cannot access 'Serializable': it is internal in 'kotlin.io'"), but only because I forgot the `import kotlinx.serialization.*`. IntelliJ did not suggest to add this import automatically, so I first assumed some configuration issue. Maybe it helps someone arrivin here via Google.

**Comment by MajidHJ** [comment]
I get rid of that error by `import java.io.Serializable`. I hope it helps.

**Comment by avanlex** [comment]
> I received the same error message ("Cannot access 'Serializable': it is internal in 'kotlin.io'"), but only because I forgot the `import kotlinx.serialization.*`. IntelliJ did not suggest to add this import automatically, so I first assumed some configuration issue. Maybe it helps someone arrivin here via Google.

I think it's better way to add `import kotlinx.serialization.Serializable` instead importing all content of `kotlinx.serialization`
at least it works for me

**Comment by fisiodes** [comment]
I receive "Cannot access 'Serializable': it is internal in 'kotlin.io'" too. If i try to add "apply plugin: 'kotlinx-serialization" i receive: Plugin with id 'kotlinx-serialization' not found.

**Comment by sandwwraith** [comment]
@fisiodes Try to add `import kotlinx.serialization.*` to your file

**Comment by fisiodes** [comment]
@sandwwraith  yes thanks i already solved the problem with that import  and migrating gradle to kotlin dsl as i wrote above.
