### ISSUE TITLE
Custom serializer for nested arrays

### ISSUE THREAD

**Issue by nuhkoca** [Kotlin/kotlinx.serialization#730]
**What is your use-case and why do you need this feature?**

Hello, first of all, please let me know if this issue is not subject to you or you don't have anything to do. Sorry for any inconvenience in advance!

I am having a server response as follows:

```
 "baseCapacity": 10,
 "distanceToPolygon": 37633,
 "polygon": [
     [
         52.399182775989175,
         12.84729402512312
      ]
```

I can serialize **polygon** field if I use like `List<List<Double>>` in my data class. However, I'd like to have a separate data class that only contains double values if possible. What I mean;

**Working approach:**

```
data class Polygons (
    val baseCapacity: Int,
    val distanceToPolygon: Int,
    val polygon: List<List<Dobule>>
)
```

**What I want:**

```
data class Polygons (
    val baseCapacity: Int,
    val distanceToPolygon: Int,
    @Serializable(with = PolygonSerializer::class)
    val polygon: List<Polygon>
)

data class Polygon (
    val values: List<Double>
)
```

I tried to write a custom serializer:

```
object PolygonSerializer : KSerializer<String> {

    override val descriptor: SerialDescriptor
        get() = StringDescriptor.withName("polygon")

    override fun serialize(encoder: Encoder, obj: String) {
        //
    }

    override fun deserialize(decoder: Decoder): String {
        val jsonInput = decoder as JsonInput
        return jsonInput.decodeString()
    }
}
```

However, I am getting `Invalid JSON at 83: Expected string or non-null literal`

I want to ask if is there any way to ignore field in **Polygon** data class and achieve the same result like `List<List<Double>>`

**Describe the solution you'd like**

This could be available however I couldn't find any solution on the internet. 

**Desired solution:** A custom serializer that ignores key and returns only values. At the end of the day, I am expecting to have a **list of list of doubles**.

**Comment by Dominaezzz** [comment]
Here you go!

```
data class Polygons (
    val baseCapacity: Int,
    val distanceToPolygon: Int,
    val polygon: List<Polygon>
)

@Serializable(with = PolygonSerializer::class)
data class Polygon (
    val values: List<Double>
)

object PolygonSerializer : KSerializer<Polygon> {
    private val serializer = ArrayListSerializer(Double.serializer())

    override val descriptor: SerialDescriptor = StringDescriptor.withName("Polygon")

    override fun serialize(encoder: Encoder, obj: Polygon) {
        encoder.encode(serializer, obj.values)
    }

    override fun deserialize(decoder: Decoder): Polygon {
        return Polygon(decoder.decode(serializer))
    }
}
```

**Comment by nuhkoca** [comment]
@Dominaezzz  you saved my day! Thanks a lot! Really thanks!

**Comment by petestmart** [comment]
@Dominaezzz [Dominaezzz](https://github.com/Dominaezzz) In which package can I find `ArrayListSerializer`?

I'm having an issue accessing the internal class.  

`Cannot access 'ArrayListSerializer': it is internal in 'kotlinx.serialization.internal'`

**Comment by Dominaezzz** [comment]
Should be `ListSerializer()` now.

**Comment by petestmart** [comment]
@Dominaezzz WOW! Thank you so much! Don't suppose you know what StringDescriptor is now, do you?

**Comment by Dominaezzz** [comment]
You can just do `ListSerializer().descriptor` now.

**Comment by petestmart** [comment]
@Dominaezzz Thank you so much!

**Comment by petestmart** [comment]
In case anyone is interested in an update, I am doing something similar with a list of strings instead of a list of doubles.  The values are being used to populate a table widget:

`@Serializable(with = TableRowSerializer::class)
@Parcelize
data class TableRow(
    val tableRowValues: List<String?> = arrayListOf(),
) : Parcelable



object TableRowSerializer : KSerializer<TableRow> {
    private val serializer = ListSerializer(String.serializer())

    override val descriptor: SerialDescriptor = serializer.descriptor

    override fun serialize(encoder: Encoder, value: TableRow) {
        val rowValues = value.tableRowValues
            rowValues.let{rowValues as? List<String>}
                ?.let { encoder.encodeSerializableValue(serializer, it) }
    }

    override fun deserialize(decoder: Decoder): TableRow {
        return TableRow(decoder.decodeSerializableValue(serializer))
    }
}`
