### ISSUE TITLE
Can not locate serializer for classes on Android API 19

### ISSUE THREAD

**Issue by arnis71** [Kotlin/kotlinx.serialization#74]
I get exception `Caused by: kotlinx.serialization.SerializationException: Can't locate companion serializer for class ___` when I try to serialize objects on android devices with api 19. I guess it is because of the proguard but I included all the keep rules so it should theoretically work. How can I fix this?

**Comment by sandwwraith** [comment]
API level shouldn't be a problem, though. Have you tried to disable proguard? And didn't you forget to add `apply plugin: 'kotlinx-serialization` or `@Serializable` annotation?

**Comment by arnis71** [comment]
I will try to run without ProGuard but still, why this happens on api 19 100% of the time?

**Comment by elizarov** [comment]
I cannot reproduce it under emulator with API 19.

**Comment by sandwwraith** [comment]
I have everything work properly on my emulator with API 19. Can you provide minimal reproducible sample?
