### ISSUE TITLE
Cannot serialize TreeMap

### ISSUE THREAD

**Issue by mschirmacher** [Kotlin/kotlinx.serialization#740]
**Describe the bug**
I want so serialize a TreeMap but it fails with
class java.util.TreeMap is not registered for polymorphic serialization in the scope of class java.util.NavigableMap

**To Reproduce**
```
class TreeMapTest {
    @Test
    fun serializeTreeMap() {
        Json(JsonConfiguration.Default).stringify(Foo.serializer(), Foo(TreeMap()))
    }

    @Serializable
    class Foo(val map: NavigableMap<String, String>)
}

**Expected behavior**
The Map gets smoothly serialized like always 


**Environment**
 - Kotlin version: 1.3.70
 - Library version: 0.20.0
 - Kotlin platforms: JVM

**Comment by elizarov** [comment]
Just curious as to why you'd need to use polymorphic serialization here. You can define `class Foo(val map: TreeMap<String, String>)`. Do you have any other useful implementations of `NavigableMap`?

**Comment by sandwwraith** [comment]
Unfortunately, we do not have serializer for `TreeMap` for now, since it is a Java collection which is not available in common code. I think it can be provided in the corresponding JVM artifact

**Comment by mschirmacher** [comment]
@elizarov it's just usage of the good old pattern "implement against interfaces not implementation".
What i need is a `NavigableMap`. TreeMap is just one implementation available in the JDK.

**Comment by pdvrieze** [comment]
@mschirmacher It would probably work correctly against the `Map` interface, but if you want it to work for `NavigableMap` you'd probably have to write your own serializer for it (possibly delegating to/inheriting from the Map serializer)

**Comment by sandwwraith** [comment]
@pdvrieze It will work for _serialization_ agains `Map` interface, but since plugin uses `LinkedHashMapSerializer` as a default serializer for `Map`, after _deserialization_, there will be `LinkedHashMap` instead of `TreeMap`.

**Comment by sandwwraith** [comment]
Part of #1931
