### ISSUE TITLE
upgrade 0.14.0 - 0.20.0: ProtoBuf missing in serialization-runtime jar

### ISSUE THREAD

**Issue by marcelmatula** [Kotlin/kotlinx.serialization#741]
after migration from version 0.14.0 to 0.20.0
ProtoBuf support is missing in org.jetbrains.kotlinx:kotlinx-serialization-runtime

I see json is still there
import kotlinx.serialization.json.Json
but not
import kotlinx.serialization.protobuf.ProtoBuf

is it moved to some other separate dependency?

**Comment by sandwwraith** [comment]
Yes, please check out [release notes](https://github.com/Kotlin/kotlinx.serialization/blob/master/CHANGELOG.md#release-notes) and [formats list](https://github.com/Kotlin/kotlinx.serialization/tree/master/formats#protobuf). Protobuf has been moved to `kotlinx-serialization-protobuf` artifact (and corresponding `kotlinx-serialization-protobuf-js`, `-native`, if you're using multiplatform)

**Comment by marcelmatula** [comment]
Thanks - it works with kotlinx-serialization-protobuf
