### ISSUE TITLE
SerialDescriptionBuilder element seems to have redundant name parameter

### ISSUE THREAD

**Issue by altavir** [Kotlin/kotlinx.serialization#747]
**What is your use-case and why do you need this feature?**
```kotlin
SerialDescriptor("MetaItem") {
        element("isNode", PrimitiveDescriptor("isNode", PrimitiveKind.BOOLEAN))
}
```
A `SerialDescriptor` for the item already contains a name, so providing additional name for the element seems to be redundant. Providing different names for the element and descriptors could lead to bugs.

**Describe the solution you'd like**

Get a name for element from descriptor and add extensions for primitive types like 
```kotlin 
fun SerialDescriptor.boolean(name: String) = 
  element(PrimitiveDescriptor(name, PrimitiveKind.BOOLEAN))
```

**Comment by qwwdfsad** [comment]
These are different names, probably we can help here with better parameter names.
For the class and `class MetaItem(val isNode: Boolean)` and descriptor 
```
SerialDescriptor("MetaItem") {
    element($name1, PrimitiveDescriptor($name2, PrimitiveKind.BOOLEAN))
}
```

$name1 is a positional name (the name of the current property in the `MetaItem` class) and should be `isNode`. The second one just describes the type and should be `kotlin.Boolean`. Moreover, it should describe the boolean: 

```
SerialDescriptor("MetaItem") {
    element("isNode", descriptor<Boolean>())
}
```

**Comment by sandwwraith** [comment]
`PrimitiveDescriptor` factory function should be used in custom serializers, where you represent your class as a boolean, but with class' serial name which is different from `kotlin.Boolean`. For class members' serial names, `element(name, Boolean.serializer().descriptor)` or example above should be used, since they're literally a boolean and not a new type

**Comment by altavir** [comment]
OK, it is more clear now. But still it is not obvious what is the function of the descriptor name. Also, if those name could be broken and a value with `PrimitiveKind.BOOLEAN` could have a wrong descriptor name, it probably should be hidden. I think that there should be extensions for adding primitive elements to avoid all that.
