### ISSUE TITLE
JsonElement.booleanOrNull not consistent

### ISSUE THREAD

**Issue by eygraber** [Kotlin/kotlinx.serialization#748]
**Describe the bug**

I'm dealing with an API that sometimes returns boolean and sometimes returns integers (0 or 1). To parse them, I have the following function:

```
inline fun JsonObject.boolean(key: String) = get(key)!!.booleanOrNull ?: get(key)!!.intOrNull != 0
```

**To Reproduce**

For the following payload:

```
{ "some_boolean": false }
```

the function I posted above returns `true` for `json.boolean("some_boolean")`

If I change my function to:

```
inline fun JsonObject.boolean(key: String) = get(key)?.boolean
```

Or

```
inline fun JsonObject.boolean(key: String) = get(key)?.booleanOrNull!!
```

then it correctly returns `false`

**Environment**
 - Kotlin version: 1.3.70
 - Library version: 0.14.0
 - Kotlin platforms: JVM/Android
 - Gradle version: 6.1.1

**Comment by qwwdfsad** [comment]
It is not a library bug, but an operator priority issue.
Your code is equivalent to the following expression: `(get(key)!!.booleanOrNull ?: get(key)!!.intOrNull) != 0`

You can workaround it by explicitly using parentheses: `get(key)!!.booleanOrNull ?: (get(key)!!.intOrNull != 0)`

Filed https://youtrack.jetbrains.com/issue/KT-37376 for a change
