### ISSUE TITLE
JS IR backend support

### ISSUE THREAD

**Issue by skuzmich** [Kotlin/kotlinx.serialization#751]
Issue to track status of JS IR backend support.

Currently some tests fail due to different companion object representation and missing support for `AssociatedObjectKey`

**Comment by bashor** [comment]
After fix unmute [related tests in ktor](https://github.com/ktorio/ktor/pull/1714/commits/6acec6f0b84301091daa8afc7038163b428d8f4b).
The issue about supporting `AssociatedObjectKey` in JS IR BE is [here](https://youtrack.jetbrains.com/issue/KT-37418).

**Comment by sandwwraith** [comment]
Besides #753 , I've fixed/muted all problems in 07de016
