### ISSUE TITLE
[0.20.0] [kotlin-1.3.70] SerializationException when used polymorphic serialization

### ISSUE THREAD

**Issue by bulbigood** [Kotlin/kotlinx.serialization#755]
**Describe the bug**
Kotlin 1.3.61 with serialization 0.11.0 was OK with polymorphic serialization.
After update to Kotlin 1.3.70 and serialization 0.20.0 it's not.

**To Reproduce**
```
interface GameTypeEntity

@Serializable
data class GameClassEntity(
	val parent: Long = 0,
	val id: Long = 0
) : GameTypeEntity

@Serializable
data class JsonGameType(
	val entities: List<@Polymorphic GameTypeEntity>
)

@ImplicitReflectionSerializer
		fun create(jsonString: String): GameTypesCatalog {
                       val jsonModule: SerialModule = SerializersModule {
			        polymorphic(GameTypeEntity::class) {
				      subclass<GameClassEntity>()
                                }
                        }
			val json = Json(
				JsonConfiguration.Stable.copy(classDiscriminator = "entityClassName"),
				jsonModule
			)
			val root = json.parse(JsonGameType.serializer(), jsonString)
			return create(root)
		}
```
Function create() calling from **suspend** function.

What I got:
`SerializationException: GameClassEntity is not registered for polymorphic serialization in the scope of class GameTypeEntity`

**Expected behavior**
Deserialization of polymorphic hierarchy proceeds without errors.

**Environment**
 - Kotlin version: 1.3.70
 - Kotlin coroutines version: 1.3.4
 - Library version: 0.20.0
 - Kotlin platforms: JS
 - Gradle version: 5.5, 6.2.2, 6.3-rc1

**Comment by qwwdfsad** [comment]
Could you pleaser provide a `jsonString` that triggers this error?
I've tried to construct it manually, but it works as expected.

I could guess that you have `"entityClassName": "GameClassEntity"` instead of `"entityClassName": "package.where.this.class.exists.GameClassEntity"` in your input

**Comment by bulbigood** [comment]
> Could you pleaser provide a `jsonString` that triggers this error?
> I've tried to construct it manually, but it works as expected.
> 
> I could guess that you have `"entityClassName": "GameClassEntity"` instead of `"entityClassName": "package.where.this.class.exists.GameClassEntity"` in your input

You are right!
Now I need to specify packages. How to do this in right way if I don't want to edit json's?

**Comment by qwwdfsad** [comment]
Marking `GameClassEntity` with `@SerialName("GameClassEntity")` should do the trick

**Comment by bulbigood** [comment]
> Marking `GameClassEntity` class with `@SerialName("GameClassEntity")` should do the trick

All works, thank you for help. I should carefully read the changelogs.
