### ISSUE TITLE
IntelliJ JUnit Test reported SerialClassDescImpl's constructor not found 

### ISSUE THREAD

**Issue by johnbanq** [Kotlin/kotlinx.serialization#756]
**Describe the bug**

All polymorphic serialization test in my gradle project reports
 java.lang.NoSuchMethodError: kotlinx.serialization.internal.SerialClassDescImpl.<init>
when it's test ran by IntelliJ JUnit5 plugin

I have tried re-importing the project, re-sync the project, but nothing works

The tests runs correctly if invoked from gradle though

**To Reproduce**
Attach a code snippet or test data if possible.

This is the minimal project needed to recreate the error:
[untitled-3.zip](https://github.com/Kotlin/kotlinx.serialization/files/4327513/untitled-3.zip)

**Expected behavior**
Complete the test a.Test2.main() in project using IntelliJ JUnit support without problem

**Environment**
 - Kotlin version: 1.3.70
 - Library version: 1.3.70 with 0.20.0 runtime
 - Kotlin platforms: JVM
 - Gradle version: 5.4.1
 - IDE version (if bug is related to the IDE): 
IntelliJ IDEA 2019.3.2 (Ultimate Edition) Build #IU-193.6015.39, built on January 21, 2020

 - Other relevant context: Compiled & Run this on RedHat OpenJDK 11，Windows

**Comment by sandwwraith** [comment]
Are you sure that Kotlin Plugin in your IDE is updated to 1.3.70 ?

**Comment by johnbanq** [comment]
the kotlin plugin is not updated, it turns out that 1.3.70 is still in EAP, problem solved after updating, thanks!
