### ISSUE TITLE
throw exception when i put a jsonobject into jsonobject

### ISSUE THREAD

**Issue by roths** [Kotlin/kotlinx.serialization#759]
```
class JsCall {
    companion object {
        fun test(): JsonObject {
            val res = JsonObject(mutableMapOf())
            val response = JsonObject(mutableMapOf())
            (response.content as MutableMap).put("data", res) 
            return response
        }
    }
}
```
I'm converting some android libraries to MPP libraries. There's some logic that puts a jsonobject inside a jsonobject. When i rewirte it with kx.serialization, i got cast error in IOS

error info:
Could not cast value of type 'SharedCodeKMapAsNSDictionary' (0x10460cee8) to 'SharedCodeKotlinx_serialization_runtimeJsonElement' (0x10460c4e8).

**Comment by roths** [comment]
i can put JsonPrimitive into JsonObject. the diff between JsonPrimitive and JsonObject is JsonObject inherit Map<String, JsonElement> and delegate by `content`. Maybe that's the problem

**Comment by sandwwraith** [comment]
I'd believe this is due to downcasting to `MutableMap`, which is generally is a bad practice

**Comment by roths** [comment]
I can't find a way to put a jsonobject into jsonobject if a dont cast to Map<>.the original jsonobject is passed by other SDK,i can not controller the builder, and i need to add some extra into it.

I tried to use a builder, but the result was the same
![image](https://user-images.githubusercontent.com/7519916/76746362-59ffd700-67b2-11ea-9b2e-a59b87658c4b.png)

**Comment by roths** [comment]
I know what the problem is.  In  IOS，JsonObject is not declared as a class. If you use JsonObject in the function signature, the compiler compiles it to NSDictionary type, but in the internal logic JsonObject is treated as JsonElement type, so when the return value of the function is declared JsonObject and the returned instance type is also JsonObject, it will report an error on IOS, but on Android is fine.
here is Kt file content：
```
class Test {
    companion object {
        // cause error
        // (NSDictionary<NSString *, SharedCodeKotlinx_serialization_runtimeJsonElement *> *)test2 __attribute__((swift_name("test2()")));
        fun test(): JsonObject {
            return json {
                "data" to json {
                    "status_code" to 0
                }
                "required" to jsonArray { +"s" }
            }
        }
        // success
        // (SharedCodeKotlinx_serialization_runtimeJsonElement *)test4 __attribute__((swift_name("test3()")));
        fun test2(): JsonElement {
            val status = JsonObject(mutableMapOf())
            status.put("status_code", JsonPrimitive(0))
            val result = JsonObject(mutableMapOf())
            result.put("data", status)
            result.put("required", jsonArray { +"s" })
            return result
        }
        // (NSDictionary<NSString *, ...runtimeJsonElement *> *)anyTestInput:(NSDictionary<NSString *, ...runtimeJsonElement *> *)
        // input __attribute__((swift_name("anyTest(input:)")));
        fun anyTest(input: JsonObject) = json {
            "output"  to input
        }

        fun toString(any: Any?): String {
            return any.toString()
        }
    }
}
```
here is header file content:
![image](https://user-images.githubusercontent.com/7519916/76828726-8c660e80-685c-11ea-99c0-7155774a08da.png)

**Comment by sandwwraith** [comment]
Seems https://github.com/JetBrains/kotlin-native/issues/3991, which I mentioned in your other issue, is also the case here.
