### ISSUE TITLE
Swift example on iOS

### ISSUE THREAD

**Issue by markchristopherng** [Kotlin/kotlinx.serialization#762]
Hi,

Are you able to provide an example of how to deserialize and serialize code in Swift on iOS. I am a Kotlin/Java programmer and I'm not very familiar with Swift. It helps in evaluating this library!

**Comment by sandwwraith** [comment]
It's no difference from calling any other Kotlin code from Swift. See https://kotlinlang.org/docs/reference/native/objc_interop.html. You can create a sample iOS/Android MPP project via new project wizard and see sample there.

**Comment by markchristopherng** [comment]
It's not at simple as that. In Kotlin/JVM there are the Json and the JsonConfiguration classes to perform the serialization and de-serialization, however on iOS i can't find these classes. Do i need to include another pod? I am using KMP and using the iOS target. It is properly generating the swift code for the classes that i have annotated with @Serializable and their serializer but beyond that not sure how to use them with the absence of the Json classes.

**Comment by sandwwraith** [comment]
Ah, I get it. You need to export serialization dependency to framework. See https://kotlinlang.org/docs/reference/building-mpp-with-gradle.html#building-final-native-binaries , section "Exporting dependencies to binaries". 

Another way to do it is just declare a `public val json: Json = ...` in your common code somewhere. `Json` class and classes related to its public API would be automatically exported.

**Comment by markchristopherng** [comment]
Thanks for you help, i added the public val json approach and that worked like a charm.
I just needed that little bit of info to get it working on Swift. Using a xcode is a little bit foreign for a Java developer coding in Swift is fairly easy even if you have never done it before. 

I tried the other approach however i got an error framework already exists so i added a name "json" but  that didn't seem to do anything. Any ideas? I am using 1.3.61 kotlin and serialization runtime 0.14.0
 
 iosX64("ios") {
        binaries {
            framework("json")
        }
    }

**Comment by sandwwraith** [comment]
you need smth like
```
iosX64("ios") {
  binaries.framework {
     export("org.jetbrains.kotlinx:kotlinx-serialization-runtime-common:0.14.0")
  }
}
```

but I can't say for sure without whole buildscript

**Comment by markchristopherng** [comment]
cool, its late here but i will try to it when i have time, the first solution you gave me is good enough for me.

thanks again.
