### ISSUE TITLE
Support compile time registering of exhaustive list of possible subclasses for open classes and interfaces

### ISSUE THREAD

**Issue by thake** [Kotlin/kotlinx.serialization#766]
**What is your use-case and why do you need this feature?**
I'm trying to implement serialization for Avro's UNION type. A UNION can be interpreted as a sealed interface. Unfortunately, a sealed interface is currently not possible in kotlin. In order to support serializing to an Avro UNION type, one needs a way to register the possible subtypes of the polymorphic type already at compile time.

**Describe the solution you'd like**
A compile-time annotation that makes a polymorphic effectively SEALED by specifying all possible subtypes.

**Comment by sandwwraith** [comment]
We had this feature in our plans but postponed it for later. In the meantime, why `sealed class` is not sufficient?

**Comment by thake** [comment]
As you cannot inherit from multiple sealed classes you're limited to only one UNION in which your class definition can be.
For example, AVRO allows records to be used in multiple UNIONs with different records. If the AVRO record was used only in one UNION and always with the same other possible record definitions, then a sealed class would be sufficient to represent the AVRO structure in kotlin at compile time.

**Comment by sandwwraith** [comment]
Sealed interfaces are now a feature in Kotlin
