### ISSUE TITLE
Could not find org.jetbrains.kotlinx:kotlinx-serialization-properties:0.14.1.

### ISSUE THREAD

**Issue by ronjunevaldoz** [Kotlin/kotlinx.serialization#769]
**Describe the bug**
Could not find org.jetbrains.kotlinx:kotlinx-serialization-properties:0.14.1.
**To Reproduce**
implementation "org.jetbrains.kotlinx:kotlinx-serialization-properties:0.14.1"

**Expected behavior**

**Environment**
 - Kotlin version: 1.3.70
 - Library version:  0.20.0
 - Kotlin platforms: JVM
 - Gradle version: [e.g. 4.10]
 - IDE version (if bug is related to the IDE) [e.g. IntellijIDEA 2019.3.4]
 - Windows

**Comment by sandwwraith** [comment]
Sorry for misleading, version `0.14.1` does not exist and was added to `formats/README.md` by mistake. Use `0.20.0` with Kotlin 1.3.70.
