### ISSUE TITLE
[0.20.0] How to migrate ArrayClassDesc ?

### ISSUE THREAD

**Issue by valeriyo** [Kotlin/kotlinx.serialization#774]
While migrating from 0.14 to 0.20, what do I do with this?
```
  override val descriptor: SerialDescriptor = ArrayClassDesc(IntDescriptor)
```

Is `IntArraySerializer().descriptor` correct?

The migration docs (https://github.com/Kotlin/kotlinx.serialization/blob/v0.20.0/CHANGELOG.md) say nothing about `ArrayClassDesc`, which was public before. I also can't find any docs on `SerialDescriptor`/`SerialDescriptorBuilder` - how to use them properly. Maybe I'm missing crucial links, but I looked at the github thoroughly.

Thanks.

**Comment by sandwwraith** [comment]
It would be `ArraySerializer(Int.serializer()).descriptor`. Unfortunately, we forgot it in migration guide.

`SerialDescriptorBuilder` should have corresponding KDoc in sources or in IDEA's 'quick documentation' popup
