### ISSUE TITLE
Provide factory-like functions for custom collection descriptors

### ISSUE THREAD

**Issue by sandwwraith** [Kotlin/kotlinx.serialization#775]
Before 0.20.0, several available functions, like `ArrayClassDesc`, `NamedMapClassDescriptor` were available as public to use them in serializers which shape matches a standard collection one (e.g. `encode` method contains `encodeSerializableValue(ListSerializer(...), customTransformation(data))`).

After 0.20.0 release, these functions were deprecated in favour of `SerialDescriptorBuilder` factories. This approach has several drawbacks:

- It is not very discoverable since `ArrayClassDesc` and others were `internal`ized without a deprecation cycle (#774)
- It is unclear from the first glance that to create `ListDescriptor` one needs to pass `StructureKind.LIST` to a builder (such knowledge requires diving into documentation and understanding kinds concept)
- It is easy to violate LIST or MAP kind contracts by providing an incorrect number of child descriptors (btw, `SerialDescritptorImpl` contains incosistent with `ListLikeDescriptor` behaviour in `elementNames` part even when its kind is list — ListLikeDesctipor will return `index.toString()` while `SerialDescriptorImpl` returns `elementNames.get`)

**Comment by altavir** [comment]
The same goes for polymorphic and union descriptors as well as primitive descriptors. In the later case descriptor name is not an obvious parameter.

**Comment by sandwwraith** [comment]
There are `listSerialDescriptor()` (https://github.com/Kotlin/kotlinx.serialization/blob/d317f5dcf7f3f4b92b0b9f2ea72c3b4903371306/core/commonMain/src/kotlinx/serialization/descriptors/SerialDescriptors.kt#L188) and `mapSerialDescriptor()` (https://kotlinlang.org/api/kotlinx.serialization/kotlinx-serialization-core/kotlinx.serialization.descriptors/map-serial-descriptor.html) functions now. They can be used either inside `buildClassSerialDescriptor` builder or in `SerialDescriptor(name, original)` delegate builder.
