### ISSUE TITLE
Wrap NumberFormatException as SerializationException

### ISSUE THREAD

**Issue by vanniktech** [Kotlin/kotlinx.serialization#779]
**Describe the bug**

When parsing a JSON with an invalid number you get a `NumberFormatException`.

**To Reproduce**

Parse a JSON where a `Number` is expected but use a string. `{"integer": "test"}`
Now this will throw a `NumberFormatException`

**Expected behavior**

Throw a `SerializationException` & pass along the `NumberFormatException` as the throwable

**Environment**
 - Kotlin version: 1.3.60
 - Library version: 0.14.0
 - Kotlin platforms: JVM
 - Gradle version: 6.2

**Comment by sandwwraith** [comment]
I think this is a duplicate of #704 and was fixed in 0.20.0. Have you tried it?

**Comment by vanniktech** [comment]
I haven't since 0.20.0 depends on Kotlin 1.3.71 and a bunch of my dependencies haven't updated :/ 
The commit looks good though, so feel free to close. For now I'm catching Throwable

**Comment by vanniktech** [comment]
I've updated to 0.20.0 and things are looking good. Thank you
