### ISSUE TITLE
JSON property is incorrect if base class is in a different module/package 

### ISSUE THREAD

**Issue by ctadlock** [Kotlin/kotlinx.serialization#783]
See attached screenshot; class A and B need to be in different modules/packages. If they are in the same file it works as expected.

**Environment**
 - Kotlin version: 1.3.61
 - Library version: 0.20.0
 - Kotlin platforms: JVM
 - Gradle version: 6.*

![image](https://user-images.githubusercontent.com/1539397/78197747-245a1f80-743b-11ea-9fe7-77603a24dea5.png)

**Comment by ctadlock** [comment]
Update.. If the field is in the body of the base class and not the constructor, it works as expected.

![image](https://user-images.githubusercontent.com/1539397/78198248-cdede080-743c-11ea-92b3-748f11f8df19.png)

**Comment by whoyawn** [comment]
+1. If I use Retrofit with kotlinx via https://github.com/JakeWharton/retrofit2-kotlinx-serialization-converter and try serializing the resulting response, I get an "Encountered unknown key {property}" error even if my property was declared with an annotation. Placing the base class in the same place as the subclass fixed my problem.

**Comment by sandwwraith** [comment]
https://github.com/Kotlin/kotlinx.serialization/issues/378

**Comment by sandwwraith** [comment]
https://github.com/Kotlin/kotlinx.serialization/issues/378#issuecomment-663134060
