### ISSUE TITLE
Polymorphic deserialization `type` field

### ISSUE THREAD

**Issue by saied89** [Kotlin/kotlinx.serialization#786]
Currently the expected value of `type`  field is the *canonical name* of sub classes. Is it possible to customize this value?

ps: Subclass name or ParentClass.SubClass might be better choices for this value. The way it is moving your model class to another package breaks the api with clients.

**Comment by qwwdfsad** [comment]
Not yet, but we are considering adding this.
As a workaround, you can change the canonical name of the class by annotation it with `@SerialName` annotation

**Comment by sandwwraith** [comment]
We do not plan to implement global strategy, but we may end up with adding functionality for specific sealed hierarchies, as discussed in #1950 and #2319
