### ISSUE TITLE
Provide a way to inject/intercept generated serializer

### ISSUE THREAD

**Issue by Dominaezzz** [Kotlin/kotlinx.serialization#793]
**What is your use-case and why do you need this feature?**
Say I have a class like this.
```kotlin
data class Data(
    val id: Int,
    val name: String,
    val email_addresses: List<String>
)
```

The shape of the input json can either look like,
```json
{
    "id": 7,
    "name": "Dominaezzz"
}
```
```json
{
    "id": 7,
    "name": "Dominaezzz",
    "email_address": "username@host.com"
}
```
```json
{
    "id": 7,
    "name": "Dominaezzz",
    "email_addresses": ["username@host.com", "other_username@host.com"]
}
```

This is too much to ask the plugin to deal with, so I use the `JsonTransformingSerializer` to make sure the field always looks like the third json example, generate the naive serializer with `@Serializer(forClass = Data::class)` to pass to the `JsonTransformingSerializer`, then annotate the `Data` class with this custom setup. Problem solved.
Now I have a few other classes with this exact transformation, and I'm having to repeat myself quite a bit.

**Describe the solution you'd like**
Ideally I would like to create a single transformation class, and have the generated serializer be injected by the plugin. As supposed to setting up the injection myself.
```kotlin
class JsonFixer(@GeneratedSerializer val gSerializer: KSerializer<Data>) : JsonTransformingSerializer(gSerializer) {
    // .....
}

@Serializer(JsonFixer::class)
data class Data(
    val id: Int,
    val name: String,
    val email_addresses: List<String>
)
```

or perhaps something like this,
```kotlin
object JsonFixer : SerializerPlugin<Data> {
    override fun serialize(delegate: KSerializer<Data>, encoder: Encoder, value: T) {
        // transform
    }

    override fun deserialize(delegate: KSerializer<Data>, decoder: Decoder): T {
        // transform
    }
}

@Serializer(with = /* default or specified */, plugins=[JsonFixer::class, /* other transforms */])
data class Data(
    val id: Int,
    val name: String,
    val email_addresses: List<String>
)
```
which would allow for a pipeline of transformations.

**Comment by shanshin** [comment]
Cloased as a buplicate of #1169
