### ISSUE TITLE
JSON5 support

### ISSUE THREAD

**Issue by acanthite1855** [Kotlin/kotlinx.serialization#797]
**What is your use-case and why do you need this feature?**
It would be nice to have JSON5 support to serialize/deserialize configs and other data files that may be written/read by humans. It has quite useful features:
- No quotes for keys when they're not needed
- Multi-line strings
- Trailing comas
- Single- and Multi-line comments.
- and some [more](https://json5.org/)

**Describe the solution you'd like**
Well, pretty much the same as for JSON but form JSON5. I don't know what else to say here. All details on the format are on [json5.org](https://json5.org/)

**Comment by sandwwraith** [comment]
Side note: trailing commas and unquoted literals are now somewhat supported by `isLenient = true` setting

**Comment by MarcelReiter** [comment]
Side note: IntelliJ has native support (e.g. syntax highlighting) for Json5 ([link](https://www.jetbrains.com/help/idea/json.html)), which would make this a cool feature for Android developers especially

**Comment by lisonge** [comment]
now  How is it going ？

**Comment by aSemy** [comment]
I'm also interested in this. For now, I've converted an existing JSON5 Java library to Kotlin and added some Kotlinx Serialization interop, so it can convert to/from JSON5/JSON. Please let me know if it's useful, and you're able to help make it more stable (I haven't tested it significantly) 

https://github.com/adamko-dev/json5-kotlin

**Comment by AmibeSkyfy16** [comment]
Hi, any news about that ?
Im trying to use json5, but it seems that kotlinx.serialization dont like comment

```json
{
  /*
   * The day when players will be able to do damage to themselves. default -> 2
   */
  "dayOfAuthorizationOfThePvP": 2,

  /*
   * The day when players can get into the nether. default -> 4
   */
  "dayOfAuthorizationOfTheEntryInTheNether": 4,

  /*
   * If players can use enderpearl to assault bases or not
   */
  "allowEnderPearlAssault": false
}
```

Caused by: java.lang.RuntimeException: kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 11: Expected semicolon ':', but had ' ' instead at path: $
JSON input: {
  /*
   * The day when players will b.....
	at ch.skyfy.jsonconfig.example3.config.Configs.<clinit>(Configs.kt:25)
	... 90 more
Caused by: kotlinx.serialization.json.internal.JsonDecodingException: Unexpected JSON token at offset 11: Expected semicolon ':', but had ' ' instead at path: $

**Comment by sandwwraith** [comment]
I don't think we'll embed JSON5 standard into our implementation. Current policy for format requests is 'write your own 3rd party lib with dependency on the core'

**Comment by AmibeSkyfy16** [comment]
Thank you very much, I think that's what I need

**Comment by ubuntudroid** [comment]
> Side note: trailing commas and unquoted literals are now somewhat supported by `isLenient = true` setting

For me trailing commas are throwing an error. What exactly does "somewhat" mean and is there a way to disable that check?

**Comment by ubuntudroid** [comment]
Alright, thanks for checking so quickly anyway! 🙏

**Comment by GazimSoliev** [comment]
I can't parse API of this site cuz this library doesn't support trailing comma: https://developers.home-assistant.io/docs/intent_conversation_api/#response_types

**Comment by lisonge** [comment]
This parser still doesn't support single-quoted strings in JSON5

https://github.com/Kotlin/kotlinx.serialization/issues/2765

maybe it can be reopend

**Comment by sandwwraith** [comment]
Yes, we decided not to support single/double quotes for now, this is something for future improvement if there is a demand for it.
