### ISSUE TITLE
Info required - how to enable serialization on the compiler? (Support for Bazel)

### ISSUE THREAD

**Issue by jongerrish** [Kotlin/kotlinx.serialization#799]
**Describe the bug**

Trying to get serialization workin in Bazel. As I understand it, with 1.3.71 the serializer plugin ships as part of the compiler, however *.serializer() methods are not generated.

Is there something specific I need to do to enable serialization processing on the compiler? The [Bazel rules](https://github.com/bazelbuild/rules_kotlin) have a [kt_compiler_plugin](https://github.com/bazelbuild/rules_kotlin) rule which supports passing options to the compiler, I think via -P plugin but I'm not sure of the plugin id (for the built in plugin or any of the options).

**To Reproduce**
Attach a code snippet or test data if possible.

**Expected behavior**

*.serializer() are generated

**Environment**
 - Kotlin version: 1.3.71
 - Library version: 0.20.0
 - Kotlin platforms: JVM
 - Gradle version: N/A - Bazel rules at master
 - IDE version: N/A command line only
 - Other relevant context: Bazel

**Comment by sandwwraith** [comment]
Hi, 

'ships as part of the compiler' is true only for IDE plugin. In CLI, the things remain the same, as with other compiler plugins. 

I'm not familiar with bazel, but it seems that it just downloads kotlinc distribution from github releases. In that case, serialization plugin is located in `kotlinx-serialization-compiler-plugin.jar`, and it can be enabled in a same way as e.g. `allopen-compiler-plugin.jar`, which `kt_compiler_plugin` rule seems to support.

**Comment by jongerrish** [comment]
Thanks, that's just the info I was looking for, tracking adding support to Bazel here https://github.com/bazelbuild/rules_kotlin/issues/313
