### ISSUE TITLE
typeOf serializer lookup should check contextual serializers

### ISSUE THREAD

**Issue by sgarfinkel** [Kotlin/kotlinx.serialization#802]
**What is your use-case and why do you need this feature?**

This feature is useful to support serializer lookup at runtime. My specific use-case is to implement a Ktor serializer that respects contextual serializers. I'm working with linked data, which means the deserialized data types should hold a reference to the HttpClient so they can resolve links. I've implemented a contextual serializer that injects the configured HttpClient, but to actually use the serializer (and support collection types), requires additional work.

**Describe the solution you'd like**

Add a function `SerialModule.serializer(type: KType)`, replace:

https://github.com/Kotlin/kotlinx.serialization/blob/cf892556abc91d45bdb141e6992231b6c186b4fc/runtime/commonMain/src/kotlinx/serialization/SerializerResolving.kt#L57

With 

```kotlin
typeArguments.isEmpty() -> getContextualOrDefault(rootClass)
```

**Comment by qwwdfsad** [comment]
We already have this function: `SerialModule .getContextualOrDefault`.
Could you please elaborate on whether it's enough to solve your use-case?

**Comment by sgarfinkel** [comment]
The suggested prototype is different, accepting a `KType` instead of a `KClass`. The function that already exists is very useful for serialization by Kotlin libraries which will likely use the `KType`. It's non-trivial to convert a KType to a KClass, and a lot of that conversion is already handled in the `serializer(KType)` function.

**Comment by sgarfinkel** [comment]
Unless it's changed, `getContextualOrDefault` doesn't do the automated checking for various collection types that the `serializer(type: KType)` function does, which makes it not as useful in general use-cases.

**Comment by sandwwraith** [comment]
`getContextualOrDefault` first looks up in the context, then calls `serializer(KType)`, so it can work with lists.

Unless you have `List<@Contextual MyDate>`. Is this your use-case?

**Comment by sgarfinkel** [comment]
Yes, that is exactly the issue. The function currently does not support collections of mapped types.
