### ISSUE TITLE
Warn users about limited support or unsupported features

### ISSUE THREAD

**Issue by cy6erGn0m** [Kotlin/kotlinx.serialization#804]
People may accidentally use unsupported features such as serializing private classes reflectively (due to [KT-38285](https://youtrack.jetbrains.com/issue/KT-38285)) or renaming a companion object.

Would be nice to generate at least warnings to clarify what is not going to work and when.

**Comment by qwwdfsad** [comment]
Should be more or less fixed in the upcoming release
