### ISSUE TITLE
Back-end (JVM) Internal error: wrong bytecode generated instead of 'Inline classes not supported' diagnostic

### ISSUE THREAD

**Issue by lamba92** [Kotlin/kotlinx.serialization#814]
When compiling [this commit](https://github.com/lamba92/dragalia-library/tree/f977119e259d7f34d01b11c27033b53278a4e08d) the compiler errors when trying to compile [AdventurerEntity.kt](https://github.com/lamba92/dragalia-library/blob/f977119e259d7f34d01b11c27033b53278a4e08d/domain/src/commonMain/kotlin/com/github/lamba92/dragalialost/domain/entities/AdventurerEntity.kt#L10) at line 10. 

I googled the error and found those similar issues:
 - #444
 - [KT YouTrack KT-28791](https://youtrack.jetbrains.com/issue/KT-28791)

None of those seems related to my issue. Also I thought that maybe `@Transient` should have been applied to function backed fields, but IDEA quickly hints that is is superfluous since it's already transient. 

[Here](https://travis-ci.org/github/lamba92/dragalia-library/builds/679183413)'s a full report of the build on TravisCI. The Gradle Build Scan is also available [here](https://travis-ci.org/github/lamba92/dragalia-library/builds/679183413), ask for invite, I will quickly grant it.

**Environment**
 - Kotlin version: 1.3.72, 1.4-M1
 - Library version: 0.20.0-1.4-M1
 - Kotlin platforms: JVM
 - Gradle version: 6.3

[KT YouTrack cross-issue-reference](https://youtrack.jetbrains.com/issue/KT-38574)

**Comment by lamba92** [comment]
After investigating, there was an inline class from an external library as on of the parameters. A better error message would be nice! It took me a week to figure this out!

That is a duplicate of [KT-28791](https://youtrack.jetbrains.com/issue/KT-28791).

**Comment by sandwwraith** [comment]
Sorry to hear that. We have a diagnostic that should emit an error when inline class is in the serializable class, but for some reason it failed in your case, so this is still a bug

**Comment by qwwdfsad** [comment]
Value classes are now properly supported
