### ISSUE TITLE
deserialization: IllegalStateException when null occurs in JSON input in place of an expected non-null object

### ISSUE THREAD

**Issue by AcidApeStudios** [Kotlin/kotlinx.serialization#816]
`SerializationException` should be thrown instead.

Example: try to parse this JSON:

```
{"foo":null}
```

for deserializing this class:

```
class MyClass(val foo: SomeObject)
```

This exception is thrown:

```
    java.lang.IllegalStateException: Expected class kotlinx.serialization.json.JsonObject but found class kotlinx.serialization.json.JsonNull
        at kotlinx.serialization.json.internal.AbstractJsonTreeInput.beginStructure(TreeJsonInput.kt:224)
```

**Comment by qwwdfsad** [comment]
Please update to `kotlinx.serialization` 0.20.0.
On 0.20.0 `JsonDecodingException` is properly thrown: `Unexpected JSON token at offset 7: Expected string literal with quotes. Use 'JsonConfiguration.isLenient = true' to accept non-compliant JSON.
 JSON input: {"foo":null}`

**Comment by AcidApeStudios** [comment]
This is 0.20.0. My above example was too simple, sorry. The bug only manifests itself during polymorphic deserialization:

```
    @Serializable
    abstract class MessageBase {
        var name = ""
    }

    @Serializable
    @SerialName("derived")
    class DerivedMessage : MessageBase() {
        @Serializable
        class CompoundObject {
            var a = ""
        }
        var c = CompoundObject()
    }

    @Test
    fun scratch() {
        val serialModule = SerializersModule {
            polymorphic(MessageBase::class) {
                DerivedMessage::class with DerivedMessage.serializer()
            }
        }

        Json(context = serialModule).parse(MessageBase.serializer(), """{"name":"foo","type":"derived","c":null}""")
    }
```

The problem is in `AbstractTreeJsonInput.beginStructure()`: there are `cast()` calls, those use `check()` and hence throw `IllegalStateException` if the check fails.
