### ISSUE TITLE
kotlin serialization library with iml projects

### ISSUE THREAD

**Issue by ka3a4ok** [Kotlin/kotlinx.serialization#823]
Is it possible to use kotlin serialization library with just *.iml projects? Without gradle or maven? How to add serialization plugin ?

**Comment by sandwwraith** [comment]
There is no convenient way to setup iml project with any of the compiler plugins, unfortunately.

There is one workaround though: manually edit iml file

Find one that related to your module (`.idea/modules/<module_name>/module_name.iml`), find `<compilerArguments>` section in it, edit/create `<option name="pluginClasspaths">` with option as following:

```xml
<option name="pluginClasspaths">
  <array>
       <option value="$KOTLIN_BUNDLED$/lib/kotlinx-serialization-compiler-plugin.jar" />
  </array>
</option>
```
