### ISSUE TITLE
KSerializer.serialize() of nullable type not invoked for null values

### ISSUE THREAD

**Issue by koral--** [Kotlin/kotlinx.serialization#824]
In the project's code there is a nullable value. 
Magic not null values need to be deserialized to null.
And nulls need to be serialized to non-null magic values.

While I'm able to deserialize to nulls the serialization does not work. `serialize()` method is not fired and null is passed to serialized form.

**To Reproduce**
Serializer code:
```kotlin
internal object LocalTimeSerializer : KSerializer<LocalTime?> {

    override val descriptor = PrimitiveDescriptor("LocalTime?", PrimitiveKind.INT)

    override fun deserialize(decoder: Decoder): LocalTime? = when (val seconds = decoder.decodeInt()) {
       -1 -> null
        else -> LocalTime.ofSecondOfDay(seconds.toLong())
    }

    override fun serialize(encoder: Encoder, value: LocalTime?) {
        when (value) {
            null -> encoder.encodeInt(-1) //this line is never reached despite that nulls exist in serialized lists
            else -> encoder.encodeInt(value.toSecondOfDay())
        }
    }
}
```

Usage inside serializable class:
```kotlin
val times: List<@Serializable(with = LocalTimeSerializer::class) LocalTime?>,
```

**Expected behavior**
`serialize()` method is invoked for nulls.

**Environment**
 - Kotlin version: 1.3.72
 - Library version: 0.20.0
 - Kotlin platforms: JVM
 - Gradle version: 6.3+

**Comment by Dominaezzz** [comment]
Your serializer is probably being wrapped in another serializer that handles nulls.

**Comment by koral--** [comment]
I'm not explicitly wrapping it.
Serialization is used with Retrofit like that:
```
val converterFactory = Json(JsonConfiguration(ignoreUnknownKeys = true))
        .asConverterFactory("application/json".toMediaType())
```
Apart from enabling `ignoreUnknownKeys` there are no more customizations.

**Comment by vladrotea** [comment]
+1, I have the same issue.

**Comment by sandwwraith** [comment]
I think the issue happens because serializer is automatically wrapped with a standard `NullableSerializer` from the runtime library
