### ISSUE TITLE
Marking properties as Transient from an interface

### ISSUE THREAD

**Issue by 0ffz** [Kotlin/kotlinx.serialization#825]
**What is your use-case and why do you need this feature?**
I have a class implementing an interface with many properties that should not be serialized. It clutters up the code to have to place the `@Transient` annotation over every property, and on top of that IntelliJ's automatic cleanup then places spacing between properties with annotations, which makes the code harder to read.

**Describe the solution you'd like**
I've looked around for a bit and couldn't find any way to mark many properties as transient without being repetitive. Perhaps a nice way to go about this could be to allow defining a property as transient within an interface, though I understand if there's a good design reason this can't be done that I'm overlooking. Thanks in advance!

**Comment by sandwwraith** [comment]
Generally, we do not favor inheriting serialization-related annotations, because it may lead to unexpected behavior (e.g. 'why my fields are not serialized? *3 hours of debugging later* ahh, they're marked transient in superclass from  code that I do not own and I can't do anything with that)

**Comment by 0ffz** [comment]
Ah good point. Any other idea I've had for applying it to multiple fields sounds like it'll run into the same problem, I guess it's better to be explicit. Feel free to close this issue.
