### ISSUE TITLE
The Properties parser doesn't parse nested maps 

### ISSUE THREAD

**Issue by francos** [Kotlin/kotlinx.serialization#826]
**Describe the bug**

When trying to parse a `Map` with nested `Map`s inside it (as values) they are ignored.

**To Reproduce**

```kotlin
fun main(args: Array<String>) {
    val map = ...
    Properties.loadNullable(TestClass1.serializer(), map)
}

@Serializable
data class TestClass1(
    val name: String,
    val test2: List<TestClass2>
)

@Serializable
data class TestClass2(
    val name: String,
    val value: String
)
```

**Expected behavior**

`Map`s inside the main `Map` should be parsed to the proper classes too.

**Environment**

- Kotlin version: 1.3.72
- Library version: 0.20.0
- Kotlin platforms: JVM
- Gradle version: 5.6.4

**Comment by sandwwraith** [comment]
Unfortunately, `Properties` are not intended to work in that way – they're intended to work with flat maps, like Java's .properties files. You can take a look at Properties documentation to find an example.

We have an idea to implement a proper `Mapper`, like a Jackson one, to support your use-case, but there's no strict timeframe commitment yet.

**Comment by francos** [comment]
Hi @sandwwraith, thanks for explaining this. 

I was not aware of that. Since there was a `Mapper` before and it was deprecated and replaced with `Properties` I assumed this latter was suppose to work as a mapper.

Should I close this issue or do you wanna keep it open for when the `Mapper` is implemented?

**Comment by qwwdfsad** [comment]
Let's close it and see if there are more report about nested maps. If so, we would consider adding real `Mapper` format to the library while keeping `properties` (that are intended to be used as regular Java properties) as is

**Comment by francos** [comment]
Hi @qwwdfsad, just FYI, some use cases for the `Mapper` were added to this issue: https://github.com/Kotlin/kotlinx.serialization/issues/746

**Comment by qwwdfsad** [comment]
Thanks!
