### ISSUE TITLE
How to use mongodb ObjectId in mutliplatform project?

### ISSUE THREAD

**Issue by ojaynico** [Kotlin/kotlinx.serialization#827]
I get this error when i try to retrieve documents from my mongodb database and it is because the _id in the database is an Object and the variable is defined as a String in my data class. Do we have any solution that favors kotlinjs too and works out of the box with kotlin jvm?

> org.bson.BsonInvalidOperationException: readString can only be called when CurrentBSONType is STRING, not when CurrentBSONType is OBJECT_ID.

**Comment by Dominaezzz** [comment]
Did you write the BSON decoder yourself?

**Comment by ojaynico** [comment]
@Dominaezzz no i didn't. I have searched everywhere though on how to use ObjectId with kotlinJS and failed. I have resorted to the implementation from this example in the kotlin playground.

> import kotlinx.serialization.Serializable

@Serializable
data class ShoppingListItem(val desc: String, val priority: Int) {
    val id: Int = desc.hashCode()

    companion object {
        const val path = "/shoppingList"
    }
}

[https://play.kotlinlang.org/hands-on/Full%20Stack%20Web%20App%20with%20Kotlin%20Multiplatform/03_A_Simple_API_Server](url)

**Comment by Dominaezzz** [comment]
This library doesn't come with bson support. I don't think the issue is in this library.

**Comment by ojaynico** [comment]
@Dominaezzz thanks for your response. I hope this will be supported sometime in the future.
