### ISSUE TITLE
IDE Warning: Serializer not found for Type

### ISSUE THREAD

**Issue by PaulWoitaschek** [Kotlin/kotlinx.serialization#829]
When having the serializer for a library class in another gradle module the ide shows a warning that no serializer is found.
It compiles fine but android studio is filled with warnings.

I created a minimal self contained example.

The warning pops up here:
https://github.com/PaulWoitaschek/SerializationBug/blob/fc8b8291857a8d2a73344b62e78f28eb8a80bdb3/app/src/main/java/com/example/serializationbug/Test.kt#L12

and I think it's triggered by
https://github.com/PaulWoitaschek/SerializationBug/blob/fc8b8291857a8d2a73344b62e78f28eb8a80bdb3/mylibrary/build.gradle#L5

The library has a compileOnly dependency on the three ten library but the app module as an implementation dependency on the threeten-android backport.

**Comment by sandwwraith** [comment]
Probably it's just an incorrect handling of `@file:UseSerializers(LocalDateSerializer::class)` annotation. I'll look into that. Does the warning disappear if `@Serializable(LocalDateSerializer::class)` is used directly on property?

**Comment by PaulWoitaschek** [comment]
Yes the warning disappears. But imo this is more due to https://github.com/Kotlin/kotlinx.serialization/issues/830

**Comment by shanshin** [comment]
Not reproduced for `@Contextual` properties in latest versions
