### ISSUE TITLE
Compiler Suppress Flags

### ISSUE THREAD

**Issue by PaulWoitaschek** [Kotlin/kotlinx.serialization#831]
Right now in my project I can see 60 occurrences of the following line:
```kotlin
@Serializable(with = LocalDateSerializer::class)
```

Instead I could use contextual serialization. However that would not remove the ide warnings. I could suppress the warnings globally but that would remove the warnings on something that I don't handle myself.

My proposal is to have a compiler flag where you can simply add a list of classes you are serializing and for which no warning is raised.
i.e. freeCompilerArgs: `-Xkotlinx-serialization-xyz=java.util.Date,java.util.UUID`

**Comment by sandwwraith** [comment]
Part of #507
