### ISSUE TITLE
Make JsonConfiguration itself @Serializable

### ISSUE THREAD

**Issue by hfhbd** [Kotlin/kotlinx.serialization#832]
**What is your use-case and why do you need this feature?**
I would like to store the JsonConfiguration itself in a Json file and read them at startup. This allows to use different behavior with a simple change in the config files.

eg having a prod configuration and a debug configuration, which use a less strict Json De-/Encoder or uses pretty print.

Of course, the JsonConfiguration for reading the json configs must be static defined and cannot be defined in the config file.
 
**Describe the solution you'd like**
Add @Serializable to JsonConfiguration

Current workaorund:
Implement a custom serializer, which I did for my project

**Comment by sandwwraith** [comment]
Closing for the reason described in https://github.com/Kotlin/kotlinx.serialization/pull/877#pullrequestreview-441582372

**Comment by hfhbd** [comment]
Its fine, my implementation was only adding 1 attribute :) But I would like to have the option changing the json behaviour with a config file, even with the new API.

**Comment by sandwwraith** [comment]
https://github.com/Kotlin/kotlinx.serialization/pull/877#issuecomment-1081826204

**Comment by sandwwraith** [comment]
Not planned because it is still not possible to create `Json` from `JsonConfiguration` and `JsonConfiguration` constructor is intended to be internal.
