### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: Didn't find class "kotlinx.serialization.internal.GeneratedSerializer"

### ISSUE THREAD

**Issue by 1530120997** [Kotlin/kotlinx.serialization#837]
**Describe the bug**
ios is work good  android jar crash
**To Reproduce**
java.lang.NoClassDefFoundError: Failed resolution of: Lkotlinx/serialization/internal/GeneratedSerializer;

**Expected behavior**

**Environment**
 - Kotlin version: [1.3.70]
 - Library version: [0.20.0]
 - Kotlin platforms: [ Native or their combinations]
 - Gradle version: [3.6.3]
 - IDE version (if bug is related to the IDE) [Android Studio 3.6]

**Comment by sandwwraith** [comment]
Can you post more details? E.g. full stacktrace, do you use Proguard, R8, or some other minifying tooling for android?
