### ISSUE TITLE
Identity test for default properties

### ISSUE THREAD

**Issue by agcom** [Kotlin/kotlinx.serialization#838]
**What is your use-case and why do you need this feature?**

Assume this input Json string,

```json
{
    "username": "hello",
    "name": null
}
```

which differs from

```json
{
    "username": "hello"
}
```

If we parse these strings to kotlin objects by the following snippet,

```kotlin
fun main() {
    
    val json = Json(JsonConfiguration.Stable.copy(encodeDefaults = false))
    
    val input1 = """{"username": "hello","name": null}"""
    val input2 = """{"username": "hello"}"""
    
    val update1 = json.parse(Update.serializer(), input1)
    val update2 = json.parse(Update.serializer(), input2)
    
}

@Serializable
data class Update(val username: String, val name: String? = null)
```

they produce the same data object `update1 == update2`.

Then encode them,

```kotlin
val up1 = json.toJson(Update.serializer(), update1)
val up2 = json.toJson(Update.serializer(), update2)
```

`up1` and `up2` both will be

```json
{
    "username": "hello"
}
```

I'm expecting `up1` to be

```json
{
    "username": "hello",
    "name": null
}
```

just like it's corresponding input.

**Why would i need such a thing?**

I was implementing a Rest Api and was using Mongo database.

The data I'm willing to store is a simple username (identifier) and a name which *can be null*.

The input strings correspond to the update needed to some document.

`input1` is trying to null the name.`input2` is doing nothing.

But if I decode them, and then encode them and apply the updates, I end up doing nothing because they both encode to

```json
{
    "username": "hello"
}
```

Why not pass them directly (avoid decode, then encode)? Need to check business logic. In this case input validation.

**Describe the solution you'd like**

Identity check during encoding default elements (through an annotation, so the plugin will add another '=' character where needed).

Currently the work around is using custom serializer and checking identity for default values.

```kotlin
@Serializable
data class Update(val username: String, val name: String? = Defaults.NAME) {
    
    object Defaults {
        
        val NAME = String() // A unique pointer
        
    }
    
    @Serializer(Update::class)
    companion object : KSerializer<Update> {
    
        override fun serialize(encoder: Encoder, value: Update) {
            
            encoder.beginStructure(descriptor).apply {
                
                encodeStringElement(descriptor, 0, value.username)
                
                // Identity check here
                if(value.name !== Defaults.NAME || shouldEncodeElementDefault(descriptor, 1)) {
                    
                    encodeNullableSerializableElement(descriptor, 1, String.serializer(), value.name)
                    
                }
                
            }.endStructure(descriptor)
            
        }
        
    }
    
}
```

Now i can distinguish between the `input1` and `input2`.

`input1` after decoding, encodes to 

```json
{
    "username": "hello",
    "name": null
}
```
and `input2` after decoding, encodes to 

```json
{
    "username": "hello"
}
```

sounds good for this small example, but writing custom serializer for big data classes = boiler plate code.

**Comment by sandwwraith** [comment]
I'm a little bit confused by the title because there is only one identity for `null` and there is no way to distinguish between null from json and null from defaults without storing additional information (which you serializer does)

**Comment by Agcom** [comment]
> I'm a little bit confused by the title because there is only one identity for `null` and there is no way to distinguish between null from json and null from defaults without storing additional information (which you serializer does)

You're right about null. But more broad, I'm trying to distinguish between existence and non-existence of default value in the input. So encoding the input (after parsing) would produce the exact Json as the input.
Like in Javascript, you would get an *undefined* but in Kotlin you will get a default value. That's lose of information about property existence.
* Updated the title
