### ISSUE TITLE
ByteArray needed

### ISSUE THREAD

**Issue by lonevetad** [Kotlin/kotlinx.serialization#859]
**What is your use-case and why do you need this feature?**
I receive a ByteArray with exactly 16 byte (it's a UUID).

**Describe the solution you'd like**
some primitive and automatic deserializer like ```String.serializer()``` (and related stuffs) do.

**Comment by Dominaezzz** [comment]
What's wrong with `ByteArraySerializer()`?

**Comment by lonevetad** [comment]
I expect a start of an array of byte but I found "50". That's weird because the uuid is correctly sent.
I worked around by using another package, sadly.

**Comment by qwwdfsad** [comment]
Could you please provide more details on your problem?
What format do you use, JSON, Protobuf or CBOR?
What exactly is wrong, e.g. could you post a short snippet that behaves improperly?
