### ISSUE TITLE
Add support for Kotlin/Native

### ISSUE THREAD

**Issue by jonasfranz** [Kotlin/kotlinx.serialization#86]
Since Kotlin/Native 0.6 supports multiplattform projects, it would be nice to have also support for kotlin native.

https://blog.jetbrains.com/kotlin/2018/02/kotlinnative-v0-6-is-here/

**Comment by sandwwraith** [comment]
Yes, Kotlin/Native support is in our plan and we've already started working at it :)

**Comment by rytedesigns** [comment]
Is there an eta on Kotlin/Native support?

**Comment by Arne517** [comment]
@sandwwraith I'm also curious about an ETA on kotlin/native support

**Comment by sandwwraith** [comment]
@rytedesigns @Arne517 there is a K/N compatible version of this library, but the compiler plugin API is not available on Native yet. To try it out (remember, this is early preview), there are two options:

* Use `sourcegen` branch and Kotlin source generator from there, which uses DSL to generate data classes with serializers compatible with library (see `example-sourcegen` folder and its `buildSrc`)
* Use `json-ast` branch and `jsonparser` native module, which contains JSON parser and JSON tree model (but can't map it on data classes yet)

**Comment by AndreasBackx** [comment]
@sandwwraith is there an update you could give on K/N support? We're looking at some options for managing APIs on Android and iOS using Kotlin Native.

**Comment by ScottPierce** [comment]
When will the Kotlin/native implementation be ready to try?

**Comment by nish-d** [comment]
https://blog.jetbrains.com/kotlin/2018/07/kotlinnative-v0-8-released/

According to this kotlinx.serialization is now supported with kotlin/native. But I am still unable to use this.

**Comment by sandwwraith** [comment]
@nish-d Support for native is limited for now and expressed as separate JSON parser. We are working in this direction.

**Comment by sandwwraith** [comment]
I'd like to announce an early access preview of kotlinx.serialization plugin for Native. The showcase project can be found at https://github.com/sandwwraith/KotlinSerializationPlayground/tree/native_preview/ . Some rules of thumb:

* Works with Kotlin/Native 0.9-dev-3770
* Version of kotlinx.serialization plugin must be `0.7.0-eap-1`, serialization runtime library `0.7.0-eap-3`.
* Kotlin version is 1.3-M2
* Kotlin Native Gradle plugin does not support compiler plugins yet, passing plugin option to compiler must be performed manually (see https://github.com/sandwwraith/KotlinSerializationPlayground/blob/native_preview/native/build.gradle#L40 , note the `-unshaded` suffix in maven coordinates).
* Internal kotlinx.serialization API has been significantly changed to match corresponding [KEEP](https://github.com/Kotlin/KEEP/blob/serialization/proposals/extensions/serialization.md), sources for 0.7.0 build can be found in branch `core_refactoring`.

What **works**: 

* `@Serializable` classes with primitive or `@Serializable` properties
* Standard collections
* `@Optional` and `@SerialName` annotations

What **does not work**:

* `@Serializable` classes with generics (except standard collections)
* Enums and arrays (`Array<T>, ByteArray, etc`)
* `@Transient` initializers and `init` blocks
* `@SerialInfo`-based annotations

**Comment by nish-d** [comment]
The showcase project has different version numbers than what you have mentioned.

**Comment by sandwwraith** [comment]
@nish-d I can see correct versions: https://github.com/sandwwraith/KotlinSerializationPlayground/blob/native_preview/gradle.properties#L1
(notice that showcase project with native is located in `native_preview` branch, not master)

**Comment by daudrain** [comment]
@sandwwraith In [SerialImplicits.kt](https://github.com/Kotlin/kotlinx.serialization/blob/v0.9.0/runtime/common/src/main/kotlin/kotlinx/serialization/SerialImplicits.kt#L12), it is noted that the code won't work with kotlin/native.
Does that mean protocolbuffer serialization/deserialization is not available yet for kotlin-native?

**Comment by sandwwraith** [comment]
@daudrain It is available, but without the possibility to specify custom serial ids – all properties are enumerated in order starting from 1.

**Comment by sandwwraith** [comment]
kotlinx.serialization plugin for native has been feature-complete for several latest releases, so I think this may be closed now. 🎉
