### ISSUE TITLE
Accessing constructors of @Serializable annotated classes from another compiler plugin causes: `Recursive call in a lazy value under LockBasedStorageManager`

### ISSUE THREAD

**Issue by AhmedMourad0** [Kotlin/kotlinx.serialization#860]
I'm not sure if this's a Kotlinx.serialization problem, but it is what's causing it for me.

**Describe the bug**
Calling `ClassDescriptor#getConstructors` from other compiler plugins on a class annotated with `@Serializable` will cause build to fail with this error:

```
java.lang.IllegalStateException: Recursive call in a lazy value under LockBasedStorageManager@38d56162 (TopDownAnalyzer for JVM)
```

**To Reproduce**
I've prepared a minimal sample project that can be used to reproduce this issue, it can be found here:
https://github.com/AhmedMourad0/buggy-compiler-plugin

Basically, this simple synthetic resolver and a `@Serializable` annotated class, will cause it:
```
class BuggySyntheticResolveExtension : SyntheticResolveExtension {
    override fun generateSyntheticMethods(
            thisDescriptor: ClassDescriptor,
            name: Name,
            bindingContext: BindingContext,
            fromSupertypes: List<SimpleFunctionDescriptor>,
            result: MutableCollection<SimpleFunctionDescriptor>
    ) {
        thisDescriptor.constructors // This crashes when any class is annotated with @Serializable
    }
}
```

**Expected behavior**
I'd expect getting the constructors of the class, and I do get them when I remove the `@Serializable` annotation.

**Environment**
 - Kotlin version: 1.3.72
 - Library version: 0.20.0
 - Kotlin platforms: JVM
 - Gradle version: 6.3

**Comment by sandwwraith** [comment]
I think the root cause of the problem is that kotlinx.serialization plugin also tries to get descriptors from the class, that triggers full resolve, that tries to ask all the plugins about synthetic declarations -- so in the end, both plugins are recursively calling each other.

Unfortunately, this seems to be a current limitation of compiler plugin API, which is now not documented and not recommended for public use.

**Comment by AhmedMourad0** [comment]
I see,

I opened an [issue](https://youtrack.jetbrains.com/issue/KT-39491) for this on Kotlin's YouTrack.

Hopefully, it's fixed soon as it can cause many plugins, when used together, to fail at the user's end with no meaningful error message.
