### ISSUE TITLE
UnitSerializer naming inconsistency

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/kotlinx.serialization#867]
Currently it's:
```kotlin
Int.serializer()
Boolean.serializer()
..
UnitSerializer()
```
For consistency it would be great if you deprecated `UnitSerializer()` and follow the same schema and provide a `Unit.serializer()` replacement.

**Comment by qwwdfsad** [comment]
Originally reported here: https://github.com/Kotlin/kotlinx.coroutines/issues/2094

**Comment by sandwwraith** [comment]
Unit does not have a companion object :(

**Comment by Dominaezzz** [comment]
Neither do `@Serializable` `object`s.

**Comment by qwwdfsad** [comment]
Well, `Unit` by itself is an object, it should be enough

**Comment by PaulWoitaschek** [comment]
> Unit does not have a companion object :(

Does that matter?
I can write:
```kotlin
fun Unit.serializer() = UnitSerializer()

fun hello() {
  val serializer: KSerializer<Unit> = Unit.serializer()
}
```
