### ISSUE TITLE
Kotlinx Serialization with Android library parcelable object

### ISSUE THREAD

**Issue by kostyaBoss** [Kotlin/kotlinx.serialization#874]
Hi all! Recently I started working with this new serialization library and run into an issue:

I have a list of [UsageStats](https://developer.android.com/reference/android/app/usage/UsageStats) objects I want to serialize/deserialize. The problem is, I was unable to find any example around how can I work with `Parcelable` items. Although this class is in deep Android sources, so I can't actually make some modifications like adding another annotation. How can I use Kotlin Serialization for such type of object? For now, the only workaround I can see is to create own data class and map into it data

Thanks

// BTW I didn't manage to put a proper label, would appreciate help on this too

**Comment by sandwwraith** [comment]
Hi.

As far as I understood your question, you want the `UsageStats` class from android framework to be parcelable? Then I think kotlinx.serialization won't help you with this -- class should implement Parcelable interface anyway. Even if you write KSerializer for class, this library do not currently work with bundles (although there's a format request for that: #148 )
