### ISSUE TITLE
Exclude object from serialization if all inner properties are also excluded

### ISSUE THREAD

**Issue by SumeraMartin** [Kotlin/kotlinx.serialization#879]
I’m trying to implement functionality that excludes the whole object from the serialization if all inner objects are excluded.

For example when I want to serialize this data class to json

```
data class Car(val engine: Engine? = null, val size: Size?  = null)
data class Engine(val type: String?  = null, val horsePower: Int?  = null)
data class Size(val size: Int? = null)

Car(engine = Engine(horsePower = null), size = Size(size = 1000))
```
then I should get the following output (engine is excluded even if it is set)

```
car {
    size {
        size = 1000
    }
}
```
Is there a way on how to achieve this?

**Comment by sandwwraith** [comment]
Seems like a strange idea to me -- why not to set `engine = null` right away? Semantically, `null` and `Engine(null, null, ...)` are different constructions.

Anyway, there's no built-in mechanisms for that. You can write your own [`JsonTransformingSerializer`](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/json_transformations.md#json-transformations) for `Car`, which will recursively traverse JSON and drop all `JsonObject`s which are empty.
