### ISSUE TITLE
NullableSerializer does not expose the underlying serializer (the descriptor doesn't either)

### ISSUE THREAD

**Issue by pdvrieze** [Kotlin/kotlinx.serialization#893]
**What is your use-case and why do you need this feature?**
The nullable serializer changes the name of the serialized type to contain a question mark. This does not work for serializers such as XML that use the type as part of the serialization (see [https://github.com/pdvrieze/xmlutil/issues/31](https://github.com/pdvrieze/xmlutil/issues/31)). To this end it would be good to be able to access the underlying descriptor and/or serializer (without hacks that use interface leakage). An additional use case is the generation of schemas from class files. In that case you need to inspect an entire tree (although the descriptor does expose the children)

**Describe the solution you'd like**
A standard way to determine the name of a type even if it is nullable, without an added question mark being added.

**Comment by sandwwraith** [comment]
The descriptor delegates to the original descriptor in everything except name/isNullable/toString/hashCode: https://github.com/Kotlin/kotlinx.serialization/blob/master/runtime/commonMain/src/kotlinx/serialization/internal/NullableSerializer.kt#L62

So you can still introspect it via `elementsCount`/`getElementName`/`getElementAnnotations`/etc without any hacks.

Regarding question mark in name, I can see your point -- it is much more convenient to build schema recursively with class names, if they do not contain it? I think we can revisit this.
