### ISSUE TITLE
Failed to invoke private kotlinx.serialization.json.JsonElement()

### ISSUE THREAD

**Issue by mochadwi** [Kotlin/kotlinx.serialization#896]
**Describe the bug**
I still have no idea what is it. Maybe missing configurations in our codebase setup?

**To Reproduce**
```
import kotlinx.serialization.JsonObject

// endpoint
@PUT(USERS)
    suspend fun updateUser(
        @HeaderMap headers: Map<String, String>,
        @Body body: DataVerificationBody
    ): JsonObject?
```

```
// request body
data class DataVerificationBody(
        val ktpNumber: String? = "",
        val currentOccupation: String? = "",
        val yearsOfExperience: String? = "",
        val isHaveNpwp: Boolean? = false,
        val npwpNumber: String? = "",
        val whatsappNumber: String? = "",
        val files: List<Any>? = emptyList(),
        val currentCity: String? = "",
        val lastEducation: String? = "",
        val educationMajor: String? = "",
        val verificationVersion: String? = ""
)
```

```
// retrofit builder
    private fun makeRetrofit(httpClient: OkHttpClient, url: String): Retrofit {
        return Retrofit.Builder()
            .client(httpClient)
            .baseUrl(url)
            .addConverterFactory(ScalarsConverterFactory.create())
            .addConverterFactory(provideGsonConverterFactory())
            .addConverterFactory(Json.asConverterFactory("application/json".toMediaType()))
            .build()
    }

```

**Expected behavior**
Should be succeed with my current config?

**Environment**
 - Kotlin version: 1.3.72
 - Library version: 0.20.0
 - Retrofit KotlinX Serial Adapter: 0.5.0
 - Kotlin platforms: [e.g. JVM, JS, Native or their combinations]
 - Gradle version: 6.1.1
 - IDE version (if bug is related to the IDE): 
```
Android Studio 4.0
Build #AI-193.6911.18.40.6514223, built on May 20, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: ide.new.welcome.screen.force=true, debugger.watches.in.variables=false
Non-Bundled Plugins: org.jetbrains.kotlin, com.google.services.firebase, com.intellij.jira, com.intellij.marketplace, com.jeppeman.locallydynamic, com.nvlad.tinypng-optimizer, com.perl5, com.thoughtworks.gauge, commit-template-idea-plugin, drawable.importer.pluginId.7658.hack', io.github.lizhangqu.intellij.plugin.android.bundle, org.intellij.plugins.markdown, org.logtalk, wu.seal.tool.jsontokotlin
```
 - Other relevant context: macOS Catalina, Java 8

**Comment by mochadwi** [comment]
Looks like this is related to https://github.com/Kotlin/kotlinx.serialization/issues/660

**Comment by mochadwi** [comment]
After a while working alternavie approach, looks like `kotlinx.serialization.JsonObject` is not supported on Retrofit. This might be due Retrofit Adapter here https://github.com/JakeWharton/retrofit2-kotlinx-serialization-converter

Modify:

```
// endpoint
@PUT(USERS)
    suspend fun updateUser(
        @HeaderMap headers: Map<String, String>,
        @Body body: DataVerificationBody
    ): JsonObject?
```

Into:
```
// endpoint
@PUT(USERS)
    suspend fun updateUser(
        @HeaderMap headers: Map<String, String>,
        @Body body: DataVerificationBody
    ): Any?
```

Works for now.

But, the questions still remains for `List<Any>` property, should we annotate `Any` with `@ContextSerialization`? because it has a compile error:

<img width="832" alt="Screen Shot 2020-07-10 at 1 37 14 AM" src="https://user-images.githubusercontent.com/7057959/87077913-0aa45180-c24e-11ea-992d-921b678d795f.png">

I still cannot find a ways to solve the #660, but if there's any documentation you can reference, it would be great!

**Comment by sandwwraith** [comment]
Hi,

JsonElement is a sealed class so yes, it has private constructor which can not be invoked via reflection. However, since your return type is a JsonObject, not a JsonElement, it should work. Also it should work natively with kotlinx.serialization, since it does not use reflection. I've noticed you have `.addConverterFactory(provideGsonConverterFactory())` in retrofit setup -- do you use Gson simultaneously with kotlinx.serialization? Then it may be its problem. A full stacktrace of exception may help in diagnostics.

Regarding your second question: it's better to use `val files: List<JsonElement>? = emptyList()`. It's more typesafe and also idiomatic in kotlinx.serialization terms (not sure how gson will handle them though)

**Comment by mochadwi** [comment]
Thanks for the explanations!

I see, so there's no need to use `@ContextualSerialization` for `Any` but favor `JsonElement` for property instead.

Yes, we're still using `Gson` partially before migrating our apps to fully using the `kotlinx.serialization`. 

We still curious about dynamic key parser on kotlinx.serialization as stated in this issue as well #856 thus we're still using GSON for that
