### ISSUE TITLE
This declaration is experimental and its usage must be marked with '@kotlinx.serialization.ImplicitReflectionSerializer' or '@OptIn(kotlinx.serialization.ImplicitReflectionSerializer::class)'

### ISSUE THREAD

**Issue by mochadwi** [Kotlin/kotlinx.serialization#897]
**Describe the bug**
Adding the `freeCompilerArgs` works removing the syntax highlighting error
```
buildscript {
    repositories { jcenter() }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-serialization:1.3.72"
    }
}

apply plugin: 'java-library'
apply plugin: 'kotlin'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlinx-serialization'

compileKotlin {
    kotlinOptions {
        jvmTarget = "1.8"
        freeCompilerArgs += [
                "-Xopt-in=kotlin.RequiresOptIn",
                "-Xopt-in=kotlinx.serialization.ImplicitReflectionSerializer",
        ]
    }
}
```
// Before the above code
TODO: will add image later

// After the above code
<img width="936" alt="Screen Shot 2020-07-10 at 2 55 06 AM" src="https://user-images.githubusercontent.com/7057959/87084742-ebf78800-c258-11ea-8606-3c11a2e155f1.png">

**To Reproduce**
Using the `serializer` even with `freeCompilerArgs` still doesn't works either, I've done the following:

1. https://kotlinlang.org/docs/reference/opt-in-requirements.html#experimental-status-of-the-opt-in-requirements
1. https://kotlinlang.org/docs/reference/opt-in-requirements.html#module-wide-opt-in

**Expected behavior**

1. No compiler error anymore
1. No needs to mark the every class with `@ImplicitReflectionSerializer`, because already using module-wide opt-in approach using `freeCompilerArgs`

**Environment**
 - Kotlin version: 1.3.7
 - Library version: 0.20.0
 - Kotlin platforms: [e.g. JVM, JS, Native or their combinations]
 - Gradle version: 6.1.1
 - IDE version (if bug is related to the IDE)
```
Android Studio 4.0
Build #AI-193.6911.18.40.6514223, built on May 20, 2020
Runtime version: 1.8.0_242-release-1644-b3-6222593 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.5
GC: ParNew, ConcurrentMarkSweep
Memory: 4029M
Cores: 8
Registry: ide.new.welcome.screen.force=true, debugger.watches.in.variables=false
Non-Bundled Plugins: org.jetbrains.kotlin, com.google.services.firebase, com.intellij.jira, com.intellij.marketplace, com.jeppeman.locallydynamic, com.nvlad.tinypng-optimizer, com.perl5, com.thoughtworks.gauge, commit-template-idea-plugin, drawable.importer.pluginId.7658.hack', io.github.lizhangqu.intellij.plugin.android.bundle, org.intellij.plugins.markdown, org.logtalk, wu.seal.tool.jsontokotlin
```
 - Other relevant context [e.g. OS version, JRE version, ... ]

**Comment by qwwdfsad** [comment]
We do not longer have `ImplicitReflectionSerializer` annotation, so closing this one.
It may be worth to report this to youtrack if you think this is a compiler/gradle-related issue
