### ISSUE TITLE
Readme gradle example not working

### ISSUE THREAD

**Issue by ersin-ertan** [Kotlin/kotlinx.serialization#9]
In the build.gradle:
Cannot resolve symbol 'serialization_version'
but if you switch to `serializationVersion` it resolves.

---
With the basic example, the annotation is red, for both of the above formats.
```kotlin
@Serializable 
// this class does not have a constructor
// Cannot access 'Serializable': it is internal in 'kotlin.io'

**Comment by sandwwraith** [comment]
Please import annotation explicitly: `import kotlinx.serialization.Serializable`

**Comment by sandwwraith** [comment]
Which example did you use? From root readme? Or from `example-jvm` folder?

**Comment by ersin-ertan** [comment]
It was an import problem, working now.
Root readme.
