### ISSUE TITLE
Default value for unknown Enum value

### ISSUE THREAD

**Issue by cosminstefanxp** [Kotlin/kotlinx.serialization#90]
In order to be forward-compatible and support certain scenarios, it would be useful to have a way to specify a default value for a deserialized `Enum` field, if an unknown value is encountered. That way, if a new type is defined and being returned by remote APIs, apps already in production will work properly in the intermediate period before migration. 

Example:
```kotlin
enum class Status { ACTIVE, INACTIVE, UNKNOWN }
class Test(val status: Status = Status.UNKNOWN)
```
would return a `Test(UNKNOWN)` when provided with the following json: `{'status': 'PENDING'}`

**Comment by simonovvasiliy** [comment]
Good use case, Jackson can do it and we rely its feature

**Comment by avently** [comment]
@sandwwraith 
A year is gone. Any news related to enums?

**Comment by sandwwraith** [comment]
@avently Not yet

**Comment by Larsmyrup** [comment]
This would be really useful. Does anyone know if this will be implemented?

**Comment by santoshastagi** [comment]
This is important for us too. Any other ways to do this?

**Comment by ManuelDCR** [comment]
This would be a really appreciated feature!
Any news @sandwwraith ?

**Comment by arberg** [comment]
This is just to help others who need to solve this issue here and now: Bolinfest showed us how to do create a custom serializer [here on issue #31 ](https://github.com/Kotlin/kotlinx.serialization/issues/31#issuecomment-488572539)

**Comment by igrmk** [comment]
For those who need a solution here is a complete answer. For simplicity reasons I used `toString` instead of `@SerialName` however.
https://github.com/igrmk/smsq/blob/25e9dd454fb131d93503e8471f71b9e9c1d280c4/android/app/src/main/java/com/github/igrmk/smsq/entities/DeliveryResult.kt

**Comment by azabost** [comment]
If you are interested in even better forward compatibility of enums, I would recommend using a wrapper like this: https://github.com/bright/codified. I have been using it for a quite long time and it works beautifully. Feel free to let me know what you think about it :blush:

**Comment by tagy** [comment]
Enabling `coerceInputValues` and setting default enum values in you class was easiest way to solve this at the moment I think.

**Comment by arberg** [comment]
> For those who need a solution here is a complete answer. https://github.com/igrmk/smsq/blob/532e3468266c8fc319c8ecca11be76f7026949a7/android/app/src/main/java/com/github/igrmk/smsq/entities/DeliveryResult.kt

I updated this example, and made it generic: https://gist.github.com/arberg/e20db05e018c61f37f1d274a254657c3

**Comment by joffrey-bion** [comment]
@qwwdfsad I'm hitting this problem myself as well. It seems that the newly introduced `coerceInputValues` doesn't quite work for me.

I would need to be able to mark one of the values of the enum (e.g. `UNKNOWN`) as being the placeholder for deserialization at the _enum declaration_ site. There might not be default values everywhere, and I still need to represent these unknown values somehow.

See: https://github.com/joffrey-bion/chrome-devtools-kotlin/issues/466

Since I'm using code generation from the Chrome DevTools Protocol definitions, I can afford to generate a custom deserializers, so I have a workaround, but I still believe this feature would be worth it in general. For example, I'd like to be able to do this:

```kotlin
enum MyEnum {
    Value1,
    Value2,
    Value3,
    @UnknownEnumValueFallback
    Unknown,
}
```

**Comment by dhoepelman** [comment]
It's a shame this in not built-in, this is a very common thing to have in serialization framework to deal with forwards/backwards compatibility of enums.

Jackson has it as [@JsonEnumDefaultValue](https://javadoc.io/doc/com.fasterxml.jackson.core/jackson-annotations/2.19.2/com/fasterxml/jackson/annotation/JsonEnumDefaultValue.html)
