### ISSUE TITLE
java.lang.ClassNotFoundException: kotlinx.serialization.ElementValueEncoder

### ISSUE THREAD

**Issue by Krulvis** [Kotlin/kotlinx.serialization#901]
**Describe the bug**
I am building a plugin for minecraft spigot and wanted to store / load settings using Kotlin's serializable and charleskorn's Yaml. However, when calling `com.charleskorn.kaml.Yaml.stringify` with a serializable data class' serializer().list from `import kotlinx.serialization.builtins.list` I am getting the following error:
`Caused by: java.lang.ClassNotFoundException: kotlinx.serialization.ElementValueEncoder`
https://pastebin.com/C9hZB7yB

**Code that is causing the issue**
```
Yaml.default.stringify(Gauntlet.serializer().list, gauntlets)
```
Where Gauntlet is a @Serializable

**This is my Gradle build file**

```
plugins {
	id 'java'
	id 'org.jetbrains.kotlin.jvm' version "$kotlin_version"
	id "org.jetbrains.kotlin.plugin.serialization" version "$kotlin_version"
	id 'com.github.johnrengelman.shadow' version '2.0.4'
}

group 'com.krulvis.gauntlet'
version '1.0'

repositories {
	mavenLocal()
	mavenCentral()
	maven {
		name = "spigot"
		url = uri("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
	}
}

dependencies {
	implementation "com.charleskorn.kaml:kaml:0.15.0"
	implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk8"
	api "org.jetbrains.kotlinx:kotlinx-serialization-runtime-native:0.20.0"
	compile "org.jetbrains.kotlinx:kotlinx-serialization-runtime-native:0.20.0"
	compileOnly("org.spigotmc:spigot-api:${minecraft_version}-R0.1-SNAPSHOT")
}

compileKotlin {
	kotlinOptions.jvmTarget = "1.8"
}
compileTestKotlin {
	kotlinOptions.jvmTarget = "1.8"
}
```

I read somewhere on another issue that some class couldn't be found and the dependency should be loaded as api rather than compile in dependencies in the gradle build file. I tried both, which didn't resolve the issue.

**Expected behavior**
Stringify list of serializable data classes
**Environment**
 - Kotlin version: 1.3.72
 - Library version: 0.20.0
 - Kotlin platforms: JVM
 - Gradle version: 6

**Comment by x-rat4-x** [comment]
ElementValueEncoder was renamed in version 0.20.0

**Comment by qwwdfsad** [comment]
`ElementValueEncoder` and `ElementValueDecoder` were renamed to `AbstractEncoder` and `AbstractDecoder` respectively.
We have migrations with replacement in 0.20.0 for these classes, but it seems that in your case they came from transitive dependency which is incompatible with 0.20.0

**Comment by Krulvis** [comment]
> 
> 
> `ElementValueEncoder` and `ElementValueDecoder` were renamed to `AbstractEncoder` and `AbstractDecoder` respectively.
> We have migrations with replacement in 0.20.0 for these classes, but it seems that in your case they came from transitive dependency which is incompatible with 0.20.0

Why does it search for an old non-existed class? Are you implying that somewhere else in the application another version of kotlinx.serialization is being used? I am unsure as to what transitive dependency means in this context.

**Comment by qwwdfsad** [comment]
>Why does it search for an old non-existed class? 

Because your dependency (`implementation "com.charleskorn.kaml:kaml:0.15.0"` or maybe `spigot-api`) is compiled against older version of `kotlinx.serialization` where this class actually exists.

You have your application that depends on `0.20.0` version and `kaml` that depends on `0.15.0` version.
These versions are incompatible, so either `kaml` should be updated, or your own dependency on `serialization` downgraded back to `0.15.0`

**Comment by Krulvis** [comment]
Thanks for clearing that up! Really appreciate the effort you guys put into this!
