### ISSUE TITLE
Default serializer for sealed types if input has no explicit type

### ISSUE THREAD

**Issue by charleskorn** [Kotlin/kotlinx.serialization#902]
**What is your use-case and why do you need this feature?**

Let's say I have some JSON that looks like this:

```json
{ "type": "typeA", "option": "abc123" }
```

or 

```json
{ "type": "typeB", "otherOption": 15 }
```

I can use a sealed type to represent these types in Kotlin, and deserialize the JSON into objects without any issues.

However, what I would like to be able to do is default to a particular type if there is no `type` in the JSON input. For example, if `{ "option": "abc123" }` was the input, I'd like to default to treating that as if it was a `typeA`.

**Describe the solution you'd like**
Perhaps this could be done with an annotation on the base class?

For example:

```kotlin
@PolymorphicDefault(TypeA::class)
sealed class Options

data class TypeA(val option: String) : Options
data class TypeB(val otherOption: Int) : Options
```

**Comment by sandwwraith** [comment]
We'll have a `default` function that allows you to register function-handler of unknown polymorphic types in the next release: https://github.com/Kotlin/kotlinx.serialization/blob/dev/runtime/commonMain/src/kotlinx/serialization/modules/PolymorphicModuleBuilder.kt#L42 . It should work with sealed classes as well.

However, it is not designed to work when class discriminator (`type` field in JSON) is absent completely. Perhaps we can extend it to that, cc @qwwdfsad

**Comment by Progdrasil** [comment]
I'm not exactly clear on how this is supposed to work, I dont see it in the [Polymorphism guide](https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md)

**Comment by sandwwraith** [comment]
See https://github.com/Kotlin/kotlinx.serialization/blob/master/docs/polymorphism.md#default-polymorphic-type-handler-for-deserialization : in `default { }` lambda, `className` parameter is now `String?`. `null` means type property in JSON was absent.

**Comment by charleskorn** [comment]
Is it possible to use this for a sealed type without creating a serializers module? 

For an open type, creating a serializers module is already required, but it seems that in order to use this with a sealed type, you need to create a module (when you would otherwise not need to).

**Comment by charleskorn** [comment]
It also does not seem possible to use this without special support from the format (eg. [this code](https://github.com/Kotlin/kotlinx.serialization/blob/v1.1.0/formats/json/commonMain/src/kotlinx/serialization/json/internal/Polymorphic.kt#L66) in the JSON format) because [`AbstractPolymorphicSerializer.deserialize()`](https://github.com/Kotlin/kotlinx.serialization/blob/v1.1.0/core/commonMain/src/kotlinx/serialization/internal/AbstractPolymorphicSerializer.kt#L52) assumes the class name is always non-null and calls `decodeString()`. I would expect it to call `decodeNotNullMark()` first to check if a class name has been provided.

(I'm trying to add support for this feature to [kaml](https://github.com/charleskorn/kaml).)

**Comment by sandwwraith** [comment]
> Is it possible to use this for a sealed type without creating a serializers module?

No, module is required. We expect sealed classes to always contain type info, since they're known statically.

> It also does not seem possible to use this without special support from the format

Yes, because default polymorphism for arbitrary format is array-based

**Comment by FilippoVigani** [comment]
> No, module is required. We expect sealed classes to always contain type info, since they're known statically.
Sorry for pinging this old issue @sandwwraith , I was wondering if with a sealed class I will need to redefine all the subclasses in a module to support the default value, or just the `default { }` declaration is sufficient

**Comment by sandwwraith** [comment]
AFAIR, `default` is sufficient
