### ISSUE TITLE
Plugin with id 'kotlinx-serialization' not found. 

### ISSUE THREAD

**Issue by wessimtrimeche** [Kotlin/kotlinx.serialization#91]
Applying the 'kotlinx-serialization' plugin in the application gradle file will result in an error stating that this plugin is unfound.
Are there some additional plugins I need to add in my gradle file in order for the serialization plugin to be found ?

**Comment by sandwwraith** [comment]
Have you added `maven { url "https://kotlin.bintray.com/kotlinx" }` in buildscript repositories?

**Comment by wessimtrimeche** [comment]
yes I did

**Comment by sandwwraith** [comment]
Rather strange. Take a look at example project configuration, it should 100% work: https://github.com/Kotlin/kotlinx.serialization/blob/master/example-jvm/build.gradle. 

Probably you use new gradle `plugin` block instead of `apply plugin ...`, which doesn't work for now, because plugin is not uploaded to Gradle Plugin Portal

**Comment by wessimtrimeche** [comment]
maybe the latest kotlin plugin named 'kotlin-android' includes the serialization one, thank you anyway

**Comment by sandwwraith** [comment]
No, I don't think so. Serialization plugin was not bundled anywhere

**Comment by LouizFC** [comment]
@wessimtrimeche are you using Kotlin DSL? I had the same problem.

I fixed it by adding the following to the `settings.gradle.kts`:
```kotlin
pluginManagement({
    repositories {
        gradlePluginPortal()
        maven("https://kotlin.bintray.com/kotlinx")
    }
    resolutionStrategy {
        eachPlugin {
            when (requested.id.id) {
                "kotlinx-serialization"->{
                    useModule("org.jetbrains.kotlinx:kotlinx-gradle-serialization-plugin:${requested.version}")
                }
            }
        }
    }
})
```
and the following in the `build.gradle.kts`
```kotlin
plugins {
    id("kotlinx-serialization") version "0.4.1" apply true
}
```
I am not familiar with "groovy" gradle, but since they are similar maybe this can help you.

**Comment by earldean** [comment]
I am having this issue using build.gradle.kts.  I tried @LouizFC solution, but it did not work for me.  

[build.gradle.kts.txt](https://github.com/Kotlin/kotlinx.serialization/files/2077984/build.gradle.kts.txt)

**Comment by pdvrieze** [comment]
As a note, the same code (except for when - use an if) works for groovy based build scripts.

**Comment by Ricindigus** [comment]
dependencies {
        classpath "org.jetbrains.kotlin:kotlin-serialization:$kotlin_version"
}

**Comment by anonym24** [comment]
> in your build.graddle (Project)
> 
> in dependencies, add this line dependencies { classpath "org.jetbrains.kotlin:kotlin-serialization:$kotlin_version" }

but this is legacy and not Kotlin DSL (KTS)

**Comment by TreyWurm** [comment]
> I was trying to set up the plugin on a KMM codebase, also using a version catalog. It worked like this for me:
> 
> At the root build.gradle.kts
> 
> ```
> plugins { 
>     // other plugins
>     alias(libs.plugins.kotlinxSerialization).apply(false)
> }
> ```
> 
> At the `libs.versions.toml` file:
> 
> ```
> kotlin = "1.9.20"
> 
> [plugins]
> kotlinxSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
> ```

Was also trying to set up a KMP
In my case I was missing the `plugin` in the id

**Comment by DidarSeyidov** [comment]
solutions mentioned above still did not work in kotlin 2.0.0. Is there any solution for kotlin 2.0.0 in kmp project

**Comment by ElisabethHuhn** [comment]
I'm still having the same problem with KMM kotlin 2.1.10
