### ISSUE TITLE
JsonElement.jsonObjectOrNull and JsonElement.jsonArrayOrNull extensions 

### ISSUE THREAD

**Issue by KarenkovID** [Kotlin/kotlinx.serialization#917]
I need to convert JsonElement to JsonObject/JsonArray but I cannot use JsonElement.jsonObject/JsonElement.jsonArray extensions because they throw exception. I can use as? JsonObject/JsonArray, for example
```kotlin
((map[ElementTable.RootColumns.ELEMENTS.value] as? JsonObject)?.get(ElementListTable.Columns.ITEMS) as? JsonArray).size
```
but as you can see I have to wrap expressions with brackets and it is less readable and convenient than using it without wrapping and using as? operator. We can create long sequences of expressions using JsonElement and do it in more readable and convenient way. For achieving this we can add extensions values JsonElement.jsonObjectOrNull and JsonElement.jsonArrayOrNull. JsonElement have extensions JsonElement.jsonObject and JsonElement.jsonArray and it is good idea to add similar one which have same behavior but don't throw exception.
```kotlin
/**
 * Convenience method to get current element as [JsonObject] or `null` if current element is not a [JsonObject]
 */
public val JsonElement.jsonObjectOrNull: JsonObject?
    get() = this as? JsonObject

/**
 * Convenience method to get current element as [JsonArray] or `null` if current element is not a [JsonArray]
 */
public val JsonElement.jsonArrayOrNull: JsonArray?
    get() = this as? JsonArray
```
and then we can write same expression using new extensions
```kotlin
map[ElementTable.RootColumns.ELEMENTS.value]?.jsonObjectOrNull?.get(ElementListTable.Columns.ITEMS)?.jsonArrayOrNull?.size
```

In addition to readability multiline expressions can be ugly
```kotlin
((map[ElementTable.RootColumns.ELEMENTS.value] as? JsonObject)
        ?.get(ElementListTable.Columns.ITEMS) as? JsonArray
        )?.size
```
but we don't have problems when we use new extensions
```kotlin
map[ElementTable.RootColumns.ELEMENTS.value]
        ?.jsonObjectOrNull
        ?.get(ElementListTable.Columns.ITEMS)
        ?.jsonArrayOrNull
        ?.size
```

**Comment by sandwwraith** [comment]
Thanks for the suggestion,
as you correctly noticed, these extensions are easy to add and can be declared in the library client's code.
For now, we are focused on shaping the core API that should consist of bare-minimum functions that get stable in 1.0 release.
For the following releases, we may open this topic again.
