### ISSUE TITLE
IntelliJ IDEA plugin not working with Kotlin plugin 1.2.30

### ISSUE THREAD

**Issue by rjaros** [Kotlin/kotlinx.serialization#92]
After installing IntelliJ IDEA plugin for serialization, Kotlin plugin 1.2.30 in IntelliJ stops working. See: https://youtrack.jetbrains.com/issue/KT-23043

**Comment by sandwwraith** [comment]
Plugin version `0.4.2` fixes compatibility with Kotlin `1.2.30` and `1.2.40-dev-XXX` versions

**Comment by ChrisAJS** [comment]
For those playing at home- the plugin can be downloaded here: https://teamcity.jetbrains.com/viewLog.html?buildId=lastPinned&buildTypeId=KotlinTools_KotlinxSerialization_KotlinCompilerWithSerializationPlugin&tab=artifacts&guest=1
