### ISSUE TITLE
Serialization function naming inconsistency

### ISSUE THREAD

**Issue by jcornaz** [Kotlin/kotlinx.serialization#94]
Hello, 

In my opinion, function names to serialize and deserialize are not consistent across the different methods.

For JSON they are named: `stringify` and `parse`
For CBOR and ProtoBuf they are named: `dump` and `load`

I would propose to give them always the same name, for example `serialize` and `deserialize`.

They could even ben unified by an interface like this (for example):

```kotlin
interface SerializationMethod<R> {
	fun <T> serialize(saver: KSerialSaver<T>, obj: T): R
	fun <T> deserialize(raw: R): T
}
```

**Comment by JakeWharton** [comment]
Dupe of #66?

**Comment by jcornaz** [comment]
@JakeWharton, yes apparently. Sorry for the duplicate.
