### ISSUE TITLE
Override the plugin-generated serializer and use it too

### ISSUE THREAD

**Issue by elizarov** [Kotlin/kotlinx.serialization#941]
When using `JsonTransformingSerializer` on a specific class you need to base it on the plugin-generated serializer for the class:

```kotlin
@Serializable 
class Data(....)

object DataSerializer : JsonTransformingSerializer<Data>(Data.serializer()) { ... }
```

However, you cannot now bind this `DataSerializer` using `@Serializable(with = DataSerializer::class)`, since it turns off the process of generation of a serializer by the plugin. Very inconvenient.

There is seemingly a workaround using (experimental) `@Serializer(forClass = Data::class)`. 

```kotlin
@Serializable(with = DataSerializer::class) 
class Data(....)

@Serializer(forClass = Data::class)
private object DefaultDataSerializer

object DataSerializer : JsonTransformingSerializer<Data>(DefaultDataSerializer) { ... }
```

However, the above "workaround" does a different thing, since `@Serializer` annotation generates an (experimental) _external_ serializer for the specified class based on properties instead of backing fields, which might be important in practice and adds a disconcerning inconsistency.

### Proposal

1. Deprecate the use of (experimental) `@Serializer` annotation in a different source file from the original class and change its behavior to generate the default field-based serializer when used in the same file.

2. Design a separate annotation for the external serialization that is more explicitly named and can be used anywhere (something like `@ExternalSerializer` or `PropertiesSerializer`).

**Comment by Dominaezzz** [comment]
Somewhat related. https://github.com/Kotlin/kotlinx.serialization/issues/793

**Comment by Dominaezzz** [comment]
Duplicate https://github.com/Kotlin/kotlinx.serialization/issues/1169 and https://github.com/Kotlin/kotlinx.serialization/issues/661

**Comment by shanshin** [comment]
Closed as a buplicate of https://github.com/Kotlin/kotlinx.serialization/issues/1169
