### ISSUE TITLE
ProtoBuf documentation: some method invocation commments do not match the actual implementation

### ISSUE THREAD

**Issue by OliverO2** [Kotlin/kotlinx.serialization#949]
**Describe the bug**
These method invocation comments seemingly do not match the actual implementation:
* https://github.com/Kotlin/kotlinx.serialization/commit/d8c9fc704d4ca155eadd430f48bc8282168f47fb#r41004722
* https://github.com/Kotlin/kotlinx.serialization/commit/d8c9fc704d4ca155eadd430f48bc8282168f47fb#r41005368
* https://github.com/Kotlin/kotlinx.serialization/commit/d8c9fc704d4ca155eadd430f48bc8282168f47fb#r41005538

**Environment**
 - Library version: kotlinx.serialization dev branch as of commit cc52ca5d

**Comment by qwwdfsad** [comment]
Thanks, will fix
