### ISSUE TITLE
1.0-M1-1.4.0-rc runtime publication missing all artifacts in Bintray

### ISSUE THREAD

**Issue by lamba92** [Kotlin/kotlinx.serialization#951]
As you can see here [https://kotlin.bintray.com/kotlinx/org/jetbrains/kotlinx/kotlinx-serialization-runtime/1.0-M1-1.4.0-rc/](https://kotlin.bintray.com/kotlinx/org/jetbrains/kotlinx/kotlinx-serialization-runtime/1.0-M1-1.4.0-rc/) there is no artifact in the publication!

**Comment by sandwwraith** [comment]
Sorry, it's a temporary problem caused by re-uploading artifacts to add missing javadocs. You can try 1.0-M1-1.4.0-rc-218 instead, it should be compatible. 1.0-M1-1.4.0-rc will be back in a couple of hours

**Comment by sandwwraith** [comment]
They're back now.
