### ISSUE TITLE
Add support for proto3?

### ISSUE THREAD

**Issue by 9468305** [Kotlin/kotlinx.serialization#96]
Hi guys,

Do you have plan to support proto3?

Thanks.

**Comment by sandwwraith** [comment]
Hello,
Proto3 parser is not very hard to implement and even its format is compatible with proto2, however, there is a big semantic change: in proto3, there are no `required` or `optional` fields, every field that is not repeated, can be specified zero or one times. It does not very well map to the Kotlin classes: basically, it means that you have to declare every field as optional and provide some default (which in many cases `null`, so your fields' types will be nullable, and imho that's not very convenient).

If you markup your classes in such way, current parser will likely work with Proto3 – except for `packed` encoding of repeated fields, which is not supported at all by now.

**Comment by jolestar** [comment]
expect proto3 support too.

**Comment by webfrea-k** [comment]
Any suggestion on how to handle empty lists with proto3?

Example:
`@Serializable
 data class Test (
        @Optional @SerialId(1) var events: List<Event> = emptyList(),
        @Optional @SerialId(2) var games: List<Game> = emptyList(),
)`

If for example `events` is "empty array" in proto3 response, Android deserializes just games correctly, while iOS throws `Unexpected EOF`. If I comment out `empty events` from the class above, iOS deserialization of just `games` succeeds as well.

**Comment by sandwwraith** [comment]
If you observe different behavior on different platforms with the same library and code, this is probably a bug and you can open separate issue

**Comment by kdarrimajou** [comment]
Hi, 

Do you have a plan to support `packed` encoding of repeated fields ?

Thanks.
