### ISSUE TITLE
NPE in IrFileSerializer

### ISSUE THREAD

**Issue by NikkyAI** [Kotlin/kotlinx.serialization#962]
**Describe the bug**

task `compileKotlinMingwX64` crashes with a NPE and without useful error information

this happened on a projecti  was more or less blindly trying to port to kotlin-multiplatform

https://gist.github.com/NikkyAI/9caf3f66ae51b79db868b7d87c7addf7

**To Reproduce**
Attach a code snippet or test data if possible.

https://github.com/NikkyAI/json-schema-serialization/tree/f7d22f1aa07bdcb0bae28140624c6ac5bd900bdb

gradle tasks: `build` or `compileKotlinMingwX64`, etc should trigger the exception

**Expected behavior**

successful compile or a pointer to the problematic code

**Environment**
 - Kotlin version: 1.3.72
 - Library version: 0.20.0
 - Kotlin platforms: mingw64, linux64
 - Gradle version: 6.3

**Comment by shanshin** [comment]
Closed as outdated
