### ISSUE TITLE
Data.serializer() is error

### ISSUE THREAD

**Issue by jackwener** [Kotlin/kotlinx.serialization#964]
**Describe the bug**
``` kotlin
// Json also has .Default configuration which provides more reasonable settings,
    // but is subject to change in future versions
    val json = Json(JsonConfiguration.Stable)
    // serializing objects
    val jsonData = json.stringify(Data.serializer(), Data(42))
    // serializing lists
    val jsonList = json.stringify(Data.serializer().list, listOf(Data(42)))
    println(jsonData) // {"a": 42, "b": "42"}
    println(jsonList) // [{"a": 42, "b": "42"}]

    // parsing data back
    val obj = json.parse(Data.serializer(), """{"a":42}""") // b is optional since it has default value
    println(obj) // Data(a=42, b="42")
```
 but `Data.serializer()` is error

**Comment by qwwdfsad** [comment]
Could you please elaborate on what exactly is wrong? 
The snippet your provided works properly with the following `Data` class:
```
@Serializable
data class Data(val a: Int, val b: Int = 42)
```

**Comment by jackwener** [comment]
> Could you please elaborate on what exactly is wrong?
> The snippet your provided works properly with the following `Data` class:
> 
> ```
> @Serializable
> data class Data(val a: Int, val b: Int = 42)
> ```

It seems that **setup** plugin is error.
sync gradle failed after follow doc to add plugins and  implementation

**Comment by jackwener** [comment]
error is 
`Cannot add task 'clean' as a task with that name already exists.`

**Comment by jackwener** [comment]
when i add it to Project build.gradle.
```
plugins {
    id 'org.jetbrains.kotlin.multiplatform' version '1.3.70' // or any other kotlin plugin
    id 'org.jetbrains.kotlin.plugin.serialization' version '1.3.70'
}
```

sync failed 

`Cannot add task 'clean' as a task with that name already exists.`

**Comment by qwwdfsad** [comment]
@sandwwraith could you please take a look?

**Comment by jackwener** [comment]
when I delete task clean, sync success.

But @Serializable will warning 
`kotlinx.serialization compiler plugin is not applied to the module, so this annotation would not be processed. Make sure that you've setup your buildscript correctly and re-import project.`

what's more,
class Data doesn't own serializer() method

**Comment by sandwwraith** [comment]
It seems that plugin wasn't applied for some reason. Have you tried to re-sync project with IDE after you fixed the build? Does `./gradlew build` works in the terminal? If not, can you please post full `build.gradle` file?

**Comment by zirman** [comment]
I'm having the same problem when editing my project in Windows 10. Opening the project in Linux doesn't have issues applying the serialization plugin.
Here is my build.gradle.kts file
`import org.jetbrains.kotlin.gradle.targets.js.webpack.KotlinWebpack

val kotlinVersion = "1.4.21"
val serializationVersion = "1.0.0-RC"
val ktorVersion = "1.4.0"
//val nettyVersion = "2.0.35.Final"

plugins {
    kotlin("multiplatform") version "1.4.0"
    kotlin("plugin.serialization") version "1.4.0"
    application // for jvm back end
}

group = "dev.robch"
version = "1.0-SNAPSHOT"

repositories {
    jcenter()
    mavenCentral()
    maven("https://plugins.gradle.org/m2/")
    maven("https://dl.bintray.com/kotlin-js-wrappers/")
    maven("https://dl.bintray.com/kotlin/kotlin-eap")
    maven("https://dl.bintray.com/kotlin/kotlinx")
    maven("https://dl.bintray.com/kotlin/ktor")
}

kotlin {
    jvm {
        withJava()
    }

    js(IR) {
        browser {
            binaries.executable()
        }
    }

    sourceSets {
        val commonMain by getting {
            dependencies {
                implementation(kotlin("stdlib-common"))
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-core:$serializationVersion")
                implementation("org.jetbrains.kotlinx:kotlinx-serialization-protobuf:$serializationVersion")
                implementation("io.ktor:ktor-client-core:$ktorVersion")
            }
        }

        val commonTest by getting {
            dependencies {
                implementation(kotlin("test-common"))
                implementation(kotlin("test-annotations-common"))
            }
        }

        val jvmMain by getting {
            dependencies {
                implementation("io.ktor:ktor-serialization:$ktorVersion")
                implementation("io.ktor:ktor-server-core:$ktorVersion")
                implementation("io.ktor:ktor-server-netty:$ktorVersion")
                implementation("io.ktor:ktor-html-builder:$ktorVersion")
//                implementation("io.netty:netty-tcnative:$nettyVersion")
//                implementation("io.netty:netty-tcnative-boringssl-static:$nettyVersion")
                implementation("ch.qos.logback:logback-classic:1.2.3")
                implementation("io.ktor:ktor-websockets:$ktorVersion")
                implementation("org.litote.kmongo:kmongo-coroutine-serialization:4.1.1")
            }
        }

        val jsMain by getting {
            dependencies {
                implementation("io.ktor:ktor-client-js:$ktorVersion") //include http&websockets
                implementation("io.ktor:ktor-client-json-js:$ktorVersion")
                implementation("io.ktor:ktor-client-serialization-js:$ktorVersion")
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.4.2")
                implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core-js:1.4.2")
//                implementation("org.jetbrains:kotlin-react:16.13.1-pre.110-kotlin-1.4.0")
//                implementation("org.jetbrains:kotlin-react-dom:16.13.1-pre.110-kotlin-1.4.0")
//                implementation(npm("react", "16.13.1"))
//                implementation(npm("react-dom", "16.13.1"))
            }
        }
        all {
            languageSettings.enableLanguageFeature("InlineClasses")
        }
    }
}

application {
    mainClassName = "ServerKt"
}

// include JS artifacts in any JAR we generate
tasks.getByName<Jar>("jvmJar") {
    val taskName =
        if (project.hasProperty("isProduction")) {
            "jsBrowserProductionWebpack"
        } else {
            "jsBrowserDevelopmentWebpack"
        }

    val webpackTask = tasks.getByName<KotlinWebpack>(taskName)
        .apply { outputFileName = "bolo.js" }

    dependsOn(webpackTask) // make sure JS gets compiled first
    from(File(webpackTask.destinationDirectory, webpackTask.outputFileName)) // bring output file along into the JAR
}

tasks {
    withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
        kotlinOptions {
            jvmTarget = "1.8"
        }
    }
}

distributions {
    main {
        contents {
            from("$buildDir/libs") {
                rename("${rootProject.name}-jvm", rootProject.name)
                into("lib")
            }
        }
    }
}

// Alias "installDist" as "stage" (for cloud providers)
tasks.create("stage") {
    dependsOn(tasks.getByName("installDist"))
}

tasks.getByName<JavaExec>("run") {
    classpath(tasks.getByName<Jar>("jvmJar")) // so that the JS artifacts generated by `jvmJar` can be found and served
}
`

**Comment by zirman** [comment]
Loaded the project on a different Windows box and it worked. I tried reinstalling Intellij and still had the issue. Reinstalled Windows 10 and it fixed the issue. (╯°□°)╯︵ ┻━┻
