### ISSUE TITLE
SerializationException meta-data

### ISSUE THREAD

**Issue by Agcom** [Kotlin/kotlinx.serialization#975]
**What is your use-case and why do you need this feature?**

Hi.

I'm building a HTTP API, using Kotlinx serialization to serialize / deserialize Json objects incoming from the client request body.

So, the `SerializationException` will probably happen and I want to inform the client about the issue. Currently, I simply send the message associated with the exception back to the client.

For example, in case of an invalid Json, a `JsonDecodingException` is thrown and the message will be something like this,

> `Runtime 0.20.0` message

```
Unexpected JSON token at offset 208: Encountered an unknown key 'unknownField'. You can enable 'JsonConfiguration.ignoreUnknownKeys' property to ignore unknown keys.
JSON input: ...
```

Well, it's fine, but contains some redundant explanations for the client.

I would like to create and send custom message in case of a `SerializationException`.

It's not possible because the `SerializationException` and **all it's inheritors** carry no meta-data except the full message.

**Describe the solution you'd like**

some of the exceptions are well defined by their main constructor parameters. Simply, the solution would be adding **`public val`** before those parameters.

For example,

```kotlin
// [message] is never null, so override it (decreases !! operator usage).
public open class SerializationException(override val message: String, cause: Throwable? = null) : RuntimeException(cause)

public class MissingFieldException(public val fieldName: String) :
    SerializationException("Field '$fieldName' is required, but it was missing")

...
```

Yet, some of the exception models are not good.

> E.g. `Json` contains only 2 exceptions, `JsonDecodingException` and `JsonEncodingException`, but has 5 builders with quite different parameters and messages.

The **general solution** would be to rework the exceptions and beside yielding a good message, it should carry some **useful meta-data** which can be used to rebuild the message, or create a new custom message.

**Comment by qwwdfsad** [comment]
Could you please elaborate on what exactly are you going to do with this meta-data? E.g. what's wrong with the current exception message?

We're trying to keep the number of public exceptions as small as possible to reduce the cognitive load and, especially, to keep the simplicity of writing custom serializer, so adding such exception (note: we should probably change all custom serializaers and add this exception to the guideline) requires a compelling use-case.

**Comment by Agcom** [comment]
@qwwdfsad. Right. I read the new documentations on the `SerializationException` class, and now it makes more sense.

> Also, saw the `JsonException` that is now declared as internal.

Yet, for **being sure**, a question remains for me.

In my use case, I was trying to inform the end-user (client) about the **exact** problem his / her input had (if any).

> But, the message yielded from a `SerializationException` contains redundant information for the end-user.
>
> For example they contain a hint about `JsonConfiguration` and the Json input string itself, which are not useful for the end-user or may even confuse him/her.
>
> So, I was trying to build a new message based on the exception's type and its' meta-data.

But, let's *lower the expectations*. Now, I just want to response with `Bad input 400` and not the exact problem.

As I understood, the `SerializationException` is gonna be thrown **only** when,

- A serializer does not support specific structure
- An invalid input

So, assuming that the serializers are healthy and tested, is it **completely safe** to response with `Bad input 400` in case of a `SerializationException`?

> Of course, the `try / catch` block will be around the code that decodes the input.

**Comment by qwwdfsad** [comment]
>is it completely safe to response with Bad input 400 in case of a SerializationException?

Yes, this exception indicates either issue with the input or with the serializer (unsupported type, missing contextual serializer etc.)
