### ISSUE TITLE
(Json) Option to remove quotes from field names in Json

### ISSUE THREAD

**Issue by fraccy** [Kotlin/kotlinx.serialization#979]
I am generating html and json mixed with js from kotlin. I use kotlinx-html for the html, and presently use jackson to generate json that is included as part of accompanying js. In order to do this, I require the option "QUOTE_FIELD_NAMES" to be set to false on jackson.

[See here in the jackson docs](https://fasterxml.github.io/jackson-core/javadoc/2.10/com/fasterxml/jackson/core/json/JsonWriteFeature.html#QUOTE_FIELD_NAMES)

> Feature that determines whether JSON Object field names are quoted using double-quotes, as specified by JSON specification or not. Ability to disable quoting was added to support use cases where they are not usually expected, which most commonly occurs when used straight from Javascript. 

I have recently switched wholesale to kotlinx serialization across a large a project. This is the only feature preventing me removing the jackson dependency.

I realise this is not part of the Json spec, but could this be added to the Json encoder?

**Comment by elizarov** [comment]
But why you need it presented without quotes? Why does your use-cases call for such a non-standard representation?

**Comment by fraccy** [comment]
That was a very good question. The honest answer appears to be that it was because of a misconception dating back years which got written into a system, that I've then come to at a later date with the mission of "replace jackson with kotlinx serialization". In not wanting to disturb the original intent I hadn't questioned it. On closer inspection there appears to be no decent reason to strip the quotes beyond shortening the output. Thanks for your help :)
