### ISSUE TITLE
Can I use kotlinx.serialization in Android project with Android Studio?

### ISSUE THREAD

**Issue by wudizhuo** [Kotlin/kotlinx.serialization#98]
Hi, Can I use kotlinx.serialization in Android project with Android Studio? 
The IDE plugin is for IntelliJ that can't use in Android Studio, it will show error "kotlin serialization-plugin plugin incompatible", Can I find the plugin for Android Studio? thank you.

**Comment by sandwwraith** [comment]
Current build of plugin works only with intellij IDEA, there are no build for AS available yet.
As far as I know, Android Studio uses gradle build by default, so if you have applied plugin in yours `build.gradle` file and OK with small amount of red code in IDE, it will work fine

**Comment by jitinsharma** [comment]
I was able to use it in Android Studio by following instructions written in README.md
Didn't face any issue

**Comment by pablogeek** [comment]
this is happening to me. How did you fix the issue?  @wudizhuo

**Comment by zhuosun-rally** [comment]
@pablogeek the plugin is not necessary, you can directly use the library without the plugin. I think the plugin is for IDE does not show red error line.

**Comment by sandwwraith** [comment]
@zhuosun-rally @pablogeek plugin for Gradle is important though

**Comment by sandwwraith** [comment]
Should be bundled now.
