### ISSUE TITLE
Extract Json from `core` artifact to own library

### ISSUE THREAD

**Issue by gildor** [Kotlin/kotlinx.serialization#994]
Eventually, all other formats were moved to own dependencies and now `core` (ex `runtime`) includes only  Json

I propose to extract json to own library and keep `core` (or again, rename it back to `runtime`) format-agnostic.

I think it would provide such benefits as:
- `Core` of kotlinx.serialization would be format agnostic and include only minimal API
- Allow to replace Json implementation (use own fork, or even separate release cycle of core from json)
- Less bytecode on runtime if json is not used
- It would be always explicit operation by adding additional serialization formats to your project (or even one of modules)

Even if json is the most popular format, it's still not clear why core should include it, having special artifact `kotlinx-serialization-json` would be even more clear, because now if you check maven repo you can find other formats, but not Json, only some abstract `core` artifact

I think it should be considered before release of 1.0.0

Original discussion in Kotlin Slack: https://kotlinlang.slack.com/archives/C7A1U5PTM/p1597737420036300

**Comment by qwwdfsad** [comment]
We've decided to fix it in RC2, thanks for the feedback!
