### ISSUE TITLE
Expose JsonLiteral.body for proper handling of different types

### ISSUE THREAD

**Issue by eygraber** [Kotlin/kotlinx.serialization#998]
**What is your use-case and why do you need this feature?**

I recently wrote code that compares values of two different JsonLiterals. I can't just do a string comparison, because it depends on what the types are. After updating to 1.0.0 RC I can no longer do this:

```
private operator fun JsonPrimitive.compareTo(other: JsonPrimitive) =
      when {
        this is JsonNull || other is JsonNull -> when(this) {
          other -> 0
          is JsonNull -> -1
          else -> 1
        }

        else -> when(val body = body) {
          is String -> when(val otherBody = other.body) {
            is String -> // string comparison
            else -> -1
          }

          is Number -> when(val otherBody = other.body) {
            is Number -> // number comparison
            else -> -1
          }

          is Boolean -> when(val otherBody = other.body) {
            is Boolean -> // boolean comparison
            else -> -1
          }

          else -> -1
        }
      }
```

**Describe the solution you'd like**

Expose `body` or provide a property that says what type the JsonPrimitive is.

**Comment by altavir** [comment]
I've encountered a similar problem. I am transforming a Json structure into inner structure and before 1.0 I used `when` over different literal types. Now I need to parse a string and it looks wrong since I have number->string->number or boolean->string->boolean conversion which will impact the performance.

**Comment by qwwdfsad** [comment]
Also: https://kotlinlang.slack.com/archives/C7A1U5PTM/p1599855781105000

**Comment by qwwdfsad** [comment]
`body` is how it is stored internally and should not actually affect user-facing API. 
Could you please elaborate on why `content` + `isString` flag is not enough for your comparisons and/or transformations?

With `body` exposed, especially with `Any` type, it starts to behave weirdly when equal `Float` and `Double` are passed to the constructor, or `Int` and `Long`. And these problems become vague and fickle bugs depending on **how exactly** you have constructed your `JsonPrimitive` from **the same data**. 
Things become even more complex when you know that there are no "typed numbers" in JSON.
To avoid situations like `json.decodeFromString("42") != JsonPrimitive(42L)` we've decided to remove `body` completely and left only types provided by JSON
